### ISSUE TITLE
Make docker image public

### ISSUE THREAD

**Issue by discordianfish** [aws/amazon-vpc-cni-k8s#100]
Hi,

I'm running my own cluster on AWS and would love to use this as my networking. When trying out the manifest I realize the image it uses (`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.0.0`) is private. Can you make this public? Or is this intentionally not provided and something I need to buld myself?

**Comment by mattlandis** [comment]
The image is publicly readable.  What region are the instances in that you are trying to pull it to?  If the `ecr get-login` it needs to be for `us-west-2` for this image (it is also hosted in `us-east-1` if you change the region in the ecr url).  It will be hosted in new regions as EKS becomes available in those regions.

**Comment by discordianfish** [comment]
Ah, okay I didn't know that I'd still need to use `ecr get-login` for public images. It's not working though. I'm running kubernetes 1.10 in us-east-1 and even after changing the region to us-east-1 I still get:

```
  Normal   Pulling                44s (x3 over 1m)  kubelet, ip-172-20-182-225.ec2.internal  pulling image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.0.0"
  Warning  Failed                 44s (x3 over 1m)  kubelet, ip-172-20-182-225.ec2.internal  Failed to pull image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.0.0": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-east-1.amazonaws.com/v2/amazon-k8s-cni/manifests/1.0.0: no basic auth credentials
```

I'm using ECR for our internal images and therefor already pass in instance profiles. Need to check if that maybe prevents me from pulling the public images..

**Comment by discordianfish** [comment]
I've fixed this, my problem was the missing ECR permissions which I only granted to my prod cluster no this test one. Sorry for the noise!
