### ISSUE TITLE
Make AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng the default

### ISSUE THREAD

**Issue by adri** [aws/amazon-vpc-cni-k8s#1040]
First of all, thanks for all the hard work you do on this project.

I think `AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng` should be the default, to avoid intermitted connection timeouts.

When moving from Kops to EKS, we noticed connection timeouts every "few minutes" to central services like Redis. Because we use PHP, which doesn't come with a connection pool built in, we create lots of connections at the same time. Here the symptom we saw in the logs (so PHP users can find this issue):
```
CRITICAL: Uncaught PHP Exception Uncaught PHP Exception RedisException: "Connection timed out" at srcKernelProdContainer.php line
```

[This blog post](https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02) from XING described the problem we’re seeing with a solution. [Another blog post](https://engineering.prezi.com/https-engineering-prezi-com-a-kubernetes-crime-story-2e8d75a77630) from Prezi translated the solution to AWS EKS. The fix was to set the config option `AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng` (see [docs](https://docs.aws.amazon.com/eks/latest/userguide/cni-env-vars.html)). After deploying this fix the symptom was gone.

What do you think? Is there any disadvantage to changing the default?

**Comment by mogren** [comment]
Thanks @adri, great question! The problem earlier was the old version of iptables that came with AL2, but since that issue has now been fixed, I don't see any reason we couldn't default to "random fully". Will investigate some first. 😄
