### ISSUE TITLE
Windows instances support

### ISSUE THREAD

**Issue by ArturChe** [aws/amazon-vpc-cni-k8s#1041]
Hi! I am wondering if this driver supports the Windows containers? Because now having an EKS cluster with both Linux and Windows nodes the new ENI attaches to Linux nodes automatically while adding pods. But on Windows instances, only primary ENI attached. And more pods trigger the cluster auto scaler to run new instance because of insufficient IP addresses.

**Comment by mogren** [comment]
Hi @ArturChe,
Currently Windows nodes only support using the primary ENI. Also, networking on Windows is using a different CNI, [vpc-shared-eni](https://github.com/aws/amazon-vpc-cni-plugins/tree/master/plugins/vpc-shared-eni) to be exact.

The effort to enable additional ENIs on Windows in tracked in https://github.com/aws/containers-roadmap/issues/802

**Comment by ArturChe** [comment]
Thanks!
