### ISSUE TITLE
Do not treat Watch GOAWAY as error

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1046]
a GOAWAY is not an error but the server telling the client that the connection has ended and should be retried

we alert on errors in cni and get tripped up by this false-positive, so it would be nice to change it to info

`aws-cni-2v94b aws-cni {"level":"ERROR","message":"Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=735, ErrCode=NO_ERROR, debug=""","pattern":"unknown"}`

**Comment by mogren** [comment]
This is related to the old version of client-go that we have, that gets pulled in by the v0.0.7 version of the operator-framework.

https://github.com/operator-framework/operator-sdk/issues/1282#issuecomment-481030678

This will be resolved once we update the framework.

**Comment by jayanthvn** [comment]
Operator-sdk dependency is removed -  https://github.com/aws/amazon-vpc-cni-k8s/pull/1419
