### ISSUE TITLE
Connection timeouts on ClusterIP service accessed over secondary ENI 

### ISSUE THREAD

**Issue by luke-richardson** [aws/amazon-vpc-cni-k8s#107]
We've been experiencing an issue where connection timeout intermittently to a ClusterIP service. The cluster is set up with kops, 3 masters and 3 nodes across 3 private subnets in a single existing VPC, running Kubernetes 1.9 and v1.0 of the aws cni.

The timeouts stop when I manually disable the source/destination check on secondary ENIs attached to the nodes. The primary ENIs attached to the nodes already have the source/destination check disabled, as its done by a controller deployed by kops ([ottoyiu/k8s-ec2-srcdst](https://github.com/ottoyiu/k8s-ec2-srcdst)). 

I noticed that the ENI attributes are not set to disable the check [here]( https://github.com/aws/amazon-vpc-cni-k8s/blob/16bf723dfe476184898f47d1dc97bfb0c4cb13d1/pkg/awsutils/awsutils.go#L551) after L-IPAM allocates a new ENI and modifies its attributes. It was my understanding that it shouldn't be required for secondary ENIs in this situation anyway, as there is no NAT involved in the connection, so possibly could be a mis-configuration in the cluster?

I haven't taken any tcdumps of the behaviour or run the support script, but am more than happy to if that would be helpful.

Thanks
Luke

**Comment by liwenwu-amazon** [comment]
Can you check if this is duplicate of https://github.com/kubernetes/kops/issues/4674#issuecomment-398380741?

thanks

**Comment by luke-richardson** [comment]
Oops, yes its a duplicate. kube-proxy and kube-controller-manager are being started with an incorrect cluster CIDR. Thanks for your help!
