### ISSUE TITLE
Upgrade eniconfigs.crd.k8s.amazonaws.com to apiextensions.k8s.io/v1 by k8s 1.22

### ISSUE THREAD

**Issue by TBBle** [aws/amazon-vpc-cni-k8s#1074]
Per https://github.com/kubernetes/kubernetes/issues/82022, the currently-used API version [`apiextensions.k8s.io/v1beta1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinition-v1beta1-apiextensions-k8s-io) will stop being served by default in k8s 1.22.

This is worth looking at sooner rather than later, as it's not a trivial change. [`apiextensions.k8s.io/v1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinition-v1-apiextensions-k8s-io) makes a [structural schema mandatory](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema), and [the current CRD definition](https://github.com/aws/amazon-vpc-cni-k8s/blob/afdb125d67eeed00a75433a14548a735430ab2d9/config/master/aws-k8s-cni.yaml#L36-L50) doesn't provide a schema at all.

I note that this might relate to #745, as the operator-sdk only gained support for generating v1 CRDs in [0.17.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.17.0), and they became the default in [0.18.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.18.0). That said, I'm not sure if that matters, or if the CRD can be manually updated despite the old operator-sdk.

**Comment by adawalli** [comment]
Any traction on this? I ran into this today when I realized that the current definition isn't compatible with Terraform's K8s Alpha plugin due to the lack of schema

**Comment by jayanthvn** [comment]
Hi @adawalli 

Yes we will look into it.

**Comment by jayanthvn** [comment]
There is already a PR #1390 and regarding the schema @achevuru can we see if can take it up as part of #1419?

**Comment by stevehipwell** [comment]
This should be easy enough to fix with an empty schema for ENIConfig v1alpha1 and then maybe an updated ENIConfig version with a typed schema in the future. I've add a https://github.com/aws/amazon-vpc-cni-k8s/pull/1390#issuecomment-876220253 to the PR with the simple addition required.
