### ISSUE TITLE
envLogLevel is not getting env var

### ISSUE THREAD

**Issue by wguto** [aws/amazon-vpc-cni-k8s#1089]
https://github.com/aws/amazon-vpc-cni-k8s/blob/d070fcae5ee2b2292ae7da9e0d2af75ae35e849b/pkg/utils/logger/config.go#L24

I am passing this ENV VAR to the deployment, I can see the env var is in the container and all but it is still spamming info logs of this exact line:

https://github.com/aws/amazon-vpc-cni-k8s/blob/d070fcae5ee2b2292ae7da9e0d2af75ae35e849b/cmd/cni-metrics-helper/main.go#L105

any reason why it is not loading the env var?
I added the deployment.yaml to my gist [here](https://gist.github.com/wguto/034a1fb5accc728dd7cfe244211f539b)

**Comment by mogren** [comment]
Hi @wguto!

This look like an issue with the log config for cni-metrics-helper. Thanks for reporting, we will fix it.

**Comment by mogren** [comment]
Added reading `AWS_VPC_K8S_CNI_LOGLEVEL` environment variable in the metrics helper in #1104.
