### ISSUE TITLE
Is the aws vpc cni intended to work only on EKS clusters ? I am not able to get pod - pod communication working at all

### ISSUE THREAD

**Issue by rakesh-nd** [aws/amazon-vpc-cni-k8s#1093]
I am currently running v.18.0 k8s cluster, self hosted on aws
I applied the yaml file from the documentation. Everything got applied properly.
Ip addresses are getting assigned properly to the Pods

But communication between the pods is not working. neither the pods are able to communicate to the internet. Can anyone please help me out with this ?

**Comment by mogren** [comment]
Hi @rakesh-nd,

Yes, we test the VPC CNI on Kops and Ubuntu as well. What base worker AMI are you using? What is needed is to allow forwarding on the worker nodes (iptables -P FORWARD ACCEPT). See #619 and https://github.com/awslabs/amazon-eks-ami/issues/332 for more details around this.

**Comment by mogren** [comment]
@rakesh-nd did allowing forward solve the issue for you?

**Comment by rakesh-nd** [comment]
@mogren thanks a lot! It is working now !
