### ISSUE TITLE
Missing documentation on how you should configure security groups?

### ISSUE THREAD

**Issue by mumoshu** [aws/amazon-vpc-cni-k8s#11]
If I understand it correctly, in order to allow Pod-to-Pod communication over IP addresses associated to secondary ENIs attached to master and worker nodes, you should configure security groups so that:

- One of your worker SGs associated to worker nodes allow ingress traffic on any port/protocol from other master and worker SGs
- Similarly, one of your master SGs associated to master nodes allow ingress traffic on any port/protocol from other master and worker SGs

Otherwise pods are unable to communicate with each other, right?

If so, could we add some note on README?

**Comment by mogren** [comment]
Documented for EKS.
