### ISSUE TITLE
Release v1.0.1 w/ Calico Manifest Changes

### ISSUE THREAD

**Issue by ozdanborne** [aws/amazon-vpc-cni-k8s#110]
Recently #99 was merged which changed the interface prefix from `cali` back to `eni`. This change is important as now Calico can be installed onto existing clusters without modification to the existing aws-node daemonset, in EKS for example.

I'm requesting a point release of this repo so that there is a static link to the new version of that calico manifest.

I raised a PR to address the EKS docs side of the change over here: https://github.com/awsdocs/amazon-eks-user-guide/pull/9
But it was merged without answering any of my questions, so I figured I'd propose a new solution here.

Thanks!

**Comment by liwenwu-amazon** [comment]
I am closing this issue. Please re-open it if you still have problems
