### ISSUE TITLE
Make errors (more) actionable: "add cmd: failed to assign an IP address to container"

### ISSUE THREAD

**Issue by discordianfish** [aws/amazon-vpc-cni-k8s#111]
Hi,

I've got some pods in this state and while I'm investigating right now the root cause, I'd wish this error would be more actionable. What failed that made it impossible to assign an IP address? Was some pool exhausted? Some syscall failed? Some api call failed?

**Comment by liwenwu-amazon** [comment]
@discordianfish ipamD as described in the [proposal-design](https://github.com/aws/amazon-vpc-cni-k8s/issues/111) is responsible assigning IP address to a Pod.  /var/log/aws-routed-eni/ipamd.log.xxxx contains more detail why it failed on IP address assignment.

[troubleshooting CNI](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md) provides tips on how to avoid IP address assignment failure.

**Comment by mogren** [comment]
Logging has been improved
