### ISSUE TITLE
pod stuck at container creating 

### ISSUE THREAD

**Issue by nandeeshb09** [aws/amazon-vpc-cni-k8s#1112]
We are facing this were pods are stuck at container creating and recently we upgraded EKS cluster to 1.14.9 and CNI version 1.6.1.

For this issue , we tried to restarting the kubelet and docker ,but did not help.

Below are the logs from pod.

E0730 06:31:07.110332    4737 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "schd-scdf-apn-site-domain-report-1596089220-p6brw": operation timeout: context deadline exceeded
Jul 30 06:31:07  kubelet[4737]: E0730 06:31:07.110385    4737 remote_runtime.go:109] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod ": operation timeout: context deadline exceeded

Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "pod-name": operation timeout: context deadline exceeded
  Warning  FailedSync     115s (x21 over 6m19s)  kubelet, error determining status: rpc error: code = Unknown desc = Error: No such container: 

Is there any issue workaround for this.

**Comment by mogren** [comment]
Hi @nandeeshb09,

Is it possible that you have run out of IPs in the subnet, or reached an ENI limit? If you could run `sudo /opt/cni/bin/aws-cni-support.sh` on the node and send the log files that would help us debugging the issue. Also, see [troubleshooting.md](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md) for some tips on how to debug issues.

**Comment by mogren** [comment]
@nandeeshb09 Did you manage to resolve this issue?

**Comment by mogren** [comment]
@nandeeshb09 Please reopen if you are still seeing this issue and have logs we can use for debugging.

**Comment by DekusDenial** [comment]
@mogren I am also seeing this especially when there's a surge of pods scheduled onto the same node. Though, it's rather intermittent. Don't think there was any memory/disk pressure but CPU usage definitely hyped up. I will create a new issue with supporting logs when this happens again.
