### ISSUE TITLE
Failed to pull image, "no basic auth credentials"

### ISSUE THREAD

**Issue by xrl** [aws/amazon-vpc-cni-k8s#1117]
Using the docker image URI from the aws-node.yaml, I can't pull the CNI right now because of an auth failure:

```
# docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.3
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.6.3: no basic auth credentials
```

**Comment by kishorj** [comment]
To get the docker credentials
$(aws ecr get-login --no-include-email --registry-ids 602401143452)

If you are using EC2 for non-EKS k8s, please refer to the similar issue https://github.com/aws/amazon-vpc-cni-k8s/issues/708

**Comment by mogren** [comment]
@xrl Did you get the image pull to work?

**Comment by xrl** [comment]
Turns out we had some systemic networking issues. Thanks!
