### ISSUE TITLE
Ensure prometheus metrics are bounded

### ISSUE THREAD

**Issue by discordianfish** [aws/amazon-vpc-cni-k8s#112]
Prometheus' design causes it to create a new timeseries for each unique combination of key-value label pairs:

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

- https://prometheus.io/docs/practices/naming/#labels

But aws-vpc-cni-k8s sets the full error message in the `ipamd_error_count` metric, e.g:
```
ipamd_error_count{error="datastore: IP is used and can not be deleted",fn="ipReconcileDel",instance="172.20.137.118:61678",job="kubernetes-service-endpoints",k8s_app="aws-node",kubernetes_name="aws-node-prometheus-discovery",kubernetes_namespace="kube-system"}	2
ipamd_error_count{error="get attached enis: failed to retrieve eni metadata for eni: 0a:75:6b:ea:20:a0/: get eni metadata: failed to retrieve device and eni from metadata service: 0a:75:6b:ea:20:a0: failed to retrieve device-number for eni 0a:75:6b:ea:20:a0: EC2MetadataError: failed to make EC2Metadata request caused by: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>404 - Not Found</title> </head> <body> <h1>404 - Not Found</h1> </body> </html> ",fn="reconcileFailedGetENIs",instance="172.20.137.118:61678",job="kubernetes-service-endpoints",k8s_app="aws-node",kubernetes_name="aws-node-prometheus-discovery",kubernetes_namespace="kube-system"}	17
```

This can quickly overwealm the Prometheus server as well as cause aws-vpc-cni-k8s to run out of memory since each timeseries's local representation will stay in memory indefinitely (by default usage of the prometheus client library)

**Comment by bboreham** [comment]
Just came across this - the error is here: https://github.com/aws/amazon-vpc-cni-k8s/blob/b68da3905f3d526a4402a0f3d38eeab0ed10548c/ipamd/ipamd.go#L810

```
ipamd_error_count{error=\"allocate eni: failed to create eni: failed to create network interface: InvalidSecurityGroupID.NotFound: The securityGroup ID 'sg-0d5c12ebredacted' does not exist\n\tstatus code: 400, request id: 05efdaad-redacted\",fn=\"increaseIPPoolAllocENI\",instance=\"192.168.31.163:61678\",job=\"kubernetes-pods\",kubernetes_namespace=\"kube-system\",kubernetes_pod_name=\"aws-node-rdss4\"}"
```

Have a customer with > 100,000 of those in one process.
