### ISSUE TITLE
Add delete timestamp to the ipamd.json file

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#1127]
Currently during pod churn and ipamd restarts, we can run into a scenario where a terminating pod and a new pod can get same IP address since the cool down cache will be cleared because of the restart. To address this issue, we can store the delete TS in ipamd.json added with this PR #972  and when IPAMD restarts we can rebuild the cool down cache to prevent the same IP being assigned to deleting and creating pod.

**Comment by anguslees** [comment]
Alternate solution: Just sleep for a while during startup (if the state file already exists) :)

**Comment by mogren** [comment]
Waiting a few seconds after starting up before assigning IPs sounds like a simpler solution, but it will delay pod starts for a while just after restarting. (Still better than seeing duplicate IPs because of the eventual consistency of the API Server.)

**Comment by jayanthvn** [comment]
Yeah this looks simpler. I can try this out.

**Comment by mogren** [comment]
The wait should only be needed if there are pods on the node, except for the case where the last pod was just deleted when ipamd restarted and is still showing up in the API server response....

**Comment by jayanthvn** [comment]
Since we are relying only on cri or the file, rebuilding the cool down cache seems to be better right?

**Comment by anguslees** [comment]
Where do we stand on this?  With the other recent discoveries/fixes, do we still think there's a need to extend the cooldown?

**Comment by mogren** [comment]
I think we can wait with this until we have verified that duplicate IPs can still be caused of this. I think the main issue has been the racy rebuilding of state in ipamd. 

The cooldown might help to avoid issues where kube-proxy doesn't update endpoints fast enough when a new pod gets a recently terminated pod's IP.

**Comment by jayanthvn** [comment]
I will open a PR for this but we might still hit duplicate IP if we are out of cooldown period and the pod is stuck in termination (#1091)

**Comment by jayanthvn** [comment]
This is a very corner case, I will re-evaluate this once we remove the cri read.
