### ISSUE TITLE
Add cni-metrics-helper's source code

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/amazon-vpc-cni-k8s#113]
[troubleshooting guide](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md), demonstrates how to use cni-metrics-helper to troubleshoot CNI issue on the cluster level.

This issue is for the effort of putting  source code of cni-metrics-helper code into this repo.

**Comment by jicowan** [comment]
The link https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/misc/cni_metrics_helper.yaml returns a 404 error.

**Comment by lswith** [comment]
It needs to be updated to this: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/cni_metrics_helper.yaml

**Comment by giorgiosironi** [comment]
Interesting, is `cni-metrics-helper` closed source at the moment? The [blog post](https://aws.amazon.com/blogs/opensource/cni-metrics-helper/) says it should serve as an example on how to extract metrics from a node, but without source code it's difficult to understand what it does.

**Comment by groodt** [comment]
I would also like this 👍

**Comment by jicowan** [comment]
https://github.com/liwenwu-amazon/amazon-vpc-cni-k8s-1/blob/metrics1/cni-metrics-helper/cni-metrics-helper.go

**Comment by groodt** [comment]
Thanks @jicowan 

I've taken a look at the code and I still have a question. Do you have any insights into this issue: https://github.com/aws/amazon-vpc-cni-k8s/issues/313

Essentially, I am wondering if there is a way to get the metrics tagged with a more descriptive cluster name.

**Comment by jicowan** [comment]
Hi @groodt, I don't actually see where the Cluster ID is being set.  Perhaps it's getting it from the kube client.

**Comment by groodt** [comment]
@jicowan 

Yes, it's an odd one. I don't know enough about Go or Cloudwatch to know what's going on. It seems a bit of a limitation if it can't support multiple clusters though.

**Comment by mogren** [comment]
Code added, v1.4.0 available.
