### ISSUE TITLE
Ability to configure secondary IP preallocation 

### ISSUE THREAD

**Issue by cnidus** [aws/amazon-vpc-cni-k8s#114]
EKS preallocates the max # of IPs that a given instance supports. This pre-warms and allows for fast pod spinup. However, it leads to over allocation of IPs and in some cases IP exhaustion of a given VPC / subnet.

In extreme examples, where a node always hosts a single pod, there could be upwards for 50 IPs wasted on each host.

Suggestion is for the IP pre-warming to be a configurable value.

**Comment by liwenwu-amazon** [comment]
#119 propose to have a configuration option to use different subnet for Pods than worker node's subnet. This can also help to prevent IP exhaustion of node's subnet.

**Comment by liwenwu-amazon** [comment]
This has been addressed with release 1.1.0.   Please refer https://aws.amazon.com/blogs/opensource/vpc-cni-plugin-v1-1-available/ for the details.
