### ISSUE TITLE
Max ip address for different type of instance

### ISSUE THREAD

**Issue by DafuSHI** [aws/amazon-vpc-cni-k8s#115]
In the main page it showed:

It is also recommended to set --max-pods equal to the number of ENIs for the instance type * (the number of IPs per ENI - 1)

While in the default cf template when adding nodes, the mapping showed:

Mappings:
  MaxPodsPerNode:
    c4.large:
      MaxPods: 29
    c4.xlarge:
      MaxPods: 58
    c4.2xlarge:
      MaxPods: 58
    c4.4xlarge:
      MaxPods: 234
    c4.8xlarge:
      MaxPods: 234
    c5.large:
      MaxPods: 29
............

It seems the two are not relevant.

**Comment by ashishgore** [comment]
Fixed #139

**Comment by liwenwu-amazon** [comment]
I am closing this issue. Please re-open it if you still have questions.
