### ISSUE TITLE
Metrics to cloudwatch without VPC endpoint

### ISSUE THREAD

**Issue by SimplySeth** [aws/amazon-vpc-cni-k8s#1150]
Can the metrics be sent to CW via proxy ?
Our clusters are private only and I cannot send the metrics to the dashboard. 
Is VPC endpoint the only option?
Thanks.

**Comment by mogren** [comment]
Hi @SimplySeth,

The current cni-metrics-helper is very simple and just pushes metrics directly to Cloud Watch [using the default CloudWatch Client from the AWS SDK](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/publisher/publisher.go#L110). The closest related roadmap item is probably https://github.com/aws/containers-roadmap/issues/387.

Supporting a proxy would require some code changes in the current metrics helper.

**Comment by nithu0115** [comment]
@SimplySeth, the easiest way that I can think of here would be to create a ConfigMap and patch the CNI metric helper deployment pod with that configMap. This way, all the traffic leaving the pod(CNI metric helper pod) would use these proxy variable to reach CloudWatch endpoints. 

For similar setup, please refer to - https://aws.amazon.com/premiumsupport/knowledge-center/eks-http-proxy-configuration-automation/

**Comment by mogren** [comment]
@SimplySeth Did Nithish's reply answer your question?

**Comment by SimplySeth** [comment]
Yes. Thank you very much.
