### ISSUE TITLE
Bandwidth plugin is bundled, but not actually usable

### ISSUE THREAD

**Issue by ianhe8x** [aws/amazon-vpc-cni-k8s#1172]
I'm interested in using bandwidth plugin in our cluster since it has been bundled with the aws-vpc-cni, and tried to enable it manually.
Then an error occurred because aws-vpc-cni doesn't pass the pod's network interface to cni plugins.

**Comment by mogren** [comment]
Closing this issue in favor of #463

**Comment by jayanthvn** [comment]
Currently this is blocked on containerd/cri#1544
