### ISSUE TITLE
Only add node label to enable trunk creation when there is room for a new ENI, even if ENABLE_POD_ENI=true

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#1202]
**What would you like to be added**:

When `ENABLE_POD_ENI=true`, we always add the `vpc.amazonaws.com/has-trunk-attached=false` signaling that for a 1.17 eks.3 EKS cluster or later, an additional ENI should get attached. If the maximum number of ENIs are already attached, (or if MAX_ENI=1), we should not set the label.

**Why is this needed**:

We should only set the label to attach an additional ENI when we have room for it to avoid potential issues.

**Comment by SaranBalaji90** [comment]
Can we make the ipamd to add the label only when trunk ENI can be created? Then we can mitigate this problem

**Comment by mogren** [comment]
Sounds good. I can rename this issue.

**Comment by mogren** [comment]
Fix merged.
