### ISSUE TITLE
Few regular pods were stuck in container creating after enabling ENABLE_POD_ENI

### ISSUE THREAD

**Issue by SaranBalaji90** [aws/amazon-vpc-cni-k8s#1203]
**What happened**:
If `ENABLE_POD_ENI` is set to true, ipamd will reserve one ENI slot for the trunk interface. If for some reason the trunk interface creation fails, ipamd will not be able to attach expected number of ENIs, so the total number of IPs available for regular pods will be reduced by a full ENI worth of secondary IPs.

**How to reproduce it (as minimally and precisely as possible)**:
Removing the VPCResourceController policy from the cluster role and enabling ENABLE_POD_ENI, will result in this issue.

**Anything else we need to know?**:
As a workaround, I had to recycle the node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- CNI Version 1.7.2
- OS (e.g: `cat /etc/os-release`): linux
- Kernel (e.g. `uname -a`):

**Comment by mogren** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/pull/1210  makes sure there is room for the Trunk-ENI
