### ISSUE TITLE
No release-1.7.1 branch?

### ISSUE THREAD

**Issue by rehevkor5** [aws/amazon-vpc-cni-k8s#1206]
**What happened**:

Cannot specify "1.7.1" version in URL for aws-k8s-cni.yaml file as mentioned in table on https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html Previously, we'd specify the particular version in a URL template like so: `https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-{full version here}/config/v{major minor only here}/aws-k8s-cni.yaml`. However, due to the lack of a release-1.7.1 branch, which may or may not have been intentional, we can only specify the release-1.7 branch which presumably might result in the patch version being updated as new commits are added to that branch. Should a branch be present which incorporates the full version number or is this approach changing moving forward to prohibit referencing specific versions? Alternatively, should the instructions https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html be altered to specify use of a github tag based URL instead? Or to not specify a particular patch version of CNI plugin?

**Environment**:
- Kubernetes version (use `kubectl version`): updating to EKS 1.16
- CNI Version: updating to 1.7.1
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by fmunteanu** [comment]
We need 1.7.1 branch, please no not change the pull behavior. There is nothing to investigate, not having a specific `major.minor.patch` branch with a `IfNotPresent` policy will introduce the possibility to have old nodes running on CNI 1.7.1 while newly scaled nodes to have CNI 1.7.2, which could raise unexpected conflicts.

Solution: please create like you always did before.

**Comment by rehevkor5** [comment]
Pull policy is not relevant here, the version is controlled explicitly in the DaemonSet.

**Comment by mogren** [comment]
@rehevkor5 Yes, you are absolutely correct. We should rely on the tags instead, since creating "patch" branches was getting too messy. I'll make sure to update the docs ASAP!

**Comment by rehevkor5** [comment]
@mogren Ok, and if that is the case then should tags like "v1.6.3" be referring to release candidate versions like `v1.6.3-rc1` in https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.6.3/config/v1.6/aws-k8s-cni.yaml#L102 or is that a mistake?

**Comment by mogren** [comment]
@rehevkor5 You are right, we should definitely verify that all the tags are set correctly before updating the docs.

**Comment by mogren** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.3 now points to the correct commit. Also verified that all other tags back to v1.5.3 are pointing to the correct config files.

**Comment by jayanthvn** [comment]
Hi @rehevkor5 

Since @mogren verified the tags to be correct, we will be closing this issue. Please reopen it if you still see any issues.

Thanks.
