### ISSUE TITLE
Pods cannot reach VPC Resources and Internet when security groups are applied

### ISSUE THREAD

**Issue by mrbalkan** [aws/amazon-vpc-cni-k8s#1211]
**What happened**:

Hi, I deployed an EKS cluster (1.17) on 2 different private subnets. I also have 2 corresponding public subnets where my NAT GWs reside for Internet access through IGW. K8S API Endpoint is private, I am reaching through bastion. AWS Ingress controller is running on the cluster. Workers are deployed via AWS managed NodeGroup without Launch Template option.

 In a typical deployment, (2 Pods , fronted by an ALB Ingress), everything is working fine, Pods are reachable via the Ingress from ALB public DNS endpoints. Pods can also reach internal VPC resources such as PrivateLink endpoints.

To test the new Pod SecurityGroups feature, I created the namespace and applied all the required steps in the documentation. I then applied the very same deployment to this namespace. Ingress was created, Pods are created, Branch Network Interface (aws-k8s-branch-eni)is created with the pod IP address. I can see on the worker nodes has trunks attached.

```
[ec2-user@ip-192-168-2-244 ~]$ kubectl get nodes -o wide -l vpc.amazonaws.com/has-trunk-attached=true
NAME                           STATUS   ROLES    AGE   VERSION              INTERNAL-IP    EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME
ip-192-168-4-8.ec2.internal    Ready    <none>   12h   v1.17.9-eks-4c6976   192.168.4.8    <none>        Amazon Linux 2   4.14.193-149.317.amzn2.x86_64   docker://19.3.6
ip-192-168-5-30.ec2.internal   Ready    <none>   12h   v1.17.9-eks-4c6976   192.168.5.30   <none>        Amazon Linux 2   4.14.193-149.317.amzn2.x86_64   docker://19.3.6
```
I can reach the web application through the Internet.(via Ingress). However, Pods cannot egress to anywhere. Not to the Internet, privatelinks on the same VPC, nowhere. I allowed All Traffic 0.0.0.0/0 Inbound and Outbound on the Pod security group but no luck.

There's no Calico and Custom Networking configured in this cluster. Other Pods in other namespaces without the security group policies, are working as expected.

**Comment by SaranBalaji90** [comment]
@mrbalkan I'm guessing you allowed inbound access for pod security group in coreDNS security group as well (normally the one that is applied to worker node).

**Comment by mrbalkan** [comment]
@SaranBalaji90 no, as I allowed All Traffic from/to 0.0.0.0/0, Inbound and Outbound. Do I still need to add the Cluster security group as a second entry? I will try anyways, but if this is a requirement, please let me know.

**Comment by SaranBalaji90** [comment]
@mrbalkan reason being pods using security group should be able to reach coreDNS for dns resolution. Let us know if it resolves the issue, if so I think we have to update our docs to be more specific to help others as well.

**Comment by mogren** [comment]
@mrbalkan Can the pods with the security group policies talk to any of the regular pods? If you check the Inbound rules for the NodeGroupSecurityGroup used by the nodes, since it also gets applied to the regular pods, does it only allow traffic in from its own SG?

**Comment by mrbalkan** [comment]
@SaranBalaji90 adding the worker node sg id to the pod security policy as a second SG item fixed the problem. We need to update the docs as it blocks a lot of things. 
After @mogren 's comment, I checked my worker node's security group and saw that it's only allowing itself and the ingress. (I guess this entry was put there by the ingress controller)
Because we are associating our secure POD with the worker node security group, it becomes a part of it, therefore talk to every pod (including CoreDNS), freely, on all ports. Is that right?

**Comment by mrbalkan** [comment]
This may bring a security risk. With the security group workaround, if another POD in another namespace references the same worker node security group, they all become a part of the same network? I confirm that I can ping another pod in another namespace.

**Comment by SaranBalaji90** [comment]
@mrbalkan Thanks for your feedback. We will update our docs to mention that coreDNS should allow inbound from security groups used by pods. 

Regarding your security risk, I'm not sure if I understand the issue properly. Lets say pod in ns A is using SecurityGroup A and pod in ns B is using SecurityGroup B. For CoreDNS to work, we have to allow SecurityGroup A and SecurityGroup B ingress on port 53 in worker node security group.

But I think you added Worker node sec group to Security group A itself which will allow everything to communicate with each other.

**Comment by mrbalkan** [comment]
@SaranBalaji90 , here is what I tried:

Try 1: I tried adding the Pod security group to the list of Worker Node's security groups -- Did not work
Try 2: I changed the Worker Node's security group policy and added a rule ALLOW All TCP from POD's security Group  -- Did not work
Try 3: I changed the K8s security policy and added the Worker Node Security group (like below) to the security groups array -- Worked

```
    groupIds:
      - sg-0556ae2f82a8217e5
      - sg-09bead8e8ca0f5913
```

I don't understand why tries 1 and 2 is not working. The last one works because it associates the pods with the Worker Node Security Group (which in my case allows full access to itself). However, it also
creates a "bridge" between the namespaces according to my tests. The last item is also mentioned in the blog post. Blog post states the following:

> The first security group we want to apply is the EKS cluster security group, which enables the matched pods launched onto branch network interfaces to communicate with other pods in the cluster such as CoreDNS.

However, when you include the Pod into the security group of the cluster, and you do the same for all other Pod security groups in other namespaces, that means they will Accept traffic from each other, if your Cluster/WorkerNode Security group trusts itself on All TCP traffic. [https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html](url)

You can test the same scenario. Just create 2 namespaces, 2 pods in it both have 2 security groups, One is their own, other is the Cluster (worker node) security group. They'll reach each other from their ENI(branch) IPs, although they are in different namespaces.

I wonder if this is the accepted behaviour that needs to be documented or a false configuration scenario which applies just to my environment. Thanks!

**Comment by SaranBalaji90** [comment]
@mrbalkan I'm sorry for going back and forth. `Try 2` should have worked with DNS(UDP) [ UDP Protocol with port number 53] 

If you would like we can jump on a call as well to resolve this. Try-1 should have worked as well in your setup based on what you have configured but both Try-1 and Try-3 will open up boarder access. 

@mikestef9 there are few things to be clarified in the doc,
1) Applying ClusterSecurityGroup to branch ENI pods is not required if your not expecting all pods to communicate with each other. 
2) Just allowing inbound from pod security groups for UDP on 53 should help with DNS queries.

**Comment by jayanthvn** [comment]
Documentation is updated.

**Comment by mnguyen96** [comment]
> Hi All, After implementing security groups for the pod, DNS queries are working but the internet is not working, Could you please assist on this.

did you ever resolve this?

**Comment by alanwu4321** [comment]
cannot access the internet either

**Comment by jdn5126** [comment]
@alanwu4321 please open a support case if you still need help in this area. This typically ends up being a security groups configuration issue
