### ISSUE TITLE
`no basic auth credentials` when pulling image

### ISSUE THREAD

**Issue by lexsys27** [aws/amazon-vpc-cni-k8s#1217]
**What happened**:

Cluster autoscaler added a node to the cluster. The node is in `NotReady` state.

In the `aws-node` logs I see an error message:

```
Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7": rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.5.7: no basic auth credentials
```

**What you expected to happen**:

I expected node to become `Ready`.

**How to reproduce it (as minimally and precisely as possible)**:

Log in to AWS and try to pull the image:

```
$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.5.7: no basic auth credentials
```

**Anything else we need to know?**:

Cluster scheduler and autoscaler add and delete nodes on a daily basis. This is the first time I see the error.

I am not aware of any IAM changes on our side today.

**Environment**:

- EKS 1.17
- CNI 1.5.7 (can't pull 1.6.3 too)
- Worker AMI `v20200904`.

**Comment by SaranBalaji90** [comment]
This doesn't seem to be CNI issue, rather kubelet not being able to pull docker image. Can you run the following command on your worker node and see if its able to pull the image?
```
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 602401143452.dkr.ecr.us-west-2.amazonaws.com
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
```

**Comment by lexsys27** [comment]
```
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::XXX:assumed-role/YYY/i-05a130fb357089f87 is not authorized to perform: ecr:GetAuthorizationToken on resource: * with an explicit deny
```

I am in `eu-west-2` so it doesn't look unusual. When login to the `eu-west-2`:

```
$ aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 602401143452.dkr.ecr.eu-west-2.amazonaws.com
WARNING! Your password will be stored unencrypted in /home/ec2-user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

I can't pull images from `us-west-2`:

```
$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.5.7: no basic auth credentials
```

But it looks like I can pull from `eu-west-2`:

```
$ docker pull 602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
v1.5.7: Pulling from amazon-k8s-cni
a7583ef20c9d: Pull complete
94f54669384b: Pull complete
bbe7c9232687: Pull complete
19470d5f8563: Pull complete
Digest: sha256:3fa028bb9f49192575011e61da5b411c439f9f45fa655423fde2b16b1e275a4e
Status: Downloaded newer image for 602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
602401143452.dkr.ecr.eu-west-2.amazonaws.com/amazon-k8s-cni:v1.5.7
```

Looks like something changed with the cross-regional authentication in AWS. Any ideas?

I will try to change the image in the manifest today and see if it helps get nodes running.

**Comment by lexsys27** [comment]
Can confirm that changing region in the CNI manifest to `eu-west-2` where the cluster is located has fixed the problem.

I have found the step in the EKS upgrade guide as well: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html Should re-read it the next time )

Maybe addition to documentation mentioning this error can show when pulling from a different region will be good? Otherwise, I am good with closing this issue.

**Comment by lexsys27** [comment]
@SaranBalaji90 thank you for help!

**Comment by groodt** [comment]
I'm seeing the same thing, but for us-east-1:
```
Get "https://602401143452.dkr.ecr.us-east-1.amazonaws.com/v2/amazon-k8s-cni-init/manifests/v1.7.2": no basic auth credentials
```

It seems weird to set it to eu-west-2 for everyone. Surely the image should be published to all regions and partitions?

**Comment by mogren** [comment]
@groodt yes, the image should be available in all regions. I just tried the same thing, first without authenticating:
```
> docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.7.2

Error response from daemon: Get https://602401143452.dkr.ecr.us-east-1.amazonaws.com/v2/amazon-k8s-cni-init/manifests/v1.7.2: no basic auth credentials
```
If I login to ECR:
```
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 602401143452.dkr.ecr.us-east-1.amazonaws.com

Login Succeeded

> docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.7.2

v1.7.2: Pulling from amazon-k8s-cni-init
Digest: sha256:0d8be70758145c3c20d2fafbb235d6d2ee1d4654fe38bf37407adf390a5c7549
Status: Downloaded newer image for 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.7.2
602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.7.2
```

The ECR login example: https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html#examples

**Comment by groodt** [comment]
Got it. Thanks. It is now working for me. I didn't login to that region. 👍

**Comment by fawadkhaliq** [comment]
Thanks for trying the correct login command and confirming it works for you. If there's anything else you need help with here, please feel free to reach out

**Comment by ZeroDeth** [comment]
> Can confirm that changing region in the CNI manifest to `eu-west-2` where the cluster is located has fixed the problem.
> 
> I have found the step in the EKS upgrade guide as well: https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html Should re-read it the next time )
> 
> Maybe addition to documentation mentioning this error can show when pulling from a different region will be good? Otherwise, I am good with closing this issue.

Thanks for working with EKS 1.21 and terraform-aws-eks-blueprints module

**Comment by vishwaratna** [comment]
When I do docker pull from my CMD I get no error
C:\Users\visratna\GolandProjects\testaws>docker pull 549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest
latest: Pulling from docker-gs-ping
Digest: sha256:2390145a17e7eb5030288176db605a393e4e606a259e943f47d10634ca5d2bd6
Status: Image is up to date for 549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest
549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest

But when I try to check my pods then they are in ImagepullBackOff Error.

I tried doing describe pods then I get below :

C:\Users\visratna\GolandProjects\testaws>kubectl describe pods
Name:             helloworld-7d48b5667c-7tlz7
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.4
Start Time:       Sun, 09 Jul 2023 14:32:27 +0530
Labels:           app=helloworld
                  pod-template-hash=7d48b5667c
Annotations:      <none>
Status:           Pending
IP:               10.1.0.42
IPs:
  IP:           10.1.0.42
Controlled By:  ReplicaSet/helloworld-7d48b5667c
Containers:
  new-cont:
    Container ID:
    Image:          549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m246c (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-m246c:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  5m6s                  default-scheduler  Successfully assigned default/helloworld-7d48b5667c-7tlz7 to docker-desktop
  Normal   Pulling    3m35s (x4 over 5m3s)  kubelet            Pulling image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest"
  Warning  Failed     3m33s (x4 over 5m2s)  kubelet            Failed to pull image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest": rpc error: code = Unknown desc = Error response from daemon: Head "https://549840312665.dkr.ecr.us-east-1.amazonaws.com/v2/docker-gs-ping/manifests/latest": no basic auth credentials
  Warning  Failed     3m33s (x4 over 5m2s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m11s (x6 over 5m2s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m57s (x7 over 5m2s)  kubelet            Back-off pulling image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest"


Name:             helloworld-7d48b5667c-g7tp9
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.4
Start Time:       Sun, 09 Jul 2023 14:32:17 +0530
Labels:           app=helloworld
                  pod-template-hash=7d48b5667c
Annotations:      <none>
Status:           Pending
IP:               10.1.0.41
IPs:
  IP:           10.1.0.41
Controlled By:  ReplicaSet/helloworld-7d48b5667c
Containers:
  new-cont:
    Container ID:
    Image:          549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4n9st (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-4n9st:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m16s                  default-scheduler  Successfully assigned default/helloworld-7d48b5667c-g7tp9 to docker-desktop
  Normal   Pulling    3m40s (x4 over 5m12s)  kubelet            Pulling image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest"
  Warning  Failed     3m38s (x4 over 5m11s)  kubelet            Failed to pull image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest": rpc error: code = Unknown desc = Error response from daemon: Head "https://549840312665.dkr.ecr.us-east-1.amazonaws.com/v2/docker-gs-ping/manifests/latest": no basic auth credentials
  Warning  Failed     3m38s (x4 over 5m11s)  kubelet            Error: ErrImagePull
  Warning  Failed     3m28s (x6 over 5m11s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    3s (x21 over 5m11s)    kubelet            Back-off pulling image "549840312665.dkr.ecr.us-east-1.amazonaws.com/docker-gs-ping:latest"


Can someone help??

**Comment by hendisantika** [comment]
When I run 
```
docker run -d --rm --name container-name -p 9102:9102 267023985100.dkr.ecr.ap-southeast-1.amazonaws.com/container-name:55
```
on VPS it is working well.

But, When I run same command using bash script via GitHub Action. It always said:
```
err: Error response from daemon: Head "https://***/v2/***/manifests/55": no basic auth credentials
err: Unable to find image '***/***:55' locally
err: docker: Error response from daemon: Head "https://***/v2/***/manifests/55": no basic auth credentials.
err: See 'docker run --help'.
2024/05/30 13:22:49 Process exited with status 125
```

Any suggestions?

Here is my shell script:
```
#!/bin/bash

start=$(date +"%s")
#aws ecr get-login-password | docker login --username AWS --password-stdin "${AWS_ECR_REGISTRY}"
aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${AWS_ECR_REGISTRY}"
#ssh -p "${SERVER_PORT}" "${SERVER_USERNAME}"@"${SERVER_HOST}" -i key.txt -t -t -o StrictHostKeyChecking=no << 'ENDSSH'
#ssh "${SERVER_USERNAME}"@"${SERVER_HOST}":"${SERVER_PORT}" -i key.txt -t -t -o StrictHostKeyChecking=no << 'ENDSSH'
docker pull ${AWS_ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

CONTAINER_NAME=mhdc-main
if [ "$(docker ps -qa -f name=$CONTAINER_NAME)" ]; then
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo "Container is running -> stopping it..."
        docker stop $CONTAINER_NAME;
    fi
fi

docker run -d --rm -p 9102:9102 --name ${CONTAINER_NAME}  ${AWS_ECR_REGISTRY}/${ECR_REPOSITORY}:$I{MAGE_TAG}

exit
ENDSSH

if [ $? -eq 0 ]; then
  exit 0
else
  exit 1
fi

end=$(date +"%s")

diff=$(($end - $start))

echo "Deployed in : ${diff}s"
```

**Comment by orsenthil** [comment]
@hendisantika Commenting on closed issues is distracting, and this is is not related to VPC CNI. Please approach the right channel for help.
