### ISSUE TITLE
Arm64 multi-arch support and update documentation

### ISSUE THREAD

**Issue by scottmalkie** [aws/amazon-vpc-cni-k8s#1218]
**What happened**:
The calico.yaml [as referenced in the EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) fails on Arm64 nodes, as the quay.io images are not multi-arch, and there is no logic to determine the underlying architecture in the [yaml.](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/calico.yaml)

**What you expected to happen**:
The calico.yaml both in the repo and referenced in the docs would work on Arm64 nodes, now the EKS support for Graviton2 is GA, and calico itself works well on Arm64.

**How to reproduce it (as minimally and precisely as possible)**:
Create EKS cluster, create an Arm64-based managed node group, attempt to deploy Calico via the documentation.

**Anything else we need to know?**:
Happy to help fix if you'd like, it should be pretty simple to add os/arch selectors.
If this is going to be a while to fix, if the docs could be updated in the meantime so as not to cause customer distress.
Also as the [Stars Policy Demo is still not officially supported on Arm64](https://github.com/projectcalico/calico/issues/3717), please update the docs to mention that, for customers who are following the docs with Arm64 clusters.

There was a previous here: https://github.com/aws/amazon-vpc-cni-k8s/issues/1047, however it only covered the preview (and the official docs haven't been updated post-EKS Graviton2 GA)

**Comment by fawadkhaliq** [comment]
We should consolidate this YAML or have one source of truth for generating the Calico YAML (and others for that matter) and push to Helm charts. There's an Helm chart with the same content here: https://github.com/aws/eks-charts/tree/master/stable/aws-calico. I will sync up @jaypipes on how we can to manage these and report back

**Comment by mogren** [comment]
Also keep this issue in mind https://github.com/aws/amazon-vpc-cni-k8s/issues/876

**Comment by jayanthvn** [comment]
Hi @scottmalkie 

#1282 is merged which supports ARM and AMD. Will pick the fix in next release.

Thank you!
