### ISSUE TITLE
Add better error message indicate why cni ipamD is not starting

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/amazon-vpc-cni-k8s#122]
Today, in CNI daemonSet(aws-node) whenever ipamD restart,   it query kubernetes API server about Pods already running on the node.  If it can not reach kubernetes API server, ipamD will exit and you will see following logs in the /var/log/aws-routed-cni/ipamd.log.xxx

```
2018-07-02T15:00:33Z [INFO] Starting L-IPAMD 1.0.0 ...
2018-07-02T15:00:33Z [INFO] Testing communication with server

..
2018-07-02T15:00:33Z [INFO] Starting L-IPAMD 1.0.0 ...
2018-07-02T15:00:33Z [INFO] Testing communication with server

```

ipamD needs print out explicit error that it failed due to it can NOT communicate with API server.

To verify security groups are configured correctly between worker node and kubernetes API server, you can run following commands:
```
# find out kubernetes service IP
kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.100.0.1   <none>        443/TCP   24d

#verify  worker node can reach port 443 of master 
telnet 10.100.0.1 443
Trying 10.100.0.1...
Connected to 10.100.0.1.
Escape character is '^]'.
```

**Comment by kuroneko25** [comment]
I think we are also running into this issue and maybe this one #104. But I don't believe it's because of security groups. I suspect it has something to do with service accounts or RBAC but right now it's extremely difficult to tell what the actual failure is since there is nothing in `ipamd.log` or the container log to help us debug. 

All I'm seeing is the crash loop output you mentioned above and this single line in the container log:

`ERROR: logging before flag.Parse: W0615 02:36:27.560592       9 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.` 

which is probably expected since you are invoking `clientcmd.BuildConfigFromFlags` but not explicitly setting `apiserver` or `kubeconfig`.

**Comment by liwenwu-amazon** [comment]
@kuroneko25 , is this a EKS cluster?

**Comment by kuroneko25** [comment]
Yes.

**Comment by liwenwu-amazon** [comment]
on your worker node, are you able to get 443 port of master.  What's the output of  on your worker node
```
telnet 10.100.0.1 443
```

**Comment by kuroneko25** [comment]
Should I try with the real master IP or in cluster VIP?

**Comment by liwenwu-amazon** [comment]
cluster VIP.  the output for 
```
kubectl get svc kubernetes
```

**Comment by kuroneko25** [comment]
Running this on my worker node (on the host VM not from any containers):
```
telnet 172.20.0.1 443
Trying 172.20.0.1...
```
Seems to just hang.

**Comment by liwenwu-amazon** [comment]
what's the output of your 
```
kubectl get svc kubernetes
```
In default EKS cluster, the kubernet VIP is 10.100.0.1

**Comment by kuroneko25** [comment]
`172.20.0.1`

**Comment by liwenwu-amazon** [comment]
i think you are running security groups issue.  In another word,  your worker node can NOT reach API server. 172.20.0.1  on port 443.

**Comment by liwenwu-amazon** [comment]
@kuroneko25  the specific security group used for creating eks cluster, which is also returned from:
```
aws eks describe-cluster --name <your cluster>
```
It needs to have port 443 open on the inbound rule

**Comment by kuroneko25** [comment]
I think we figured out the issue in our SG configuration. Thanks for the help!

**Comment by hobbsh** [comment]
@kuroneko25 Do you mind sharing the solution? I am seeing a similar problem.

**Comment by cjbottaro** [comment]
@liwenwu-amazon One of my nodes can connect to the API server fine, and the other can't. How can I debug this?

```
admin@ip-10-3-18-165:~$ telnet 10.3.0.1 443
Trying 10.3.0.1...
Connected to 10.3.0.1.
Escape character is '^]'.
```

```
admin@ip-10-3-18-164:~$ telnet 10.0.0.1 443
Trying 10.0.0.1...
```

Both nodes come from the same kops instancegroup, so they both have the same security group.

Thanks for the help.

**Comment by liwenwu-amazon** [comment]
@cjbottaro are u using any HTTP_PROXY? check their setting

**Comment by cjbottaro** [comment]
It was all related to this for some reason: https://github.com/kubernetes/kops/issues/2189#issuecomment-395799809

Once I switched to the suggested image, all networking problems went away.

Thanks!
