### ISSUE TITLE
Include SNAT CIDR

### ISSUE THREAD

**Issue by tanguyfalconnet** [aws/amazon-vpc-cni-k8s#1224]
**What would you like to be added**:
We would like a new parameter for SNAT configuration : 'AWS_VPC_K8S_CNI_INCLUDE_SNAT_CIDRS'.

**Why is this needed**:
We are currently trying to avoid natting : with clusters greater than 100 nodes and a few thousand pods, our NAT tables are full. 
We want to use an overlapping subnet dedicated to pods to avoid beeing limited in IPs with `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG` feature. This overlapping subnet isn't routed in our VPN, and natting is necessary for that. 
All traffic to internet goes throught a NAT Gateway.

So, if we want to nat only vpn traffic, we have to list all "internet" cidrs and exclude them with  'AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS' which is really bad. A parameter 'AWS_VPC_K8S_CNI_INCLUDE_SNAT_CIDRS' would be much easier and cleaner.

**Comment by tanguyfalconnet** [comment]
I'm trying to do it by myself : https://github.com/aws/amazon-vpc-cni-k8s/compare/master...tanguyfalconnet:feat/include_snat_cidrs

**Comment by jayanthvn** [comment]
#1229 is pending review. Once it is reviewed will close this issue.
