### ISSUE TITLE
Scope down permissions for extensions

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#1232]
**What would you like to be added**:
Right now, the sample CNI config gives [list and watch permissions for all extensions](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.7.3/config/v1.7/aws-k8s-cni.yaml#L46-L52). We should scope this down to only the required resources.
```
- "apiGroups":
  - "extensions"
  "resources":
  - "*"
  "verbs":
  - "list"
  - "watch"
```

**Why is this needed**:
We should always avoid giving broader permissions than needed.

**Comment by aaronmell** [comment]
Any idea what the permissions should actually be?
