### ISSUE TITLE
Publish images to public repository

### ISSUE THREAD

**Issue by amdonov** [aws/amazon-vpc-cni-k8s#1233]
Would you consider pushing these images to Docker hub along with some of the other images that you make available there? We're not using ECR and found configuring our CI/CD processes to pull images from there to be a real hassle.

Thanks

**Comment by jayanthvn** [comment]
Hi @amdonov 

Thanks for your question. We will discuss internally and get back to you asap.

**Comment by jayanthvn** [comment]
Hi @amdonov , Can you please share what other images you are looking for along with CNI? What is the setup where you're trying to download images where ECR is not available? Also Docker hub has added limits of number of image pulls so we need to evaluate further on how we can enable this option. Until we have decision, please feel free to build/copy images over to your Docker hub account for your use. Thanks

**Comment by jayanthvn** [comment]
Hi @amdonov 

Currently we don't have plans to push the images to docker hub given the latest limits added for docker pulls. Kindly pull the image and push to your internal repo as a workaround. Will get back to you if there are any other alternate options.

Thank you.

**Comment by amdonov** [comment]
Thanks for considering the request.
