### ISSUE TITLE
Log to standard output by default

### ISSUE THREAD

**Issue by otterley** [aws/amazon-vpc-cni-k8s#1236]
By default, the VPC CNI pod logs most of its output to a file (by default, `/host/var/log/aws-routed-eni/ipamd.log`) instead of standard output.

This is atypical for containerized applications, which [idiomatically log to stdout](https://12factor.net/logs) so that those logs can be handled by out-of-band consumers. Since we're talking about Kubernetes here, if logs were sent to stdout, customers could view logs the K8S idiomatic way by simply running `kubectl [-n namespace] logs <pod-id>`.

Because we're not logging to stdout by default, customers need to know where that log file is, and have access to the host in order to view it. (And security-conscious customers may disallow host access.) We don't clearly document the log file's location, and in light of the K8S context, it's unlikely that customers are going to think to look for the logs on the host.

Here's an example of what one would see by running `kubectl logs <pod-id>` today if there were some required IAM permissions missing, causing crash loops:

```
Copying portmap binary ... Starting IPAM daemon in the background ... ok.
Checking for IPAM connectivity ...  failed.
Timed out waiting for IPAM daemon to start:
```

The logs that provide the real root cause are hiding in that log file.

All this is to suggest we ought to send all the logs to stdout by default. This will make troubleshooting much faster and idiomatic for our customers.

**Comment by jayanthvn** [comment]
Hi @otterley 

Thanks for the question. Today this is supported by setting `AWS_VPC_K8S_CNI_LOG_FILE` to `stdout`. So this will redirect the IPAMD logs to stdout instead of `/host/var/log/aws-routed-eni/ipamd.log`.

**Comment by otterley** [comment]
@jayanthvn Understood - this suggestion is to make it log to standard output by default, as opposed to burdening the customer with making a change.

**Comment by discordianfish** [comment]
I just tripped over this while debugging a vpc-cni-k8s failure. I'd suggest to log to stdout by default and simply change https://github.com/aws/amazon-vpc-cni-k8s/blob/6a15a84cae6576cba1c3302964431a26c435d07c/scripts/entrypoint.sh#L91 to /host/var/log/aws-routed-eni/ipamd.log. That way the log is still as the expected location and the error logging in the container logs work as well.
