### ISSUE TITLE
Migrating from Calico to Amazon VPC

### ISSUE THREAD

**Issue by igorvpcleao** [aws/amazon-vpc-cni-k8s#124]
Hi there,

I've been doing some PoCs in order to check if it's possible to change the CNI of a given Kubernetes cluster from Calico to _amazon-vpc-cni-k8s_ with 0 downtime. I've not been lucky so far. The best I could accomplish was obtaining a valid and stable cluster after killing all old pods (which used to have a different CIDR for their internal IPs). In the time between deploying _amazon-vpc-cni-k8s_ as CNI and assigning a new IP to old pods by deleting them, requests among services within the cluster were not stable.

Any ideas on that subject? Is that possible?

Thanks!

**Comment by liwenwu-amazon** [comment]
If 2 different worker nodes are in 2 different subnets, I think calico uses tunnel overlay for Pods communication.  If this is true, then a Pod from Amazon VPC CNI will not able to communicate to another Pod from Calico if their worker node are in different subnet.

**Comment by igorvpcleao** [comment]
Thanks, @liwenwu-amazon.

**Comment by liwenwu-amazon** [comment]
@igorvpcleao I am closing this one.   Please re-open it if you still think this is an issue.
