### ISSUE TITLE
Stop re-pulling images on every container start

### ISSUE THREAD

**Issue by anguslees** [aws/amazon-vpc-cni-k8s#1249]
https://github.com/aws/amazon-vpc-cni-k8s/blob/47f1bc4d818fac1ef1ad958a4bcba4954df09bae/config/master/manifests.jsonnet#L147

We set imagePullPolicy=Always in numerous places in our manifests, and have done so for a long time afaics.  This causes extra boot delay, load on ECR, and increases the chances of a runtime failure impacting existing nodes.

Can anyone think of a reason to keep doing this?  I think we should remove this line (and thus fall back to the usual k8s IfNotExists default)

**Comment by mogren** [comment]
I totally agree. Having this set is useful for testing, but it should be removed in our sample configs and in [eks-charts/stable/aws-vpc-cni](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni)

**Comment by nzoueidi** [comment]
> I totally agree. Having this set is useful for testing, but it should be removed in our sample configs and in [eks-charts/stable/aws-vpc-cni](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni)

I noticed that there is no issue in the eks-charts repository, so I have created it https://github.com/aws/eks-charts/issues/333

**Comment by jayanthvn** [comment]
Pending changes of #1285 to be merged. Will close this once the PR is merged.
