### ISSUE TITLE
aws-cni chaining with linkerd-cni from linkerd2

### ISSUE THREAD

**Issue by caleygoff-invitae** [aws/amazon-vpc-cni-k8s#1253]
I am curious if the aws-cni plugin allows for chaining with the linkerd2 linkerd-cni. I see a few issues open where this was allowed for the bandwidth plugin, and there is there is documentation out there with cilium and calico. Essentially I have been advised that if we can control the startup order of the cnis, where the aws-cni starts first and then the linkerd-cni ds starts afterwards, the linkerd service mesh will work with the network capabilities that aws-cni provides. 

I am not sure how to go about this with aws-cni, any thoughts or feedback will be appreciated

**Environment**:
- Kubernetes version (use `kubectl version`):1.17
- CNI Version: 1.6.1
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Hi @caleygoff-invitae 

We are currently blocked on supporting chaining for bandwidth plugin because of this - https://github.com/containerd/cri/issues/1544. I can explore if we have similar issues chaining with `linkerd-cni` and get back to you soon.

Thanks.

**Comment by caleygoff-invitae** [comment]
Many thanks @jayanthvn !!

**Comment by caleygoff-invitae** [comment]
So I installed 1.7.5 and I see this in the logs for aws-node, thoughts?

```
[12:39:18 caley.goff@cgoff-LVCF:~/work/invitae-kubernetes (linkerd-components %)]$ kubectl --context west -n kube-system logs -f pod/aws-node-jxz7c
{"level":"info","ts":"2020-10-13T17:39:13.379Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2020-10-13T17:39:13.400Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2020-10-13T17:39:13.401Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
ERROR: logging before flag.Parse: E1013 17:39:13.466806      10 memcache.go:147] couldn't get resource list for tap.linkerd.io/v1alpha1: the server is currently unable to handle the request
{"level":"info","ts":"2020-10-13T17:39:15.416Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2020-10-13T17:39:15.419Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2020-10-13T17:39:15.420Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

**Comment by kivagant-ba** [comment]
@jayanthvn, have you had a chance to test `amazon-vpc-cni` coupling with `linkerd-cni`? Any chance it would work?

**Comment by jayanthvn** [comment]
Hi @kivagant-ba 

Sorry haven't got a chance to check. I need to follow up on this - containerd/cri#1544. Since with chaining we had seen issue with containerd. Will look into it and update as soon as possible.

**Comment by jayanthvn** [comment]
Issue with bandwidth plugin chaining is fixed. You should be able to add linkerd as a chain and try it out. Please let us know if you see any issues.

**Comment by wmorgan** [comment]
Nice. Thanks @jayanthvn. @caleygoff-invitae I'd love to know if this now works for you.

**Comment by KIVagant** [comment]
@frimik , could you please share more details about the issues you have met?

**Comment by frimik** [comment]
@KIVagant Simply put - chaining aws+linkerd CNIs (out of the box) doesn't (didn't!) work properly.

I'm happy to report I'm now successfully able to run AWS CNI + Linkerd CNI (with my patch for the chaining script logic) and have now gotten rid of our custom aws-vpc-cni+linkerd-cni container.

Discussion and implementation of my final fix for linkerd2-cni:
https://github.com/linkerd/linkerd2/issues/2219#issuecomment-1170778317

And Matei David of Bouyant brought it in: https://github.com/linkerd/linkerd2/pull/8778

I'm using a linkerd edge helm chart with a specific build of the cni at version `edge-22.6.2` - then I patch the chaining script and mount it via a configmap volume mount. It seems there is not yet a new edge release cut yet. The latest one is `edge-22.6.2`. I suppose there will be a new one very soon as they usually release an edge every week which should include a functional version straight from the helm chart. Stay tuned.

https://gist.github.com/frimik/ec5c6280c274151bd601948657b6a0e4#file-linkerd2-cni-libsonnet-L19
