### ISSUE TITLE
IPAMD uses default HTTP Client with no timeout which can lead to stuck go routines

### ISSUE THREAD

**Issue by abhipth** [aws/amazon-vpc-cni-k8s#1256]
**What happened**:
If the EC2 API call fails for let's say ec2 service endpoint is not reachable then it's possible the request is stuck forever because there is no timeout in the http client used by IPAMD.

If we don't pass the client in [aws config](https://github.com/aws/aws-sdk-go/blob/master/aws/defaults/defaults.go#L59) it will use the default client
```
WithHTTPClient(http.DefaultClient).
```
The default client has [no timeout](https://github.com/golang/go/blob/master/src/net/http/client.go#L109)
```
var DefaultClient = &Client{}
```
With the default client the Timeout is 0 which means the client connection would never time out.

Since we are using a timeout of 0 if the ec2 service is not responding for some reason then the connection will never timeout and the go routine will remain stuck and no further reconciliation will be performed. 

This leads to new pods not getting IPv4 Addresses and the Pod will remain in ContainerCreating state till the aws-node is restarted to allow the connection to establish again.

**What you expected to happen**:
Expected behavior is to timeout the connection and keep on retrying.

**How to reproduce it (as minimally and precisely as possible)**:
The easiest way to reproduce is by creating a new faulty client in one of the ```DeallocIPAddresses``` method and use the client to make the EC2 API Call. After deleting pods as soon as the workflow is hit the go routine will hang forever given that we passed a non existent endpoint.
```
 // Create a client with wrong endpoint
 sess, err := session.NewSession(
     &aws.Config{Region: aws.String("us-west-2"),
         MaxRetries: aws.Int(15), Endpoint:aws.String("nonexistantsite.com")})
```

**Fix**
After performing the bench marking and finding out the appropriate value for timeout, introduce the timeout by using a non default HTTP client 
```
sess, err := session.NewSession(
	&aws.Config{Region: aws.String("us-west-2"),
		MaxRetries: aws.Int(15),
		HTTPClient: &http.Client{
			Timeout: time.Second * 5,
	}})
```
 
**How to see if you may have been impacted by the problem**
1. If you see the following errors ``` RequestError: send request failed\ncaused by: Post https://ec2.<local-region-name>.amazonaws.com/: dial tcp: i/o timeout"``` [Optional, but can indicate the problem]
2. If you still have remaining capacity on your ENI's and the go routine that adds the IP Address to the Data Store is stuck and not logging anything then it's possible you may be facing the issue.

**Temporary Workaround** 
Restarting the aws-node will allow the connection to be reestablished and the stuck pod getting the IP (Assuming the underlying problem that was causing the connection issue is resolved)

**Anything else we need to know?**:
Apart from the [EC2 Client](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/awsutils/awsutils.go#L334) used to Allocate/DeAllocate IPv4 Addresses we should probably remove the default client from all the places and introduce appropriate timeouts to prevent this from happening.

1. [Metrics Publisher](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/publisher/publisher.go#L110)
2. [EC2 Wrapper](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ec2wrapper/ec2wrapper.go#L41)
3. [Instance Metada Client](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ec2metadatawrapper/ec2metadatawrapper.go#L35)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- CNI Version: v1.6.3

**Comment by jayanthvn** [comment]
#1331 is merged so closing this issue.
