### ISSUE TITLE
A documentation error in docs/eni-and-ip-target.md

### ISSUE THREAD

**Issue by pseonghoon** [aws/amazon-vpc-cni-k8s#1261]
**What happened**:

In docs/eni-and-ip-target.md,  the values of  WARM_IP_TARGET (5) and MINIMUM_IP_TARGET (2)  in the second p3dn.24xlarge example seem incorrect. 

It makes the example confusing, especially because there is no explanation for the environment variables in this page.

**What you expected to happen**:
I think two values should be swapped as the following:
WARM_IP_TARGET = 2 , MINIMUM_IP_TARGET = 5 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
None 
**Environment**:
N/A

**Comment by mogren** [comment]
@pseonghoon Thanks, I agree that the example didn't make sense. I updated the doc.
