### ISSUE TITLE
New pods failing to start with `FailedCreatePodSandBox` warning for CNI versions 1.7.x with Cilium

### ISSUE THREAD

**Issue by YesemKebede** [aws/amazon-vpc-cni-k8s#1265]
**What happened**:

New pods started failing to come up after upgrading to eks CNI v1.7.0 from v1.6.0.  I was able to upgrade to v1.6.3 without any issue. I started to see the errors when I upgraded to 1.7.0. I also tried to upgrade to other version ( v1.7.2 and v1.7.5) but I am seeing the same issue. 

Here is the error I am seeing.
```
 Warning  FailedCreatePodSandBox  28s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7e3423d27fc6f36276de03aa7f41ef6b6f02121f800b65b64b8073c6a207b696" network for pod "spinnaker-get-resource-type-3fc73e4e3611d9f4-ps4b7": networkPlugin cni failed to set up pod "spinnaker-get-resource-type-3fc73e4e3611d9f4-ps4b7_default" network: invalidcharacter '{' after top-level value

``` 
Here is the [cni log](https://github.com/aws/amazon-vpc-cni-k8s/files/5403389/eks_i-06f4c3b1d6a6a3b1a_2020-10-19_1616-UTC_0.6.2.tar.gz)

**Anything else we need to know?**:
- We have Cilium running in chaining mode (v1.8.4) 

**Environment**:
- Kubernetes version :`v1.17.9-eks-4c6976`
- CNI Version: Tried different versions but seeing same issue for (1.7.0, 1.7.2, 1.7.5)
- Kernel: `5.4.58-27.104.amzn2.x86_64`

**Comment by jayanthvn** [comment]
Hi @YesemKebede 

Can you please confirm if you have set `AWS_VPC_K8S_PLUGIN_LOG_FILE` to stdout?

I checked IPAMD logs and I see IP allocation seems fine on the first look. We will further investigate the issue.

Thanks.

**Comment by YesemKebede** [comment]
@jayanthvn  `AWS_VPC_K8S_PLUGIN_LOG_FILE` is set to `/var/log/aws-routed-eni/plugin.log`

**Comment by jayanthvn** [comment]
Thanks @YesemKebede . We will look into it asap.

**Comment by jayanthvn** [comment]
Hi @YesemKebede 

Can also please confirm how you upgraded from 1.6.3 to 1.7.X?

Thank you!

**Comment by YesemKebede** [comment]
@jayanthvn I followed the this [Doc]( https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html)

**Comment by sophomeric** [comment]
I upgraded from 1.6.3 to 1.7.5 and had the same problem. No new pod could be started and they had that same error. I had both AWS_VPC_K8S_CNI_LOG_FILE and AWS_VPC_K8S_PLUGIN_LOG_FILE set to stdout and had this same problem. Removing them so they get sent to files as per their default config solved the issue for me.

Google led me here: https://github.com/Azure/azure-container-networking/issues/195#issuecomment-408990663

**Comment by jayanthvn** [comment]
@sophomeric Yes setting AWS_VPC_K8S_PLUGIN_LOG_FILE  to stdout will cause a similar issue(#1251). But here it wasn't set.

**Comment by Aggouri** [comment]
We are experiencing the same issue on newly provisioned clusters with the following difference in versions:
- Kubernetes version: `v1.17.11-eks-cfdc40`
- Cilium `v1.9.0-rc2` in chaining mode

If it helps, although I am not 100% sure about the Kubernetes version being exactly the same patch version, that same configuration was working last week on a different cluster with the same characteristics.

**Comment by jayanthvn** [comment]
Hi @Aggouri 

Can you please confirm the CNI version for the two clusters?

```
kubectl describe daemonset aws-node -n kube-system | grep Image | cut -d "/" -f 2
```

Thanks.

**Comment by Aggouri** [comment]
@jayanthvn 

> Can you please confirm the CNI version for the two clusters?

The cluster was provisioned a few hours ago:

```console
$ kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2

amazon-k8s-cni-init:v1.7.5-eksbuild.1
amazon-k8s-cni:v1.7.5-eksbuild.1
```

Sadly, I am unable to provide the CNI plugin version of the previous cluster as it was already torn down. If it helps, I know it was provisioned at the beginning of last week and used the defaults EKS came with for Kubernetes version `1.17.x`.

**Comment by jayanthvn** [comment]
Thanks for conforming @Aggouri . We are actively looking into the issue. Will update asap.

**Comment by Arsen-Uulu** [comment]
@jayanthvn  upgraded from 1.6.3 to 1.7.5 having a problem.
```
{"level":"error","ts":"2020-10-27T10:44:04.889-0400","caller":"routed-eni-cni-plugin/cni.go:249","msg":"Error received from DelNetwork gRPC call for container ba592f75d2b25963c4bd64f218ae0930917fa39e3efffd2231b313f8eb42d344: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:500
```

**Comment by jayanthvn** [comment]
Hi,

We have found the RC, for now please add `pluginLogFile` and `pluginLogLevel` in `05-cilium.conflist`. We will fix this issue in the next release.

```
cat /etc/cni/net.d/05-cilium.conflist
{
  "cniVersion": "0.3.1",
  "name": "aws-cni",
  "plugins": [
    {
      "name": "aws-cni",
      "type": "aws-cni",
      "vethPrefix": "eni",
      "mtu": "9001",
      "pluginLogFile": "/var/log/aws-routed-eni/plugin.log",
      "pluginLogLevel": "Debug"
    },
    {
       "name": "cilium",
       "type": "cilium-cni",
       "enable-debug": false
    }
  ]
}

```
Thank you!

**Comment by jayanthvn** [comment]
#1275 is merged so closing this issue.

**Comment by bogarcia** [comment]
is there any ETA for a new release including this fix?
Thanks!

**Comment by pankajmt** [comment]
I tried the workaround suggested in https://github.com/aws/amazon-vpc-cni-k8s/issues/1265#issuecomment-717349630 👍 

After this, coredns is RUNNING but NOT READY. This from the 2 pods. 

`pankaj.tolani@tolani-mac  ~/afterpay/inception/cilium/alpha  kl coredns-74fcbd4cb4-k4dhc
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.7.0
linux/amd64, go1.13.15, f59c03d0
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:60370->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:48293->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:49938->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:38861->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:56928->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 1687429144305681147.3333962346685544537. HINFO: read udp 10.240.35.84:52537->10.240.0.2:53: i/o timeout
 pankaj.tolani@tolani-mac  ~/afterpay/inception/cilium/alpha  kl coredns-74fcbd4cb4-x68m8
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.7.0
linux/amd64, go1.13.15, f59c03d0
[ERROR] plugin/errors: 2 5763478806533751487.8973578589187692515. HINFO: read udp 10.240.29.242:47668->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 5763478806533751487.8973578589187692515. HINFO: read udp 10.240.29.242:48540->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 5763478806533751487.8973578589187692515. HINFO: read udp 10.240.29.242:57593->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 5763478806533751487.8973578589187692515. HINFO: read udp 10.240.29.242:37493->10.240.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 5763478806533751487.8973578589187692515. HINFO: read udp 10.240.29.242:42574->10.240.0.2:53: i/o timeout
I0308 03:17:11.104617       1 trace.go:116] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2021-03-08 03:16:41.103761797 +0000 UTC m=+0.020357165) (total time: 30.000769225s):
Trace[1427131847]: [30.000769225s] [30.000769225s] END
E0308 03:17:11.104647       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get https://172.20.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 172.20.0.1:443: i/o timeout
I0308 03:17:11.105067       1 trace.go:116] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2021-03-08 03:16:41.104625732 +0000 UTC m=+0.021221092) (total time: 30.000420935s):
Trace[911902081]: [30.000420935s] [30.000420935s] END
E0308 03:17:11.105080       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get https://172.20.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 172.20.0.1:443: i/o timeout
I0308 03:17:11.105165       1 trace.go:116] Trace[1474941318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2021-03-08 03:16:41.104545953 +0000 UTC m=+0.021141323) (total time: 30.000607402s):
Trace[1474941318]: [30.000607402s] [30.000607402s] END
E0308 03:17:11.105172       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get https://172.20.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.20.0.1:443: i/o timeout`

Thoughts?

**Comment by jayanthvn** [comment]
Hi @pankajmt 

Which image version are you using since Rel 1.7.9 has the fix for #1265 - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.9.

**Comment by tgraf** [comment]
Can we point to a particular set of EKS releases in the Cilium docs somehow? What versions of EKS will ship with 1.7.9?

**Comment by pankajmt** [comment]
I am on aws cni 1.7.8. 

`amazon-k8s-cni-init:v1.7.8
amazon-k8s-cni:v1.7.8`

So looks like there is hope assuming the EKS version we need is GA in our region. While docs improve, someone knows the EKS version I should be looking for?

Many thanks,
Pankaj

**Comment by jayanthvn** [comment]
Hi,

Yeah that would be great if Cilium docs can point to EKS CNI versions and if there is any known issue it would be easy for Cx to fallback or look for new versions. Currently EKS default CNI version is 1.7.5 with new clusters. Will keep you updated if we plan to make 1.7.9 or later versions default for EKS.

Thank you!

**Comment by pankajmt** [comment]
So looks like then ours is a custom install of the EKS CNI. I will figure out how it was done and how can I upgrade it to 1.7.9.

**Comment by pankajmt** [comment]
worked well with aws cni v1.7.9. many thanks.
