### ISSUE TITLE
Broken aws-k8s-cni.yaml in 1.7?

### ISSUE THREAD

**Issue by therc** [aws/amazon-vpc-cni-k8s#1268]
Compare 

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.7/aws-k8s-cni.yaml#L243

with

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.6/aws-k8s-cni.yaml#L30

The new file seems to be truncated. Plus, it's in a different order and fields are all quoted strings, so a diff becomes a lot noisier.

**Comment by jayanthvn** [comment]
Hi @therc 

We validated the 1.7 yaml and it is not broken. Please let us know if you are having any issues applying the yaml. 1.7 onwards we auto generate the config files please refer to #986 hence the order will be bit different. Three dots indicates the end of a block at L243. 

Thank you!

**Comment by therc** [comment]
Hi @jayanthvn 
I was not aware of the three dot syntax, you always learn something new... We had made custom tweaks to the YAML file, hence my attempts to run a textual diff. I guess the 1.6->1.7 jump will be disruptive, but after that changes will be incremental only.

Thanks for the details, I'll close for now.

**Comment by therc** [comment]
For anyone in the same boat, you can use this script to convert both 1.6-style and 1.7-style YAML to a format that's easier to diff:

```
import sys
import yaml

def rewrite(x):
  i = open(x, "r")
  y = yaml.load_all(i)
  with open(x+".new", "w") as o:
    yaml.dump_all(y, o)
  i.close()

for x in sys.argv[1:]:
  rewrite(x)
```

You might have to sort the objects in the 1.6 document by the "kind" field, e.g. with ServiceAccount last.

**Comment by jayanthvn** [comment]
Thanks for checking @therc :)
