### ISSUE TITLE
Liveness and Readiness probes fail using the CNI per pod SG

### ISSUE THREAD

**Issue by hetpats** [aws/amazon-vpc-cni-k8s#1269]
**What happened**: WE are using 1.17 eks cluster and 1.7.3 CNI version in our environment, All our liveness and readiness probs fail to connect and pods keep restarting, we do have the ports open both on the worker node SG and the inbound for pod SG.
We have the DISABLE_TCP_EARLY_DEMUX enabled to true.
We can however login to the node and telnet to the pod  on the port number its listening on for the probes
our probes are simple TCP call to a port on pod.
pods are communicating to the other apps via SG just fine, we have to disabled the probes for now for the application to come up.
are we missing anything?

**Environment**:
- Kubernetes version (use `kubectl version`):1.17
- CNI Version 1.7.3
- OS (e.g: `cat /etc/os-release`):Amazon Linux Release 2 (karoo)
- Kernel (e.g. `uname -a`):Linux 4.14.198-152.320.amzn2.x86_64

**Comment by jayanthvn** [comment]
Hi @hetpats 

Can you please provide us the below information -

1. On the instance -
```
cat /proc/sys/net/ipv4/tcp_early_demux
```
2. can you email me (varavaj@amazon.com) your Cluster ARN

Thank you!

**Comment by hetpats** [comment]
email sent with details

**Comment by atimush** [comment]
Same for us running CNI 1.7.5. All liveness and readiness probes are failing either with Allow ANY in the SGs

**Comment by SaranBalaji90** [comment]
@atimush do you use http-proxy in your setup as well?

**Comment by atimush** [comment]
@SaranBalaji90 Hey Saran, we do not use any http-proxy. 
We have an on-going support case. I found the issue here and taught it would relevant to mention same problem as other people experience just to facilitate others who started to explore the new feature and might spend hours of debugging (like me) 👍

**Comment by SaranBalaji90** [comment]
@atimush can you give your support case number? I can take a look.

**Comment by SaranBalaji90** [comment]
@atimush can you check if DISABLE_TCP_EARLY_DEMUX is set to true under initContainers env (described here  https://github.com/aws/amazon-vpc-cni-k8s/blob/master/README.md)

**Comment by SkySonR** [comment]
Hi! Same issue with EKS 1.18 and 1.7.5 CNI version

**Comment by SaranBalaji90** [comment]
@SkySonR can you verify if DISABLE_TCP_EARLY_DEMUX is set to true in your initContainer? Because looks like documentation is missing this step which is causing confusion. We are updating the documentation now. Sorry for the trouble it caused.

**Comment by SaranBalaji90** [comment]
@atimush @SkySonR we have updated docs, let me know if this doesn't solve the problem
CNI ReadMe - https://github.com/aws/amazon-vpc-cni-k8s/pull/1273/files
Aws Docs - https://github.com/awsdocs/amazon-eks-user-guide/pull/233
Blog post - https://aws.amazon.com/blogs/containers/introducing-security-groups-for-pods/

**Comment by atimush** [comment]
@SaranBalaji90 Thank you. That fixed the issue.

**Comment by jayanthvn** [comment]
Documentation is updated hence closing the issue. Kindly let us know if you have any more questions.
