### ISSUE TITLE
allow tagging enis

### ISSUE THREAD

**Issue by eatwithforks** [aws/amazon-vpc-cni-k8s#1276]
we need all our enis to be tagged with a project tag. please either allow us inheriting that from a node label or allow setting an annotations, for example cni.eni/tags = project:foo

would you accept a pr that implements this feature?

**Comment by jayanthvn** [comment]
Hi @eatwithforks 

With 1.6.0 onwards you can provide additional eni tags which will be applied to the ENIs when created, can you please check if this will solve your use case -

```
ADDITIONAL_ENI_TAGS (Since v1.6.0)

Type: String

Default: {}

Example values: {"tag_key": "tag_val"}

Metadata applied to ENI help you categorize and organize your resources for billing or other purposes. Each tag consists of a custom-defined key and an optional value. Tag keys can have a maximum character length of 128 characters. Tag values can have a maximum length of 256 characters. These tags will be added to all ENIs on the host.

Important: Custom tags should not contain k8s.amazonaws.com prefix as it is reserved. If the tag has k8s.amazonaws.com string, tag addition will ignored.
```

Thank you!

**Comment by eatwithforks** [comment]
Hi @jayanthvn, thanks for the quick response! Does this env var retroactively apply tags to existing enis?

**Comment by jayanthvn** [comment]
Hi @eatwithforks 

We won't retroactively apply tags to existing ENIs. Only for newly allocated ENI the tag will be applied - https://github.com/aws/amazon-vpc-cni-k8s/blob/a68e8106ad7a4fa058df6e86edbe5d617a09346e/pkg/awsutils/awsutils.go#L626

Thanks.
