### ISSUE TITLE
show attached enis in node annotation or status

### ISSUE THREAD

**Issue by eatwithforks** [aws/amazon-vpc-cni-k8s#1277]
for debugging, would be great if the enis are available in the node.

**Comment by jayanthvn** [comment]
Hi @eatwithforks 

Yes it would be good for debugging. We can evaluate to see if we can add it to node events which can be queried from `kubectl describe nodes`.

Thank you!

**Comment by vissree** [comment]
Hi @jayanthvn,

I would like to work on this. This is the approach I am thinking of. Please let me know if this looks good.

1) Update k8sapi package to send events ([Event v1 core](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#event-v1-core))
2) Send the event with the corresponding Node as the 'involvedObject' after a successful tryAllocateENI and tryFreeENI in ipamd.

**Comment by jayanthvn** [comment]
Hi @vissree 

Thanks, it would be helpful. But we need to track attach (https://github.com/aws/amazon-vpc-cni-k8s/blob/9fa117af7592ca2cc668674083df905ae3648ba1/pkg/awsutils/awsutils.go#L649) and detach ENI (https://github.com/aws/amazon-vpc-cni-k8s/blob/9fa117af7592ca2cc668674083df905ae3648ba1/pkg/awsutils/awsutils.go#L857).

**Comment by vissree** [comment]
Hi @jayanthvn,

Created  a PR for this change.

I haven't updated the awsutils package and added the event part in the ipamd package instead so that the IPAMContext doesn't need to be passed to the awsutils package and keep the imports also clean. Could you please review the PR and let me know your comments?

**Comment by jayanthvn** [comment]
PR is pending merge.

**Comment by jayanthvn** [comment]
PR is pending merge.
