### ISSUE TITLE
Seeing error "couldn't get resource list for metrics.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by marcincuber** [aws/amazon-vpc-cni-k8s#1290]
**What happened**:
```
ERROR: logging before flag.Parse: E1118 16:07:28.895445       9 memcache.go:147] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
I am consistently seeing the above error message. I can't figure out what the issue really is.

I upgraded metrics-server to latest 0.4.1 version. I also checked RBAC permissions and I can't find anything missing.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8-eks-7c9bda
- CNI Version 1.7.5

Any help on how to debug this further?

**Comment by jayanthvn** [comment]
Hi @marcincuber 

Please refer to https://github.com/aws/amazon-vpc-cni-k8s/issues/486. Looks like similar issue.

Thank you!

**Comment by jayanthvn** [comment]
Hi @marcincuber 

Please check this comment - https://github.com/aws/amazon-vpc-cni-k8s/issues/486#issuecomment-685848903. So this should be mitigated once we update to the latest client-go. Updating the go-client is tracked in #745.

**Comment by marcincuber** [comment]
@jayanthvn Thanks for the update. I though this was something in my cluster but in this case I am waiting for client-go update :).
