### ISSUE TITLE
Failing with SELinux Enabled

### ISSUE THREAD

**Issue by arhea** [aws/amazon-vpc-cni-k8s#1291]
**What happened**:
RHEL 7 image with the EKS binaries installed. When joining the instance to the cluster the `aws-node` init container successfully runs because it runs in privileged mode. The long-running daemon container fails to move and place files in the host directory.

```text
# aws-node logs
"level":"info","ts":"2020-11-19T21:03:44.454Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
install: cannot remove '/host/opt/cni/bin/aws-cni': Permission denied
```

**What you expected to happen**:
```text
# aws-node logs with privileged mode or running on non-selinux host
{"level":"info","ts":"2020-11-19T20:51:21.267Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2020-11-19T20:51:21.279Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}{"level":"info","ts":"2020-11-19T20:51:21.281Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}{"level":"info","ts":"2020-11-19T20:51:23.299Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2020-11-19T20:51:23.302Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}{"level":"info","ts":"2020-11-19T20:51:23.303Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

**How to reproduce it (as minimally and precisely as possible)**:
```text
$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

**Anything else we need to know?**:
When running in privileged mode, the daemon set functions properly.

```yaml
securityContext:
  privileged: true
  capabilities:
    add:
      - NET_ADMIN
```

If the mounted host directories are configured with the `container_file_t` label, then the CNI is able copy the files but is never able to communicate with the ipam-D agent:

```text
{"level":"info","ts":"2020-11-19T20:51:21.267Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2020-11-19T20:51:21.279Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}{"level":"info","ts":"2020-11-19T20:51:21.281Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
```

**Environment**:
- Kubernetes version: v1.18.8-eks-7c9bda
- CNI Version: v0.8.6
- OS: RHEL 7.9
- Kernel: Linux ip-192-168-104-223.us-east-2.compute.internal 3.10.0-1160.6.1.el7.x86_64

**Comment by nithu0115** [comment]
@arhea I tried with AL2, RHEL7, RHEL8 version and wasn't able to replicate the issue. Please let me know if there is any special configuration is needed to replicate the issue. Btw, I am using the same as you are to build my custom AMIs - https://github.com/aws-samples/amazon-eks-custom-amis

AL2 == ```
[root@ip-192-168-52-199 ec2-user]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
12:49
[ec2-user@ip-10-0-1-130 ~]$ knw get po aws-node-m7cnt
NAME             READY   STATUS    RESTARTS   AGE     IP               NODE                                           NOMINATED NODE   READINESS GATES
aws-node-m7cnt   1/1     Running   0          2m22s   192.168.52.199   ip-192-168-52-199.us-east-2.compute.internal   <none>           <none>
12:49
[ec2-user@ip-10-0-1-130 ~]$ kn logs aws-node-m7cnt
{"level":"info","ts":"2021-01-15T18:47:11.043Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-01-15T18:47:11.056Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-01-15T18:47:11.058Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2021-01-15T18:47:13.081Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2021-01-15T18:47:13.083Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2021-01-15T18:47:13.084Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

RHEL7 ```
[ec2-user@ip-192-168-42-219 ~]$ sudo su
[root@ip-192-168-42-219 ec2-user]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
[root@ip-192-168-42-219 ec2-user]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[root@ip-192-168-42-219 ec2-user]#

aws-node-wqzfs                            1/1     Running   0          6m35s
[ec2-user@ip-10-0-1-130 amazon-eks-custom-amis]$ kn logs aws-node-wqzfs
{"level":"info","ts":"2021-01-23T02:22:13.849Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-01-23T02:22:13.869Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-01-23T02:22:13.872Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2021-01-23T02:22:15.909Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2021-01-23T02:22:15.913Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2021-01-23T02:22:15.914Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

**Comment by jayanthvn** [comment]
Thanks @nithu0115 for verifying. Closing this issue and if needed kindly reach out to us.

**Comment by jayanthvn** [comment]
@nithu0115  - Reopening the issue since it is seen with AL2 extra.

**Comment by nithu0115** [comment]
Quick update: I am able to replicate the issue on AL2 with `selinux-enabled` on docker daemon. 

Things that I have done so far to replicate the linux on AL2:
```
sudo amazon-linux-extras install selinux-ng
[OPTIONALLY FOR CONTAINER SUPPORT] sudo yum install container-selinux
Edit /etc/selinux/config to set SELINUX=enforcing (or targeted as desired)
vi /etc/docker/daemon.json and add `"selinux-enabled": true` to the file
Reboot
```
After that I see aws-node daemonSet crash with permissions issue.
```
[ec2-user@ip-10-0-1-130 ~]$ kn logs aws-node-tdkvt
{"level":"info","ts":"2021-02-03T16:06:30.680Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
install: cannot remove '/host/opt/cni/bin/aws-cni': Permission denied
```
Here, the host SELinux config isn't to blame. The aws-node pod starts and as part of entrypoint script, we install the CNI binary and also copy 10-awslist.conf file and the written file carries the SELinux context of that container (random MCS pair). This is causing container to start as the host MCS pair is associated to a different user/group (probably)?

Quick work around this is to set `spc_t` selinuxOptions or run containers as `privileged: true`
```  
securityContext:	         
    seLinuxOptions:	         
         type: spc_t
```
However, If you run as spc_t by default you'll break current Bottlerocket releases since we don't define that label.

**Comment by jmonson** [comment]
We continue to see this problem on RHEL 8.7. Did you find a resolution? We're using the EKS addons, and I can see it's using `privileged: true`.

**Comment by jwc-armis** [comment]
we have encountered this issue

**Comment by jdn5126** [comment]
> v1.12.0-eksbuild.2

Can you try with `v1.12.1-eksbuild.1`? Our support for custom AMIs is best effort, so it will take some time to get to this if the latest version does not work.

**Comment by jmonson** [comment]
Our issue stemmed from comparing 2 "like" nodes and getting different results. Both were using SELinux enforcing, but we failed to catch that one node had selinux-enabled in docker and the other did not (I should have read @nithu0115 's response more closely on how he replicated). We are good now.
