### ISSUE TITLE
Documentation missing for `vpc.amazonaws.com/pod-eni` annotation/limits

### ISSUE THREAD

**Issue by adammw** [aws/amazon-vpc-cni-k8s#1292]
**What would you like to be added**:
Documentation around how to manually use annotations/limits with POD_ENI enabled without amazon-vpc-resource-controller-k8s, or pointers to where in the resource controller it is defined.

**Why is this needed**:
We are looking to apply a custom ENI configuration for a single pod to attach it to a different subnet, but there's no documentation to see if the annotation supports this..

**Comment by adammw** [comment]
Reading more of the code, it appears that the CNI plugin isn't actually involved in the attachment of ENI trunks but instead relies on https://github.com/aws/amazon-vpc-resource-controller-k8s to attach and configure the trunk, which again does not seem to be documented in the ENABLE_POD_ENI description.

**Comment by haouc** [comment]
The README has been updated in the PR [Update README for Per Pod Security Group](https://github.com/aws/amazon-vpc-cni-k8s/pull/1321).
