### ISSUE TITLE
E1030 - Failed to list *v1.Pod: Unexpected error 

### ISSUE THREAD

**Issue by oxr463** [aws/amazon-vpc-cni-k8s#1293]
**What happened**:

```
2020-10-30T18:52:48.811047288Z ERROR: logging before flag.Parse: E1030 18:52:48.810963      12 reflector.go:205] github.com/aws/amazon-vpc-cni-k8s/pkg/k8sapi/discovery.go:262: Failed to list *v1.Pod: Unexpected error &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc421b1ffb0), Addr:(*net.TCPAddr)(0xc426a9c000), Err:(*os.SyscallError)(0xc424eee200)} when reading response body. Please retry.
```

**What you expected to happen**: Unsure

**How to reproduce it (as minimally and precisely as possible)**: Unsure

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Unsure
- CNI Version: v1.4.1
- OS (e.g: `cat /etc/os-release`):

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```
- Kernel (e.g. `uname -a`):

```
Linux ip-100-65-86-213.ec2.internal 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jayanthvn** [comment]
Hi @oxr463 

Is this a new cluster and do share the kubernetes version? Can you please email me (varavaj@amazon.com) your cluster ARN since would like to check the response from API Server ? Also do share me CNI logs, please run the below script - 

`sudo bash /opt/cni/bin/aws-cni-support.sh`

Thank you!

**Comment by oxr463** [comment]
> Hi @oxr463
> 
> Is this a new cluster and do share the kubernetes version? Can you please email me ([varavaj@amazon.com](mailto:varavaj@amazon.com)) your cluster ARN since would like to check the response from API Server ? Also do share me CNI logs, please run the below script -
> 
> `sudo bash /opt/cni/bin/aws-cni-support.sh`
> 
> Thank you!

Hi @jayanthvn, thanks for the quick follow up. This is from a customer's cluster. Let me forward these instructions on to him.

**Comment by jayanthvn** [comment]
Hi @oxr463 

Did you get a chance to collect the details?

**Comment by oxr463** [comment]
> Hi @oxr463
> 
> Did you get a chance to collect the details?

No, the ticket auto-closed after going stale. I will close this.

**Comment by jayanthvn** [comment]
Thanks. Please do reach out if you again see the issue.
