### ISSUE TITLE
Failed to allocate IP address for coredns pod

### ISSUE THREAD

**Issue by jstegemanhv** [aws/amazon-vpc-cni-k8s#1294]
**What happened**: I created a new EKS cluster with public/private control plane access. My VPC has 4 subnets - 2 in each of 2 AZs. 2 of the subnets are for node IPs and 2 are secondary for pods. I added 3 nodes to the cluster after setting up the configuration for the CNI plugin. The coredns pods are stuck in ContainerCreating status. Looking at the ipamd plugin logs, CNI plugin is failing to allocate an IP.

{"level":"error","ts":"2020-11-23T18:27:16.362Z","caller":"routed-eni-cni-plugin/cni.go:117","msg":"Failed to assign an IP address to container d441ca8a9c84c538c66cb9ee1b91b16af44d3c3c92a1c6fb96bb039d90111926"}

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Hi @jstegemanhv 

Can you please share compete log file? Please run the below command on one of the nodes where coredns has failed to get an IP and share it with me.

`sudo bash /opt/cni/bin/aws-cni-support.sh`

Thank you!

**Comment by jstegemanhv** [comment]
Hi thanks for the quick answer... It may be a bad yaml file setting up the CNI subnets... stand by

**Comment by jstegemanhv** [comment]
That seems to have been the issue. Now on to debug why istiod doesn't like this

Thanks for your quick response!

**Comment by jayanthvn** [comment]
Thanks for confirming @jstegemanhv. Will close the issue. Please reach out if needed.
