### ISSUE TITLE
It is possible to increate the IP limits?

### ISSUE THREAD

**Issue by aledbf** [aws/amazon-vpc-cni-k8s#13]
Using m4.large instances I can only have 27 pods per node

**Comment by dbenhur** [comment]
The IP-Pod/Node limits are a direct consequence of [ENI/Instance limits](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI).  These are hard, not soft, limits stemming from the implementation of AWS VPC networking.   If you require denser pod/node packing than permitted, then this CNI's approach is not suitable.

**Comment by chrislovecnm** [comment]
@dbenhur where is this documented?

>  These are hard, not soft

Hard as in you never will improve them?  This, in my opinion, is a big limitation for this CNI provider, but some of my big data stuff will love this plugin.

Until this is documented can we please re-open this issue.

cc: @arun-gupta @liwenwu-amazon
