### ISSUE TITLE
Support ECR public registry

### ISSUE THREAD

**Issue by nithu0115** [aws/amazon-vpc-cni-k8s#1306]
AWS announced ECR public registry. It would be great if we could have aws-vpc-cni-k8s image and cloudwatch metrics image in there. 
https://gallery.ecr.aws/?searchTerm=Kubernetes

**Comment by jayanthvn** [comment]
This is not stale.

**Comment by jdn5126** [comment]
CNI, CNI init, and metrics helper images are currently available at https://gallery.ecr.aws/eks

Leaving issue open until charts can be modified to point to public registry, i.e. `public.ecr.aws/eks/amazon-k8s-cni:<tag>`

**Comment by jdn5126** [comment]
All new releases will be published to public ECR, but charts will still point to private ECR for security reasons. Closing this issue as completed.

**Comment by dinesh** [comment]
@jdn5126 we don't have 1.12.5 updated in https://gallery.ecr.aws/eks/amazon-k8s-cni. is it a manual propagation or automated in CI ?

**Comment by dinesh** [comment]
thx, our CI is failing because of it while trying to upgrade. Better if you can automate it.

**Comment by jdn5126** [comment]
@dinesh is there a reason you are relying on the public registry instead of the EKS private registries for each region? The private registries are what we recommend, mostly for performance, and the public registry is something we really just publish as a courtesy for the community, i.e. you don't need an AWS account or to use EKS to access the image

**Comment by dinesh** [comment]
@jdn5126 Because of compliance needs, we started to own every docker image going into the cluster and get it built in CI, and push it to the internal docker registry. We don't want to pull aws-region specific images in CI which requires aws auth (I guess) and relies on the public registry.

**Comment by jdn5126** [comment]
@dinesh btw, 1.12.5 and 1.12.6 images are published to public ECR now
