### ISSUE TITLE
CNI 1.7.6 Manifest is pointing to CNI 1.7.5

### ISSUE THREAD

**Issue by suket22** [aws/amazon-vpc-cni-k8s#1308]
**What happened**:
I was trying to update to CNI 1.7.6 by running - 
`kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.6/config/v1.7/aws-k8s-cni.yaml` but that wasn't updating my CNI to 1.7.6

**Attach logs**
N/A

**What you expected to happen**:
I should've been able to update to 1.7.6 as per the latest release - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.6

**How to reproduce it (as minimally and precisely as possible)**:
```
> kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni-init:v1.7.5
amazon-k8s-cni:v1.7.5

> kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.6/config/v1.7/aws-k8s-cni.yaml
clusterrolebinding.rbac.authorization.k8s.io/aws-node unchanged
clusterrole.rbac.authorization.k8s.io/aws-node unchanged
customresourcedefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com unchanged
daemonset.apps/aws-node unchanged
serviceaccount/aws-node unchanged

> kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni-init:v1.7.5
amazon-k8s-cni:v1.7.5
```

**Anything else we need to know?**:
N/A

**Environment**:
Leaving as blank since this is wrt modifying the CNI version.

**Comment by jayanthvn** [comment]
Hi @suket22  - Thanks for finding this. The manifest is fixed now. Please retry.
