### ISSUE TITLE
Waiting for CNI file

### ISSUE THREAD

**Issue by johan-smits** [aws/amazon-vpc-cni-k8s#1320]
**Describe the bug**
When running with AWS EKS cluster and the default CNI it keeps waiting
**To Reproduce**
1. https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
2. `curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/VERSION/v1.18.12/g' | kubectl apply -f -`
3. I skipped the flanel because I use the amazon-k8s-cni

**Expected behavior**
That the kube-proxy would start normally

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows_Server-2019-English-Core-EKS_Optimized-1.18-2020.11.12
 - Kubernetes Version: 1.18 (eks.2)
 - CNI: amazon-k8s-cni:v1.7.5

**Additional context**
Unable to have a loadbalancer route data to other pods then the Windows ones. It is a mixed environment of Linux and Windows nodes.

**Comment by haouc** [comment]
@johan-smits I have reproduced the log you were seeing on windows node. I think the reason you are seeing this because this CNI plugin doesn't support Windows node (https://github.com/aws/amazon-vpc-cni-k8s/issues/15). If you don't have CNI installed in the host, [this while loop](https://github.com/kubernetes-sigs/sig-windows-tools/blob/c19b43da06e9dbb04e185eb44b9cb718d0d81ecd/kubeadm/kube-proxy/kube-proxy.yml#L11) will keep looking for etc/cni/net.d for config file. Please let me know if you have other concerns. Thanks.

**Comment by johan-smits** [comment]
@haouc, thanks for the information. The problem that I'm facing is that in AWS the Windows nodes sometimes don't forward any packages from a classic loadbalancer. So my thoughts where no node proxy service is running on the Windows nodes and I followed the Kubernetes documentation on how to add it. Or is this an other issue that I'm facing?

We use a mixed environment of Windows, Linux and Fargate nodes in the same cluster with NLB, ALB and CLB.

**Comment by haouc** [comment]
@johan-smits, sorry for the late reply. If you were following the instruction you mentioned to prepare your cluster to support Windows nodes, I think you already have the proxy service applied. This CNI is not expected to work on Windows node. The [proxy service](https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml) you were trying to install is using the upstream image and has a startup script to look for the CNI config file. This CNI won't place the config file in Windows nodes and the startup script of proxy will fail. If you have to use the proxy, I would suggest you to check with [this GitHub project](https://github.com/aws/amazon-vpc-cni-plugins) that is for VPC CNI plugins in Windows nodes. Thanks.

**Comment by johan-smits** [comment]
thnx for the reply.
