### ISSUE TITLE
Paginate DecribeNetworkInterface call

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#1325]
**What would you like to be added**:
Paginate DescribeNetworkInterfaceCall

**Why is this needed**:
With larger cluster i.e, with higher node scale on nodeInit we call DescribeNetworkInterface to query all the ENIs in the account for cleanup which will cause higher API calls with larger node scale. Hence pagination will help.

https://github.com/aws/amazon-vpc-cni-k8s/blob/a68e8106ad7a4fa058df6e86edbe5d617a09346e/pkg/awsutils/awsutils.go#L1396

https://github.com/aws/amazon-vpc-cni-k8s/blob/a68e8106ad7a4fa058df6e86edbe5d617a09346e/pkg/awsutils/awsutils.go#L1399

**Comment by fawadkhaliq** [comment]
@jayanthvn @haouc since the ipamd instance is bound to an ec2 instance and ec2 instance belongs to an availability zone. Should we also add `availability-zone` to `DescribeNetworkInterfacesInput` [1] filters to further filter the entries ipamd does not need to process? The more we can filter, the better (less number of API calls when # of pages > 1 )

[1] https://godoc.org/github.com/datacratic/aws-sdk-go/service/ec2#DescribeNetworkInterfacesInput

**Comment by jayanthvn** [comment]
@fawadkhaliq This call https://github.com/aws/amazon-vpc-cni-k8s/blob/a68e8106ad7a4fa058df6e86edbe5d617a09346e/pkg/awsutils/awsutils.go#L1399 is made to clean up all leaked ENIs in the Cx account. So you are referring to filter this on availability-zone? So still some of the ENIs might not get cleaned right?

**Comment by SaranBalaji90** [comment]
As Jayanth pointed out, this go routine is specifically for cleaning up leaked ENIs. we can’t filter out by AZ unfortunately but Jayanth if we have cluster name in the tag and if that’s known to CNI plug-in we can use that as well.

**Comment by fawadkhaliq** [comment]
I see. +1, that would help. However, only consider cluster name tag if it exists for the supported CNI versions to make sure we don't skip interfaces from older CNI versions

**Comment by jayanthvn** [comment]
Yeah @SaranBalaji90 today we are not aware of the cluster name. But is it fine to just clean up ENIs in the same cluster? Because today we clean up all leaked ENIs in the Cx account and that will be limited to the cluster now.

**Comment by fawadkhaliq** [comment]
> But is it fine to just clean up ENIs in the same cluster?

Absolutely. We should only be touching ENIs that belong to the cluster ipamd is running on. Let each cluster ipamds clean up their own ENIs

**Comment by SaranBalaji90** [comment]
Ideally we should keep the permission only within that node boundary and if not may be at cluster level but we shouldn’t perform action across the entire account. We should discuss how we can improve this in future.

**Comment by jayanthvn** [comment]
Yeah that makes sense @fawadkhaliq and @SaranBalaji90 . I can open a tracking PR for this. For now we can paginate the calls and clean up this in the following PR if that makes sense?

**Comment by fawadkhaliq** [comment]
Makes sense. Given the previous versions do not tag with cluster identifier, we may need to roll this out in multiple steps to address the upgrades and handle the ENIs without the tags.
