### ISSUE TITLE
aws-cni vs aws-node

### ISSUE THREAD

**Issue by ghostsquad** [aws/amazon-vpc-cni-k8s#1346]
**What would you like to be added**:

Just curious why the daemonset and such is called `aws-node` instead of `aws-cni`, and to formally request that this be changed in future releases, as it means there's a bit of indirection when someone is looking for the CNI. Almost everything here except for the name of the daemonset uses `cni` in the name, not `node`

**Why is this needed**:

Clarity, Readability, Discoverability.

**Comment by jaypipes** [comment]
Hi @ghostsquad! The daemonset is called `aws-node` as a historical legacy, not for any particular reason. Of course, you don't need to name it that when you install the CNI daemonset (via Helm or otherwise). I agree that it would be much clearer to rename it to `aws-vpc-cni`.
