### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by GlennMR** [aws/amazon-vpc-cni-k8s#137]
Cluster regularly loses connection for some reason:

`Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 172.17.31.213:10250: getsockopt: no route to host`

This happened on a fresh cluster, setup using the guide explained here https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html.

After about 5 minutes it did start working, the log from aws-node is:

`kubectl logs -f aws-node-xmd5p -n kube-system            
=====Starting installing AWS-CNI =========
=====Starting amazon-k8s-agent ===========
ERROR: logging before flag.Parse: W0721 00:00:05.365123      11 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.`

Instance class: m4.xlarge

Other solution is to remove all aws-node pods, but the issue usually comes back after a few minutes.

**Comment by streetmapp** [comment]
I am seeing this behavior as well. Other details is that this is after using the builder scripts to install the necessary components for a Custom CentOS EKS Worker AMI.

**Comment by PeterGrace** [comment]
This is now happening for me as well, I used the terraform aws eks module to provision, and my autoscaling group is using ami eks-worker-v22.  I'm seeing intermittent "no route to host" on 10250; if I keep trying the same command enough times it will work.

**Comment by cjbottaro** [comment]
Same issue here. Also, so fo my instances are losing `eth1` and then networking becomes all sorts of messed up.

**Comment by conversicachrisr** [comment]
Also appear to be having this issue on v23. Have not tested v21 or v22. v20 based AMI works fine.

**Comment by conversicachrisr** [comment]
I was able to resolve my similar issue by updating my userdata to match the new bootstrap method in the AMI. It may be worth checking to see if this is your issue, it showed under describing the node as such:

```
Warning  MissingClusterDNS        2m (x80 over 32m)  kubelet, <redacted dns of node>    kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
```

This was notified [here](https://aws.amazon.com/about-aws/whats-new/2018/08/new-amazon-eks-optimized-ami-and-cloudformation-template-for-worker-node-provisioning/?sc_channel=em&sc_campaign=Launch_RN20180827&sc_publisher=aws&sc_medium=em_&sc_content=launch_la_nontier1&sc_country=&sc_geo=&sc_category=mult&sc_outcome=launch&mkt_tok=eyJpIjoiTXpKbFpqZzVOV0l3TXprMiIsInQiOiJjaHNSXC9udk5vRUZyb3BSQmlCRWIrczRvTWpLZUYzM1hWY2VJTENUOVZJRm9JMEI0eDZMNlBVYzhPbzBRYkpnRXpxbTljRXh3VG1SUjJvR1ZsRXgzSzZkbEprcGJTZUx6d3BJSzJRWWtBUTZcL0V1NzdVTGt4MmpQTXRBT2hVYkQwIn0%3D) where it says you now must use cloudformation (which seems ridiculous). This is actually not true, as you simply need to build the userdata in the new format.

Userdata looks like this now for terraform generated configs, note I did not need the cfn script listed in their userdata [here](https://github.com/awslabs/amazon-eks-ami/blob/b2f96567dd894a86c5551a1237843829e9059db4/amazon-eks-nodegroup.yaml#L310).
```#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh \
  --use-max-pods ${var.max-pods} \
  --b64-cluster-ca ${aws_eks_cluster.cluster.certificate_authority.0.data} \
  --apiserver-endpoint ${aws_eks_cluster.cluster.endpoint} \
  ${aws_eks_cluster.cluster.id}
```

**Comment by bchav** [comment]
@conversicachrisr I can see how you've gotten that impression! We don't mean that you *have* to use Cloudformation, quite the opposite. The new bootstrapping actually makes it easy to not use Cloudformation.

We mean that you must use the *new* Cloudformation with V23+, the old template won't work. Sorry for the confusion!

**Comment by conversicachrisr** [comment]
No worries, everything is working well for us now. Hopefully this helps some others with the same issue.

**Comment by PeterGrace** [comment]
If the above doesn't solve your issue, for others who might be having this error:  The VPC we provisioned our EKS cluster into was in 172.17.0.0/16.  This collides with Docker's default internal cidr, so this issue was caused for us by that collision.  Check your VPC supernet and make sure you're not conflicting with Docker.

**Comment by alepaez** [comment]
Having the same issue here. 

My vpc was in 172.31.0.0/16, already tried changing it to 10.0.0.0/16.

Changed userdata to updated script but the issue still the same.

```
=====Starting installing AWS-CNI =========
=====Starting amazon-k8s-agent ===========
ERROR: logging before flag.Parse: W0911 20:24:57.044969      13 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

looking my vpc logs I found some rejected connections:

```
version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status
2 669494096318 eni-040b95ab1dba462cd - - - - - - - 1536696872 1536696902 - NODATA
2 669494096318 eni-0a72877ff0404436b - - - - - - - 1536696886 1536696914 - NODATA
2 669494096318 eni-05a3c64416cd316bd 77.72.83.133 10.0.2.100 45096 2008 6 1 40 1536696909 1536696911 REJECT OK
2 669494096318 eni-05a3c64416cd316bd 134.119.193.57 10.0.2.100 40478 20256 6 1 40 1536696909 1536696911 REJECT OK
2 669494096318 eni-03999574f950fed4c 35.164.180.138 10.0.0.188 443 53044 6 66 33708 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 10.0.0.48 10250 59670 6 1 52 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 134.119.193.57 10.0.0.188 40478 21579 6 1 40 1536696893 1536696907 REJECT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.48 10.0.0.188 59670 10250 6 1 52 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 96.244.96.19 39696 123 17 1 76 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 96.244.96.19 10.0.0.188 123 39696 17 1 76 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 35.164.180.138 53044 443 6 66 3726 1536696893 1536696907 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 4.53.160.75 10.0.0.188 123 42654 17 1 76 1536696911 1536696925 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 134.119.193.57 10.0.0.188 40478 56076 6 1 40 1536696911 1536696925 REJECT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 4.53.160.75 42654 123 17 1 76 1536696911 1536696925 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 72.5.72.15 10.0.0.188 123 50684 17 1 76 1536696911 1536696925 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 72.5.72.15 50684 123 17 1 76 1536696911 1536696925 ACCEPT OK
2 669494096318 eni-040b95ab1dba462cd - - - - - - - 1536696933 1536696962 - NODATA
2 669494096318 eni-05a3c64416cd316bd - - - - - - - 1536696939 1536696979 - NODATA
2 669494096318 eni-03999574f950fed4c 10.0.0.188 35.164.180.138 53044 443 6 67 3778 1536696956 1536696966 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 134.119.193.57 10.0.0.188 40478 46545 6 1 40 1536696956 1536696966 REJECT OK
2 669494096318 eni-03999574f950fed4c 35.164.180.138 10.0.0.188 443 53044 6 67 34264 1536696956 1536696966 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 78.128.112.38 10.0.0.188 53459 38388 6 1 40 1536696956 1536696966 REJECT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 10.0.0.48 48508 443 6 1 60 1536696956 1536696966 ACCEPT OK
2 669494096318 eni-05a3c64416cd316bd - - - - - - - 1536696979 1536696991 - NODATA
2 669494096318 eni-03999574f950fed4c 134.119.193.57 10.0.0.188 40478 41705 6 1 40 1536696983 1536696984 REJECT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 45.32.75.249 43906 123 17 1 76 1536696983 1536696984 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 45.32.75.249 10.0.0.188 123 43906 17 1 76 1536696983 1536696984 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 54.70.37.88 10.0.0.188 443 35152 6 348 212171 1536697000 1536697001 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 54.70.37.88 35152 443 6 278 23126 1536697000 1536697001 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 10.0.2.175 10250 56442 6 1 52 1536697000 1536697001 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.2.175 10.0.0.188 56442 10250 6 1 52 1536697000 1536697001 ACCEPT OK
2 669494096318 eni-0a72877ff0404436b - - - - - - - 1536697006 1536697038 - NODATA
2 669494096318 eni-03999574f950fed4c 35.164.180.138 10.0.0.188 443 53044 6 69 34470 1536697017 1536697018 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 35.164.180.138 53044 443 6 68 3882 1536697017 1536697018 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 4.53.160.75 10.0.0.188 123 44347 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 96.244.96.19 46955 123 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 119.144.124.117 10.0.0.188 40004 1433 6 1 40 1536697044 1536697060 REJECT OK
2 669494096318 eni-03999574f950fed4c 96.244.96.19 10.0.0.188 123 46955 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 72.5.72.15 59645 123 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 54.70.37.88 35152 443 6 290 23852 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 72.5.72.15 10.0.0.188 123 59645 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 54.70.37.88 10.0.0.188 443 35152 6 348 210909 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 4.53.160.75 44347 123 17 1 76 1536697044 1536697060 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.48 10.0.0.188 59670 10250 6 1 52 1536697073 1536697078 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 35.164.180.138 53044 443 6 67 3778 1536697073 1536697078 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 35.164.180.138 10.0.0.188 443 53044 6 67 34264 1536697073 1536697078 ACCEPT OK
2 669494096318 eni-03999574f950fed4c 10.0.0.188 10.0.0.48 10250 59670 6 1 52 1536697073 1536697078 ACCEPT OK
```

**Comment by emalihin** [comment]
> Userdata looks like this now for terraform generated configs, note I did not need the cfn script listed in their userdata [here](https://github.com/awslabs/amazon-eks-ami/blob/b2f96567dd894a86c5551a1237843829e9059db4/amazon-eks-nodegroup.yaml#L310).
> 
> ```
> set -o xtrace
> /etc/eks/bootstrap.sh \
>   --use-max-pods ${var.max-pods} \
>   --b64-cluster-ca ${aws_eks_cluster.cluster.certificate_authority.0.data} \
>   --apiserver-endpoint ${aws_eks_cluster.cluster.endpoint} \
>   ${aws_eks_cluster.cluster.id}
> ```

don't forget to include `#!/usr/bin/env bash` on top of your userdata, otherwise provisioning will fail with:
```
Unhandled non-multipart (text/x-not-multipart) userdata: 'set -o xtrace...'
```

**Comment by MBalazs90** [comment]
Seems like this issue still persist:

eu-central-1

```
$ kubectl logs -n kube-system tiller-deploy-778f674bf5-6lwmn
Error from server: Get https://10.0.0.115:10250/containerLogs/kube-system/tiller-deploy-778f674bf5-6lwmn/tiller: dial tcp 10.0.0.115:10250: getsockopt: no route to host
```

**Comment by FreedomBen** [comment]
> If the above doesn't solve your issue, for others who might be having this error: The VPC we provisioned our EKS cluster into was in 172.17.0.0/16. This collides with Docker's default internal cidr, so this issue was caused for us by that collision. Check your VPC supernet and make sure you're not conflicting with Docker.

I apologize this may not be the most appropriate place for a discussion, but our VPC (I'll call it VPC-1 for ease) is also 172.17.0.0/16 and experiences this issue.  Using terraform to create a VPC (I'll call this VPC-2) on 10.0.0.0/16 makes this problem go away, so it does seem to make sense that this could be the problem.  However, I want to understand this deeper, particularly because manually poking around hasn't revealed the problem to me.

In VPC-1, docker appears to create docker0 bridge as 172.18.0.0/16, but in VPC-2 it comes up as default 172.17.0.0/16.  This implies some programmatic forethought.  However, using `docker inspect` to view the networks the pods are attached to, it looks like they aren't attached to docker networks anyway, so I don't understand why docker's internal default network (which again appears to be on a different subnet than the default for VPC-1) would be causing issues.  Using `docker exec` to get into the AWS CNI node reveals that eth0 in the container is on the VPC-1 subnet, which does seem to be a problem.  However, the same thing happens on VPC-2 (which implies that it is intentional), but the intermittent "No route to host" is not a problem there.  

I am surely misunderstanding something about how this all works.  Would appreciate a point in the right direction if anybody has more info to help teach a k8s n00b how to fish :smile: :fishing_pole_and_fish:

**Comment by PeterGrace** [comment]
When the docker daemon comes up, by default, it creates a docker network that routes 172.17.0.0/16 inbound to the docker0 interface.  If your other worker nodes are also in 172.17.0.0/16 via VPC, then packets that kube-proxy might be trying to route will hairpin back to docker0 and have no-route-to-host rather than going out the cni network to the other workers.  I suppose that might be provable by setting externalTrafficPolicy to Local on the service in question and seeing if the problem goes away.  
Unfortunately I don't have an environment to do any kind of tests for this assumption, but that's just my wild guess on it.

**Comment by mogren** [comment]
CIDR check was added to the EKS control plane.

**Comment by CB-GuangyaoXie** [comment]
@mogren Hi, can you elaborate on how the CIDR check works? EKS allows me to create cluster on 172.17.0.0/16. But I'm seeing similar issue.

**Comment by 2tim** [comment]
I'm seeing similar behavior with a 10.133.0.0/18 subnet. The eks api is very intermittent. About every 3rd attempt to access it works. I used the same vpc topology (built with terraform) with kops with no issues. My searching led me here.

**Comment by luvpreetsingh** [comment]
This problem happened to us because initially when we launched the cluster, the Userdata was compatible with the Base AMI we were using for the worker nodes. But then, we updated our Base AMI in the cloudformation, but we did not update the Userdata. So, after struggling for some time, I came here. The solution is @conversicachrisr 's comment.

Your userdata and AMI needs to be compatible
