### ISSUE TITLE
Add metrics/counter for addresses in cooldown period

### ISSUE THREAD

**Issue by dcherman** [aws/amazon-vpc-cni-k8s#1379]
**What would you like to be added**:

A new metric to track the number of addresses in cooldown.

**Why is this needed**:

I've been debugging pod creation delays in some clusters that I support and noted that although the CNI metrics claimed that there was available addresses, those addresses were not being assigned out.  This cluster has somewhat high pod churn, so many of those "available" addresses were likely in the cooldown period, meaning that the actual number of available addresses was likely much lower than I was expecting, though I have little visibility into this right now.  Can we add this as a new metric?

Side note:  30s seems like a very long time to wait for propagation across all nodes.  I'm not aware of any other controller that waits that long before taking actions - can this be lowered or be made configurable?

**Comment by jayanthvn** [comment]
Hi @dcherman 

Nice suggestion to add the addresses in cool down. We will look into it. Yes we have a PR pending merge to make the reconciler configurable #1280 

Thanks!
