### ISSUE TITLE
Upgrading the CNI overwrites the custom configuration options

### ISSUE THREAD

**Issue by philmcdo** [aws/amazon-vpc-cni-k8s#1382]
**What happened**:
When upgrading the CNI with the instructions here [1], several of the custom configuration settings will be lost. This is because the settings are enforced as environment variables in the CNI, and those ENVs are overwritten by the manifest's pod definition. See an example here where the custom networking option is set to false [2]. 

When these settings are overwritten, it can cause undesirable behavior leading to application downtime by doing things like assigning pods to the wrong subnets.

[1] https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html
[2] https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.7/aws-k8s-cni.yaml#L128

**Attach logs**

```
$ kubectl get daemonset aws-node -n kube-system -o json | jq '.spec.template.spec.containers[0].env | .[] | select(.name == "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG")'
{
  "name": "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG",
  "value": "true"
}

$ kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/release-candidate/aws-k8s-cni.yaml
clusterrolebinding.rbac.authorization.k8s.io/aws-node unchanged
clusterrole.rbac.authorization.k8s.io/aws-node unchanged
customresourcedefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com unchanged
daemonset.apps/aws-node configured
serviceaccount/aws-node unchanged

$ kubectl get daemonset aws-node -n kube-system -o json | jq '.spec.template.spec.containers[0].env | .[] | select(.name == "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG")'
{
  "name": "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG",
  "value": "false"
}
```

**What you expected to happen**:
Custom configuration settings should persist through an upgrade of the CNI. 

**How to reproduce it (as minimally and precisely as possible)**:
Create an EKS cluster and add a secondary pod CIDR as per the instructions here: https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/

Upgrade the CNI using the instructions here: https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html

Inspect the pod for the CNI and see that the environment variable for "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG" is set back to false.

**Anything else we need to know?**:
The helm chart manages the CNI environment variables itself and is probably not subject to this issue.

**Comment by philmcdo** [comment]
I've confirmed that upgrading the CNI via Helm preserves the custom settings:

```
$ helm upgrade aws-vpc-cni --namespace kube-system eks/aws-vpc-cni --values values.yaml --set image.tag=v1.7.4
Release "aws-vpc-cni" has been upgraded. Happy Helming!
NAME: aws-vpc-cni
LAST DEPLOYED: Fri Feb 12 09:28:27 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
aws-vpc-cni has been installed or updated. To check the status of pods, run:

kubectl get pods --namespace kube-system -l "app.kubernetes.io/name=aws-node,app.kubernetes.io/instance=aws-vpc-cni"


$ kubectl get daemonset aws-node -n kube-system -o json | jq '.spec.template.spec.containers[0].env | .[] | select(.name == "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG")'
{
  "name": "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG",
  "value": "true"
}


$ helm upgrade aws-vpc-cni --namespace kube-system eks/aws-vpc-cni --values values.yaml --set image.tag=v1.7.8
Release "aws-vpc-cni" has been upgraded. Happy Helming!
NAME: aws-vpc-cni
LAST DEPLOYED: Fri Feb 12 09:29:40 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 5
TEST SUITE: None
NOTES:
aws-vpc-cni has been installed or updated. To check the status of pods, run:

kubectl get pods --namespace kube-system -l "app.kubernetes.io/name=aws-node,app.kubernetes.io/instance=aws-vpc-cni"


$ kubectl get daemonset aws-node -n kube-system -o json | jq '.spec.template.spec.containers[0].env | .[] | select(.name == "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG")'
{
  "name": "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG",
  "value": "true"
}
```

**Comment by jayanthvn** [comment]
Hi @philmcdo 

Yes applying the entire manifest will overwrite the configs previously done, as you mentioned helm upgrade will solve this. Other option is to use EKS managed add-ons (server-side apply [1]). But we are also waiting to merge this PR #1088 and the only downside with config maps today is rolling update is not supported so I am exploring options to get both features - config map and rolling update.

[1] https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-simplifies-installation-and-management-for-kubernetes-cluster-add-ons/

**Comment by overdrive3000** [comment]
HI @jayanthvn.

Maybe a simply change in the documentation can be enough to avoid service disruptions. Instead of showing how to upgrade the CNI by replacing the whole Daemonset manifests, it can show how to upgrade the CNI by applying a `kubectl patch` command and documentation can point out to a `patch-file.yaml` instead of the manifests.

**Comment by fawadkhaliq** [comment]
++, we should update the documentation

We recommend customers to use VPC CNI EKS add-on. EKS add-on uses Kubernetes service side apply and owns only specific fields of the VPC CNI configuration. This allows customers to preserve the configuration on upgrades. (Note: you will need to be on EKS 1.18 + to use EKS add-ons)

Also, we have a pull request to support configuration through ConfigMap https://github.com/aws/amazon-vpc-cni-k8s/pull/1088. With ConfigMap, customers will be upgrade VPC CNI independent of the config. 

If EKS add-ons option doesn't work for your use-case, you can define an upgrade workflow (custom to your use-case and your deployment tool) to handle the config during upgrade

**Comment by jayanthvn** [comment]
Thanks @sheetaljoshi. Documentation is updated with https://github.com/awsdocs/amazon-eks-user-guide/pull/346. We will track the config map changes as part of #1088 .
