### ISSUE TITLE
Problems with source address/snat? on ec2 based kubernetes doesn't happen on eks.

### ISSUE THREAD

**Issue by davidgibbons** [aws/amazon-vpc-cni-k8s#1387]
**What happened**:

We’re having an issue attempting to use the AWS-VPC-CNI in our kubernetes on ec2 cluster. The behavior we’re seeing is that traffic coming out of the pods to other pods or service endpoints are showing up with the source address of the host. This is throwing off some of our monitoring and making us worried about unexpected behavior.

This appears to be divergent from the pattern of traffic out of our EKS cluster and we cannot see any difference in configuration.

To validate this we’ve set up an echoserver pod and ran a rest curl against its service address from the same cluster. From the EKS cluster, this shows the traffic coming from the pod ip address. In the other kubernetes cluster this shows as coming from the hosts ip address.

Example output is included below

We’ve confirmed our aws-vpc-cni (aws_node) configurations are the same between the two sources. Our configurations are included below.

At this point we wonder if there is maybe a host level configuration missing from the installation steps described in the aws-vpc-cni repo. It almost behaves like the local traffic is seen as a different network and attempts to SNAT the traffic but we were unable to find any configuration tuning that defined or controlled when it would attempt to SNAT.

**Environment**:
- Kubernetes version 1.17.5
- CNI Version 1.7.9
- OS Flatcar Linux

The EKS cluster is using version 1.7.5 of the aws-vpc-cni plugin
The kubernetes-on-ec2 cluster is using version 1.7.9. 

These are the env variable we have on the CNI deployments

        Environment:
        HOST_CNI_BIN_PATH:                      /host/etc/kubernetes/cni/bin
        HOST_CNI_CONFDIR_PATH:                  /host/etc/kubernetes/cni/net.d
        ADDITIONAL_ENI_TAGS:                    {}
        AWS_VPC_CNI_NODE_PORT_SUPPORT:          true
        AWS_VPC_ENI_MTU:                        9001
        AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER:  false
        AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG:  false
        AWS_VPC_K8S_CNI_EXTERNALSNAT:           false
        AWS_VPC_K8S_CNI_LOGLEVEL:               DEBUG
        AWS_VPC_K8S_CNI_LOG_FILE:               /host/var/log/aws-routed-eni/ipamd.log
        AWS_VPC_K8S_CNI_RANDOMIZESNAT:          prng
        AWS_VPC_K8S_CNI_VETHPREFIX:             eni
        AWS_VPC_K8S_PLUGIN_LOG_FILE:            /var/log/aws-routed-eni/plugin.log
        AWS_VPC_K8S_PLUGIN_LOG_LEVEL:           DEBUG
        DISABLE_INTROSPECTION:                  false
        DISABLE_METRICS:                        false
        ENABLE_POD_ENI:                         false
        WARM_ENI_TARGET:                        1
        MY_NODE_NAME:                           (v1:spec.nodeName)

We have the same variable set on the EKS cluster except for

        HOST_CNI_BIN_PATH:                      /host/etc/kubernetes/cni/bin
        HOST_CNI_CONFDIR_PATH:                  /host/etc/kubernetes/cni/net.d

When doing a curl to the echoserver on the kubernetes cluster we see the ip of the node rather than the pod.

# kubectl get pods  alpine-w4lrb -n kube-system -o wide
NAME            READY   STATUS  RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
alpine-w4lrb   1/1      Running   0             26h   10.21.5.67   ip-10-21-6-85.ec2.internal   <none>          <none>

# kubectl exec -it alpine-w4lrb -n kube-system ash
/ # curl  echo-service.default.svc.cluster.local
Request served by echo-server-7589b698cd-v6kpz

HTTP/1.1 GET /

Host: echo-service.default.svc.cluster.local
User-Agent: curl/7.69.1
Accept: */*

/ # curl  echo-service.default.svc.cluster.local
Request served by echo-server-7589b698cd-v6kpz

HTTP/1.1 GET /

Host: echo-service.default.svc.cluster.local
User-Agent: curl/7.69.1
Accept: */*

These are the logs from the echoserver which shows the ip from the node not the pod, it should show 10.21.5.67 NOT 10.21.6.85

10.21.6.85:58206 | GET /
10.21.6.85:31248 | GET /
10.21.6.85:42503 | GET /
10.21.6.85:31907 | GET /

When doing a curl on the EKS cluster we get the correct ip of the pod

aws-kubectl get pods  alpine -n infrastructure -o wide
NAME    READY   STATUS  RESTARTS   AGE  IP              NODE                            NOMINATED NODE   READINESS GATES
alpine   1/1    Running   2             125m   10.21.11.139   ip-10-21-11-86.ec2.internal   <none>              <none>

aws-kubectl exec -it alpine -n infrastructure ash
/ # curl        echo-service.infrastructure.svc.cluster.local
Request served by echo-deployment-6dc7d7968-25zlw

HTTP/1.1 GET /

Host: echo-service.infrastructure.svc.cluster.local
User-Agent: curl/7.52.1
Accept: */*

/ # curl        echo-service.infrastructure.svc.cluster.local
Request served by echo-deployment-6dc7d7968-25zlw

HTTP/1.1 GET /

Host: echo-service.infrastructure.svc.cluster.local
User-Agent: curl

These are the logs from the echoserver, which shows the correct IP of the pod rather than the node IP

10.21.11.139:34558 | GET /
10.21.11.139:52438 | GET /
10.21.11.139:52442 | GET /
10.21.11.139:52444 | GET /
10.21.11.139:52626 | GET /
10.21.11.139:52632 | GET /

**Comment by jayanthvn** [comment]
Hi,

We are looking into it. Will get back to you ASAP.

Thank you!

**Comment by davidgibbons** [comment]
The resulting tarball was too large for github, Let me know if this slack file link works: 
https://slack-files.com/T0287AG68-F01RAPDJMV2-b80245b2e8

**Comment by jayanthvn** [comment]
Thanks, will look into it.

**Comment by nithu0115** [comment]
As per conversation over the call, we saw a masquerade rule which was SNAT all traffic going out of the node. As discussed, you will keep both EKS/K8s on AWS cluster kube-proxy daemonSet uniform. Let us know if you are still running into any issues.

**Comment by jayanthvn** [comment]
Closing the issue, please let us know if you need any help.
