### ISSUE TITLE
China VPC CNI error: "memcache.go:138 couldn't get current server API group list"

### ISSUE THREAD

**Issue by marcincuber** [aws/amazon-vpc-cni-k8s#1389]
**What happened**:

VPC CNI is outputs error logs
**Attach logs**

```
ERROR: logging before flag.Parse: E0223 07:00:18.075391      10 memcache.go:138] couldn't get current server API group list; will keep using cached value. (Get https://172.20.0.1:443/api?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers))
```

**What you expected to happen**:
No error showing.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy latest cni
**Anything else we need to know?**:
n/a
**Environment**:
- Kubernetes version: 1.19
- CNI Version: 918309763551.dkr.ecr.cn-north-1.amazonaws.com.cn/amazon-k8s-cni:v1.7.9-eksbuild.1

**Comment by achevuru** [comment]
#1078

**Comment by jayanthvn** [comment]
Hi @marcincuber

Can you please confirm if you are seeing these messages "Failed to retrieve node info: nodes **** " in kube-proxy logs? Also does aws-node comes up fine after kube-proxy is up?

Thank you!

**Comment by marcincuber** [comment]
Yeah, after a few moments it is fine. So I guess it needs to wait for kube-proxy to run in first place.

**Comment by jayanthvn** [comment]
Hi @marcincuber 

This is a known issue are we are tracking it as part of #1078 . Will post updates there.

Thanks.
