### ISSUE TITLE
AWS EKS - failed to assign an IP address to container 

### ISSUE THREAD

**Issue by adhityan** [aws/amazon-vpc-cni-k8s#1391]
**What happened**:
Anytime we try to launch a pod it fails to provision it with the below error. The cluster has both fargate and nodegroups. There should be more than enough free IPs available.

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "89a7c4d0455147ea9eeece8b9bd12059835b40cec28be6b1b4988ce69fc312a8" network for pod "insta-service-6b959c8fdd-cw5pm": networkPlugin cni failed to set up pod "insta-service-6b959c8fdd-cw5pm_insta-service" network: add cmd: failed to assign an IP address to container`

**What you expected to happen**:
Pod to be created successfully

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod.

**Anything else we need to know?**:
The cluster is a new cluster provisioned using terraform. This may also be a reopen of https://github.com/aws/amazon-vpc-cni-k8s/issues/1245

**Environment**:
- Kubernetes version: 1.19
- CNI Version: 1.7.9
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.4.91-41.139.amzn2.x86_64

**Comment by adhityan** [comment]
Closing the issue as pod creation is resolved now. Looks like there is about > 10 minutes of wait time before the IP addresses are cleaned up after upgrading CNI.

**Comment by adhityan** [comment]
> Closing the issue as pod creation is resolved now. Looks like there is about > 10 minutes of wait time before the IP addresses are cleaned up after upgrading CNI.

This was only temporary. Issue has recurred again / is intermittent. Seeing the same issue again.

**Comment by couralex6** [comment]
Hi @adhityan, I'm looking into this. Could you send me your cluster ARN as well as the ipamd and plugin logs (under /var/log/aws-routed-eni/) by email: courouba@amazon.com

Thank you!

**Comment by adhityan** [comment]
@couralex6 thanks for the followup. I am closing the issue after more debugging at my end. 

For those facing similar issues / are interested - 

1. Each instance on the node-grpups have a maximum limit on the number of IP addresses that they support based on their instance type -
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI 

2. You can check the current status of this allocation for each node by asking a report from the aws-node pod from the CNI demonset running on that node. The command is `curl http://localhost:61679/v1/enis | python -m json.tool`. For more details, you should read https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md

In my case, I was running very workloads (dev/qa) outside fargate and I was only running a few T2.smalls in my node-groups. Whenever an helm install updated a number of pods, the required AssignedIPs temporarily became equal to TotalIPs while the previous pods were cleaned-up. Once that happens, the issue was being auto-resolved.

Do note that this is a similar but completely different issue from the one in #1245. I had to update my CNI plugin to 1.7.9 from 1.7.5 to resolve the issue from #1245.
