### ISSUE TITLE
Any plans on dropping dockershim?

### ISSUE THREAD

**Issue by njuettner** [aws/amazon-vpc-cni-k8s#1397]
Hey folks 👋🏻 ,

we're currently investigating CAPI/CAPA and we'd like to know if there's a plan to drop `dockershim` from `aws-cni`? We'd like to drop docker completely and use containerd. 
I saw there was already an issue created ~1 year old but I'd like to know if anything has changed so far.

 DaemonSet Volume Mount:

            - mountPath: /var/run/dockershim.sock
              name: dockershim

Ref.: https://github.com/aws/amazon-vpc-cni-k8s/issues/971

**Comment by couralex6** [comment]
Hi @njuettner,

We are planning on removing the `dockershim` mount in release v1.8, going out early April.

This is the PR that removes the mount: #1352.

**Comment by haouc** [comment]
We have announced support to containerd as an option in EKS1.21 release. Please refer to [this document](https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/).

**Comment by njuettner** [comment]
@haouc that is really nice you supporting containerd for EKS but what if someone don't use EKS, you can also use CAPA without any EKS. The PR @couralex6 mentioned is still not merged, so I'm a bit confused why you're closing the issue.

Maybe I'm missing something, but I'd appreciate if someone could shed some light 🙂

**Comment by haouc** [comment]
@njuettner 
You are right. My bad. I will reopen this issue. We are still working to make a clean path for customers to migrate to docker independent AWS VPC CNI.

**Comment by njuettner** [comment]
@haouc any updates here 🙂?

**Comment by haouc** [comment]
Hey @njuettner thanks for checking on this. Yes, we are working on this currently.

**Comment by anguslees** [comment]
(noise comment to reset the stale counter)

**Comment by ankitjain28may** [comment]
Hey folks, Do we have any way to migrate to contained from dockershim without facing any downtime? we are managing our k8s cluster using kops.

**Comment by jayanthvn** [comment]
v1.12 release is out and dockershim is removed from manifest. Closing this issue.
