### ISSUE TITLE
do not DeleteNetworkInterface when it is still in use or silence the failure

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1399]
we monitor cni errors and get a lot of these:
```
   errorCode: Client.InvalidParameterValue
   errorMessage: Network interface 'eni-0bb6d5cc5ed4f5140' is currently in use.
```

Which looks like it’s a race condition where it attempts to delete the network interface while it’s still in use/attached, and then just retries where it succeeds.

Would be great if this was not thrown as error (at least on the initial try) so we can keep our error log/metric clean.

**Comment by jayanthvn** [comment]
Hi @grosser 

Looks like in your cluster detach is taking more time and so delete is throwing this error, there is a 2 sec delay between detach and delete but seems like it is not sufficient. These failures are critical to log in other debug scenarios such as to find the number of ec2 calls, number of eni delete failures and so on. Is it possible in your metric collector to ignore these errors? Something like if eventually an ENI is deleted ignore previous failed attempts? Please let me know your thoughts.

Thank you!

**Comment by grosser** [comment]
I can't easily ignore them ... is there a way to configure the delay instead ? (does it need to be 2s ?)

**Comment by grosser** [comment]
I was hoping it could `detach check check check delete` to avoid the delete from showing errors

**Comment by haouc** [comment]
Hey @grosser 

I think this is a good point that we can handle the error logging more gracefully. I am looking into this. Thanks.

**Comment by DanOfir** [comment]
any workaround here? it's making the entire ec2 reach the rate limit

**Comment by jayanthvn** [comment]
> any workaround here? it's making the entire ec2 reach the rate limit

Hi, Can you please expand more on this? Are you reaching API rate limit because we keep retrying delete while detach is still under process? Or are you seeing ENIs in the account while cluster is deleted?

**Comment by haouc** [comment]
This need some investigation since it sounds like a still-active issue. In general this should be a harmless behavior with eventual success. But in some environment, unnecessary EC2 API calls could be expensive to users.
