### ISSUE TITLE
Produce a versioned artifact for programatic consumption

### ISSUE THREAD

**Issue by geojaz** [aws/amazon-vpc-cni-k8s#14]
We're interested in consuming this plugin via kops.

I understand this is pre-release, but could you give us a tag? Just so we don't have to use latest: `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:latest`

Thanks

**Comment by liwenwu-amazon** [comment]
Here is the tag for version **0.1.1**
**602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:0.1.1**

**Comment by liwenwu-amazon** [comment]
I am closing this for now. Please reopen it if you still have issues with this. thanks.

**Comment by geojaz** [comment]
excellent thanks :)
