### ISSUE TITLE
Custom Networking Feature Requires Node Reboot

### ISSUE THREAD

**Issue by jwenz723** [aws/amazon-vpc-cni-k8s#1403]
**What would you like to be added**:

Currently all nodes that exist before Custom Networking is enabled must be rebooted after enabling/disabling Custom Networking. This is documented in step 9 [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html). Please update the CNI to be able to handle 'Custom Networking' to be enabled/disabled without requiring nodes to be rebooted.

**Why is this needed**:

It is an inconvenience to have to reboot nodes after enabling Custom Networking.

In my EKS setup I use terraform to manage the creation of my EKS cluster and nodes. I use ArgoCD with a GitOps approach for managing the configuration of the AWS VPC CNI and ENIConfig resources. I have to create the nodes before ArgoCD can run. This means that after ArgoCD syncs the AWS VPC CNI and ENIConfig resources I have to manually reboot the nodes for the 'Custom Networking' feature to take effect.

**Comment by jayanthvn** [comment]
Hi @jwenz723 

The reason custom networking will need nodes reboot because of these reasons - 

1. If secondary ENIs are attached we need reassignment with secondary cidr
2. if there are any running pods, we need to restart the pods to use secondary CIDR since we cannot evict the running pod.

Hope this clarifies.

**Comment by jwenz723** [comment]
@jayanthvn if all pods are forcefully deleted (i.e. `kubectl delete pods --all -A`) will that cause new secondary ENIs to be attached with the secondary cidr?

**Comment by jayanthvn** [comment]
Yes you can do that, but you will have to wait for the ENIs to be freed. IPs will be in cool down cache for 10 seconds and then based on the WARM ENI TARGET and WARM IP TARGET, ENIs will be released. Say for instance t3.small supports 6 IPs per ENI, if either you have WARM ENI TARGET as 1 (which is set by default in the manifest) or if you have WARM_IP_TARGET as 7, then one full ENI will be kept in IPAMD's cache which will not get freed even if you force delete the pods. Please let me know if this helps.

**Comment by jwenz723** [comment]
Would it be possible to implement the VPC CNI Custom Networking as a feature in the EKS vpc-cni Add-On? Maybe this could allow the Add-On to intelligently determine if a node needs to be rebooted or terminated? Seems like this could be accomplished with Managed EKS Node Groups.

I'm fully aware of how to get the Custom Networking feature working on my EKS clusters, I'm just curious if anything can be done to make the enablement/disablement of this feature easier.

**Comment by jayanthvn** [comment]
Yes we completely agree with you and we will work towards making this feature toggling better in future. @mikestef9 can share our thought process here to gather initial feedback. Having said that, will bring it up with AddOn team if they can manage node reboot when customNetworking is toggled

**Comment by jayanthvn** [comment]
Hi,

We are tracking CNI custom networking simplification as part of AWS container-roadmap. We will evaluate how this enhancement can be implemented. So will be closing the issue here and provide updates as part of https://github.com/aws/containers-roadmap/issues/867.

Thank you!
