### ISSUE TITLE
Error assigning IPv4 address not handled 

### ISSUE THREAD

**Issue by adammw** [aws/amazon-vpc-cni-k8s#1405]
err is assigned but overwritten before being checked 
https://github.com/aws/amazon-vpc-cni-k8s/blob/60d3c20de20c7fb4b679747fb14e3d79a1c94321/pkg/ipamd/rpc_handler.go#L141

**Comment by adammw** [comment]
Also I think there's a race condition where the request for an IP address can come before the CNI plugin has attached ENIs, therefore commonly logging "DataStore has no available IP addresses" on node bootstrap.

**Comment by jayanthvn** [comment]
Hi @adammw 

Thank you and we are happy to take PRs.

Regarding the race condition, yes on bootstrap once kubelet finds the CNI binary will start pumping in the IP requests and IPAMD might still be processing the ENI/IP allocation. These are 2 independent components and eventually all pods get IP unless there is an IP/ENI exhaustion.

**Comment by haouc** [comment]
Hey @adammw

The error is used when constructing response and logged afterwards. I am not sure what you mean about overwritten. But we are happy to take PRs if you still have concerns. Thanks.

**Comment by haouc** [comment]
Hey @adammw, this has been open for a while and want to follow up if you still have any concern on this? Or you are planning to send a CR soon? Thanks.

**Comment by adammw** [comment]
the original error seems to be fixed since the error was reported, as the code now checks the `err` variable before reusing it elswhere.

https://github.com/aws/amazon-vpc-cni-k8s/blob/ea4de0e89e5b08cda8ab5fa8dfa32cec54b7d7aa/pkg/ipamd/rpc_handler.go#L141-L145

will close this issue.
