### ISSUE TITLE
CNI Metrics Helper does not publish or expose aggregate metrics on port 61678

### ISSUE THREAD

**Issue by jsanghi** [aws/amazon-vpc-cni-k8s#1413]
**What would you like to be added**:

- Aggregate Open metrics for cni-metrics-helper published on Port 61678 for Prometheus collection
- Updates to the README to make it clear that currently the application does not publish open metrics for datadog or prometheus collection

**Why is this needed**:
The README specifies that metrics are published on :61678/metrics by default:  https://github.com/aws/amazon-vpc-cni-k8s/tree/master/cmd/cni-metrics-helper
`By default ipamd will publish prometheus metrics on :61678/metrics.`

Going to the source, there doesn't seem to be any mechanism to serve these aggregate metrics from the pod.  Also, the readme states that if Cloudwatch is "false", you need to periodically pull metrics from the log files.  It would be helpful to make this a bit more clear as I spent time debugging the app, kube deployment, datadog annotations, etc, in an attempt to pull these metrics directly with the datadog agent, rather than go through Cloudwatch.

For future enhancement, it would be great to open a port to expose these open metrics.

Thank you!
Jason

**Comment by jayanthvn** [comment]
Hi @jsanghi 

CNI metrics helper does compute the aggregated metrics published by IPAMD(aws-node) from port 61678 

Ref -
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/metrics/cni_metrics.go#L27
https://github.com/aws/amazon-vpc-cni-k8s/blob/a9c92f52a6d6815e5f626b0f7ff9e72b68ac3d70/cmd/cni-metrics-helper/metrics/metrics.go#L84

**Comment by jsanghi** [comment]
Hello @jayanthvn, thank you for looking into this.

The issue is not that computation of the aggregate metics (these work and are sent to Cloudwatch).  But the cni-metrics-helper application itself does not expose the aggregate metrics for Prometheus collection.

If  USE_CLOUDWATCH = "false", the only way to gather the metrics is to query the logs.  I am looking for the application to serve these metrics 

Please correct me if wrong, but otherwise I would need to collect individual metrics from each aws-node pod, rather than aggregate metrics direct from the cni-metrics-helper deployment.

**Comment by achevuru** [comment]
@jsanghi Yes, you are correct. `cni-metrics-helper` will collect Prometheus metrics from individual CNI pods, aggregate them and publish to Cloudwatch. It currently doesn't expose any metrics endpoint for an external service to query these aggregated metrics. cni-metrics-helper [README](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/cmd/cni-metrics-helper#cni-metrics-helper) -  calls it out as well.

We can definitely try to expose them via an endpoint as you're suggesting but just curious why not use the [aggregator operators](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators) that Prometheus provides by default?
