### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by mveitas** [aws/amazon-vpc-cni-k8s#1415]
**What happened**:
We are seeing a potential memory leak for the aws cni container provided by AWS in our EKS cluster. Below is the memory usage over the past month. We have seen a few restarts of the pods that were caused by OOM error. We have taken steps to increase the memory allocation for the pod.

We are seeing this across all of our 6 clusters that we are running.

![Screen Shot 2021-04-06 at 11 53 24 AM](https://user-images.githubusercontent.com/439521/113740487-ba6bfa00-96ce-11eb-8d0e-33a4068416c3.png)

**Environment**:
- EKS 1.18
- 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.7.5
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- OS: Ubuntu 18.04
- Kernel: Linux XXXXXX 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jayanthvn** [comment]
Hi @mveitas 

Can you please share the logs on one of the nodes where you are seeing the issue - `sudo bash /opt/cni/bin/aws-cni-support.sh`

Will do an initial triage and reach out to you for getting more logs/information. Also is there any pod churn happening and what is the instance type and scale of nodes/pods?

Thanks!

**Comment by mveitas** [comment]
@jayanthvn The churn rate on the pods is not high (maybe 1x per week), but pending additional cluster usage, we would rather not see this happen more frequently and affect something.

We are running `m5.2xlarge` instance types now with cluster ranging from 12 to 18 nodes (depending on which cluster). We are typically running about 30-40 pods per host now.

With regards to the logs, I'll open an AWS support case to attach the logs to so they aren't floating out in the public and provide the case ID

**Comment by jayanthvn** [comment]
Thanks, makes sense on attaching the details with AWS support case.

**Comment by mveitas** [comment]
I posted a support case in our account with the output of the logs

**Comment by haouc** [comment]
@mveitas 
Are you still seeing this issue? Thanks.
