### ISSUE TITLE
Calico manifest doesn't work with k8s 1.11

### ISSUE THREAD

**Issue by xdrus** [aws/amazon-vpc-cni-k8s#142]
Hello,

The current [calico manifest](config/v1.1/calico.yaml) can't be deployed in self-hosted 1.11.x k8s because of "description" field that is [not a part of CustomResourceDefinition spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#customresourcedefinition-v1beta1-apiextensions-k8s-io)

> error: error validating "/etc/kubernetes/addons/50_calico.yaml": error validating data: ValidationError(CustomResourceDefinition): unknown field "description" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition; if you choose to ignore these errors, turn validation off with --validate=false

As far as I understand [a new validation was implemented in 1.11](https://github.com/kubernetes/kubernetes/pull/64267) to check this.

Also: https://github.com/projectcalico/canal/issues/129

Removing these lines fixes it:

```diff
125d130
< description: Calico Felix Configuration
141d145
< description: Calico BGP Configuration
157d160
< description: Calico IP Pools
173d175
< description: Calico Host Endpoints
189d190
< description: Calico Cluster Information
205d205
< description: Calico Global Network Policies
221d220
< description: Calico Global Network Sets
237d235
< description: Calico Network Policies
```

Best,
Ruslan.

**Comment by bcreane** [comment]
@liwenwu-amazon, please reassign this issue to me (Casey is offline). Thanks

**Comment by eswarbala** [comment]
Fix is now merged into master. Closing this out
