### ISSUE TITLE
How to migrate to containerd

### ISSUE THREAD

**Issue by SimplySeth** [aws/amazon-vpc-cni-k8s#1421]
How do I migrate to containerd?

**What happened**:

replaced `/var/run/docker.sock` with `/var/run/containerd/containerd.sock` in the daemonset manifest

set `WATCH_NAMESPACE` in the env for the container  (previous log had error saying to enable this)

**Environment**:
- Kubernetes: 1.18 
- CNI Version: 1.7.5
- OS: CentOS 7 Linux

**Results:**

**log:**
```
time="2021-04-08T00:01:22Z" level=error msg="failed to create service for operator metrics: services is forbidden: User \"system:serviceaccount:kube-
```

**k describe pod:**

```
Warning  Unhealthy         53s                kubelet            Readiness probe failed: {"level":"info","ts":"2021-04-07T23:59:55.011Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}

**Comment by jayanthvn** [comment]
Hi @SimplySeth 

Yes just updating the manifest won't be sufficient. Did you do the below steps -

1. stop kubelet
2. delete all docker containers
3. remove docker
4. install containderd
5. start containerd
6. Remove docker service from `/etc/systemd/system/kubelet.service`
7. Add this -` --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock'` to kubelet args
8. Start kubelet

We are planning to put a doc on the steps needed to migrate to containerd.

**Comment by SimplySeth** [comment]
Containerd is already running on the nodes. 
I'll add the kubelet args, thanks.

**Comment by SimplySeth** [comment]
Containerd is already running on the nodes. 
I'll add the kubelet args, thanks.
