### ISSUE TITLE
Tigera Operator attempts to schedule on Fargate nodes despite this being unsupported

### ISSUE THREAD

**Issue by bcbrockway** [aws/amazon-vpc-cni-k8s#1429]
**What happened**:

Following [these docs](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) with a few of our pods scheduled on Fargate, a DaemonSet is created that doesn't distinguish between EC2 and Fargate nodes so we end up with a load of pending pods that will never be scheduled.

```
$ k get pods -n calico-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-5d786d9bbc-dpgw7   1/1     Running   0          99s
calico-node-4mplm                          1/1     Running   0          99s
calico-node-6l5dm                          0/1     Pending   0          99s
calico-node-7jbbn                          1/1     Running   0          99s
calico-node-97q74                          1/1     Running   0          99s
calico-node-9zs4v                          1/1     Running   0          99s
calico-node-g6x97                          1/1     Running   0          99s
calico-node-phc56                          0/1     Pending   0          100s
calico-node-sfhkb                          0/1     Pending   0          99s
calico-node-vl9cq                          1/1     Running   0          99s
calico-node-whgcr                          0/1     Pending   0          99s
calico-typha-68bcdfb7bf-m67jc              1/1     Running   0          100s

$ k get daemonset
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   10        10        6       10           6           kubernetes.io/os=linux   62s
```

**What you expected to happen**:

The DaemonSet would only schedule pods on EC2 nodes (perhaps with `nodeSelector: eks.amazonaws.com/compute-type=ec2`?).

**How to reproduce it (as minimally and precisely as possible)**:

Start an EKS cluster with something running on Fargate and deploy Calico using the official method.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19
- CNI Version: v1.7.5
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.4.105-48.177.amzn2.x86_64

**Comment by jayanthvn** [comment]
Hi @bcbrockway 

Yes, we can add the nodeSelector as you mentioned. Today we do this for aws-node - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni-cn.yaml#L100. We are happy to take PRs.

**Comment by tmjd** [comment]
The doc @bcbrockway linked to clearly states
> Calico is not supported when using Fargate with Amazon EKS.

So I'm not sure I'd classify this as a bug, because the directions are not being followed.

This could be addressed by adding some logic to the operator here https://github.com/tigera/operator/blob/3ee2a1c36b8c4858c0a432c822a4067dfcce08d7/pkg/render/node.go#L619 for when ProviderEKS to set the nodeSelector as @jayanthvn suggests. I'd be happy review a PR that does this.

**Comment by jayanthvn** [comment]
Created an issue in Tigera operator repo to track this issue - https://github.com/tigera/operator/issues/1438
