### ISSUE TITLE
[IRSA alternative] Why AWS_SHARED_CREDENTIALS_FILE is not detected?

### ISSUE THREAD

**Issue by victoraldir** [aws/amazon-vpc-cni-k8s#1433]
**What happened**:

Hello! 
I have been through this challenge for this whole week now, and now I decided to share this questions with you. 

Basically, I have one goal. I **want to remove the policy** `AmazonEKS_CNI_Policy` **from the Amazon EKS node IAM role, but I can't use the [IRSA solution](https://aws.amazon.com/es/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/)**. 

Why not IRSA?

Given the fact that each cluster needs an OIDC in order to get IRSA enabled, this would lead me to a hard limit of 100 cluster per account, as AWS just offer 100 OIDC per account. This happens to be a problem for my solution.

Workaround

![hadmade_aws_credentials_injection (3)](https://user-images.githubusercontent.com/881964/115474278-82f36680-a213-11eb-9912-1b0dab6a79e7.png)

We are okay with the idea of giving user's credentials (not temporary, I know) to VPC CNI. But we would like to rotate this credentials without a new deployment, so we came up with the idea of mounting volumes from secrets within user's credentials. With this file in place, it is just a matter of declaring **AWS_SHARED_CREDENTIALS_FILE** env variable with the reference to the path of volume mounted so that AWS SDK can use the configuration file

This works just fine with AWS CLI so I thought it would be the same with VPC CNI, as it uses aws-sdk-go underlying. The thing is it doesn't. Any suggestion of how to get this done?

**Environment**:
- Kubernetes version (use `kubectl version`):

`Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

- CNI Version

amazon-k8s-cni:v1.7.5-eksbuild.1

- OS (e.g: `cat /etc/os-release`):

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

****

**Comment by ptzianos** [comment]
@victoraldir I just saw this and wanted to ask if you have tried setting up an external OIDC provider such as AWS Cognito to have a centralized registry of your users.
