### ISSUE TITLE
AWS EKS upgrade 1.16 to 1.17 fails with "cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d"

### ISSUE THREAD

**Issue by alnhk** [aws/amazon-vpc-cni-k8s#1442]
When upgrading the AWS EKS from 1.16 to 1.17, we are observed all EKS Worker nodes  with status "Not Ready".  

**What happened**:
When checked the kubelet log message, observed below :
`Apr 24 17:40:58 ip-192-168-58-207 kubelet: W0424 17:40:58.005255    5347 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.dApr 24 17:40:58 ip-192-168-18-101 kubelet: E0424 17:40:58.903012    5347 kubelet.go:2195] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
`

**Attach logs**
followed this link - https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html
```
amazon-k8s-cni-init:v1.7.10
amazon-k8s-cni:v1.7.10
```
Also, applied 
`
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml
`

we deleted the EKS worker node, and new node was added, yet we still encounter status "Not Ready".  Please advise the resolution.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-c5067d", GitCommit:"c5067dd1eb324e934de1f5bd4c593b3cddc19d88", GitTreeState:"clean", BuildDate:"2021-03-05T23:39:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version
```
amazon-k8s-cni-init:v1.7.10
amazon-k8s-cni:v1.7.10
```

- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-192-168-18-101 4.14.225-169.362.amzn2.x86_64 #1 SMP Mon Mar 22 20:14:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Also, as per log, there is nothing under 
```
/etc/cni/net.d
```

AMI version is 
```
v1.17.12-eks-7684af
```
and result of " cat /etc/eks/release" 
```
BASE_AMI_ID="ami-0849ada759754b5f5"
BUILD_TIME="Wed Apr 14 20:18:45 UTC 2021"BUILD_KERNEL="4.14.225-169.362.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by jayanthvn** [comment]
Hi @alnhk 

Is the issue seen on all nodes? Can you please email me (varavaj@amazon.com) logs generated from `sudo bash /opt/cni/bin/aws-cni-support.sh` on one of the nodes which has the issue?

Thanks!

**Comment by alnhk** [comment]
Hello @jayanthvn : this is happening on all nodes.  Should we run /opt/cni/bin/aws-cni-support.sh on all nodes ?

**Comment by alnhk** [comment]
Ran `/opt/cni/bin/aws-cni-support.sh` on one of the node and below is the result 
```

        This is version 0.6.2. New versions can be found at https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/

Trying to collect common operating system logs...
Trying to collect kernel logs...
Trying to collect mount points and volume information...
Trying to collect SELinux status...
Trying to collect iptables information...
Trying to collect installed packages...
Trying to collect active system services...
Trying to Collect Containerd daemon information...
Trying to collect Docker daemon information...
Trying to collect kubelet information...
Trying to collect L-IPAMD introspection information... Trying to collect L-IPAMD prometheus metrics... Trying to collect L-IPAMD checkpoint... cp: cannot stat '/var/run/aws-node/ipam.json': No such file or directory

Trying to collect sysctls information...
Trying to collect networking infomation... conntrack v1.4.4 (conntrack-tools): 151 flow entries have been shown.

Trying to collect CNI configuration information... cp: cannot stat '/etc/cni/net.d/*': No such file or directory

Trying to collect Docker daemon logs...
Trying to archive gathered information...

        Done... your bundled logs are located in /var/log/eks_i-0675683d1d04a1157_2021-04-25_0528-UTC_0.6.2.tar.gz

```

The file  is shared with you.

**Comment by jayanthvn** [comment]
Thank you!. I haven't yet received the file. Can you please recheck?

**Comment by alnhk** [comment]
Hello Jayanth :  Just sent. Please review.

**Comment by jayanthvn** [comment]
Hi Hari,

Can you please check if kube-proxy is running? IPAMD is not able to connect to API server hence aws-node is unable to start.

```
{"level":"info","ts":"2021-04-23T10:05:59.199Z","caller":"aws-k8s-agent/main.go:28","msg":"Starting L-IPAMD v1.7.10  ..."}
{"level":"error","ts":"2021-04-23T10:06:59.201Z","caller":"aws-k8s-agent/main.go:28","msg":"Failed to create client: error communicating with apiserver: Get https://10.100.0.1:443/version?timeout=32s: dial tcp 10.100.0.1:443: i/o timeout"}
```

In the logs bundle, in kube-proxy.log, I see this error - 

```
Error: unknown flag: --resource-container
```

Was this working with 1.16? Because In the docs [https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html] , I see this - "If you originally created an Amazon EKS cluster with Kubernetes version 1.11 or earlier and haven't removed the --resource-container flag from the kube-proxy DaemonSet, then updating to Kubernetes 1.16 will cause kube-proxy failures. This flag is no longer supported in Kubernetes 1.16. For more information, see kube-proxy in Kubernetes 1.16 Deprecations and removals. You must remove this flag before updating to Kubernetes 1.16."

What is the current kube-proxy version? Maybe you can try updating kube-proxy to 1.17.9 (recommended version for 1.17).

**Comment by alnhk** [comment]
Yes in 1.16, it was working, regarding kube-proxy version we are using this
``` 
Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.17.9-eksbuild.1
```

coming to. flag "--resource-container", it is showing here 
```
 Command:
      /bin/sh
      -c
      kube-proxy --resource-container="" --oom-score-adj=-998 --master=https://5e070f09771432737d309cb81f051f78.sk1.us-west-2.eks.amazonaws.com --kubeconfig=/var/lib/kube-proxy/kubeconfig --proxy-mode=iptables --v=2 1>>/var/log/kube-proxy.log 2>&1
```

Should we remove this flag  and try again ?

**Comment by alnhk** [comment]
Okay - after removing the flag "--resource-container" from kube-proxy, all the kube-proxy pod is now showing "running", re-applied aws-k8s-cni.yaml and reported all good.
