### ISSUE TITLE
possible solutions for max ip and max eni 

### ISSUE THREAD

**Issue by ksaritek** [aws/amazon-vpc-cni-k8s#1446]
**What happened**:
we are running jobs which are scheduled as every minute. we are having problems with IPs in the cooldown period and available max IP limits. So, pods could not start because of `DataStore has no available IP addresses` error.

Is there a way to increase the IP address capacity or running whole jobs with the same Eni? 

regarding to the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI, 
we are using m5.large and they have max 27 IP addresses.

**Environment**:
- Kubernetes version: v1.16.15-eks-ad4801
- CNI Version: 1.7.10

**Comment by jayanthvn** [comment]
Hi @ksaritek 

We are working on this effort - https://github.com/aws/containers-roadmap/issues/138. This should increase the pod density on the instances.

Thanks!

**Comment by hiago-miguel** [comment]
Hi @jayanthvn 

Is there any expected date for this?
Thanks!

**Comment by jayanthvn** [comment]
Hi,

Will provide updates on release/timelines here - https://github.com/aws/containers-roadmap/issues/138# so closing this issue.
