### ISSUE TITLE
Unable to update cni config: no networks found in /etc/cni/net.d

### ISSUE THREAD

**Issue by syedaliammar** [aws/amazon-vpc-cni-k8s#1450]
Hi, I am currently attempting to create a simple AWS EKS cluster and the nodes always run into the creation failure health issue. Could someone point me in the right direction? Details below:

**Environment**:
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version: `amazon-k8s-cni:v1.7.10-eksbuild.1`
- OS (e.g: `cat /etc/os-release`): `CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"`
- Kernel (e.g. `uname -a`): Linux ip-REDACTED.eu-west-1.compute.internal 4.14.225-169.362.amzn2.x86_64

**Issue**:
We see the following errors in the POD messages and the nodes always face NodeCreationFailure issue:
```
cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
kubelet.go:2195] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
**Further details**:
- Here's what `kubectl get pods -A` reveals:
```
NAMESPACE     NAME                       READY   STATUS              RESTARTS   AGE
kube-system   aws-node-7zvlj             0/1     Init:0/1            0          24h
kube-system   aws-node-d8tmz             0/1     Init:0/1            0          24h
kube-system   coredns-6d97dc4b59-4frw9   0/1     Pending             0          3d20h
kube-system   coredns-6d97dc4b59-t7b9f   0/1     Pending             0          3d20h
kube-system   kube-proxy-cpdwt           0/1     ContainerCreating   0          24h
kube-system   kube-proxy-r7v99           0/1     ContainerCreating   0          24h
```
- Running `kubectl get nodes` gives:
```
NAME                                            STATUS     ROLES    AGE   VERSION
ip-REDACTED.eu-west-1.compute.internal   NotReady   <none>   24h   v1.18.9-eks-d1db3c
ip-REDACTED.eu-west-1.compute.internal     NotReady   <none>   24h   v1.18.9-eks-d1db3c
```
The cluster was created using the following command and the API server endpoint access is "Public and private":
`aws eks create-cluster --region eu-west-1 --name $cluster_name --kubernetes-version 1.18 --role-arn arn:aws:iam::REDACTED:role/my.eks.iam.role --resources-vpc-config subnetIds=subnet-REDACTED1,subnet-REDACTED2,subnet-REDACTED3`

The node group was created using:
`aws eks create-nodegroup --cluster-name $cluster_name --nodegroup-name $nodegroup_name --node-role arn:aws:iam::REDACTED:role/my.node.iam.role --ami-type AL2_x86_64 --instance-types t3.medium --scaling-config minSize=2,maxSize=2,desiredSize=2 --remote-access ec2SshKey=$ssh_keypair,sourceSecurityGroups=sg-REDACTED --subnets "subnet-REDACTED1" "subnet-REDACTED2" "subnet-REDACTED3"`

**Comment by jayanthvn** [comment]
Hi @syedaliammar 

Can you please ssh to the node and check if any errors in `/var/log/aws-routed-eni/ipamd.log`? I am wondering if you are missing `AmazonEKS_CNI_Policy` in your role.

**Comment by syedaliammar** [comment]
Hi @jayanthvn
The CNI plugin has a role with the `AmazonEKS_CNI_Policy` policy attached to it. This role has the proper settings in its trust relationship, as mentioned [here](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html). The nodes in the cluster have a separate node role assigned to them that having the following two policies: `AmazonEKSWorkerNodePolicy `and `AmazonEC2ContainerRegistryReadOnly`. Any other ideas?

**Comment by jayanthvn** [comment]
Can you email me (varavaj@amazon.com) the logs generated from this - `sudo bash /opt/cni/bin/aws-cni-support.sh` on one of the nodes?

Thanks.

**Comment by jayanthvn** [comment]
Hi,

I did check your logs, instance has one ENI and no secondary IPs attached yet. But aws-node seems to be crashing after this - https://github.com/aws/amazon-vpc-cni-k8s/blob/dba11f45b747350cda623b08c6510876e2fb3f59/pkg/awsutils/awsutils.go#L604. Is it possible to open a support ticket? Logs aren't clear on why aws-node is crashing.

**Comment by achevuru** [comment]
@syedaliammar Is access to IMDS blocked? After switching to IRSA for aws-node pods, have you restarted the aws-node daemonset? Can you verify if your aws-node pod is able to assume the IRSA role?

**Comment by jayanthvn** [comment]
Based on the logs IMDS access seems fine, calls to EC2 might be blocked?

**Comment by syedaliammar** [comment]
> Based on the logs IMDS access seems fine, calls to EC2 might be blocked?

How can I verify that? The node role already has the following trust relationship:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by achevuru** [comment]
@syedaliammar Can you confirm if you've restarted aws-node daemonset after switching to IRSA?

**Comment by syedaliammar** [comment]
@jayanthvn @achevuru excuse the late response. The reason was an improper configuration of the OIDC provider. The audience "sts.amazonaws.com" was not added. Doing so solved the issue.

Thank you for your support.

**Comment by syedaliammar** [comment]
The audience "sts.amazonaws.com" was not added in the OIDC provider configuration. Doing so solved the issue.
