### ISSUE TITLE
All nodes in cluster in Not Ready state with the error: NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by sambaran69** [aws/amazon-vpc-cni-k8s#1452]
**What happened**:
Performed an EKS updgrade form 1.17 to 1.18. Post upgrade when attempting to upgrade _aws-node_, _core-dns_, _kube-proxy_, _calico_ and _cluster-autoscaler_, the `aws-node` upgrade failed. All nodes went into `Not Ready` state with the error mentioned above. All services that were running started throwing:  `Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container error`

**Attach logs**

Please contact me regarding the Log files.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.16-eks-7737de
- CNI Version: 1.7.9
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`):  4.14.225-169.362.amzn2.x86_64

**Comment by jayanthvn** [comment]
Hi @sambaran69 

Can you please share the logs - `sudo bash /opt/cni/bin/aws-cni-support.sh` from one of the nodes. You can email it to varavaj@amazon.com.

Thanks!

**Comment by sambaran69** [comment]
Hi,

The issue was caused by installing `aws-vpc-cni` with incorrect (old) config. This was resolved when we installed `aws-vpc-cni` using the helm chart instead of running `kubectl apply -f ...`. 

This issue can be marked as closed.
