### ISSUE TITLE
After switching to IAM for service accounts there are still calls to CreateNetworkInterface using ec2 instance profile role according to Cloudtrail

### ISSUE THREAD

**Issue by alexmnyc** [aws/amazon-vpc-cni-k8s#1454]
I followed https://docs.amazonaws.cn/en_us/eks/latest/userguide/cni-iam-role.html and verified ` kubectl exec -n kube-system aws-node-55t22 env | grep AWS_ROLE` is injected correctly. Yet Cloudtrail still shows errors where instances in the cluster are trying to call CreateNetworkInterface

```
"userAgent":"aws-sdk-go/1.33.14 (go1.13.15; linux; amd64) amazon-vpc-cni-k8s","errorCode":"Client.UnauthorizedOperation","errorMessage":"You are not authorized to perform this operation ....`
userIdentity.sessionContext.sessionIssuer.arn:   arn:aws:iam::XXX:role/org/project/ec2
eventName : CreateNetworkInterface
eventSource : ec2.amazonaws.com

```

Logs seem fine from what I can tell

```
 kubectl logs -f -n kube-system  -l k8s-app=aws-node
{"level":"info","ts":"2021-05-03T17:27:18.831Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-05-03T17:27:18.881Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-05-03T17:27:22.386Z","caller":"entrypoint.sh","msg":"Install CNI binary.."}
{"level":"info","ts":"2021-05-03T17:27:22.402Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2021-05-03T17:27:18.882Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2021-05-03T17:27:20.936Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2021-05-03T17:27:22.403Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2021-05-03T17:27:28.598Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2021-05-03T17:27:20.943Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2021-05-03T17:27:28.615Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2021-05-03T17:27:20.944Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
{"level":"info","ts":"2021-05-03T17:27:28.622Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

What is also strange that the ec2 instance profile does have `ec2:CreateNetworkInterface` permission on `"Resource": "*"`

Do I need to recycle the ec2 nodes perhaps not just the aws-node pods? It is not clear to me why this would be happening

I checked the ec2 instance and it does belong to the cluster that has aws-node annotated with the IAM role and correct OIDC trust relationship  `userIdentity.arn: arn:aws:sts::XXX:assumed-role/ec2-role/i-0930b5ca6ee55ffff` 

I don't see this affecting anything in the cluster but that is a mystery as to why Cloudtrail reports so many errors with authorization related to this plugin

**Comment by achevuru** [comment]
Hi @alexmnyc, If there are permission issues, we will see error logs (403s) in ipamd log file. Do you see any such errors? Once you switch to IRSA, you just need to reload aws-node pods. No need to reboot instances.

**Comment by alexmnyc** [comment]
I don't see any 403 errors through pod logs or via /var/log/aws-routed-eni/plugin.log 

I just reran the query in cloudtrail. it seems like now it is isolated to the clusters that don't use the IAM for service accounts method and have the following enabled:

```
# commands block ALL containers from using the instance profile credentials
yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables
systemctl enable --now iptables
```
I think that is the explanation. If nodes have the metadata endpoint disabled aws-node pods cannot assume correct credentials. What was misleading though, Cloudtrail was reporting userIdentity.arn as the instance profile of the instance though. I don't know how aws-node would be able to assume those credentials to show up in cloutrail if that iptable rule was in place to block access to the metadata endpoint

**Comment by achevuru** [comment]
Yeah that explains. Cloudtrail is showing the calls made to EC2 from aws-node user agent, so you're seeing the API call requests that EC2 received..since it is not able to assume the role, API request gets rejected.

**Comment by alexmnyc** [comment]
Correct. But why would cloudtrail show underlying instance instance profile role as the identity for the failed call? If the pod is blocked from assuming instance profile role how would cloudtrail show a call rejected from any identity, there should be none, no?

**Comment by achevuru** [comment]
@alexmnyc You can run and check aws sts get-caller-identity from with in aws-node pod to see the role it is trying to use. It is possible that it got the Node instance role name prior to IMDS access is blocked but since these are temp credentials it is no longer able to retrieve the latest credentials to use and therefore running in to 403 with the stale credentials.
