### ISSUE TITLE
AWS cni kops configuration

### ISSUE THREAD

**Issue by kaliha** [aws/amazon-vpc-cni-k8s#146]
Hello. Is it possible to pass docker image url or version on `kops edit cluster` command?

**Comment by igorvpcleao** [comment]
I believe not. As far as I know, Kops will populate your `KOPS_STATE_STORE` bucket on S3 with manifests from Kops Github itself, reading from S3 while installing cluster addons: https://github.com/kubernetes/kops/tree/063afb28d79abae32743923a28a7a1743257addf/upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni (notice the image is hard coded).

However, it seems that nothing forbids you to change the image by either editing the `aws-node` daemonset itself or even editing `KOPS_STATE_STORE/CLUSTER_NAME/addons/networking.amazon-vpc-routed-eni` on S3.

**Comment by igorvpcleao** [comment]
related: https://github.com/kubernetes/kops/issues/5568

It seems it's not just bumping
