### ISSUE TITLE
Docs: switching AWS_VPC_K8S_CNI_EXTERNALSNAT from true to false breaks routing for existing pods

### ISSUE THREAD

**Issue by maxenglander** [aws/amazon-vpc-cni-k8s#1462]
**Request**:

This is a request to add documentation for `AWS_VPC_K8S_CNI_EXTERNALSNAT` to explain that switching from `true` to `false` can break routing for running pods.

**What happened**:

Hello, we had an issue during upgrade of VPC CNI component, and are looking for some insight.

We recently upgraded EKS from 1.15 to 1.16, and as part of that upgrade we upgraded VPC CNI from 1.6.x to 1.7.5 according to the [EKS upgrade docs](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).

As part of following that procedure we unintentionally switched from `AWS_VPC_K8S_CNI_EXTERNALSNAT: true` to `false` (this may or may not be a relevant point. Also, there was an AWS API issue (April 13, 2021) happening during the upgrade, and we observed some API failures from VPC CNI to AWS, which succeeded on retry.

As new `aws-node` pods rolled out, we saw behavior like this:

 1. In some cases, K8S reported health probe failures for the new `aws-node`, usually these were resolved quickly
 1. `aws-node` logged "Successfully copied CNI plugin binary and config file."
 1. Within a second, incoming requests to pods that were running *before the new `aws-node` pods* dropped by a lot (sometimes to zero), and outgoing requests (e.g. to RDS databases in a separate VPC) timed out
 1. Those pods had health probe failures, and were eventually recreated by K8S
 1. Upon recreation of the pods, the problem (whatever it was) resolved

This behavior continued sporadically for about 30 minutes as the new `aws-node` pods rolled out.

I looked through the issue history for this repo, and didn't see anything that exactly resembled the behavior we saw. I am not trying to pin the issue on AWS VPC CNI, and am not asking for help precisely figuring out the root cause. I am just trying to come up with plausible theories about what happened, and if/how VPC CNI might have played a role.

 * Could switching SNAT from `true` to `false` have played a role?
 * Could intermittent internal server error responses from AWS API have played a role?
 * Can VPC CNI change host-level routing in a way that affects existing pods, causing traffic to be dropped?
 * (Slight variation of last question) Can VPC CNI change the IP address or routing tables for pods that have already been created and assigned an IP address by IPAMD?

Unfortunately the hosts from that incident have all been terminated, and we don't have logs from the host-level component. We do still have some logs from the K8S agent, some details related to health probe failures of the VPC CNI component, and a good amount of application logs and metrics.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.15-eks-ad4801 (was on 1.15 prior to upgrade)
- CNI Version: 1.7.5
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.225-169.362.amzn2.x86_64

**AWS support**:

Here's what AWS support told us:

> I received update from our internal team about this. Changing AWS_VPC_K8S_CNI_EXTERNALSNAT variable “true” to “false” will definetly effect pod traffic/connectivity.
>
> To explain this, Our AWS document [1] doesn’t mention is that, the CNI Plugin will also update the host level routing and IP rules when you update the AWS_VPC_K8S_CNI_EXTERNALSNAT configuration variable. The traffic packets usually drops due to the Linux kernel think of the interface that the packet is received on, is not the best return path for the packet. This is the key point for affecting the connectivity.
>
> When the CNI Plugin initialized, it is using the strict mode(rp_filter=1) and the kernel will proactively ignore the packet. 
> 
> Note: rp_filter=1: Strict Mode as defined in RFC 3074. Each incoming packet to a router is tested against the routing table and if the interface that the packet is received on is not the best return path for the packet then the packet is dropped.
> 
> To confirm, By default, the Linux kernel has feature to prevent attacks used by Spoofing IP Addresses, which is Reverse Path Filter (rp_filter), it can be configured to each network interface. The rp_filter provided by Linux kernel feature will proactively check incoming packets, if the reply to this packet wouldn't go out the interface this packet came in, then it think it is a bogus packet and should be ignored when setting strict mode(rp_filter=1). Since aws-node is responsible for managing network interfaces, the packets were dropped until your aws-node pods are successfully rolled out.

**Comment by maxenglander** [comment]
I also posed the question above to AWS support, and received this great answer:

> I received update from our internal team about this. Changing AWS_VPC_K8S_CNI_EXTERNALSNAT variable “true” to “false” will definetly effect pod traffic/connectivity.
>
> To explain this, Our AWS document [1] doesn’t mention is that, the CNI Plugin will also update the host level routing and IP rules when you update the AWS_VPC_K8S_CNI_EXTERNALSNAT configuration variable. The traffic packets usually drops due to the Linux kernel think of the interface that the packet is received on, is not the best return path for the packet. This is the key point for affecting the connectivity.
>
> When the CNI Plugin initialized, it is using the strict mode(rp_filter=1) and the kernel will proactively ignore the packet. 
> 
> Note: rp_filter=1: Strict Mode as defined in RFC 3074. Each incoming packet to a router is tested against the routing table and if the interface that the packet is received on is not the best return path for the packet then the packet is dropped.
> 
> To confirm, By default, the Linux kernel has feature to prevent attacks used by Spoofing IP Addresses, which is Reverse Path Filter (rp_filter), it can be configured to each network interface. The rp_filter provided by Linux kernel feature will proactively check incoming packets, if the reply to this packet wouldn't go out the interface this packet came in, then it think it is a bogus packet and should be ignored when setting strict mode(rp_filter=1). Since aws-node is responsible for managing network interfaces, the packets were dropped until your aws-node pods are successfully rolled out.

I could be missing it, but I didn't see any documentation in this repo about that. Is it worth adding that documentation?

**Comment by jayanthvn** [comment]
Thanks @maxenglander, yes will update the documentation. There is some documentation now - https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html but would definitely need to update the narrative.

**Comment by maxenglander** [comment]
Thanks @jayanthvn I'll rename/update this ticket to reflect that what's need is an update to docs
