### ISSUE TITLE
Allocatable pods in 1.1.0

### ISSUE THREAD

**Issue by incognick** [aws/amazon-vpc-cni-k8s#148]
I'm running an EKS cluster 1.10.3. I just upgraded the CNI plugin to 1.1.0 with EXTERNALSNAT to "true".  I'm running m5.large worker nodes. When I describe the node in kubectl,  I see the following:  

```
Capacity:
 cpu:                2
 ephemeral-storage:  20959212Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             7867456Ki
 pods:               20
Allocatable:
 cpu:                2
 ephemeral-storage:  19316009748
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             7765056Ki
 pods:               20
```

Shouldn't pods be around 30? This should have 3 interfaces with 10 IPs per interface. In the AWS console I can see 3 private IPs and 30 secondary IPs attached.

**Comment by cablespaghetti** [comment]
I may be completely wrong here. But double check your user_data for your worker nodes. Mine contains:
`sed -i s,MAX_PODS,20,g /etc/systemd/system/kubelet.service`

**Comment by mogren** [comment]
Resolving old issues.
