### ISSUE TITLE
Support for t4g (ARM graviton) instances

### ISSUE THREAD

**Issue by jamesetune** [aws/amazon-vpc-cni-k8s#1481]
**What would you like to be added**:Support for T4G instance types

**Why is this needed**: T4g's are cheaper instance types that are more suitable for our workloads that M6's

**Comment by jayanthvn** [comment]
Hi @jamesetune 

Which CNI release are you using? Since 1.7.6 onwards t4g's are supported - https://github.com/aws/amazon-vpc-cni-k8s/pull/1296

**Comment by jayanthvn** [comment]
T4g instance support is already added from 1.7.6, please let us know if you are seeing any issue.
