### ISSUE TITLE
Failed create pod sandbox

### ISSUE THREAD

**Issue by lambertpan** [aws/amazon-vpc-cni-k8s#149]
I have installed Calico on my EKS cluster using manifest from https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.1/calico.yaml. But still I get errors `Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod` when I reach above 10 pods on t2.small.
I understood that Calico can overcome this node per pod limitation as mentioned [here](https://aws.amazon.com/blogs/opensource/networking-foundation-eks-aws-cni-calico/). Do I miss anything here?

**Comment by liwenwu-amazon** [comment]
@lambertpan when you apply https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.1/calico.yaml on top of a EKS cluster,  you are actually add calico policy-engine add-on to work with amazon-vpc-cni-k8s CNI.   The Pod limit per instance still applies (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI)
