### ISSUE TITLE
ServiceAccount should precede DaemonSet in yaml

### ISSUE THREAD

**Issue by rittneje** [aws/amazon-vpc-cni-k8s#1491]
See https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml for example.

We are trying to have the VPC CNI assume a role via EKS's OIDC provider. To do so requires us to add an annotation to the ServiceAccount, which must be present when the CNI pods are being created so that EKS can properly issue the JWT and set the necessary environment variables. However, the ServiceAccount appears _after_ the DaemonSet in the yaml, which leads to a race where the new DaemonSet pods might not necessarily get the environment variables set and therefore will not work as expected.

Please fix the yaml to put the ServiceAccount first so there less manual changes are required for this use case.

**Comment by achevuru** [comment]
@rittneje If SA is missing when the aws-node daemonset pod boots up, then it will fail to come up. I'm not sure I'm following the race condition you are referring to. Are you creating the aws-node Serviceaccount first and then manually modifying it to add the IRSA annotation? Default manifest doesn't carry SA annotation.

**Comment by rittneje** [comment]
If we modify the ServiceAccount to include the annotation without also reordering the yaml file, then some of the pods end up without the AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables set due to this race condition.

In addition as you mentioned the ServiceAccount needs to exist before the DaemonSet is created in the first place. (However since it seems EKS automatically creates it when you create the cluster this particular issue hasn't come up for us.)

Between these two problems, it seems that reordering the yaml in this repo would be for the best.

**Comment by jayanthvn** [comment]
With the next CNI release (probably next month) we will be generating these manifests from helm and that will ensure the service account is on the top.

**Comment by jayanthvn** [comment]
This https://github.com/aws/amazon-vpc-cni-k8s/pull/1271 will fix the issue. We will be taking it up in 1.8.1 onwards. This couldn't be done with the latest release due to pending documentation update for new labels added thru helm charts.
