### ISSUE TITLE
Windows container supported?

### ISSUE THREAD

**Issue by messmerxx** [aws/amazon-vpc-cni-k8s#15]
Dear all,

I would like to know whether this plug-in can be used for a kubernetes cluster with windows nodes. I would like to have master node with linux and windows nodes with windows container.

Is it possible?

Thanks.

Best regards
Kejun xu

**Comment by eswarbala** [comment]
Thanks for the interest Kejun. We don't support windows containers with this CNI plugin at the moment, though it is something we have in our roadmap. We will provide more info when we identify our timeline.

**Comment by PaulLiang1** [comment]
+1 on this feature. 

Looks like it's doable by marrying these together somehow..

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/networkutils/network.go#L72
https://github.com/Azure/azure-container-networking/blob/master/network/network_windows.go
https://github.com/Microsoft/hcsshim/blob/master/internal/hns/hnsnetwork.go

**Comment by Rajesh804** [comment]
Hi,

We are eagerly waiting for this to be supported for Windows. Do you have any update or ETA on this?

Thanks,
RR

**Comment by amitsaha** [comment]
Will it be possible to share rough ideas for the community to look at implementing this?

**Comment by mogren** [comment]
Not using this CNI

**Comment by ofiliz** [comment]
To be clear, EKS Windows Nodes is a "coming soon" feature tracked in our roadmap: https://github.com/aws/containers-roadmap/issues/69

We have a separate CNI plugin for Windows.
