### ISSUE TITLE
vpc_ip_resource_limit is missing r5 instances

### ISSUE THREAD

**Issue by mejran** [aws/amazon-vpc-cni-k8s#150]
This is causing our r5 instances to get no additional IPs assigned to them since it defaults to 0 for unknown instance types.

**Comment by seb-steuer** [comment]
+1 I just found out the hard way ;) and spent a lot of time debugging my EKS cluster

**Comment by oded-dd** [comment]
+1

**Comment by seb-steuer** [comment]
there is already a pull request for that :)
https://github.com/aws/amazon-vpc-cni-k8s/pull/145

**Comment by liwenwu-amazon** [comment]
This should be resolved with https://github.com/aws/amazon-vpc-cni-k8s/pull/145.  Please reopen it if this is still an issue to you.
