### ISSUE TITLE
ENI is not getting associated with POD

### ISSUE THREAD

**Issue by RajatToshniwal** [aws/amazon-vpc-cni-k8s#1505]
**What happened**:
I followed the steps mentioned "https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html" in order to enable security groups for pods. I want to have some security policy between pod-to-pod communication.  It is not showing me any ENI created for the security group. I verified it both from the AWS console as well as by describing the pods.
Currently my security group has no inbound security rules, which means everything should be blocked, but somehow I am able to connect the pod from other pods in the same namespace.

**Describe pods Annotations**
I have a test pod in bookinfo namespace with the following annotations 
Annotations:  kubectl.kubernetes.io/default-container: productpage
              kubectl.kubernetes.io/default-logs-container: productpage
              kubernetes.io/psp: eks.privileged
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy
","istio-data","istio-podinfo","istio-token","istiod-...

As per the "https://www.eksworkshop.com/beginner/115_sg-per-pod/50_deploy/", it should have "eni id" as one of the annotations.
Similarly, when I am seeing it in the AWS console network interface, I don't see any interface associated with the security group.

_I already have ENABLE_POD_ENI=true_

**kubectl get nodes -o wide -l vpc.amazonaws.com/has-trunk-attached=true**

_NAME                                          STATUS   ROLES    AGE   VERSION              INTERNAL-IP     EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                CONTAINER-RUNTIME
ip-10-105-49-177.us-east-2.compute.internal   Ready    <none>   17d   v1.20.4-eks-6b7464   10.105.49.177   <none>        Amazon Linux 2   5.4.117-58.216.amzn2.x86_64   docker://19.3.13_

**Attach logs**
[eks_i-01d0b4d672b45e4f2_2021-06-11_1418-UTC_0.6.2.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/6639072/eks_i-01d0b4d672b45e4f2_2021-06-11_1418-UTC_0.6.2.tar.gz)

**What you expected to happen**:
pods network control (L3) using independent security groups.

**How to reproduce it (as minimally and precisely as possible)**:

- Attach "AmazonEKSVPCResourceController" policy to the EKS Cluster role
- Upgraded the CNI to 1.8 using the below mentioned command 
- curl -o aws-k8s-cni.yaml  https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.8/config/v1.8/aws-k8s-cni.yaml
- Applied : kubectl set env daemonset aws-node -n kube-system ENABLE_POD_ENI=true
- kubectl patch daemonset aws-node \
   -n kube-system \
   -p '{"spec": {"template": {"spec": {"initContainers": [{"env":[{"name":"DISABLE_TCP_EARLY_DEMUX","value":"true"}],"name":"aws-vpc-cni-init"}]}}}}'

**Security Group Policy** 

apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: bookinfo-policy
  namepsace: bookinfo
spec:
  serviceAccountSelector:
    matchLabels:
      app: productpage
  securityGroups:
    groupIds:
      - sg-xxxxxxx (Replaced the value)

**Environment**: EKS 1.20
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- CNI Version : amazon-k8s-cni:v1.8.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): Linux ip-10-105-48-49 5.4.0-1045-aws

**Comment by abhipth** [comment]
Hi @RajatToshniwal can you confirm if you see `vpc.amazonaws.com/pod-eni` on descring the pod. Also can you provide the name of the pod so I can cross check in the logs.

**Comment by RajatToshniwal** [comment]
Hi Abhi,

pod name is productpage
I don't see vpc.amazonaws.com/pod-eni.

kubectl -n bookinfo  describe pod productpage-v1-6b746f74dc-n6zs7  | grep -i  "vpc.amazonaws.com/pod-eni"

showing me no result.

**Comment by abhipth** [comment]
Thanks for confirming, I see in your SGP that you are using `serviceAccountSelector` with match labels `app: productpage`. This Policy will target all the Pods that are using a Service Account that has the label `app: productpage`. Could you confirm that the label is present on the Service account of pod `bookinfo/productpage`.

**Comment by RajatToshniwal** [comment]
I can't see "app: productpage" there 
kubectl describe  serviceaccount bookinfo-productpage  -n bookinfo
Name:                bookinfo-productpage
Namespace:           bookinfo
Labels:              account=productpage
Annotations:         Image pull secrets:  <none>
Mountable secrets:   bookinfo-productpage-token-mjnk9
Tokens:              bookinfo-productpage-token-mjnk9
Events:              <none>

**Comment by RajatToshniwal** [comment]
My bad, after using the podSelector, it starts working fine.

Thanks a lot for your support.

**Comment by abhipth** [comment]
@RajatToshniwal that would explain why the Pod in question is not getting an ENI.

In order to target your pod currently you can do the following
- Use ` serviceAccountSelector` that you currently have and add the label to your Service Account. This will allocate a ENI to all Pods that are using that service account.
- Alternatively, you could use `podSelector` instead of   serviceAccountSelector` and for the add the label to your Pods for which you want an ENI.
```
podSelector: 
    matchLabels:
      <role>: <my-role>
```

Also for this to happen, you would have to re-create your Pod after you picked an option above. Let me know if this helps solve your issue. You can refer this [doc](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html) for additional details

**Comment by RajatToshniwal** [comment]
Hi Abhi,

Now my pods are kind of stuck, they are not getting created .
I am getting the following error

  Normal   ResourceAllocated       7m43s                    vpc-resource-controller  Allocated [{"eniId":"eni-040919c5860611402","ifAddress":"06:8c:b6:a5:ae:9e","privateIp":"10.105.49.166","vlanId":1,"subnetCidr":"10.105.49.128/26"}] to the pod
  Warning  FailedCreatePodSandBox  7m43s                    kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "97692788bcc8bf132832622c5dc21600f9db885c97c268decc3d1d5331a421a1" network for pod "productpage-v1-6b746f74dc-s9krz": networkPlugin cni failed to set up pod "productpage-v1-6b746f74dc-s9krz_bookinfo" network: add cmd: failed to assign an IP address to container

Let me know if I need to create a separate ticket for this?

**Comment by abhipth** [comment]
We can work using this issue. Could you share the output from the log collector script on the node where the Pod is stuck in ContainerCreating.

**Comment by RajatToshniwal** [comment]
Please find them attached.
Meanwhile I am also getting the below mentioned error
{"level":"debug","ts":"2021-06-11T16:08:36.581Z","caller":"retry/retry.go:70","msg":"No secondary IPv4 addresses available yet on ENI eni-08bef2935d5494306".

Do I need to configure the secondary IPv4 as well?
[Uploading eks_i-01d0b4d672b45e4f2_2021-06-11_1610-UTC_0.6.2.tar.gz…]()

**Comment by RajatToshniwal** [comment]
Please ignore  this line  "No secondary IPv4 addresses available yet on ENI eni-08bef2935d5494306" 
It may be because I tried changing the configuration 
            - name: WARM_ENI_TARGET
              value: '2'
Now I am not getting that line in the ipamd logs.
I have changed my configuration  back to "1", still my pods are not getting created. They are stuck.

**Comment by abhipth** [comment]
Could you confirm if both ENI Pod as well as normal Pods are stuck in ContainerCreating?

Also, I could'nt find the Pod `productpage-v1-6b746f74dc-s9krz` in the most recent logs. Could you share the Pod Description for the impacted Pod which is present in the the above logs tar.

**Comment by RajatToshniwal** [comment]
[eks_i-01d0b4d672b45e4f2_2021-06-11_1634-UTC_0.6.2.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/6639934/eks_i-01d0b4d672b45e4f2_2021-06-11_1634-UTC_0.6.2.tar.gz)

Pod Name : productpage-v1-6b746f74dc-kxrs4

Events:

Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               16m                  default-scheduler        Successfully assigned bookinfo/productpage-v1-6b746f74dc-kxrs4 to ip-10-105-49-177.us-east-2.compute.internal
  Normal   SecurityGroupRequested  16m                  vpc-resource-controller  Pod will get the following Security Groups [sg-020893c8acd8e77e9]
  Normal   ResourceAllocated       16m                  vpc-resource-controller  Allocated [{"eniId":"eni-05fea37c9708913d7","ifAddress":"06:74:5b:7b:54:3a","privateIp":"10.105.49.186","vlanId":2,"subnetCidr":"10.105.49.128/26"}] to the pod
  Warning  FailedCreatePodSandBox  16m                  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a8d3347352bc4cc01af42df6ad475b9dcf74bc78a9346864bc99d985ed9704d0" network for pod "productpage-v1-6b746f74dc-kxrs4": networkPlugin cni failed to set up pod "productpage-v1-6b746f74dc-kxrs4_bookinfo" network: add cmd: failed to assign an IP address to container
  Normal   SandboxChanged          16m                  kubelet                  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  16m                  kubelet                  Container image "docker.io/istio/proxyv2:1.10.0" already present on machine
  Normal   Created                 16m                  kubelet                  Created container istio-init
  Normal   Started                 16m                  kubelet                  Started container istio-init
  Normal   Pulled                  16m                  kubelet                  Container image "docker.io/istio/examples-bookinfo-productpage-v1:1.16.2" already present on machine
  Normal   Created                 16m                  kubelet                  Created container productpage
  Normal   Started                 16m                  kubelet                  Started container productpage
  Normal   Pulled                  16m                  kubelet                  Container image "docker.io/istio/proxyv2:1.10.0" already present on machine
  Normal   Created                 16m                  kubelet                  Created container istio-proxy
  Normal   Started                 16m                  kubelet                  Started container istio-proxy
  Warning  Unhealthy               91s (x450 over 16m)  kubelet                  Readiness probe failed: Get "http://10.105.49.186:15021/healthz/ready": dial tcp 10.105.49.186:15021: connect: connection refused

**Comment by RajatToshniwal** [comment]
Mistakenly closed it

**Comment by abhipth** [comment]
I see the Readiness Probe is failing on the Pod. With SGP you would need to disable TCP Early Demux in order to have readiness probe work with SGP Pod.

If you would like to disable it, you can use the following command.

```
kubectl patch daemonset aws-node \
  -n kube-system \
  -p '{"spec": {"template": {"spec": {"initContainers": [{"env":[{"name":"DISABLE_TCP_EARLY_DEMUX","value":"true"}],"name":"aws-vpc-cni-init"}]}}}}'
```

Reference: [SGP Doc](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)

**Comment by RajatToshniwal** [comment]
I already did that and it is already showing me as true
kubectl describe   ds aws-node -n kube-system |grep "DISABLE_TCP_EARLY_DEMUX" -A 1
      DISABLE_TCP_EARLY_DEMUX:  true

**Comment by abhipth** [comment]
@RajatToshniwal could you confirm if you allowed inbound communication from cluster security group for the readiness probe port?

**Comment by RajatToshniwal** [comment]
Hi Abhi,

My pod security group is all open for UDP and TCP. No restrictions at all.
In the ClusterMasterSecurityGroup, I have opened TCP and UDP port 53 for pod securitygroup

**Comment by abhipth** [comment]
Hi @RajatToshniwal 

From the readiness probe failure error `connection refused` I am still suspecting this is due to SG blocking readiness probes.
```
Jun 11 16:17:20 ip-10-105-49-177.us-east-2.compute.internal kubelet[4947]: I0611 16:17:20.915693    4947 prober.go:117] Readiness probe for "productpage-v1-6b746f74dc-kxrs4_bookinfo(f70df05f-544a-4cea-810a-18d74f32ea74):istio-proxy" failed (failure): Get "http://10.105.49.186:15021/healthz/ready": dial tcp 10.105.49.186:15021: connect: connection refused
```
Could you share your cluster ARN at abhipth@amazon.com so I could further inspect the issue.

**Comment by RajatToshniwal** [comment]
Sent.

**Comment by RajatToshniwal** [comment]
Hi Abhi,

Another thing which I have noticed  on my datanode, I can't  see the pod IP there as well. Though the network interface is showing the mac-address but not the corresponding IP address. Similarly if I am inspecting my docker images from data nodes. They are not assigned any IP address.
**Interface on my data node**
vlan.eth.2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet6 fe80::4d3:a2ff:fee4:ac72  prefixlen 64  scopeid 0x20<link>
        ether 06:d3:a2:e4:ac:72  txqueuelen 1000  (Ethernet)
        RX packets 377  bytes 44831 (43.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 469  bytes 227412 (222.0 KiB)

**Describe pod**
" Normal   ResourceAllocated       55s                 vpc-resource-controller  Allocated [{"eniId":"eni-0963131a327d2d137","ifAddress":"**06:d3:a2:e4:ac:72**","privateIp":"10.105.49.173","vlanId":2,"subnetCidr":"10.105.49.128/26"}] to the pod"

**Docker inspect**
docker inspect 165144c0b3ed |grep "10.105"
showing no result

**Comment by RajatToshniwal** [comment]
Above observation is correct, When I run it by disabling the istio inject label, it is working fine. But I need istio, I can't disable it . Can you please provide a solution for this use case where pod security groups needs to be run along with istio.

**Comment by RajatToshniwal** [comment]
Hi Abhi,

You were correct there were some ports missing in my control plane security group. After adding tcp ports from 15001 to 15014 along with the DNS ports, my pod starts working. 
But now the issue is my "security-group" for the pods is not blocking anything. I have only allowed the inbound communication from the cluster security group. Still all other pods in that namespace are able to connect with my pod.  I want to block all the communication from other services/pods except the required ones.

**Comment by RajatToshniwal** [comment]
Please consider it as resolved.
