### ISSUE TITLE
Allow primary ENI to be unmanaged

### ISSUE THREAD

**Issue by haoming-db** [aws/amazon-vpc-cni-k8s#1510]
**What would you like to be added**:
Allow primary ENI to be unmanaged.
Currently the `node.k8s.amazonaws.com/no_manage` tag [is ignored on the primary ENI](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.7/pkg/ipamd/ipamd.go#L220), so as a user we have no way to opt our primary ENI out of CNI's management.

Alternatively, AWS-CNI can provide an option to run in a low-privileged mode, where it doesn't manage any ENIs/IPs, but only assign available IPs to pods. 

**Why is this needed**:
Our team wants to manage ENIs by our own (including creating/attaching/detaching/deleting ENIs, security groups, as well as private IPs). 
Currently `aws-node` requires highly privileged IAM permissions on a node, including Attach/Create/Delete/Detach NetworkInterface, as well as ModifyNetworkInterfaceAttribute. These IAM permissions make a node vulnerable if it's running untrusted containers.
It's better to have a way for AWS-CNI or EKS users to opt out any ENI management and reduce the required IAM permissions on the node role.

**Comment by achevuru** [comment]
@haoming-db If your primary concern is due to an untrusted container taking advantage of CNI Policy permissions tied to the NodeInstanceRole, you should be able to use IRSA instead and remove the CNI Policy from the NodeInstanceRole. Will limit these permissions to aws-node pods on the node and a random pod will not be able to assume these permissions/role.

**Comment by jayanthvn** [comment]
This https://github.com/aws/amazon-vpc-cni-k8s/pull/1586 will help to run aws-node in low-privileged mode.

**Comment by jayanthvn** [comment]
CNI 1.9.1 is released - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.1 which supports `DISABLE_NETWORK_RESOURCE_PROVISIONING`. Will close the issue. Please feel free to reach out for any help.
