### ISSUE TITLE
At 1st run, ipamd always sets the security groups of ENIs even if they already have the desired security groups

### ISSUE THREAD

**Issue by haoming-db** [aws/amazon-vpc-cni-k8s#1511]
**What happened**:
[RefreshSGIDs is called at CNI’s ipamd starts](https://github.com/aws/amazon-vpc-cni-k8s/blob/d9d69e17c86baff36cdee67986551492f24f5d94/pkg/ipamd/ipamd.go#L323) (and also every 30s in the background).
When the container starts, [EC2InstanceMetadataCache.securityGroups](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.7/pkg/awsutils/awsutils.go#L189) is empty (there’s no code to init it).
Then, at the first run, [addedSGs](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.7/pkg/awsutils/awsutils.go#L440) is always equal to the desired SGs, and [it always updates the ENIs' SGs](https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.7/pkg/awsutils/awsutils.go#L482) at the first run, even if the ENI(s) already have the desired SGs.

**Attach logs**

**What you expected to happen**:
The ipamd should call DescribeENI first and update it only if it doesn't have the desired SGs.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is very important in our use cases, because we don't give the ModifyNetworkInterfaceAttribute IAM permission to `aws-node`. Instead, we manage ENI SGs (including the primary ENI) by ourselves.

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Hi @haoming-db 

Will look into this and get back to you.
