### ISSUE TITLE
Node affinity requires matching with both beta.kubernetes.io and kubernetes.io labels

### ISSUE THREAD

**Issue by yangxintian** [aws/amazon-vpc-cni-k8s#1518]
In the v1.7 aws-k8s-cni.yaml file, the node affinity is set to require matching with both beta.kubernetes.io/... labels and kubernetes.io/... labels. Is this really intended?
For now, this works because nodes created in EKS have both the beta.kubernetes.io/... labels and the kubernetes.io/... labels. But from Kubernetes [documentation](https://kubernetes.io/docs/reference/labels-annotations-taints/), the beta labels are deprecated. If it were happen that EKS stop populating the beta labels, it will cause the daemonset can't be scheduled on those nodes.

Please clarify whether the current yaml code is intended, if not please fix it by removing the beta labels. 

Yaml code as follow:
```
    "spec":
      "affinity":
        "nodeAffinity":
          "requiredDuringSchedulingIgnoredDuringExecution":
            "nodeSelectorTerms":
            - "matchExpressions":
              - "key": "beta.kubernetes.io/os"
                "operator": "In"
                "values":
                - "linux"
              - "key": "beta.kubernetes.io/arch"
                "operator": "In"
                "values":
                - "amd64"
                - "arm64"
              - "key": "eks.amazonaws.com/compute-type"
                "operator": "NotIn"
                "values":
                - "fargate"
            - "matchExpressions":
              - "key": "kubernetes.io/os"
                "operator": "In"
                "values":
                - "linux"
              - "key": "kubernetes.io/arch"
                "operator": "In"
                "values":
                - "amd64"
                - "arm64"
              - "key": "eks.amazonaws.com/compute-type"
                "operator": "NotIn"
                "values":
                - "fargate"

```

**Comment by nithu0115** [comment]
@yangxintian, +1 and thanks for bringing it up to our notice. Now that EKS does not support 1.12 - 1.14 Kubernetes versions, we can safely remove these beta labels. We will work on removing these labels.
