### ISSUE TITLE
Support custom networking by subnet

### ISSUE THREAD

**Issue by stevehipwell** [aws/amazon-vpc-cni-k8s#1528]
**What would you like to be added**:
Support for custom networking at the subnet level rather than at the zone level. Off the top of my head an env variable to use the primary ENI subnet ID as the selector for the ENIConfig instead of a label would solve this issue with minimal effort.

**Why is this needed**:
The AWS node labels don't support differentiating between public and private subnets despite them being the recommended VPC pattern. Without this we have to hack the userdata to add a subnet node label which isn't supported in Bottlerocket.

**Comment by jayanthvn** [comment]
Hi @stevehipwell 

Would like to understand the use case more here. Subnets are associated with AZs and in the ENIConfig we have to manually select the subnet IDs which would be used for the nodes. I understand it is a more manual work but we could effectively just specify the public or private subnet ID based on the usage. Please let me know if my understanding is correct?

**Comment by stevehipwell** [comment]
@jayanthvn if we work from the first principal that any manual steps automatically makes the solution invalid for IaC; and IaC is a must here 

The most granular label on a node is the zone, but a zone can contain multiple subnets, and in the recommended AWS pattern contains both a public and private subnet. A secondary subnet should map to a primary subnet, so we have multiple secondary subnets in a zone. This means there is currently no way to automatically link primary and secondary subnets based on node labels. I'm asking for a first party automated solution for this as my current solution will not work with Bottlerocket nodes.

It should be relatively easy to use the primary ENI subnet ID to map to an ENIConfig either on name or another label on the ENIConfig.

**Comment by achevuru** [comment]
@stevehipwell  Primary ENI is excluded in Custom networking mode. Can you elaborate on what you mean by `A secondary subnet should map to a primary subnet, so we have multiple secondary subnets in a zone`?

**Comment by stevehipwell** [comment]
@achevuru the ENI is present so the node can communicate withe the rest of the VPC and is where the IPs come from for host network. This ENI can be looked up from metadata and provide the subnet ID that it's attached to. If the subnet ID can be used to select ENIConfig we've solved the issue of dynamic lookup.

**Comment by jayanthvn** [comment]
With the current implementation we can set `ENI_CONFIG_ANNOTATION_DEF` with `k8s.amazonaws.com/eniConfig` and annotate the node -

```
Each subnet and security group combination requires its own custom resource. 
If you have multiple subnets in the same Availability Zone, 
use the following command to annotate the nodes in each subnet with the matching config name.

kubectl annotate node <node-name>.<region>.compute.internal k8s.amazonaws.com/eniConfig=<subnet1ConfigName>
```
Ref: https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

But yes we agree this won't solve the issue of differentiating public/private subnet ID and there is room for automation here and we will look into it.

**Comment by stevehipwell** [comment]
@jayanthvn manual solutions using `kubectl` aren't fit for purpose in a world of IaC. I already have a working solution on the standard AMI and have a solution now for Bottlerocket; but both are hacky and leave me wanting native support. The recommended AWS VPC has multiple subnets per region so it's not like this is an edge case. Using the ID of the subnet on the node primary ENI as the key for the ENIConfig seems pretty trivial to me and would solve this.

**Comment by ppandiya** [comment]
Any updates on this.

**Comment by stevehipwell** [comment]
@ppandiya we're going to change our K8s network design to only use a single secondary address space per zone when using IPv4; with IPv6 we don't need this functionality.

Based on EKS best practices all of nodes should be in private subnets, which does raise some compliance concerns when compared to legacy architecture but these should be mitigated by K8s native controls such as network policies.

**Comment by ppandiya** [comment]
@stevehipwell Thanks for the update.
I am using nat instances not nat gateway due to cost concerns. i have 6 subnets and 6 nat instances 1 per subnet. I have to distribute traffic to all 6 nat instances . Any ideas?

**Comment by stevehipwell** [comment]
@ppandiya I've learnt that fighting managed services such as EKS is almost never worth it; is the NAT cost saving worth the extra effort and being responsible for outages?

That said custom networking with a custom label works correctly. It's trivially easy to add zone based labels when using single zone ASGs; when using multi zone ASGs you need custom bootstrapping; if you're running AL2 self-managed this isn't hard, for AL2 managed you need to use a multi part cloud init userdata (https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1789 adds easy support for this), for Bottlerocket you can use a bootstrap container. If you let me know how you're creating your nodes I can probably offer something closer to a working example.
