### ISSUE TITLE
request traffic shaping support by using cni bandwidth plugin

### ISSUE THREAD

**Issue by ggaaooppeenngg** [aws/amazon-vpc-cni-k8s#1535]
**What happened**:

CNI has a bandwidth plugin. By adding the config below in 10-aws.conflist, it may work.
```
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15
- CNI Version 0.3.1
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.173-137.229.amzn2.x86_64

**Comment by jayanthvn** [comment]
Hi,

Currently this is blocked on containerd/cri#1544. I will look into this in couple weeks and update here - https://github.com/aws/amazon-vpc-cni-k8s/issues/1172.

Thank you.
