### ISSUE TITLE
Document WARM_ENI_TARGET , WARM_IP_TARGET and MINIMUM_IP_TARGET behaviour when using Security Group for Pods

### ISSUE THREAD

**Issue by pcolazurdo** [aws/amazon-vpc-cni-k8s#1537]
**What happened**:

Having a cluster that is mostly using Pods with Security Groups it seemed like a waste of IPs to have a WARM_ENI_TARGET=1 as the number of standard pods is very low and stable (kube-system related mostly) so when trying to understand how these settings would work together it became very hard to understand their interrelationship. 

I've found that the number of assigned IPs in the pool wasn't affected by the number of Pods with Security Groups so I've assumed these IPs were being handled in the amazon-vpc-resource-controller-k8s.

It would be nice to have a bit more documentation about this, and also any additional considerations that could be taken in this scenario (100% of the workload using Pods with Security Groups)

**Environment**:
Not Relevant

**Comment by jayanthvn** [comment]
Hi @pcolazurdo 

You can also set WARM_IP_TARGET to a very low number if you have entire workload using pods with security groups instead of WARM_ENI_TARGET. Currently this https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/eni-and-ip-target.md explains the number of IPs allocated with warm target combinations.

**Comment by pcolazurdo** [comment]
I agree, the challenge I've found that it took me a long time to understand that Branch ENIs ip-allocation (the ones used for Pods with Security Groups) isn't handled by the vpc-cni, so taking a decision about the number of IPs when the workload is mostly based on this type of Pods was difficult. Also, I don't know if there are plans to move these allocations to the CNI in the future, so I would like for this to be documented so it's easier to refer to it if something changes in the future

**Comment by jayanthvn** [comment]
Sure, I can add a note in readme on this. There is no plans to move these allocations to IPAMD in future.

**Comment by jayanthvn** [comment]
Merged #1565
