### ISSUE TITLE
Inconsistent ENI count attached to instances running 1.1.0

### ISSUE THREAD

**Issue by hobbsh** [aws/amazon-vpc-cni-k8s#154]
I have noticed an inconsistency in the number of ENI's attached to EKS nodes. I have not been able to correlate it to anything in particular - not hitting the ENI limit yet, doesn't seem related to an instance size but that was my initial thought. Seems like something was removed or added in 1.1.0 but the Changelog does not seem to call anything out related to this. 

In one VPC, all the m4.larges have 2 ENIs apiece so I assumed this is how the CNI is supposed to work. Then I spun up workers in a different VPC and some had 1 ENI, some had 2, and some had 3 (m5.xlarge instance size). So, I tried m4.xlarges and they all have 1 ENI - I would expect a larger instance to have more ENIs given it is going to be supporting more pods. 

Running `amazon-k8s-cni:1.1.0` on all the m4.xlarges and m5.xlarges but not on the m4.larges (running 1.0.0) which are the ones with an even distribution. If this is somehow normal/changed behavior or if I misconfigured something, it would be great to know. Additionally, if I can provide any information to help troubleshoot this issue, please let me know.

**Comment by liwenwu-amazon** [comment]
@hobbsh in v1.1.0, the number of ENIs attached to the instance is triggered by number of concurrent running Pods running  on the instance.
* when a worker node first joins the cluster, there is only 1 ENI along with all of its addresses in the ENI
* when number of pods running on the node exceeds the number of addresses on a single ENI, the CNI backend start allocating a new ENI and start using following allocation scheme:

```
Without any configuration, ipamD always try to keep one extra ENI.  

For example, a m4.4xlarge node can have up to 8 ENIs, and each ENI can have up to 30 IP addresses. ( https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html ).   

* If the number of current running Pods is between 0 to 29, ipamD will allocate one more eni. And Warm-Pool size is 2 eni * (30 -1) = 58 
* If the number of current running Pods is between 30 and 58, ipamD will allocate 2 more eni. And Warm-Pool size is 3 eni * (30 -1) = 87
```

**Comment by hobbsh** [comment]
@liwenwu-amazon thanks for the clarification. I see this is laid out in more complex language in the proposal - it would be great to add what you just said into the readme. Also, what do you mean by "without any configuration, ipamD will always try to keep one extra ENI" - does this mean that by deafult, all workers in an m4.xlarge should have at least 2 ENI?

I created a PR to pull what you said into the readme.

**Comment by liwenwu-amazon** [comment]
@hobbsh  in v1.1.0, m4.xlarge should have 1 ENI initially.  When number of Pods running stays between 0 and 15, it stays with 1 ENI.  Once the number of Pods running on the node exceeds 15, it will start `always keep one extra ENI` behavior.  For example,  if number of pods is 16 to 30, ipamD will allocate 2 ENIs. If number of Pods is 31 to 45, ipamD will allocate 3 ENIs.  Also, even after number of pods drops to 0 to 15, ipamD still keeps 1 ENI around and free the other 2 ENIs.

**Comment by hobbsh** [comment]
I see, so when I had some nodes with 3 ENIs and some with 1, the cluster must've just been balanced a bit strange. I will upgrade the outdated cluster to bring it up to par. Thanks

**Comment by dvohra** [comment]
> Once the number of Pods running on the node exceeds 15, it will start always keep one extra ENI behavior.

If the number of Pods on a m4.xlarge exceeds 15 another ENI is needed as first ENI's IP Addresses capacity has been exceeded. ipamD allocating another ENI isn't "keep one extra ENI" implementation. Also another ENI is allocated if number of Pods exceed 14 because one IP Address is for the ENI primary IP Address. 
Does the documentation need to be updated? As discussed in documentation.

> For example, a m4.4xlarge node can have up to 8 ENIs, and each ENI can have up to 30 IP addresses. 
> 
> -If the number of current running Pods is between 0 to 29, ipamD will allocate one more eni. And Warm-Pool size is 2 eni * (30 -1) = 58
> -If the number of current running Pods is between 30 and 58, ipamD will allocate 2 more eni. And Warm-Pool size is 3 eni * (30 -1) = 87

**Comment by dvohra** [comment]
> in v1.1.0, m4.xlarge should have 1 ENI initially. When number of Pods running stays between 0 and 15, it stays with 1 ENI. Once the number of Pods running on the node exceeds 15, it will start always keep one extra ENI behavior. For example, if number of pods is 16 to 30, ipamD will allocate 2 ENIs. If number of Pods is 31 to 45, ipamD will allocate 3 ENIs. Also, even after number of pods drops to 0 to 15, ipamD still keeps 1 ENI around and free the other 2 ENIs.

Tested with v1.10 and none of the preceding implementation gets applied.
Instance type is c1.medium

Instance Type | Maximum Network Interfaces | IPv4 Addresses per Interface | IPv6 Addresses per Interface
-- | -- | -- | --
c1.medium | 2 | 6 | IPv6 not supported

ENI Allocation:
Initially 1 ENI per node in a cluster of 3 nodes
Up till 15 Pods # of ENIs is 1 per node
At the 16th Pod # of ENIs becomes 3 per node (which does implement the 1 extra ENI)
Scaling to 45 Pods actually starts 44 Pods, not 45
Scaling down from 45 to 15 Pods does not reduce the # of ENIs which is still 3 per node

**Comment by dvohra** [comment]
Maximum ENIs per node instance is the issue, not maximum addresses per ENI.
Isn't `WARM_IP_TARGET` environment variable for configurable IP Address Pool?

**Comment by liwenwu-amazon** [comment]
@dvohra This is NOT WARM_IP_TARGET.  It is a internal variable which is used to calculate whether to allocate a new ENI.   Since it is not set correctly, it will not trigger allocating new ENI.  Let me modify the title to make it more clear. thanks

**Comment by liwenwu-amazon** [comment]
@dvohra , for your case, `c.medium`,   although ipamD desires to have 3 ENIs worth of IPs in its WARM-IP pool,  it will NOT allocate 3 ENIs since the max number of ENI for `c.medium` is 2.  In your console,  only 2 of those ENIs are allocated by ipamD.    You can tell by its descriptions that all ENI allocated by ipamD have descriptions of `aws-K8S-i-<instance-id>`

**Comment by dvohra** [comment]
Does iPAMD only allocate/deallocate new ENIs and not the first ENI on each node? Because the first ENI allocated by default does not have the `aws-K8S-i-<instance-id>` description.  Seems like iPAMD does not take into consideration that 1 ENI is already allocated.

**Comment by liwenwu-amazon** [comment]
@dvohra  From our database,  i-0a232da4c56915e21 is a t2.medium, not c.medium.  t2.medium allows 3 ENIs

**Comment by dvohra** [comment]
Thanks. The instance type is indeed `t2.medium`, not `c.medium`.  But the fluctuation in ENIs is, or was if issue is fixed, not per specification.

**Comment by dvohra** [comment]
On `**t2.medium**`, on scaling from 5 to 9 Pods allocates two new ENIs on the same instance, and none of the two new ENIs are used.   Refer enclosed screenshot. 
![newenis](https://user-images.githubusercontent.com/3654431/45129896-24991880-b13b-11e8-95e1-16b4fe50a473.jpg)

```

C:\EKS>kubectl get pods -o wide
NAME                                READY     STATUS    RESTARTS   AGE       IP
               NODE
nginx-deployment-75675f5897-56lzd   1/1       Running   0          20s       192
.168.241.220   ip-192-168-209-196.ec2.internal
nginx-deployment-75675f5897-59trh   1/1       Running   0          20s       192
.168.76.65     ip-192-168-120-102.ec2.internal
nginx-deployment-75675f5897-624cn   1/1       Running   0          2h        192
.168.119.147   ip-192-168-120-102.ec2.internal
nginx-deployment-75675f5897-ddrwr   1/1       Running   0          20s       192
.168.192.73    ip-192-168-209-196.ec2.internal
nginx-deployment-75675f5897-lmtbq   1/1       Running   0          2h        192
.168.168.58    ip-192-168-146-69.ec2.internal
nginx-deployment-75675f5897-nj4kh   1/1       Running   0          1h        192
.168.182.75    ip-192-168-146-69.ec2.internal
nginx-deployment-75675f5897-rh5sm   1/1       Running   0          1h        192
.168.121.11    ip-192-168-120-102.ec2.internal
nginx-deployment-75675f5897-rhf6x   1/1       Running   0          20s       192
.168.142.85    ip-192-168-146-69.ec2.internal
nginx-deployment-75675f5897-wgmhx   1/1       Running   0          1h        192
.168.220.152   ip-192-168-209-196.ec2.internal
```

The node  `ip-192-168-209-196.ec2.internal` has instance id `i-032c3c1f0e67862be` on which the 2 new Pods are started. Refer 
![instance-newpods](https://user-images.githubusercontent.com/3654431/45130086-02ec6100-b13c-11e8-915b-e9f32c927b18.jpg)

A total of 3 ENIs for 3 Pods on the instance and only the Secondary IPs from the 1st ENI already allocated are used. Refer screenshot for Secondary IPs and the IPs of 2 of the new Pods listed with `kubectl get pods -o wide` are from the default ENI on which two new ENIs are started.
![secondaryipsfromdefaulteni](https://user-images.githubusercontent.com/3654431/45130333-0af8d080-b13d-11e8-9425-e51187846fe2.jpg)

**Comment by liwenwu-amazon** [comment]
@dvohra   are you running ipamD from PR #169 ?

**Comment by liwenwu-amazon** [comment]
@dvohra  Current EKS worker node uses CNI v1.1.0.   You can wait till CNI1.2.0 which will have this change.  Or you have to manually checkout PR #169, build it and upgrade your cluster with your private built image.

**Comment by dvohra** [comment]
When is CNI1.2.0 expected?

**Comment by vladfr** [comment]
Hi! Leaving this here: when is CNI 1.2 expected?

I have a rather different scenario: I need to spin up a set of workers with c4.4xlarge, that will be used for ML (cpu heavy). I won't ever need more than 20 running pods.  Currently, at boot `cni` allocates 1 ENI with 30 IPs (max for my instance type). I've tried setting `max_pods` at 20 and starting kubelet with `WARM_IP_TARGET` to no avail. Any insight? @liwenwu-amazon

**Comment by hobbsh** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.2.0

**Comment by dvohra** [comment]
Thanks hobbsh. vladfr  what is the expected number of ENIs. The cluster starts with more than requested ENIs because some ENIs are also used by Kubernetes system pods `kube-proxy`, `kube-dns`.

**Comment by dvohra** [comment]
hobbsh. What was implied was that when shall EKS support CNI 1.2?

**Comment by hobbsh** [comment]
I dont know the details - all I know is a release was cut. I was told more details are coming in terms of upgrading.

**Comment by vladfr** [comment]
@dvohra we wouldn't run more than 16 containers on these nodes, 1 per core. Reducing the initial pool of IPs to 20 would allow for sufficient scaling. We are in an env where we are constrained by IP space, due to factors not in our control :(

**Comment by dvohra** [comment]
Use an instance type that limits # Pods per instance further than the default setting. The `c1.medium` type supports only 2 ENIs per node with 5 schedulable pods per ENI for a total of 10 IPs per node.

**Comment by vladfr** [comment]
@liwenwu-amazon I tried that, but the allocation at boot is still 1 ENI + all its IPs. I took a cursory look at the go code and that seems to be the way it's written.

**Comment by dvohra** [comment]
`WARM_IP_TARGET` is not settable in EKS as CNI plugin is already implemented.

**Comment by vladfr** [comment]
Thanks. Yes, that is my experience as well... I can redeploy cni at set it
from yaml, but I need it at boot.

I probably need to modify the bootstrap script and see if the kubelet can
actually support it.

**Comment by dvohra** [comment]
_Is WARM_IP_TARGET to be set in the kubeconfig file?_
The env variable is set in the `aws-node` daemonset.
`kubectl edit daemonset aws-node --namespace=kube-system`

**Comment by vladfr** [comment]
@dvohra thanks for your help. Indeed I can confirm that `WARM_IP_TARGET` works as intended. I was confused and thought the CNI code runs outside kube, but I now realise that the `bootstrap.sh` script on the AMI just configures it as a `daemonset` via yaml.

**Comment by tabern** [comment]
This issue is deprecated as of version 1.3.2

**Comment by mshakhmaykin** [comment]
> @dvohra thanks for your help. Indeed I can confirm that `WARM_IP_TARGET` works as intended.

Let me second that! In fact this behavior should perhaps be more clearly documented here. Or maybe the default value should be set to a reasonable restrictive number.

**Comment by dvohra** [comment]
Thanks for the update.
