### ISSUE TITLE
Enable use of EC2 IP prefixes

### ISSUE THREAD

**Issue by alter3d** [aws/amazon-vpc-cni-k8s#1547]
A recent annoucement by AWS (https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-virtual-private-cloud-vpc-customers-can-assign-ip-prefixes-ec2-instances/) describes the ability to assign prefixes to an EC2 instance for higher IP-per-host density.

The CNI driver should implement this feature by supporting a configurable subnet-size-per-interface and being able to search the VPC for free blocks of the appropriate size.  It MAY make sense to enable this feature by default, with conservative default values (e.g. assign a /28 per interface)

**Comment by morganchristiansson** [comment]
Looks like it will be included in v1.9.0 https://github.com/aws/amazon-vpc-cni-k8s#enable_prefix_delegation-v190

**Comment by alter3d** [comment]
@morganchristiansson Good find, and great news!  I don't see an option to tweak the prefix size -- just a fixed /28 -- which would be a nice additional feature enhancement.

**Comment by achevuru** [comment]
@alter3d Current support is only for /28 prefixes (v4), so this is not VPC CNI limitation.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html#ec2-prefix-basics

**Comment by alter3d** [comment]
@achevuru Understood -- closing this issue as it looks like it's fully implemented until the VPC/EC2 team support different prefix sizes.  Thanks!
