### ISSUE TITLE
node permission verbs needs "patch"

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1555]
deployed v1.8 and got this error:
```
nodes "<IP>" is forbidden: User "system:serviceaccount:default:aws-cni" cannot patch resource "nodes" in API group "" at the cluster scope
```

so patch need to be added here https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L41-L45

**Comment by jayanthvn** [comment]
Hi @grosser 

Was this working before and now with 1.8 you are seeing the error? We never had "patch" for node resource since aws-node doesn't patch the node.

**Comment by grosser** [comment]
I think we had this fix for along time, I just made backfill issue now so it's tracked.

**Comment by grosser** [comment]
could it be coming from the initcontainer ?

**Comment by grosser** [comment]
this looks like the culprit https://github.com/aws/amazon-vpc-cni-k8s/blob/2446813b6244f4492cc91a87a8c127e1cd6f1cc5/test/framework/resources/k8s/resources/node.go#L60-L62

**Comment by grosser** [comment]
hmmm no, that's in test framework :/

**Comment by grosser** [comment]
can't find anything in the code ... any idea how I could track this down ?

**Comment by grosser** [comment]
... ok, nvm ... we run a custom script as part of cni startup 🤦
