### ISSUE TITLE
Clarification on pod density with Security Groups for Pods with new ENABLE_PREFIX_DELEGATION

### ISSUE THREAD

**Issue by larhauga** [aws/amazon-vpc-cni-k8s#1557]
Hi,
we are running EKS clusters where most deployments have different SecurityGroups + SGPs. 

With the release of 1.9.0 with `ENABLE_PREFIX_DELEGATION` to enable higher pod density, we are wondering if this would be the case also when `ENABLE_POD_ENI` is configured to true.

If this is not the case, is there any upcoming features that would increase the pod density for SGFPs?

I could not find any documentation on this specific case, so sorry for the inconvenience of an GH issue. Hopefully we are not the only ones that are wondering about this.

Thanks!

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.8
- CNI Version: 1.9.0
- OS (e.g: `cat /etc/os-release`): Bottlerocket 1.1.2
- Kernel (e.g. `uname -a`): 5.10.35

**Comment by jayanthvn** [comment]
Hi @larhauga 

The feature doesn't increase the pod density of branch pods since we are limited by the number of branch network interfaces - https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#supported-instance-types. ASFAIK there is no upcoming feature for increasing pod density for SGPP pods but would double check and let you know if there is any plans. I will also update documentation for this.

Hope this helps.

**Comment by Shaiou** [comment]
Hello,
 
  We are also using EKS with security group for pods enable and were wondering which value to set among all the 'WARM_*" documented here https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/prefix-and-ip-target.md would be beneficial/detrimental to us. Could you shed some light for us please ?

**Comment by jayanthvn** [comment]
Hi @Shaiou 

Yes with the PR #1565 , I will update the documentation. None of the WARM targets will impact pods with SGPP enabled. For example, a c5.4xlarge can continue to have up to 234 secondary IP addresses assigned to standard network interfaces and up to 54 branch network interfaces. Each branch network interface (ENI) only receives a single primary IP address and this address will be allocated to the branch pods behind branch ENI. So the WARM targets setting should be based off the number of pods which are behind the regular ENI or in there words which are not pods with SG enabled. 

Please let me know if it clarifies.

Thanks!

**Comment by jayanthvn** [comment]
Merged #1565

**Comment by Shaiou** [comment]
Thanks a lot @jayanthvn , it's much clearer indeed. Is there any planned evolution to have an equivalent improvement for SGPP like for instance reserving a subset of IPs for the host itself and attributing them to the branch ENIs as they come along. We kind of feel lef out of this nice improvement ;)

**Comment by abhipth** [comment]
Hi @Shaiou we have a roadmap item for tracking this - https://github.com/aws/containers-roadmap/issues/1342
