### ISSUE TITLE
[Query] Why does EKS cluster is not created with the recommended version of aws-vpc-cni plugin?

### ISSUE THREAD

**Issue by amitkatyal** [aws/amazon-vpc-cni-k8s#1564]
I deployed the EKS cluster with k8s version 1.21 but the default AWS-VPC-CNI-PLUGIN version is 1.7.5.
Any specific reason of why the EKS cluster is not created with the recommended version of the AWS-VPC-CNI?

In order to migrate to the latest version (1.9), just adapting the existing aws-node to the AWS-VPC-CNI helm chart release should be good enough?

**Comment by jayanthvn** [comment]
Hi,

Yes the EKS default is currently 1.7.5. Generally once most of the bugs are fixed and have few enhancements/optimizations then we update the default version. Currently we are looking into updating the EKS default. 

Yes to upgrade to 1.9 you can use helm or

**Comment by amitkatyal** [comment]
@jayanthvn, Thanks for the quick reply!

**Comment by jayanthvn** [comment]
No problem. Please do reach out for any questions.
