### ISSUE TITLE
Add support for m6i instance type

### ISSUE THREAD

**Issue by uthark** [aws/amazon-vpc-cni-k8s#1575]
**What would you like to be added**:

Please add support for `m6i` instance type that was announced recently https://aws.amazon.com/blogs/aws/new-amazon-ec2-m6i-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/ 
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/eni-max-pods.txt doesn't list the new instance types.

**Why is this needed**:
To support new instance type family. It would allow using `m6i` instances in kubernetes clusters which use AWS VPC CNI Plugin.

**Comment by jayanthvn** [comment]
Thank you. Will update the eni-max-pods.

**Comment by jayanthvn** [comment]
#1576 merged to master. We will pick it up in the next release.
