### ISSUE TITLE
Deprecated CustomResourceDefinition API in Deployment Charts

### ISSUE THREAD

**Issue by technotaff-nbs** [aws/amazon-vpc-cni-k8s#1581]
**What happened**:
The following CRD's are using deprecated APIs that are due to be removed in kubernetes 1.22:

[eniconfigs.crd.k8s.amazonaws.com
](https://github.com/aws/amazon-vpc-cni-k8s/blob/492feb12850e2308ab89117793f17060a2ea0e08/config/master/aws-k8s-cni-cn.yaml#L54)securitygrouppolicies.vpcresources.k8s.aws

**What you expected to happen**:
These CustomResourceDefinition should be using [apiextensions.k8s.io/v1](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#customresourcedefinition-v1-apiextensions-k8s-io) instead of apiextensions.k8s.io/v1beta1.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubent
----8<----8<--[ OUTPUT TRUNCATED ]--8<----8<----
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                             NAMESPACE     NAME                                         API_VERSION                            REPLACE_WITH (SINCE)
CustomResourceDefinition         <undefined>   eniconfigs.crd.k8s.amazonaws.com             apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1 (1.16.0+)
CustomResourceDefinition         <undefined>   securitygrouppolicies.vpcresources.k8s.aws   apiextensions.k8s.io/v1beta1           apiextensions.k8s.io/v1 (1.16.0+)
----8<----8<--[ OUTPUT TRUNCATED ]--8<----8<----
```

These CRDs need to be removed before EKS 1.22 can be deployed.

**Comment by jayanthvn** [comment]
Hi @technotaff-nbs 

There is an open PR to fix this - https://github.com/aws/amazon-vpc-cni-k8s/pull/1534

**Comment by jayanthvn** [comment]
#1534 is merged.

For `securitygrouppolicies.vpcresources.k8s.aws` you might want to open an issue here - https://github.com/aws/amazon-vpc-resource-controller-k8s
