### ISSUE TITLE
coredns-degraded when creating nodes

### ISSUE THREAD

**Issue by LinuxAdmin1** [aws/amazon-vpc-cni-k8s#1584]
**What happened**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Hi @LinuxAdmin1 

Are you seeing this message as coredns-degraded with managed add-on UI? Also can you please mention the steps to repro and any functional impact?

**Comment by jayanthvn** [comment]
Closing the issue for now. Please feel free to re-open if further investigation is needed.
