### ISSUE TITLE
CNI Metrics Helper CloudWatch Kubernetes Namespace Not Created

### ISSUE THREAD

**Issue by qgervacio** [aws/amazon-vpc-cni-k8s#1599]
**What happened**:

What could be the reason for the CloudWatch Kubernetes namespace to be not created? Followed the steps in https://docs.aws.amazon.com/eks/latest/userguide/cni-metrics-helper.html and able to see the namespace. Did the same in our internal eks cluster however the namespace is not created. 

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`
- CNI Helper Metrics Version:
`602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/cni-metrics-helper:v1.9.0`
- OS (e.g: `cat /etc/os-release`):
`NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`
- Kernel (e.g. `uname -a`):
`Linux ip-10-0-196-21 4.14.238-182.422.amzn2.x86_64 #1 SMP Tue Jul 20 20:35:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

CNI Helper Metrics Logs:
`
{"level":"info","ts":"2021-08-31T09:18:42.568Z","caller":"runtime/proc.go:203","msg":"Starting CNIMetricsHelper. Sending metrics to CloudWatch: true, LogLevel Debug"}
I0831 09:18:44.636331       1 request.go:621] Throttling request took 1.043285373s, request: GET:https://192.168.8.1:443/apis/coordination.k8s.io/v1?timeout=32s
{"level":"info","ts":"2021-08-31T09:19:17.019Z","caller":"runtime/proc.go:203","msg":"Collecting metrics ..."}
{"level":"info","ts":"2021-08-31T09:19:17.120Z","caller":"metrics/cni_metrics.go:195","msg":"Total aws-node pod count:- %!(EXTRA int=5)"}
{"level":"debug","ts":"2021-08-31T09:19:17.129Z","caller":"metrics/metrics.go:382","msg":"cni-metrics text output: # HELP awscni_add_ip_req_count The number of add IP address requests\n# TYPE awscni_add_ip_req_count ... <snip>"}
{"level":"debug","ts":"2021-08-31T09:19:17.130Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: false, noPreviousDataPoint: true, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.130Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: false, noPreviousDataPoint: true, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.130Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: false, noPreviousDataPoint: true, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.138Z","caller":"metrics/metrics.go:382","msg":"cni-metrics text output: # HELP awscni_add_ip_req_count The number of add IP address requests\n# TYPE awscni_add_ip_req_count ... <snip>"}
{"level":"debug","ts":"2021-08-31T09:19:17.145Z","caller":"metrics/metrics.go:382","msg":"cni-metrics text output: # HELP awscni_add_ip_req_count The number of add IP address requests\n# TYPE awscni_add_ip_req_count ... <snip>"}
{"level":"debug","ts":"2021-08-31T09:19:17.146Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: true, noPreviousDataPoint: false, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.146Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: true, noPreviousDataPoint: false, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.157Z","caller":"metrics/metrics.go:382","msg":"cni-metrics text output: # HELP awscni_add_ip_req_count The number of add IP address requests\n# TYPE awscni_add_ip_req_count ... <snip>"}
{"level":"debug","ts":"2021-08-31T09:19:17.157Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: true, noPreviousDataPoint: false, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.165Z","caller":"metrics/metrics.go:382","msg":"cni-metrics text output: # HELP awscni_add_ip_req_count The number of add IP address requests\n# TYPE awscni_add_ip_req_count ... <snip>"}
{"level":"debug","ts":"2021-08-31T09:19:17.166Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: true, noPreviousDataPoint: false, noCurrentDataPoint: false"}
{"level":"debug","ts":"2021-08-31T09:19:17.166Z","caller":"metrics/metrics.go:261","msg":"Reset detected resetDetected: true, noPreviousDataPoint: false, noCurrentDataPoint: false"}
{"level":"info","ts":"2021-08-31T09:19:47.019Z","caller":"runtime/proc.go:203","msg":"Collecting metrics ..."}
.
.
<snip>
`

**Comment by jayanthvn** [comment]
Hi @qgervacio 

I do see reset detected errors, can you please try increasing - `http-put-response-hop-limit`

```
By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level. You can adjust the hop limit using the modify-instance-metadata-options command if you need to make it larger. For example, you might need a larger hop limit for backward compatibility with container services running on the instance. For more information, see modify-instance-metadata-options in the AWS CLI Command Reference. 
```
Ref : https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/configuring-instance-metadata-service.html

```
 modify-instance-metadata-options
--instance-id <value>
[--http-tokens <value>]
[--http-put-response-hop-limit <value>]
[--http-endpoint <value>]
[--dry-run | --no-dry-run]
[--http-protocol-ipv6 <value>]
[--cli-input-json <value>]
[--generate-cli-skeleton <value>]
```

**Comment by jayanthvn** [comment]
Hi @qgervacio 

Closing this issue for now, please try increasing - `http-put-response-hop-limit` and do reach out if you need any help.

Thanks!

**Comment by atileren** [comment]
Hi @jayanthvn 

why should we increase http-put-response-hop-limit? when we encounter resetDetected error? I use managed nodes and I don't want to edit instance-metadata-options. could it be different reason?

Thanks
