### ISSUE TITLE
Pod inaccessible stuck `Running` when cni `failed to assign an IP address to container`

### ISSUE THREAD

**Issue by pedroslopez** [aws/amazon-vpc-cni-k8s#1602]
**What happened**:
After triggering an image update for multiple deployments, one of these never came back up. Looking into the events, I saw errors relating to getting an IP:

```
 Normal   TriggeredScaleUp        55m                  cluster-autoscaler  pod triggered scale-up: [{XXX-cluster-worker-group-120210622140656650300000010 5->7 (max: 10)}]
  Warning  FailedScheduling        54m (x8 over 55m)    default-scheduler   0/5 nodes are available: 5 Too many pods.
  Warning  FailedScheduling        54m                  default-scheduler   0/6 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 5 Too many pods.
  Normal   Scheduled               54m                  default-scheduler   Successfully assigned default/grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds to ip-10-1-3-32.ec2.internal
  Warning  FailedCreatePodSandBox  54m                  kubelet             Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3287afa1ccabfeed92bb54bea07b284dfc21ea16f7f3113994169c3e2c2429b6" network for pod "grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds": networkPlugin cni failed to set up pod "grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds_default" network: add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  54m                  kubelet             Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "fb53a7cc8811c6b53d316ebfe39fda1337dc7013997fd0eb0085b0ee2b2c67db" network for pod "grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds": networkPlugin cni failed to set up pod "grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds_default" network: add cmd: failed to assign an IP address to container
```

Interestingly, the pod was stuck in `Running` state, unlinke other issues I've seen here where it gets stuck in `ContainerCreating`. The container however did not start up.

According to the subnets, there are still enough IPs available:

![image](https://user-images.githubusercontent.com/4368928/132069602-7e1c201e-494f-49a1-b856-91a06b531107.png)

ipamd logs from that time period are available here https://gist.github.com/pedroslopez/38fe6a7860d0d5d4ea199c9ad50085f8 Note that sensitive data has been replaced.

It took manually killing the pod and letting kubernetes reschedule it for it to start up properly (it went to another node). Any ideas what could be going on here?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7
- CNI Version: v1.7.5-eksbuild.1
- OS: linux

**Comment by jayanthvn** [comment]
Hi @pedroslopez 

I see these errors in the logs - 

```
{"level":"debug","ts":"2021-09-02T21:37:16.672Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignIPv4Address: IP address pool stats: total: 15, assigned 14"}
{"level":"debug","ts":"2021-09-02T21:37:16.672Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-0bc8d387e5d44c0ea does not have available addresses"}
{"level":"debug","ts":"2021-09-02T21:37:16.672Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-0951da6c549dc883c does not have available addresses"}
{"level":"debug","ts":"2021-09-02T21:37:16.672Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-007516e683d5e705f does not have available addresses"}
{"level":"error","ts":"2021-09-02T21:37:16.672Z","caller":"ipamd/rpc_handler.go:142","msg":"DataStore has no available IP addresses"}
```
So none of the ENIs have IPs attached even though there are IP address available in the subnet.

Can you please share the EC2 error code from ipamd.logs on why EC2 is not able to alloc IP address for any of the ENIs? You will be able find it either in the aws-node startup while attaching IPs to the primary ENI  [https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.7.5/pkg/ipamd/ipamd.go#L420] or during reconcilation - https://github.com/aws/amazon-vpc-cni-k8s/blob/eb63a013949c1ad5335ac9c229b2e136a1896797/pkg/ipamd/ipamd.go#L613.

Thanks!

**Comment by pedroslopez** [comment]
Hi @jacksontj, thanks for the quick response!

It doesn't seem like an error is being logged here... 

Logs during reconciliation:
```
{"level":"debug","ts":"2021-09-02T21:37:30.041Z","caller":"ipamd/ipamd.go:476","msg":"Reconciling ENI/IP pool info because time since last 1m0.018914893s <= 1m0s"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:476","msg":"Reconcile existing ENI eni-007516e683d5e705f IP pool"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:1019","msg":"Reconcile and skip primary IP 10.1.3.61 on ENI eni-007516e683d5e705f"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:476","msg":"Reconcile existing ENI eni-0951da6c549dc883c IP pool"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:1019","msg":"Reconcile and skip primary IP 10.1.3.249 on ENI eni-0951da6c549dc883c"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:476","msg":"Reconcile existing ENI eni-0bc8d387e5d44c0ea IP pool"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:1019","msg":"Reconcile and skip primary IP 10.1.3.32 on ENI eni-0bc8d387e5d44c0ea"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:476","msg":"Successfully Reconciled ENI/IP pool"}
{"level":"debug","ts":"2021-09-02T21:37:30.050Z","caller":"ipamd/ipamd.go:476","msg":"IP Address Pool stats: total: 15, assigned: 14"}
{"level":"info","ts":"2021-09-02T21:37:30.479Z","caller":"rpc/rpc.pb.go:504","msg":"Received DelNetwork for Sandbox 24c8af9065c26a4916dce87b5b717bf7a557febf413dc9d181b0194450b7b12e"}
{"level":"debug","ts":"2021-09-02T21:37:30.479Z","caller":"rpc/rpc.pb.go:504","msg":"DelNetworkRequest: ClientVersion:\"v1.7.5\" K8S_POD_NAME:\"grouparoo-app-XXXXXXXXX-web-99d78bd5c-zp5ds\" K8S_POD_NAMESPACE:\"default\" K8S_POD_INFRA_CONTAINER_ID:\"24c8af9065c26a4916dce87b5b717bf7a557febf413dc9d181b0194450b7b12e\" Reason:\"PodDeleted\" ContainerID:\"24c8af9065c26a4916dce87b5b717bf7a557febf413dc9d181b0194450b7b12e\" IfName:\"eth0\" NetworkName:\"aws-cni\" "}
{"level":"debug","ts":"2021-09-02T21:37:30.480Z","caller":"ipamd/rpc_handler.go:221","msg":"UnassignPodIPv4Address: IP address pool stats: total:15, assigned 14, sandbox aws-cni/24c8af9065c26a4916dce87b5b717bf7a557febf413dc9d181b0194450b7b12e/eth0"}
{"level":"debug","ts":"2021-09-02T21:37:30.480Z","caller":"ipamd/rpc_handler.go:221","msg":"UnassignPodIPv4Address: Failed to find IPAM entry under full key, trying CRI-migrated version"}
{"level":"warn","ts":"2021-09-02T21:37:30.480Z","caller":"ipamd/rpc_handler.go:221","msg":"UnassignPodIPv4Address: Failed to find sandbox _migrated-from-cri/24c8af9065c26a4916dce87b5b717bf7a557febf413dc9d181b0194450b7b12e/unknown"}
{"level":"info","ts":"2021-09-02T21:37:30.480Z","caller":"rpc/rpc.pb.go:504","msg":"Send DelNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: unknown pod"}
{"level":"info","ts":"2021-09-02T21:37:30.959Z","caller":"rpc/rpc.pb.go:486","msg":"Received AddNetwork for NS /proc/27616/ns/net, Sandbox cd8369fea33713e13f5d580ec90529c9c2107d831752939e21bcb209594e1aa2, ifname eth0"}
{"level":"debug","ts":"2021-09-02T21:37:30.960Z","caller":"rpc/rpc.pb.go:486","msg":"AddNetworkRequest: ClientVersion:\"v1.7.5\" K8S_POD_NAME:\"grouparoo-app-XXXXXXXXXX-web-99d78bd5c-zp5ds\" K8S_POD_NAMESPACE:\"default\" K8S_POD_INFRA_CONTAINER_ID:\"cd8369fea33713e13f5d580ec90529c9c2107d831752939e21bcb209594e1aa2\" ContainerID:\"cd8369fea33713e13f5d580ec90529c9c2107d831752939e21bcb209594e1aa2\" IfName:\"eth0\" NetworkName:\"aws-cni\" Netns:\"/proc/27616/ns/net\" "}
{"level":"debug","ts":"2021-09-02T21:37:30.960Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignIPv4Address: IP address pool stats: total: 15, assigned 14"}
{"level":"debug","ts":"2021-09-02T21:37:30.960Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-0951da6c549dc883c does not have available addresses"}
{"level":"debug","ts":"2021-09-02T21:37:30.960Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-007516e683d5e705f does not have available addresses"}
{"level":"debug","ts":"2021-09-02T21:37:30.960Z","caller":"ipamd/rpc_handler.go:142","msg":"AssignPodIPv4Address: ENI eni-0bc8d387e5d44c0ea does not have available addresses"}
{"level":"error","ts":"2021-09-02T21:37:30.960Z","caller":"ipamd/rpc_handler.go:142","msg":"DataStore has no available IP addresses"}
```

Looking for when `increaseIPPool` runs, these logs do come up repeatedly:

```
{"level":"debug","ts":"2021-09-02T21:38:22.556Z","caller":"ipamd/ipamd.go:483","msg":"Starting to increase IP pool size"}
{"level":"debug","ts":"2021-09-02T21:38:22.556Z","caller":"ipamd/ipamd.go:483","msg":"Skipping ENI allocation as the max ENI limit of 3 is already reached (accounting for 0 unmanaged ENIs and 0 trunk ENIs)"}
{"level":"debug","ts":"2021-09-02T21:38:27.556Z","caller":"ipamd/ipamd.go:852","msg":"IP pool stats: total = 15, used = 15, c.maxIPsPerENI = 5"}
{"level":"debug","ts":"2021-09-02T21:38:27.556Z","caller":"ipamd/ipamd.go:482","msg":"IP pool is too low: available (0) < ENI target (1) * addrsPerENI (5)"}
```

But as I understand it, if an error had occurred in `tryAssignIPs` it would be logged between the first two.

**Comment by jayanthvn** [comment]
Hi @pedroslopez 

I want to correct my previous statement. I missed this log - 

```
"ipamd/ipamd.go:852","msg":"IP pool stats: total = 15, used = 15, c.maxIPsPerENI = 5"}
```
So the instance has 3 ENIs and 5 IPs per ENI and all 15 IPs are used. Since max ENIs are reached you are not able to add any more pods.

We know that issue happens when the pod IPs are in cool down and new pods gets scheduled on these nodes. Please ref to https://github.com/aws/amazon-vpc-cni-k8s/issues/1160 for more context and we are actively working on it. 

One way to mitigate this issue is to use this new feature - https://aws.amazon.com/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/.

Thanks.

**Comment by pedroslopez** [comment]
Interesting! So even though there's a limit set on the max number of pods that can run per node, there may still not be enough IPs available if the IPs are on "cooldown"? Does that mean that as it stands, these pods that get stuck when this edge case happens need to be manually killed?

Good to know that a scheduler extension is being worked on- we'll definitely take a look at the linked feature.

**Comment by jayanthvn** [comment]
Yes it has to be manually killed. I am checking other options to mitigate this issue along with scheduler extender.

**Comment by glaracuente** [comment]
I'm in a similar situation, except I do have free ENI IPs. Some ipamd logs with redacted sensitive info:

`{"level":"info","ts":"2021-09-09T21:10:57.034Z","caller":"rpc/rpc.pb.go:519","msg":"Received DelNetwork for Sandbox 0c89370030fb85c73825f2a4779dfa29c93d68e315758a8badd309d"}
{"level":"debug","ts":"2021-09-09T21:10:57.034Z","caller":"rpc/rpc.pb.go:519","msg":"DelNetworkRequest: ClientVersion:\"v1.9.0\" K8S_POD_NAME:\"jobname-2021-09-09-20-20-55-q5tzp\" K8S_POD_NAMESPACE:\"env\" K8S_POD_INFRA_CONTAINER_ID:\"0c89370030fb85f2a4779dfa29c93d68e315758a8ba4f352bf1bdd309d\" Reason:\"PodDeleted\" ContainerID:\"0c89370030fb85c9dfa29c93d68e315758a8ba4f352bf1bdd309d\" IfName:\"eth0\" NetworkName:\"aws-cni\" "}
{"level":"debug","ts":"2021-09-09T21:10:57.034Z","caller":"ipamd/rpc_handler.go:204","msg":"UnassignPodIPv4Address: IP address pool stats: total:5, assigned 1, sandbox aws-cni/0c89370030fb85c73825f2a4779dfa29c93d68e315758a8ba4f352bf1bdd309d/eth0"}
{"level":"debug","ts":"2021-09-09T21:10:57.034Z","caller":"ipamd/rpc_handler.go:204","msg":"UnassignPodIPv4Address: Failed to find IPAM entry under full key, trying CRI-migrated version"}
{"level":"warn","ts":"2021-09-09T21:10:57.034Z","caller":"ipamd/rpc_handler.go:204","msg":"UnassignPodIPv4Address: Failed to find sandbox _migrated-from-cri/0c89370030fb85c73825f2a4779dfa29c93d68e315758a4f352bf1bdd309d/unknown"}
{"level":"info","ts":"2021-09-09T21:10:57.040Z","caller":"rpc/rpc.pb.go:519","msg":"Send DelNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: unknown pod"}`

It seems like it failing to remove an IP? Maybe that's my root issue? Not sure but let me know if these log lines look familiar to anyone.

**Comment by glaracuente** [comment]
FYI I just finished working with AWS support and figured out my issue. Completed Jobs in the cluster were not releasing their IPs, so we were running out of ENI IPs, but blind to the issue.

The related bug is here: https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/33

In order to move past this, we are upgrading our cluster to v1.21 in order to gain the feature of adding _ttlSecondsAfterFinished_ to our job manifests, in order to clean up old job pods, and therefore IPs

**Comment by jayanthvn** [comment]
@pedroslopez - Closing the issue, please feel free to reach out for any help.
