### ISSUE TITLE
Question about charts/aws-calico vs. calico's chart

### ISSUE THREAD

**Issue by nuriel77** [aws/amazon-vpc-cni-k8s#1603]
**What happened**:

We'd like to use Calico's policy engine in combination with EKS's AWS VPC CNI.
We've come across the [instructions ](https://docs.aws.amazon.com/eks/latest/userguide/calico.html). We are considering to install the [chart](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico).
What is the reason to maintain Calico's chart over here? Are there big differences in using it vs. the chart from Calico?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19 (EKS)
- CNI Version: v1.8.0-eksbuild.1
- EKS managed nodes AMI version 1.19.13-20210813

**Comment by jayanthvn** [comment]
Hi @nuriel77 

We do get EKS specific manifest/charts changes from calico team and also by default we set kubernetesProvider as EKS here - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-calico/values.yaml#L8. But if you need any more implementation specific details you can reach out here - https://github.com/projectcalico/calico.

**Comment by jayanthvn** [comment]
Please feel free to reach out if you have any more questions.
