### ISSUE TITLE
Taint for nodes does not supported

### ISSUE THREAD

**Issue by oded-dd** [aws/amazon-vpc-cni-k8s#162]
Although cni is daemon set (which should not be affected by the scheduler), nodes with Taint configured failed to run the CNI

**Comment by oded-dd** [comment]
Hi,

Sorry for the delay,

I've changed the toleration part to be:

      tolerations:
      - operator: Exists

Which basically supports running the `aws-node` on every instance, instead
of the current config, it solves the issue.

Thanks,

**Comment by oded-dd** [comment]
See attached the original file:

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: aws-node
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - list
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-node
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aws-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-node
subjects:
- kind: ServiceAccount
  name: aws-node
  namespace: kube-system

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: aws-node
  name: aws-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: aws-node
    spec:
      containers:
      - env:
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image:
602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.0.0
        name: aws-node
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/var/log
          name: log-dir
        - mountPath: /var/run/docker.sock
          name: dockersock
      hostNetwork: true
      serviceAccountName: aws-node
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /opt/cni/bin
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
        name: cni-net-dir
      - hostPath:
          path: /var/log
        name: log-dir
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
  updateStrategy:
    type: RollingUpdate

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    role.kubernetes.io/networking: "1"
  name: k8s-ec2-srcdst
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    role.kubernetes.io/networking: "1"
  name: k8s-ec2-srcdst
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    role.kubernetes.io/networking: "1"
  name: k8s-ec2-srcdst
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-ec2-srcdst
subjects:
- kind: ServiceAccount
  name: k8s-ec2-srcdst
  namespace: kube-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: k8s-ec2-srcdst
    role.kubernetes.io/networking: "1"
  name: k8s-ec2-srcdst
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: k8s-ec2-srcdst
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: k8s-ec2-srcdst
        role.kubernetes.io/networking: "1"
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: eu-west-1
        image: ottoyiu/k8s-ec2-srcdst:v0.2.0-3-gc0c26eca
        imagePullPolicy: Always
        name: k8s-ec2-srcdst
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ssl-certs
          readOnly: true
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: k8s-ec2-srcdst
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
        name: ssl-certs

**Comment by liwenwu-amazon** [comment]
@oded-dd good to know your issue is solved.  I am closing this for now. Please re-open it if this is still an issue. thanks

**Comment by oded-dd** [comment]
Hi,

I fixed it manually for my env. It should be fixed as part of kops, as you
can see in the file attached previously the current configuration on kops
does not support Taints
