### ISSUE TITLE
tigera-operator is not installed with helm chart. aws-calico Pods never get healthy.

### ISSUE THREAD

**Issue by sean-mcgimpsey** [aws/amazon-vpc-cni-k8s#1627]
**What happened**:
When installing the eks/aws-calico to enable network policy engine on EKS , the tigera-operator is not installed. I think this is resulting in the aws-calico pods never hitting a ready state. 

```
  Warning  Unhealthy         29m (x2 over 30m)     kubelet, ip-10-8-5-61.eu-west-2.compute.internal  Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
```

This may be by design but when i pull the helm chart , i dont see the tigera operator templates 

```
tar -zxvf aws-calico-0.3.8.tgz 
aws-calico/Chart.yaml
aws-calico/values.yaml
aws-calico/templates/_helpers.tpl
aws-calico/templates/config-map.yaml
aws-calico/templates/daemon-set.yaml
aws-calico/templates/deployment.yaml
aws-calico/templates/pod-disruption-budget.yaml
aws-calico/templates/podsecuritypolicy.yaml
aws-calico/templates/rbac.yaml
aws-calico/templates/service-accounts.yaml
aws-calico/templates/service.yaml
aws-calico/.helmignore
aws-calico/README.md
aws-calico/crds/crds.yaml
```

**What you expected to happen**:
I'd expect tigera-operator to be installed alongside calico...but i maybe wrong there.
Additionally i'd expect the default values to return a functioning install of calico. 

**How to reproduce it (as minimally and precisely as possible)**:
Install the chart with default options on EKS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- CNI Version: aws-cni

**Comment by haouc** [comment]
Hey @sean-mcgimpsey,

Thanks for reporting the issue to us. Do you mind to share how you installed Calico operator from CNI repo? 

I tried installing the operator and calico nodes from a Linux box. That works and I got this
```
% helm upgrade --install --recreate-pods --force aws-calico --namespace kube-system charts/aws-calico
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/zhuhz/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/zhuhz/.kube/config
Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods
Release "aws-calico" does not exist. Installing it now.
NAME: aws-calico
LAST DEPLOYED: Mon Sep 20 13:02:37 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
% kubectl get pods -A
NAMESPACE         NAME                               READY   STATUS    RESTARTS   AGE
kube-system       aws-node-8lfqd                     1/1     Running   0          2d19h
kube-system       aws-node-cmrk2                     1/1     Running   0          2d19h
kube-system       coredns-559b5db75d-j7jk2           1/1     Running   0          20d
kube-system       kube-proxy-l5dst                   1/1     Running   0          20d
kube-system       kube-proxy-wprlq                   1/1     Running   0          19d
tigera-operator   tigera-operator-856b4c65b4-jhp77   1/1     Running   0          7s
% kubectl get pods -A
NAMESPACE         NAME                                       READY   STATUS    RESTARTS   AGE
calico-system     calico-kube-controllers-5689468587-h5hll   1/1     Running   0          58s
calico-system     calico-node-9stfs                          1/1     Running   0          58s
calico-system     calico-node-hfs7t                          1/1     Running   0          58s
calico-system     calico-typha-df7f74df4-7p26n               1/1     Running   0          51s
calico-system     calico-typha-df7f74df4-ct4j4               1/1     Running   0          58s
kube-system       aws-node-8lfqd                             1/1     Running   0          2d19h
kube-system       aws-node-cmrk2                             1/1     Running   0          2d19h
kube-system       coredns-559b5db75d-j7jk2                   1/1     Running   0          20d
kube-system       kube-proxy-l5dst                           1/1     Running   0          20d
kube-system       kube-proxy-wprlq                           1/1     Running   0          19d
tigera-operator   tigera-operator-856b4c65b4-jhp77           1/1     Running   0          66s
```

**Comment by NivStav-RecoLabs** [comment]
![image](https://user-images.githubusercontent.com/88609182/134969631-db282e0d-dd02-45e7-8944-e96c66cceb40.png)

Tried both directly with `helm upgrade --install --recreate-pods --force aws-calico --namespace kube-system eks/aws-calico` and using `helmfile` as part of our deploy flow - both finish without the tigera-operator.

Following the guide at https://docs.aws.amazon.com/eks/latest/userguide/calico.html installs the entire stack properly.

**Comment by jayanthvn** [comment]
@NivStav-RecoLabs can you please paste the o/p of `kubectl get crds`?

**Comment by NivStav-RecoLabs** [comment]
@jayanthvn 
![image](https://user-images.githubusercontent.com/88609182/135145979-859b460b-74d1-4446-8428-1ec0067aa1ea.png)

**Comment by haouc** [comment]
Hi @NivStav-RecoLabs, thanks for providing detailed info. Seems you are trying to install tigera operator from eks-charts? We haven't introduced tigera operator into eks-charts yet. The [change](https://github.com/aws/eks-charts/pull/625) is in process and under review by Calico team. Once the PR is approved and merged, we will also update charts folder name here to make them synced. We will also add the sync action into workflow.

If you want to try out for now, you can try to install the operator using this command
`helm upgrade --install --recreate-pods --force aws-calico --namespace kube-system charts/aws-calico` from amazon-vpc-cni-k8s repo charts/aws-calico .

**Comment by kspradheep** [comment]
I'm also experiencing the same issue. Also, unable to install the Calico CRDs:
kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds

error: evalsymlink failure on '/private/var/folders/l2/0x9z7mhj54s_2hx2c35ql14hc83n7w/T/kustomize-076783641/tree/master/stable/aws-calico/crds' : lstat /private/var/folders/l2/0x9z7mhj54s_2hx2c35ql14hc83n7w/T/kustomize-076783641/tree: no such file or directory

**Comment by haouc** [comment]
@NivStav-RecoLabs @sean-mcgimpsey 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html). You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
