### ISSUE TITLE
ServiceAccount should precede DaemonSet in yaml

### ISSUE THREAD

**Issue by rittneje** [aws/amazon-vpc-cni-k8s#1632]
Reopening #1491. It was claimed to be fixed by #1271, but this is not the case, as evidenced by the 1.9 yaml file.
https://github.com/aws/amazon-vpc-cni-k8s/blob/07284393715b6e3872b91a6eb94da803af4ab86e/config/v1.9/aws-k8s-cni.yaml#L242-L246

---

See https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml for example.

We are trying to have the VPC CNI assume a role via EKS's OIDC provider. To do so requires us to add an annotation to the ServiceAccount, which must be present when the CNI pods are being created so that EKS can properly issue the JWT and set the necessary environment variables. However, the ServiceAccount appears after the DaemonSet in the yaml, which leads to a race where the new DaemonSet pods might not necessarily get the environment variables set and therefore will not work as expected.

Please fix the yaml to put the ServiceAccount first so there less manual changes are required for this use case.

**Comment by jayanthvn** [comment]
Yes we couldn't take #1271 for 1.9 due to last minute changes needed for calico manifests. I will tag this for 1.10 release.
