### ISSUE TITLE
Prefix Assignment Mode works on some nodes and not others

### ISSUE THREAD

**Issue by calvinbui** [aws/amazon-vpc-cni-k8s#1634]
**What happened**:

I followed the instructions on the [AWS blog](https://aws.amazon.com/blogs/containers/amazon-vpc-cni-increases-pods-per-node-limits/) to increase the pods per node limits. 

1. cluster upgraded to 1.21 
2. vpc-cni EKS add-on to 1.9.1
3. `kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true`
4. `kubectl set env daemonset aws-node -n kube-system WARM_PREFIX_TARGET=1`
5. Refreshed all managed node groups instances

Since then, pods on certain nodes will fail to start with the error [(pod events attached):](https://github.com/aws/amazon-vpc-cni-k8s/files/7217892/pod-events.log)

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f05ef3b1752cb579dcee78be595d1fa26ab8231bd4dbcdeeaa0ac1038e2f8e11" network for pod "grafana-backups-27206700-24gf8": networkPlugin cni failed to set up pod "grafana-backups-27206700-24gf8_grafana" network: add cmd: failed to assign an IP address to container
```

Checking the EC2 instance, it does not have an IPv4 prefix assigned to it's ENI

![ec2-network](https://user-images.githubusercontent.com/3604363/134514156-44bbae7c-9cb6-4ccc-9f88-802a350c7acc.png)

![eni](https://user-images.githubusercontent.com/3604363/134514161-b7edfd6f-a66a-47fe-8690-6c2ddea6e366.png)

The subnet it uses does have enough free IP addresses

![subnet](https://user-images.githubusercontent.com/3604363/134514223-235dc3c2-6372-4ecb-a6c0-236279a4f14b.png)

Here are the logs for the vpc-cni pod on the node: [aws-vpc-cni.log](https://github.com/aws/amazon-vpc-cni-k8s/files/7217896/aws-vpc-cni.log)

And the node's YAML: [node.txt](https://github.com/aws/amazon-vpc-cni-k8s/files/7217917/node.txt)

and the daemonset's YAML: [ds-aws-node.txt](https://github.com/aws/amazon-vpc-cni-k8s/files/7217921/ds-aws-node.txt)

This would happen here and there on some nodes and no others.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.2-eks-0389ca3
- CNI Version: v1.9.1-eksbuild.1
- OS (e.g: `cat /etc/os-release`): N/A (EKS Linux managed node)
- Kernel (e.g. `uname -a`): N/A (EKS Linux managed node)

**Comment by calvinbui** [comment]
the log line that stands out is

```
{"level":"error","ts":"2021-09-23T12:58:54.748Z","caller":"ipamd/ipamd.go:926","msg":"Failed to allocate a private IP/Prefix addresses on ENI eni-01beb28d78683821f: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: 7529a42c-9981-410c-9b18-c1069dece5b8"}
{"level":"error","ts":"2021-09-23T12:58:54.749Z","caller":"ipamd/ipamd.go:382","msg":"Unable to attach IPs/Prefixes for the ENI, subnet doesn't seem to have enough IPs/Prefixes. Consider using new subnet or carve a reserved range using create-subnet-cidr-reservation"}
```

but we only have 4 nodes across 3 x /24 subnets.

**Comment by thanhma** [comment]
My clusters also facing same issue since yesterday. Subnets still have thousands of IP available to allocate.

`ipamd.log` has these lines:
```
{"level":"error","ts":"2021-09-23T03:56:26.040Z","caller":"ipamd/ipamd.go:618","msg":"failed to allocate one IPv4 prefix on ENI eni-0083c******3c9d6, err: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: b1a0f94b-74b7-4950-bf4a-1a463e59c090: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: b1a0f94b-74b7-4950-bf4a-1a463e59c090"}
{"level":"error","ts":"2021-09-23T03:56:26.040Z","caller":"ipamd/ipamd.go:618","msg":"Unable to attach IPs/Prefixes for the ENI, subnet doesn't seem to have enough IPs/Prefixes. Consider using new subnet or carve a reserved range using create-subnet-cidr-reservation"}
```

**Comment by jayanthvn** [comment]
@calvinbui - As you have mentioned and also based on the logs EC2 is unable to carve out a /28 prefix - `ENI eni-01beb28d78683821f: InsufficientCidrBlocks` for subnet - `subnet-0e90b5936e934d6f3`

IPAMD will request VPC EC2 for a /28 prefix in ENIs subnet and if the subnet is fragmented then they won't be able to carve a /28 prefix leading to InsufficientCidrBlocks error. 

I would request you to open a support case with EC2 team to confirm on the fragmentation. As you have said if there are only 4 nodes across all the subnets then EC2 would be able to help debug this further as to why they are not able to carve out a /28 prefix.

Also on a side note, we are working with EC2 team to give more visibility to IPAMD and other users on the number of /28s that can be carved in a subnet.

**Comment by thanhma** [comment]
@jayanthvn So if the subnet IPs are fragmented, IPAMD will not be able to carve a /28 prefix, even if there're lots of IPs available, right?

In my case, the /19 subnet (8,187 IPs) already has 350 ENIs and and 80 of them has prefix (about 300 prefixes in total). Now the subnet still has 3,874 available IPs, but it's high chance of fragmentation so that the IPAM cannot carve new /28 prefix. 

It makes sense.

**Comment by jayanthvn** [comment]
Yeah thats right @thanhma

**Comment by thanhma** [comment]
Thank you @jayanthvn 

Didn't notice this !important block in the [guide](https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html)...

![image](https://user-images.githubusercontent.com/6383907/134548734-48504041-2ac8-47df-853e-a20c63d0f39f.png)

**Comment by jayanthvn** [comment]
Closing this issue for now. Please reach out to EC2 support to confirm on the fragmentation on the subnet.
