### ISSUE TITLE
InstanceMetadata awsApiErr elevated in cni 1.9

### ISSUE THREAD

**Issue by gregsterin** [aws/amazon-vpc-cni-k8s#1636]
**Environment**:
- Kubernetes version (use `kubectl version`): 1.19
- CNI Version: 1.9
- OS (e.g: `cat /etc/os-release`): 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
- Kernel (e.g. `uname -a`):
Linux ip-10-0-208-198.ec2.internal 5.4.110-54.189.amzn2.x86_64 #1 SMP Mon Apr 26 21:25:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Since upgrading to CNI version 1.9, we are seeing increased awsApiErr metrics:
awscni_aws_api_error_count{api="GetMetadata",error="EC2MetadataError"} 1290

It seems like this commit https://github.com/aws/amazon-vpc-cni-k8s/pull/1544/files pulled in this https://github.com/aws/aws-sdk-go/pull/3962 which is exposing 404s without retries. 

Interestingly, I would expect to see errors in the ipamd log about this, but grepping for error in these logs doesn't yield any results. Our aws-node pods also seem to be functioning properly. Is there any case where awscni_aws_api_error_count would be incremented despite being retried somewhere in ipamd?

Any help/support would be appreciated! Happy to provide any additional diagnostics that would be helpful!

**Comment by jayanthvn** [comment]
Hi @gregsterin 

One of the reasons we don't want to retry for 404 is because IPAMD with 1.9 queries for prefixes and secondary IPs from IMDS and if we are in secondary IP mode then get prefixes will return 404 and SDK keeps retrying causing aws-node to fail. 

Will check regarding the increased error count.

**Comment by gregsterin** [comment]
Did anything change in the CNI metrics collector? I know the prometheus metrics endpoint is exposing awsApiErr as a counter. I wonder if it started sending the growing counter value to CW when it wasnt before (we use the aws-cni-metrics-helper). Unfortunately we dont currently have prometheus scrape annotations on the aws-nodes right now, I'll also try to scraping into prometheus to see if that shows differently



![Screen Shot 2021-09-23 at 10 06 03 PM](https://user-images.githubusercontent.com/21046178/134621227-72a1f726-200c-47c0-b8ea-f48def5e5506.png)
