### ISSUE TITLE
Update test cases to support PR 1633 to fix issue #1626

### ISSUE THREAD

**Issue by nbbhall** [aws/amazon-vpc-cni-k8s#1638]
**What happened**:
Test cases need updating for changes committed via PR 1633 to fix issue #1626

**Environment**:
N/A

**Comment by jayanthvn** [comment]
Happy to take PRs :)

**Comment by dbgoytia** [comment]
Hey @nbbhall @jayanthvn I'd like to work on this, is this still open?

**Comment by jayanthvn** [comment]
@dbgoytia - Yes it is still open. Thanks for the help :)
