### ISSUE TITLE
make docker fails Lumberjack.v2 dependency

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-cni-k8s#1660]
**What happened**:
Running `make docker` fails with the error

```
Step 9/18 : RUN go mod download
 ---> Running in a190197d7983
go: gopkg.in/natefinch/lumberjack.v2@v2.0.0: reading gopkg.in/natefinch/lumberjack.v2/go.mod at revision v2.0.0: unknown revision v2.0.0
```
**Attach logs**

**What you expected to happen**:

* Docker image created successfully

**How to reproduce it (as minimally and precisely as possible)**:

* Clone repo
* `make docker`

**Anything else we need to know?**:

NA

**Environment**:

NA

- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Merged #1665
