### ISSUE TITLE
CNI does not support jumbo packets

### ISSUE THREAD

**Issue by oded-dd** [aws/amazon-vpc-cni-k8s#167]
When using amazon CNI it seems that the eni created for the POD does not support jumbo packets

```
eni24e1650925c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 3a:76:a2:dc:c0:88 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

While the node itself does supports
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 06:db:1a:40:a5:1c brd ff:ff:ff:ff:ff:ff
```

**Comment by oded-dd** [comment]
Any news about it? It's quite critical for us

**Comment by hmizuma** [comment]
Primary interface is configured by DHCP for jumbo frames. Secondary ENIs are not handled by DHCP so changes needed to configure for jumbo frames after creation.

**Comment by yuriipolishchuk-finsight** [comment]
@hmizuma moreover MTU is hardcoded here: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/plugins/routed-eni/driver/driver.go#L41

**Comment by simplytunde** [comment]
is their a  reason why jumbo packet is not configured for the secondary interfaces?
