### ISSUE TITLE
Add ARM based nodes for e2e and UT tests

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#1689]
**What would you like to be added**:
ARM based work nodes and runners

**Why is this needed**:
To test both AMD and ARM based images

**Comment by vikasmb** [comment]
Changes have been completed and merged.
Multi-arch integ test sample execution is in https://github.com/aws/amazon-vpc-cni-k8s/runs/5056823481?check_suite_focus=true
