### ISSUE TITLE
Attach interface via host-device with Multus

### ISSUE THREAD

**Issue by renanqts** [aws/amazon-vpc-cni-k8s#1694]
**What happened**:

I'm using Multus to attach another interface in a pod with 

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-conf-1
spec:
  config: '{
      "cniVersion": "0.3.1", 
      "type": "host-device", # this is used because I need dpdk driver
      "pciBusID": "0000:00:07.0"
    }'
```

It creates the `net1` without the VPC IP in the state down

```
6: net1: <BROADCAST,MULTICAST> mtu 9001 qdisc noop state DOWN group default qlen 1000
    link/ether 06:c1:9a:ad:a0:fd brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 128 maxmtu 9216 numtxqueues 2 numrxqueues 2 gso_max_size 65536 gso_max_segs 65535 
    alias eth2
```

Related to that, I have the following questions:

- How can I achieve this interface configure with VPC IP, and of course, in the upstate?
- With the configuration before, I had to add the interface into the node. Is there a way to create this interface via aws-cni?

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.21.4
- CNI Version
v1.9.1
- OS (e.g: `cat /etc/os-release`):
Amazon Linux 2
- Kernel (e.g. `uname -a`):
5.4.149-73.259.amzn2.x86_64

**Comment by renanqts** [comment]
@cgchinmay this I did. Currently, I'm attaching the interface to the node.
The question is how to set up one IP of the VPC in this interface that is created dynamically (DHCP).

As mentioned before, it is created there but the status is DOWN and there is no IP on that.
```
6: net1: <BROADCAST,MULTICAST> mtu 9001 qdisc noop state DOWN group default qlen 1000
    link/ether 06:c1:9a:ad:a0:fd brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 128 maxmtu 9216 numtxqueues 2 numrxqueues 2 gso_max_size 65536 gso_max_segs 65535 
    alias eth2

```

I already tried something like
```
"cniVersion": "0.3.1",
      "type": "host-device",
      "pciBusID": "0000:00:07.0",
      "ipam": {
        "type": "static",
        "addresses": [{
          "address": "192.168.1.0/24"
        }]
      }
```

But I'm not sure if I'm on the correct path since IPAM probably doesn't work with `pciBusID`.

**Comment by renanqts** [comment]
Hey @cgchinmay. I didn't try yet

**Comment by renanqts** [comment]
@cgchinmay I tried here.
I was faced with the error below

> dpdk           EAL:  0000:00:07.0 not managed by VFIO driver, skipping

**Comment by renanqts** [comment]
I had to mount the /dev into the container too, it solved the issue mentioned before.
@cgchinmay thanks for you help

**Comment by kuzaxak** [comment]
@renanqts could you post the whole config?

**Comment by kuzaxak** [comment]
@cgchinmay hey, have you done documentation for `host-device` mode?

**Comment by cgchinmay** [comment]
Hi @kuzaxak ita been quite a while and my information would be outdated. Tagging @jayanthvn who might be able to help
