### ISSUE TITLE
networkPlugin cni failed to set up pod "<pod name>" network: add cmd: failed to assign an IP address to container.

### ISSUE THREAD

**Issue by NagarajBM** [aws/amazon-vpc-cni-k8s#1709]
Hey,

issue still happening on aws eks.

cluster ARN = arn:aws:eks:us-east-1:531074996011:cluster/Cuttle

kubernetes version = 1.21
Platform version = eks.2
coredns version = v1.8.4-eksbuild.1
kube-proxy version = v1.21.2-eksbuild.2
vpc-cni version = v1.9.1-eksbuild.1

I have an AWS EKS cluster and while deploying pods I'm getting this error. "failed to assign an IP address to container"

My Current container setup:-

A cluster with single node group.
The node group with 2 nodes and "c5.2xlarge" instance type.
The node group is launched in a subnet which is not used for any other resources and has an CIDR of "10.0.1.0/24"
Error:
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "0707507c6ea3d0a38b1222ebc9acfb22bf9fc8ac5f5fa73ebd272fb107324f60" network for pod "automation-archival-hub-integration-service-6dfc4b4999-v94nq": networkPlugin cni failed to set up pod "automation-archival-hub-integration-service-6dfc4b4999-v94nq_cuttle-automation" network: add cmd: failed to assign an IP address to container.

Extra details:-

The "c5.2x large" can have 58 pods running in it. since only 4 network interface can be attached to the above instance type.
Our cluster has more than 75 pods.
When the 2nd node is launched only 2 network interfaces are created by the cluster and are attached to the node, and the network interface is allocated with 13 secondary IP.

The cni log:- 
[eks_i-00f0fd06e616a9386_2021-10-27_0637-UTC_0.6.2.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/7427857/eks_i-00f0fd06e616a9386_2021-10-27_0637-UTC_0.6.2.tar.gz)

Thanks,
Nagaraj

**Comment by jayanthvn** [comment]
@NagarajBM - Can you please share the logs from the correct instance?

**Comment by jayanthvn** [comment]
@NagarajBM - Can you please share the correct log file?
