### ISSUE TITLE
Support for c6i instances

### ISSUE THREAD

**Issue by lukeprentice202** [aws/amazon-vpc-cni-k8s#1716]
**What would you like to be added**: Support for newly announced instance type c6i https://aws.amazon.com/blogs/aws/new-amazon-ec2-c6i-instances-powered-by-the-latest-generation-intel-xeon-scalable-processors/

**Why is this needed**: To allow the newer instance types to be used in clusters using the vpc cni

**Comment by cgchinmay** [comment]
Hi @lukeprentice202 are using custom AMI or if EKS AMI then which version ?

**Comment by lukeprentice202** [comment]
Hey @cgchinmay, am using the EKS AMI version amazon-eks-node-1.18-v20211013 (ami-0c1d7ae34efa8647b)

**Comment by cgchinmay** [comment]
For now, to be able to launch the c6i instances, you will have to use a launch template for creating the nodegroup with following UserData script. This is how you can use c6i.large. After this cni should work without any update. 
Let us know if you see any errors
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

--==MYBOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"

#!/bin/bash 
set -ex 
echo "c6i.large 110" >> /etc/eks/eni-max-pods.txt

--==MYBOUNDARY==--
```

**Comment by lukeprentice202** [comment]
Thanks @cgchinmay that worked :) I assume this is just a temp workaround till the list is generated with all the available instances?

**Comment by cgchinmay** [comment]
> Thanks @cgchinmay that worked :) I assume this is just a temp workaround till the list is generated with all the available instances?

Yes, I do see the [list](https://github.com/awslabs/amazon-eks-ami/pull/796) has been updated, A new eks-ami will be released soon to have this information

**Comment by avivgold098** [comment]
@cgchinmay 
Hey! I'm running with `kops` using the official `Ubuntu` is it relevant also?
Started the instance with no issues on the vpc cni

**Comment by cgchinmay** [comment]
> @cgchinmay Hey! I'm running with `kops` using the official `Ubuntu` is it relevant also? Started the instance with no issues on the vpc cni
No, Its relevant only if you are using eks-ami

**Comment by cgchinmay** [comment]
Closing this issue, you can track the eks-ami release [here](https://github.com/awslabs/amazon-eks-ami)
