### ISSUE TITLE
When do pod IP addresses become available again?

### ISSUE THREAD

**Issue by LCaparelli** [aws/amazon-vpc-cni-k8s#1719]
**What happened**:

We have an EKS cluster using this CNI plugin. We run a few jobs, their pods are kept around after they're finished for posterior troubleshooting and record keeping. 

I noticed that even pods in a `Completed` state have IP addresses at the ouput of `kubectl get pod` and family, which should be fine, it's useful to know the pod's IP address at the time it ran during troubleshooting. However, I also noticed this IP address still seems to be allocated to the node's EC2 network interface as a secondary IP address.

Is this IP address actually available for new pods to use? Should I be concerned with running out of IP addresses if these completed pods are kept for too long?

I feel it should be available, since the pod is already finished and won't be doing any network communication, but since it's still allocated to the network interface I'm not sure if that's the case or if I'm missing some important point on why this is kept allocated.

Perhaps it's marked as available even though it's allocated to an interface? Like how marking blocks as deleted in disks/memory doesn't mean they're actually written to with zeros?

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by LCaparelli** [comment]
So, I just found a running pod using one of the completed pods IP address, it started 5 minutes after the `Completed` pod's container finished. So yeah, it becomes available shortly after, it seems.

Closing, hopefully this will at least be of use to others with the same question. :-)

**Comment by jayanthvn** [comment]
Yeah thats right, the completed pod IP will be released and reused. The IP might still be attached to the ENIs because of the WARM_IP/ENI targets configuration.
