### ISSUE TITLE
Prefix delegation with Calico

### ISSUE THREAD

**Issue by Yitaek** [aws/amazon-vpc-cni-k8s#1722]
Does `ENABLE_PREFIX_DELEGATION` work with Calico installed on EKS?

**What happened**:

Setting `ENABLE_PREFIX_DELEGATION: true` causes aws-node to crash. This feature works on cluster without Calico installed 

**Environment**:
- Kubernetes version: `v1.19.13-eks-8df270` 
- CNI Version: `amazon-k8s-cni:v1.9.0` 
- OS (e.g: `cat /etc/os-release`): bottlerocket 

`aws-calico-0.3.5` chart installed from https://github.com/aws/eks-charts/tree/master/stable/aws-calico, waiting for this bug (https://github.com/aws/eks-charts/issues/537, https://github.com/aws/eks-charts/issues/565) to be fixed before updating to latest

**Comment by jayanthvn** [comment]
Prefix delegation will work with Calico. Can you please provide the steps on how you enabling the feature and installing Calico?

Can you also share the o/p from `/var/log/aws-routed-eni/ipamd.log` once you set `ENABLE_PREFIX_DELEGATION: true`

**Comment by Yitaek** [comment]
Yup, so Calico was installed as helm-chart via https://github.com/aws/eks-charts/tree/master/stable/aws-calico (version 0.3.5) with all the default values. 

And followed this guide to enable prefix delegation: https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html

Once I set `ENABLE_PREFIX_DELEGATION: true` then new aws-node pod fails readiness probe:

```
Readiness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 1s exceeded: context deadline exceeded

Readiness probe failed: {"level":"info","ts":"2021-11-02T19:43:01.805Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"timeout: failed to connect service \":50051\" within 1s"}
```

**Comment by jayanthvn** [comment]
Can you please either ssh to the instance or exec into aws-node pod and provide ipamd logs? It will be under var/log/aws-routed-eni.

**Comment by Yitaek** [comment]
Yeah when I exec-ed into the pod, there was nothing under `/var/log/aws-routed-eni` . I assumed that it didn't even get to that point of starting up. I'll try again and paste what I see

**Comment by jayanthvn** [comment]
When you exec to the pod, you can check under /host/var/log/aws-routed-eni

**Comment by Yitaek** [comment]
oh i see, i get 

```
{"level":"warn","ts":"2021-11-02T20:44:36.942Z","caller":"ipamd/ipamd.go:799","msg":"failed to allocate all available IPv4 Prefixes on ENI eni-07a4d509389292143, err: allocate IP/Prefix address: failed to allocate a private IP/Prefix address: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: 52b26e60-d958-4290-9cec-9774145860d8"}
{"level":"info","ts":"2021-11-02T20:44:36.942Z","caller":"ipamd/ipamd.go:857","msg":"Trying to allocate 1 IP addresses on ENI eni-07a4d509389292143"}
{"level":"debug","ts":"2021-11-02T20:44:36.942Z","caller":"ipamd/ipamd.go:857","msg":"PD enabled - true"}
{"level":"error","ts":"2021-11-02T20:44:37.296Z","caller":"ipamd/ipamd.go:857","msg":"Failed to allocate a private IP/Prefix addresses on ENI eni-07a4d509389292143: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: a2bb0daa-3af2-4c9c-b2fe-bcfbb22fd4c4"}
{"level":"error","ts":"2021-11-02T20:44:37.296Z","caller":"aws-k8s-agent/main.go:28","msg":"Initialization failure: failed to allocate one IPv4 prefix on ENI eni-07a4d509389292143, err: allocate IP/Prefix address: failed to allocate a private IP/Prefix address: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: a2bb0daa-3af2-4c9c-b2fe-bcfbb22fd4c4: allocate IP/Prefix address: failed to allocate a private IP/Prefix address: InsufficientCidrBlocks: The specified subnet does not have enough free cidr blocks to satisfy the request.\n\tstatus code: 400, request id: a2bb0daa-3af2-4c9c-b2fe-bcfbb22fd4c4"}
```

**Comment by Yitaek** [comment]
seems like issue with my subnet / cidr setup. thanks for all the help!

**Comment by jayanthvn** [comment]
No problem, glad to RC the issue :) 

You can also ref to this : https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
