### ISSUE TITLE
Doc updates for CLI auth for ECR

### ISSUE THREAD

**Issue by danbeaulieu** [aws/amazon-vpc-cni-k8s#173]
I am running a non-EKS cluster and ran in to an issue that I didn't find documented. In order to pull the CNI image the docker client needs to be logged in. This is done via the aws cli.

```
eval $(aws ecr get-login --region us-west-2 --registry-ids 602401143452 --no-include-email)
```

The region in the login command needs to match the region in the registry name for the CNI docker image.

**Comment by amitsaha** [comment]
Hi @danbeaulieu I am currently running a non-EKS cluster via kops + terraform. I didn't need to login explicitly. Wondering what's different in your case?

**Comment by rafaelmagu** [comment]
@amitsaha are you running in a region other than us-west-2? I'm running it in ap-southeast-2 and ran into the same issue.

**Comment by jaypipes** [comment]
Hey @danbeaulieu sorry for the delay in responding to this issue. Are you saying that the documentation bug here is that the docs don't mention the need to specify the `--region` with the `aws ecr get-login` call? Or are you saying that the documentation bug is something else?

**Comment by jaypipes** [comment]
We are standardizing on the Helm chart for deployment/configuration of the CNI. We do have the `image.region` configuration option documented (https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni#configuration) in the Helm chart. Closing this issue out.

**Comment by mogren** [comment]
For reference, there is also https://github.com/awslabs/amazon-ecr-credential-helper 
> The Amazon ECR Docker Credential Helper is a credential helper for the Docker daemon that makes it easier to use Amazon Elastic Container Registry.
