### ISSUE TITLE
Container does not use eni interface

### ISSUE THREAD

**Issue by ruster-cn** [aws/amazon-vpc-cni-k8s#1734]
Using the k8s cluster built by EC2 and the AWS CNI plug-in, we found that the container did not use the Eni network interface as eth0.I checked many places and found no problem. What are the possible reasons for this problem.

![image](https://user-images.githubusercontent.com/58843667/140930210-7a2d2590-47b2-4ad3-bef9-dac99dcc7657.png)
![image](https://user-images.githubusercontent.com/58843667/140930303-3f264ff0-1116-40be-9a2d-0ba7061b35b7.png)

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
- CNI Version
v1.9.3
- OS (e.g: `cat /etc/os-release`):
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
- Kernel (e.g. `uname -a`):
4.14.232-177.418.amzn2.x86_64 #1 SMP Tue Jun 15 20:57:50 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jayanthvn** [comment]
@ruster-cn - The eth0 with Mac ending 71:18 is pod side Veth and the eni o/p on the host ending a4:21 is host side Veth.

**Comment by ruster-cn** [comment]
> @ruster-cn - The eth0 with Mac ending 71:18 is pod side Veth and the eni o/p on the host ending a4:21 is host side Veth.

But I think the eth0 of pod on eks is the same as the MAC address of ens.
![image](https://user-images.githubusercontent.com/58843667/141037434-0dc1c2e8-4b30-4298-8cb5-ffacfaebf3f6.png)
![image](https://user-images.githubusercontent.com/58843667/141037462-2941f1a9-cbf6-4ae2-8aca-153947d3b0ea.png)

**Comment by achevuru** [comment]
@ruster-cn Can you elaborate on your question? Are you saying the host side eni(veth) device/interfacde and Pod's eth0 have the same MAC address?

**Comment by achevuru** [comment]
@ruster-cn Any update?

**Comment by jayanthvn** [comment]
@ruster-cn - Closing this issue for now. Please feel free to open if you have further questions.
