### ISSUE TITLE
Support for G5 Instance Types

### ISSUE THREAD

**Issue by vinayan3** [aws/amazon-vpc-cni-k8s#1748]
**What would you like to be added**:
Support for G5 instance types. https://aws.amazon.com/blogs/aws/new-ec2-instances-g5-with-nvidia-a10g-tensor-core-gpus/

**Why is this needed**:
Currently the EKS bootstrap script has to add the instance to the max pods file like
```
echo "g5.4xlarge 20" >> /etc/eks/eni-max-pods.txt
```

*Note*: The ENI value was simply copied from the g4 for simplicity and likely could be wrong because this is a newer instance type.

**Comment by cgchinmay** [comment]
The solution you have pointed out is to have Node in ready state. Could also create an issue on this repo : https://github.com/awslabs/amazon-eks-ami/issues . The eks-ami needs to have this information built in. 
Similar to : #1716

**Comment by cgchinmay** [comment]
Closing this issue, as it can be tracked as part of [eks-ami release](https://github.com/awslabs/amazon-eks-ami/issues). vpc-cni doesn't block the usage of this instance
