### ISSUE TITLE
calico-typha not scheduled on each node in EKS cluster

### ISSUE THREAD

**Issue by dvohra** [aws/amazon-vpc-cni-k8s#175]
The `calico-typha` should get scheduled on all nodes according to:

> CNI Plugin Daemons Scheduled to All Nodes
> Previously, node taints like NoExecute and NoSchedule would prevent daemon pods, such as aws-node, calico-node, and calico-typha, from being scheduled to each node in the cluster. Now, these daemons are always scheduled to all nodes.
https://aws.amazon.com/blogs/opensource/vpc-cni-plugin-v1-1-available/

But in a three node EKS  cluster with calico manifest applied  `calico-typha` is scheduled on only one node.
```
kubectl get pods --namespace=kube-system
NAME                                                  READY     STATUS    RESTAR
TS   AGE
aws-node-k4z7t                                        1/1       Running   1
     2m
aws-node-n7xcb                                        1/1       Running   1
     2m
aws-node-w8z9q                                        1/1       Running   0
     2m
calico-node-9q8l9                                     1/1       Running   0
     37s
calico-node-cw2nh                                     1/1       Running   0
     37s
calico-node-jfjkb                                     1/1       Running   0
     37s
calico-typha-75667d89cb-nqrwm                         1/1       Running   0
     37s
calico-typha-horizontal-autoscaler-78f747b679-74mqn   1/1       Running   0
     35s
kube-dns-64b69465b4-bgjfs                             3/3       Running   0
     40m
kube-proxy-7mdcd                                      1/1       Running   0
     2m
kube-proxy-rpb4x                                      1/1       Running   0
     2m
kube-proxy-wpx8w                                      1/1       Running   0
     2m

```

**Comment by someword** [comment]
@dvohra i think the wording may be misleading.  If you look at https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.1/calico.yaml#L348 and https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.1/calico.yaml#L472 you can see that calico-typha is a deployment which defaults to a single replica but has a autoscaler watching it that will scale it up as needed.   So initially in an idle system just seeing 1 replica is the desired state.   HTH

**Comment by mogren** [comment]
Wrong wording in the blog post, resolving.

**Comment by dvohra** [comment]
Thanks mogren.
