### ISSUE TITLE
aws-load-balancer-controller crashing on RHEL8 worker node. 

### ISSUE THREAD

**Issue by deepshock-211120** [aws/amazon-vpc-cni-k8s#1767]
**Environment**:
- AWS Region: ap-southeast-1
- Instance Type(s): m5.large
- EKS Platform version: "eks.3"
- Kubernetes version : "1.20"
- AMI Version: "1.20"
- Kernel (e.g. `uname -a`):4.18.0-348.2.1.el8_5.x86_64

Hello all, 

I have followed the 
[amazon-eks-custom-amis](https://github.com/aws-samples/amazon-eks-custom-amis)  to create CIS-hardened (OS level) custom ami for both AL2 and RHEL8. 

Was able to create node group and tested joining to both 1.20 and 1.18 clusters successfully for AL2 custom AMI. 

Was able to create another node group and tested joining to both 1.20 and 1.18 clusters successfully for RHEL8 custom AMI (with the tweak to add "sudo modprobe iptables" into the bootstrap procedure. 

I wish to have EKS cluster with RHEL8-only worker nodes. 

However, I am facing an issue to stablize aws-load-balancer-controller deployment on RHEL8 worker nodes. The error got is 

```# {"level":"info","ts":***********.7889001,"msg":"version","GitVersion":"v2.3.0","GitCommit":"83a8c40061304b67fa19d344e159f43c0b3b7e64","BuildDate":"2021-10-20T21:09:04+0000"}
# {"level":"error","ts":":***********..7923973,"logger":"controller-runtime.manager","msg":"Failed to get API Group-Resources","error":"Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"}
# {"level":"error","ts":":***********..7924356,"logger":"setup","msg":"unable to start manager","error":"Get \"https://10.100.0.1:443/api?timeout=32s\": dial tcp 10.100.0.1:443: i/o timeout"}
```

When I pin the deployment to AL2 nodes. It works perfectly. The security group, node role IAM policy for RHEL8 nodes and AL2 nodes are exactly the same. 

Appreciate your help here.

**Comment by jayanthvn** [comment]
@deepshock-211120 - This is the correct repo - https://github.com/kubernetes-sigs/aws-load-balancer-controller for AWS LB controller.
