### ISSUE TITLE
CNI Prefix isn't working in region China

### ISSUE THREAD

**Issue by njuettner** [aws/amazon-vpc-cni-k8s#1769]
**What happened**:

When trying to enable CNI prefix (IPv4 only) in `cn-north-1`, AWS CNI won't work as expected.

**Attach logs**

```
{"level":"error","ts":"2021-11-26T11:35:49.086Z","caller":"ipamd/ipamd.go:937","msg":"Failed to allocate a private IP/Prefix addresses on ENI eni-06e77e5a1840bb8d5: UnknownParameter: The parameter ipv4PrefixCount is not recognized\n\tstatus code: 400, request id: b92340a5-3422-4135-a6b5-f449838f5730"}
{"level":"error","ts":"2021-11-26T11:35:49.086Z","caller":"ipamd/ipamd.go:629","msg":"failed to allocate one IPv4 prefix on ENI eni-06e77e5a1840bb8d5, err: UnknownParameter: The parameter ipv4PrefixCount is not recognized\n\tstatus code: 400, request id: b92340a5-3422-4135-a6b5-f449838f5730: UnknownParameter: The parameter ipv4PrefixCount is not recognized\n\tstatus code: 400, request id: b92340a5-3422-4135-a6b5-f449838f5730"}
```

**What you expected to happen**:

Enable IPv4 Prefix should work.

**How to reproduce it (as minimally and precisely as possible)**:

Create a test cluster in region China and set envs to:

```
- name: ENABLE_PREFIX_DELEGATION
  value: "true"
- name: "WARM_PREFIX_TARGET"
  value: "1"
```

**Anything else we need to know?**:

I tried it on `m5.xlarge` instances.

**Environment**:
- Kubernetes 1.21.7
- CNI Version 1.9.3
- flatcar 2905.2.6
- Kernel 5.10.75

**Comment by jayanthvn** [comment]
@njuettner IPv4 prefix delegation is not supported in China region yet. Ref - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.0

**Comment by njuettner** [comment]
@jayanthvn Oh sorry I missed that, thanks for pointing me to that 🤗. Do you have some estimation when this becomes available in China?

**Comment by jayanthvn** [comment]
No problem :) I have reached out VPC team and will let you know once I get an update.

**Comment by jayanthvn** [comment]
@njuettner - Few folks are still on PTO so will get back to you after the long weekend.

**Comment by jayanthvn** [comment]
@njuettner - Currently team is working on it and tentatively it is Q2 2022. If something changes on our end we will update you. Please feel free to reach out to us.
