### ISSUE TITLE
Too many IPv4 addresses assigned to my instances

### ISSUE THREAD

**Issue by jnicholls** [aws/amazon-vpc-cni-k8s#177]
I received a notice from Amazon that my instances are using too many IPv4 addresses, which are managed by this CNI adapter. I was running 0.1.4 at the time (upgraded to 1.1.0 last night). I checked and saw that my ENI interfaces each had the maximum number of IP addresses allowed for the associated instance type as secondary IPs; they also had a primary IP, which altogether put the total number of IPs at 1 over the max. e.g. m5.large can have 3 ENIs with 10 IPs each; my instance has 2 ENIs but each have 11 IPs...1 primary and 10 secondary.

Is there a bug in the adapter that isn’t counting the primary IP when it should be? Is this not an issue in 1.1.0? Or, is Amazon just straight wrong about its claim that I am using too many IPs?

Thanks in advance.

**Comment by washingtoneg** [comment]
This may be related to issue https://github.com/aws/amazon-vpc-cni-k8s/issues/18 and it's proposed fix https://github.com/aws/amazon-vpc-cni-k8s/pull/31

**Comment by washingtoneg** [comment]
It looks like this issue got fixed in https://github.com/aws/amazon-vpc-cni-k8s/pull/60. The `GetENIipLimit` function was added  returns the number IP address can be allocated on a ENI. There is logic in the funtion to return the Instance's Available IP (for a given instance type) minus 1 (leaving room for the primary IP).

This issue should be fixed in > v1.0.0

**Comment by jnicholls** [comment]
@washingtoneg Awesome, thanks! Yes I see the compensation for the primary IP, perfect. I'm going to see if I have any secondary IPs that aren't being used by a POD and will remove one from each ENI adapter. At least I presume that won't break anything with k8s :) I don't want Amazon to be mad at me because their APIs didn't prevent over-allocation, haha.
