### ISSUE TITLE
Published docker images are vunerable to ALAS-2021-1552

### ISSUE THREAD

**Issue by dylanlingelbach** [aws/amazon-vpc-cni-k8s#1774]
**What happened**:

Published docker images are vulnerable to ALAS-2021-1552
**Attach logs**

**What you expected to happen**:
New docker images published with an updated base image

**How to reproduce it (as minimally and precisely as possible)**:
Check version of NSS in published docker image

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version: All
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`):

**Comment by cgchinmay** [comment]
Hi @dylanlingelbach which version of cni image did you find this vulnerability ?

**Comment by dylanlingelbach** [comment]
@cgchinmay `602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.9.3`

It looks like that image is based on `amazonlinux:2.0.20211001.0`

**Comment by cgchinmay** [comment]
@dylanlingelbach the linked CVE: https://alas.aws.amazon.com/ALAS-2021-1552.html recommends running yum update on nss package. We do yum [update](https://github.com/aws/amazon-vpc-cni-k8s/blob/2af69b263885e94e4eeae309b07807b3714c0381/scripts/dockerfiles/Dockerfile.release#L23) and I could not find vulnerability with the latest cni release. Will try to run scan against v1.9.3 and confirm this.

**Comment by dylanlingelbach** [comment]
@cgchinmay yes, I expect `yum update` would fix it. Are you suggesting we'd need to run `yum update` each time we start this container?

I think `amazonlinux:2.0.20211201.0` has the security updates applied in the image itself, so no `yum update` is needed

**Comment by cgchinmay** [comment]
@dylanlingelbach When we build the image, we already do it in the Dockerfile, so nothing needed from your side. Our current release  v1.10.x doesn't show this vulnerability as it would have already got addressed.

**Comment by dylanlingelbach** [comment]
@cgchinmay 

> When we build the image, we already do it in the Dockerfile, so nothing needed from your side

Yes, but if a vulnerability is patched after you build the Docker image the patch won't be present unless I am missing something?

> Our current release v1.10.x doesn't show this vulnerability as it would have already got addressed.

So your recommendation is to upgrade to v1.10.x?

**Comment by cgchinmay** [comment]
Yes, use the latest image v1.10.x

**Comment by dylanlingelbach** [comment]
Closing as this is fixed in the latest version of the image

**Comment by cgchinmay** [comment]
@dylanlingelbach You can use following image tag: v1.10.2-rc1 which has this fix. This is a private image release which we made recently to address the following issues. 
https://github.com/aws/amazon-vpc-cni-k8s/issues/1644
https://github.com/aws/amazon-vpc-cni-k8s/issues/1644

We are working on making an official public release and that will fix this NSS vulnerability. So keeping this issue open until we make a public release.

**Comment by jayanthvn** [comment]
v1.10.2 image published.
