### ISSUE TITLE
ipamd loop creating and freeing ENI when WARM_ENI_TARGET=0 and no IP is being used on the node

### ISSUE THREAD

**Issue by dtnyn** [aws/amazon-vpc-cni-k8s#1775]
**What happened**:
When we set `WARM_ENI_TARGET=0 ` for our CNI configuration, we notice that when there is no pod on the node. The ipamd will detect that it met its requirement to request for a new ENI

```
{"level":"debug","ts":"2021-12-02T00:01:40.937Z","caller":"ipamd/ipamd.go:563","msg":"IP pool is too low: available (0) < ENI target (0) * addrsPerENI (14)"}
{"level":"debug","ts":"2021-12-02T00:01:40.937Z","caller":"ipamd/ipamd.go:564","msg":"Starting to increase pool size"}
```

However it will then delete this ENI as it is not in used due to no pod is consuming IP.

This created an issue where the ipamd will continuously create new ENI but then procceed to delete it afterwards

```
➜ cat ipamd.log | ag "(Created a new ENI)|(Successfully freed ENI)" | head -n 10
{"level":"info","ts":"2021-12-02T00:00:11.209Z","caller":"awsutils/awsutils.go:667","msg":"Created a new ENI: eni-05a14ca3e85f7bab2"}
{"level":"info","ts":"2021-12-02T00:01:23.778Z","caller":"awsutils/awsutils.go:850","msg":"Successfully freed ENI: eni-05a14ca3e85f7bab2"}
{"level":"info","ts":"2021-12-02T00:01:41.339Z","caller":"awsutils/awsutils.go:667","msg":"Created a new ENI: eni-0cd69037ff4b1992d"}
{"level":"info","ts":"2021-12-02T00:02:53.433Z","caller":"awsutils/awsutils.go:850","msg":"Successfully freed ENI: eni-0cd69037ff4b1992d"}
{"level":"info","ts":"2021-12-02T00:02:58.844Z","caller":"awsutils/awsutils.go:667","msg":"Created a new ENI: eni-0a9f1da35fb408dbc"}
{"level":"info","ts":"2021-12-02T00:04:14.765Z","caller":"awsutils/awsutils.go:850","msg":"Successfully freed ENI: eni-0a9f1da35fb408dbc"}
{"level":"info","ts":"2021-12-02T00:04:20.190Z","caller":"awsutils/awsutils.go:667","msg":"Created a new ENI: eni-05257e8d3edf05e46"}
{"level":"info","ts":"2021-12-02T00:05:33.547Z","caller":"awsutils/awsutils.go:850","msg":"Successfully freed ENI: eni-05257e8d3edf05e46"}
{"level":"info","ts":"2021-12-02T00:05:38.932Z","caller":"awsutils/awsutils.go:667","msg":"Created a new ENI: eni-029ee0a76c5a556f7"}
{"level":"info","ts":"2021-12-02T00:06:49.035Z","caller":"awsutils/awsutils.go:850","msg":"Successfully freed ENI: eni-029ee0a76c5a556f7"}
```

We're suspecting it is due to the conditional set here https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.9.0/pkg/ipamd/ipamd.go#L1840. Since after the ipamd free the unused ENI, it will always pass the second conditional and starts this creation/deletion loop again

```go
poolTooLow := available < totalIPs*warmTarget || (warmTarget == 0 && available == 0)
if poolTooLow {
        logPoolStats(total, used, c.maxIPsPerENI, c.enableIpv4PrefixDelegation)
        log.Debugf("IP pool is too low: available (%d) < ENI target (%d) * addrsPerENI (%d)", available, warmTarget, totalIPs)
}
```

As the allocated ENI will not have any pod using IP from it, it will always be freed because it will not be catched by the guards in https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.9.0/pkg/ipamd/datastore/data_store.go#L774 (we expect this behaviour) 
```go
if eni.hasPods() {
	ds.log.Debugf("ENI %s cannot be deleted because it has pods assigned", eni.ID)
	continue
}
```

**What you expected to happen**:

We're expecting that ipamd would not provision any ENI at all as no IP is being requested by any pod and ENI pre-warming is disabled.

Furthermore, the log line 
```go
log.Debugf("IP pool is too low: available (%d) < ENI target (%d) * addrsPerENI (%d)", available, warmTarget, totalIPs)
```

Should be fixed to avoid confusing situation such as `available < totalIPs*warmTarget` being reported to having passed the `poolTooLow` check despite actually passing the `(warmTarget == 0 && available == 0)` check instead as seen in:
```go
{"level":"debug","ts":"2021-12-02T00:01:40.937Z","caller":"ipamd/ipamd.go:563","msg":"IP pool is too low: available (0) < ENI target (0) * addrsPerENI (14)"}
``` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.20.11`
- CNI Version: `v1.9.0`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.3 LTS (Focal Fossa)`
- Kernel (e.g. `uname -a`): `Linux xxxxxxxx 5.11.0-1019-aws #20~20.04.1-Ubuntu SMP Tue Sep 21 10:40:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jayanthvn** [comment]
@dtnyn - this is a known issue - https://github.com/aws/amazon-vpc-cni-k8s/issues/1451 and @haouc is working on it. This issue can be reproduced with and without custom networking.

**Comment by jayanthvn** [comment]
We will provide updates on #1451. Closing this issue.
