### ISSUE TITLE
Which chart should I use to install the vpc cni? Docs missing

### ISSUE THREAD

**Issue by markussiebert** [aws/amazon-vpc-cni-k8s#1786]
I use helm charts for managing the vpc cni but no I am confused what chart to use:

We have helm charts inside this repo and here: https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni

It would be nice to know which chart is the prefered one to use with the cni and where it is published.

Wouldn't it be good to deprecate one and link to the other?

**Comment by Shreya027** [comment]
All code changes are made in amazon-vpc-cni upstream repository, we sync the changes to the eks-charts repository during release.

**Comment by cgchinmay** [comment]
@markussiebert 
We usually sync the charts in these 2 repos. It seems there could have been a miss in syncing vpc-cni [Chart](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni) with the [repo](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni that you pointed out.  Let me check on that and fix it. 

For you information, this is the latest helm [chart:](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni)  as it uses the latest cni image v1.10.1

**Comment by cgchinmay** [comment]
You can find the updated chart in the helm now. Closing this
