### ISSUE TITLE
NodeAutoScalingGroup starts with max size

### ISSUE THREAD

**Issue by dvohra** [aws/amazon-vpc-cni-k8s#179]
`NodeAutoScalingGroup` is designed to scale  if needed and starting max size setting of worker nodes to start with is creating redundant nodes. Example:

`NodeAutoScalingGroupMinSize` 1
`NodeAutoScalingGroupMaxSize` 10

Nodes started 10
User Pods running 0

How does the `NodeAutoScalingGroup` provide scaling if it always runs the max # of nodes.

**Comment by max-rocket-internet** [comment]
Scaling of k8s nodes up and down is done by the [cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler), not by the ASG itself.

**Comment by dvohra** [comment]
Thanks. And isn't the cluster autoscaler implemented in AWS Elastic Kubernetes Service? The Worker Node Group should start the minimum number of worker nodes and scale up as needed. Starting the max number of worker nodes even when none is used is provisioning unneeded EC2 instances.

**Comment by mogren** [comment]
Not a CNI issue

**Comment by dvohra** [comment]
Thanks mogren.
