### ISSUE TITLE
Init container emits non-error messages to stderr

### ISSUE THREAD

**Issue by skpy** [aws/amazon-vpc-cni-k8s#1801]
**What happened**:
The amazon-vpc-cni-init container invokes [set -x](https://github.com/aws/amazon-vpc-cni-k8s/blob/ec409b0cd124923dc4f369483b4416499ab7bc3b/scripts/init.sh#L3) in `init.sh` which emits output to stderr.  Our log collection and monitoring system (DataDog) sees these messages as errors (because they're coming from stderr, not stdout) and trips our alerting threshold for number of errors per unit of time whenever the init container runs.

I have implemented a log processor in DataDog to forcibly set all `amazon-vpc-cni-init` logs as INFO, which avoids the superfluous alerts at the expense of masking any real errors. I could also modify our existing alerts to exclude amazon-vpc-cni-init, then make a new alert specifically for amazon-vpc-cni-init, if necessary.

It might also be worth adding `-s` to the curl commands ([1](https://github.com/aws/amazon-vpc-cni-k8s/blob/ec409b0cd124923dc4f369483b4416499ab7bc3b/scripts/init.sh#L7) and [2](https://github.com/aws/amazon-vpc-cni-k8s/blob/ec409b0cd124923dc4f369483b4416499ab7bc3b/scripts/init.sh#L15)) to suppress the status output from curl, which also emits to stderr.

**Environment**:
EKS 1.21

- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`
- CNI Version `v1.10.1-eksbuild.1`

**Comment by jaypipes** [comment]
@skpy What's up, Skippy? :)

**Comment by jaypipes** [comment]
I agree that it's generally poor Bash hygiene to have any non-error output be directed to `stderr`. We could either do `BASH_XTRACEFD=1` at the start of the init script or we could simply remove the use of `set -x`  entirely (as it's mostly a debug/troubleshooting need and not something that should be in production scripts). @jayanthvn what do you think?

**Comment by skpy** [comment]
I can trivially submit a PR to effect the removal of `-x` (and add `-Ss` to both curl calls, consistent with other curl invocations within this repo); but I don't have a good way to building, testing, and validating this yet.

**Comment by jaypipes** [comment]
> I can trivially submit a PR to effect the removal of `-x` (and add `-Ss` to both curl calls, consistent with other curl invocations within this repo); but I don't have a good way to building, testing, and validating this yet.

ack, totes. I'd be good with that. just checking with Jayanth if he's good with it too.

**Comment by cgchinmay** [comment]
@skpy Thanks for bringing this up. I will talk to @jayanthvn and can actively work on this from next week. Feel free to raise a PR, if you have anything in mind. I can take it from there.

**Comment by jayanthvn** [comment]
> I agree that it's generally poor Bash hygiene to have any non-error output be directed to `stderr`. We could either do `BASH_XTRACEFD=1` at the start of the init script or we could simply remove the use of `set -x`  entirely (as it's mostly a debug/troubleshooting need and not something that should be in production scripts). @jayanthvn what do you think?

I agree with you @jaypipes we can remove the set -x. We do have logs in stdout which shows if anything fails during init.

**Comment by skpy** [comment]
Thanks for merging my PR! Out of curiosity, when do you think this will land in a release?

**Comment by jayanthvn** [comment]
@skpy - I have milestoned the PR for next upcoming release of v1.11.0. It is planned for Jan/Feb but will provide you an estimated date by next week.

**Comment by orsenthil** [comment]
The PR https://github.com/aws/amazon-vpc-cni-k8s/pull/1802 is merged.
