### ISSUE TITLE
Syntax error in environment variables in code documentation

### ISSUE THREAD

**Issue by o6uoq** [aws/amazon-vpc-cni-k8s#1805]
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L66-L69

References to `WARM-IP-TARGET` should be `WARM_IP_TARGET`

**Comment by alternaivan** [comment]
Opened PR for this:
https://github.com/aws/amazon-vpc-cni-k8s/pull/1806

**Comment by Shreya027** [comment]
Closing issue as this is fixed in #1806.
