### ISSUE TITLE
TestIPAMContext_nodeIPPoolTooLow is flaky, and relies on the order of the output for assertion

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-cni-k8s#1821]
**What happened**:

Exercising this test https://github.com/orsenthil/amazon-vpc-cni-k8s/blob/8c1be691b618ac97914e297a59f68395f75faed8/pkg/ipamd/ipamd_test.go#L1323 multiple times can give different results.

**Attach logs**

**What you expected to happen**:

Deterministic output from TestIPAMContext_nodeIPPoolTooLow test run.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by vikasmb** [comment]
In my testing, I did not find `TestIPAMContext_nodeIPPoolTooLow` to be flaky. Refer to sample execution below.
```
while true; do go clean -testcache; /usr/local/go/bin/go test -timeout 30s -run ^TestIPAMContext_nodeIPPoolTooLow$ github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd; done
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.016s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
ok      github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd     0.015s
```

However, based on unit test execution logs, `TestIPAMContext_filterUnmanagedENIs_disableManageUntaggedMode` was flaky due to test's expectation on map entries being iterated in a fixed order. I am creating a PR to fix that and will be attached to this issue.

**Comment by vikasmb** [comment]
ipamd package flaky tests have been fixed in the linked PRs.
