### ISSUE TITLE
 codecov/project  status check fails

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-cni-k8s#1822]
**What happened**:

 codecov/project  status check on PR, even while not required is failing often as of Jan 2022.

We might want to take a call and either remove it or fix it.

**Attach logs**

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
@orsenthil - it shows CI passed here - https://app.codecov.io/gh/aws/amazon-vpc-cni-k8s/commits?page=1. Wondering if we need to set this `allow_coverage_offsets: True`. For instance when we try to open the PR page on code coverage it show this error - "Changes found in between efb92a6...25f0daf (pseudo...base) which prevent comparing this pull request. " (https://app.codecov.io/gh/aws/amazon-vpc-cni-k8s/compare/1824?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr%20comments&utm_term=aws). The base chosen is quite old commit and as per the docs - https://docs.codecov.com/docs/comparing-commits this can be configured by setting `allow_coverage_offsets`.

**Comment by orsenthil** [comment]
Hi @jayanthvn - Thank you. I wasn't aware if that codecov success in the recent time. 

Let's try the suggestion you have shared above - https://github.com/aws/amazon-vpc-cni-k8s/pull/1833 

We can collect data and fix it in the PR.

**Comment by jayanthvn** [comment]
Thanks @orsenthil
