### ISSUE TITLE
Add K8s client package

### ISSUE THREAD

**Issue by ptzianos** [aws/amazon-vpc-cni-k8s#1837]
**What would you like to be added**: Use K8s code generator to produce a package that can be used by the K8s client to get/modify/delete the CRDs used by the daemon

**Why is this needed**: Need to build tooling and an operator to automate some processes and this would make a lot easier to check the state of the objects and modify them accordingly

**Comment by M00nF1sh** [comment]
@ptzianos 
These CRDs are consumed by the Unstructured K8s client currently. Would you use that to build your operator? e.g. using libraries like controller-runtime.
