### ISSUE TITLE
1.10.x documentation missing required env vars

### ISSUE THREAD

**Issue by laupow** [aws/amazon-vpc-cni-k8s#1854]
**What happened**:
I upgraded a self-managed add-on to 1.10.x and the container failed to start.  This is a repeat of https://github.com/aws/amazon-vpc-cni-k8s/issues/1725.

Docs in this repo say all env vars are optional, but this is not true as of the 1.10 release branch. 1.10.x won't start until users provide both `ENABLE_IPv4` _and_ `ENABLE_IPv6` environment variables.

Before the 1.10 release all env vars duplicated the default values and were not necessary. Therefore our manifests (managed in Terraform) don't include most env vars. 

**Attach logs**
### Upgrading my 1.9.x manifests to run a 1.10.x container image: SIGSEGV
```
{"level":"info","ts":"2022-02-04T22:24:54.997Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-02-04T22:24:54.999Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-02-04T22:24:55.013Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-02-04T22:24:55.014Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
I0204 22:24:56.095582      12 request.go:621] Throttling request took 1.047064274s, request: GET:https://10.100.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":"2022-02-04T22:24:57.022Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x5597a7c2b3f8]

goroutine 380 [running]:
github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd.(*IPAMContext).StartNodeIPPoolManager(0xc000281560)
    /go/src/github.com/aws/amazon-vpc-cni-k8s/pkg/ipamd/ipamd.go:640 +0x18
created by main._main
    /go/src/github.com/aws/amazon-vpc-cni-k8s/cmd/aws-k8s-agent/main.go:64 +0x2bb
{"level":"info","ts":"2022-02-04T22:24:59.030Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
```

### Adding `ENABLE_IPv4=true` 
```
{"level":"info","ts":"2022-02-04T22:43:05.478Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-02-04T22:43:05.479Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-02-04T22:43:05.494Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-02-04T22:43:05.495Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
I0204 22:43:06.579265      13 request.go:621] Throttling request took 1.046646791s, request: GET:https://10.100.0.1:443/apis/policy/v1?timeout=32s
{"level":"info","ts":"2022-02-04T22:43:07.503Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-02-04T22:43:09.510Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-02-04T22:43:11.518Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
/app/entrypoint.sh: line 171: ENABLE_IPv6: unbound variable
{"level":"info","ts":"2022-02-04T22:43:11.539Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
```

### Adding `ENABLE_IPv4=true` and `ENABLE_IPv6=false`
```
{"level":"info","ts":"2022-02-04T22:43:52.429Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-02-04T22:43:52.431Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-02-04T22:43:52.447Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-02-04T22:43:52.448Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
I0204 22:43:53.542573      14 request.go:621] Throttling request took 1.045520919s, request: GET:https://10.100.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":"2022-02-04T22:43:54.456Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-02-04T22:43:56.463Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-02-04T22:43:58.471Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-02-04T22:43:58.489Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
{"level":"info","ts":"2022-02-04T22:43:58.493Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2022-02-04T22:43:58.494Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}


```

**What you expected to happen**:
The container started without issues. 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy manifests from https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.10/config/master/aws-k8s-cni.yaml with no environment variables, because they are supposedly all optional.

**Anything else we need to know?**:
Please fix the 1.10.x default values. There is only one configuration that guarantees full backwards compatibility on 1.10.x:
 * `ENABLE_IPv4=true`
 * `ENABLE_IPv6=false`

Requiring users to add these variables makes no sense: this was the only valid configuration for every prior release.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version: 1.9.3, and trying to get to 1.10.2
- OS (e.g: `cat /etc/os-release`): EKS 1.19 AMI (will be updating to 1.21 after addons start)
- Kernel (e.g. `uname -a`):

**Comment by cgchinmay** [comment]
Yes, you are right. Starting from v1.10.x we need those env vars. Will update our docs.

**Comment by laupow** [comment]
Thanks! Love the quick response.  

For more context, my team still maintains self-managed versions of the cni addon in our clusters. The official manifest files won't work since we need to patch env vars. (kustomize could be an option, but it's not what we currently have)

I would love to use the managed EKS addons, but they don't support any configuration and therefore isn't very useful yet. Moving forward, I imagine users self-managing cluster addons won't be able to use default manifest files since I think that's essentially the same as the managed addon.

**Comment by achevuru** [comment]
@laupow Ideally we need to use the corresponding CNI manifest when we move to a new version of CNI. Modifying the image tag is not the recommended approach even if the defaults are automatically derived. For ex, we've enhancements to `liveness` and `readinessprobes` which are only present in the latest manifests. Can we add these two env vars to your base manifest which you are using? We will update the doc to make it clear.

**Comment by laupow** [comment]
@achevuru I did capture all the recent changes to the CNI manifests. And have a updated, working deployment. 👍

**Comment by cgchinmay** [comment]
The PR with updated documentation has been merged. So closing this issue
