### ISSUE TITLE
Update documentation for CNI environment variables and provide an example

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-vpc-cni-k8s#186]
The documentation says the following about the environment variables you can add to the pod manifest for the CNI plugin: 
```
AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
Type: Boolean
Default: false
```

```
WARM_ENI_TARGET
Type: Integer
Default: 1
```

Both of these should be of `Type: String`

A better description of how the custom networking for pods works would also be helpful.  When I reconfigured the existing nodes in my cluster to use custom networking, the daemonsets were assigned secondary IPs from the worker node's primary ENI instead of the ENI associated with the subnet specified in the CRD (custom network config).  Once I annotated the node with the CRD, pods scheduled onto that node were assigned secondary IPs from the custom network config range.  Also, please explain how pods, including daemonsets, can be assigned IPs from the custom range during scale out operations, prior to the node being annotated with a custom network config.

**Comment by mogren** [comment]
The custom network part is tracked in https://github.com/awsdocs/amazon-eks-user-guide/pull/72, will fix the types.

**Comment by marceloboeira** [comment]
it seems the issue is solved, should it be closed @jicowan / @mogren ?

**Comment by mogren** [comment]
Thanks @marceloboeira, you are right! 😄
