### ISSUE TITLE
CNI Metrics Helper does not account for changes in 1.2

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-vpc-cni-k8s#187]
If you configure an instance to use an ENIConfig CRD, the metrics helper still reports that max IPs is:
`max number of ENIs per instance(max number of secondary IPs per ENI - 1)`
even though pods are not supposed to use IPs allocated to the primary ENI on the worker node.

**Comment by mogren** [comment]
Closing in favor of #331 that has more discussion.
