### ISSUE TITLE
Image scan has detect several vulnerabilites

### ISSUE THREAD

**Issue by albertschwarzkopf** [aws/amazon-vpc-cni-k8s#1875]
Trivy image scanner has detect several vulnerabilites:

`trivy image 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.10.2-eksbuild.1`

`app/aws-cni (gobinary)
Total: 2 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

app/aws-k8s-agent (gobinary)
Total: 3 (UNKNOWN: 1, LOW: 0, MEDIUM: 1, HIGH: 1, CRITICAL: 0)

app/bandwidth (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

app/egress-v4-cni (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

app/grpc-health-probe (gobinary)
Total: 1 (UNKNOWN: 1, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

app/host-local (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

app/loopback (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

app/portmap (gobinary)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
`

**Environment**:
- Kubernetes version (use `kubectl version`): AWS EKS 1.21
- CNI Version: v1.10.2-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Bottlerocket OS

[k8s-cni-v1.10.2.txt](https://github.com/aws/amazon-vpc-cni-k8s/files/8109290/k8s-cni-v1.10.2.txt)

Could you please fix the "HIGH" vulnerabilities?

**Comment by vikasmb** [comment]
hello, please follow the [security guideline](https://github.com/aws/amazon-vpc-cni-k8s#security-disclosures) to report these. This issue will be closed as per the guideline.
