### ISSUE TITLE
v1.2 Docker image doesn't exist in us-east-1

### ISSUE THREAD

**Issue by deiwin** [aws/amazon-vpc-cni-k8s#189]
For v1.1, we used one image in `us-west-2` and another in `us-east-1`, to improve image pull speed/efficiency. Both of the following images exist:

* `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.1.0`
* `602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.1.0`

With v1.2, however, there doesn't seem to be a respective image in `us-east-1`. I.e. `602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.2.0` does not exist.

I know the example YAMLs in this repository only refer to `us-west-2`. Should we only use the `us-west-2` images?

**Comment by liwenwu-amazon** [comment]
I have just uploaded `602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:1.2.0`.  Please let me know if you still see problems.  thanks

**Comment by deiwin** [comment]
In general, can we expect the images to always be available in all regions where EKS is supported. E.g. including `eu-west-1` as well, at the moment?

**Comment by mogren** [comment]
Yes, they should be available in all regions. I also noticed that 1.2.0 was missing in eu-west-1, but 1.2.1 will be there once it is released.

**Comment by sr** [comment]
Looks like 1.3 and 1.4 haven't been pushed to us-east-1 either.

**Comment by mogren** [comment]
@sr They should be there. What image URIs did you try with? These one should work:

`602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.3.4`

`602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.4.1`

**Comment by sr** [comment]
@mogren 

```
$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.4.1
v1.4.1: Pulling from amazon-k8s-cni
f64ae36417d7: Pulling fs layer 
eea82191567d: Pulling fs layer 
```

```
$ docker pull 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.4.1
Error response from daemon: Get https://602401143452.dkr.ecr.us-east-1.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.4.1: no basic auth credentials
```
