### ISSUE TITLE
AWS_VPC_K8S_CNI_RANDOMIZESNAT=none is not used for IPv6 EKS cluster IPv4 SNAT

### ISSUE THREAD

**Issue by asheldon** [aws/amazon-vpc-cni-k8s#1893]
**What you expected to happen**:
When AWS_VPC_K8S_CNI_RANDOMIZESNAT is set to `none` on IPv6 EKS clusters, I expected IPv4 to IPv4 SNAT to use `none` for SNAT randomization and to therefore use the ephemeral port range set at the OS level for IPv4 egress.

**How to reproduce it (as minimally and precisely as possible)**:
Run an IPv6 EKS cluster and validate that IPv4 egress from the pods use ports outside the standard Linux ephemeral range (32768+).  Alternately, inspect the iptables rules and see `random-fully`.
1. Set up NACLs on a node subnet that prohibit IPv4 ingress on ports below 32768 from outside the VPC IP range
2. Put nodes in that subnet
3. Set `AWS_VPC_K8S_CNI_RANDOMIZESNAT=none` on the CNI
4. Exec into a pod and repeatedly attempt to access IPv4 resources (e.g. wget -4 [amazon.com](http://amazon.com/)). It will fail randomly, but frequently.

**Anything else we need to know?**:
This scenario makes connectivity flaky, which can break liveness / readiness probes on IPv6-only EKS clusters when those probes rely on IPv4.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.5-eks-bc4871b
- CNI Version: v1.10.2
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10.96-90.460.amzn2

**Comment by achevuru** [comment]
@[asheldon](https://github.com/asheldon) Can you expand on what you mean by `IPv6 to IPv4 SNAT`? We don't rely on NAT64 and there is no IPv6->IPv4 SNAT configured. Liveness/Readiness probes on an IPv6 only EKS cluster will only rely on IPv6 address assigned to the pod. IPv4 address assigned to the pod is a node local address and `kubelet` isn't aware of it. Why will a NACL(configured for IPs outside the VPC IP range) in IPv4 table block node local traffic (kubelet->pod  - liveness/readiness probes)? Can you please elaborate?

**Comment by asheldon** [comment]
> Can you expand on what you mean by IPv6 to IPv4 SNAT?

EKS doesn't have dual-stack pods, so IPv6 cluster pods egress to the internet via SNAT on the host.  If that is not how egress to the internet works, how does it work?

I believe the relevant code is in https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/egress-v4-cni-plugin/snat/snat.go

**Comment by achevuru** [comment]
@[asheldon](https://github.com/asheldon) Yes, but we rely on IPv4->IPv4 SNAT (i.e.,) `egress-v4-cni-plugin` will allocate a node local IPv4 address which is then SNAT'ed to Node's primary IP before leaving the node (for egress IPv4 traffic). 

I was referring to the statement- `which can break liveness / readiness probes on IPv6-only EKS clusters when those probes rely on IPv4`. These probes should be node local and over IPv6. So, the NACLs blocking certain port range from Non VPC IP range shouldn't break liveness/readiness probes - unless I misunderstood what was implied.

**Comment by asheldon** [comment]
> Why will a NACL(configured for IPs outside the VPC IP range) in IPv4 table block node local traffic (kubelet->pod - liveness/readiness probes)? Can you please elaborate?

I've observed with multiple Kubernetes add-ons that they attempt to reach out to the internet as part of their start up processes or as part of their health check process. Because network egress connectivity fails randomly, so do the health checks. With some add-ons, I've seen crash loops that eventually stop and stay stable, and with others the crash loops never end.  I haven't debugged each add-on to understand their unique failure modes, but it's safe to say that this behavior would affect applications as well.

**Comment by achevuru** [comment]
I see. So, the liveness/readiness probe failure is because a particular application pod is trying to reach an egress v4 endpoint but if the port number picked during the SNAT process falls in the port range blocked by the installed NACL then the application fails to come up leading to probe failures. Is that accurate?

**Comment by asheldon** [comment]
That is my understanding as well.

**Comment by achevuru** [comment]
Let me check that behavior and get back to you.

**Comment by achevuru** [comment]
@[asheldon](https://github.com/asheldon) I was able to sort of replicate the behavior. For the IPv4 (NodeLocal IP) -> IPv4 (Node Primary IP) based SNAT for IPv6 pods, we use `--random-fully` option by [default](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/egress-v4-cni-plugin/snat/snat.go#L36) if it is [supported by the underlying `iptables` version](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/egress-v4-cni-plugin/snat/snat.go#L52). `AWS_VPC_K8S_CNI_RANDOMIZESNAT` is only honored by the base VPC CNI plugin currently and is not considered in`egress-v4-cni-plugin`. We need to extend this env variable to the secondary CNI plugin as well to be able to control `--random-fully` option for v4 SNAT. We will do the required changes to support it.

**Comment by jayanthvn** [comment]
#1903 is merged to master. This will be released as part of CNI 1.11.0.
