### ISSUE TITLE
 ENABLE_PREFIX_DELEGATION=true

### ISSUE THREAD

**Issue by mclouds2020** [aws/amazon-vpc-cni-k8s#1900]
**What happened**:

In AWS documentation I can see ,

When you deploy a 1.21 or later cluster, version 1.10.1 or later of the VPC CNI add-on is deployed with it, and this setting is true by default. (ENABLE_PREFIX_DELEGATION=true)

I have created a new cluster 1.21 and with CNI as 1.10.1 but it is not enabled by default. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version 1.10.1

**Comment by haouc** [comment]
@mclouds2020 this may be caused by some confusion in the doc. We only set this ENV to true when you create a IPv6 EKS cluster. We will update the docs. Thank you.
