### ISSUE TITLE
aws-vpc-cni chart changelog?

### ISSUE THREAD

**Issue by arnaudmm** [aws/amazon-vpc-cni-k8s#1901]
Small suggestion: it would be great to have a changelog file in https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni and reference it here https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni

**Comment by haouc** [comment]
@arnaudmm I think this is a good point. We do have changelog for VPC CNI release. Adding a changelog for charts sounds a good idea. The PR to add the file is welcome.

**Comment by arnaudmm** [comment]
Sure I can add the file and I also can generate the changelog for the last 5 versions of the Chart using commit message.

But I need to know which commit were used to generate the last 5 versions referenced here : https://artifacthub.io/packages/helm/aws/aws-vpc-cni

What is the process to publish a Chart in artifacthub?

**Comment by jayanthvn** [comment]
@arnaudmm - I will check on the process and get back to you.

**Comment by SizZiKe** [comment]
bump
