### ISSUE TITLE
aws-node CNI is frequently restarting

### ISSUE THREAD

**Issue by oded-dd** [aws/amazon-vpc-cni-k8s#191]
We are using KOPS 1.10 and kubernetes 1.10.5 with aws-node version 1.1.
We are using CoreOS `1855.4.0` running docker `18.6.1` 

From time to time we are getting an alert indicating `aws-node` CNI was restarted frequently, and was unable to start (State is Error).
The only way to fix it is to terminate the instance and let the autoscaling group recreate it. In that case the problematic aws-node CNI is terminated and new one being created on the new instance.

Though the workaround is pretty simple it affects our day to day work.

**Comment by liwenwu-amazon** [comment]
@oded-dd is it possible you can run `/opt/cni/bin/aws-cni-support.sh` and send me `/var/log/aws-routed-cni/aws-cni-support.tar.gz`?   thanks

**Comment by oded-dd** [comment]
@liwenwu-amazon It happens today again on production but the person who handle it did not capture the logs. Once it will happen again I will share the files. Thank you.

**Comment by oded-dd** [comment]
@liwenwu-amazon 

As the CNI provides 2 private IPs I was not able to access the primary one (172.40.52.87), but only the secondary one (172.40.57.206).

As we are working with CoreOS no `/var/log/messages` exists (So I removed it from the script for now)

[aws-cni-support.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/2533791/aws-cni-support.tar.gz)

**Comment by oded-dd** [comment]
We also see the same issue happen after instance reboot

**Comment by liwenwu-amazon** [comment]
@oded-dd  I am seeing following errors in your `aws-cni-support.tar.gz`

```
2018-10-31T09:01:15Z [ERROR] Failed to CreateNetworkInterface NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2018-10-31T09:01:15Z [ERROR] Failed to increase pool size due to not able to allocate ENI allocate eni: failed to create eni: failed to create network interface: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Also I do NOT see route for instance metadata service in your route table.   In another word, the following route is missing on the node.
```
169.254.169.254 dev eth0
```
I think your AMI need to make sure metadata service route exists in the route table.  Since `CNI ipamD` has dependencies on instance metadata service, it will crash if it can not talk to instance metadata service.

**Comment by oded-dd** [comment]
@liwenwu-amazon I am not sure I understand the answer as I am able to scrape the URI `curl http://169.254.169.254/latest/meta-data/`

**Comment by oded-dd** [comment]
Also after `reboot` to the instance it works again

**Comment by liwenwu-amazon** [comment]
@oded-dd  
Can you take a look at your AMI ?  From the support bundle (`aws-cni-support.tar.gz`) you attached earlier,  the following route is missing
```
169.254.169.254 dev eth0
```
This causes all **Pods** running on this node NOT able to retrieve instance meta-data.

**Comment by WarpRat** [comment]
> @liwenwu-amazon I am not sure I understand the answer as I am able to scrape the URI `curl http://169.254.169.254/latest/meta-data/`

We're having a similar problem and can also curl the meta-data server both from the node itself and while exec'd into the aws-node container. After running that support script, I see the route.output file in the log directory, and we don't have a direct route to 169.254.169.254 either but wouldn't it just go over the default route which is also over eth0? So far it has only happened on one of our nodes in one of our clusters - comparing the output of that support script on other nodes to this node, the routes look the same.

We're running the 1.1 cni plugin, c5.xlarge, using kubernetes version 1.10.9, kops version 1.10, running on this public debian AMI - k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17 (ami-0718f95f70da8f50e)

**Comment by mogren** [comment]
Have been unable to reproduce this issue since the v1.4.0 release.
