### ISSUE TITLE
CNI reports as Ready even if it cannot get any IPs

### ISSUE THREAD

**Issue by chickenbeef** [aws/amazon-vpc-cni-k8s#1923]
**What happened**:

After pull request #1585 and #1830 was merged, IPAMD reports as healthy and running even if there are insufficient IP addresses or prefixes in a subnet. This changes the behaviour of the VPC CNI plugin as the entrypoint script will copy the CNI binary and kubelet will mark the node as `Ready`. Pods will get scheduled onto the node but get stuck in ContainerCreating because IPAMD cannot assign an IP address.

Prior to #1585 and #1830, the aws-node pod would go into a CrashLoopBackOff state and the node would remain in a `NotReady` state - preventing pods from being scheduled onto it.

I am creating this issue to learn more about why the behaviour was changed. Was the main reason to reduce the number of `DescribeNetworkInterface` calls each time the aws-node was restarted due to `InsufficientCidrBlocks` and `InsufficientFreeAddressesInSubnet` errors? Is there any other issue that this change resolves?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version: 1.10.2

**Comment by jayanthvn** [comment]
Yes this was done to reduce the number of `DescribeNetworkInterface` calls instead reconciler will retry every 2 mins.

**Comment by jayanthvn** [comment]
@chickenbeef - issue is reopened. Can you please let me know if you are seeing any issue with the approach?

**Comment by jayanthvn** [comment]
One option is to add `noSchedule` taint when IPs/Prefixes are not available on startup. But need to explore any risks by enabling this functionality in IPAMD.

**Comment by jayanthvn** [comment]
This would need providing pod patch permission to aws-node. We are actually trying to improve aws-node security posture by limiting/reducing RBAC permissions. Maybe a scheduler extender - https://github.com/aws/amazon-vpc-cni-k8s/issues/1160 might be a better solution but haven't scoped yet.

**Comment by jayanthvn** [comment]
@chickenbeef - we have a similar issue - https://github.com/aws/amazon-vpc-cni-k8s/issues/1523. So closing this for now. Will provide updates on this https://github.com/aws/amazon-vpc-cni-k8s/issues/1523#issuecomment-1020158661.
