### ISSUE TITLE
IPv6 egress support for IPv4 EKS clusters

### ISSUE THREAD

**Issue by asheldon** [aws/amazon-vpc-cni-k8s#1925]
**What would you like to be added**:

The ability to egress from an IPv4-only pod to an IPv6-only endpoint

**Why is this needed**:

When a resource is available only via IPv6, it cannot be accessed from an IPv4-only EKS cluster, except via host networking.

**Comment by achevuru** [comment]
[asheldon](https://github.com/asheldon) We will look in to it and get back to you. However, interested in understanding the use case a bit more. Are you more interested in reaching external IPv6 only services (or) IPv6 services hosted on different clusters with in the same VPC?

Have you considered using a [dual stack NLB/ALB](https://aws.amazon.com/about-aws/whats-new/2021/11/application-load-balancer-network-load-balancer-end-to-end-ipv6-support/) for this purpose? (i.e.,) let the dual stack NLB handle the IPv4 to IPv6 transition between the client and the server. AWS ALB controller now supports IPv6 targets as well (IP Mode).

**Comment by asheldon** [comment]
@achevuru Thanks for the reply. Snapchat runs a [service mesh](https://eng.snap.com/monolith-to-multicloud-microservices-snap-service-mesh) based on [Envoy](https://envoyproxy.io/), so for typical communication between services, we do not use traditional load balancers. This is especially true in scenarios where we use routing techniques, like ring hashing, that don't treat every server in a fleet as stateless and interchangeable. Dual-stack NLB/ALB is a great technology, but it doesn't meet all our needs.

Reaching IPv6 resources within the VPC is more important than reaching IPv6 resources outside the VPC, but we'd like to be able to do both.

**Comment by asheldon** [comment]
There may be some relationship with #956

**Comment by achevuru** [comment]
[asheldon](https://github.com/asheldon) We're exploring a solution that is similar to our current Egress IPv4 support for IPv6 pods. Will provide an update in few weeks.

**Comment by jdn5126** [comment]
Closing as complete by https://github.com/aws/amazon-vpc-cni-k8s/pull/2361. Feature will ship in v1.13.0 release
