### ISSUE TITLE
VPC CNI Network Policy controller

### ISSUE THREAD

**Issue by dsaydon90** [aws/amazon-vpc-cni-k8s#1934]
**What would you like to be added**:
Today, when you create a new **EKS** cluster you are getting the **VPC cni** by default.
Now, if you need to limit the network access between your pods you have several choices:

1. Install [Calico add-on](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) which comes with some limitations 
2. Use [Security groups for pods ](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)

So, if I already has the **VPC cni** by default, and I want to use the [k8s network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) syntax, why not to keep it simple by creating  a new controller that will do it for me? 
just like the [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/) which creates ALBs for me with the same k8s ingress syntax.

**Why is this needed**:
Controller that will detect [k8s network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/)  and will create the Security groups for pods for me

related:

- https://github.com/aws/containers-roadmap/issues/1478
- https://github.com/aws/amazon-vpc-cni-k8s/issues/1257

**Comment by jayanthvn** [comment]
We already have a roadmap item - https://github.com/aws/containers-roadmap/issues/1478

**Comment by jayanthvn** [comment]
@dsaydon90 - We already have a roadmap item for NP support. So will close this issue here and provide you update about the release here - https://github.com/aws/containers-roadmap/issues/1478
