### ISSUE TITLE
v1.10.2 could leak IP addresses under edge conditions

### ISSUE THREAD

**Issue by M00nF1sh** [aws/amazon-vpc-cni-k8s#1939]
**What happened**:
v1.10.2 introduced a [change](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.10.2/cmd/routed-eni-cni-plugin/cni.go#L320) to skip CNI's delCmd when netNS is empty. This can cause IP address leaks under certain edge conditions when sandbox container was terminated(e.g. OOM), where IPAMD didn't free the IP addresses used by these terminated Pod.  

The mitigation step if it happens is to:
1. restart the AWS-Node pod, which will cause IPAMD to reconcile it's IP pool with alive Pod information from read from CRI socket.
2. downgrade to CNI v1.10.1 (we are working to release a v1.10.3)

**Attach logs**

**What you expected to happen**:
IPAMD should always free IP addresses when pods are terminated, even when sandbox container was terminated first.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version: v1.12
- OS (e.g: `cat /etc/os-release`): linux
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
1.10.3 release is done on GitHub.
