### ISSUE TITLE
Change Image Name on yaml manifest based on the version (vpc-cni v1.8.0)

### ISSUE THREAD

**Issue by chiplux** [aws/amazon-vpc-cni-k8s#1947]
**What happened**:

Image problem on version 1.8.0, https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.8.0/config/master/aws-k8s-cni.yaml#L156
should change:
1.  `"image": "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:latest"` to `"image": "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.8.0"`
2. `"image": "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:latest"` to `"image": "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.8.0"`

**Attach logs**

```
  Normal   BackOff    15s (x5 over 87s)  kubelet            Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:latest"
  Warning  Failed     15s (x5 over 87s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    1s (x4 over 88s)   kubelet            Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:latest"
  Warning  Failed     1s (x4 over 88s)   kubelet            Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:latest not found: manifest unknown: Requested image not found
  Warning  Failed     1s (x4 over 88s)   kubelet            Error: ErrImagePull
```
**What you expected to happen**:
change the image name
**How to reproduce it (as minimally and precisely as possible)**:
updating the vpc-cni-add-on based on this document, https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on,
when applying the manifest
```
kubectl apply -f aws-k8s-cni.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): version 1.21
- CNI Version: 1.8.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): 5.13.0-39-generic #44~20.04.1-Ubuntu

**Comment by jayanthvn** [comment]
@chiplux - you can find the correct manifest here - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.8.0/config/v1.8/aws-k8s-cni.yaml. 

Is there any reason you would like config/master to be updated in release-1.8 branch?

**Comment by jayanthvn** [comment]
@chiplux - Until v1.9.0, we used to have image tag "latest" in config/master and have version tag in config/<release-version> for instance "config/v1.8". But "latest" tag image never existed hence from 1.9.0 onwards we just have correct latest tag under config/master.

To find the correct release, you can check here - https://github.com/aws/amazon-vpc-cni-k8s/releases

From v1.9.0 onwards you can follow the step as above i.e, replacing v1.10.1 to v1.9.0 - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.10.1/config/master/aws-k8s-cni.yaml but not with v1.8.0. Sorry for the confusion.

**Comment by chiplux** [comment]
@jayanthvn - Thank you for the information, I think we can close this issue.
Thank you.
