### ISSUE TITLE
Configure the private image registry

### ISSUE THREAD

**Issue by raj13aug** [aws/amazon-vpc-cni-k8s#1955]
**What happened**:

How to configure calico operator to pull images from a our private registry rather than public registry? please help me on this matter.

I have followed the AWS document to install addon via  manifest. 

https://docs.aws.amazon.com/eks/latest/userguide/calico.html

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
@raj13aug - You mean the Tigera operator? You might have to update here - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/calico-operator.yaml#L5153

**Comment by jayanthvn** [comment]
You can update the image with the private repo in the calico operator manifest. Closing this issue.
