### ISSUE TITLE
CNI Plugin fails to start or log any errors if the default/kubernetes service contains invalid/non-functional endpoints

### ISSUE THREAD

**Issue by sidewinder12s** [aws/amazon-vpc-cni-k8s#1963]
**What happened**:
Somehow my API Servers which were configured with public/private access, ended up with the control plane ENIs going into an Available (instead of attached) state. This left their addresses left in the service object for the kubernetes service in the default namespace, but the IPs were non-functional.

This left the cluster is a completely broken state/no networking with the CNI plugin not throwing any errors about being unable to contact anything/what was actually wrong.

**Attach logs**
I've forwarded the log bundle to the email address provided.

This is all that the CNI would output before it restarted:

```log
{"level":"info","ts":"2022-04-11T20:03:36.299Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-04-11T20:03:36.299Z","caller":"aws-k8s-agent/main.go:42","msg":"Testing communication with server"}
```

**What you expected to happen**:

I would have expected some kind of clear error message about being unable to contact the control plane.

**How to reproduce it (as minimally and precisely as possible)**:

It would appear if you are able to detach the control plane ENIs in your VPC, it should reproduce.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version 1.10.2
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
`Linux ip-10-64-76-152.us-west-2.compute.internal 5.4.172-90.336.amzn2.x86_64 #1 SMP Wed Jan 19 23:08:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jayanthvn** [comment]
Maybe we can add an error message - "Unable to reach API server" after the retry here - https://github.com/aws/amazon-vpc-cni-k8s/blob/dd7615ed0003457a55ebfa9225d3661d58eaef63/pkg/k8sapi/k8sutils.go#L118

**Comment by jayanthvn** [comment]
#1988 merged.
