### ISSUE TITLE
Inconsistent doc/code for ENABLE_IPv4 behaviour

### ISSUE THREAD

**Issue by tlnd-rdalverny** [aws/amazon-vpc-cni-k8s#1965]
Hi! The README (https://github.com/aws/amazon-vpc-cni-k8s#enable_ipv4-v1100) says:

> ENABLE_IPv4 (v1.10.0+)
> Type: Boolean as a String
> Default: true

while:

https://github.com/aws/amazon-vpc-cni-k8s/blob/dd7615ed0003457a55ebfa9225d3661d58eaef63/pkg/ipamd/ipamd.go#L1686-L1688

I'm not sure which should be changed (doc or code)?

**Comment by achevuru** [comment]
@[tlnd-rdalverny](https://github.com/tlnd-rdalverny) `README` is referring to the default value used in the published VPC CNI manifests - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L195.

**Comment by tlnd-rdalverny** [comment]
@achevuru thanks for pointing this out.

I expected "default" to mean that's how the app behaves when the variable is not set at all, as the README states "all of them are optional".
