### ISSUE TITLE
CNI deletes in-use ENI after restart with stale IMDS, leaving pods without network connectivity

### ISSUE THREAD

**Issue by drakedevel** [aws/amazon-vpc-cni-k8s#1967]
**What happened**:

A pod was found running with an IP not associated with the EC2 instance it was running on. Upon further investigation, we found that the CNI had allocated that IP to the pod, and then later deleted the ENI while it was in-use, killing network connectivity to the pod. Here's a walkthrough of the logs I think are relevant (will email full ones):

CNI startup, so far so good:
```json
{"level":"info","ts":"2022-04-12T18:09:00.272Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-04-12T18:09:00.273Z","caller":"aws-k8s-agent/main.go:42","msg":"Testing communication with server"}
{"level":"info","ts":"2022-04-12T18:09:00.311Z","caller":"aws-k8s-agent/main.go:42","msg":"Successful communication with the Cluster! Cluster Version is: v1.20. git version: v1.20.10. git tree state: clean. commit: 8152330a2b6ca3621196e62966ef761b8f5a61bb. platform: linux/amd64"}
```

Shortly thereafter, it creates its first ENI (`eni-08c...`), which is the one it will later free while in-use:
```json
{"level":"info","ts":"2022-04-12T18:09:06.467Z","caller":"awsutils/awsutils.go:730","msg":"Creating ENI with security groups: [sg-0179e0179f3e93bab] in subnet: subnet-07e1bb9d6ebd2e0de"}
{"level":"info","ts":"2022-04-12T18:09:06.882Z","caller":"awsutils/awsutils.go:730","msg":"Created a new ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:09:08.031Z","caller":"ipamd/ipamd.go:853","msg":"Successfully created and attached a new ENI eni-08c872dba81641a42 to instance"}
{"level":"info","ts":"2022-04-12T18:09:08.031Z","caller":"ipamd/ipamd.go:862","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:09:08.431Z","caller":"ipamd/ipamd.go:862","msg":"Allocated 14 private IP addresses"}
```

But it spent the next three minutes unable to actually hand out any of the IPs it just allocated:
```json
{"level":"info","ts":"2022-04-12T18:09:10.496Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /var/run/netns/bfda097f-fa1f-4e12-a177-1a5f1c10af84, Sandbox 82dc579a09949d5872fdc41bfe4bbdfe0f2afb932ee68b1ccd27b43c31834287, ifname eth0"}
{"level":"error","ts":"2022-04-12T18:09:10.496Z","caller":"datastore/data_store.go:680","msg":"DataStore has no available IP/Prefix addresses"}
{"level":"info","ts":"2022-04-12T18:09:10.513Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr , IPv6Addr: , DeviceNumber: -1, err: assignPodIPv4AddressUnsafe: no available IP/Prefix addresses"}
...
{"level":"error","ts":"2022-04-12T18:12:07.852Z","caller":"datastore/data_store.go:680","msg":"DataStore has no available IP/Prefix addresses"}
{"level":"info","ts":"2022-04-12T18:12:07.870Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr , IPv6Addr: , DeviceNumber: -1, err: assignPodIPv4AddressUnsafe: no available IP/Prefix addresses"}
```

Apparently because the IMDS was stale:
```json
{"level":"error","ts":"2022-04-12T18:12:08.766Z","caller":"ipamd/ipamd.go:812","msg":"Failed to increase pool size: Unable to discover attached ENI from metadata service waitForENIAndIPsAttached: giving up trying to retrieve ENIs from metadata service"}
```

So it triggers a resync from the EC2 API. It also allocates 14 more IPs here:

```json
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"Got network cardindex 0 for ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"eni-08c872dba81641a42 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"awsutils/awsutils.go:1201","msg":"logOutOfSyncState: DescribeNetworkInterfaces(eni-08c872dba81641a42) yielded private IPv4 addresses 100.68.33.202,100.68.35.149,100.68.35.40,100.68.36.147,100.68.37.227,100.68.40.230,100.68.41.40,100.68.42.38,100.68.55.166,100.68.58.43,100.68.61.197,100.68.63.104,100.68.63.144,100.68.63.219 that were not yet found in IMDS."}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"Got network cardindex 0 for ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"ipamd/ipamd.go:1318","msg":"eni-0c7c58f6368533bd1 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:12:11.412Z","caller":"networkutils/network.go:904","msg":"Setting up network for an ENI with IP address 100.68.41.92, MAC address 06:ad:59:59:f9:65, CIDR 100.68.32.0/19 and route table 2"}
{"level":"info","ts":"2022-04-12T18:12:11.421Z","caller":"ipamd/ipamd.go:1372","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:12:11.421Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 10.7.8.73 on ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:12:13.921Z","caller":"ipamd/ipamd.go:935","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.61.197/32 to datastore"}
...
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.41.40/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:12:14.356Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.41.40/32 to datastore"}
...
```

Having done that, it then handles four AddNetworkRequests successfully, including assigning 100.68.41.40 to the pod that brought this issue to our attention:

```json
{"level":"info","ts":"2022-04-12T18:12:16.851Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /var/run/netns/76c30140-c4c8-4408-a445-9f73cb3489a2, Sandbox be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a, ifname eth0"}
{"level":"info","ts":"2022-04-12T18:12:16.851Z","caller":"datastore/data_store.go:784","msg":"AssignPodIPv4Address: Assign IP 100.68.41.40 to sandbox aws-cni/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/eth0"}
...
{"level":"info","ts":"2022-04-12T18:12:22.884Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr 100.68.61.197, IPv6Addr: , DeviceNumber: 1, err: <nil>"}
```

Then it starts another resync -- not sure what triggers it. The pod is replaced shortly thereafter -- this lines up with a rolling update to adjust the resource requests.

```json
{"level":"info","ts":"2022-04-12T18:13:16.877Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 10.7.8.73 on ENI eni-0c7c58f6368533bd1"}
{"level":"warn","ts":"2022-04-12T18:13:16.878Z","caller":"ipamd/ipamd.go:1350","msg":"Instance metadata does not match data store! ipPool: [100.68.35.40 100.68.63.144 100.68.61.197 100.68.55.166 100.68.63.219 100.68.33.202 100.68.35.149 100.68.41.40 100.68.58.43 100.68.37.227 100.68.63.104 100.68.36.147 100.68.42.38 100.68.40.230], metadata: [{\n  Primary: true,\n  PrivateIpAddress: \"100.68.41.92\"\n}]"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1422","msg":"Reconcile and skip primary IP 100.68.41.92 on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1422","msg":"Trying to add 100.68.61.197"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"IP already in DS"}
...
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"Adding 100.68.63.219/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:16.976Z","caller":"ipamd/ipamd.go:1546","msg":"IP already in DS"}
{"level":"info","ts":"2022-04-12T18:13:51.327Z","caller":"aws-k8s-agent/main.go:27","msg":"Starting L-IPAMD   ..."}
```

The IMDS is _still_ not updated, so the new CNI pod has to sync from the EC2 API. However, it retrieves the list of running pods before the IPs from that sync make it into the datastore:

```json
{"level":"info","ts":"2022-04-12T18:13:54.250Z","caller":"awsutils/awsutils.go:1592","msg":"Will attempt to clean up AWS CNI leaked ENIs after waiting 4m41s."}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"ipamd/ipamd.go:457","msg":"Setting up host network... "}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"networkutils/network.go:262","msg":"Discovered primary interface: eth0"}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"ipamd/ipamd.go:457","msg":"Skip updating RPF for primary interface: net/ipv4/conf/eth0/rp_filter"}
{"level":"info","ts":"2022-04-12T18:13:54.251Z","caller":"networkutils/network.go:365","msg":"Discovered primary interface: eth0"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"Got network cardindex 0 for ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"eni-08c872dba81641a42 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"awsutils/awsutils.go:1201","msg":"logOutOfSyncState: DescribeNetworkInterfaces(eni-08c872dba81641a42) yielded private IPv4 addresses 100.68.33.202,100.68.35.149,100.68.35.40,100.68.36.147,100.68.37.227,100.68.40.230,100.68.41.40,100.68.42.38,100.68.55.166,100.68.58.43,100.68.61.197,100.68.63.104,100.68.63.144,100.68.63.219 that were not yet found in IMDS."}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"Got network cardindex 0 for ENI eni-0c7c58f6368533bd1"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:463","msg":"eni-0c7c58f6368533bd1 is of type: interface"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:487","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"ipamd/ipamd.go:415","msg":"ENI eni-0c7c58f6368533bd1 set up."}
{"level":"info","ts":"2022-04-12T18:13:54.442Z","caller":"networkutils/network.go:904","msg":"Setting up network for an ENI with IP address 100.68.41.92, MAC address 06:ad:59:59:f9:65, CIDR 100.68.32.0/19 and route table 2"}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:487","msg":"Found ENIs having 1 secondary IPs and 0 Prefixes"}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:415","msg":"ENI eni-08c872dba81641a42 set up."}
{"level":"info","ts":"2022-04-12T18:13:54.443Z","caller":"ipamd/ipamd.go:509","msg":"Reading ipam state from CRI"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/c32c2fa0bf126622bc2c3c0f43fda78ff75912cdb78729d3f1fe87bf209758ca/unknown uses unknown IP Address 100.68.61.197 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/cdcee44ae7b074c002d321a88dbda867a6918084e45e6aa15a68f8ab71048b29/unknown uses unknown IP Address 100.68.42.38 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/94fe6dd3ea800537f7c86bf12f5ff31643fdf91d2296770ce5cc2e108046bf71/unknown uses unknown IP Address 100.68.58.43 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:509","msg":"datastore: Sandbox _migrated-from-cri/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/unknown uses unknown IP Address 100.68.41.40 - presuming stale/dead"}
{"level":"info","ts":"2022-04-12T18:13:54.446Z","caller":"ipamd/ipamd.go:541","msg":"Get Node Info for: ip-10-7-8-73.eu-west-1.compute.internal"}
{"level":"info","ts":"2022-04-12T18:13:54.647Z","caller":"ipamd/ipamd.go:935","msg":"Trying to allocate 14 IP addresses on ENI eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.61.197/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.61.197/32 to datastore"}
...
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Adding 100.68.41.40/32 to DS for eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:13:55.100Z","caller":"ipamd/ipamd.go:1077","msg":"Added ENI(eni-08c872dba81641a42)'s IP/Prefix 100.68.41.40/32 to datastore"}
...
```

A couple of seconds later, it concludes that eni-08c... is unused and deletes it:

```json
{"level":"info","ts":"2022-04-12T18:14:57.771Z","caller":"ipamd/ipamd.go:699","msg":"RemoveUnusedENIFromStore eni-08c872dba81641a42: IP/Prefix address pool stats: free 14 addresses, total: 0, assigned: 0, total prefixes: 0"}
{"level":"info","ts":"2022-04-12T18:14:57.771Z","caller":"awsutils/awsutils.go:913","msg":"Trying to free ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:14:58.506Z","caller":"retry/retry.go:70","msg":"Successfully detached ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:15:02.922Z","caller":"retry/retry.go:70","msg":"Successfully deleted ENI: eni-08c872dba81641a42"}
{"level":"info","ts":"2022-04-12T18:15:02.922Z","caller":"awsutils/awsutils.go:913","msg":"Successfully freed ENI: eni-08c872dba81641a42"}
```

Hours later, the pod is noticed in a bad state and manually deleted, and the CNI has no record of the pod:

```json
{"level":"info","ts":"2022-04-12T21:03:00.426Z","caller":"rpc/rpc.pb.go:731","msg":"Received DelNetwork for Sandbox be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a"}
{"level":"warn","ts":"2022-04-12T21:03:00.426Z","caller":"ipamd/rpc_handler.go:222","msg":"UnassignPodIPAddress: Failed to find sandbox _migrated-from-cri/be11ae75f40d6dfc666fb96a568f94ebc264122000af5edb3752389e1d092e1a/unknown"}
{"level":"info","ts":"2022-04-12T21:03:00.464Z","caller":"rpc/rpc.pb.go:731","msg":"Send DelNetworkReply: IPv4Addr , DeviceNumber: 0, err: datastore: unknown pod"}
```

So it seems like the startup process should wait for the datastore to be populated with the attached IPs before permanently forgetting about running pods.

**Attach logs**
Will send full log bundle by email.

**What you expected to happen**:
The CNI should not delete the ENI currently in-use by pods on the node.

**How to reproduce it (as minimally and precisely as possible)**:
Reproducing this in a natural environment may be a challenge since it relies on the IMDS being stale, but I would bet that it reproduces readily if you run a modified version of the binary that filters out all but the primary interface from `GetMACs`. Just restart it after it allocates a few IPs.

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.10
- CNI Version: 1.10.2
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.4.181-99.354.amzn2.x86_64

**Comment by jayanthvn** [comment]
@drakedevel - Thanks for the details. I will look into the logs and get back to you. Typically in the reconciler we shouldn't be adding the ENI in the datastore if the IPs are not populated in IMDS similar to the behavior with initial ENI attachment.

**Comment by jayanthvn** [comment]
If we hit this state - https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/awsutils/awsutils.go#L1226 and "none of the IPs" are available in IMDS then we need to remove the ENI from eniMap - https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/awsutils/awsutils.go#L1149. But if there is a mismatch of few IPs i.e, only subset of IPs are in IMDS then we need those IPs to reconcile so we shouldn't remove those from the eniMap.

**Comment by drakedevel** [comment]
> But if there is a mismatch of few IPs i.e, only subset of IPs are in IMDS then we need those IPs to reconcile so we shouldn't remove those from the eniMap.

I'm not sure that distinction is totally meaningful. For my particular case the IMDS was stale in a way that caused the whole ENI not to show up, but it seems like it should also be possible for e.g. the recent allocations not to show up. For example something like:
- Allocate ENI A
- Allocate IP 1 on ENI A 
- IMDS updates with IP 1
- Assign IP 1 to pod X
- Allocate IP 2 on ENI A
  - As I understand it, adding an IP to an existing ENI doesn't wait for the IMDS
- Assign IP 2 to pod Y
- CNI pod restarts
- IMDS hasn't updated yet, so the CNI only sees IP 1 in IMDS. It ignores pod Y during the CRI sync since it has an unknown IP, and later frees IP 2.

---

The root of the issue as far as I can tell is that the `ReadBackingStore` requires that the datastore state be accurate, and the `DescribeAllENIs`/`setupENI` step beforehand fails to satisfy that invariant. When `ReadBackingStore` fetches the pods from the CRI / checkpoint, it skips over any pods with unknown IPs, triggering the `presuming stale/dead` log line:
https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/ipamd/datastore/data_store.go#L492-L495

Since `ReadBackingStore` is only called once, if a pod is skipped here, it's game over. The CNI won't be aware of that IP assignment, and is free to release the IP or assign it to a different pod -- neither of which is a good outcome. 

`DescribeAllENIs` actually fetches the IPs from the EC2 API, and uses that to log that the IMDS is out of sync, but then discards that result and returns the stale IMDS data anyway. `setupENI` then happily uses that stale data to populate the datastore, and then `ReadBackingStore` is called with an incorrect datastore state. It seems like that loop needs to wait for the IMDS to be in-sync, or to just use the data from the EC2 API directly. (Is there ever a case where the IMDS is more accurate than the EC2 API? If so then probably the answer is to wait for it to be in-sync.)

**Comment by jayanthvn** [comment]
Yes agreed when IPs are added to existing ENI we need to wait for IMDS to sync which is not there today. 

The assumption of backing store is that, it always has correct and latest information and hence it is called once to restore on startup. First we get attachedENIs and then compare it with EC2 data - https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/awsutils/awsutils.go#L1155. If the ENI is not found then we do not pass it for further processing- - https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/awsutils/awsutils.go#L1172 

But for the attached ENIs if the number of IPs are a mismatch then we log the out of sync error- https://github.com/aws/amazon-vpc-cni-k8s/blob/db1481f2f2d89af057866afa5e227350a17ecefa/pkg/awsutils/awsutils.go#L1226

Yes EC2 will always be accurate but we rely on IMDS mainly because to reduce the number of EC2 API calls and use IMDS for most of the metadata info like subnet, Mac, instance id and so on.

**Comment by drakedevel** [comment]
> Yes EC2 will always be accurate but we rely on IMDS mainly because to reduce the number of EC2 API calls and use IMDS for most of the metadata info like subnet, Mac, instance id and so on.

That makes sense, but `DescribeAllENIs` _always_ calls the EC2 API, so it seems like it costs nothing extra to use the result.

Incidentally I don't totally understand one thing that's going on in `DescribeAllENIs`. It looks like it uses IMDS to get the list of attached ENI IDs, which it then passes in as `NetworkInterfaceIds` to `DescribeNetworkInterfaces`. If one of those ENIs isn't found, it removes it from the list and tries again.

(I guess that means for my logs, the ENI _was_ in the IMDS, but none of the secondary IPs?)

It seems like it would be simpler to just do a single `DescribeNetworkInterfaces` with a filter on `attachment.instance-id=<this instance ID>`; then you have the authoritatively-correct set of attached ENIs and all of their IPs in one call guaranteed. (This also means it doesn't rely on the IMDS to have an up-to-date list of all the attached ENIs.)

**Comment by jayanthvn** [comment]
_"The link there looks like it's the case where the ENI is in the IMDS, but not in the EC2 API, which is the opposite of the case I hit (where it's in the EC2 API but not in the IMDS)."_ -> Basically I was trying to explain that here we make sure the ENIs fetched from IMDS is indeed attached to the instance and not stale ENIs and this is to handle existing ENIs. But yes, ENI might be created and not present in IMDS which will be handled in `waitForENIAndIPsAttached`. 

_"but it seems that if the ENI does legitimately exist (as defined by the EC2 API), and it's removed from eniMap"_ -> Yeah I was referring that we need to design around this so that the eni is not added to the eniMap, sorry for the confusion.

Yes based on your logs the ENI was attached but not the IPs.

_"It seems like it would be simpler to just do a single DescribeNetworkInterfaces with a filter on attachment.instance-id=<this instance ID>;"_ Yes this will be simple and we have thought about having a single source of truth rather than relying on IMDS and EC2 calls. This would need some code restructuring. I will check how it can simplified.

**Comment by drakedevel** [comment]
@jayanthvn this should probably be reopened (unless the planned changes were already made)
