### ISSUE TITLE
missing changelog entry for 1.11.0

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1978]
this is empty ... https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.11.0/CHANGELOG.md

**Comment by jayanthvn** [comment]
Thanks, will update.

**Comment by jayanthvn** [comment]
Change log is updated with the latest v1.11.2 release - https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.11/CHANGELOG.md
