### ISSUE TITLE
HOWTO tell if the cluster uses the Amazon VPC CNI?

### ISSUE THREAD

**Issue by acnodal-tc** [aws/amazon-vpc-cni-k8s#1980]
**What happened**:

I'm working on a product that needs to work differently when running in a cluster that uses the Amazon VPC CNI so I'd like a reliable way to detect when that's true. One approach would be to scan the files in /etc/cni/net.d and look for objects like:

```
{  "cniVersion": "0.3.1",
  "name": "aws-cni",
  "plugins": [    {
      "name": "aws-cni",      "type": "aws-cni",
      "vethPrefix": "eni",      "mtu": "9001",
      "pluginLogFile": "/var/log/aws-routed-eni/plugin.log",
      "pluginLogLevel": "DEBUG"    },
```
This seems clumsy, though.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22 and later
- CNI Version: 0.3.1 and later
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any

**Comment by jayanthvn** [comment]
@acnodal-tc - How about checking aws-node DaemonSet?

**Comment by cgchinmay** [comment]
@acnodal-tc If you are asking as you may have more than 1 cni plugins in your cluster, then its the lexicographically first file found in location /etc/cni/net.d and the file should conform to cni spec, which gets used to setup pod networks, as described here: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni
