### ISSUE TITLE
CNI spec & binary versions

### ISSUE THREAD

**Issue by M00nF1sh** [aws/amazon-vpc-cni-k8s#1986]
**What would you like to be added**:
We should upgrade the CNI spec & binary versions to newer version v1.0.0+.

**Why is this needed**:
1. the current CNI spec and binary versions are a bit too old.
2. https://docs.google.com/document/d/1zwKls4-NUxkpak-591ghRaGEKdjp8BEdXD8YpL_zdIk/edit#

**Comment by nce** [comment]
I'd appreciate it, as it's currently not possible to use the aws-vpc-cni on the latest flatcar release (packaging `containerd 1.6.3`)

```
  Normal   Scheduled               1s    default-scheduler  Successfully assigned default/nginx to i-072da99539f0878c9
  Warning  FailedCreatePodSandBox  1s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "59e8c55f09e25ec2c061d3d4be525e894f773f9f577d0b2ed023d112407d3697": plugin type="loopback" failed (add): incompatible CNI versions; config is "1.0.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1" "0.4.0"]
  ```
  
  apparently due to the outdated loopback:
  ```
  i-06e8a3ebc6832070a ~ # /opt/cni/bin/loopback -v
CNI loopback plugin v0.9.0
```

Possible Workaround (for me right now) -> overwriting the loopback binary:
```
i-072da99539f0878c9 ~ # curl -qLO https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-arm64-v1.1.1.tgz
i-072da99539f0878c9 ~ # tar xfz cni-plugins-linux-arm64-v1.1.1.tgz
i-072da99539f0878c9 ~ # mv loopback /opt/cni/bin/
i-072da99539f0878c9 ~ # /opt/cni/bin/loopback -v
CNI loopback plugin v1.1.1
```

which then results in a successfull start:
```
  Normal  Scheduled  6s    default-scheduler  Successfully assigned default/nginx to i-072da99539f0878c9
  Normal  Pulling    6s    kubelet            Pulling image "nginx"
```

Thanks for the issue, hoping to see this resolved soon. Posting merely for anyone with the same issue.

**Comment by jayanthvn** [comment]
Binary version is updated with v1.11.2 release - https://github.com/aws/amazon-vpc-cni-k8s/pull/1997
