### ISSUE TITLE
Stochastic "connection refused" errors with pod liveness probes, unable to connect to or from container.

### ISSUE THREAD

**Issue by phyllisstein** [aws/amazon-vpc-cni-k8s#202]
I'm having some additional trouble with v1.2.1 of the plugin, both on a Kops cluster running Ubuntu 16.04 and on a Kops cluster running the default Debian image. Every so often, a pod's liveness probe will fail with a "connection refused" error. Additionally, when I `exec` into the bad pod, I'm unable to make connections to the outside world. I know that it's not a DNS failure because the queries aren't appearing in the DNS pods' logs and because direct pings to IP addresses also fail. And I'm reasonably confident that it's not an issue with the workloads, since the other pods in the StatefulSet spin up fine. The only potential pattern that I've been able to identify so far is that it seems to happen with pods whose `DeviceNumber` in the debug logging is not `0`.

I've collected troubleshooting logs for Ubuntu (http://go.phyl.li/15c463fd2259) and Debian (http://go.phyl.li/5663ba15e339). In both cases, the pod that was failing was called `anderson-read-replica-1`. Happy to furnish any additional color I can---I know this is a little vague---and grateful for any thoughts you might have.

**Comment by phyllisstein** [comment]
Just wanted to gently ping the maintainers to see if they've had a chance to look at this yet. Looks like a similar issue is affecting at least a couple of other users.

/cc @liwenwu-amazon

**Comment by phyllisstein** [comment]
Apologies, I think Chrome and Firefox were flagging it because the gzipped path contained `var/log`. Here are new archives without that prefix that work fine in both browsers:

* Ubuntu: <http://go.phyl.li/a95a972caa1d>
* Debian: <http://go.phyl.li/86483a5c3549>

**Comment by liwenwu-amazon** [comment]
@phyllisstein Thanks for providing the logs.  I have few questions:

* For `Ubuntu`:
  * Which Pod was having trouble? 
  * What's the Pod IP and name?
  * Can you ping `from` different node to this Pod IP?   If not, can you provide the node IP?
  * Can you ping `from` this Pod to the node you were using before? 
  * After running these tests, can you collect the logs again ?

**Comment by phyllisstein** [comment]
I think the glitching pod was called `anderson-read-replica-0`. I wound up tearing down the cluster because without the database read replicas there was no point in trying to deploy the rest of my workload.

That said, I believe I was able to reproduce the issue with a new cluster:

* Pod `anderson-read-replica-0` could not successfully perform its health checks.
* Pod IP was `172.20.70.159`, name was `pod-name=anderson-read-replica-0`, namespace was `staging`.
* Ping from a Busybox container (name: `bash-5968677879-w6776`; IP: `172.20.70.255`) to `172.20.70.159` was successful.
* Ping from within the failing pod was impossible to test because I couldn't reach the APT list sources to install `ping`.
* Logs from the node with the failing pod: <http://go.phyl.li/25d34c61ee5f>.

I'm going to leave this cluster in the air for a bit. If you need any additional debugging info, I'd be happy to provide it here; and if you'd like direct access to the cluster for deeper troubleshooting, just e-mail me at <daniel@daniel.sh> and I'll get you SSH keys and Kubernetes configs.

Thanks so much for looking into this, I really appreciate it.

**Comment by liwenwu-amazon** [comment]
@phyllisstein can you ping the failing pod from a different node?

**Comment by liwenwu-amazon** [comment]
@phyllisstein  I also noticed `"AWS_VPC_K8S_CNI_EXTERNALSNAT":true`.  Do you have external NAT setup correctly for pod `172.20.70.159`?

**Comment by phyllisstein** [comment]
That was a schoolboy error on my part. Normally the cluster sits behind an AWS NAT gateway, but this one did not. After removing that environment variable and reapplying the CNI's `DaemonSet` I was able to connect to the outside world from within the pod, so it seems as though I've been unable to reproduce the issue. On top of which, a full-scale production cluster that I spun up with Kops, Ubuntu, and v1.2.1 of the CNI plugin has also not produced the same failure state.

I'm going to go ahead and assume that this was a problem with something else in my infrastructure and close the ticket. Apologies for the wild goose chase---had the first few attempts not been so consistent across two different AMIs, I would've left it alone.
