### ISSUE TITLE
AWS_VPC_K8S_CNI_RANDOMIZESNAT: unbound variable

### ISSUE THREAD

**Issue by vgunapati** [aws/amazon-vpc-cni-k8s#2027]
**What happened**:
Upgrading CNI from 1.10.2 to 1.11.2 makes CNI crash with the following error 
AWS_VPC_K8S_CNI_RANDOMIZESNAT: unbound variable

**Attach logs**
```
{"level":"info","ts":"2022-07-08T21:14:14.630Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2022-07-08T21:14:14.631Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2022-07-08T21:14:14.646Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2022-07-08T21:14:14.647Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2022-07-08T21:14:16.654Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-07-08T21:14:18.660Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2022-07-08T21:14:18.678Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
/app/entrypoint.sh: line 182: AWS_VPC_K8S_CNI_RANDOMIZESNAT: unbound variable
```
**What you expected to happen**:

According to [DOC](https://github.com/aws/amazon-vpc-cni-k8s#aws_vpc_k8s_cni_randomizesnat) `AWS_VPC_K8S_CNI_RANDOMIZESNAT` default is `prng`. It should automatically set this default value and not crash 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): v1.21.13-eks-84b4fe6
- CNI Version 1.11.2
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.4.196-108.356.amzn2.x86_64

**Comment by jayanthvn** [comment]
Hi,

How did you upgrade the CNI? Since the variable is set by default in the manifest - https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.11/config/master/aws-k8s-cni.yaml#L181

**Comment by jayanthvn** [comment]
PR is safe to be merged. But wanted to confirm on how you upgraded? Since if the upgrade was just the image tag then that is not recommended since we would have introduced new env variables. Ideal way to upgrade is to apply the manifest shared on the release page.

**Comment by jayanthvn** [comment]
Thanks for confirming. PR lgtm.
