### ISSUE TITLE
Pods stuck in ContainerCreating due to pull error unauthorized

### ISSUE THREAD

**Issue by axelczk** [aws/amazon-vpc-cni-k8s#2030]
We recently switched our cluster to EKS 1.22 with managed node group and since we have sometime this error when container are created. We don't have a fix except replacing the node where the pod try to be scheduled. 

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to pull image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to pull and unpack image "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/pause:3.1-eksbuild.1": failed to resolve reference "602401143452.dkr.ecr.eu-north-1.amazonaws.com/eks/pause:3.1-eksbuild.1": pulling from host 602401143452.dkr.ecr.eu-north-1.amazonaws.com failed with status code [manifests 3.1-eksbuild.1]: 401 Unauthorized   
```

I don't know if it's the right place to ask for this. If this is not, please tell me where I can post this issue.

**Comment by axelczk** [comment]
I know I'm getting a 401. The real question is why when the node just started it's working and I can pull this image and after some days or hours, it's not working anymore ? 

I don't know which service is responsible for this.

**Comment by dotsuber** [comment]
Hi, I'm having this exactly issue too after upgrading EKS. Is there any solution to that?

**Comment by juris** [comment]
Just had the same issue and found this ticket.
In my case, pause image was gone after pruning unused images and it turns out that it [can not be downloaded](https://github.com/containerd/containerd/issues/6637) back by containerd.
So I had to manually download it.

I'm using BottlerocketOS, so it was not that trivial. Here's how to do it.
1. Get your aws ecs auth token first (did it with my aws access key / secret key on a laptop)
```shell
aws ecr get-login-password --region <your-region>
```
2. Login to the affected instance and get _crictl_
```shell
cd /tmp
yum install tar -y
curl -fsL -o crictl.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz
tar zxf crictl.tar.gz
chmod u+x crictl
```
3. Pull the pause image
```shell
./crictl --runtime-endpoint=unix:///.bottlerocket/rootfs/run/dockershim.sock pull --creds "AWS:TOKEN_FROM_STEP_1" XXXXX.dkr.ecr.XXXXXXX.amazonaws.com/eks/pause:3.1-eksbuild.1
```
Now you have that pause image in place, so pods should be able to start normally.

**Comment by axelczk** [comment]
> Hi, I'm having this exactly issue too after upgrading EKS. Is there any solution to that?

There is an error on their side on EKS node. You need to add this bootstrap extra arg:
'--pod-infra-container-image=602401143452.dkr.ecr.${var.region}.amazonaws.com/eks/pause:3.1-eksbuild.1'

Using this, the garbage collector will not remove the pause container and you will not have the need to pull the image.

**Comment by juris** [comment]
As far as I know, garbage collector takes only disk space into account. In my case, the server was running out of inodes, so I had to manually prune images.

**Comment by axelczk** [comment]
We have contacted the AWS support on our side, and after days of exchange and debugging this was the explanation we found. The garbage collector was pruning image on the node and removing also the pause container with others images. I still have the ticket somewhere and can check for the full explanation if necessary.

**Comment by dotsuber** [comment]
Hi, I'm having the same issue after upgrading EKS to 1.25. Is this solution still valid? I think this feature flag is deprecated.

> > Hi, I'm having this exactly issue too after upgrading EKS. Is there any solution to that?
> 
> There is an error on their side on EKS node. You need to add this bootstrap extra arg: '--pod-infra-container-image=602401143452.dkr.ecr.${var.region}.amazonaws.com/eks/pause:3.1-eksbuild.1'
> 
> Using this, the garbage collector will not remove the pause container and you will not have the need to pull the image.

**Comment by ddl-slevine** [comment]
Having the same issue in an EKS upgrade to 1.24

**Comment by interair** [comment]
Having the same issue in an EKS upgrade to 1.24, can anyone help me?

```
Aug 10 10:50:06  kubelet[3229]: E0810 10:50:06.304292    3229 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \ with CreatePodSandboxError: \"Failed to create sandbox for pod \\\: rpc error: code = Unknown desc = failed to get sandbox image \\\"602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5\\\": failed to pull image \\\"602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5\\\": failed to pull and unpack image \\\"602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5\\\": failed to resolve reference \\\"602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5\\\": pulling from host 602401143452.dkr.ecr.us-west-2.amazonaws.com failed with status code [manifests 3.5]: 401 Unauthorized\"" 
```

**Comment by hamdallahjodah** [comment]
any updates here same issue!!

**Comment by jdn5126** [comment]
@VikramPunnam @hamdallahjodah @interair @ddl-slevine I am not familiar with this issue, and it is not an issue with the VPC CNI, so I suggest opening an AWS support case to get help. That will be the fastest way to a resolution, and you can your findings here.

**Comment by ohrab-hacken** [comment]
I am have the same issue when upgrade to 1.29. Some node can download pause image, but some node cannot. So all pods no the node just hung in create state. Doesn't understand why pause image have 401 only some times.

**Comment by elvishsu66** [comment]
We also have this issue after upgrading to 1.29. Do we have a few good hints so I can start digging?

**Comment by nightmareze1** [comment]
I have the same issue with EKS 1.29 :(

**Comment by pjanouse** [comment]
I've observed the same after v1.29 upgrade today too. Tried to re-place an affected compute node with the fresh one and it seems helped (at least for awhile). So far so good...

**Comment by nightmareze1** [comment]
I think the problem is happening after 12hs when the session token expires and curiously the instance where I tested it didn't have any inodes/space problems.

**Comment by cartermckinnon** [comment]
If this is happening on the EKS AMI, can you open an issue in our repo so we can look into it?

**Comment by ohrab-hacken** [comment]
--pod-infra-container-image flag is set on kubelet. I found that my disk on node really become full after some time and kubelet image garbage collector delete pause image. So, instead of delete different images, it deletes pause image. After pause image deleted, node doesn't work.
I found the reason of full disk. In my case, I have ttlSecondsAfterFinished: 7200 for dagster jobs, and it consume all disk space. I've changed it to ttlSecondsAfterFinished: 120 and jobs cleaned up more frequently and we don't have this issue any more.
It's strange cause I didn't have this issue on 1.28, and I didn't change any Dagster configuration between version upgrade. My guess, it kubelet image garbage collector works different in 1.28 and 1.29.

**Comment by jdn5126** [comment]
@ohrab-hacken `--pod-infra-container-image` was deprecated in k8s 1.27. As I understand it, the container runtime will prune the image unless it is marked as `pinned`. From the EKS 1.28 AMI, it does seem like the pause image is not pinned for some reason. @cartermckinnon do you know if it should be?

**Comment by jdn5126** [comment]
This issue is being discussed at https://github.com/awslabs/amazon-eks-ami/issues/1597

**Comment by avisaradir** [comment]
> > Is there any new progress solving this matter?
> 
> Did you follow the issue I linked to? This issue is in the EKS AMI, not the VPC CNI, so short and long-term resolutions are being discussed there

I will take another look at that.

**Comment by ForbiddenEra** [comment]
Just started running into this today?

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/pause:3.5": failed to pull image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/pause:3.5": failed to pull and unpack image "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/pause:3.5": failed to resolve reference "602401143452.dkr.ecr.ca-central-1.amazonaws.com/eks/pause:3.5": unexpected status from HEAD request to https://602401143452.dkr.ecr.ca-central-1.amazonaws.com/v2/eks/pause/manifests/3.5: 401 Unauthorized
```
