### ISSUE TITLE
Add metrics for Describe calls and other EC2 API Calls in CNI Metrics helper

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2035]
**What would you like to be added**:
CNI Metrics helper today includes metrics around ipamd datastore - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L177-L230. It would be good to add metrics for all the EC2 calls made by IPAMD and expose it with CNI Metrics helper.

**Why is this needed**:
This would give better UX and easy access to number of EC2 calls made per node.

**Comment by sidewinder12s** [comment]
Currently users have to contact AWS Support to get these enabled on the AWS side rather than directly from the CNI: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/monitor.html

**Comment by jayanthvn** [comment]
2142 is merged.
