### ISSUE TITLE
Connect RDS on EKS pod sometimes failed

### ISSUE THREAD

**Issue by Haebuk** [aws/amazon-vpc-cni-k8s#2046]
**What happened**:

eks cluster and rds (mysql) cluster are in **same** vpc.
I added my eks security group(eks-cluster-sg-MYCLUSTERNAME-*) to rds security group's inbound rule (port 3306)
I found rds connection sometimes succeed but sometimes failed. (it is timeout error)
I set timeout seconds to 300s, so I think it's not matter.
It has some weird pattern. When connection success, it tooks < 1 sec or it tooks more than 2 minutes. (very fast or long)
I tested in local, there is no problem (connection tooks < 1sec). but same code in pod shows above things.

I don't know why connection sometimes success, sometimes failed. how to fix it? any ideas?
thank you.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.22.0
- CNI Version

**Comment by jayanthvn** [comment]
@Haebuk - Can you please open a support case? Support team or the service team will be able to verify if it is the VPC issue or the RDS issue. If CNI pod networking is an issue we should see the failure always.

**Comment by jayanthvn** [comment]
Hi, please open a support case and VPC flow logs will be useful when the timeout happens.

**Comment by Haebuk** [comment]
ok, I will. thank you :)
