### ISSUE TITLE
ip rule leaked under some conditions 

### ISSUE THREAD

**Issue by cdemonchy** [aws/amazon-vpc-cni-k8s#2048]
Hi,

**What happened**:

Sometimes the ip rule  associated to a pod are not deleted when the pod is deleted. The leaked rules are never deleted but the ip is free in the ipam.

The ip can be reallocated on another node in the cluster. When this happens, the pods on the node with the leaked rules can't reach the pod with the reallocated ip. 

We've the case when cluster autoscaler fails to evict a node : 
- cluster autoscaler wants to evict a node
- pods on the nodes are stopped calling the cni plugin. The pod `aws-node` is stopped and restart quickly. 
- for some pods the cni plugin can't call ipamd before the container is deleted. In this case the rule are leaked. 
- After 2 minutes,  as it didn't success to move all the pod quickly (due to a very conservative pdb). The eviction is stopped and the node came back in the pool. ([cluster austoscaler faq](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-work-with-poddisruptionbudget-in-scale-down))

**Attach logs**

The log for a pod during the delete phase : 
```
{"level":"debug","ts":"2022-07-31T11:35:11.678Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Prev Result: &{0.4.0 [{Name:eni054dbc5e65c Mac: Sandbox:} {Name:eth0 Mac: Sandbox:/proc/12533/ns/net}] [{Version:4 Interface:0xc000270280 Address:{IP:10.109.167.233 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\n"}
{"level":"info","ts":"2022-07-31T11:35:11.678Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Received CNI del request: ContainerID(2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Netns(/proc/12533/ns/net) IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod-annonce;K8S_POD_NAME=XXX-84c9dd9cc5-5s86q;K8S_POD_INFRA_CONTAINER_ID=2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"prevResult\":{\"cniVersion\":\"0.4.0\",\"interfaces\":[{\"name\":\"eni054dbc5e65c\"},{\"name\":\"eth0\",\"sandbox\":\"/proc/12533/ns/net\"}],\"ips\":[{\"version\":\"4\",\"interface\":1,\"address\":\"10.109.167.233/32\"}],\"dns\":{}},\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"error","ts":"2022-07-31T11:35:11.678Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Error received from DelNetwork gRPC call for container 2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused\""}
{"level":"debug","ts":"2022-07-31T11:35:12.404Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Prev Result: &{0.4.0 [{Name:eni054dbc5e65c Mac: Sandbox:} {Name:eth0 Mac: Sandbox:/proc/12533/ns/net}] [{Version:4 Interface:0xc0002e0280 Address:{IP:10.109.167.233 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\n"}
{"level":"info","ts":"2022-07-31T11:35:12.404Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Received CNI del request: ContainerID(2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Netns() IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod-annonce;K8S_POD_NAME=XXX-84c9dd9cc5-5s86q;K8S_POD_INFRA_CONTAINER_ID=2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"prevResult\":{\"cniVersion\":\"0.4.0\",\"interfaces\":[{\"name\":\"eni054dbc5e65c\"},{\"name\":\"eth0\",\"sandbox\":\"/proc/12533/ns/net\"}],\"ips\":[{\"version\":\"4\",\"interface\":1,\"address\":\"10.109.167.233/32\"}],\"dns\":{}},\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"error","ts":"2022-07-31T11:35:12.404Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Error received from DelNetwork gRPC call for container 2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused\""}
{"level":"debug","ts":"2022-07-31T11:35:13.476Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Prev Result: &{0.4.0 [{Name:eni054dbc5e65c Mac: Sandbox:} {Name:eth0 Mac: Sandbox:/proc/12533/ns/net}] [{Version:4 Interface:0xc00027a2e0 Address:{IP:10.109.167.233 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\n"}
{"level":"info","ts":"2022-07-31T11:35:13.476Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Received CNI del request: ContainerID(2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Netns() IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod-annonce;K8S_POD_NAME=XXX-84c9dd9cc5-5s86q;K8S_POD_INFRA_CONTAINER_ID=2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"prevResult\":{\"cniVersion\":\"0.4.0\",\"interfaces\":[{\"name\":\"eni054dbc5e65c\"},{\"name\":\"eth0\",\"sandbox\":\"/proc/12533/ns/net\"}],\"ips\":[{\"version\":\"4\",\"interface\":1,\"address\":\"10.109.167.233/32\"}],\"dns\":{}},\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"error","ts":"2022-07-31T11:35:13.477Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Error received from DelNetwork gRPC call for container 2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused\""}
{"level":"debug","ts":"2022-07-31T11:36:10.189Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Prev Result: &{0.4.0 [{Name:eni054dbc5e65c Mac: Sandbox:} {Name:eth0 Mac: Sandbox:/proc/12533/ns/net}] [{Version:4 Interface:0xc0002a0a70 Address:{IP:10.109.167.233 Mask:ffffffff} Gateway:<nil>}] [] {[]  [] []}}\n"}
{"level":"info","ts":"2022-07-31T11:36:10.189Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Received CNI del request: ContainerID(2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Netns() IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod-annonce;K8S_POD_NAME=XXX-84c9dd9cc5-5s86q;K8S_POD_INFRA_CONTAINER_ID=2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"prevResult\":{\"cniVersion\":\"0.4.0\",\"interfaces\":[{\"name\":\"eni054dbc5e65c\"},{\"name\":\"eth0\",\"sandbox\":\"/proc/12533/ns/net\"}],\"ips\":[{\"version\":\"4\",\"interface\":1,\"address\":\"10.109.167.233/32\"}],\"dns\":{}},\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"info","ts":"2022-07-31T11:36:10.190Z","caller":"routed-eni-cni-plugin/cni.go:303","msg":"Container 2fffde85e1f7d2009a5a7b6bf2a8ea011a26aced26faf2ceea4123d14b655f69 not found"}
```

We can see 3 attempts with a connection refused when connecting to ipamd. The last attempt fails has the container has been removed. 

When looking at the rule tables, the rules associated to the ip are still present. 

```
# ip rule | grep 10.109.167.233
from all to 10.109.167.233 lookup main 
from 10.109.167.233 lookup 2
```

I'll send the complete support tarball by mail. 

**What you expected to happen**:
We expect that the rules are removed when a container is stopped. 

**Anything else we need to know?**:

When looking at the del function [del](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/routed-eni-cni-plugin/cni.go#L306), the logic seems to be : 
-  [tryDelWithPrevResult](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L325): try to clean the ip but only for pod with a security group attached. 
- [call the ipamd](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L348)
- [do the clean](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L405)

In our case, during the first call the function `tryDelWithPrevResult` didn't do anything as the code seems to only handle pod with a security group attached. We're not attaching security group to the pod we're using `Individual IP addresses assigned to network interface` mode. 

During the last call, the call to ipamd seems to succeed the cleaning from the del function is not called : [cni.go#L405](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L405) as we've a container not found error before : [cni.go#L364](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L364). 

Maybe it's possible to do the clean in the `tryDelWithPrevResult` like for branch eni ? 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version : v1.11.2

**Comment by jayanthvn** [comment]
Hi @cdemonchy , We will land here [cni.go#L364](https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L364). because of https://github.com/aws/amazon-vpc-cni-k8s/blob/21f39eeca2d8a19dcd5069a8ee7811f5a924b16e/cmd/routed-eni-cni-plugin/cni.go#L360 which is because the IPAMD state file is missing the container. One possible cause is, when IPAMD started in the last retry, the container was already deleted so IPAMD marked it as stale, not added to state file and IP is free. Now when CNI tries to reach IPAMD the container is not available in the state file so returned unknown pod error. I can confirm this once we have the logs. I think one solution we can do is in the plugin, when there is a new add we delete if any stale rule is present and then program the new rule. We do similarly for SGPP pods clan rules.

**Comment by cdemonchy** [comment]
I forgot to send the log, I've just sent them.

**Comment by jayanthvn** [comment]
Ideally when the aws-node restarts we will have to clean up the rules associated with free IPs if one exists.

**Comment by cdemonchy** [comment]
We managed to mitigate the issue by updating cluster auto scaler configuration to not evict daemonset pods. We didn't have leaked rules since the update. 

aws-node is not evicted by cluster autoscaler and don't restart. This confirm that the problem occurs when pod are deleted during a restart of aws-node. 

Regards,

**Comment by jdn5126** [comment]
@cdemonchy were you previously enabling daemonset eviction? It should be disabled by default

**Comment by cdemonchy** [comment]
Hi @jdn5126 

The daemonset eviction has been enabled automatically when we've upgraded cluster autoscaler from v1.20.2 and to v1.21.2 

To solve our issue we've upgraded to cluster autoscaler v1.21.3 and added the flag `--daemonset-eviction-for-occupied-nodes=false`

**Comment by jdn5126** [comment]
Closing as PR has merged
