### ISSUE TITLE
Multiple interfaces and Master Secondary IP addresses 

### ISSUE THREAD

**Issue by osobh** [aws/amazon-vpc-cni-k8s#205]
Using KOPS to deploy cluster with AWS CNI ENI and one of the 3 masters that gets deployed picks up multiple secondary addresses, and here are the error logs:
CNI = 1.2.1

--node-ip (primary interface) on all kubeletes

-----------------------------------------------------------------------------------------------------
**aws-node:**

aws-node-qvgqj aws-node ERROR: logging before flag.Parse: W1018 07:22:00.082866      11 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

----------------------------------------------------------------------------------------------------
**ec2-srcdst:**

8s-ec2-srcdst-845468ffc8-9fw8v k8s-ec2-srcdst   status code: 400, request id: 7c6ad53e-c305-4e71-9a52-b20a7ba6b70d
k8s-ec2-srcdst-845468ffc8-9fw8v k8s-ec2-srcdst E1018 07:44:28.168853       1 srcdst_controller.go:87] Fail to disable src dst check for EC2 instance: i-06115f8518c54458a; InvalidInstanceID: There are multiple interfaces attached to instance 
k8s-ec2-srcdst-845468ffc8-9fw8v k8s-ec2-srcdst E1018 07:44:28.168853       1 srcdst_controller.go:87] Fail to disable src dst check for EC2 instance: i-06115f8518c54458a; InvalidInstanceID: There are multiple interfaces attached to instance 

------------------------------------------------------------------------------------------------------------------------------------------
EC2-Roles for Kubelets:

"ec2:DescribeSubnets"
 "ec2:AttachNetworkInterface"
 "ec2:AssignPrivateIpAddresses"
 "ec2:UnassignPrivateIpAddresses"
 "ec2:CreateNetworkInterface"
 "ec2:DescribeNetworkInterfaces"
 "ec2:DetachNetworkInterface"
 "ec2:DeleteNetworkInterface"
 "ec2:ModifyNetworkInterfaceAttribute"
 "ec2:DescribeVpcs"
 "ec2:DescribeVpcPeeringConnections"

Let me know if any other logging will help with digging into this issue.

**Comment by osobh** [comment]
When we deploy the same cluster but use Calico as the CNI we don't see these issues.

**Comment by thestrongenough** [comment]
+1 on this. We are seeing the same issue. Any updates on this?

**Comment by thomasvnoort** [comment]
What version of kops are you running? 

We have seen similar errors after upgrading kops from 1.8 to 1.10. We found out that kops 1.10 [no longer](https://github.com/kubernetes/kops/commit/106eb3861c714543bf61da7d335dec0e41b5ed4d#diff-01d8d5b5d9dd00bd56b45313c256581d) installs [k8s-ec2-dst](https://github.com/ottoyiu/k8s-ec2-srcdst) with the CNI plugin. So after manually deleting everything related to k8s-ec2-srcdst these errors went away (obviously) and everything still worked. 

The reason for removing this in kops 1.10 is unclear from the PR, but maybe the author @ripta can explain why this is no longer needed?

**Comment by mogren** [comment]
Is this still an issue? @osobh

**Comment by osobh** [comment]
Not an issue anymore, thank you !
