### ISSUE TITLE
Release notes references incorrect URL for applying release

### ISSUE THREAD

**Issue by mkohner-repay** [aws/amazon-vpc-cni-k8s#2067]
The release notes for amazon-vpc-cni-k8s releases have the wrong url for applying the release. 

See [v1.11.2](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.11.2) 

*To apply this release:*

`kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.11/config/master/aws-k8s-cni.yaml`

The URL will pull the latest version of `aws-k8s-cni.yaml` from the `release-1.11` branch, which currently points to the version `v1.11.4-rc1` image. 

URL should be of the form `https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/{$tagged_version}/config/master/aws-k8s-cni.yaml` e.g.  `https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.11.2/config/master/aws-k8s-cni.yaml`

**Comment by jayanthvn** [comment]
Yes it should have been based of the tag. I will update it. Thanks.

**Comment by jayanthvn** [comment]
I have updated the release page for release-1.10 and release-1.11. Except for v1.10.3 release since the manifest was updated after tagging.
