### ISSUE TITLE
Support `ecr-fips` endpoint in Helm chart

### ISSUE THREAD

**Issue by stevehipwell** [aws/amazon-vpc-cni-k8s#2070]
**What would you like to be added**:
I'd like to be able to use the `ecr-fips` [ECR endpoint](https://docs.aws.amazon.com/general/latest/gr/ecr.html) without needing to completely override the image values. My prefered implementation would be to add `image.repository` to combine with `image.tag`, as found in the other AWS charts, with a lower precedence than `image.override`.

**Why is this needed**:
Having to update the image version in sync with the chart version when using the image override has the potential for error and is unnecessary toil.

**Comment by jayanthvn** [comment]
@stevehipwell - we are happy to take PR for this and review if you have bandwidth.

**Comment by stevehipwell** [comment]
@jayanthvn I'll open a PR next week when I'm back in the office.

**Comment by stevehipwell** [comment]
Sorry I am planning on opening a PR, just been crazy busy.
