### ISSUE TITLE
Ability to set VPC CNI configuration per instance type or per ASG

### ISSUE THREAD

**Issue by olileach** [aws/amazon-vpc-cni-k8s#2072]
**What would you like to be added**:

Currently, MINIMUM_IP_TARGET and WARM_IP_TARGET configuration for the VPC CNI is a global setting and is applied to all instances deployed via kubernetes, regardless of whether these nodes are deployed via mechanisms like the Kube API, CFN, CloudFormation, EKSCTL, Cluster Autoscaler or Karpenter etc.

However, these global settings do not make sense when instance types vary. For example, MINIMUM_IP_TARGET for a m5.large instance may need to be different compared to an m5.24xlarge instance, simple because the m5.24xlarge instance can run more pods than an m5.large instance type so the MINIMUM_IP_TARGET should be different.

I would like to have the ability to set MINIMUM_IP_TARGET and WARM_IP_TARGET for either specific instance types or for ASG that are configured with different instance families but the same instance type (required when using Cluster Autosacler, for example).

If there isn't a specific configuration for an instance of an ASG, there should be a default fallback configuration. 

An example configuration could be a key value pair for 

MINIMUM_IP_TARGET = 10
INSTANCE_TYPE_MINIMUM_IP_TARGET =  { "m5.large": 5, "m5.24xlarge": 20}
ASG_NODE_GROUP_MINIMUM_IP_TARGET = { "my_node_group" : 15}

If an m5.large instance type was deployed, the MINIMUM_IP_TARGET would equal 5
If an m5.24xlarge instance type was deployed, the MINIMUM_IP_TARGET would equal 20
If an m5.16xlarge instance type was deployed, the MINIMUM_IP_TARGET would equal 10
If an m5.8xlarge instance type was deployed using my_node_group ASG, the MINIMUM_IP_TARGET would equal 15

The config example above can also be used to applied to the WARM_IP_TARGET configuration setting.

**Why is this needed**:

Different instance types can run different numbers of pods, therefore the MINIMUM_IP_TARGET can and should be different. Smaller instance types could have a smaller MINIMUM_IP_TARGET value whereas larger instance types could have a larger MINIMUM_IP_TARGET value. 

This does a couple of things. Make IP usage more efficient based on different node types as we can have different MINIMUM_IP_TARGET settings for different instance types and it also reduces the number of API calls necessary to allocate or deallocate private IPs, especially when using a low value for MINIMUM_IP_TARGET and a large instance type. 

The same applies to WARM_IP_TARGET.

Lastly, the reason why I want configuration options for NODE GROUPS and INSTANCE TYPES is because my nodes can be scaled using Cluster Autoscaler (which should have all instance types of the same type but we need to make sure all instance types can run the same number of pods) or by Karpenter, which can deploy any instance type based on what it can allocate at the point of requesting more EC2 instances.

Thanks - please comment on above logic or suggest different configuration options as per your use case.

**Comment by jayanthvn** [comment]
Hi,

Thanks for filing the feature request, we already have one open - https://github.com/aws/amazon-vpc-cni-k8s/issues/216

Thanks!

**Comment by olileach** [comment]
The https://github.com/aws/amazon-vpc-cni-k8s/issues/216 looks like it is closed. I've also logged a feature request here, too: https://github.com/aws/containers-roadmap/issues/1834

**Comment by jayanthvn** [comment]
Thanks @olileach. As discussed offline we will track the issue on containers roadmap.

**Comment by jayanthvn** [comment]
@olileach - we will provide update on the container-roadmap issue. Closing the issue.
