### ISSUE TITLE
How to set separate outgoing (and possibly incoming) IP address for pods?

### ISSUE THREAD

**Issue by exander77** [aws/amazon-vpc-cni-k8s#2078]
I want some of the pods to use different outgoing IP. I have set up separate ElasticIP and Gateway, how can I set pods to use it?
Some ability to set route table for pod/namespace?

**Comment by jayanthvn** [comment]
@exander77 - If I understand correctly you want to attach your own ENIs/secondary IPs and pods should pick them? If so you can set this env variable - https://github.com/aws/amazon-vpc-cni-k8s#disable_network_resource_provisioning-v191. Then when ENIs and IPs are attached, those IPs will be picked from IPAMD and used for pod IPs and route tables will be programmed.

**Comment by exander77** [comment]
> @exander77 - If I understand correctly you want to attach your own ENIs/secondary IPs and pods should pick them? If so you can set this env variable - https://github.com/aws/amazon-vpc-cni-k8s#disable_network_resource_provisioning-v191. Then when ENIs and IPs are attached, those IPs will be picked from IPAMD and used for pod IPs and route tables will be programmed.

I want my pod (several pods) to get separate outgoing IP, i.e. route the traffic through a different interface. I am unsure how could I use that variable? I would assume I somehow attach my ElasticIP to the cluster and to the pod.

**Comment by exander77** [comment]
> We would need more insights on the use case. Are you available on k8s slack? We can connect and setup a call.

If it is this: https://communityinviter.com/apps/kubernetes
Then I just joined.

Basically, I need separate outgoing (and possibly incoming) IP for traffic of a pod (pods).

**Comment by jayanthvn** [comment]
/not stale

@exander77 - Yes thats the right channel.
