### ISSUE TITLE
How to calculate IP address usage at cluster level ?

### ISSUE THREAD

**Issue by ishabatraa** [aws/amazon-vpc-cni-k8s#2085]
We came across one cluster where metric value for awscni_assigned_ip_addresses is greater than awscni_total_ip_addresses. See screenshot below : 

<img width="1616" alt="Screenshot 2022-09-13 at 11 34 17 AM" src="https://user-images.githubusercontent.com/113414411/189822696-dbe804b2-c63a-41be-aef5-3e7771a5847c.png">

As per the definition assigned_ip_addresses is the number of IP addresses attached to the pod while awscni_total_ip_addresses is the total ip address allocated to ENI. 
Want to understand how can the IP's attached to pod more than the total IP's of the cluster ?

Also, if you can guide how can we monitor the IP address usage of cluster? 
Right now, we are using formula:
 sum(awscni_assigned_ip_addresses/awscni_total_ip_addresses)*100 
but don't think it's giving the proper result.

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
@ishabatraa - What is your CNI version? Have you enabled prefix delegation? Also can you please share the log collector bundle? 

You can run the below command on one of the nodes.
```
sudo bash /opt/cni/bin/aws-cni-support.sh
```

**Comment by ishabatraa** [comment]
We are using v1.10.2. 
ENABLE_PREFIX_DELEGATION is set to false.
Attached bundle.
[cnibundle.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/9564370/cnibundle.zip)
[logs-1.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/9564377/logs-1.zip)
[kube-system_kube-proxy-4jbl2_5a1bba3e-bb6f-4fc8-b74a-5765820e8101.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/9564378/kube-system_kube-proxy-4jbl2_5a1bba3e-bb6f-4fc8-b74a-5765820e8101.zip)

[aws-routed-eni.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/9564379/aws-routed-eni.zip)

**Comment by ishabatraa** [comment]
Hey Jayanth, Any update on this?

**Comment by jayanthvn** [comment]
I did check few sample logs and didn't see any skew -

```
"level":"debug","ts":"2022-09-14T07:57:45.852Z","caller":"ipamd/ipamd.go:2045","msg":"Current warm IP stats: target: 1, total: 14, assigned: 13, available: 1, cooldown: 0, short: 0, over 0"}
```

Did you at any point toggle between prefix delegation and secondary mode?
