### ISSUE TITLE
IPAM-D fails to start on cluster with Custom Networking & Prefix Delegation enabled

### ISSUE THREAD

**Issue by mikeinton** [aws/amazon-vpc-cni-k8s#2086]
**What happened**:
New EKS worker nodes from a managed node group never becomes ready, and the aws-node daemonset pod enters CLBO stuck at "Retrying waiting for IPAM-D".

Currently getting help via k8s-awscni-triage@amazon.com distro group so opening up this issue here as a formality.

Also have an AWS Support ticket where it seems that we've been ghosted, no response in 5+ days Case 10736510071.

Output of `sudo bash /opt/cni/bin/aws-cni-support.sh` on a problematic node has been emailed to k8s-awscni-triage@amazon.com yesterday with the case number mentioned above in the Subject line.

Our deployment is roughly based off of this EKS Blueprints example [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/vpc-cni-custom-networking/main.tf) with the following exceptions.
- We've removed the custom AMI bits in favor of using the default AMI provided by EKS.  [Here](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/vpc-cni-custom-networking/main.tf#L76-L96) is most of what we removed as I recall reading in one of the AWS blogs that max pod calculations no longer have to performed manually when using the latest AMI's.
- We're deploying to existing VPC's and Subnets, where as this EKS Blueprint example creates it's VPC level dependencies and works without any issues in our testing.  Something seems to break when we attempt to utilize Custom Networking in our VPC/Subnets specifically that we can't quite figure out.  Another thing to note is that in our existing VPC, we're using custom DNS settings in our DHCP optionsets vs the default AmazonProvidedDNS.  The SystemsManager EKS Worker Node troubleshooting tool seems to complain that we're not using AmazonProvidedDNS but I'm not entirely sure how much that matters.

**Environment**:
- Kubernetes version (use `kubectl version`):  GitVersion:"v1.23.7-eks-4721010"
- CNI Version:  amazon-k8s-cni:v1.11.3-eksbuild.1
- OS (e.g: `cat /etc/os-release`):  "Amazon Linux"
- Kernel (e.g. `uname -a`):  5.4.209-116.363.amzn2.x86_64

**Additional logs**:
[ipamd.log](https://github.com/aws/amazon-vpc-cni-k8s/files/9560333/ipamd.log)
[aws-node.log](https://github.com/aws/amazon-vpc-cni-k8s/files/9560334/aws-node.log)

**Comment by jayanthvn** [comment]
@mikeinton - Looks the logger is unable to instantiate and causing restart. There were changes to logger made in 1.11.3. Will try to repro internally and get back to you.

```
{"level":"info","ts":"2022-09-08T17:20:54.912Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2022-09-08T17:20:54.912Z","caller":"eniconfig/eniconfig.go:61","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2022-09-08T17:20:54.918Z","caller":"aws-k8s-agent/main.go:28","msg":"Starting L-IPAMD   ..."}
{"level":"info","ts":"2022-09-08T17:20:54.919Z","caller":"aws-k8s-agent/main.go:39","msg":"Testing communication with server"}
```

Can you please try 1.11.2 ?

**Comment by mikeinton** [comment]
@jayanthvn - No change after switching to `amazon-k8s-cni:v1.11.2-eksbuild.1`

**Comment by jayanthvn** [comment]
I don't think my above assumption about logger is correct, let me try locally and get back.

**Comment by jayanthvn** [comment]
I see while trying to access metadata (https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.11.3/pkg/awsutils/awsutils.go#L603) there is no reply and eventually aws-node is restarting -

```
{"level":"debug","ts":"2022-09-08T17:20:56.995Z","caller":"awsutils/awsutils.go:592","msg":"Found ENI: eni-02549061a341f807c, MAC 02:f0:65:9a:c1:63, device 0"}
```
Around 2 minutes there is a wait - 
```
{"level":"info","ts":"2022-09-08T17:22:34.976Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2022-09-08T17:22:34.976Z","caller":"eniconfig/eniconfig.go:61","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2022-09-08T17:22:34.982Z","caller":"aws-k8s-agent/main.go:28","msg":"Starting L-IPAMD   ..."}
```
On the node can you please share the below o/p?

eni-02549061a341f807c, MAC 02:f0:65:9a:c1:63
```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://19.254.169.254/latest/meta-data/network/interfaces/macs/02:f0:65:9a:c1:63/mac

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://19.254.169.254/latest/meta-data/network/interfaces/macs/02:f0:65:9a:c1:63/device-number

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKE9.254.169.254/latest/meta-data/network/interfaces/macs/02:f0:65:9a:c1:63/ipv4-prefix

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKE9.254.169.254/latest/meta-data/network/interfaces/macs/02:f0:65:9a:c1:63/interface-id
```

If you are not comfortable sharing here, please email it to [k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)

**Comment by mikeinton** [comment]
@jayanthvn So far it's looking like the first one is going to time out.
```
[root@ip-10-112-77-56 /]# TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` && curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://19.254.169.254/latest/meta-data/network/interfaces/macs/02:f0:65:9a:c1:63/mac
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0  84977      0 --:--:-- --:--:-- --:--:-- 56000
*   Trying 19.254.169.254:80...
```

**Comment by mikeinton** [comment]
Ah I see, I think your paste had a typo `19.254.169.254` retrying with valid IP.

**Comment by jayanthvn** [comment]
Ahh right, I think while copying it got truncated. Correcting it.

**Comment by mikeinton** [comment]
All but /ipv4-prefix worked, sending output to [k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)

**Comment by jayanthvn** [comment]
Local repro with PD and custom networking works fine.

Reg this - "Something seems to break when we attempt to utilize Custom Networking in our VPC/Subnets specifically that we can't quite figure out."

You mean new VPC and subnet with PD and custom networking works fine? You are seeing issues only with existing VPCs and subnets?

**Comment by mikeinton** [comment]
@jayanthvn - Correct, new VPC and new Subnets everything works fine.  When we try to fit an EKS cluster enabled with custom networking and prefix delegation into our existing VPC/Subnets, this is where we start seeing this problem.

So far on our end, all the preliminary checks seem to be in order, aws-node daemonset has the updated envars, the eniConfig custom resource in the EKS cluster is created with a valid name of availability zones and each eniConfig has the correct subnets according to it's AZ and security groups associated with the EKS cluster.

**Comment by jayanthvn** [comment]
Thanks @mikeinton . Have you tried without custom networking and PD enabled on existing VPC/subnets? Just want to make sure if PD is enabled at VPC level.

**Comment by mikeinton** [comment]
@jayanthvn - I have not, was not aware PD needed to be enabled at the VPC/Subnet levels.  If that is the case, that could make sense as we are deploying to old VPC/Subnets that were created years ago prior to PD being enabled by default (which seems like it could be the case on newly created VPC's?)

How would I confirm/check to be sure PD is enabled?  I'm not seeing anything relevant on the VPC or Subnet via the AWS Console UI.

Also to note is that for a short period of time, one of these clusters worked as expected.  Custom Networking was enabled and pod IP assignment was coming from our secondary CIDR subnets.  Then as nodes were cycled out and replacements came in, it stopped working.  We tried to deploy a new EKS cluster to see if we could reproduce that behavior and this one never worked.

**Comment by jayanthvn** [comment]
Yeah that might be the case but we will reach out to VPC team and confirm on that.

**Comment by mikeinton** [comment]
@jayanthvn - Thanks for the debugging call with the rest of the team today, please feel free to close this issue as per the following summary.

- Calls to IMDS and EC2 from the EKS node worked as expected
- aws-node daemonset liveness probe and initialDelaySeconds config increased to prevent restarts/CLBO
- aws-node daemonset pod would continue to log
```
{"level":"info","ts":"2022-09-14T21:21:38.325Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
```
- However now the IPAM log on the EC2 node started to log the following error (note that in original config when kubelet would restart the failed aws-node container due to failed liveness, we never actually got to the point of seeing this error)
```
{"level":"error","ts":"2022-09-14T20:49:25.135Z","caller":"ipamd/ipamd.go:463","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-032f2110640c9769b]: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-west-2.amazonaws.com"
```
- Netcat to regional STS fails and returns private IP's instead of the expected public endpoint for STS
```
[root@<redacted>aws-routed-eni]# nc -vz sts.us-west-2.amazonaws.com 443
Ncat: Connection to <redacted> failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection to <redacted> failed: Connection timed out.
Ncat: Trying next address...
Ncat: Connection timed out.
```
- Checked VPC --> Endpoints and found that another team recently created a private DNS endpoint for `https://sts.us-west-2.amazonaws.com` which effectively hijacked our DNS calls to STS in our impacted VPC
- Current fix was to update the security group on the new privateDNS endpoint for STS to allow access to our EKS nodegroups. Long term fix may be to remove the private endpoint for STS unless it is absolutely required

**Comment by jayanthvn** [comment]
@mikeinton - Glad to know issue is fixed :)
