### ISSUE TITLE
Encrypt in-cluster pod traffic in EKS using AWS VPC CNI 

### ISSUE THREAD

**Issue by nayanen** [aws/amazon-vpc-cni-k8s#2087]
**What would you like to be added**:

Raising the feature at AWS VPC cni level to have a mechanism to encrypt the traffic between pods in EKS. 

The current option available is to make use of Nitro instances where the communication between these Nitro instance classes, when the instances are located within the same VPC, is fully encrypted using AES at line-rate speeds. By utilizing these encryption-capable Nitro instance classes for our Kubernetes nodes, we get inter-node traffic encryption “for free”, without layering on new software or having to compromise on performance. There is a similar [feature](https://projectcalico.docs.tigera.io/security/encrypt-cluster-pod-traffic) which has been developed with calico by enabling WireGuard helps in Host-to-host encryption for pod traffic. 

**Why is this needed**:
We have seen some industries where there are higher security requirements when it comes to data transfer.

**Comment by jayanthvn** [comment]
@nayanen - Ideally it is not the responsibility of the CNI to handle this. Can you please open a request here - https://github.com/aws/containers-roadmap/. Team will evaluate and get back on the component and provide timelines as we plan the roadmap.

**Comment by haouc** [comment]
Since this is out of the scope of VPC CNI, can you open the feature request in the roadmap as jayanthvn@ suggested? We are closing the issue.
