### ISSUE TITLE
Images missing from ap-east-1

### ISSUE THREAD

**Issue by william00179** [aws/amazon-vpc-cni-k8s#2098]
Hi, 

I am trying to deploy the chart in Hong Kong ap-east-1 and am getting a not found back from ECR. Same deployment is currently working perfectly in other regions so I suspect the containers are not being replicated to ap-east-1

**Comment by achevuru** [comment]
Can you share the exact image path+tag that is failing for you?

**Comment by luthermonson** [comment]
@achevuru I had something similar from a QA tester today, we couldn't find 

```
602401143452.dkr.ecr.ap-east-1.amazonaws.com/amazon-k8s-cni-init:v1.11.2
```

All that was set in values.yaml was init.image.region image.region to ap-east-1 and we get this image backoff error...

<img width="1591" alt="Screenshot 2022-10-04 at 10 38 52 PM" src="https://user-images.githubusercontent.com/1616909/194375038-47bbcd2c-48c4-43ba-aa6d-75d67b7ac26d.png">

**Comment by jdn5126** [comment]
@luthermonson `ap-east-1` uses a different account. You can find the correct account for the region from https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html

**Comment by luthermonson** [comment]
thanks @jdn5126 ! didn't know that
