### ISSUE TITLE
Source Environment Variables from ConfigMap

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-cni-k8s#2102]
**What would you like to be added**:
CNI environment variables to be sourced from ConfigMap

**Why is this needed**:
To allow environment variables to persist during CNI upgrade. Current mechanism is to run `kubectl set env` during upgrade.

**Comment by jdn5126** [comment]
Reference #1088

**Comment by dschunack** [comment]
Still waiting in this feature

**Comment by dschunack** [comment]
Still waiting on this

**Comment by warezWally** [comment]
Would also like this feature, to allow setting of the "ENI_CONFIG_LABEL_DEF" environment variable in the aws-node pods. Without it my pods are not being assigned an IP
