### ISSUE TITLE
Can't connect to any service running in aws infra like rds, ec2 instance when using security group for pods

### ISSUE THREAD

**Issue by samjain04** [aws/amazon-vpc-cni-k8s#2107]
What happened:
We recently upgraded our eks cluster to 1.21 from 1.20 as well as other add-ons like VPC CNI, Coredns, Kube-proxy and after upgrade our pods are unable to connect our RDS and mongo servers.

But when we remove security groups from pod then they are able to connect.
 Disable_tcp_early_demux  is already set to true
DISABLE_TCP_EARLY_DEMUX:  true
ENABLE_POD_ENI:                                      true
POD_SECURITY_GROUP_ENFORCING_MODE:                   standard

Is there anything else needs to be updated for at the time of cluster upgrade which could have caused this issue
**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: v1.21.2-13+d2965f0db10712
Server Version: v1.21.14-eks-6d3986b

- CNI Version :-  amazon-k8s-cni-init:v1.11.3
amazon-k8s-cni:v1.11.3

**Comment by jdn5126** [comment]
@samjain04 what CNI version did you upgrade from? Moving from default mode to standard mode can require recycling of pods. Can you share the logs before recycling and we can take a look?

**Comment by samjain04** [comment]
@jdn5126 Upgraded from v1.11.0 to v1.11.3 and POD_SECURITY_GROUP_ENFORCING_MODE was standard before upgrade. 
Pods were recycled after we starting getting this issue but didn't helped

**Comment by jdn5126** [comment]
> @jdn5126 Upgraded from v1.11.0 to v1.11.3 and POD_SECURITY_GROUP_ENFORCING_MODE was standard before upgrade. Pods were recycled after we starting getting this issue but didn't helped

I see, do you have the logs from this period? We can take a look, or you can feel free to open a support case if that is easier.

**Comment by achevuru** [comment]
@samjain04 Is this still an active issue? If yes, can you please share the logs requested above? You can email them to `k8s-awscni-triage@amazon.com` ..
