### ISSUE TITLE
Move go.mod in test directory to root go.mod

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-cni-k8s#2109]
**What would you like to be added**:
Move `go.mod` in test directory to use `go.mod` in root directory.

**Why is this needed**:
Managing dependencies is easier when they are all defined in one place. This is also closer to Golang recommended organization. 

Note that moving `go.mod` will require updating GitHub runners and (potentially) some import paths.

**Comment by royninja** [comment]
but go.mod is already in root directory

**Comment by jdn5126** [comment]
> but go.mod is already in root directory

There is an additional `go.mod` in the test directory, which can be removed, and its dependencies moved into the `go.mod` in the root directory.

**Comment by jdn5126** [comment]
Closing as fixed
