### ISSUE TITLE
IPv6 prefix on pods

### ISSUE THREAD

**Issue by tanshihaj** [aws/amazon-vpc-cni-k8s#2120]
I wonder is there any way to delegate IPv6 prefix to the pod's interface? I have an application that have to listen connections on ~1000 ipv6 addresses and it would be really wasteful to run one pod per address. Currently I have to do it in EC2 instances, which is not very convenient.

**Comment by achevuru** [comment]
@tanshihaj All the containers in a Pod share the same network namespace (i.e.,) same set of network interfaces, nw stack etc., How are you going to assign a different IP to individual containers in a single pod? CNIs work at pod level. And why do you need all of them in the same pod? All the containers in the same pod can talk to each other via `localhost` as they share the same network namespace and it might not make sense to assign different IPs to individual containers - It is like trying to assign different IP addresses to various processes running directly on your host ...

**Comment by tanshihaj** [comment]
> All the containers in a Pod share the same network namespace (i.e.,) same set of network interfaces, nw stack etc., How are you going to assign a different IP to individual containers in a single pod? CNIs work at pod level.

As far as I know I do not need to assign different IP addresses to different containers (honestly, I do not know what does 'assign IP to container' mean). Since all processes in all containers inside one pod shares one network namespace I can just add IPv6 address from IPv6 prefix delegated to the network interfaces to this interface and then bind listen socket to this address in container's process. I do not expect any problems here.

> And why do you need all of them in the same pod?
I want to save cluster resources. If I can bring IPv6 prefix to one pod I can run one process that listen several addresses in it. If I have to run one pod per one IPv6 address it obviously increases processor time and memory consumption dramatically.

> All the containers in the same pod can talk to each other via localhost as they share the same network namespace and it might not make sense to assign different IPs to individual containers - It is like trying to assign different IP addresses to various processes running directly on your host ...
Yes, in most of the applications this is pointless. However even on average server different processes can listen different addresses (I assume that 'assign IP to process' means listening socket that binds to some address).

**Comment by jdn5126** [comment]
@tanshihaj can you elaborate on why this application needs to listen on 1k+ IP addresses? Can the application instead listen on a range of ports and accomplish the same function?

**Comment by tanshihaj** [comment]
> can you elaborate on why this application needs to listen on 1k+ IP addresses?

It is an SSH proxy application. Each hostname (which SSH connection should be proxied) resolves to one IP address. SSH proxy process listen on 22 port on this IP address and thus know which host should be proxied and know how to authorize access.

> Can the application instead listen on a range of ports and accomplish the same function?

It can be done if there will be another proxy that will map (many IPv6 addresses) -> (one IPv6 address + many ports). But it will increase whole system complexity.

**Comment by achevuru** [comment]
```
 I can just add IPv6 address from IPv6 prefix delegated to the network interfaces to this interface and then bind listen socket to this address in container's process. I do not expect any problems here.
```
I'm not sure I follow this. We will only have one network interface for these pods (unless you go for multi homed pods with a meta plugin like Multus CNI) and how will you then tie one address from this range to one of the container process?

```
Each hostname (which SSH connection should be proxied) resolves to one IP address. SSH proxy process listen on 22 port on this IP address and thus know which host should be proxied and know how to authorize access.
```
Again, how will we map this inside a single pod? (i.e.,) an IP from an assigned prefix (on pod's eth0) to a process/container inside the pod? 

VPC CNI will only attach a host IP address (/32 or /128) based on the IP family of the cluster.

**Comment by tanshihaj** [comment]
> I'm not sure I follow this. We will only have one network interface for these pods (unless you go for multi homed pods with a meta plugin like Multus CNI) and how will you then tie one address from this range to one of the container process?

In my case each host have some integer id `host_id` in range 0-2^16. Lets say I want to run process that should listen for host with id `42` on interface with IPv6 prefix `2a02:6b8:c3a:204:260d::/80`. Thus this process will add `2a02:6b8:c3a:204:260d::91` address to this interface and bind listening socket with `[2a02:6b8:c3a:204:260d::91]:22` endpoint. I think it is possible to find out other ways to `bind` address and process, this is not a problem. Or maybe I didn't understand the problem, please explain better what do you mean by "tie" address and process.

> VPC CNI will only attach a host IP address (/32 or /128) based on the IP family of the cluster.
Yes, I know that currently it is not possible to delegate IPv6 prefix to the pod, but it would be great if it will be possible in the future. I've described at least one usecase.
