### ISSUE TITLE
Can I use amazon-vpc-cni-k8s on other clusters

### ISSUE THREAD

**Issue by He-Jingkai** [aws/amazon-vpc-cni-k8s#2126]
**What happened**:

I want to use it on my cluster I set up on the physical machine，but I don't know if it's supported.

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
@He-Jingkai can you provide more information, i.e. how did you set up the cluster, and everything else required in the environment section of the issue template

**Comment by He-Jingkai** [comment]
@jdn5126 

Thank you Nelson.
I set up mu cluster using `kubeadm`.

Kubernetes version (use kubectl version):
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
OS (e.g: cat /etc/os-release):
```bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Kernel (e.g. uname -a):
```bash
$ uname -a
Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

**Comment by achevuru** [comment]
@He-Jingkai AWS VPC CNI will only work with AWS infra (either EKS or Self managed K8S cluster) and doesn't support Overlay mode. So, we can't use it on a cluster outside of AWS.

**Comment by He-Jingkai** [comment]
@achevuru Thank you.
