### ISSUE TITLE
Support for NAT with configurable IP address 

### ISSUE THREAD

**Issue by zeagord** [aws/amazon-vpc-cni-k8s#2130]
**What would you like to be added**:

When a POD communicates outside the EKS cluster, need a option of NAT the IP address to a reliable static IP from the VPC CIDR. 

**Why is this needed**:

The reliable/static set up IPs can be used to add to the security groups of other services and also in firewall rules.

**Comment by sushrk** [comment]
@zeagord Can you please explain the usecase more? Is this for communication outside the VPC? If so, you can use the node IP (this is not assigned by CNI, you would need to scrape this on your side). And the IP inside a VPC is unique, and we no do any NAT within the cluster.

**Comment by zeagord** [comment]
I should have been much clearer. I am looking for an egress gateway of sort, where all outgoing traffic gets NATed to a specific set of IPs instead of the node IP addresses (SNAT). Something similar to - https://docs.cilium.io/en/v1.12/gettingstarted/egress-gateway/

**Comment by jdn5126** [comment]
@zeagord have you considered using a NAT gateway, like what we support with `AWS_VPC_K8S_CNI_EXTERNALSNAT` - https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html ?

**Comment by elasticdotventures** [comment]
Just want to echo - I have this requirement (a NAT gateway to allow our traffic to come from a dedicated IP).

I also have a separate, similar, but wholly unrelated requirement for inbound IPSEC connections to a fixed address (trading partner requires a whitelisted IP), so a NAT gateway would only allow outbound.

Didn't realize this would be so difficult/impossible to deal with fixed ip's & EKS.

**Comment by achevuru** [comment]
@elasticdotventures You can place a NAT gateway in front of your EKS nodes and you can configure  `AWS_VPC_K8S_CNI_EXTERNALSNAT` to let VPC CNI know that you plan to use an external NAT gateway for traffic destined for a target external to your VPC.

For the other scenario you described, are you looking for a static/fixed IP for a Pod? If yes, I don't think you need a CNI to do that as you want the IP to be fixed for a particular pod. If you just want a predictable IP address, why not place an NLB in front of your cluster? Or you can use host network pods if you want a static IP (in this case node IP).
