### ISSUE TITLE
Add resource configuration in cni-metrics-helper helm chart

### ISSUE THREAD

**Issue by jcogilvie** [aws/amazon-vpc-cni-k8s#2140]
**What would you like to be added**:
Enable me to set `resources` on the cni-metrics-helper pods via their helm chart

**Why is this needed**:
When using an autoscaler (e.g. karpenter), the cluster needs to know a resource request on behalf of any running pod so that it can provision adequate space

**Comment by jayanthvn** [comment]
#2141 is merged to master. We will pick it up in the next release.
