### ISSUE TITLE
Inconsistent behavior of ENIConfig

### ISSUE THREAD

**Issue by asevans** [aws/amazon-vpc-cni-k8s#215]
I'm seeing inconsistent behavior assigning pods to an ENIConfig: when creating a new deployment, pods are assigned to the intended ENIConfig, but if the pods are evicted, scaled, or recreated they appear on wrong ENI.

My setup:
- EKS 1.10 (running amazon-k8s-cni:1.2.1)
- Calico installed (per https://docs.aws.amazon.com/eks/latest/userguide/calico.html)
- CNI custom networking installed (per https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html)

Steps:
- My cluster nodes have the default security group "my-cluster"
- Created new security group "my-app"
- Created new ENIConfig (scoped to "my-app" security group and existing subnets of the cluster)
- Deployed the stars demo (from Calico instructions above)
- New pods created are assigned to an ENI having the "my-app" security group
- Delete one of the pods
- Pod gets recreated, but now is assigned to an ENI having the default "my-cluster" security group

I also tried the following:
- scale up the ReplicaController to run additional pods: additional pods assigned to ENI with "my-cluster" SG rather than "my-app" SG
- drained the node running the pod: even though new node has an ENIConfig for "my-app", pods are assigned to ENIs for "my-cluster" SG
- the stars demo uses ReplicaControllers, but I changed them to use Deployments (and still see these issues)

**Comment by asevans** [comment]
I believe Calico is related to this problem, because when I removed it I was unable to recreate the steps above (and after reinstalling it, could recreate it)

**Comment by mogren** [comment]
Is this still an issue?
