### ISSUE TITLE
Updating add-on fails due to conflicts

### ISSUE THREAD

**Issue by plhrja** [aws/amazon-vpc-cni-k8s#2150]
**What happened**:
Attempting to update the add-on (from v1.9.3-eksbuild.1 to v1.10.3-eksbuild.1) from the console results in a failure with the following message 
```Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. Conflicts: DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].resources.requests DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].resources.requests.cpu DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].resources.requests DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].resources.requests.cpu DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].resources.requests.cpu```

It is unclear what actions should be taken based on the above message. We managed to perform the update without trouble in our test cluster, which has pretty much identical configuration apart from node instance types.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.14
- CNI Version v1.9.3-eksbuild.1

**Comment by jayanthvn** [comment]
@plhrja Can you please select -

```
Override - If conflict exists, override conflicting fields with values from the EKS API.
```

Ideally even the test cluster should have seen this issue. Was the K8s version also same between test and prod?

**Comment by plhrja** [comment]
Oh thanks, this remedied the update. My bad, overlooked the (hidden) advanced configurations. Fixed, so closing this.

> Was the K8s version also same between test and prod?

Indeed, the are in the exact same version.
