### ISSUE TITLE
Mechanism for configuring CNI when installed as a managed addon

### ISSUE THREAD

**Issue by DerekTBrown** [aws/amazon-vpc-cni-k8s#2151]
## Problem
- We currently use CNI on our EKS clusters.
- We have previously been told by AWS Support that we need to configure certain environment variables in order to mitigate issues/bugs in CNI ([reference](https://github.com/aws/amazon-vpc-cni-k8s/issues/2056#issuecomment-1215888082)).
- CNI is installed as an EKS managed addon. The AWS EKS Addon API doesn't have support for configuring environment variables ([reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAddon.html)).

## Other Solutions
- AWS support has indicated that we could set these environment variables using `kubectl` ([reference](https://www.repost.aws/questions/QUuXmaLKkzRembgsaXAqql-Q/how-to-pass-environment-variables-to-cni-addon?sc_ichannel=ha&sc_ilang=en&sc_isite=repost&sc_iplace=hp&sc_icontent=QUuXmaLKkzRembgsaXAqql-Q&sc_ipos=14)).  This solution doesn't work for several reasons:
    1. This isn't guaranteed to persist across upgrades or restarts.
    2. We dynamically allocate clusters using infrastructure-as-code (Terraform), which doesn't have the ability to run arbitrary `kubectl` commands.

## Feature Request
We need some mechanism to configure CNI environment variables when CNI is installed as a managed addon. This could be:
1. Reading from a ConfigMap (similar to #2102)
2. Extending the Addon CNI configuration to permit specifying environment variables.

**Comment by jdn5126** [comment]
@DerekTBrown great timing, as we have actually been working on advanced configuration for managed addons in the background for some time. This feature will allow for the configurability that you are interested in via managed addon. There will be a public announcement for this soon (plan is by end of year), so I will post here when it is up.

**Comment by achevuru** [comment]
Also, you can use `resolveConflicts: PRESERVE` feature which should leave all the fields with conflicts untouched during an upgrade. You can check this out - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-preserve-customer-edits

**Comment by DerekTBrown** [comment]
>  Also, you can use resolveConflicts: PRESERVE feature which should leave all the fields with conflicts untouched during an upgrade. You can check this out - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-preserve-customer-edits

Does this apply to env variables as well?

**Comment by jdn5126** [comment]
> > Also, you can use resolveConflicts: PRESERVE feature which should leave all the fields with conflicts untouched during an upgrade. You can check this out - https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-preserve-customer-edits
> 
> Does this apply to env variables as well?

It applies to any conflicts detected while deploying the helm chart, so if the field is in the helm chart, then yes.

**Comment by jayanthvn** [comment]
Env variables are user managed and during upgrades those variables will be retained once modified.

**Comment by romich** [comment]
>great timing, as we have actually been working on advanced configuration for managed addons in the background for some time. This feature will allow for the configurability that you are interested in via managed addon. There will be a public announcement for this soon (plan is by end of year), so I will post here when it is up.

Looks like it's live now, though `vpc-cni` addon seems to be missing support for `WARM_IP_TARGET` env var, which is the only one we're actually interested in :(

**Comment by jdn5126** [comment]
@romich which addon version are you currently using? I do see that `WARM_IP_TARGET` is not configurable through MAO schema (`WARM_ENI_TARGET` is). Our initial release did not expose all env vars in the schema, but we are working on releasing new versions that expose the rest.

Can you let me know which addon version you are using so I can track this?

**Comment by sidewinder12s** [comment]
The advanced config appears to have gotten released: https://aws.amazon.com/about-aws/whats-new/2022/12/eks-add-ons-supports-advanced-configuration/

**Comment by romich** [comment]
@jdn5126 we're on vpc-cni addon version `v1.11.3-eksbuild.1`, though we can upgrade to whatever version is required to get  additional env vars working. Another one we might be interested in is `MINIMUM_IP_TARGET`.

**Comment by jdn5126** [comment]
Schema update is in progress and new versions are being tested. Hoping to release new versions with updated schema in the next few weeks. All env vars available in each version are now part of schema

**Comment by jdn5126** [comment]
New VPC CNI managed addon versions have been released with all environment variables as configurable in the schema. For example:
```
% aws eks describe-addon-configuration --addon-name=vpc-cni --addon-version="v1.11.3-eksbuild.3" --query=configurationSchema --output=text | jq . | grep -i IP_TARGET
        "MINIMUM_IP_TARGET": {
        "WARM_IP_TARGET": {
```
Please let me know if you run into any issues with these new versions

**Comment by romich** [comment]
>Please let me know if you run into any issues with these new versions

While I see updated schema when describing configuration for version `v1.12.0-eksbuild.2`, I can't install it on EKS 1.24 ("InvalidParameterException: Addon version specified is not supported"), and `describe-addon-versions --addon-name vpc-cni` doesn't list this new `.2` build (same for `v1.11.3-eksbuild.3`).

**Comment by romich** [comment]
Yup, now i also can see and install `v1.12.0-eksbuild.2`. ~6 hours ago `aws eks describe-addon-versions --addon-name vpc-cni` was only giving me `eksbuild.1` for 1.12.0 version.

**Comment by jdn5126** [comment]
Ah sorry, yeah I see there were block days on the 1st and 2nd, so some regions didn't get the rollout until today

**Comment by therc** [comment]
@jdn5126 how long does it take for a new release to be available as an addon? Is the process automated, or does it rely on a human to kick off something? 1.12.1 was cut yesterday, but the latest addon in us-east-1 is still 1.12.0. Thank you.

**Comment by jdn5126** [comment]
@therc the managed addon release has some human intervention (I am working on this now), but in general we try to release the managed addon a few days after the GitHub release. The v1.12.1 managed addon is taking a bit longer this time due to process changes that should speed things up going forward.

**Comment by jdn5126** [comment]
@therc sorry for the long delay here, but VPC CNI `v1.12.1-eksbuild.1` is available as a managed addon in all regions now. This will be much faster going forward as we finished automating a large part of this
