### ISSUE TITLE
VPC CNI Pods are not scheduled for more than 10 minutes when there is no outbound internet connection

### ISSUE THREAD

**Issue by zeagord** [aws/amazon-vpc-cni-k8s#2162]
**What happened**:
I am trying to provision new capacity for the EKS cluster using Karpenter. The provisioner was able to create nodes immediately, usually the instance sizes are m5.large or m5.xlarge and on-demand instances. But it takes about 10 minutes for the EC2 node to be ready. Checked the EC2 quotas, Karpenter Webhook and Controller logs in debug mode and no information there.

It is a fully private cluster with no outbound access to internet. I have checked the Karpenter troubleshooting guide and checked the kubelet logs. But I could not SSH via SSM for about 10 minutes as well.

Upon further debugging,

Below events are from `kube-proxy` and `vpc-cni`
```
Warning  FailedScheduling  24s   default-scheduler  0/5 nodes are available: 1 Insufficient cpu, 1 Too many pods, 4 node(s) didn't match Pod's node affinity/selector. 
```
Once I enabled a NAT GW to my VPC, I was able to SSH in my node and found this.

```
Found these errors from kubelet "Failed to create sandbox for pod" err="roc error: code = Unknown desc= failed to setup network for sandbox\": plugin type=\"aws-cni\" name=\"aws-cni\"
```

Checked the logs files in `/var/log/aws-routed-eni/` and `ipamd.log`, there are no interesting entries there.

Note: I have all the necessary VPC endpoints and the VPC have sufficient number of IPs

**Attach logs**

**What you expected to happen**:

VPC-CNI nodes should launch with no issues

**How to reproduce it (as minimally and precisely as possible)**:

Run an EKS Cluster in fully private mode with outbound internet in the VPC

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.23.6
- CNI Version: 1.12.0-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Bottlerocket
- Kernel (e.g. `uname -a`):

Probably related to - https://github.com/aws/karpenter/issues/3033

**Comment by jdn5126** [comment]
@zeagord can you run the log collector script in `/opt/cni/bin/aws-cni-support.sh` for one of the affected nodes and we can investigate? You can add it here if you are comfortable, email to [k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com), or we can connect on k8s slack.

**Comment by zeagord** [comment]
@jdn5126 Thank you looking in to this. I suspect it has to do with Karpenter or Bottlerocket user data settings. The node is not ready until it finishes the setting hence the `aws-vpc-cni` pods are not up. I am doing further investingation and for now, we can close this ticket. Thank you for the help.
