### ISSUE TITLE
Multicast support

### ISSUE THREAD

**Issue by m4ce** [aws/amazon-vpc-cni-k8s#2164]
Are there any plans to support multicast in the future? We tried running a multicast-enabled application on EKS but we couldn't get it to work with VPC CNI on the same host.

**Comment by jayanthvn** [comment]
@m4ce - Currently we don't have plans but can you please open a request here - https://github.com/aws/containers-roadmap

**Comment by jayanthvn** [comment]
Thank you @m4ce
