### ISSUE TITLE
Merge test/e2e and test/integration folder

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2167]
**What would you like to be added**:
Merge all ginkgo tests into one folder and update the references 

https://github.com/aws/amazon-vpc-cni-k8s/tree/b88fdf22d26caa168581b6147f567dc9133ee77b/test/e2e
https://github.com/aws/amazon-vpc-cni-k8s/tree/b88fdf22d26caa168581b6147f567dc9133ee77b/test/integration

Also https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/amazon-eks-nodegroup.yaml is deleted. Need to update - https://github.com/aws/amazon-vpc-cni-k8s/blob/b88fdf22d26caa168581b6147f567dc9133ee77b/test/framework/resources/aws/utils/nodegroup.go#L31
**Why is this needed**:
Will be easy to track test cases.

**Comment by jdn5126** [comment]
Yeah, I have been pulling from `https://raw.githubusercontent.com/awslabs/amazon-eks-ami/v20220811/amazon-eks-nodegroup.yaml`. I am working on a PR now to vendor in `amazon-eks-nodegroup.yaml`

**Comment by jdn5126** [comment]
Self-managed node group template is vendored in #2176. I will merge the `integration` and `e2e` folders after #2176 merges.
