### ISSUE TITLE
CNI not work on kubernetes created by cluster API

### ISSUE THREAD

**Issue by zirain** [aws/amazon-vpc-cni-k8s#2168]
**What happened**:

create a kubernete with cluster-api-aws-provide, then run following:
```console
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.12.0/config/master/aws-k8s-cni.yaml
```
every looks good:
```console
NAMESPACE     NAME                                                  READY   STATUS    RESTARTS   AGE
default       httpbin-9dbd644c7-hggls                               1/1     Running   0          3m55s
default       httpbin-9dbd644c7-vvnqb                               1/1     Running   0          70s
default       sleep-78ff5975c6-njljj                                1/1     Running   0          3m44s
kube-system   aws-node-c5rgh                                        1/1     Running   0          5m33s
kube-system   aws-node-lgmf8                                        1/1     Running   0          5m33s
kube-system   aws-node-xm74z                                        1/1     Running   0          5m35s
kube-system   coredns-565d847f94-cfzdn                              1/1     Running   0          6m26s
kube-system   coredns-565d847f94-flt2d                              1/1     Running   0          6m26s
kube-system   etcd-ip-10-0-124-69.ec2.internal                      1/1     Running   0          6m25s
kube-system   kube-apiserver-ip-10-0-124-69.ec2.internal            1/1     Running   0          6m25s
kube-system   kube-controller-manager-ip-10-0-124-69.ec2.internal   1/1     Running   0          6m25s
kube-system   kube-proxy-6d62f                                      1/1     Running   0          6m26s
kube-system   kube-proxy-xpfl8                                      1/1     Running   0          5m33s
kube-system   kube-proxy-zhjhn                                      1/1     Running   0          5m33s
kube-system   kube-scheduler-ip-10-0-124-69.ec2.internal            1/1     Running   0          6m25s
```
but the pod network across nod seems broken:
```console
k get po -owide
NAME                      READY   STATUS    RESTARTS   AGE     IP             NODE                           NOMINATED NODE   READINESS GATES
httpbin-9dbd644c7-hggls   1/1     Running   0          5m4s    10.0.65.109    ip-10-0-72-203.ec2.internal    <none>           <none>
httpbin-9dbd644c7-vvnqb   1/1     Running   0          2m19s   10.0.109.192   ip-10-0-126-192.ec2.internal   <none>           <none>
sleep-78ff5975c6-njljj    1/1     Running   0          4m53s   10.0.107.42    ip-10-0-72-203.ec2.internal    <none>           <none>
```

```console
k exec -it sleep-78ff5975c6-njljj -- curl 10.0.65.109:80/ip
{
  "origin": "10.0.107.42"
}

k exec -it sleep-78ff5975c6-njljj -- curl 10.0.109.192:80/ip
```

how can I make it works?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.0
- CNI Version: 
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
@zirain - Can you please run tcp dump and confirm if the traffic is egressing the pod and node. That would confirm if the packets are dropped at the node level or at the vpc level. Also good to verify if the IP tables and rules are programmed fine. 

I see you are not using EKS AMI, you can maybe copy this [script](https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh) and run it on the node? This would generate the log bundle and you can attach it to the issue.

**Comment by jdn5126** [comment]
Do we currently support CNI on k8s 1.25?

**Comment by zirain** [comment]
> @zirain - Can you please run tcp dump and confirm if the traffic is egressing the pod and node. That would confirm if the packets are dropped at the node level or at the vpc level. Also good to verify if the IP tables and rules are programmed fine.
> 
> I see you are not using EKS AMI, you can maybe copy this [script](https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh) and run it on the node? This would generate the log bundle and you can attach it to the issue.

thanks for your reply, I'll try with your suggestions.

**Comment by zirain** [comment]
after I setup IRSA, everything looks good now
thanks for your help @jayanthvn

**Comment by zirain** [comment]
for folks have same issue, cluster-api has a sg rule only allow port between 3000 and 32767 across node, don't forgot update it if you want to use `amazon-vpc-cni`.
