### ISSUE TITLE
Is it possible to assign specific custom network to a node OR schedule a pod to a specific network?

### ISSUE THREAD

**Issue by brian-provenzano** [aws/amazon-vpc-cni-k8s#2169]
With custom networking enabled, is there a method to designate a node (or better a pod/deployment) so that it always uses a specific network? Currently we have custom networking setup using `ENI_CONFIG_LABEL_DEF` set to `failure-domain.beta.kubernetes.io/zone` with ENIConfigs for each AZ/subnet using non-routable (100.64..) addresses - pretty much [this method](https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/).  What we would like to be able to do is selectively schedule pods on the network of choice (either the VPC network or the custom 100.x network).  This can either be by designating specific nodes to use the custom 100.x network and then selectively schedule pods possibly using something like taints/tolerations.   Hopefully I am explaining this effectively... :)

**Current config**:
- custom networking enabled
- using non-routable (100.64..) addresses

**Environment**:
- Kubernetes version (use `kubectl version`):  `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`
- CNI Version: amazon-k8s-cni-init:v1.10.1-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): Linux ip-172-28-103-59 5.4.0-1081-aws #88~18.04.1-Ubuntu SMP Thu Jun 23 16:29:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jayanthvn** [comment]
@brian-provenzano - Right now this is not possible unfortunately since custom networking is a cluster level config. Maybe once we support this https://github.com/aws/containers-roadmap/issues/1834, this might be doable.

**Comment by jayanthvn** [comment]
Closing the issue, we will provide the updates in the roadmap feature request - #1834.
