### ISSUE TITLE
Allow pullInterval to be configurable

### ISSUE THREAD

**Issue by dnatic09** [aws/amazon-vpc-cni-k8s#2171]
**What would you like to be added**:
Allow for the pullInterval (`30 seconds`) to be configurable. We are expending a large amount of custom metrics in non-production environments. This parameter is inflexible and does not allow administrators to tune to the frequency required.

**Why is this needed**:
Allows for administrators to reduce cost and overhead of custom metrics in CloudWatch.

**Extra Notes**
This change is NOT invasive, is backwards compatible, and should not impact any other active work.

**Extra-Extra Note**
I am making a pull request for this right now. To be updated soon.

EDIT: Pull Request opened locally.
https://github.com/dnatic09/amazon-vpc-cni-k8s/pull/1

EDIT 2: PR opened against this repo. You can ignore the first.
https://github.com/aws/amazon-vpc-cni-k8s/pull/2172

**Comment by jdn5126** [comment]
Closing as implemented
