### ISSUE TITLE
Allow POD_SECURITY_GROUP_ENFORCING_MODE to be configurable via aws cli/CloudFormation

### ISSUE THREAD

**Issue by krzysztof-mitus** [aws/amazon-vpc-cni-k8s#2173]
**What happened**:

I'm unable to update vpc-cni addon with POD_SECURITY_GROUP_ENFORCING_MODE parameter via aws cli and CloudFormation.
It's not in the schema.

**Attach logs**
```
[cloudshell-user@ip-10-0-32-98 ~]$ aws eks describe-addon-configuration --addon-name=vpc-cni --addon-version="v1.12.0-eksbuild.1" --query=configurationSchema --output=text|jq .|grep -i POD
        "ANNOTATE_POD_IP": {
        "ENABLE_POD_ENI": {


[cloudshell-user@ip-10-0-32-98 ~]$ aws eks update-addon --cluster-name=PLAY04-app-k8s --addon-name=vpc-cni --addon-version="v1.11.4-eksbuild.1" --resolve-conflicts OVERWRITE --configuration-values '{"env":{"POD_SECURITY_GROUP_ENFORCING_MODE":"standard"}}'

An error occurred (InvalidParameterException) when calling the UpdateAddon operation: ConfigurationValue provided in request is not supported [$.env.POD_SECURITY_GROUP_ENFORCING_MODE: is not defined in the schema and the schema does not allow additional properties]
```

**What you expected to happen**:

I want to be able to update  POD_SECURITY_GROUP_ENFORCING_MODE with aws cli/Cloud Formation

**Environment**:
- Kubernetes version (use `kubectl version`): EKS 1.23
- CNI Version: v1.12.0-eksbuild.1

**Comment by jdn5126** [comment]
@krzysztof-mitus the schema update is in progress. Hoping to have new versions released with new schema in the next few weeks

**Comment by jdn5126** [comment]
@krzysztof-mitus new VPC CNI addon versions have been released with all environment variables as configurable. Running this for `v1.12.0-eksbuild.2` yields:
```
% aws eks describe-addon-configuration --addon-name=vpc-cni --addon-version="v1.12.0-eksbuild.2" --query=configurationSchema --output=text | jq . | grep -i POD
        "ANNOTATE_POD_IP": {
        "ENABLE_POD_ENI": {
        "POD_SECURITY_GROUP_ENFORCING_MODE": {
```

**Comment by krzysztof-mitus** [comment]
thanks a lot for quick resolution
