### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by jaydeokar** [aws/amazon-vpc-cni-k8s#2175]
**What happened**:
Update client-go, helm and vpc-resource-controller packages in the repository to the latest compatible version

**Attach logs** 
N/A

**What you expected to happen**:
Update dependencies, run integration tests. Create the vpc cni image and scan using enhanced scanning or similar tool and make sure the image doesn't report any critical vulnerabilities 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:

**Comment by jdn5126** [comment]
Closing as fixed by #2204
