### ISSUE TITLE
Support public subnets for pods with Security Groups

### ISSUE THREAD

**Issue by barryrobison** [aws/amazon-vpc-cni-k8s#2179]
**What would you like to be added**:

According to https://docs.aws.amazon.com/eks/latest/userguide/pod-networking-use-cases.html  if you want to use Security Groups on your pods, they must be in private subnets. Testing confirms these pods get a "Failed to create pod sandbox" error.

We would like to use pods in public subnets, with Security Groups attached.

**Why is this needed**:

Our workload generates a large amount of internet bound traffic. For cost and performance reasons we would like to avoid traversing a NAT Gateway for this traffic.

Thank you!

**Comment by jayanthvn** [comment]
@barryrobison - I need to verify this or @M00nF1sh might be aware of it. I assume, we can use version 1.11 or later of the plugin with `POD_SECURITY_GROUP_ENFORCING_MODE=standard` for your use case.

```
If you're using version 1.10 or earlier of the Amazon VPC CNI plugin or version 1.11 with POD_SECURITY_GROUP_ENFORCING_MODE=strict, which is the default setting, source NAT is disabled for outbound traffic from pods with assigned security groups so that outbound security group rules are applied. To access the internet, pods with assigned security groups must be launched on nodes that are deployed in a private subnet configured with a NAT gateway or instance. Pods with assigned security groups deployed to public subnets are not able to access the internet.

If you're using version 1.11 or later of the plugin with POD_SECURITY_GROUP_ENFORCING_MODE=standard, then pod traffic destined for outside of the VPC is translated to the IP address of the instance's primary network interface. For this traffic, the rules in the security groups for the primary network interface are used, rather than the rules in the pod's security groups.
```

**Comment by jayanthvn** [comment]
Verified this and pods in public subnet with `POD_SECURITY_GROUP_ENFORCING_MODE=standard` can reach the internet.

```
curl -L http://www.google.com/
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly..
```

Strict mode + pod in public subnet fails to reach, which is expected.
```
curl -L http://www.google.com/
curl: (6) Could not resolve host: www.google.com
```

But was curious, in your comment you have mentioned you saw `Failed to create pod sandbox` error which should not happen in either of the private or public subnets, did you check if branch ENI is attached to the node?

**Comment by haouc** [comment]
Can you describe the pods that have the error and check if any errors in event. Also you can check if trunk interface is attached to nodes by `kubectl get no -oyaml | grep trunk`. If you are not seeing any output, please check if your node instance types are qualified for the feature and you turned on the feature in VPC CNI ENV `ENABLE_POD_ENI`. One last thing to check is your cluster IAM role has the permission to use VPC resource controller, which is unlikely but could be a reason depending on how you created your cluster.

**Comment by barryrobison** [comment]
Thanks @jayanthvn I can confirm that setting `POD_SECURITY_GROUP_ENFORCING_MODE` to standard allows the pods access to the internet from a public subnet.  Appreciate the pointers!
