### ISSUE TITLE
Deploy Security groups for pods in a secure way

### ISSUE THREAD

**Issue by janavenkat** [aws/amazon-vpc-cni-k8s#2180]
**What happened**:

Currently we're testing pod security group and we hit into one problem it's hard for us to deploy security group in production without downtime. Because during deployment old and new pods available as we want to create ingress/egress rule on both sides of the connection.

Is there any way to deploy in a safe way without affecting the connections? For example is it possible to only log the deny connection and proceed with the request? 

In Calico there is a way to log the connection https://projectcalico.docs.tigera.io/security/calico-network-policy#generate-logs-for-specific-traffic

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.15
- CNI Version: 1.1.16
- OS (e.g: `cat /etc/os-release`): Amazon Linux
- Kernel (e.g. `uname -a`): `5.4.219-126.411.amzn2.x86_64`

**Comment by jdn5126** [comment]
Hi @janavenkat , if I understand correctly, you have an existing deployment, and when you configure a security group for the pods in that deployment, you have downtime while the pods are re-deployed behind branch ENIs. Is that correct? And you want to know how you can progressively roll out security groups to existing pods without security groups?

**Comment by janavenkat** [comment]
@jdn5126 thank you for the response.

Yes exactly and also is there a way to test it properly?

> Is there any way to deploy in a safe way without affecting the connections? For example is it possible to only log the deny connection and proceed with the request?

In Calico there is a way to log the connection instead of deny https://projectcalico.docs.tigera.io/security/calico-network-policy#generate-logs-for-specific-traffic

**Comment by jdn5126** [comment]
@janavenkat the best way to test is to use the VPC Reachability Analyzer: https://docs.aws.amazon.com/vpc/latest/reachability/getting-started.html

This will let you specify endpoints within the VPC and evaluate which security group rules will be hit (pod, source node, dest node, etc) and whether the connection will be accepted/denied. As far as pod deployments go, we typically recommend starting with a security group policy that allows all ingress/egress traffic, then adding rules and testing with reachability analyzer.

It is also a good idea to deploy a test/canary pod with the security group and use VPC reachability analyzer before moving that SG to the target pod.

Hopefully that helps, let me know if have any other questions or specific scenarios that you want to walk through. Also adding @haouc in case he can think of any other suggestions.

**Comment by jayanthvn** [comment]
@janavenkat - Adding to what Jeff mentioned, you can enable VPC flow logs to capture the traffic too - https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html

**Comment by janavenkat** [comment]
@jdn5126 @jayanthvn thank you for the reply!

We thought of using VPC flow logs and allow all traffic in security group and also more complicated to test.

I haven't tested with the VPC Reachability Analyzer yet, I will take a look.

It appears that all of the options require a significant amount of manual work and testing. It would be useful if there was a simpler method for deployment, like deploying a security group policy with the necessary ingress/egress rules and the ability to allow, deny, or log traffic, similar to how Calico does."

Again thank you both
