### ISSUE TITLE
Update the Client-go and dependent packages

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2195]
**What would you like to be added**:
Update the client-go package and dependent packages, currently we are using - 

```
	k8s.io/api v0.20.2
	k8s.io/apimachinery v0.20.2
	k8s.io/cli-runtime v0.20.2
	k8s.io/client-go v0.20.2
```
**Why is this needed**:
0.25.X and 0.26.X is available.

**Comment by dims** [comment]
related to https://github.com/aws/amazon-vpc-cni-k8s/issues/2196

**Comment by jdn5126** [comment]
Closing as #2204 merged
