### ISSUE TITLE
Support for Kubernetes 1.25 and 1.26

### ISSUE THREAD

**Issue by dims** [aws/amazon-vpc-cni-k8s#2196]
Does v1.12.0 support the newer versions of k8s? Looking at the go.mod, probably not. Could we make fresh releases to support newer version of k8s?

thanks!

**Comment by dims** [comment]
related to https://github.com/aws/amazon-vpc-cni-k8s/issues/2195

**Comment by dims** [comment]
related to https://github.com/aws/amazon-vpc-cni-k8s/issues/2194

**Comment by jayanthvn** [comment]
Yes Dims, we will update the modules and have 1.12.2 or probably 1.13.0 with new changes for SGPP planned by @haouc

**Comment by jdn5126** [comment]
Closing as completed by #2204 . #2278 also increments modules
