### ISSUE TITLE
Name in example yaml is confusing

### ISSUE THREAD

**Issue by nckturner** [aws/amazon-vpc-cni-k8s#22]
In the example yaml files in misc/, the name and value for the `k8s-app` label is `aws-node` which is not very descriptive.  I propose changing it to `amazon-cni` or `amazon-vpc-cni-k8s`.

**Comment by SaranBalaji90** [comment]
We should also add following content to our yaml file

spec:
  updateStrategy:
    type: RollingUpdate

**Comment by mogren** [comment]
Great idea, we should have done that a year ago... 😪
