### ISSUE TITLE
Add EC2 instance types M6in, M6idn, R6in, and R6idn to eni-max-pods.txt

### ISSUE THREAD

**Issue by dsalamancaMS** [aws/amazon-vpc-cni-k8s#2206]
**What would you like to be added**:

EC2 instance types M6in, M6idn, R6in, and R6idn were released on Nov 28: 
- https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-ec2-m6in-m6idn-r6in-r6idn-network-optimized-instances/

**Comment by nickmancari** [comment]
PR added for this.

Happy to help :smile:

**Comment by jdn5126** [comment]
Fixed by #2235
