### ISSUE TITLE
How to disable debug level for cni-metrics?

### ISSUE THREAD

**Issue by csantanapr** [aws/amazon-vpc-cni-k8s#2207]
**What happened**:

The cni-metric-helper pod is logging to much information, is dumping all metrics to logs and this is a cost and operation overhead.

This is the default behaivor, I think we should change the log level to be as expected in production environment error only, if someone is trying to debug or develop then they can change it to high verbose level like debug

I installed the cni-metric-helper using the instructions here https://docs.aws.amazon.com/eks/latest/userguide/cni-metrics-helper.html

**Comment by jdn5126** [comment]
@csantanapr this is a good call out. Can you share which version of `cni-metrics-helper` you are using and some example logs that you think should be suppressed? I can dig further, but it seems like `cni-metrics-helper` respects the `AWS_VPC_K8S_CNI_LOGLEVEL` environment variable (default is `Debug` as you mentioned).

**Comment by jdn5126** [comment]
I see, yeah https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/metrics/cni_metrics.go#L196 is definitely too verbose by default. `INFO` is probably a better default, and customers can set `ERROR` in the helm chart if they truly only want to see error conditions.

I agree that `AWS_VPC_K8S_CNI_LOGLEVEL` should be documented in the README and its default added to https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/cni-metrics-helper/values.yaml

I'll mark this as a good first issue since setting the environment variable is a workaround. I'll take up the effort if no one can get to it before me.

**Comment by hkhelif** [comment]
@jdn5126 you mentioned that the [cni-metrics-helper](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/cmd/cni-metrics-helper) respects the `AWS_VPC_K8S_CNI_LOGLEVEL` environment variable, would changing the `defaultLogLevel` [here](https://github.com/aws/amazon-vpc-cni-k8s/blob/0a9960e1c66ecd0fac722da487bc3b762199b713/pkg/utils/logger/config.go#L22) to `INFO` fix this issue? 

Then the users can set the desired log level by setting it from the environment variable. 

I have tested the suggested changes and I was able to only see `INFO` logs, then I set `AWS_VPC_K8S_CNI_LOGLEVEL` to `DEBUG` and I was able to get to the desired output.

Sorry if my questions or suggested implementation are silly, I am new to this project and new to contributing to open source in general 😄

**Comment by jdn5126** [comment]
@hkhelif you are right on track, but just setting the environment variable to `DEBUG` or `INFO` should have the same effect without requiring a change to the source code. In general, we are very cautious about changing the default value of anything, but for CNI metrics helper, I think it is reasonable.

**Comment by hkhelif** [comment]
@jdn5126 I see that there is already an open PR for this issue, should I open a new one, or it is not required anymore as #2226 already archives the same goal?

**Comment by jdn5126** [comment]
> @jdn5126 I see that there is already an open PR for this issue, should I open a new one, or it is not required anymore as #2226 already archives the same goal?

Yeah, #2226 will take care of this issue. If you are interested in contributing, anything [here](https://github.com/aws/amazon-vpc-cni-k8s/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) that is unassigned is fair game
