### ISSUE TITLE
Update cni-metric-helper doc with requirement about node ports

### ISSUE THREAD

**Issue by csantanapr** [aws/amazon-vpc-cni-k8s#2208]
**What happened**:

I deployed a cluster using the terraform module [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks/) by default the managed node groups are created with a minimal set of security group ingress rules with tcp ports 443 (cluster API),10250(kubelet), 53(coredns) as noted [here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L74-L106)

From what I understand how cni-metric-helper communicates with ipamd/vpc-cni pods that have the endpoint on tcp port :61678/metrics

The cni-metric-helper doesn't try to reach the pod IP directly and instead use the kube-api to proxy, the cni-metric-helper will hit the cluster kube-api node on port 443 (which is very common configured node->cluster) then a connection is made from cluster master node to node on port 61678.

In my case the cni-metric-helper was not able to communicate and printed the following logs
```
Failed to grab CNI endpoint: the server is currently unable to handle the request (get pods aws-node-ktpbn:61678)"}
Failed to grab CNI endpoint: the server is currently unable to handle the request (get pods aws-node-4tjv5:61678)"}
```

**What you expected to happen**:

We should update the docs to have this information as part of installation instructions.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a EKS with recommended [Restricting cluster traffic](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html#security-group-default-rules), then install cni-metric-helper following [docs](https://github.com/terraform-aws-modules/terraform-aws-eks/)

**Anything else we need to know?**:
I opened an issue on terraform repo https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2394

**Comment by jdn5126** [comment]
Looks like the upstream terraform issue was rejected. It does feel like this should be documented somewhere, though. Is there a terraform document that you were referencing? If not, it seems like updating the CNI Metrics README with a note for terraform users is reasonable.

**Comment by csantanapr** [comment]
Hi @jdn5126 I will be creating a new addon eks module for terraform to show users how to configured it properly https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1341

In Addition we should add a note in this repo about the requirement, I can submit a PR

**Comment by bryantbiggs** [comment]
to be clear, I think the "norm" is that this port is exposed in the helm chart which both allows users to customize what port is used but also serves as the canonical source of documentation for the networking access rules that are required by the pod(s). This is not unique to Terraform though

Examples:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/a92e689dfe464f5b24784f398947e0fef31dc470/helm/aws-load-balancer-controller/values.yaml#L176
- https://github.com/aws/karpenter/blob/fb274cdd1c3e303714cafd993ef0b2cad462674d/charts/karpenter/values.yaml#L130

**Comment by csantanapr** [comment]
Hi @jdn5126 

Why is the cni-metric-helper needs to go thru the control plane (kube-api) to get to the node using pod/proxy API, instead of targeting directly the node with node to node communication?
