### ISSUE TITLE
'aws-node' pod's not running (CrashLoopBackOff ) with internal error

### ISSUE THREAD

**Issue by Argal87** [aws/amazon-vpc-cni-k8s#2212]
**What happened**:

The last commit 'a81e07f8e9c642f9e7370b44ca02d0fd60b17ed1' don't run 'aws-node' pod.

**Attach logs**

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/aws-k8s-cni.yaml

**Anything else we need to know?**:
when I downloaded the 'aws-k8s-cni.yaml'  file from previous commit and ran it with kubectl apply, that was worked.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.26.0
- CNI Version
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (AltArch)
- Kernel (e.g. `uname -a`): 4.18.0-348.20.1.el7.aarch64

**Comment by jdn5126** [comment]
@Argal87 thanks for catching this! The commit you highlighted modified `config/master/*` in a backward-incompatible way, as those changes are not compatible with `v1.12.1` images used in YAML file. The changes to `config/master/*` need to wait until the next release image is available (`v1.12.2` or `v1.13.0`). I will revert changes in that directory now.

**Comment by jayanthvn** [comment]
PR is merged, closing the issue.
