### ISSUE TITLE
Remove "update" permissions for node in next release

### ISSUE THREAD

**Issue by jdn5126** [aws/amazon-vpc-cni-k8s#2214]
**What would you like to be added**:
Remove `update` permissions for node in `config/master/aws-k8s-cni*`.

**Why is this needed**:
In #2149 , changes were made for the SGPP feature that no longer require `aws-node` pod to have `update` permissions for node resource. Those changes were made in the chart, and this issue is to track them being made in `config/master/aws-k8s-cni*` when the next release image, `v1.12.2`, is available.

**Comment by haouc** [comment]
Since this will be with a major change to enable events to the resource controller, is a minor version release preferred? For example, v1.13.0?

**Comment by jdn5126** [comment]
> Since this will be with a major change to enable events to the resource controller, is a minor version release preferred? For example, v1.13.0?

Yeah, we'll have to decide on this internally, as I was hoping that the base package updates could go into a 1.12.2 and that we could avoid cherry-picking.

**Comment by jdn5126** [comment]
Closing this issue as this will no longer be taken up
