### ISSUE TITLE
missing "node" api "update" on upgrading from 1.11 to 1.12.0 on eks 

### ISSUE THREAD

**Issue by rkferreira** [aws/amazon-vpc-cni-k8s#2218]
Upgrading aws vpc cni from 1.11 to 1.12.0 it does not come up because cannot update resource \"nodes\" in API group.

`
{"level":"info","ts":"2023-01-16T23:46:00.656Z","caller":"ipamd/ipamd.go:605","msg":"Remove current list [[ip rule 1536: from 10.72.229.169/32 table 2]]"}
{"level":"debug","ts":"2023-01-16T23:46:00.656Z","caller":"ipamd/ipamd.go:605","msg":"UpdateRuleListBySrc: Successfully removed current rule [ip rule 1536: from 10.72.229.169/32 table 2] to "}
{"level":"info","ts":"2023-01-16T23:46:00.656Z","caller":"ipamd/ipamd.go:605","msg":"UpdateRuleListBySrc: Successfully added pod rule[ip rule 1536: from 10.72.229.169/32 table 2]"}
{"level":"info","ts":"2023-01-16T23:46:00.656Z","caller":"ipamd/ipamd.go:541","msg":"Get Node Info for: ip-10-72-228-255.ec2.internal"}
{"level":"debug","ts":"2023-01-16T23:46:00.758Z","caller":"retry/util.go:51","msg":"Node found \"ip-10-72-228-255.ec2.internal\" - no of labels - 14"}
{"level":"debug","ts":"2023-01-16T23:46:00.758Z","caller":"retry/util.go:51","msg":"Deleting label \"vpc.amazonaws.com/eniConfig\""}
{"level":"error","ts":"2023-01-16T23:46:00.760Z","caller":"retry/util.go:51","msg":"Failed to patch node ip-10-72-228-255.ec2.internal with label \"vpc.amazonaws.com/eniConfig\": \"\", error: nodes \"ip-10-72-228-255.ec2.internal\" is forbidden: User \"system:serviceaccount:kube-system:aws-node\" cannot update resource \"nodes\" in API group \"\" at the cluster scope"}
{"level":"error","ts":"2023-01-16T23:46:00.760Z","caller":"ipamd/ipamd.go:414","msg":"Failed to delete eniConfig node label%!(EXTRA *errors.StatusError=nodes \"ip-10-72-228-255.ec2.internal\" is forbidden: User \"system:serviceaccount:kube-system:aws-node\" cannot update resource \"nodes\" in API group \"\" at the cluster scope)"}
{"level":"error","ts":"2023-01-16T23:46:00.760Z","caller":"aws-k8s-agent/main.go:28","msg":"Initialization failure: nodes \"ip-10-72-228-255.ec2.internal\" is forbidden: User \"system:serviceaccount:kube-system:aws-node\" cannot update resource \"nodes\" in API group \"\" at the cluster scope"}
`

**How to reproduce it (as minimally and precisely as possible)**:
Prior helm version: 1.1.12
Prior image version: 1.11.0

Upgrade to helm: 1.2.2
Image version: 1.2.0

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- CNI Version: 1.2.0

As a fix, I mainly put back "update" verb on node api.

**Comment by achevuru** [comment]
@rkferreira  How did you upgrade to v1.12.0?

v1.12.0 manifest has the required `update` permissions for the node - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.12.0/config/master/aws-k8s-cni.yaml#L68.

Same is true with the chart as well - https://github.com/aws/eks-charts/blob/v0.0.121/stable/aws-vpc-cni/templates/clusterrole.yaml#L31

**Comment by rkferreira** [comment]
Hi @achevuru , I got latest chart version 1.2.2 fron the main branch and set image tag as 1.12.0 instead default 1.12.1.

**Comment by jdn5126** [comment]
@rkferreira sorry for the confusion here. The stable chart is published at https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni , as Apurup linked to. The chart in this repo's master branch can drift as new features go in. The image tag is set to the latest release image, but the features are for the next release image, and may not always be compatible with previous image.

If you want to use the 1.12.0 chart, you should install it from eks-charts:
`helm repo add eks https://aws.github.io/eks-charts`

You can run `helm search repo aws-vpc-cni -l` to see the available charts:
```
% helm search repo aws-vpc-cni -l
NAME            CHART VERSION   APP VERSION     DESCRIPTION
eks/aws-vpc-cni 1.2.2           v1.12.1         A Helm chart for the AWS VPC CNI
eks/aws-vpc-cni 1.2.0           v1.12.0         A Helm chart for the AWS VPC CNI
eks/aws-vpc-cni 1.1.21          v1.11.4         A Helm chart for the AWS VPC CNI
...
```

**Comment by rkferreira** [comment]
Perfect, thanks @jdn5126

**Comment by jdn5126** [comment]
Closing as this is working as expected
