### ISSUE TITLE
Kubernetes Cluster Version Compatibility

### ISSUE THREAD

**Issue by ripta** [aws/amazon-vpc-cni-k8s#222]
I'm planning on updating the Amazon VPC CNI templates bundled with `kops` to the latest version 1.2.1.

Are the different versions of the Amazon VPC CNI plugin compatible with all all versions of Kubernetes 1.7–1.11? Is there a compatibility matrix documented elsewhere?

Thanks!

**Comment by mogren** [comment]
It is compatible.
