### ISSUE TITLE
VPC CNI Configuration Variable ENI source/destination check false

### ISSUE THREAD

**Issue by rolvhil** [aws/amazon-vpc-cni-k8s#2223]
**What would you like to be added**:
The VPC CNI creates and attaches more ENIs to instances based on the needs,  which usually corresponds to the number of Pods. The added ENIs have source/destination check set to true. The request is a Configuration Variable to set the source/destination check to false for ENIs created and attached by VPC CNI

e.g. ENI_SOURCE_DESTINATION_CHECK=false

**Why is this needed**:
To allow transitive traffic to/from pods with secondary IPs created by VPC CNI

**Comment by jdn5126** [comment]
@rolvhil ENIs are attached to the node based on the minimum and warm ENI/IP target settings and IP address requirements. 

Are you asking about the reverse path filter setting on these attached ENIs? Can you describe an example workflow where you have asymmetric traffic routing?

**Comment by rolvhil** [comment]
for clarification, transitive here would mean able to reach addresses outside of the VPC CDR. 

If a Pod is behind a secondary ENI (which created by VPC CNI) and is reaching out to an address outside the VPC CIDR, the traffic should egress via the secondary ENI. However if the source/destination check of the secondary ENI is true, traffic would be dropped.

**Comment by jdn5126** [comment]
@rolvhil traffic from a pod behind a secondary ENI to a destination outside of the VPC CIDR should egress via the primary ENI, unless there is a load-balancer within the VPC that is in the forwarding path.

Is it possible that you are hitting #1910? There is a known issue where traffic from a pod behind a secondary ENI fails if the destination is an external IP behind a service. If this is not the case, can you please share more details about this traffic pattern. If it is easier, we can connect on #aws-vpc-cni channel on k8s Slack
