### ISSUE TITLE
Daemonsets and hostNetwork

### ISSUE THREAD

**Issue by ltagliamonte-dd** [aws/amazon-vpc-cni-k8s#2225]
Every devops/platform team that manage a Kubernetes cluster soon or later will face VPC IP exhaustion and realize that a lot of IPs are consumed by daemonsets.

The fastest solution is obviously to move the daemonsets to hostNetwork, however by doing so the quality of observability, security and isolation goes down.
 
I'd like to hear what others have found that work for them, in an ideal world I would love for the CNI to manage an internal bridge (like docker does) and when requested allocate an interface on the bridge instead of allocating an IP from an ENI.

**Comment by jdn5126** [comment]
@ltagliamonte-dd not sure I understand the request, as assigning IP addresses to pods is fundamental to k8s. It is up to the operator to decide whether a pod belongs in the host network namespace or its own namespace. I have not previously seen clusters where so many daemonsets are deployed that they take up a significant chunk of the available IP addresses, so I am curious to hear more about this.

Can you tell me more about the scale of daemonset pods you have here? Is VPC IP exhaustion your main issue here? If so, IPv6 is a great solution, but we can discuss more here or on #aws-vpc-cni channel on k8s Slack

**Comment by jayanthvn** [comment]
@ltagliamonte-dd - Prefix delegation should help with pod packing on the node but it won't solve the IP exhaustion. There will always be subnet/vpc limitation for IPv4. Overlay plugin will help but currently aws-vpc-cni doesn't support it yet. Maybe IPv6 will help but I do agree the applications must support?
