### ISSUE TITLE
Manifest for 1.8.0 pulls image with latest tag, rather than a 1.8 tag

### ISSUE THREAD

**Issue by jimdial-aws** [aws/amazon-vpc-cni-k8s#2234]
**What happened**:

**Attach logs**

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
Yeah, that is definitely a bug: https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.8.0/config/master/aws-k8s-cni.yaml#L156 , but I don't see a strong incentive to fix this as this is a very old version and the managed addon chart and upstream helm chart (eks-charts) are correct.

**Comment by jayanthvn** [comment]
The link shared on the release page has correct tag - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.8.0/config/v1.8/aws-k8s-cni.yaml
