### ISSUE TITLE
amazon-vpc-cni to isolate the network based on namespace？

### ISSUE THREAD

**Issue by 93910676wangd** [aws/amazon-vpc-cni-k8s#2241]
Hello, I have a question to ask.

I want to perform network isolation based on namespace under EKS.
Can network isolation based on namespace be realized using amazon-vpc-cni?
Just like Calico, the namespace is invisible to the network, and finally the multi-tenant is realized.
Wait for u replay,Thanks.

**Environment**:
- Kubernetes version (use `kubectl version`):1.24
- CNI Version:v1.11.4-eksbuild.1
- OS (e.g: `cat /etc/os-release`):AWS EKS
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
Hi @93910676wangd , so native network isolation on EKS today is achieved using security groups for pods: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html . 

You can also use Calico network policy on EKS: https://docs.aws.amazon.com/eks/latest/userguide/calico.html

Native kubernetes network policy on EKS is currently in progress: https://github.com/aws/containers-roadmap/issues/1478

**Comment by 93910676wangd** [comment]
> Hi @93910676wangd , so native network isolation on EKS today is achieved using security groups for pods: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html .
> 
> You can also use Calico network policy on EKS: https://docs.aws.amazon.com/eks/latest/userguide/calico.html
> 
> Native kubernetes network policy on EKS is currently in progress: [aws/containers-roadmap#1478](https://github.com/aws/containers-roadmap/issues/1478)

thanks for replay
look forward to the early completion of this [Native kubernetes network policy]
