### ISSUE TITLE
Do not provision IP address from the range that AWS uses

### ISSUE THREAD

**Issue by osobh** [aws/amazon-vpc-cni-k8s#225]
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html

according to these docs you do not want to allocate the first 4 ips and last IP address of each subnet you use to an instance. How can we make sure that doesn't happen?

**Comment by labria** [comment]
The plug-in uses AWS API to provision IPs, it does not choose the value of the IP itself. The AWS API will not allocate those reserved IPs.

**Comment by jareksm** [comment]
@labria is that the case for services/ingresss too?

**Comment by labria** [comment]
Ingresses for sure.
Not sure about Services, but they are out of the scope of this CNI plug-in anyway (Service IPs are not VPC-routed, and not attached to real ENIs)

**Comment by jaypipes** [comment]
Related: #652

**Comment by mogren** [comment]
Since this CNI is asking EC2 to assign an IP to the ENI, they will make sure none of the reserved IPs will be used.
