### ISSUE TITLE
VPC CNI Helm Chart v1.2.6 release?

### ISSUE THREAD

**Issue by peterabarr** [aws/amazon-vpc-cni-k8s#2257]
**What happened**:

I noticed that the latest image version of _VPC CNI_ [v1.12.2](https://github.com/aws/amazon-vpc-cni-k8s/commit/0e6031678c050468fee14517d4a2c3f0d3be4d9d) contained the Helm Chart version `v1.2.6` but when trying to upgrade to that version, the chart does not exist. I'm just wondering when the `v1.2.6` chart containing the latest image `v1.12.2` will be released?

**Comment by jdn5126** [comment]
Thanks for letting us know @peterabarr . Looks like the auto-publish on https://github.com/aws/eks-charts is not working as expected for VPC CNI. I am digging into this now, sorry for the delay

**Comment by peterabarr** [comment]
> Thanks for letting us know @peterabarr . Looks like the auto-publish on https://github.com/aws/eks-charts is not working as expected for VPC CNI. I am digging into this now, sorry for the delay

Thank you, I have just seen it come in now!

**Comment by jdn5126** [comment]
Yep, job succeeded this time, thanks for the help!
