### ISSUE TITLE
Expose Clientset, Informers and Listers for External Integrations

### ISSUE THREAD

**Issue by christopherhein** [aws/amazon-vpc-cni-k8s#226]
It would be nice if the CNI plugin exposed the Clientset, Informers and Listers for the new `ENIConfig` CRD type allowing other folks to build integrations using those methods. 

These are code generated via the https://github.com/kubernetes/code-generator project and would allow someone to build and informer based controller.

**Comment by jaypipes** [comment]
so much changed. going to revisit what and how much is still relevant in a separate issue once I've removed the existing operator-framework dependency.
