### ISSUE TITLE
aws-node assigned multiple IP addresses on a host interface.

### ISSUE THREAD

**Issue by rupang790** [aws/amazon-vpc-cni-k8s#2264]
**What happened**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24 (v1.24.8-eks-ffeb93d)
- CNI Version
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 

On one node of self-managed NodeGroup, all pods could not network with any other pods and internet.
So I check that node and I think it could be root-cause about my issue.

This is the result of `ip -br a` on the node, and all spare IPs have been assigned to the node's host interface.
![053AA298-6805-439E-B037-C3D2CBED37BE](https://user-images.githubusercontent.com/40801176/218247638-ca53e046-e742-4ab3-a334-644fbb05e281.png)

I created a pod for testing, but the assigned Pod IP is already assigned to the host, so it appears to be a networking issue due to an IP conflict. To solve this, `/etc/sysconfig/network-scripts` was modified, but it was meaningless. Eventually, it was initialized by `aws-node` pod, and it was confirmed that all IPs were assigned to hosts as before.

Do anyone has same experience? I would like to solve and recover my node.

**Comment by achevuru** [comment]
@rupang790  IP addresses are assigned to ENIs of the node by VPC CNI based on your WARM_IP/MIN_IP/WARM_ENI settings and these are the IPs that are assigned to your Pods. VPC CNI is not an overlay plugin but is VPC aware (i.e.,) each pod gets an IP address from your VPC CIDR. So, the IPs that you see assigned to your node ENIs are assigned to Pods scheduled on the node.

Please refer to this: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/eni-and-ip-target.md

and https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md
