### ISSUE TITLE
Unable to run EFA jobs on EKS Ubuntu nodes

### ISSUE THREAD

**Issue by suruchissingh** [aws/amazon-vpc-cni-k8s#2282]
We have an EKS cluster where we are trying to run EFA enabled jobs on ubuntu nodes, but unable to get this running due to networking issues on pods running on EFA enabled nodes. The error we see are usually related to pods communication , pods scheduled on EFA nodes are unable to communicate with each other.
We have observed that we are facing the issues only with EFA enabled ubuntu nodes , the setup is working fine for amazon linux nodes. We have been able to use EFA in non EKS EC2 ubuntu machines in the past but for some reason this is not working with EKS ubuntu nodes.
As for our use case we need to use ubuntu nodes only , We would like to understand if there are any differences in how vpc cni / EFA networking works for ubuntu and amazon linux. Also are there any similar use cases with successful implementation of EFA on Ubuntu nodes in EKS. This is a major blocker for us, any recommendations/references on this would be highly appreciated.

**Comment by jdn5126** [comment]
@suruchissingh I am not aware of any issues with EFA on Ubuntu nodes. As for the differences in how the CNI works on Amazon Linux vs Ubuntu, there are not really any, though we do have two known issues with Ubuntu in our troubleshooting doc: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#known-issues

If you are using Ubuntu 22.04+, the `system-udev` race condition could possibly be affecting you, but it would not be specific to EFA enabled nodes. If pod to pod communication is broken just on EFA enabled Ubuntu nodes, our best path forward is to debug on those nodes and check things like:
1. Can the container ARP for it's gateway? (to rule out system-udev issue)
2. Are the correct IP rules installed? (to see if a conflicting Ubuntu package is uninstalling them)
3. Where in the routing path is the drop happening? (using tcpdump to see if packet egresses pod veth interface, etc)

For this, I recommend you open up an EKS support case, as I think it will get you the quickest resolution.
