### ISSUE TITLE
VPC CNI plugin creates empty cache files causing "KillPodSandbox" errors when deleting pods

### ISSUE THREAD

**Issue by mrparkers** [aws/amazon-vpc-cni-k8s#2283]
### **What happened**:

I started seeing some pods stuck in a `Terminating` state with the following event being displayed via `kubectl describe pod`:

```
Warning  FailedKillPod   43s (x229 over 49m)  kubelet  error killing pod: failed to "KillPodSandbox" for "a7ea2280-7361-4329-8566-89975485b20e" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"ace318daccdc6ce88de8f8ae7156256a9f17c7a44da4969eb30a2fba68e815db\": failed to get network \"aws-cni\" cached result: decoding version from network config: unexpected end of JSON input"
```

After doing some debugging on the node, I found that the cache file for this pod was empty (the file size is zero):

```
bash-5.1# ls -alh /var/lib/cni/results | grep ace318daccdc6ce88de8f8ae7156256a9f17c7a44da4969eb30a2fba68e815db
-rw-------. 1 root root    0 Feb 24 04:43 aws-cni-ace318daccdc6ce88de8f8ae7156256a9f17c7a44da4969eb30a2fba68e815db-eth0
```

This seems to line up with the error - there is an unexpected end of JSON input because there is no JSON in the file.  Other cache files in this directory look fine and are valid JSON.

Deleting this file caused the pod to finally delete.

The logs of the `aws-node` pod on that node don't look any different from any of the the other `aws-node` pods on other nodes:

```
{"level":"info","ts":"2023-02-24T04:37:19.950Z","caller":"entrypoint.sh","msg":"Validating env variables ..."}
{"level":"info","ts":"2023-02-24T04:37:19.952Z","caller":"entrypoint.sh","msg":"Install CNI binaries.."}
{"level":"info","ts":"2023-02-24T04:37:19.967Z","caller":"entrypoint.sh","msg":"Starting IPAM daemon in the background ... "}
{"level":"info","ts":"2023-02-24T04:37:19.968Z","caller":"entrypoint.sh","msg":"Checking for IPAM connectivity ... "}
{"level":"info","ts":"2023-02-24T04:37:20.974Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2023-02-24T04:37:21.979Z","caller":"entrypoint.sh","msg":"Retrying waiting for IPAM-D"}
{"level":"info","ts":"2023-02-24T04:37:21.997Z","caller":"entrypoint.sh","msg":"Copying config file ... "}
mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied
{"level":"info","ts":"2023-02-24T04:37:22.001Z","caller":"entrypoint.sh","msg":"Successfully copied CNI plugin binary and config file."}
{"level":"info","ts":"2023-02-24T04:37:22.002Z","caller":"entrypoint.sh","msg":"Foregrounding IPAM daemon ..."}
```

### **What you expected to happen**:

My understanding is that it's the CNI plugin that's responsible for populating the files in the `/var/lib/cni/results` directory.  If this is the case, then I think that the VPC CNI plugin should not put empty cache files here.

### **How to reproduce it (as minimally and precisely as possible)**:

I am not sure how to reproduce this naturally, but this happened on a larger node running 200+ pods which had a lot of activity at the time I noticed this issue (many pods creating and terminating at the same time due to a large deployment).

I suppose you might be able to manually clear the contents of one of those cache files and try deleting the associated pod to reproduce the error, but I am not sure how or why that empty file got there in the first place.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}`
- CNI Version: `v1.12.0`
- OS (e.g: `cat /etc/os-release`): `Bottlerocket OS 1.12.0 (aws-k8s-1.24)`
- Kernel (e.g. `uname -a`): `Linux ip-10-3-133-76.us-west-2.compute.internal 5.15.79 #1 SMP Wed Jan 25 03:35:24 UTC 2023 x86_64 GNU/Linux`

**Comment by jdn5126** [comment]
@mrparkers this issue looks specific to SELinux, and the
```
mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied
```
log stands out to me. We did previously have some permissions issues with SELinux (https://github.com/aws/amazon-vpc-cni-k8s/issues/1291), but that doesn't exactly line up with what you are seeing.

As far as `/var/lib/cni/results` go, writing there is the responsibility of the container runtime, not the CNI. I looked for upstream issues, but I did not find anything (other than https://github.com/cri-o/cri-o/issues/3581, which appears to be fixed in your version).

I think we will likely need to move this debugging to upstream for your container runtime, but before that, can you answer:
1. What version of containerd are you using?
2. Can you reproduce this issue?
3. Has this only happened on SELinux?

**Comment by mrparkers** [comment]
Hi @jdn5126, thanks for following up with this.

I also took a look at https://github.com/cri-o/cri-o/issues/3581, but that issue didn't seem to be related, since the cni-loopback files within the same `/var/lib/cni/results` directory seemed to be fine.  It was only the empty `aws-cni-*` files that were causing issues.

> What version of containerd are you using?

```
bash-5.1# ctr --version
ctr github.com/containerd/containerd 1.6.15+bottlerocket
```

> Can you reproduce this issue?

I haven't been able to reproduce it yet.  This happened on a single node in a 200+ node cluster, no other nodes experienced any issues, and I haven't run into this issue again since originally reporting it.

> Has this only happened on SELinux?

This is the first time I've ran into this issue, and we are using SELinux, so I suppose the answer is yes.  The EKS clusters I'm working with were only recently updated to v1.24, switching from docker to containerd, and using Bottlerocket as the OS, so a lot of things have changed recently that could help narrow down the issue.

**Comment by jdn5126** [comment]
I see, I think the next step should be to focus on trying to reproduce this issue, and then you likely will want to engage upstream containerd, as the VPC CNI is not involved with `/var/lib/cni/results`

**Comment by mrparkers** [comment]
Sounds good.  I just experienced this issue again yesterday, so I raised another issue upstream at https://github.com/containerd/containerd/issues/8197

**Comment by jdn5126** [comment]
> Sounds good. I just experienced this issue again yesterday, so I raised another issue upstream at [containerd/containerd#8197](https://github.com/containerd/containerd/issues/8197)

Thanks! I'll follow this issue and see if it requires any input from AWS VPC CNI.

**Comment by stijndehaes** [comment]
I just experienced this today, sadly the issue was closed by a bot. Could we reopen this?

**Comment by jdn5126** [comment]
@stijndehaes reopening, though it is the upstream issue, https://github.com/containerd/containerd/issues/8197, that we will need some help from containerd team for
