### ISSUE TITLE
Unable to install calico manifest on eks 1.25

### ISSUE THREAD

**Issue by miguelhar** [aws/amazon-vpc-cni-k8s#2287]
**What happened**:

Unable to install the calico operator on EKS `1.25`

```
 kubectl  apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml

customresourcedefinition.apiextensions.k8s.io/apiservers.operator.tigera.io created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/imagesets.operator.tigera.io created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/installations.operator.tigera.io created
customresourcedefinition.apiextensions.k8s.io/tigerastatuses.operator.tigera.io created
namespace/tigera-operator created
clusterrolebinding.rbac.authorization.k8s.io/tigera-operator created
clusterrole.rbac.authorization.k8s.io/tigera-operator created
serviceaccount/tigera-operator created
deployment.apps/tigera-operator created
error: resource mapping not found for name: "tigera-operator" namespace: "" from "https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

**Attach logs**

**What you expected to happen**:

Installation is successful. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy eks 1.25
3. kubectl  apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml

**Anything else we need to know?**:

- Seemingly caused by https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/calico-operator.yaml#L4862
- PSPs are removed in k8s 1.25: https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Environment**:
- Kubernetes version (use `kubectl version`): eks 1.25
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
@jdn5126 - We will have to cleanup the documentation here - https://docs.aws.amazon.com/eks/latest/userguide/calico.html for manifest installation.

**Comment by miguelhar** [comment]
Thank you @jdn5126. Will the installation manifest still be maintained:
https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-crs.yaml

**Comment by jdn5126** [comment]
> Thank you @jdn5126. Will the installation manifest still be maintained: https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-crs.yaml

No, so we no longer maintain calico manifests in `config/master/` as we do not have a mechanism to update them as Calico changes them (especially as they change for already released versions). Instead, we point to upstream Calico docs: https://docs.tigera.io/calico/3.25/getting-started/kubernetes/managed-public-cloud/eks , where we recommend helm as the installation method. If you want to apply the manifests themselves, they are stored upstream at https://github.com/projectcalico/calico/tree/master/manifests

**Comment by miguelhar** [comment]
Thank you
