### ISSUE TITLE
pods not able to be given IPs on d3en.12xlarge

### ISSUE THREAD

**Issue by gbucknel** [aws/amazon-vpc-cni-k8s#2309]
**What happened**:
Pods stopped being able to be started on a new d3en.12xlarge node. Perhaps 60 pods were started but then new ones stopped being started correctly with this error in the containerd logs : 
```
plugin type=\"aws-cni\" name=\"aws-cni\" failed (add): add cmd: failed to assign an IP address to container"
```
This is in the ipamd log :
```
"level":"error","ts":"2023-03-09T04:09:07.998Z","caller":"ipamd/ipamd.go:819","msg":"Failed to increase pool size due to not able to allocate ENI AllocENI: error attaching ENI: attachENI: failed to attach ENI: AttachmentLimitExceeded: Interface count 4 exceeds the limit for d3en.12xlarge\n\tstatus code: 400, request id: 04af5d7e-7de9-466c-9ed0-f6998d9b02c2"}
{"level":"info","ts":"2023-03-09T04:09:08.904Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /var/run/netns/cni-e8ab5b75-0d82-291d-272e-6d03881ba08a, Sandbox a0547ad5b4bccfd092d053985e1adcf550dcda88ef66ddbc965f80338b19a397, ifname eth0"}
{"level":"debug","ts":"2023-03-09T04:09:08.904Z","caller":"rpc/rpc.pb.go:713","msg":"AddNetworkRequest: K8S_POD_NAME:\"employer-management-service-feat-new-account-service-78699ps8kg\"  K8S_POD_NAMESPACE:\"employer\"  K8S_POD_INFRA_CONTAINER_ID:\"a0547ad5b4bccfd092d053985e1adcf550dcda88ef66ddbc965f80338b19a397\"  ContainerID:\"a0547ad5b4bccfd092d053985e1adcf550dcda88ef66ddbc965f80338b19a397\"  IfName:\"eth0\"  NetworkName:
{"level":"debug","ts":"2023-03-09T04:09:08.904Z","caller":"datastore/data_store.go:722","msg":"AssignIPv4Address: IP address pool stats: total: 58, assigned 58"}
```
I'm not sure why it tries to add a new ENI if this instance type just supports 3 ENIs. 

**Attach logs**
Understood, will email them. 

**What you expected to happen**:
Pods should be able to be started until it reaches the limit at 89 pods and then they won't be scheduled on the node. . 

**How to reproduce it (as minimally and precisely as possible)**:
Provision more than 60 pods on the node 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-eks-48e63af", GitCommit:"9176fb99b52f8d5ff73d67fea27f3a638f679f8a", GitTreeState:"clean", BuildDate:"2023-01-24T19:17:48Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version `1.12.5`
- OS (e.g: `cat /etc/os-release`):
```
NAME=Bottlerocket
ID=bottlerocket
VERSION="1.12.0 (aws-k8s-1.24)"
PRETTY_NAME="Bottlerocket OS 1.12.0 (aws-k8s-1.24)"
VARIANT_ID=aws-k8s-1.24
VERSION_ID=1.12.0
BUILD_ID=6ef1139f
HOME_URL="https://github.com/bottlerocket-os/bottlerocket"
SUPPORT_URL="https://github.com/bottlerocket-os/bottlerocket/discussions"
BUG_REPORT_URL="https://github.com/bottlerocket-os/bottlerocket/issues"
```
- Kernel (e.g. `uname -a`): `5.15.79`

**Comment by jdn5126** [comment]
Hi @gbucknel , the `d3en.12xlarge` instance supports attaching only 3 ENIs, as you mentioned. What probably happened here is that some IPs were in cooldown mode after the pods were deleted (30 second cooldown). To determine that, you can look for the following log entry:
```
Total IPs/Prefixes = %d/%d, AssignedIPs/CooldownIPs: %d/%d"
```

**Comment by jayanthvn** [comment]
@gbucknel - Are you using custom networking?

**Comment by gbucknel** [comment]
@jayanthvn , no I wasn't. I'll close this, since the instance went away, and it seems like it is expected.
