### ISSUE TITLE
Make all the boolean values case insensitive in aws vpc cni environmental variables. 

### ISSUE THREAD

**Issue by vtgspk** [aws/amazon-vpc-cni-k8s#2311]
**What would you like to be added**:
ENABLE_IPV6=FALSE is enabling the EGRESSV4PLUGIN and as a result an additional interface is added to the EKS pod. Changing from "FALSE" to "false" is fixing the issue. I believe this is because of this [code] I suppose (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/egress-v4-cni-plugin/cni.go#L360).

So please make the boolean values of ENV variables in aws vpc cni  wherever applicable as case insensitive. 
**Why is this needed**:
Good coding standards to have case insensitive values for Boolean.  Had to spend 2+ weeks to figure out this case sensitivity was causing the problem.

**Comment by jdn5126** [comment]
Thanks for the callout @vtgspk, this is definitely something we want to handle in future releases. Will work on getting this assigned. Also marking as a good first issue in case anyone from the community wants to take it before that
