### ISSUE TITLE
Support custom AWS endpoint configuration.

### ISSUE THREAD

**Issue by jihunseol** [aws/amazon-vpc-cni-k8s#2317]
**What would you like to be added**:
Is there any plan to support custom AWS endpoint configuration for AWS VPC CNI plugin?
To use AWS VPC CNI plugin for custom AWS endpoint environment(e.g. testing environment), it would be great to support custom AWS endpoint configuration like below.

  * Using map configuration like aws-load-balancer-controller (format: ec2=URL1,monitoring=URL2)
  * Using environment variable like aws-ebs-csi-driver (format: AWS_EC2_ENDPOINT, AWS_CLOUDWATCH_ENDPOINT)

**Why is this needed**:
In order to use AWS VPC CNI plugin for testing environment(AWS API compatible), it is necessary to support custom AWS endpoint configuration.

**Comment by jdn5126** [comment]
@jihunseol yeah, this was brought up before in https://github.com/aws/amazon-vpc-cni-k8s/pull/2101 . We have been trying to push for no more non-functional environment variables, but an environment variable may be the only reasonable approach here.

If you would like to revive this old PR and follow the approach from ebs-csi-driver (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/pkg/cloud/cloud.go#L252), I am ok with that. Just need to do some testing

**Comment by jihunseol** [comment]
@jdn5126 I noticed that the previously closed pull request has already addressed the issue. It would be helpful to reopen the old PR instead of opening a new one to avoid duplicate work. Thanks for considering the issue.

**Comment by jdn5126** [comment]
That's fine with me too, but I don't think the individual who opened that initial PR is working on this or following it, so it probably needs someone new to drive it

**Comment by jihunseol** [comment]
Thank you for letting me know. If there is no issue, I would be happy to take one the responsibility of driving this pull request forward.

**Comment by jdn5126** [comment]
> 

Awesome, thank you so much for the help!

**Comment by jihunseol** [comment]
I have submitted pull request #2326 to address the issue. As per the approach used in ebs-csi-driver, I have skipped unit testing for this code.
Should I update the README.md file to introduce this new environment variable? If so, I will update the README.md file accordingly.
