### ISSUE TITLE
Non-daemonset PODs failed to start when create with IPV6 family

### ISSUE THREAD

**Issue by gaussye** [aws/amazon-vpc-cni-k8s#2338]
**What happened**:
I created the EKS cluster with IPV6 on with the following config:
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-ipv6-cluster
  version: "1.25"
  region: ap-northeast-1

kubernetesNetworkConfig:
  ipFamily: IPv6

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: latest # optional
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # optional
  - name: kube-proxy
    version: latest # optional

managedNodeGroups:
  - name: x86-al2-on-demand-x2
    amiFamily: AmazonLinux2
    instanceTypes: [ "c6i.32xlarge"]
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true
    updateConfig:
      maxUnavailablePercentage: 33
    labels:
      os-distribution: amazon-linux-2

Non-daemonset pods can not start:
aws-node-r7txk             1/1     Running             0          161m
aws-node-t4lxb             1/1     Running             0          160m
coredns-7c7bdc65d6-jbl7k   0/1     ContainerCreating   0          13m
coredns-7c7bdc65d6-qkr9b   0/1     ContainerCreating   0          162m
kube-proxy-5w58r           1/1     Running             0          2d4h
kube-proxy-ljllr           1/1     Running             0          2d4h

k describe pod coredns-7c7bdc65d6-jbl7k -n kube-system
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               14m                  default-scheduler  Successfully assigned kube-system/coredns-7c7bdc65d6-jbl7k to ip-192-168-7-190.ap-northeast-1.compute.internal
  Warning  FailedCreatePodSandBox  14m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bcc6219329525680110e31743cea7a1ccb3b38b02837e2a12dbbcca40516a0b4": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  13m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "372fabb001aca0cb7d3e5766f2b6ee24f31095e57437588501dfe036112fd030": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  13m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cb06b0d732c66f27a34190dba7f5caea53f960732641cf21be8984009f9ea80b": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  13m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e936f1e381cc09fb6b9fed0766ad899713f738db650cc9dcaa55f091d718cae4": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  13m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7b8c2308be02deef436a4053b5ae7b141cc639111c1e54d5559060ac1cb9f9d7": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  12m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a05aacb4791fb0805c764e8c00125b3c64b69419c7255f45f7866056a72c71f8": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  12m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c8d25f740d71afca07affee205c92ee159eb8509295b1c2cc40462854bba32b5": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  12m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "013c5631c87c188e8b0754cbbacc2bad87d9039d2909a8b1de93dd7a997c5060": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  12m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "944eb338f6c4d71def778e0d1436b3bea59452fd985632c6493aa2dd53c3697f": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container
  Warning  FailedCreatePodSandBox  4m5s (x37 over 11m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "be215c2bcb2a7357252ab8e1e0d88f33f0207560f922e983b16fab0db3217f18": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: failed to assign an IP address to container

Check IPAMD.log
{"level":"info","ts":"2023-03-31T05:37:32.733Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:37:32.733Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:37:32.743Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:37:32.743Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:37:47.732Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:37:47.732Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:37:47.742Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:37:47.743Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:01.733Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:01.733Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:01.743Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:01.743Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:16.732Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:16.732Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:16.742Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:16.742Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:30.733Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:30.733Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}
{"level":"info","ts":"2023-03-31T05:38:30.742Z","caller":"logger/logger.go:52","msg":"Constructed new logger instance"}
{"level":"info","ts":"2023-03-31T05:38:30.742Z","caller":"networkutils/network.go:123","msg":"Initialized new logger as an existing instance was not found"}

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by achevuru** [comment]
`AmazonEKS_CNI_Policy` is IPv4 specific policy. Please refer here for the IAM policy you need to use for IPv6 clusters - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/iam-policy.md#ipv6-mode.

**Comment by gaussye** [comment]
It is working now. Thanks achevuru!
