### ISSUE TITLE
Facing vulnerability issues with golang

### ISSUE THREAD

**Issue by kalpanathanneeru21** [aws/amazon-vpc-cni-k8s#2340]
Facing vulnerability issues with golang older packages versions since all these are outdated/old versioned

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- CNI Version: v1.12.5
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/85505383/229793769-ca2cbd91-d637-48f5-aa14-80323d8b6115.png">
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/85505383/229793993-5743fe94-8c62-429b-b4b5-09e8e2c13047.png">

is there any existing release which is having fixed vulnerabilities or planning to release any time soon. Please update

**Comment by dims** [comment]
@kalpanathanneeru21 `kaas-core` is not something AWS ships in any shape or form AFAICT. there is definitely no `aws-node-init` in this repository.

You may be mixing this up with another vendor. [this one](https://www.google.com/search?q=kaas+mirantis) perhaps?

closing this!
