### ISSUE TITLE
Facing vulnerability issues with golang

### ISSUE THREAD

**Issue by kalpanathanneeru21** [aws/amazon-vpc-cni-k8s#2341]
Facing vulnerability issues with golang older packages versions since all these are outdated/old versioned

			

  |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | aws-vpc-cni-init/879504c6abff45e3f2a8490 365390e5c39904af1/sha256__21605ccf9a37ebb60 5c20faaa466db6b4ce897fd282ea404adc7e47c515c 0a28.tar.gz/init/host-local/github.com/lang/go/go;  |   | github.com/golang/go | < 1.18.7,1.19.0 <= Version < 1.19.2 | 1.18.7,1.19.2 | 2023-03-31T03:31:1 7Z

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/85505383/229809591-283afff4-7b4b-4115-a3a9-c0a3bb68a4ec.png">

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- CNI Version: v1.12.5
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

is there any existing release which is having fixed vulnerabilities or planning to release any time soon. Please update

**Comment by jdn5126** [comment]
@kalpanathanneeru21 the Golang version was updated past this point in the latest release, `v1.12.6`. Please see the release notes: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.6

In the future, please follow the rules on security disclosures: https://github.com/aws/amazon-vpc-cni-k8s#security-disclosures
