### ISSUE TITLE
When using multus and updating VPC CNI from lower to v1.12.6 or vice-versa this error occurs failed to parse config: json: cannot unmarshal number into Go struct field NetConf.mtu

### ISSUE THREAD

**Issue by nbrational** [aws/amazon-vpc-cni-k8s#2346]
**What happened**:
When using multus and updating VPC CNI from lower to v1.12.6 or vice-versa, new PODs get stuck in ContainerCreating with error

```
failed to parse config: json: cannot unmarshal number into Go struct field NetConf.mtu
```

Error when upgrading from lower to v1.12.6

`
20m         Warning   FailedCreatePodSandBox   pod/llb-statefulset-0         Failed to create pod sandbox: ... network for pod "llb-statefulset-0": networkPlugin cni failed to teardown pod "llb-statefulset-0_p1e2az1prismf01" network: delegateDel: error invoking ConflistDel - "aws-cni": conflistDel: error in getting result from DelNetworkList: failed to parse config: json: cannot unmarshal number into Go struct field NetConf.mtu of type string]
`

Error when downgrading from v1.12.6 to lower

`
Apr 06 05:32:34 ip-172-31-72-132.ec2.internal kubelet[5474]: E0406 05:32:34.561313    5474 cni.go:380] "Error deleting pod from network" err="add cmd: error loading config from args: add cmd: error loading config from args: json: cannot unmarshal number into Go struct field NetConf.mtu of type string" pod="default/netshoot-95v7j" podSandboxID={Type:docker ID:2e9248ca95a649ed3b2a475c2efc29ade521e70a2898410dc1406a170129378c} podNetnsPath="" networkType="aws-cni" networkName="aws-cni"
`

Issue resolves if `kube-multus-ds` PODs are restarted

`
k rollout restart ds kube-multus-ds -n kube-system
`

**What you expected to happen**:

multus to dynamically pick changes in `/etc/cni/net.d/10-aws.conflist`

**How to reproduce it (as minimally and precisely as possible)**:

In multus setup, change CNI version say from 1.12.5 to 1.12.6; Create a new POD. It will get stuck in ContainerCreating

**Anything else we need to know?**:

This is related to recent change 
https://github.com/aws/amazon-vpc-cni-k8s/blob/c1839cdaa2a71475aebf19a143c71a915e3aaf8e/CHANGELOG.md#v1126
https://github.com/aws/amazon-vpc-cni-k8s/pull/2295/files

`kube-multus-ds-*` POD generates the `/etc/cni/net.d/00-multus.conf` file upon startup and places it on the host to be consumed by VPC CNI (delegate plugin)

But to generate this file, multus first reads from the `/etc/cni/net.d/10-aws.conflist` file created by VPC CNI

VPC CNI 1.12.6 creates file `/etc/cni/net.d/10-aws.conflist` with double quotes around `"mtu"`
https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.12.6/misc/10-aws.conflist#L18 

VPC CNI 1.12.5 and older creates file /etc/cni/net.d/10-aws.conflist without double quotes around `mtu`
https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.12.5/misc/10-aws.conflist#L18 

Therefore, if VPC CNi version changes between <1.12.6 and 1.12.6, 10-aws.conflist changes and therefore kube-multus-ds-* POD must be restarted to detect that change and create a new conf file of its own which is honored by VPC CNI

I could replicate the issue with worker based on 1.21 1.22 1.23

**Comment by jdn5126** [comment]
@nbrational this is a multus issue, as you concluded, so I suggest filing a bug against multus: https://github.com/k8snetworkplumbingwg/multus-cni/issues

Closing this as there is nothing VPC CNI can do
