### ISSUE TITLE
Facing vulnerability issues with golang and certs

### ISSUE THREAD

**Issue by kalpanathanneeru21** [aws/amazon-vpc-cni-k8s#2349]
Facing vulnerability issues with golang older packages versions since all these are outdated/old versioned

  |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | aws-vpc-cni/github.com/golang/go; aws-vpc-cni/89dadf92f76a666947a113b1f6 f27336def75589/sha256__d9a02349de9b6d0fdd73 c774e9be1f409ecb5163db1f86965fbf570769466d7 e.tar.gz/app/egress-v4-cni/github.com/golang/go; aws-node/89dadf92f76a666947a113b1f6 f27336def75589/sha256__d9a02349de9b6d0fdd73 c774e9be1f409ecb5163db1f86965fbf570769466d7 e.tar.gz/app/grpc-health-probe/github.com/golang/ go; aws-node-init/89dadf92f76a666947a113 b1f6f27336def75589/sha256__8e08d08ae08d23b3 a1b8716817791adbbe17e9d9b2840fa5739a70ee54 78a48b.tar.gz/init/aws-vpc-cni-init/github.com/gol ang/go; aws-node/89dadf92f76a666947a113b1f6 f27336def75589/sha256__d9a02349de9b6d0fdd73 c774e9be1f409ecb5163db1f86965fbf570769466d7 e.tar.gz/app/aws-cni/github.com/golang/go; aws-node/89dadf92f76a666947a113b1f6 f27336def75589/sha256__d9a02349de9b6d0fdd73 c774e9be1f409ecb5163db1f86965fbf570769466d7 e.tar.gz/app/aws-k8s-agent/github.com/golang/go | github.com/golang/go | < 1.19.7,1.20.0 <= Version < 1.20.2 | 1.19.7,1.20.2 | 2023-03-17T03:31:0 4Z
  |   |   |   |   |   |   |  

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/85505383/229809591-283afff4-7b4b-4115-a3a9-c0a3bb68a4ec.png">

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- CNI Version: v1.12.6
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

is there any existing release which is having fixed vulnerabilities or planning to release any time soon. Please update

**Comment by jdn5126** [comment]
@kalpanathanneeru21 please follow the rules for security disclosures: https://github.com/aws/amazon-vpc-cni-k8s#security-disclosures . Closing this, as we track CVEs internally
