### ISSUE TITLE
Pod annotations or labels to ignore secondary ENI usage

### ISSUE THREAD

**Issue by akundrock** [aws/amazon-vpc-cni-k8s#2359]
**What would you like to be added**:

I would like to see the ability to schedule a pod on the primary ENI without using the hostNetwork: true pod spec. Possibly with pod  labels or annotations

**Why is this needed**:

Certain projects create webhooks for upgrading or validating CRD's. Because these interact with the K8s/EKS API directly, I have been experiencing issues that the service becomes unreachable when the webhook's pod is scheduled with the secondary ENI IP addresses.

One workaround is to set the hostNetwork: true flag in a pods spec, but then I run into issues with port overlap between different projects, and this can cause additional nodes to be scheduled (sometimes for a single pod) if the webhook is set up with multiple replicas.

It would be great to schedule pods in the primary subnet/ENI ranges with a simple label/annotation instead of modifying almost every other project (and keeping a list) to use reserved port numbers

Some references:

https://cert-manager.io/docs/installation/compatibility/#aws-eks
External-secrets
Emissary-Ingress

**Comment by jdn5126** [comment]
@akundrock you should be able to reach the k8s API server from a pod deployed behind a secondary ENI, as long as that pod has mounted a service account token that grants access. What VPC CNI version are you using, and have you validated that the pod has permission to access API server?

https://eksctl.io/usage/vpc-cluster-access/#cluster-access talks about how API server can be configured for private/public access.

**Comment by akundrock** [comment]
Thanks for the comment!
VPC CNI version: v1.10.2-eksbuild.1
EKS: 1.23
Nodes: AWS EKS AMI 1.22

The webhook/pods in question worked before using the secondary ENI addresses (so I believe Cluster Roles are set up correctly), but I believe you have pointed me to the right place. I don't have time to work on this today, but I will review the EKS cluster security group to allow access from the additional subnet ranges. This might also explain why I was unable to get nodes to join when in a private / NAT subnet.

I'll get back to you next week.
Thanks!
