### ISSUE TITLE
IP Deallocation delay when multiple enis attached to host

### ISSUE THREAD

**Issue by bikashmishra100** [aws/amazon-vpc-cni-k8s#2363]
**What happened**:
The IP deallocation gets delayed in a particular case. When there are multiple enis attached to host and during the iteration to check freeable cidrs, if the first eni does not return anything, the entire loop exits it seems.

On this occasion, there are two enis attached to the host, one ending with `d6ac` and another ending with `86af`.

> {"level":"debug","ts":"2023-04-22T00:00:03.178Z","caller":"datastore/data_store.go:1104","msg":"ENI eni-***d6ac cannot be deleted because it is primary"}
{"level":"debug","ts":"2023-04-22T00:00:03.178Z","caller":"datastore/data_store.go:1104","msg":"ENI eni-***865f cannot be deleted because it has pods assigned"}

We are tracking two IP addresses which are allocated.

> {"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1412","msg":"Trying to add 10.246.106.92"}
{"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1536","msg":"Adding 10.246.106.92/32 to DS for eni-***865f"}
{"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1536","msg":"IP already in DS"}
{"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1412","msg":"Trying to add 10.246.105.43"}
{"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1536","msg":"Adding 10.246.105.43/32 to DS for eni-***865f"}
{"level":"info","ts":"2023-04-22T00:00:50.702Z","caller":"ipamd/ipamd.go:1536","msg":"IP already in DS"}

We get a unassignment of IP `10.246.105.43`.

> {"level":"info","ts":"2023-04-22T00:03:32.592Z","caller":"rpc/rpc.pb.go:731","msg":"Send DelNetworkReply: IPv4Addr 10.246.105.43, DeviceNumber: 1, err: <nil>"}

When the decrease datastore is invoked, the `d6ac` eni comes first and the loop exits when the over count is > 1.

> {"level":"debug","ts":"2023-04-22T00:04:03.819Z","caller":"ipamd/ipamd.go:662","msg":"Starting to decrease Datastore pool"}
{"level":"debug","ts":"2023-04-22T00:04:03.819Z","caller":"ipamd/ipamd.go:716","msg":"Current warm IP stats : target: 1, short: 0, over: 1, stats: Total IPs/Prefixes = 8/0, AssignedIPs/CooldownIPs: 6/0"}
{"level":"error","ts":"2023-04-22T00:04:03.819Z","caller":"ipamd/ipamd.go:682","msg":"Error finding unassigned IPs for ENI eni-***d6ac"}
{"level":"debug","ts":"2023-04-22T00:04:03.819Z","caller":"ipamd/ipamd.go:662","msg":"Successfully decreased IP pool"}

Now another IP gets unassigned `10.246.106.92`.

> {"level":"info","ts":"2023-04-22T00:04:05.603Z","caller":"rpc/rpc.pb.go:731","msg":"Send DelNetworkReply: IPv4Addr 10.246.106.92, DeviceNumber: 1, err: <nil>"}

Now over is 2, but same thing continues.

> {"level":"debug","ts":"2023-04-22T00:05:03.836Z","caller":"ipamd/ipamd.go:662","msg":"Starting to decrease Datastore pool"}
{"level":"debug","ts":"2023-04-22T00:05:03.836Z","caller":"ipamd/ipamd.go:716","msg":"Current warm IP stats : target: 1, short: 0, over: 2, stats: Total IPs/Prefixes = 8/0, AssignedIPs/CooldownIPs: 5/0"}
{"level":"error","ts":"2023-04-22T00:05:03.836Z","caller":"ipamd/ipamd.go:682","msg":"Error finding unassigned IPs for ENI eni-***d6ac"}
{"level":"debug","ts":"2023-04-22T00:05:03.836Z","caller":"ipamd/ipamd.go:662","msg":"Successfully decreased IP pool"}

When the loop order gets right, the deallocation happens. This time `865f` eni gets picked up first.

> {"level":"debug","ts":"2023-04-22T00:08:03.903Z","caller":"ipamd/ipamd.go:662","msg":"Starting to decrease Datastore pool"}
{"level":"debug","ts":"2023-04-22T00:08:03.903Z","caller":"ipamd/ipamd.go:716","msg":"Current warm IP stats : target: 1, short: 0, over: 2, stats: Total IPs/Prefixes = 8/0, AssignedIPs/CooldownIPs: 5/0"}
{"level":"info","ts":"2023-04-22T00:08:03.903Z","caller":"ipamd/ipamd.go:747","msg":"Deleted ENI(eni-***865f)'s IP/Prefix 10.246.106.92/32 from datastore"}
{"level":"info","ts":"2023-04-22T00:08:03.903Z","caller":"ipamd/ipamd.go:747","msg":"Deleted ENI(eni-***865f)'s IP/Prefix 10.246.105.43/32 from datastore"}
{"level":"error","ts":"2023-04-22T00:08:04.388Z","caller":"ipamd/ipamd.go:682","msg":"Error finding unassigned IPs for ENI eni-***d6ac"}
{"level":"debug","ts":"2023-04-22T00:08:04.388Z","caller":"ipamd/ipamd.go:662","msg":"Successfully decreased IP pool"}

https://github.com/aws/amazon-vpc-cni-k8s/blob/e864016e80cb311bb2f8fc4338ef79e9b3a53e47/pkg/ipamd/ipamd.go#L777

**Attach logs**
Explained above.

**What you expected to happen**:
The unassignment could have happened faster. Due to the ALB target deregistration delay, we got 504s when the container got destroyed and the IP dropped traffic.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
Agreed, we should continue to check for next ENI. 

If you are interested happy to take PRs.

**Comment by bikashmishra100** [comment]
Thanks Jayanth. Sure I can contribute a pull request.

I am trying to understand one phenomenon whether the WarmIPTarget at ENI level or the entire CNI level.

Let's say we have 4 IP addresses and 2 ENIs on the host. There are two IP address available(unassigned) from each of the ENI.

Case 1: If each ENI has one out of the two IP addresses assigned to pods, the deallocate loop frees 1 IP address from each pods. So 2 IP addresses released.

Case 2: If there are two ip address assigned from a single ENI then the total freeable IP address from that ENI is zero and that ENI is skipped. The other ENI just releases 1 IP address above the warmIPTarget level.

**Comment by jayanthvn** [comment]
This section - https://github.com/aws/amazon-vpc-cni-k8s/blob/e864016e80cb311bb2f8fc4338ef79e9b3a53e47/pkg/ipamd/ipamd.go#L774-L788 can be optimized.

So warm settings are applied at cluster level i.e, every node in the cluster will try to maintain the DS pool based on the warm setting..

**Comment by bikashmishra100** [comment]
I submitted the PR https://github.com/aws/amazon-vpc-cni-k8s/pull/2368. Please let me know if any changes required.

**Comment by jdn5126** [comment]
Closing as fixed by #2368
