### ISSUE TITLE
CNI Plugin Not Initialized on some Bottlerocket nodes

### ISSUE THREAD

**Issue by shay-ul** [aws/amazon-vpc-cni-k8s#2365]
**What happened**:
We are running Bottlerocket nodes on EKS 1.25 with Karpenter and some very basic user data:
```
[settings]
[settings.kubernetes]
allowed-unsafe-sysctls = ["net.core.somaxconn"]
registry-qps = 20
```

The cluster is configured for Custom Networking and prefix-delegation.

Occasunally (not too often) a node will be stuck NotReady. While exploring the journal on the node, we see the usual error which indicates something is not working with the VPC CNI:

`"Error syncing pod, skipping" err="network is not ready: container runtime network notready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"`

We do not have IP Address shortage on our subnets.
The interesting thing is that the `/var/log/aws-routed-eni` directory is missing, so is the suppot script which should be located at `/opt/cni/bin/aws-cni-support.sh`

I have read that for the CNI Plugin to initialize (IPAMD), the `aws-node` daemonset should spin up on the node first.
The `aws-node` pod that should be scheduled to the node is stuck Pending and has the following events:
```
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  59m (x9 over 62m)      default-scheduler  0/65 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  54m (x47 over 82m)     default-scheduler  0/74 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  49m (x7 over 50m)      default-scheduler  0/80 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  44m (x43 over 80m)     default-scheduler  0/79 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  34m (x36 over 41m)     default-scheduler  0/83 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  24m (x33 over 31m)     default-scheduler  0/78 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  19m (x5 over 19m)      default-scheduler  0/76 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  14m (x5 over 14m)      default-scheduler  0/72 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  9m14s (x9 over 10m)    default-scheduler  0/69 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  4m6s (x11 over 8m52s)  default-scheduler  0/68 nodes are available: 1 Insufficient memory.
```

I cannot wrap my head around why "Insufficient memory" is even a thing, since we're speaking off a `c5a.2xlarge` node.

**Attach logs**

**What you expected to happen**:

A node should spin up Ready, aws-routed-eni directory with ipamd logs should exist, and `aws-cni-support.sh` should also exist.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
EKS 1.25
- Kubernetes version (use `kubectl version`):
Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af"
- CNI Version
v1.12.6-eksbuild.1
- OS (e.g: `cat /etc/os-release`):
Bottlerocket OS 1.13.4 (aws-k8s-1.25)
- Kernel (e.g. `uname -a`):
5.15.102

**Comment by shay-ul** [comment]
Thanks for the feedback, unfortunately (or not?) I'm still waiting for this to happen again, for some reason all nodes worked perfectly for the past couple of days.

**Comment by jdn5126** [comment]
Gotcha, so I would check in `/var/log/messages` to see if there are any kernel logs related to memory issues. Other than that, you can install the EKS log collector script manually from https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/linux/eks-log-collector.sh, though it is probably already there if the nodes are running fine now. The relevant logs may have rolled over by now, but yeah if this happens again, definitely try to run the log collector script as soon as possible

**Comment by jdn5126** [comment]
@shay-ul Got it, I subscribed to https://github.com/bottlerocket-os/bottlerocket/issues/3076 so that I can follow along. One note, it looks like your `aws-node` pod is still mounting the dockershim socket: `/var/run/dockershim.sock`. This was a known issue we had in the past when upgrading to `v1.12.0+` (as opposed to a fresh install). It does not hurt anything, but you can manually remove that mount from the daemonset with `kubectl edit ds aws-node -n kube-system`

**Comment by ArtemChekunov** [comment]
To solve the issue, you need to initialise the addon before `compute` 

example:
```
  cluster_addons = {
    vpc-cni = {
      most_recent    = true
      before_compute = true
    }
}
```

**Comment by jgournet** [comment]
I've hit that issue now, when moving from eks 1.33 to eks 1.34 when trying deploy core-dns addon

Note:
- we do not have aws-vpc-cni installed neither in 1.33 nor 1.34 and wanted to avoid installing it.
- eks-pod-identity-agent does start without issues on those notReady nodes
- /etc/cni/net.d/ is empty in 1.34 (but contains 10-aws.conflist in 1.33)
