### ISSUE TITLE
[POD_ENI] Something wrong with r7g.medium instances

### ISSUE THREAD

**Issue by WesselAtWork** [aws/amazon-vpc-cni-k8s#2369]
We recently set up our EKS cluster with karpenter, vpc-cni, EKS Custom Networking and prefix delegation.

So far everything works great!

However we are running into the following issue specifically with `r7g.medium` instances.

For some reason the trunk interface never gets attached but the vpc cni think it has.

```json
{"level":"debug","ts":"","caller":"retry/util.go:51","msg":"Node found \"ip.region.compute.internal\" - no of labels - 30"}
{"level":"debug","ts":"","caller":"retry/util.go:51","msg":"Node label \"vpc.amazonaws.com/has-trunk-attached\" is already \"false\""}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:2143","msg":"Current warm IP stats : target: 1, short(prefixes): 1, over(prefixes): 0, stats: Total IPs/Prefixes = 0/0, AssignedIPs/CooldownIPs: 0/0"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:683","msg":"Starting to increase pool size"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:796","msg":"Current warm IP stats : target: 1, short(prefixes): 1, over(prefixes): 0, stats: Total IPs/Prefixes = 0/0, AssignedIPs/CooldownIPs: 0/0"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:815","msg":"Node found \"ip.region.compute.internal\" - no of taints - 1"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:927","msg":"Current warm IP stats : target: 1, short(prefixes): 1, over(prefixes): 0, stats: Total IPs/Prefixes = 0/0, AssignedIPs/CooldownIPs: 0/0"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:2232","msg":"Prefix target is 1, short of 1 prefixes, free 0 prefixes"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:1047","msg":"ToAllocate: 1"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:1050","msg":"Skip the primary ENI for need IP check"}
{"level":"debug","ts":"","caller":"ipamd/ipamd.go:683","msg":"Skipping ENI allocation as the max ENI limit of 2 is already reached (accounting for 0 unmanaged ENIs and 1 trunk ENIs)"}
```

Very strange. The CNI can see that there is no trunk attached: `Node label vpc.amazonaws.com/has-trunk-attached is already false` but then when it gets to calculating if the node has enough ENI's available it accounts for the trunk eni. But it is never attached.
Viewing the instance in the console I can see the primary eni but no secondary eni.

Can also verify on the node that there is no other interface connected:

```sh
# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast qlen 1000
    link/ether 0a:8e:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
```

I know this isn't some configuration issue because we have multiple `c7g.medium` running fine in cluster.  
These two instances have identical networking limits in the [vpc-resource-controller](https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/aws/vpc/limits.go)

https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/0c6381a1ef46b1315dbe3b88d453115a1623e88f/pkg/aws/vpc/limits.go#L1769-L1781

https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/0c6381a1ef46b1315dbe3b88d453115a1623e88f/pkg/aws/vpc/limits.go#L7182-L7194

I don't know where else to look to try and find out why the resource controller can't assign a trunk interface on these instances specifically. Any advice?

**Environment**:
- Kubernetes version (use `kubectl version`): EKS v1.23
- CNI Version:  v1.12.6-eksbuild.1

**Comment by jdn5126** [comment]
@WesselAtWork The log about skipping ENI allocation is a red herring, as it is the VPC Resource Controller's responsibility to attach the trunk ENI and then update that label to true. The VPC CNI discovers the trunk ENI after it is attached, so if you can see in the console that it is not attached, this points to a VPC Resource Controller issue. From VPC CNI perspective, everything is good, it just needs to wait for the trunk ENI to be attached. I am pulling in some more help for this to figure out the next debugging step. This being instance specific is definitely very strange.

**Comment by WesselAtWork** [comment]
Oh cool!

I was completely unaware that this could have been a potential issue! 💯 
Thank you so much for the quick response!

Is there a place I can see the current status or the versions of controllers (like the VPC controller) in my EKS cluster? Just wondering so I can keep track.

**Comment by haouc** [comment]
@WesselAtWork currently the version is not available to public. We are making a plan to expose the info to users by some way. You can track [this open issue](https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/216).
