### ISSUE TITLE
Disable auto provision additional eni

### ISSUE THREAD

**Issue by mikehalof** [aws/amazon-vpc-cni-k8s#239]
Hi,
I do have a requirement to disable the auto-allocation of new ENI of cni-aws plugin. Basically I would like to have only ONE eth0 attached to a worker node, with the maximum # allocated IP.
Is there a configuration that allow me to accomplish that? 

Thanks
MikeH

**Comment by mogren** [comment]
`MAX_ENI`  
Type: Integer  
Default: None  
Specifies the maximum number of ENIs that will be attached to the node. When MAX_ENI is unset or 0 (or lower), the setting is not used, and the maximum number of ENIs is always equal to the maximum number for the instance type in question. Even when MAX_ENI is a positive number, it is limited by the maximum number for the instance type.
