### ISSUE TITLE
Fix release workflow

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2410]
**What happened**:

Release workflow will help generate manifests, release artifacts and EKS charts PRs.

**Attach logs**

Failed workflow

**What you expected to happen**:
Reduce release time.

**How to reproduce it (as minimally and precisely as possible)**:
Cut a new release

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by orsenthil** [comment]
This has been fixed by this PR - https://github.com/aws/amazon-vpc-cni-k8s/pull/2398/files

**Comment by orsenthil** [comment]
If the intention was if need more automation, we can capture that as a specific task.
