### ISSUE TITLE
Missing format string in VPC CNI helper info log

### ISSUE THREAD

**Issue by rittneje** [aws/amazon-vpc-cni-k8s#2420]
https://github.com/aws/amazon-vpc-cni-k8s/blob/b9ec2ff5999549b7db2fca86df9a88dbdfa4473b/cmd/cni-metrics-helper/metrics/pod_watcher.go#L59

> {"level":"info","ts":"2023-06-14T10:56:00.313Z","caller":"metrics/cni_metrics.go:209","msg":"Total aws-node pod count:- %!(EXTRA int=7)"}

**Comment by jdn5126** [comment]
Thanks for filing @rittneje , we are happy to take PRs if you have the bandwidth
