### ISSUE TITLE
Document VPC CNI helper metrics

### ISSUE THREAD

**Issue by rittneje** [aws/amazon-vpc-cni-k8s#2421]
The documentation for the VPC CNI helper lists the names of the metrics that it will report, but does not explain what they mean, or how to use them to monitor the health of the cluster. Please add more detail on these points. https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/README.md

**Comment by jdn5126** [comment]
Thanks for filing @rittneje , we are happy to take PRs if you have the bandwidth

**Comment by rittneje** [comment]
@jdn5126 Is there any existing reference that explains them?

**Comment by rittneje** [comment]
not stale

**Comment by rittneje** [comment]
not stale

**Comment by rittneje** [comment]
not stale

**Comment by sidewinder12s** [comment]
> @jdn5126 Is there any existing reference that explains them?

Just the code implementing them: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/utils/prometheusmetrics/prometheusmetrics.go#L31

**Comment by jdn5126** [comment]
Closing following the merge of #2786
