### ISSUE TITLE
VPC CNI Configuration Variable ENI source/destination check false

### ISSUE THREAD

**Issue by rolvhil** [aws/amazon-vpc-cni-k8s#2441]
What would you like to be added:
The VPC CNI creates and attaches new ENIs to instances based on the needs, which usually corresponds to the number of Pods. The added ENIs have source/destination check set to true. The request is a Configuration Variable for VPC CNI to set the source/destination check to false for secondary ENIs created and attached by VPC CNI

e.g. ENI_SOURCE_DESTINATION_CHECK=false

Why is this needed:
To allow transitive traffic to/from pods with secondary IPs created by VPC CNI

Use case:
access the pods directly (e.g ssh) from the outside network (e.g on-premises)

current workaround:
https://github.com/rolvhil/Lambda-source-dest-check-disable-secondary-interface

**Comment by jdn5126** [comment]
@rolvhil this looks like a duplicate of https://github.com/aws/amazon-vpc-cni-k8s/issues/2223. Can you answer my questions on that issue, and then I can close this as a duplicate?

**Comment by rolvhil** [comment]
@jdn5126 yes its the same as [#2223](https://github.com/aws/amazon-vpc-cni-k8s/issues/2223), however this is a different use case from https://github.com/aws/amazon-vpc-cni-k8s/issues/1910. The use case is just access the pods directly (e.g ssh) from the outside network (e.g on-premises) via the secondary ENI.

**Comment by rolvhil** [comment]
@jdn5126 the use case or architecture does not have a loadbalancer (the application  will not use one) and there is no public IPs. The client will not have eks access via kubectl.

**Comment by jdn5126** [comment]
Sorry, I do not understand the request here then. Can you work with your TAM to provide a more detailed request/spec, and we can connect to discuss after that?

**Comment by rolvhil** [comment]
accessing the pod was just one example for simplification. But let me put why its needed. An application running metallb creates a pod with a VIP. The VIP is not part of the VPC CIDR and used as ingress for receiving traffic. If the pod scales and consumes an IP from a second interface created by VPC CNI. The VIP created from the scaled PODs will not be accessible because source/dest check on the interface is not disabled. I hope the use case is clearer now.

**Comment by jdn5126** [comment]
> @jdn5126 An application running metallb creates a pod with a VIP. The VIP is not part of the VPC CIDR and used as ingress for receiving traffic. If the pod scales and consumes an IP from a second interface created by VPC CNI. The VIP created from the scaled PODs will not be accessible because source/dest check on the interface is not disabled.

I am still not sure that I follow, but it sounds like you have a problem routing to/from the VIP when the pod is behind a secondary ENI instead of the primary ENI. How is routing for this VIP configured in your VPC? This does feel like the use case for a Kubernetes service, but we might be able to do something with VPC routing.

**Comment by rolvhil** [comment]
@jdn5126 unfortunately this is not the type where we can use a Kubernetes service. The application advertises the VIP via BGP through the metallb plugin. In AWS, by default ENI has source/destination check enabled, which prevents traffic  through that ENI dropped if the destination IP is not part of the VPC CIDR. We need the capability to disable that flag when an ENI is created from VPC CNI. Its not actually about VPC routing.

**Comment by jdn5126** [comment]
Is deploying these pods in host networking mode an option? We will discuss internally, but I am very hesitant to provide a way to disable this check. Another option you have is during node initialization, you can loosen the rp filter check with `echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter`. That's essentially what any env var would do anyway

**Comment by rolvhil** [comment]
i don't think rp_filter can influence here. The traffic will be dropped by the vpc before it reaches the machine.

**Comment by jdn5126** [comment]
Hmm.. I don't think VPC routing does any such check, as I think the workaround that you linked to is just setting `rp_filter=2` for that specific ENI. I would be interested to see if that works for you, but either way I think we will want to work with your TAM and setup a discussion.

**Comment by rolvhil** [comment]
I do not understand how rp_filter=02 comes here. you can do a simple test. create an instance. on the routing table put VIP destination IP which is not part of the VPC CIDR, next hop ENI of the ec2 instance. then try to ping that VIP IP, you wont be able to ping it, if you enable vpc flow logs you will notice that traffic is not reaching the ENI (its being dropped by the VPC). If you then disable source/destination check then you notice you can now ping the VIP.

Are you referring to this workaround? https://github.com/rolvhil/Lambda-source-dest-check-disable-secondary-interface . the workaround has nothing to do with rp_filter. it watches for events that creates an ENI from a subnetid, lambda is then triggered to disable the source/destination check.

**Comment by jdn5126** [comment]
I assumed that the source-destination check on an ENI created by EC2 simply mapped to the RP filter in Linux, but it seems like that is not the case. So what you are asking for boils down to the ability to specify whether the source-dest check is enabled when we create an ENI here: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/awsutils/awsutils.go#L767

Having an environment variable to allow this seems ok to me, but I will discuss with the team further. In the meantime, we are happy to take a PR for something like this if you are able to contribute
