### ISSUE TITLE
Panic in event recorder with missing IAM permission - 1.13.2

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2466]
**What happened**:

If there is a node IAM permission issue then on aws-node startup, refreshSGID which is called as part of awsutils init will fail to update the ENI and tries to add a pod event. But the event recorder is initialized after awsutils init.

We are passing `c.eventRecorder` - > https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.13.2/pkg/ipamd/ipamd.go#L399 

But the value is set here - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.13.2/pkg/ipamd/ipamd.go#L412

Needs code reordering.

**Attach logs**

**What you expected to happen**:
No panic, just log event.

**How to reproduce it (as minimally and precisely as possible)**:
Remove IAM permission and restart aws-node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version - 1.13.2
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
Closing as fixed by #2467
