### ISSUE TITLE
Support LLQ on EKS worker nodes

### ISSUE THREAD

**Issue by raghugorthy** [aws/amazon-vpc-cni-k8s#2469]
Need support for enabling LLQ on EKS Worker Nodes.

Related Issue: https://github.com/amzn/amzn-drivers/issues/142
**What would you like to be added**:

**Why is this needed**:

**Comment by jdn5126** [comment]
Hi @raghugorthy , this repository is only for the Amazon VPC CNI and IPAMD. I think https://github.com/aws/containers-roadmap/issues is a better place to file an issue. Please include more information in that issue

**Comment by raghugorthy** [comment]
Created issue in Container roadmap closing this issue
