### ISSUE TITLE
 POD_SECURITY_GROUP_ENFORCING_MODE not avaialble in the configuration values of the VPC CNI 

### ISSUE THREAD

**Issue by haofeif** [aws/amazon-vpc-cni-k8s#2479]
**What would you like to be added**:
Add `POD_SECURITY_GROUP_ENFORCING_MODE` to the configuration value as quoted in the [code](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L163-L203)

**Why is this needed**:

If customers would like to use Network Policy together with Security Group for Pods, it needs to change the parameters of VPC CNI according to [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)

* If you're using version 1.10 or earlier of the Amazon VPC CNI plugin, or version 1.11 with `POD_SECURITY_GROUP_ENFORCING_MODE=strict`, which is the default setting, then Kubernetes services of type NodePort and LoadBalancer using instance targets with an externalTrafficPolicy set to Local aren't supported with Pods that you assign security groups to. For more information about using a load balancer with instance targets, see [Network load balancing on Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html). If you're using version 1.11 or later of the plugin with `POD_SECURITY_GROUP_ENFORCING_MODE=standard`, then instance targets with an externalTrafficPolicy set to Local are supported.

**Comment by jdn5126** [comment]
@haofeif sorry, I do not understand the request here. `POD_SECURITY_GROUP_ENFORCING_MODE` is already configurable as an environment variable. You can set it in the [helm chart](https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/values.yaml) or add it to the manifest you are using

**Comment by haofeif** [comment]
Hi @jdn5126 . The use case is we are leveraging the AWS Managed VPC CNI, and we would like to use Terraform to put in "configuration values" in the [terraform document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon)

In short, we would like to  get the `POD_SECURITY_GROUP_ENFORCING_MODE` into the `configuration_value`, instead of changing the helm chart if this makes sense

```terraform
resource "aws_eks_addon" "example" {
  cluster_name                = "mycluster"
  addon_name                  = "coredns"
  addon_version               = "v1.10.1-eksbuild.1"
  resolve_conflicts_on_create = "OVERWRITE"

  configuration_values = jsonencode({
    replicaCount = 4
    resources = {
      limits = {
        cpu    = "100m"
        memory = "150Mi"
      }
      requests = {
        cpu    = "100m"
        memory = "150Mi"
      }
    }
  })
}
```

**Comment by jdn5126** [comment]
`POD_SECURITY_GROUP_ENFORCING_MODE` is only configurable via the managed addon in VPC CNI `v1.12.1`+. You can see the configurable schema with:
```
aws eks describe-addon-configuration --addon-name vpc-cni --addon-version v1.12.1-eksbuild.1 | jq -r .configurationSchema | jq .
```

**Comment by jdn5126** [comment]
Closing this as it is not an issue
