### ISSUE TITLE
CRD spec.names unused field

### ISSUE THREAD

**Issue by ryanli-me** [aws/amazon-vpc-cni-k8s#248]
https://github.com/aws/amazon-vpc-cni-k8s/blob/07363123942c6fa03da6a7737a2d15817a7c2f8e/config/v1.2/aws-k8s-cni.yaml#L125

I'm using `kubediff` to check diff my running env with the config file. I see that `spec.names` doesn't contain `scope` field with `kubectl get crd -oyaml --export`. Maybe this field is not used?

**Comment by mogren** [comment]
Fix merged
