### ISSUE TITLE
Authorization needed to pull cni-metrics-helper image

### ISSUE THREAD

**Issue by dantamsdb** [aws/amazon-vpc-cni-k8s#2484]
**What happened**:

Fetching the cni-metrics-helper image (https://602401143452.dkr.ecr.us-west-2.amazonaws.com/cni-metrics-helper:v1.13.3) requires authorization. 

I would expect to be able to download the image without credentials.

How am I supposed to fetch it if I do not have any credentials?

I am new to Kubernetes, so I apologize if this is a silly newbie question.

**Environment**:
N/A

**Comment by orsenthil** [comment]
You will need login to the ECR registry to pull the image - https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html#registry-auth-token

For your EKS clusters and nodes in your EKS clusters,  the nodes authenticate using an IAM role that has permissions to read from the ECR registry, so they are auto-authenticated and EKS nodes can pull the images from those registries directly.
