### ISSUE TITLE
Unable to configure DISABLE_TCP_EARLY_DEMUX in the console addon or through configuration_values in the aws_eks_addon resource

### ISSUE THREAD

**Issue by mattcberkeley** [aws/amazon-vpc-cni-k8s#2491]
**What happened**:
I've tried many combinations however I'm unable to set DISABLE_TCP_EARLY_DEMUX to true both through the console and through the aws_eks_addon terraform resource. 

Some example combinations tried through the console and terraform:
`{"env":{"ENABLE_POD_ENI":"true"},"InitEnv": {"DISABLE_TCP_EARLY_DEMUX": "true"}}`
_$.InitEnv: is not defined in the schema and the schema does not allow additional properties_

`{"env":{"ENABLE_POD_ENI":"true", "DISABLE_TCP_EARLY_DEMUX": "true"}}`
_$.env.DISABLE_TCP_EARLY_DEMUX: is not defined in the schema and the schema does not allow additional properties]_

`{"env":{"ENABLE_POD_ENI":"true"},"Init": {"env": {"DISABLE_TCP_EARLY_DEMUX": "true"}}}`
_$.Init: is not defined in the schema and the schema does not allow additional properties_

According to the schema in the console the first option above should be correct.

For reference the terraform is as below, the configuration values are jsonencoded and passed into configuration_values  property of the aws_eks_addon:
```
// this resource is the module aws-vpc-cni
resource "aws_eks_addon" "vpc_cni" {
  cluster_name             = var.addon_context.eks_cluster_id
  addon_name               = local.name
  addon_version            = try(var.addon_config.addon_version, data.aws_eks_addon_version.this.version)
  resolve_conflicts        = try(var.addon_config.resolve_conflicts, "OVERWRITE")
  service_account_role_arn = local.create_irsa ? module.irsa_addon[0].irsa_iam_role_arn : try(var.addon_config.service_account_role_arn, null)
  preserve                 = try(var.addon_config.preserve, true)
  **configuration_values     = try(var.addon_config.configuration_values, null)**

  tags = merge(
    var.addon_context.tags,
    try(var.addon_config.tags, {})
  )
}
...
module "aws_vpc_cni" {
  source = "./aws-vpc-cni"

  enable_ipv6 = false
  addon_config = {
    kubernetes_version = local.eks_cluster_version,
    **configuration_values = jsonencode**({
      "env" : {
        "ENABLE_POD_ENI" : "true"  #this should do the same as this command: kubectl set env daemonset aws-node -n kube-system ENABLE_POD_ENI=true
      }
      # "InitEnv": {
      #   "env": {
      #     "DISABLE_TCP_EARLY_DEMUX" : "true" # attempt to address Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container
      #   }
      # }
    })
  } 
```

**Attach logs**
See above errors and 

> │ Error: updating EKS Add-On (clustername:vpc-cni): InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.InitEnv: is not defined in the schema and the schema does not allow additional properties]
> │ {
> │   RespMetadata: {
> │     StatusCode: 400,
> │     RequestID: "b678ea40-7abe-45c3-a552-47ffae0173b2"
> │   },
> │   AddonName: "vpc-cni",
> │   ClusterName: "clustername",
> │   Message_: "ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.InitEnv: is not defined in the schema and the schema does not allow additional properties]"
> │ }

**What you expected to happen**:
It should be possible to set the DISABLE_TCP_EARLY_DEMUX variable at creation/through the console and not by running the manual step:
```
kubectl patch daemonset aws-node
-n kube-system
-p '{"spec": {"template": {"spec": {"initContainers": [{"env":[{"name":"DISABLE_TCP_EARLY_DEMUX","value":"true"}],"name":"aws-vpc-cni-init"}]}}}}'
```

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to set DISABLE_TCP_EARLY_DEMUX 

in the EKS VPC-CNI addon edit page. e.g. using the below configuration.
`{"env":{"ENABLE_POD_ENI":"true"},"InitEnv": {"DISABLE_TCP_EARLY_DEMUX": "true"}}`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27
- CNI Version v1.13.4-eksbuild.1
- OS (e.g: `cat /etc/os-release`): bottlerocket /ami-031aaabc376771a72
- Kernel (e.g. `uname -a`): n/a

**Comment by jdn5126** [comment]
@mattcberkeley you want:
```
{
  "init": {
    "env": {
      "DISABLE_TCP_EARLY_DEMUX": "true"
    }
  }
}
```

**Comment by mattcberkeley** [comment]
Oh man, thank you @jdn5126 I thought I'd tried that combination but evidentially not. Thank you.

**Comment by jdn5126** [comment]
JSON schema is case-sensitive and hierarchical, and the names are derived from the `properties` fields
