### ISSUE TITLE
IPTables (DNAT/SNAT) within POD

### ISSUE THREAD

**Issue by jbreed** [aws/amazon-vpc-cni-k8s#2493]
**What happened**:

For a custom component we have to integrate hardware into our EKS cluster, there is a need to setup a tunnel from a pod within the cluster to an external node outside of the cluster. 

[---------------EKS--------------]
TunnelPod < - > ProxyPod < - > EC2 Bastion < - > Hardware

The ProxyPod and Bastion leverage IPTables to DNAT traffic between while doing a masquerade to change the source address to itself. This worked a while back before we upgraded our EKS clusters from 1.23 to 1.27, but the past few days I have been debugging why the masquerading is not working and sometimes it only works in one direction. 

**TunnelPod:** Creates a tunnel with the remote side noted as the proxy pod

**ProxyPod:** Has DNAT rules (NET_ADMIN) for tunnel traffic from TunnelPod to forward to the Bastion and the other way as well. Also, masquerading is setup on eth0. **_The issue is here_**. Using tcpdump I was seeing the bastion traffic get DNAT'd and sent to the however, the source IP is not updated. It has been inconsistent the other way in which sometimes the TunnelPod to Bastion traffic would get masqueraded and other times I would stand this up and it would do no SNAT/Masq similar to the other direction.

**EC2 Bastion:** Similar to ProxyPod just doing iptable DNAT with masquerading

**Hardware**: Similar config to TunnelPod in that it creates the tunnel to what it thinks is the bastion node.

When troubleshooting this I tried to create SNAT's with no changes seen in the tcpdump. I also deleted the DNAT entries in the proxypod and was still seeing the traffic get translated to be forwarded. The fact the DNAT rules were working really makes this part confusing. I would think the AWS VPC CNI would be using iptables on the node level and not the linux namespace level, but not entirely sure. I have AWS_VPC_K8s_CNI_EXTERNALSNAT set to true so traffic going to the bastion has the proxy pods IP address and not the nodes IP. _**Does anyone have an idea on what could be causing iptables masquerading to not work, or be inconsistent?**_ 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27
- CNI Version: amazon-k8s-cni:v1.12.6-eksbuild.2
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10

**Comment by jbreed** [comment]
Same results when using version: amazon-k8s-cni:v1.13.4-eksbuild.1

**Comment by jbreed** [comment]
Same results when using version: amazon-k8s-cni:v1.13.4-eksbuild.1

**Comment by jdn5126** [comment]
Glad to see that you figured it out @jbreed !
