### ISSUE TITLE
 FailedScheduling -   0/12 nodes are available: 12 Insufficient vpc.amazonaws.com/pod-eni.

### ISSUE THREAD

**Issue by saikumar21698** [aws/amazon-vpc-cni-k8s#2494]
Containers:
  amazon-mq-proxy:
    Image:     xxxxxxxxxxxx
    Ports:       5673/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:                        500m
      memory:                     40Mi
      vpc.amazonaws.com/pod-eni:  1
    Requests:
      cpu:                        5m
      memory:                     20Mi
      vpc.amazonaws.com/pod-eni:  1
    Environment:                  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5jz9r (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  kube-api-access-5jz9r:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             vpc.amazonaws.com/pod-eni:NoSchedule op=Exists
Events:
  Type     Reason             Age                  From                Message
  ----     ------             ----                 ----                -------
  Normal   NotTriggerScaleUp  2m6s (x61 over 12m)  cluster-autoscaler  pod didn't trigger scale-up: 12 Insufficient vpc.amazonaws.com/pod-eni
  Warning  FailedScheduling   23s (x13 over 12m)   default-scheduler   0/12 nodes are available: 12 Insufficient vpc.amazonaws.com/pod-eni.

Please help me with the fix

**Comment by jdn5126** [comment]
@saikumar21698 you are going to need to provide much more information to get help with something like. I cannot see the link to the Amazon VPC CNI, so I am going to close this and suggest that you open an EKS support ticket from your AWS console.
