### ISSUE TITLE
InvalidNetworkInterfaceID.NotFound and EC2 metadata

### ISSUE THREAD

**Issue by Kulagin-G** [aws/amazon-vpc-cni-k8s#2497]
**What happened**:

Today, during verification of our EKS cluster v1.24 after `aws-vpc-cni` upgrade we've found that 2 `aws-node-*` pods (from ~80) started to generate `awscni_aws_api_error_count` metrics.

```
# HELP awscni_aws_api_error_count The number of times AWS API returns an error
# TYPE awscni_aws_api_error_count counter
awscni_aws_api_error_count{api="DescribeNetworkInterfaces",error="InvalidNetworkInterfaceID.NotFound"} 83
awscni_aws_api_error_count{api="IMDSMetaDataOutOfSync",error="InvalidNetworkInterfaceID.NotFound"} 84
awscni_aws_api_error_count{api="ModifyNetworkInterfaceAttribute",error="InvalidNetworkInterfaceID.NotFound"} 1
```

During an investigation, we discovered that the plugin upgrade was not a real reason and the issue also was happening with a previous version.

Looking into a code - https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.13.4/pkg/awsutils/awsutils.go#L1002 it became more clear that ENI-related-data comes from EC2 metadata. And of course, in EC2 metadata we see 3 ENI interfaces instead of 2 that are really visible and attached to EC2.

Example:
```
[root@ip-10-18-XXX-X ~]# curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs
02:9c:08:07:bb:2c/
02:ae:ef:9e:ff:38/
02:f0:3e:0d:a2:98/
[root@ip-10-18-XXX-X ~]#
[root@ip-10-18-XXX-X ~]# ip a |grep -E "02:9c:08:07:bb:2c|02:ae:ef:9e:ff:38|02:f0:3e:0d:a2:98"
    link/ether 02:ae:ef:9e:ff:38 brd ff:ff:ff:ff:ff:ff
    link/ether 02:9c:08:07:bb:2c brd ff:ff:ff:ff:ff:ff
[root@ip-10-18-XXX-X ~]#
```

`02:9c:08:07:bb:2c` and `02:ae:ef:9e:ff:38` are real interfaces attached to EC2 instance, `02:f0:3e:0d:a2:98` is an old one that was removed, see logs below.

Part of `ipamd.log` and ENI interface lifecycle :
```
{"level":"info","ts":"2023-08-09T17:22:42.310Z","caller":"awsutils/awsutils.go:742","msg":"Created a new ENI: eni-01ea"}
...
{"level":"info","ts":"2023-08-09T17:22:43.874Z","caller":"ipamd/ipamd.go:852","msg":"Successfully created and attached a new ENI eni-01ea to instance"}
{"level":"debug","ts":"2023-08-09T17:22:47.874Z","caller":"datastore/data_store.go:1104","msg":"ENI eni-01ea cannot be deleted because it is too young"}
....
{"level":"debug","ts":"2023-08-09T17:22:52.875Z","caller":"ipamd/ipamd.go:930","msg":"Found ENI eni-01ea that has less than the maximum number of IP/Prefixes addresses alloca
ted: cur=1, max=14"}
{"level":"debug","ts":"2023-08-09T17:23:13.355Z","caller":"datastore/data_store.go:1104","msg":"ENI eni-01ea cannot be deleted because it is too young"}
{"level":"debug","ts":"2023-08-09T17:23:48.380Z","caller":"datastore/data_store.go:1104","msg":"ENI eni-01ea cannot be deleted because it is required for WARM_IP_TARGET: 2"}
{"level":"debug","ts":"2023-08-09T17:23:55.898Z","caller":"ipamd/ipamd.go:653","msg":"Reconcile existing ENI eni-01ea IP pool"}
...
{"level":"debug","ts":"2023-08-09T18:26:45.080Z","caller":"datastore/data_store.go:1104","msg":"getDeletableENI: found a deletable ENI eni-01ea"}
{"level":"info","ts":"2023-08-09T18:26:45.080Z","caller":"ipamd/ipamd.go:698","msg":"RemoveUnusedENIFromStore eni-01ea: IP/Prefix address pool stats: free 0 addresses, total:
 28, assigned: 26, total prefixes: 0"}
{"level":"debug","ts":"2023-08-09T18:26:45.080Z","caller":"ipamd/ipamd.go:665","msg":"Start freeing ENI eni-01ea"}
{"level":"info","ts":"2023-08-09T18:26:45.080Z","caller":"awsutils/awsutils.go:929","msg":"Trying to free ENI: eni-01ea"}
{"level":"debug","ts":"2023-08-09T18:26:45.193Z","caller":"awsutils/awsutils.go:929","msg":"Found ENI eni-01ea attachment id: eni-attach-0c8e... "}
{"level":"info","ts":"2023-08-09T18:26:45.692Z","caller":"retry/retry.go:70","msg":"Successfully detached ENI: eni-01ea"}
{"level":"debug","ts":"2023-08-09T18:26:47.692Z","caller":"awsutils/awsutils.go:974","msg":"Trying to delete ENI: eni-01ea"}
{"level":"info","ts":"2023-08-09T18:26:48.116Z","caller":"retry/retry.go:70","msg":"Successfully deleted ENI: eni-01ea"}
{"level":"info","ts":"2023-08-09T18:26:48.116Z","caller":"awsutils/awsutils.go:929","msg":"Successfully freed ENI: eni-01ea"}
...
{"level":"debug","ts":"2023-08-09T18:27:45.642Z","caller":"awsutils/awsutils.go:592","msg":"Found ENI: eni-01ea, MAC 02:f0:3e:0d:a2:98, device 2"}
{"level":"error","ts":"2023-08-09T18:27:45.735Z","caller":"ipamd/ipamd.go:1315","msg":"Failed to call ec2:DescribeNetworkInterfaces for [eni-xxx1 eni-xxx2 eni-01
eni-01ea]: InvalidNetworkInterfaceID.NotFound: The networkInterface ID 'eni-01ea' does not exist\n\tstatus code: 400, request id: 4b52d8a2-11a4-45e1-9270-e446ad650cb1"
}
{"level":"debug","ts":"2023-08-09T18:27:45.735Z","caller":"ipamd/ipamd.go:1315","msg":"Could not find interface: The networkInterface ID 'eni-01ea' does not exist, ID: eni-01ea"}
```

It looks like EC2 metadata was not updated properly after removing `eni-01ea` interface, but I'm not sure it's a plugin issue and not AWS internally.

Could you please take a look and let us know how and with whom we should fix this issue? With AWS or with a plugin community?

Thank you for any feedback, help, and your time!

**Environment**:

- **Plugin version before update**: `v1.11.4`
- **Plugin after update**: `v1.13.4`
- **Kubernetes**: `v1.24.16-eks-2d98532`
- **OS**: `Amazon Linux 2`
- **AMI**: `v1.24.11-eks-a59e1f0`
- **Kernel**: `5.10.178-162.673.amzn2.x86_64`

**Comment by jdn5126** [comment]
@Kulagin-G debugging this further will likely require instance-level details, so I think you should open an EKS Support Case through AWS console so that we can dig further.

In the meantime, it looks like IMDS does have the updated data, so why the `aws-node` pod is unable to pull that data is confusing. Can you restart the `aws-node` pods on these nodes and see if this gets back in sync? Restarting the `aws-node` pods is a hitless operation that will not affect any running pods

**Comment by Kulagin-G** [comment]
Hi all,

There is an update from AWS Support about this case:

_After further investigation by our internal team it was identified that the issue you experienced is a known software defect.  This issue was triggered by a defect which affects instances in rare cases when requests to mutate network interfaces and/or their associated configuration are issued in quick succession. Failures of this nature are infrequent, and the internal team continuously work on optimizations to prevent recurrence._ 

_In terms of removing the entry for an instance which is already affected one option is to assign and then unassign an additional IP address to any of the instance's network interfaces, as that should refresh all network related metadata, ideally with a delay between assign and unassigned operations._ 

_To reduce the risk of the issue occurring avoid calling detach network interface very close together with other calls which will mutate network interface metadata (e.g. associate/disassociate IP addresses with any ENI)._

Unfortunately, it's not what I'd like to hear from AWS and it means there are no guarantees it will not happen again.

So, I'm not sure that it's profitable and how it can affect plugin performance, but what about adding a customizable timeout for these types of API calls?

**Comment by hbhasker** [comment]
Reopening as we are seeing the same issue on 1.13.4

**Comment by gete76** [comment]
Seeing this on 1.18.0, with karpenter nodepools that scale aggressively.

**Comment by dmegyesi** [comment]
I'd like to confirm we see the same issues frequently on EKS 1.29, CNI 1.18.3 on clusters that are heavily scaling.
