### ISSUE TITLE
ENI's Primary IP's interface fails to set MTU due to invalid argument

### ISSUE THREAD

**Issue by nak3** [aws/amazon-vpc-cni-k8s#250]
### environment

```
root@ip-172-20-38-50:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

root@ip-172-20-38-50:~# kubectl -n kube-system get pod aws-node-2wq8c -o yaml |grep image:
    image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.3.0
```

### issue

- ENI's primary IP produces `failed to set MTU for 172.20.47.22: invalid argument` below. It is failing MTU on host side's veth pair.

~~~
2018-11-30T12:45:05Z [ERROR] Failed to increase pool size: failed to setup eni eni-0bfaf4f6e80c13ff4 network: eni network setup: failed to set MTU for 172.20.47.22: invalid argument
~~~

#### 1. Scale up until start using secondary ENI and let ipamD assign an IP to primary IP of the secondary ENI.

See `eth1` has an IP(`172.20.34.216`):

```
# ip a |grep eth1
22: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.20.34.216/19 brd 172.20.63.255 scope global eth1
```
Note, not enixxxxxx as it is not primary IP.  Also, check `Assigned: true` via ipamD's API:

```
# curl http://localhost:61678/v1/enis | python -m json.tool |grep 172.20.34.216 -2
            "ID": "eni-0ea4cae59a0123687",
            "IPv4Addresses": {
                "172.20.34.216": {
                    "Assigned": true
                },
```

#### 2. Check MTU of the `eth1`, which is 1500 not 9100.

```
# ip a |grep eth1
22: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 172.20.34.216/19 brd 172.20.63.255 scope global eth1
```

#### 3. Log message complains that ipamD fails to set MTU.

~~~
# grep -rH 172.20.34.216 /var/log/aws-routed-eni/ |grep invalid
/var/log/aws-routed-eni/ipamd.log.2018-11-30-12:2018-11-30T12:44:33Z [ERROR] Failed to increase pool size: failed to setup eni eni-0ea4cae59a0123687 network: eni network setup: failed to set MTU for 172.20.34.216: invalid argument
~~~

### Additional Info:

The error is from here:

https://github.com/aws/amazon-vpc-cni-k8s/blob/3fba7b6aaae4766d1e667537eb072149786d30c2/pkg/networkutils/network.go#L500-L502

If equivalent command - `ip link set dev eth1 mtu 9100` is fired on the host, it produces same error:

~~~
# ip link set dev eth1 mtu 9100
RTNETLINK answers: Invalid argument
~~~

So, setting mtu via netlink seems not working. Another veth (inside pod) has correct MTU

~~~
  # kubectl exec -it my-pod -- ip a |grep eth |grep mtu
  3: eth0@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default 
~~~

**Comment by hmizuma** [comment]
@nak3 Could you provide the instance type you were using?

**Comment by nak3** [comment]
@hmizuma Sure, I was using `t2.medium` for the node. If I should test another instance type, please let me know.

**Comment by nak3** [comment]
Hmm... I have created same cluster env more than 2 times, but the issue cannot be produced anymore. Even the command `# ip link set dev eth1 mtu 9100` is working fine now. I am closing this report as it would be some temporary issue of network interface.
