### ISSUE TITLE
No version number reported in CloudTrail history.

### ISSUE THREAD

**Issue by guessi** [aws/amazon-vpc-cni-k8s#2518]
**What happened**:

While troubleshooting VPC CNI related event, it is better to have version number included.

But the fact is that there's no version number reported in CloudTrail history, hard to tell which version was applied.

Version defined [HERE](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.14.0/pkg/awsutils/awssession/session.go#L38-L39) and [HERE](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.14.0/pkg/awsutils/awssession/session.go#L90-L98) seems like not defined, but I'm not sure how to fix it correctly, so I create the bug report here.

![image](https://github.com/aws/amazon-vpc-cni-k8s/assets/984415/fdab3abb-dc48-4dc7-b929-0dbc59577405)

**Attach logs**

n/a

**What you expected to happen**:

Version info should be included in CloudTrail events.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It's a long lasting bug, version is not that important.

**Comment by jdn5126** [comment]
This is a good call out @guessi , thank you for the report! Yeah, that `version` variable should be set based on the current VPC CNI version. We should do the same for our Kubernetes client userAgent: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/k8sapi/k8sutils.go#L174

I marked this as a good first issue, and will try to find someone to work on this.

**Comment by jdn5126** [comment]
Closing as this merged in #2566 and will ship in v1.15.1
