### ISSUE TITLE
Security groups in ENIConfig are not added to the managed ENIs

### ISSUE THREAD

**Issue by wmgroot** [aws/amazon-vpc-cni-k8s#2521]
**What happened**:
We noticed that communication between our K8s Apiserver and our webhook pods was timing out. With further investigation, we noticed that the security group for the cluster was missing from the pod ENI's attached to the worker nodes.

This is our ENIConfig (similar for each zone).
```
$ kubectl get eniconfig us-east-2a -o yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: us-east-2a
spec:
  securityGroups:
  - sg-03a6540691a4cfa92
  subnet: subnet-0b51b893d744c4af8
```

In the logs below, you can see that the aws-node controller locates the correct ENIConfig and confirms the existence of security group `sg-03a6540691a4cfa92`, then states that it is creating an ENI with that exact security group. However, the referenced security group is not present in the security groups for the ENI.

![Screenshot from 2023-08-30 15-17-08](https://github.com/aws/amazon-vpc-cni-k8s/assets/3124965/7fba1fe8-8a6b-4564-9ea7-ac02850ba7fe)

**Attach logs**
```
{"level":"info","ts":"2023-08-30T20:08:34.159Z","caller":"eniconfig/eniconfig.go:73","msg":"Get Node Info for: ip-10-115-202-43.us-east-2.compute.internal"}
{"level":"debug","ts":"2023-08-30T20:08:34.159Z","caller":"eniconfig/eniconfig.go:136","msg":"Using ENI_CONFIG_LABEL_DEF topology.kubernetes.io/zone"}
{"level":"info","ts":"2023-08-30T20:08:34.160Z","caller":"ipamd/ipamd.go:837","msg":"Found ENI Config Name: us-east-2a"}
{"level":"info","ts":"2023-08-30T20:08:34.260Z","caller":"ipamd/ipamd.go:811","msg":"ipamd: using custom network config: [sg-03a6540691a4cfa92], subnet-0b51b893d744c4af8"}
{"level":"debug","ts":"2023-08-30T20:08:34.260Z","caller":"ipamd/ipamd.go:811","msg":"Found security-group id: sg-03a6540691a4cfa92"}
{"level":"info","ts":"2023-08-30T20:08:34.260Z","caller":"awsutils/awsutils.go:733","msg":"Using a custom network config for the new ENI"}
{"level":"info","ts":"2023-08-30T20:08:34.260Z","caller":"awsutils/awsutils.go:733","msg":"Creating ENI with security groups: [sg-03a6540691a4cfa92] in subnet: subnet-0b51b893d744c4af8"}
{"level":"info","ts":"2023-08-30T20:08:34.682Z","caller":"awsutils/awsutils.go:733","msg":"Created a new ENI: eni-0a275ca5e0309142c"}
```

**What you expected to happen**:
I expect the aws-node controller to attach security groups listed in the ENIConfig, and ensure any existing ENIs are reconciled and updated if they are missing the security groups specified.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to attach a security group to the ENIs used by the pods following the standard security rule documentation.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.14", GitCommit:"0018fa8af8ffaff22f36d3bd86289753ca61da81", GitTreeState:"clean", BuildDate:"2023-05-17T16:21:16Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version
1.13.4 (originally noticed on 1.1.17)
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-115-214-43 5.15.0-1040-aws #45~20.04.1-Ubuntu SMP Tue Jul 11 19:08:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jdn5126** [comment]
@wmgroot this looks like an EC2 issue. You can take a look at the CloudTrail logs to find the request made from IPAMD, but I think the best way to debug this is to open a support case through your AWS console.

Were these ENIs created before you upgraded to `v1.13.4`, or are these new?

**Comment by wmgroot** [comment]
Both, I tried creating entirely new nodes in the cluster before and after the upgrade to 1.13.4.

**Comment by jdn5126** [comment]
> 

I see. We will likely need instance-level details to debug this, so a support case is the only way we can get that info

**Comment by djmcgreal-cc** [comment]
Hi, we're also experiencing a recent ENIConfig oddity. I'm not sure it's related but posting here in case it sheds light.

We stopped being able to override via the `k8s.amazonaws.com/eniConfig` annotation. Our logs show nothing beyond the initial detection of the availability zone based custom network setup. We haven't updated anything since 1.11.4-eksbuild.1.

Can you suggest any way to debug?

**Comment by jdn5126** [comment]
@djmcgreal-cc I am not sure that I follow. Which VPC CNI version are you currently using?

It sounds like you are saying that you set `ENI_CONFIG_ANNOTATION_DEF`. What value did you set it to? That value would dictate how we pick the `ENIConfig` to use for each node: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/eniconfig/eniconfig.go#L132

The typical configuration is to match the `ENIConfig` name to the availability zone name and set `ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone`.

To debug, we would want to start with the `ENIConfig` name that IPAMD tried to use, so the logs from `/var/log/aws-routed-eni/ipamd.log` on the node.

**Comment by djmcgreal-cc** [comment]
Sorry, I must not have explained well.

Previously we've been able to `kubectl annotate node/<name> k8s.amazonaws.com/eniConfig=alternative-eniconfig` to get the ipamd to switch to using an alternative ENIConfig. This annotation is the default of _ ENI_CONFIG_ANNOTATION_DEF_ which we haven't altered.

Version `v1.11.4-eksbuild.1`.

When the node comes up, it finds the ENIConfig that matches the AZ but after that there's no evidence in the logs that it's trying to respond to the change in annotation. But this has worked previously with this same VPC version.

**Comment by djmcgreal-cc** [comment]
i.e. https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html step 4.3.c

**Comment by djmcgreal-cc** [comment]
Also when I edit the AZ ENIConfigs to change subnet, nothing is changing when allocating new IP addresses on existing nodes, but new nodes are getting the new configuration correctly.

**Comment by djmcgreal-cc** [comment]
Last comment in before I read your last one. I'm not expecting existing ENIs to detach, but for new allocations to come from the new pool. Is that incorrect?

**Comment by jdn5126** [comment]
The IPAMD logs only show ENIConfig name when attaching a new ENI, and hours is way too long for it to be a caching issue.

For these new nodes getting the ENIConfig with a larger subnet, when they come up, they have no annotation, right? And then you are adding the annotation for the new ENIConfig, I assume

**Comment by djmcgreal-cc** [comment]
The new nodes coming up have no annotation or label but they’re using the default ENIConfig (named after the zone).

On 31 Aug 2023, at 18:01, Jeffrey Nelson ***@***.***> wrote:



**EXTERNAL EMAIL**
________________________________
The IPAMD logs only show ENIConfig name when attaching a new ENI, and hours is way too long for it to be a caching issue.


For these new nodes getting the ENIConfig with a larger subnet, when they come up, they have no annotation, right? And then you are adding the annotation for the new ENIConfig, I assume

—
Reply to this email directly, view it on GitHub<https://protect-us.mimecast.com/s/jBo1C82lE0ujZNgrUnwbjE?domain=github.com>, or unsubscribe<https://protect-us.mimecast.com/s/dh7hC9rmgPhmg4j1HEMc89?domain=github.com>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This email, including attachments, contains confidential information belonging to Cambridge Consultants. It is intended for the addressee only and may only be copied or disclosed to others with permission. If you are not the intended recipient please delete the material from any computer. Emails are subject to monitoring for legal and security purposes. If this email has been sent as a personal message the company accepts no liability for the content.

**Comment by jdn5126** [comment]
@djmcgreal-cc if ENIs from the new `ENIConfig` are not being attached after the annotation is added, then we'll need to debug further. I suggest collecting node logs and emailing them to k8s-awscni-triage@amazon.com or opening an EKS support case through your AWS console so that we can dive deeper

**Comment by jdn5126** [comment]
Closing issue as there is nothing actionable for our side
