### ISSUE TITLE
Node agent resources not configurable in the Helm chart

### ISSUE THREAD

**Issue by stevehipwell** [aws/amazon-vpc-cni-k8s#2524]
**What would you like to be added**:
The Helm chart uses the same resource configuration for all of the containers; when there was only a single init and regular container this didn't matter as the resource usage would be exactly as was configured. Now that there is an additional node agent container which uses the same resource configuration the DaemonSet will always use twice as many resources as is configured.

**Why is this needed**:
The resource configuration should be container specific and be clear to end-users.

**Comment by jdn5126** [comment]
That's a great point, though the introduction of the node agent does necessarily require more resources do be consumed by the `aws-node` pod. The node agent container has to remain in a warm state and watch for Network Policy resources to be created.

The helm chart probably should allow for container-specific resources to be specified, but the omission was done for simplicity. I am not opposed to accepting a PR here, though.

**Comment by yurrriq** [comment]
I'd also like to see the optino to disable the sidecar entirely, ref: https://github.com/aws/amazon-vpc-cni-k8s/issues/2565
