### ISSUE TITLE
aws-network-policy-agent is not pre-loaded in the latest AMI

### ISSUE THREAD

**Issue by tvizor** [aws/amazon-vpc-cni-k8s#2538]
**What happened**:
aws-network-policy-agent image is not preloaded on the latest AL2 EKS optimized AMI. As per https://github.com/awslabs/amazon-eks-ami/pull/938 other images are preloaded to speedup node start.

Node start times increased significantly with the latest version of the addon. 

VPC CNI Plugin events:

```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  10m    default-scheduler  Successfully assigned kube-system/aws-node-<redacted> to <redacted>
  Normal  Pulled     10m    kubelet            Container image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni-init:v1.14.0-eksbuild.3" already present on machine
  Normal  Created    10m    kubelet            Created container aws-vpc-cni-init
  Normal  Started    10m    kubelet            Started container aws-vpc-cni-init
  Normal  Pulled     9m57s  kubelet            Container image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.14.0-eksbuild.3" already present on machine
  Normal  Created    9m56s  kubelet            Created container aws-node
  Normal  Started    9m56s  kubelet            Started container aws-node
  Normal  Pulling    9m56s  kubelet            Pulling image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-network-policy-agent:v1.0.1-eksbuild.1"
  Normal  Pulled     9m34s  kubelet            Successfully pulled image "602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-network-policy-agent:v1.0.1-eksbuild.1" in 21.76736507s (21.767382681s including waiting)
  Normal  Created    9m25s  kubelet            Created container aws-eks-nodeagent
  Normal  Started    9m24s  kubelet            Started container aws-eks-nodeagent
```

**What you expected to happen**:

Image aws-network-policy-agent will be preloaded on the latest AMI, as other components of AWS VPC CNI plugin.

**How to reproduce it (as minimally and precisely as possible)**:

Start a new node. Describe newly created aws-node pod.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27
- CNI Version: v1.14.0-eksbuild.3
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10.186-179.751.amzn2.x86_64

**Comment by jdn5126** [comment]
@tvizor this looks like a good issue for https://github.com/awslabs/amazon-eks-ami/issues. The VPC CNI repo does not have any control there

**Comment by tvizor** [comment]
submitted https://github.com/awslabs/amazon-eks-ami/issues/1417
