### ISSUE TITLE
Nodes are not joining in aws eks

### ISSUE THREAD

**Issue by trojanops** [aws/amazon-vpc-cni-k8s#254]
I have launched cluster using aws eks successfully. applied aws-auth but nodes are not joining. I checked log message of a node and found this -

```
Dec  4 08:09:02 ip-10-0-8-187 kubelet: E1204 08:09:02.760634    3542 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:461: Failed to list *v1.Node: Unauthorized
Dec  4 08:09:03 ip-10-0-8-187 kubelet: W1204 08:09:03.296102    3542 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Dec  4 08:09:03 ip-10-0-8-187 kubelet: E1204 08:09:03.296217    3542 kubelet.go:2130] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Dec  4 08:09:03 ip-10-0-8-187 kubelet: E1204 08:09:03.459361    3542 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:452: Failed to list *v1.Service: Unauthorized

```
I am not sure about this. I have attached eks full access to these instance node roles.

**Comment by dvohra** [comment]
Has the ConfigMap for authentication been created?

**Comment by sbkg0002** [comment]
We have the same issue with the official AMI from 20190109. The ConfigMap was successfull.

**Comment by dvohra** [comment]
Has the kubeconfig been created using the settings generated by EKS cluster? What does `kubectl get nodes` list?

**Comment by sbkg0002** [comment]
In our case the tags on the nodes had a typo..

**Comment by sasvirco** [comment]
I have the same problem, what was the typo?

**Comment by dvohra** [comment]
sasvirco What does kubectl get nodes list?

**Comment by sasvirco** [comment]
in my case was a wrong arn in the config map, kubectl get nodes list did not show anything as nodes were unable to join, once I did update the configMap with the proper arn, they joined promptly.

**Comment by dvohra** [comment]
sasvirco thanks for the update.

**Comment by paulkendobnc** [comment]
I had the same issue and spent a few hours investigating, only to fin out that my new instance type "m5a.2xlarge" was the cause!!! I switched back to "m5.2xlarge" and everything is ok. very weird.
--

**Comment by on0n** [comment]
I am currently experiencing this issue.

I've triple-checked every detail (Role ARNs, ConfigMap, etc.) following the [AWS tutorial](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) several times, worker nodes still fail to join.

Checking /var/log/messages gives the same "Unauthorized" errors:
```
...
Feb 27 04:34:07 ip-192-168-236-87 kubelet: E0227 04:34:07.917732    3818 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Feb 27 04:34:07 ip-192-168-236-87 kubelet: E0227 04:34:07.917750    3818 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
```

I've tried t3.micro and t3.medium instances with the recommended EKS-optimized AMI for the correct region. Is there documentation around which instance sizes are compatible with EKS worker nodes? Is that really a factor?

**Comment by tabern** [comment]
@trojanops this may be an issue with the IAM authenticator? Please open a ticket with AWS support so we can troubleshoot.

**Comment by elliottb303** [comment]
Adding on re: tags, the typo is a newb mistake. Digging for more complicated reasons was rough. Node has to be 'owned' by a certain cluster. The nodes will only join a cluster its supposed to. I overlooked this but there was not a lot of docs on it. In my case using terraform. Make sure variables match. This is node tag naming parent cluster to join
```terraform
    key = "kubernetes.io/cluster/${var.eks_cluster_name}-${terraform.workspace}"
```
