### ISSUE TITLE
Update IP_COOLDOWN_PERIOD and WARM Targets documentation

### ISSUE THREAD

**Issue by jayanthvn** [aws/amazon-vpc-cni-k8s#2558]
**What would you like to be added**:
Update documentation to make it clear that WARM_IP_TARGET or IP_COOLDOWN_PERIOD or any warm targets doesn't influence branch/trunk ENIs.

**Why is this needed**: 
Better clarity of SGPP customers.

**Comment by ssup2** [comment]
@jayanthvn Thanks :)
