### ISSUE TITLE
Debug level logging enabled in yaml

### ISSUE THREAD

**Issue by gflarity** [aws/amazon-vpc-cni-k8s#257]
Just checking. It seems like enabling debug logging by default in the yaml might lead to excessive logging? 

https://github.com/aws/amazon-vpc-cni-k8s/blob/07363123942c6fa03da6a7737a2d15817a7c2f8e/config/v1.3/aws-k8s-cni.yaml#L79

**Comment by mogren** [comment]
Tracked as part of #511, discussing a switch to a structured logger. Configurability of the logger should be handled in a Helm chart.
