### ISSUE TITLE
Getting Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws) after upgrade to 1.15.0

### ISSUE THREAD

**Issue by cbugneac-nex** [aws/amazon-vpc-cni-k8s#2589]
**What happened**:
After upgrade to 1.15.0 I started to get a lot of error messages:
```shell
$ kubectl -n kube-system logs aws-node-7k5lb
Defaulted container "aws-node" out of: aws-node, aws-eks-nodeagent, aws-vpc-cni-init (init)
Installed /host/opt/cni/bin/aws-cni
Installed /host/opt/cni/bin/egress-cni
time="2023-09-28T14:52:22Z" level=info msg="Starting IPAM daemon... "
time="2023-09-28T14:52:22Z" level=info msg="Checking for IPAM connectivity... "
E0928 14:52:24.675031      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
time="2023-09-28T14:52:24Z" level=info msg="Copying config file... "
time="2023-09-28T14:52:24Z" level=info msg="Successfully copied CNI plugin binary and config file."
E0928 14:52:25.481191      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:52:27.686591      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:52:32.446596      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:52:41.691178      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:52:56.185271      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:53:34.141211      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:54:07.818534      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:54:45.390576      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:55:30.741028      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:56:17.951797      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:56:57.626522      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:57:30.824984      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:58:08.047201      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:58:47.684812      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 14:59:25.239971      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:00:19.086564      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:01:00.100615      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:01:51.692482      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:02:48.166933      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:03:44.738870      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:04:16.841938      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:05:03.209249      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:05:37.478366      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:06:16.821894      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:07:07.152870      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:07:57.974485      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:08:45.497795      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:09:38.117638      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:10:36.382931      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E0928 15:11:23.286600      12 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
```

I'm not using Network Policies in EKS cluster.

**Attach logs**

**What you expected to happen**:
No error messages.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy EKS cluster v1.25
2. Deploy VPC CNI Add-on version v1.15.0-eksbuild.2 with custom networking.
3. Run `kubectl -n kube-system logs aws-node-*****`

**Anything else we need to know?**:
Nope.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.25.12
Server Version: v1.25.12-eks-2d98532
- CNI Version: v1.15.0-eksbuild.2
- OS (e.g: `cat /etc/os-release`): Bottlerocket OS 1.14.2 (aws-k8s-1.25)
- Kernel (e.g. `uname -a`): Linux ip-10-151-8-251.eu-west-1.compute.internal 5.15.117 #1 SMP Thu Jul 6 03:52:07 UTC 2023 x86_64 GNU/Linux

**Comment by jdn5126** [comment]
Yep, this is harmless and fixed by https://github.com/aws/amazon-vpc-cni-k8s/pull/2570. Will ship in v1.15.1 in mid-October

**Comment by smallc2009** [comment]
what exactly time v1.15.1 release? I'm waiting for it to test.

**Comment by sathakatheef** [comment]
@jdn5126 Any idea when the v1.15.1 will be ready? Waiting for it too.

**Comment by jdn5126** [comment]
The target is mid-October, so hoping to finish up release prep this week and make it available early next week

**Comment by sathakatheef** [comment]
> The target is mid-October, so hoping to finish up release prep this week and make it available early next week

Thanks for the update @jdn5126.

**Comment by jdn5126** [comment]
Closing now that v1.15.1 is released on GitHub

**Comment by oxr463** [comment]
@jdn5126 I'm still seeing this occur in v1.15.1-eksbuild.1 in one of my clusters:

```
kubectl logs -n kube-system aws-node-bwzv2
Defaulted container "aws-node" out of: aws-node, aws-eks-nodeagent, aws-vpc-cni-init (init)
Installed /host/opt/cni/bin/aws-cni
Installed /host/opt/cni/bin/egress-cni
time="2023-10-24T18:18:11Z" level=info msg="Starting IPAM daemon... "
time="2023-10-24T18:18:11Z" level=info msg="Checking for IPAM connectivity... "
E1024 18:18:12.922316      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
time="2023-10-24T18:18:13Z" level=info msg="Copying config file... "
time="2023-10-24T18:18:13Z" level=info msg="Successfully copied CNI plugin binary and config file."
E1024 18:18:14.240615      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:18:17.131308      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:18:22.002189      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:18:31.339359      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:18:54.020008      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:19:40.235436      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:20:15.197762      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:21:13.720003      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:22:10.592531      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:23:00.954364      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:23:36.662313      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:24:32.650883      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:25:17.224438      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1024 18:25:52.749505      11 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
```

**Comment by sathakatheef** [comment]
@oxr463 I don't see that issue anymore on my end with v1.15.1. Try setting the network policy to false and give it a try. You may want to check on the config map `amazon-vpc-cni`'s config `enable-network-policy-controller` and container `aws-eks-nodeagent`'s args `--enable-network-policy` both set to **false**.

**Comment by yury-liberau-workday** [comment]
We also keep seeing the error in the logs:

`git:(master) k logs aws-node-2bcjr -n kube-system                                                                                                                                                                                                  

Defaulted container "aws-node" out of: aws-node, aws-eks-nodeagent, aws-vpc-cni-init (init)
Installed /host/opt/cni/bin/aws-cni
Installed /host/opt/cni/bin/egress-cni
time="2023-10-25T10:18:20Z" level=info msg="Starting IPAM daemon... "
time="2023-10-25T10:18:20Z" level=info msg="Checking for IPAM connectivity... "
E1025 10:18:22.469300      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
time="2023-10-25T10:18:23Z" level=info msg="Copying config file... "
time="2023-10-25T10:18:23Z" level=info msg="Successfully copied CNI plugin binary and config file."
E1025 10:18:23.974926      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:18:26.864920      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:18:30.829626      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:18:39.449934      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:18:59.236748      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:19:36.231684      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:20:08.902293      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:20:52.805911      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:21:26.119054      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:22:03.120822      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:22:47.070255      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:23:40.077920      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:24:21.297450      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:25:08.758548      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:26:05.408468      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:26:53.571851      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)
E1025 10:27:45.762904      12 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.1/tools/cache/reflector.go:229: Failed to watch *v1alpha1.CNINode: unknown (get cninodes.vpcresources.k8s.aws)`


the version of vpc-cni plugin is **amazon-k8s-cni:v1.15.1-eksbuild.1**

**Comment by oxr463** [comment]
> @oxr463 I don't see that issue anymore on my end with v1.15.1. Try setting the network policy to false and give it a try. You may want to check on the config map `amazon-vpc-cni`'s config `enable-network-policy-controller` and container `aws-eks-nodeagent`'s args `--enable-network-policy` both set to **false**.

Yes, those were already set to false like in this comment, https://github.com/aws/amazon-vpc-cni-k8s/issues/2562#issuecomment-1717784488

**Comment by jdn5126** [comment]
It sounds like the fix to prevent the `Failed to watch *v1alpha1.CNINode` log was not complete. Thank you for updating, I will look at why this is still logging when it is not being cached. Note that this log is harmless
