### ISSUE TITLE
Error when setting image.account in chart

### ISSUE THREAD

**Issue by gabegorelick** [aws/amazon-vpc-cni-k8s#2594]
**What happened**:

 
The aws-vpc-cni chart allows specifying `image.account` and `init.image.account`. The following works fine in chart versions before https://github.com/aws/amazon-vpc-cni-k8s/commit/41f8d8c9ac4ad3b56ddbc5165c5f2bda8e3d7af9, but now generates an error.

To reproduce, run the following on `master`:
`helm template --debug . --set 'image.account=602401143452'`

The resulting YAML has the following:

> image: %!s(int64=602401143452).dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.15.0

The same issue exists for `init.image.account`.

You can use `--set-string` as a workaround, but that wasn't necessary in prior versions of this chart.

**Attach logs**

> Error: YAML parse error on aws-vpc-cni/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 55: found character that cannot start any token

**What you expected to happen**: Valid YAML

**How to reproduce it (as minimally and precisely as possible)**: `helm template . --set 'image.account=602401143452'`

**Anything else we need to know?**:

I've opened https://github.com/aws/amazon-vpc-cni-k8s/pull/2595 as a fix for this.

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- CNI Version: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A

**Comment by jdn5126** [comment]
Thanks for pointing this out @gabegorelick! There are quite a few values in the helm chart like this, and I think it is best to be explicit with helm and use `--set-string` or quote the value rather than quoting in the chart. But, quoting in the chart does not hurt anything, so I'll take a look at the PR and figure out which release it can go in
