### ISSUE TITLE
Use aws web console to upgrade aws cni plugin to v1.14.1 got: Conflicts found when trying to apply.

### ISSUE THREAD

**Issue by leeeboo** [aws/amazon-vpc-cni-k8s#2607]
**What happened**:

I just upgrade my eks to 1.28.1 and deploy aws cni plugin upgrade to v1.14.1 by aws web console.
I got en Error said: Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. Conflicts: DaemonSet.apps aws-node - .spec.template.spec.containers[name="aws-node"].env[name="ENABLE_PREFIX_DELEGATION"].value

my current ENV:

`
- env:
        - name: ADDITIONAL_ENI_TAGS
          value: '{}'
        - name: ANNOTATE_POD_IP
          value: "false"
        - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
          value: "false"
        - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
          value: "true"
        - name: AWS_VPC_ENI_MTU
          value: "9001"
        - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
          value: "false"
        - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
          value: "false"
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: AWS_VPC_K8S_CNI_LOG_FILE
          value: /host/var/log/aws-routed-eni/ipamd.log
        - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
          value: prng
        - name: AWS_VPC_K8S_CNI_VETHPREFIX
          value: eni
        - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
          value: /var/log/aws-routed-eni/plugin.log
        - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
          value: DEBUG
        - name: CLUSTER_ENDPOINT
          value: https://BD9138284BE98F2D04DDB759AA88DEA9.gr7.cn-northwest-1.eks.amazonaws.com.cn
        - name: CLUSTER_NAME
          value: weixinhost
        - name: DISABLE_INTROSPECTION
          value: "false"
        - name: DISABLE_METRICS
          value: "false"
        - name: DISABLE_NETWORK_RESOURCE_PROVISIONING
          value: "false"
        - name: ENABLE_IPv4
          value: "true"
        - name: ENABLE_IPv6
          value: "false"
        - name: ENABLE_POD_ENI
          value: "false"
        - name: ENABLE_PREFIX_DELEGATION
          value: "true"
        - name: VPC_ID
          value: vpc-641fec0d
        - name: WARM_ENI_TARGET
          value: "1"
        - name: WARM_PREFIX_TARGET
          value: "1"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: WARM_IP_TARGET
          value: "20"
        - name: MINIMUM_IP_TARGET
          value: "5"
`

**Environment**:
- Kubernetes version (use `kubectl version`):  Server Version: v1.28.1-eks-43840fb
- CNI Version: v1.13.4 need upgrade to v1.14.1 
- OS (e.g: `cat /etc/os-release`): aws eks ami

**Comment by jdn5126** [comment]
@leeeboo this is not a VPC CNI issue, this is an error from the EKS Managed Addon Service. Since you have conflicts while updating, you would need to set the "Resolve Conflicts" field to "OVERWRITE"
