### ISSUE TITLE
Provide current IP count for kubernetes scheduling

### ISSUE THREAD

**Issue by cskinfill** [aws/amazon-vpc-cni-k8s#2638]
**What would you like to be added**:

Provide the kube api with the current number of pooled IPs so that these resources can be used for scheduling decisions.  There are a number of issues that seem related to this (https://github.com/aws/amazon-vpc-cni-k8s/issues/1160 and https://github.com/aws/amazon-vpc-cni-k8s/issues/26)

Using the ["Device Plugins"](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) feature, the aws cni (or a sidecar) can provide to the kubelet the number of IP addresses.  The kubelet will then report these resources back to the kube api which the scheduler can then use for scheduling decisions.

**Why is this needed**:

To ensure that a pod isn't scheduled to a node that has sufficient resources but NOT sufficient IP addresses available.

**Comment by sidewinder12s** [comment]
This would be massively helpful generally for operation of the CNI.

**Comment by sidewinder12s** [comment]
Not stale

**Comment by nedimYilmaz** [comment]
@jdn5126 is there any estimation for the solution? or do you have any suggestion to prevent or any workaround to do not stuck on ContainerCreation state.
