### ISSUE TITLE
Information Required : POD IP address limit while using amazon-vpc-routed-eni

### ISSUE THREAD

**Issue by sam0104** [aws/amazon-vpc-cni-k8s#265]
I am testing amazon-vpc-routed-eni inside AWS with KOPS deployed using --topology=private
**My scenario** 
I am deploying multiple kubernetes cluster ( assume 100 ) and each kubernetes cluster use separate VPC with unique VPC CIDR. 

No VPC is going to use same CIDR for avoiding conflict 
Deployed Kubernetes cluster using KOPS with amazon-vpc-routed-eni  networking , which allow eacg POD to have IP address from CIDR range 

Q : Is it fine to use amazon-vpc-routed-eni for large Kubernetes setup , where each VPC has unique CIDR ?

Q: What is the limit for amazon-vpc-routed-eni for providing POD IP from a /16 CIDR. Example : 172.16.0.0/16 , 10.0.0.0/16 

Q: How many maximum POD IP can be assigned using amazon-vpc-routed-eni if I am using the large ec2 VM m2.4xlarge  which supports 8 network interface and 30 IPV4 address per interface. Which provides me 30x8 = 240 IPV4 IP addresses from **one Kubernetes worker node** . If I am using 6 Kubernetes worker node and each worker node is m2.large then I will get 6 x 240 = **1440 IPV4** IP addresses per Kubernetes cluster. Am I in the right direction for calculating POD IP addresses per cluster ?

Q: Is there a maximum limit for amazon-vpc-routed-eni for deploying worker nodes. Can I deploy 5000  worker nodes with c4.8xlarge using amazon-vpc-routed-eni in a VPC with 172.16.0.0/16 CIDR to get maximum POD  IPV4 addresses ?
I am referring  to Kubernetes : https://kubernetes.io/docs/setup/cluster-large/

**Comment by labria** [comment]
1. Yes, it's ok to use amazon-vpc-routed-eni in this case.
2. /16 is ~32k addresses in total (if you assign the whole /16 to the subnet you're gonna use with Kube).
3. Yes, you're right. Here's a complete table for calculations: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI. Although, notice that https://kubernetes.io/docs/setup/cluster-large/ says **No more than 100 pods per node**, so you might want smaller instances (not sure what's the reasoning behind this limit, or how hard a limit this is).
4. There is no limit for the plugin, AFAIK. But beware, a cluster of that size might require tuning master servers quite a bit. You might want to do a lot of load testing with carefully monitoring to make sure your cluster is stable.

**Comment by jaypipes** [comment]
Closing this issue out. Seems original questions have been answered.
