### ISSUE TITLE
Incorrect aws-k8s-cni.yaml

### ISSUE THREAD

**Issue by joval-sv** [aws/amazon-vpc-cni-k8s#2676]
While upgrading to version 1.15.4 (the latest version) I got a warning that the current version `v1.12.2` is now unsupported. So, in order to fix this issue, I'm downloading both YAML documents directly using:

For the new version: v1.15.4
[aws-k8s-cni-v1.15.4.yaml](https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.15.4/config/master/aws-k8s-cni.yaml)

For the old version: v1.12.2
[aws-k8s-cni-v1.12.2.yaml](https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.12.2/config/master/aws-k8s-cni.yaml)

I was going to destroy the old definitions by:
`kubectl delete -f aws-k8s-cni-v1.12.2.yaml`

Then install the new version with:
`kubectl apply -f aws-k8s-cni-v1.15.4.yaml`

But when double checking the content of the file: `aws-k8s-cni-v1.15.4.yaml` the content is the same as the content from the v1.14.1 version. This does not happen with version v1.15.3.

```bash
curl -O https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.15.4/config/master/aws-k8s-cni.yaml
grep image aws-k8s-cni.yaml
        image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.14.1"
          image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.14.1"
          image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-network-policy-agent:v1.0.2"

```
This is not an issue when upgrading via the AWS Console or via the aws-cli tools.
Could it be that just this resource is pointing to the wrong version?

**Environment**:
- Kubernetes version: 1.26
- CNI Version: v1.12.2
- OS: Amazon Linux 2
- Kernel: 5.10.197-186.748.amzn2.x86_64

- Local: Ubuntu 22.04 LTS
- Kernel:  Linux PF426J1K 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jdn5126** [comment]
@joval-sv thank you for catching this! It looks like the `v1.15.4` tag somehow got applied to the `release-1.14` branch instead of the `release-1.15` branch. I am not sure how that happened, so I am digging into it now. I will fix the tag and recreate the release 🤦🏻

**Comment by jdn5126** [comment]
@joval-sv the tag is fixed now, thank you again for reporting. I will continue to figure out where the typo came from
