### ISSUE TITLE
Refactor iptable mock

### ISSUE THREAD

**Issue by jchen6585** [aws/amazon-vpc-cni-k8s#2711]
**What would you like to be added**:
Issue to keep track of refactoring iptable mock

**Why is this needed**:
Currently, our mock has some empty functions and only map the chain to rules that start with `-A`. We specifically should add chain creation rules to the map as well `-N`. This leaves some gaps in our test coverage such as testing https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/networkutils/network.go#L379

**Comment by jdn5126** [comment]
Closing as fixed by #2721
