### ISSUE TITLE
Tag v1.17.0 in ECR

### ISSUE THREAD

**Issue by nunoadrego** [aws/amazon-vpc-cni-k8s#2722]
**What happened**:

During the development of a tool that examines image tags in a registry, we discovered that there is a v1.17.0 tag for amazon-k8s-cni (public.ecr.aws/eks/amazon-k8s-cni:v1.17.0). The tag was created about one year ago. Is this intentional or is it a faulty tag?

https://gallery.ecr.aws/eks/amazon-k8s-cni

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
@nunoadrego this is a faulty tag. I will get it removed, thanks for reporting!

**Comment by jdn5126** [comment]
Done, thanks again!
