### ISSUE TITLE
Add Windows IPAM options as Environment Variables

### ISSUE THREAD

**Issue by tip-dteller** [aws/amazon-vpc-cni-k8s#2726]
**What would you like to be added**:
Would like to add the following as environment variables.
```
  enable-windows-ipam: "false"
  enable-network-policy-controller: "false"
  enable-windows-prefix-delegation: "false"
```

**Why is this needed**:
When running an EKS hybrid cluster - linux and windows. it is required per AWS documentation to add
'enable-windows-ipam=true' as a VPC-CNI ConfigMap, making IPs available for allocation to Windows Pods.

There's no easy to add this when building a cluster using Terraform or any other IaC tool.
The steps required are:
1. Create EKS Cluster and 1 Node Group.
2. Wait for completion.
3. Add ConfigMap using TF or manually.
4. Add Windows Node Group - so it can work off the bat.

It would be far simpler to apply already in EKS Addon section of Terraform:
```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"

  # Truncated for brevity
  ...

  cluster_addons = {
    vpc-cni = {
      before_compute = true
      most_recent    = true # To ensure access to the latest settings provided
      configuration_values = jsonencode({
        env = {
          ENABLE_PREFIX_DELEGATION = "true"
          WARM_PREFIX_TARGET       = "1"
          ENABLE_WINDOWS_IPAM = "true"
        }
      })
    }
  }
```

Env Vars should be loaded from the aws-vpc-cni\main.go - [main.go](https://github.com/aws/amazon-vpc-cni-k8s/blob/6a13d8ee304306791b793de5a4e42649c4ce15e0/cmd/aws-vpc-cni/main.go#L86)

Subsequent logic should be added in relevant functions.

**Comment by jdn5126** [comment]
@tip-dteller this configurability is already added in the EKS addon configuration for VPC CNI `v1.16.0-eksbuild.1.`.

VPC CNI `v1.16.0` is already available on GitHub: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.16.0, and those fields are configurable in the ConfigMap via the helm chart: https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.16.0/charts/aws-vpc-cni/templates/configmap.yaml#L20

For the EKS addon API you linked above, using `configuration_values`, you will be able to pass those fields from the top level, i.e.:
```
configuration_values = jsonencode({
  enableWindowsIpam = "true"
  enableWindowsPrefixDelegation = "true"
  warmWindowsIPTarget = 5
})
```

The EKS addon for `v1.16.0-eksbuild.1` is currently in the pipeline, but is blocked by the holiday block days. It should be available across all regions by 12/28

**Comment by tip-dteller** [comment]
@jdn5126  - Thanks for the reply,
so it will be available in 1.16, meaning an upgrade is required to use this via IaC solutions.

Also, why in the helm chart the ConfigMap is created as an objected but isnt attached to the daemonset? is that by design?
what reads the configmap?

**Comment by jdn5126** [comment]
> @jdn5126 - Thanks for the reply, so it will be available in 1.16, meaning an upgrade is required to use this via IaC solutions.
Correct
> 
> Also, why in the helm chart the ConfigMap is created as an objected but isnt attached to the daemonset? is that by design? what reads the configmap?
The ConfigMap is consumed by the controller: https://github.com/aws/amazon-vpc-resource-controller-k8s. In Windows deployments, the AWS VPC CNI is not used, as the controller handles all of the pod networking setup. These Windows variables are present in this helm chart only to make it easier for customers to use the same helm chart across Linux and Windows environments. This is where the AWS VPC CNI is prevented from being scheduled on Windows nodes: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L561

**Comment by tip-dteller** [comment]
Hmm I suppose it should be documented under some section in the documentation, since this part confused me, if you hadnt mentioned it, i'd be chasing a tail, trying to figure out what consumes those variables and how.

**Comment by jdn5126** [comment]
Which part should be documented? I see it covered pretty well in https://aws.github.io/aws-eks-best-practices/networking/prefix-mode/index_windows/ and https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html

**Comment by VLZZZ** [comment]
I just want to add more context on why it might be misleading when using Helm chart.

During the upgrade to `v1.16.0` we encountered with the following change in our dry-run job:
![image](https://github.com/aws/amazon-vpc-cni-k8s/assets/9082481/80d50ee9-61b0-4c2b-a32f-bd60cb342c8c)

And it took some time to understand how it will (or not) affect our configuration. 
Because the env var `WARM_PREFIX_TARGET` (for linux) and config map entry `warm-prefix-target` (for windows) are almost identical.

Moreover when reading documentation you might think that - "Ok, Linux is using env vars for configuration, while Windows using config file entries", but as far as I remember from this discussion [on IPv6 Disablement](https://github.com/aws/amazon-vpc-cni-k8s/issues/2483#issuecomment-1693515358) config file is just a config file that's not tied to the target OS and you may have some common configuration here.

For me it would make more sense to have all windows-related setting to be configurable not only in the atomic way, but also to have main switch for the Helm chart, like `windows.enabled: false` (just to reflect my idea) to have full control over configuration (if I don't have any Windows/Linux hosts, why do I need some configuration, which is controller in two different ways) and avoid misleading changes like this.

**Comment by jdn5126** [comment]
@VLZZZ yeah, the naming for these ConfigMap variables was a big miss. The names are fixed because that is what the VPC Resource Controller looks at for Windows Prefix Delegation (https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/pkg/config/type.go#L76). We need to update the names in a future release.

**Comment by tip-dteller** [comment]
@jdn5126 
the main reason i was initially asking if because of things like this:
We have our terraform\terragrunt configuration setup and would like to enable WindowsIPAM as well.
```
    vpc-cni = {
        # resolve_conflicts = "OVERWRITE"
        resolve_conflicts_on_create = "OVERWRITE"
        resolve_conflicts_on_update = "OVERWRITE"
        addon_version = "${local.env_common.locals.vpc-cni_version}"
        before_compute           = true
        configuration_values = jsonencode({
          env = {
            # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
            # These flags increase the amount of Ips available for Nodes - meaning u a can assign also, more Pods to a node.
            # In order to get the values to pass here run this command and read the output:
            ENABLE_PREFIX_DELEGATION = "true"
            WARM_PREFIX_TARGET       = "1"
            enable-windows-ipam        = "true"
            
          }
        })
      }
```

As described in Terraform Registry - AWS eks-addon
you need to use the describe command to get the schema to find the correct value it expects:
```
jq '.configurationSchema'
"{\"$ref\":\"#/definitions/VpcCni\",\"$schema\":\"http://json-schema.org/draft-06/schema#\",\"definitions\":{\"Affinity\":{\"type\":[\"object\",\"null\"]},\"EniConfig\":{\"additionalProperties\":false,\"properties\":{\"create\":{\"type\":\"boolean\"},\"region\":{\"type\":\"string\"},\"subnets\":{\"additionalProperties\":{\"additionalProperties\":false,\"properties\":{\"id\":{\"type\":\"string\"},\"securityGroups\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"id\"],\"type\":\"object\"},\"minProperties\":1,\"type\":\"object\"}},\"required\":[\"create\",\"region\",\"subnets\"],\"type\":\"object\"},\"Env\":{\"additionalProperties\":false,\"properties\":{\"ADDITIONAL_ENI_TAGS\":{\"type\":\"string\"},\"ANNOTATE_POD_IP\":{\"format\":\"boolean\",\"type\":\"string\"},\"AWS_EC2_ENDPOINT\":{\"type\":\"string\"},\"AWS_EXTERNAL_SERVICE_CIDRS\":{\"type\":\"string\"},\"AWS_MANAGE_ENIS_NON_SCHEDULABLE\":{\"format\":\"boolean\",\"type\":\"string\"},\"AWS_VPC_CNI_NODE_PORT_SUPPORT\":{\"format\":\"boolean\",\"type\":\"string\"},\"AWS_VPC_ENI_MTU\":{\"format\":\"integer\",\"type\":\"string\"},\"AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG\":{\"format\":\"boolean\",\"type\":\"string\"},\"AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS\":{\"type\":\"string\"},\"AWS_VPC_K8S_CNI_EXTERNALSNAT\":{\"format\":\"boolean\",\"type\":\"string\"},\"AWS_VPC_K8S_CNI_LOGLEVEL\":{\"type\":\"string\"},\"AWS_VPC_K8S_CNI_LOG_FILE\":{\"type\":\"string\"},\"AWS_VPC_K8S_CNI_RANDOMIZESNAT\":{\"type\":\"string\"},\"AWS_VPC_K8S_CNI_VETHPREFIX\":{\"type\":\"string\"},\"AWS_VPC_K8S_PLUGIN_LOG_FILE\":{\"type\":\"string\"},\"AWS_VPC_K8S_PLUGIN_LOG_LEVEL\":{\"type\":\"string\"},\"CLUSTER_ENDPOINT\":{\"type\":\"string\"},\"DISABLE_INTROSPECTION\":{\"format\":\"boolean\",\"type\":\"string\"},\"DISABLE_LEAKED_ENI_CLEANUP\":{\"format\":\"boolean\",\"type\":\"string\"},\"DISABLE_METRICS\":{\"format\":\"boolean\",\"type\":\"string\"},\"DISABLE_NETWORK_RESOURCE_PROVISIONING\":{\"format\":\"boolean\",\"type\":\"string\"},\"DISABLE_POD_V6\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_BANDWIDTH_PLUGIN\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_POD_ENI\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_PREFIX_DELEGATION\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_V4_EGRESS\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_V6_EGRESS\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENI_CONFIG_ANNOTATION_DEF\":{\"type\":\"string\"},\"ENI_CONFIG_LABEL_DEF\":{\"type\":\"string\"},\"INTROSPECTION_BIND_ADDRESS\":{\"type\":\"string\"},\"IP_COOLDOWN_PERIOD\":{\"format\":\"integer\",\"type\":\"string\"},\"MAX_ENI\":{\"format\":\"integer\",\"type\":\"string\"},\"MINIMUM_IP_TARGET\":{\"format\":\"integer\",\"type\":\"string\"},\"POD_SECURITY_GROUP_ENFORCING_MODE\":{\"type\":\"string\"},\"WARM_ENI_TARGET\":{\"format\":\"integer\",\"type\":\"string\"},\"WARM_IP_TARGET\":{\"format\":\"integer\",\"type\":\"string\"},\"WARM_PREFIX_TARGET\":{\"format\":\"integer\",\"type\":\"string\"}},\"title\":\"Env\",\"type\":\"object\"},\"Init\":{\"additionalProperties\":false,\"properties\":{\"env\":{\"$ref\":\"#/definitions/InitEnv\"},\"resources\":{\"$ref\":\"#/definitions/Resources\"}},\"title\":\"Init\",\"type\":\"object\"},\"InitEnv\":{\"additionalProperties\":false,\"properties\":{\"DISABLE_TCP_EARLY_DEMUX\":{\"format\":\"boolean\",\"type\":\"string\"},\"ENABLE_V6_EGRESS\":{\"format\":\"boolean\",\"type\":\"string\"}},\"title\":\"InitEnv\",\"type\":\"object\"},\"Limits\":{\"additionalProperties\":false,\"properties\":{\"cpu\":{\"type\":\"string\"},\"memory\":{\"type\":\"string\"}},\"title\":\"Limits\",\"type\":\"object\"},\"NodeAgent\":{\"additionalProperties\":false,\"properties\":{\"conntrackCacheCleanupPeriod\":{\"format\":\"integer\",\"type\":\"integer\"},\"enableCloudWatchLogs\":{\"format\":\"boolean\",\"type\":\"string\"},\"enablePolicyEventLogs\":{\"format\":\"boolean\",\"type\":\"string\"},\"enabled\":{\"type\":\"boolean\"},\"healthProbeBindAddr\":{\"format\":\"integer\",\"type\":\"string\"},\"metricsBindAddr\":{\"format\":\"integer\",\"type\":\"string\"},\"resources\":{\"$ref\":\"#/definitions/Resources\"}},\"title\":\"NodeAgent\",\"type\":\"object\"},\"Resources\":{\"additionalProperties\":false,\"properties\":{\"limits\":{\"$ref\":\"#/definitions/Limits\"},\"requests\":{\"$ref\":\"#/definitions/Limits\"}},\"title\":\"Resources\",\"type\":\"object\"},\"Tolerations\":{\"additionalProperties\":false,\"items\":{\"type\":\"object\"},\"type\":\"array\"},\"VpcCni\":{\"additionalProperties\":false,\"properties\":{\"affinity\":{\"$ref\":\"#/definitions/Affinity\"},\"branchENICooldown\":{\"type\":\"integer\"},\"enableNetworkPolicy\":{\"format\":\"boolean\",\"type\":\"string\"},\"enableWindowsIpam\":{\"format\":\"boolean\",\"type\":\"string\"},\"enableWindowsPrefixDelegation\":{\"format\":\"boolean\",\"type\":\"string\"},\"eniConfig\":{\"$ref\":\"#/definitions/EniConfig\"},\"env\":{\"$ref\":\"#/definitions/Env\"},\"init\":{\"$ref\":\"#/definitions/Init\"},\"livenessProbeTimeoutSeconds\":{\"type\":\"integer\"},\"minimumWindowsIPTarget\":{\"type\":\"integer\"},\"nodeAgent\":{\"$ref\":\"#/definitions/NodeAgent\"},\"podAnnotations\":{\"additionalProperties\":{\"not\":{\"type\":[\"object\",\"array\",\"null\"]}},\"type\":[\"object\",\"null\"]},\"podLabels\":{\"additionalProperties\":{\"not\":{\"type\":[\"object\",\"array\",\"null\"]}},\"type\":[\"object\",\"null\"]},\"readinessProbeTimeoutSeconds\":{\"type\":\"integer\"},\"resources\":{\"$ref\":\"#/definitions/Resources\"},\"tolerations\":{\"$ref\":\"#/definitions/Tolerations\"},\"warmWindowsIPTarget\":{\"type\":\"integer\"},\"warmWindowsPrefixTarget\":{\"type\":\"integer\"}},\"title\":\"VpcCni\",\"type\":\"object\"}},\"description\":\"vpc-cni\"}"
```

this one: 
```
\"type\":\"string\"},\"enableWindowsIpam\":{\"format\":\"boolean\"
```

we tried setting it:
```
...
configuration_values = jsonencode({
          env = {
             enableWindowsIpam = "true"
          }
OR
enableWindowsIpam = true
or 
enable-windows-ipam  = true # as specified in AWS documentation for the ConfigMap
```


but all those result with the same error:
```
operation error EKS: UpdateAddon, https response error StatusCode: 400, RequestID: 30dd936e-8d7f-4e87-81dc-3f2058487f43, InvalidParameterException: ConfigurationValue provided in request is not supported: Json schema validation failed with error: [$.env.enable-windows-ipam: is not defined in the schema and the schema does not allow additional properties]
```

the ConfigMap itself shows this:.
```
k get cm -n kube-system amazon-vpc-cni -o yaml
apiVersion: v1
data:
  branch-eni-cooldown: "60"
  enable-network-policy-controller: "false"
  enable-windows-ipam: "false"
  enable-windows-prefix-delegation: "false"
  minimum-ip-target: "3"
  warm-ip-target: "1"
  warm-prefix-target: "0"
```

so im completely confused as to what exactly im supposed to use and consequently the documentation provides no help in this case.

**Comment by tip-dteller** [comment]
from the Schema it appears to be under this section
```
      "VpcCni": {
        "additionalProperties": false,
        "properties": {
          "affinity": {
            "ref": "#/definitions/Affinity"
          },
          "branchENICooldown": {
            "type": "integer"
          },
          "enableNetworkPolicy": {
            "format": "boolean",
            "type": "string"
          },
          "enableWindowsIpam": {
            "format": "boolean",
            "type": "string"
          },
```
which is not under ENV scope.
so would it make sense like this?
```
    vpc-cni = {
        # resolve_conflicts = "OVERWRITE"
        resolve_conflicts_on_create = "OVERWRITE"
        resolve_conflicts_on_update = "OVERWRITE"
        addon_version = "${local.env_common.locals.vpc-cni_version}"
        before_compute           = true
        
        configuration_values =  jsonencode({
          enableWindowsIpam    = true
          env = {
            # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
            # These flags increase the amount of Ips available for Nodes - meaning u a can assign also, more Pods to a node.
            # In order to get the values to pass here run this command and read the output:
            ENABLE_PREFIX_DELEGATION = "true"
            WARM_PREFIX_TARGET       = "1"
            
          }
        })
      }
```
