### ISSUE TITLE
How to create SecurityGroupPolicy with Terraform?

### ISSUE THREAD

**Issue by tom10271** [aws/amazon-vpc-cni-k8s#2779]
**What happened**:
Any suggested Terrform provider I can use which supports creating `SecurityGroupPolicy`?

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
@tom10271 not that I am aware of, but moving this issue to https://github.com/terraform-aws-modules/terraform-aws-eks/issues

**Comment by jdn5126** [comment]
Actually, I do not have permission to transfer this issue to that repository. @tom10271 can you move it?

**Comment by tom10271** [comment]
That repository is for Terraform module only, which still need native
Terraform resource for SecurityGroupPolicy supported by Terraform Provider.

「Jeffrey Nelson ***@***.***>」在 2024年2月3日 週六，上午12:13 寫道：

**Comment by jdn5126** [comment]
@tom10271 I am not quite sure I follow, but Terraform is separate from the VPC CNI, and the CRD that you are referring to is installed by the VPC Resource Controller: https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/master/config/crd/bases/vpcresources.k8s.aws_securitygrouppolicies.yaml

It sounds like this feature request belongs at https://github.com/aws/containers-roadmap/issues then

**Comment by tom10271** [comment]
Thank you @jdn5126. I think this repository would solve my problem. 

https://github.com/metio/terraform-provider-k8s/issues/115#issuecomment-1923420295
