### ISSUE TITLE
add support for EKS Pod Identity

### ISSUE THREAD

**Issue by pdeva** [aws/amazon-vpc-cni-k8s#2780]
**What would you like to be added**:

Add support for EKS Pod Identity feature. 

**Why is this needed**:

Currently vpc-cni still uses IRSA which has been superceded by Pod Identity. Its the only compoenent in our cluster that requires configuring and setting up IRSA.

**Comment by jdn5126** [comment]
@pdeva the VPC CNI support the EKS pod identity agent as far as I am aware. Are you seeing an issue?

**Comment by pdeva** [comment]
is there any documentation for this? the official docs seem to suggest only IRSA
https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html

**Comment by leolimas** [comment]
I'm working with this just now... 

EKS: 1-27
VPC-CNI: 1.16.2

I just got success when I inject the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY into env vars... When I remove it one of aws-node pods don't works it get stucked in liveness / readiness, and CNI don't go ready... 

AWS_CONTAINER_CREDENTIALS_FULL_URI is present on this pod

**Comment by jdn5126** [comment]
@pdeva @leolimas it looks like I spoke a bit too soon. This should work, however the public announcement and documentation around it has not been released yet. It is targeting to be released in the near future.

**Comment by leolimas** [comment]
@jdn5126 

Here I got a curious scenario...

I have 2 lab clusters running CNI with secrets, if I just remove the secrets and deploy the new version of CNI using Pod Identity directly it do not works... 

The only way that worked for me is deploy  the upgrade from 1.13 to 1.16 using the secrets into ENV Vars, and in a second deploy I remove the secrets and deploy only using Pod Identity... 

This happened in both lab clusters

**Comment by zztopping** [comment]
I was able to get CNI  v1.15.5+ (via managed add-on) to work with Pod Identity with the following workaround. Since Pod Identity only uses host networking (no strict reliance on CNI), this was a node-readiness taint problem, not a hard-dependency problem.

For reference, pod Identity's default toleration is:
`node.kubernetes.io/not-ready:NoExecute op=Exists`

But when the CNI cannot start, the node is flagged as `NoSchedule`, which does not match the default toleration and therefore the Pod Identity pod cannot get scheduled on the node. Without Pod Identity, CNI cannot start...and there you have a chicken and egg problem.

Adding this toleration to Pod Identity's JSON [configurationValues](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAddon.html#AmazonEKS-CreateAddon-request-configurationValues) config using EKS API allows Pod Identity to start before node is fully ready (ie before CNI is functional) and effectively works around this issue (this is only a snip, not the full config):
```
"tolerations" : [
        {
            "key": "node.kubernetes.io/not-ready",
            "operator": "Equal",
            "effect":"NoSchedule"
        }
  ]
```

The pod identity agent could/should tolerate all taints by default, and that could be a more coarse-grained way to address this yourself. I can’t see any scenario where you would not want this Pod/agent running on all nodes by default.

**Comment by zztopping** [comment]
Additional note, the CNI version (v1.15.5+) is important because it includes the version of the Go SDK that is compatible with Pod Identity.

https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

**Comment by leolimas** [comment]
> @jdn5126
> 
> Here I got a curious scenario...
> 
> I have 2 lab clusters running CNI with secrets, if I just remove the secrets and deploy the new version of CNI using Pod Identity directly it do not works...
> 
> The only way that worked for me is deploy the upgrade from 1.13 to 1.16 using the secrets into ENV Vars, and in a second deploy I remove the secrets and deploy only using Pod Identity...
> 
> This happened in both lab clusters

More one info... when using Pod Identity my pod stucks with this message:
Readiness probe failed: {"level":"info","ts":"2024-02-02T21:24:34.245Z","caller":"/root/sdk/go1.21.5/src/runtime/proc.go:267","msg":"timeout: failed to connect service \":50051\" within 2s"}

**Comment by pdeva** [comment]
The following is confirmed via experience on our own cluster and via AWS support:

to repro:

1. create a eks cluster with eks access api only (no configmap support).
2. add a single node to cluster and enable vpc cni and pod identity addons
3. add pod identity associations for vpc-cni to `kube-system:aws-node` 
4. now add a new node to the cluster
5. the node will never join the cluster

root issue:

there is a race condition. the aws-node pod is now waiting for pod-identity-agent pod to access the vpc to assign ip. 
however, the pod-identity-agent pod is not scheduled on the node cause its not part of the cluster yet.

possible solution:
eks team needs to add `pod-identity-agent` to the list of default pods along with `aws-node` that are spun up on  a brand new node.

**Comment by zztopping** [comment]
@pdeva did you see my write-up above? This has been tested in my environment and at least 2 others with success.

**Comment by pdeva** [comment]
> @pdeva did you see my write-up above? The workaround to add additional tolerations to the add-on config has been tested in my environment and at least 2 others with success.

@zztopping that does seem like a nice fix. hopefully the aws team adds that config by default.

another workaround is to delete the pod identity association for vpc-cni completely and attach the 'AmazonEKS_CNI_Policy' to the node role (the terraform eks module does this by default). doing so causes the aws-node pods to take the permissions from the worker node themselves and does work.

**Comment by zztopping** [comment]
Yes on both fronts! The default tolerations on the pod identity add-on should accommodate this use case, and the documentation needs updating to reflect the current support status (before or after this default toleration is changed)

And yes, if your security posture allows for VPC permissions to be attached to the node that can be used at bootstrapping time. But that really goes against the intent of the enhanced security that Pod Identity and IRSA before it provide. ;-)

**Comment by jdn5126** [comment]
The latest EKS Pod Identity agent version, `v1.2.0-eksbuild.1`, contains this toleration, so I am going to mark this issue as resolved.
