### ISSUE TITLE
Supported Windows flags should's cause confusion with Linux flags' name

### ISSUE THREAD

**Issue by haouc** [aws/amazon-vpc-cni-k8s#2799]
**What would you like to be added**:
In charts, Windows flags name are provided without definitive naming which can cause confusion for Linux users. The names should be renamed to indicate Windows. 
**Why is this needed**:
[Another dependency has renamed the Windows flags' name](https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/371) and now supports both names for every Windows flag, this charts can update the names accordingly to deprecate the old names.

**Comment by haouc** [comment]
This change should be made in https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/configmap.yaml#L23-L25.

The deprecation should be made after [the PR](https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/371) in VPC resource controller is deployed to all clusters.

**Comment by poblahblahblah** [comment]
Chiming in to say that these flags are confusing at best and we look forward to this being addressed!
