### ISSUE TITLE
Metric for AZ traffic usage between pods

### ISSUE THREAD

**Issue by y0zg** [aws/amazon-vpc-cni-k8s#2812]
Hello, 
I'd like to see intra/inter-AZ traffic metric, is it something in the roadmap?

Thanks

**Comment by jdn5126** [comment]
@y0zg can you please file this request at https://github.com/aws/containers-roadmap/issues? That repository is the better place to track features in the pipeline, especially when they are not specific to the VPC CNI. I assume you are asking for something more granular and Kubernetes-specific compared to what EC2 already provides.
