### ISSUE TITLE
2-3x increase in GetMetadata API calls from 1.16.2 -> 1.16.3 release

### ISSUE THREAD

**Issue by diranged** [aws/amazon-vpc-cni-k8s#2813]
**What happened**:
This morning we upgraded from `1.16.2` to `1.16.3` - and while there are no errors or problems, I noticed a sharp increase in the latency of `GetMetadata` API calls coming from the CNI pods (and the count):

(Graph is a rate ...)

```
sum by (api, error, status) (
    rate(
        awscni_aws_api_latency_ms_sum{
            job=~"$daemonset",
            node=~"$node",
            error="false"
        }[$__rate_interval]
    )
)
```

![image](https://github.com/aws/amazon-vpc-cni-k8s/assets/768067/f8a4efee-274b-4a4e-a757-d59771059a53)

Here's the count of total calls:
```
sum by (api, error, status) (
    rate(
        awscni_aws_api_latency_ms_count{
            job=~"$daemonset",
            node=~"$node",
            error="false"
        }[$__rate_interval]
    )
)
```
![Screenshot 2024-02-26 at 1 06 42 PM](https://github.com/aws/amazon-vpc-cni-k8s/assets/768067/8aed1f8e-f504-47c1-b9c1-5e8c5f2f76ba)

Is this expected or known?

**Environment**:
Kubernetes: 1.28
CNI: 1.16.3
OS: BottleRocket 1.17.0

**Comment by jdn5126** [comment]
@diranged this is definitely not a known issue. Did the volume of these calls change at all? Does reverting to v1.16.2 immediately resolve this issue?

**Comment by jdn5126** [comment]
@diranged `v1.16.4` is now released. Can you try this release?

**Comment by orsenthil** [comment]
@diranged - Do you see the same behavior with `v1.16.4` release? This call volume could have come from transitive dependency call, and we wanted to verify that.

**Comment by orsenthil** [comment]
Later version `v1.16.4` and now `v1.17.1` is available, and we haven't seen any of reports of this. Closing and fixed.
