### ISSUE TITLE
kubelet readonly port disabled but still referenced in aws-cni-support.sh

### ISSUE THREAD

**Issue by onlybakam** [aws/amazon-vpc-cni-k8s#285]
ref:
-  https://github.com/kubernetes/kubeadm/issues/732
- https://github.com/kubernetes/kubernetes/pull/59666#issuecomment-373829976
- https://github.com/awslabs/amazon-eks-ami/issues/128

the kubelet readonly port is disabled, but the `aws-cni-support.sh` script still tries to access it:
`curl http://localhost:10255/pods  > ${LOG_DIR}/kubelet.output`

the command fails and breaks the script. The line should be removed

**Comment by max-rocket-internet** [comment]
Just make a PR to change the script? https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/aws-cni-support.sh
