### ISSUE TITLE
What is the difference between `vX.X.X` and `vX.X.X-eksbuild.x` ? 

### ISSUE THREAD

**Issue by sherifabdlnaby** [aws/amazon-vpc-cni-k8s#2867]
I couldn't find any information online.

**Comment by orsenthil** [comment]
The `vX.X.X` refers to the version of CNI. This is also the version of the AWS addon that you can see in the console or cli. The aws addon or helm charts or deployment manifests versioned as `vX.X.X` will internally be referencing some `-eksbuild.x` version.


`vX.X.X-eksbuild.x` is the internal docker image build. We increment our `eksbuild.x` version whenever we issue a _rebuild_ of the container image. 

Hope this helps.
