### ISSUE TITLE
RefreshSecurityGroups should only be called on ENIs already checked by the ENI/IP reconciler

### ISSUE THREAD

**Issue by joshjp-aws** [aws/amazon-vpc-cni-k8s#2875]
**What would you like to be added**:
I would like the current behavior to change. Currently the ENI/IP reconciler runs on a 60 second loop while the SG reconciler runs on a 30 second loop. Further both reconcilers pull information on the ENIs from IMDS.

Consider a scenario where an instance is launched and shortly after an ENI with the `node.k8s.amazonaws.com/no_manage: true` tag is added to the instance. If the SG reconciler runs before the ENI/IP reconciler it will modify the security groups as the ENI/IP reconciler hasn't had a chance to check the tags on the ENI yet. 

Ideally the SG reconciler would only run against ENIs which are known and confirmed to not have this label attached. 

One option here is to have the SG reconciler rely on an internal cache while the ENI/IP reconciler is responsible for pulling the ENIs from IMDS and determine if it is managed/unmanaged.

**Why is this needed**:
To prevent the SG reconciler from updating ENIs with the `node.k8s.amazonaws.com/no_manage: true` tag

**Comment by sorjii** [comment]
Thanks for looking at this @orsenthil. Will be on standby for the fix as this is affecting production workload in our environment.

**Comment by jayanthvn** [comment]
Basically we don't need this - https://github.com/aws/amazon-vpc-cni-k8s/blob/73c45d8d2e3b572832a9b4082c718f77d9d2ee71/pkg/awsutils/awsutils.go#L504 rather pull from datastore unmanaged ENI cache.. might it be tricky to do it and would need some refactoring..

**Comment by orsenthil** [comment]
This is addressed.

**Comment by orsenthil** [comment]
@sorjii - Not yet. We are planning to release 1.18.2 with this change and other security fixes which are in pipeline.  The change is merged in master.

**Comment by sorjii** [comment]
Thanks for the quick response, really appreciate it. :)
