### ISSUE TITLE
Conflicts .data.enable-windows-ipam

### ISSUE THREAD

**Issue by elitistphoenix** [aws/amazon-vpc-cni-k8s#2877]
**What happened**: I tried to upgrade the Amazon VPC CNI version (via the web ui) from v1.17.1-eksbuild.1 to v1.18.0-eksbuild.1. I've had issues on previous versions updates too. I get the following error:

ConfigurationConflict	
Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. 
Conflicts: ConfigMap amazon-vpc-cni - .data.enable-windows-ipam

It is enabled (set to true) since we have two windows nodes in the cluster. But this doco says to enable it?
https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support

It will upgrade fine (with no noticeable issues) if I set the "Conflict resolution method" to Preserve. I would however like to figure out and fix the issue though please.

**Environment**:
- Kubernetes version 
Client Version: v1.29.0-eks-5e0fdde
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3

- CNI Version - v1.17.1-eksbuild.1 to v1.18.0-eksbuild.1

**Comment by orsenthil** [comment]
Hello @elitistphoenix 

The default value for `enableWindowsIpam` is false. 
https://github.com/aws/amazon-vpc-cni-k8s/blob/73c45d8d2e3b572832a9b4082c718f77d9d2ee71/charts/aws-vpc-cni/values.yaml#L98

So, when you had turned to `true`, a conflict is expected when you update the addon, and it is correct action to choose "preserve".

This is documented in the AWS Documentation here:

https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#vpc-add-on-update

> The --resolve-conflicts PRESERVE option preserves existing configuration values for the add-on. If you've set custom values for add-on settings, and you don't use this option, Amazon EKS overwrites your values with its default values. If you use this option, then we recommend testing any field and value changes on a non-production cluster before updating the add-on on your production cluster. If you change this value to OVERWRITE, all settings are changed to Amazon EKS default values. If you've set custom values for any settings, they might be overwritten with Amazon EKS default values. If you change this value to none, Amazon EKS doesn't change the value of any settings, but the update might fail. If the update fails, you receive an error message to help you resolve the conflict.
