### ISSUE TITLE
Improve VPC CNI memory by reducing number of things it is caching 

### ISSUE THREAD

**Issue by GnatorX** [aws/amazon-vpc-cni-k8s#2887]
**What would you like to be added**:
Narrow down what VPC CNI is caching to reduce memory utilization in large clusters. Currently we see pretty high memory utilization and seems to scale with nodes. 

**Why is this needed**:
The current behavior is pretty problematic when cluster size gets large (5000+ nodes) causing us to increase memory request for the CNI even though it isn't necessary for the CNI to use all that memory.

I believe simply adding a new ByObject Filter on Node object is enough to reduce cache utilization. Since https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/k8sapi/k8sutils.go#L183 only gets the node object the CNI is running on.

**Comment by orsenthil** [comment]
Thanks for the report and the Pull Request. Have you done any measurements with and without this change? Could you share the differences?

**Comment by GnatorX** [comment]
Not yet. Will update once I have tested this

**Comment by GnatorX** [comment]
I took a pprof of the issue. 
![Screenshot 2024-04-29 at 10 30 58 AM](https://github.com/aws/amazon-vpc-cni-k8s/assets/6425977/d5d4a776-825b-4508-a308-79446c928f4b)

It seems like the issue is with the stream watcher is consuming memory during cluster size increase. It seems to require quite a bit of memory in order to process all nodes and store it in the memory. Even though the memory consumption isn't very high, its still unnecessary to store all node information in cache. 

I need to re-test this with my change however I do believe the real solution is to avoid performing list watch against all nodes and only watch for node events specific to the CNI.

**Comment by orsenthil** [comment]
>  K8s caches which usesList + watches on startup are extremely expensive calls

>  Even though the memory consumption isn't very high, its still unnecessary to store all node information in cache.

> I do believe the real solution is to avoid performing list watch against all nodes and only watch for node events specific to the CNI.

It is pretty standard for k8s client calls to use the cached client. It will be good to measure difference in the memory usage *and the performance* of the various operations in the large clusters before we decide to not use the cache.

With your changes, if you see any different in both memory and performance, please share an update here.

**Comment by GnatorX** [comment]
> It is pretty standard for k8s client calls to use the cached client. It will be good to measure difference in the memory usage and the performance of the various operations in the large clusters before we decide to not use the cache.

Agreed. 

When I tested my changes, it didn't yield that different in memory utilization. I believe, as shown in the pprof, the memory usage is because of the stream watcher attempting unmarshal incoming data. Short of writing a different list watcher I suspect the memory climb likely can't be fixed. At the moment the issue isn't that bad however it was concerning to see it spike up with increase in node count. 

I can close to issue for now since I likely don't have time to look into rewriting the list watcher for the kube client and I suspect the memory impact isn't big enough for most to look deeper into.

**Comment by orsenthil** [comment]
> I can close to issue for now since I likely don't have time to look into writing a direct watcher instead and I think the memory spike isn't large enough to be a concern.

This sounds reasonable, if we have better proof with improvements, we can bring this change in.

**Comment by GnatorX** [comment]
When we added the filter https://github.com/aws/amazon-vpc-cni-k8s/pull/2888 we were able to drop our memory utilization on a 3000 nodes cluster.
<img width="1595" alt="Screenshot 2024-10-10 at 11 14 15 AM" src="https://github.com/user-attachments/assets/f781446c-4127-4791-b181-059feed664e9">

**Comment by orsenthil** [comment]
> When we added the filter https://github.com/aws/amazon-vpc-cni-k8s/pull/2888 we were able to drop our memory utilization on a 3000 nodes cluster.

Could you explain this a bit more, how did adding cache filter on node reduce the VPC CNI memory utilization? Is it due to stream watcher you attributed to here - https://github.com/aws/amazon-vpc-cni-k8s/issues/2887#issuecomment-2083350407

**Comment by GnatorX** [comment]
Sorry i realize now that I commented on the PR and not the issue. Feel free to close this against the PR since it is merged now
