### ISSUE TITLE
CNI does not change service Cluster IP

### ISSUE THREAD

**Issue by oded-dd** [aws/amazon-vpc-cni-k8s#290]
AWS CNI sets a POD IP based on AWS VPC subnet network the PODs are in e.g. 

`NAME                                                              READY   STATUS              RESTARTS   AGE   IP              NODE                                          NOMINATED NODE
alertmanager-kube-prometheus-0                                    2/2     Running             0          1h    172.40.53.236   ip-172-40-58-3.eu-west-1.compute.internal     <none>`

But it does not do the same for the IP address used by the `ClusterIP` service (this IP does not affects from the IP of the VPC subnet). Which causes services that are using the IP instead of the DNS name to some issues.
e.g. 
```elasticsearch-client                                  ClusterIP      102.67.73.26     <none>                                                                             9200/TCP                        97d```

I believe both Pods and Services of type `ClusterIP` should be affected by the CNI

**Comment by labria** [comment]
`ClusterIP` service IPs are not real IPs, they only exist inside the cluster via iptables rules. They're not provisioned by the CNI, but by the API server itself.
Ideally, when building a cluster with the AWS CNI, you should make sure your cluster uses a `--service-cluster-ip-range` different from the CIDR your AWS subnet(s) use, to avoid any possible IP clashes.
