### ISSUE TITLE
make generate-limits script failed due to ENI limit mismatch

### ISSUE THREAD

**Issue by ytsssun** [aws/amazon-vpc-cni-k8s#2906]
**What happened**:
I am getting error when running `make generate-limits`.
```
A previous region has different limits for instanceType=c6in.32xlarge than region=ap-south-1
```

**Attach logs**

Full log:
```
{"level":"info","ts":"2024-05-03T22:24:57.229Z","caller":"/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51","msg":"Describing instance types in region=ap-northeast-1"}
{"level":"info","ts":"2024-05-03T22:25:00.001Z","caller":"/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51","msg":"Describing instance types in region=ap-northeast-2"}
{"level":"info","ts":"2024-05-03T22:25:01.684Z","caller":"/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51","msg":"Describing instance types in region=ap-northeast-3"}
{"level":"info","ts":"2024-05-03T22:25:02.829Z","caller":"/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51","msg":"Describing instance types in region=ap-south-1"}
{"level":"fatal","ts":"2024-05-03T22:25:04.973Z","caller":"/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51","msg":"A previous region has different limits for instanceType=c6in.32xlarge than region=ap-south-1","stacktrace":"github.com/aws/amazon-vpc-cni-k8s/pkg/utils/logger.(*structuredLogger).Fatalf\n\t/home/ec2-user/amazon-vpc-cni-k8s/pkg/utils/logger/zaplogger.go:83\nmain.describeInstanceTypes\n\t/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:178\nmain.main\n\t/home/ec2-user/amazon-vpc-cni-k8s/scripts/gen_vpc_ip_limits.go:51\nruntime.main\n\t/usr/lib/golang/src/runtime/proc.go:250"}
exit status 1
```

**What you expected to happen**:
Expect the script to run successfully and generate the `eni-max-pods.txt`.

**How to reproduce it (as minimally and precisely as possible)**:
Can be easily reproduced by running the `make generate-limits` command.

**Anything else we need to know?**:
This is currently blocking Bottlerocket 1.20.0 release (https://github.com/bottlerocket-os/bottlerocket/issues/3942)

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- CNI Version: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A

**Comment by orsenthil** [comment]
This report looks like the instance `c6in.32xlarge` does have the same maxENI value depending on the region, which is very strange.

The error being thrown is intentional to capture these issues, and it was introduced in this PR
https://github.com/aws/amazon-vpc-cni-k8s/pull/1846/files

**Comment by ytsssun** [comment]
Issue is resolved, looks like root cause is not with the script. Thanks!
