### ISSUE TITLE
Confusing environment variable names

### ISSUE THREAD

**Issue by trourance** [aws/amazon-vpc-cni-k8s#2907]
I'm planning an upgrade of our EKS cluster from 1.23 to 1.24. I would like to disable container IPv6, but the doc and the release notes are contradictory. 
In the v1.15.0 release notes, there's a mention about a variable named `DISABLE_CONTAINER_V6`, while in the doc there's no reference about it, but there's another variable named `DISABLE_POD_V6`.
Which one am I supposed to use to achieve my goals ?

https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.15.0

https://github.com/aws/amazon-vpc-cni-k8s/tree/v1.15.0

**Comment by orsenthil** [comment]
It should be `DISABLE_POD_V6` .
https://github.com/aws/amazon-vpc-cni-k8s/blob/92977ef5169506c017a90c011d48f228b8696cc1/cmd/aws-vpc-cni/main.go#L108

The 1.15 release notes are wrong.
The latest readme has the correct information.
