### ISSUE TITLE
Create secondary ENI when previous ENI isn't full due to lack of IPs in subnet - enhanced subnet discovery

### ISSUE THREAD

**Issue by jchen6585** [aws/amazon-vpc-cni-k8s#2908]
**What would you like to be added**:
When enhanced subnet discovery is enabled, we should create a secondary ENI using a new subnet (if there is one available) when the previous ENI is failing to add more IPs due to lack of IPs in subnet.

**Why is this needed**:
This will prevent IPAMD from being stuck trying to allocate IPs to the previous ENI even if the subnet is out of IPs.

**Comment by yieon-lyon** [comment]
If you provide this method, I think there will be any problems with IP loss for existing instances.
But before understanding this, we must first carefully manage subnet configuration. with cidr ...

**Comment by orsenthil** [comment]
This is addressed in https://github.com/aws/amazon-vpc-cni-k8s

**Comment by dougbyrne** [comment]
I think the previous link was meant to be https://github.com/aws/amazon-vpc-cni-k8s/pull/2954
