### ISSUE TITLE
Need aws-vpc-cni dockerfile in ironbank repo

### ISSUE THREAD

**Issue by Farhanec07** [aws/amazon-vpc-cni-k8s#2916]
**What happened**:

We're looking for Dockerfiles in ironbank repo. As aws-vpc-cni helm chart is open source, we security harden image, so we expect dockerFile in ironbank repo

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by orsenthil** [comment]
Hello @Farhanec07 , The dockerfiles are available here https://github.com/aws/amazon-vpc-cni-k8s/tree/master/scripts/dockerfiles
