### ISSUE TITLE
IP addresses still allocated to completed pods

### ISSUE THREAD

**Issue by hibbert** [aws/amazon-vpc-cni-k8s#294]
Hi,

We have some CronJobs that run hourly and then the pods return to Completed. It looks like the IP address is still in use. The ENI itself is still in use with other secondary IPs. But wandering why this stays as "In Use" despite the cronjob being complete and no pods are running? Also what is the cooling period?

Thanks

**Comment by mogren** [comment]
Hi @hibbert! 

The reasons we have the IPs around is an optimization. Also, they are not allocated to the pods, but kept as a "warm pool" per ENI for the CNI plugin to pick from when attaching IPs to new pods. Some more details in my reply on [issue 123](https://github.com/aws/amazon-vpc-cni-k8s/issues/123#issuecomment-455403330).

**Comment by mogren** [comment]
I've added some improved logging, but not been able to track down the issue. Punting this issue to 1.5.

**Comment by mogren** [comment]
Resolving since v1.5.0 is released. If you want the IPs to be released from attached ENIs, please set the `WARM_IP_TARGET` environment variable.
