### ISSUE TITLE
Setting MTU on ipv4 egress on a ipv6 only cluster

### ISSUE THREAD

**Issue by umutuzgur** [aws/amazon-vpc-cni-k8s#2949]
**What happened**:

We are trying to change the MTU values on all interfaces on our ipv6 only cluster with ipv4 egress. When we set the AWS_VPC_ENI_MTU value, this only affects the eth0 interface but not the v4if0 interface where ipv4 egress is supported. Which values do we need to set so the MTU values are persisted on both interfaces?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.30.0-eks-036c24b
- CNI Version: v1.18.1-eksbuild.3
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10.213-201.855.amzn2.x86_64

**Comment by umutuzgur** [comment]
This might become a feature request or a bug depending on how it is interpreted but we found the culprit to be this here https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/10-aws.conflist#L18. When that line is turned to `__MTU__`, everything works as expected

**Comment by orsenthil** [comment]
This may be a bug. The environment variable `AWS_VPC_ENI_MTU` is picked up and assigned to __MTU__  
Since the value was set to 9001, I assume this wasn't getting set for egress-cni property for IPV4 Egress on IPV6 Cluster.
