### ISSUE TITLE
valid openAPIV3 Schema

### ISSUE THREAD

**Issue by cyberox** [aws/amazon-vpc-cni-k8s#2963]
**What would you like to be added**:
Update the ENIConfig CRD to include a valid openAPIV3 Schema

**Why is this needed**:
When creating ENIConfig resources using Terraform manifest resources, I receive a warning:
```
│ Warning: This custom resource does not have an associated OpenAPI schema.
│
│ We could not find an OpenAPI schema for this custom resource. Updates to this resource will cause a forced replacement.
```

Terraform issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1382

**Comment by orsenthil** [comment]
aws-vpc-cni will need to add complete schema definition here - https://github.com/aws/amazon-vpc-cni-k8s/blob/e65d256c6dfa3e2dc318c6319b3c1a70addfa764/config/master/aws-k8s-cni.yaml#L33 

similar to AWS LB controller does here - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/v2_2_4_full.yaml#L37

**Comment by orsenthil** [comment]
@cyberox  - would you like to use these changes in your terraform config https://github.com/aws/amazon-vpc-cni-k8s/pull/2969 and see if the terraform behavior is fixed?

**Comment by cyberox** [comment]
@orsenthil - yes, those changes fix the issue.

**Comment by orsenthil** [comment]
This is addressed in https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.18.3
