### ISSUE TITLE
Is there a way to get the tags on the new ENIs created by CNI backend ?

### ISSUE THREAD

**Issue by hgokavarapuz** [aws/amazon-vpc-cni-k8s#297]
Wondering if there is a way to get the ENI's created by CNI backend get tagged as the original the ENI or some sort of tag to identify them easily that those are created by the CNI backend. I am trying to use the plugin with our custom spun up kubernetes clusters. [Documentation](https://aws.amazon.com/blogs/opensource/vpc-cni-plugin-v1-1-available/) shows that it creates tags but I don't see any tags on the ENIs. Are they only available if it is EKS cluster?
Here is the screenshot.

<img width="1451" alt="screen shot 2019-01-23 at 12 08 12 pm" src="https://user-images.githubusercontent.com/40212013/51634106-3faccf00-1f08-11e9-8b8c-d9fd0c3f174b.png">

**Comment by nak3** [comment]
Can you ssh into one of Nodes and grep following message?

```
# grep -rH "Failed to tag the newly created eni"  /var/log/aws-routed-eni/
```

I guess that you got some error in ipamd.log why it failed to get tags. If there are no failed log, please grep widely like - `# grep -rH tag  /var/log/aws-routed-eni/`

**Comment by nak3** [comment]
(Not sure if you are using kops, but) I tested kops and it failed to create tag. I sent a PR to upstream https://github.com/kubernetes/kops/pull/6389

**Comment by hgokavarapuz** [comment]
We are not using Kops currently, using custom scripts to spun up the cluster. let me check the logs widely if there is any error message...but I checked the code and it shows tagging feature but nothing getting tagged. Thanks @nak3

**Comment by hgokavarapuz** [comment]
I don't see any errors in the logs as well.

**Comment by hgokavarapuz** [comment]
I am able to get the tags on it. It was an issue on the permissions finally. Closing this issue in favor of the documentation [issue](https://github.com/aws/amazon-vpc-cni-k8s/issues/299)
