### ISSUE TITLE
Document the CLUSTER_NAME env variable

### ISSUE THREAD

**Issue by hgokavarapuz** [aws/amazon-vpc-cni-k8s#299]
I don't see any documentation about the CLUSTER_NAME env variable but I see that in the code which can be useful.

https://github.com/aws/amazon-vpc-cni-k8s/blob/3fba7b6aaae4766d1e667537eb072149786d30c2/pkg/awsutils/awsutils.go#L669

**Comment by markchalloner** [comment]
For others, you can use:

```
kubectl set env daemonset/aws-node -n kube-system "CLUSTER_NAME=..."
```

to set environmental variables.

**Comment by mogren** [comment]
Fixed in https://github.com/aws/amazon-vpc-cni-k8s/pull/726/
