### ISSUE TITLE
[EKS] upgrade to v1.18.2-eksbuild.1 failed by xtables-lock

### ISSUE THREAD

**Issue by yieon-lyon** [aws/amazon-vpc-cni-k8s#2993]
**What happened**:

The EKS version was upgraded, and all upgrades except vpc-cni were successful.
Why did I fail when I just followed the recommendations? I don't know why xtables-lock occurred.
All instances are AL2.

![image](https://github.com/user-attachments/assets/46b24975-2ca0-48f1-aff2-6e8a83fda80a)
![image](https://github.com/user-attachments/assets/3bcbef25-1e9b-4cae-a3e7-4e94a4e5935a)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28
- CNI Version v1.18.0-eksbuild.1
- OS (e.g: `cat /etc/os-release`): AL2
- Kernel (e.g. `uname -a`): x
- AMI: amazon-eks-node-1.28-v20240703

**Comment by yieon-lyon** [comment]
FileOrCreate

**Comment by yieon-lyon** [comment]
FileOrCreate

**Comment by RafaelrainBR** [comment]
@yieon-lyon Did you find a solution for the error?

**Comment by yieon-lyon** [comment]
> [@yieon-lyon](https://github.com/yieon-lyon) Did you find a solution for the error? If you have fixed it, could you please share the solution?

@RafaelrainBR The issue occurred on one or two nodes during the upgrade from EKS version 1.27 to 1.28. We promptly resolved it by draining the affected nodes, and the impact was quickly mitigated.
Since then, we’ve continued upgrading our EKS versions without encountering the same issue again, so we don’t consider it a major concern at this point. I also recall that the issue might have been related to NodeLocalDNS.

**Comment by yieon-lyon** [comment]
> 나에게 효과가 있었던 것은 "선택적 구성 설정" 하단에서 찾을 수 있는 "재정의" 충돌 ​​방법 해결을 사용하는 것이었습니다.
> 
> ![Image](https://github.com/user-attachments/assets/d9632a77-2c76-4e02-abd7-81537e350969)

It’s likely that overriding was inevitable in this case.
Looking back at the upgrade history, I previously updated from v1.18.0-eksbuild.1 to v1.18.2-eksbuild.1, and confirmed that an override was applied during that process.
I believe the changes between these two versions may have introduced this behavior.
