### ISSUE TITLE
Is the `VPC_ID` env var used?

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [aws/amazon-vpc-cni-k8s#2999]
**What happened**:

We are wondering if the env var `VPC_ID` added by eks is still used by the vpc-cni plugin, there's no trace of its usage in the doc or the code.
We need to know it because we are self-managing the vpc-cni addon so we need to configure all the needed env vars.

**Environment**:
- Kubernetes version (use `kubectl version`): NA
- CNI Version: NA
- OS (e.g: `cat /etc/os-release`): Bottlerocket
- Kernel (e.g. `uname -a`): NA

**Comment by orsenthil** [comment]
> We are wondering if the env var VPC_ID added by eks is still used by the vpc-cni plugin

No. We don't. But `vpc-id` is very important and we get it from the [IMDS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) of the machine
https://github.com/aws/amazon-vpc-cni-k8s/blob/18181594cb431b87eda914a34386d9992a6f1880/pkg/awsutils/awsutils.go#L461

**Comment by SharpEdgeMarshall** [comment]
Sure, I know that; we wondered why EKS put that env var if it's not used.
