### ISSUE TITLE
VPC CNI Image upgrade fails from 1.18.2 to 1.18.3 version not found

### ISSUE THREAD

**Issue by HadeedS** [aws/amazon-vpc-cni-k8s#3007]
**What happened**:

Upgrading the VPC CNI Image version from 1.18.2 to 1.18.3 failed giving an error:
`Error: chart "aws-vpc-cni" version "1.18.3" not found in https://aws.github.io/eks-charts/ repository`

**Attach logs**

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Change the image version in terraform and terraform plan fails.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.29
- CNI Version 1.18.2 > 1.18.3
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`): uname -a

**Comment by orsenthil** [comment]
@HadeedS , I apologize. I had missed publishing helm-chart, assumed the CI would triggered the publish. I have fixed it now, and the chart is now available

```
helm repo update eks
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "eks" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo eks/aws-vpc-cni --versions
```

```
[senthilx@88665a371033:~]$ helm search repo eks/aws-vpc-cni --versions |grep v1.18.3
eks/aws-vpc-cni	1.18.3       	v1.18.3    	A Helm chart for the AWS VPC CNI
```

Verified it with an installation too.
