### ISSUE TITLE
init.image.pullPolicy and nodeAgent.image.pullPolicy not being respect

### ISSUE THREAD

**Issue by zyue110026** [aws/amazon-vpc-cni-k8s#3009]
We have noticed two instances of incorrect helming in your Kubernetes configuration files. Hardcoded or default configuration values in the template are considered anti-pattern and configurable values in the values.yaml file are not being respect, resulting in user-provided configurations never being applied. Additionally, we provide anecdotal evidence from [trivy-operator#729](https://github.com/aquasecurity/trivy-operator/issues/729) regarding the incorrect helming defect.

**What happened**:

[init.image.pullPolicy](https://github.com/aws/amazon-vpc-cni-k8s/blob/18181594cb431b87eda914a34386d9992a6f1880/charts/aws-vpc-cni/values.yaml#L16) and [nodeAgent.image.pullPolicy](https://github.com/aws/amazon-vpc-cni-k8s/blob/18181594cb431b87eda914a34386d9992a6f1880/charts/aws-vpc-cni/values.yaml#L35) not take affect when changing them to other values. This is due to missing implementation for this value in daemonset.yaml file:

https://github.com/aws/amazon-vpc-cni-k8s/blob/2884e901090635ff6f0358b4e1884804ff719c7e/charts/aws-vpc-cni/templates/daemonset.yaml#L41

https://github.com/aws/amazon-vpc-cni-k8s/blob/2884e901090635ff6f0358b4e1884804ff719c7e/charts/aws-vpc-cni/templates/daemonset.yaml#L128

**Attach logs**

**What you expected to happen**:

change image pullpolicy for initcontainer and nodeAgent image can take affect, or delete these two values in value.yaml file

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version: main version
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by orsenthil** [comment]
This is fixed in https://github.com/aws/amazon-vpc-cni-k8s/pull/3010 and will be available in next release.

**Comment by orsenthil** [comment]
This is fixed and released.
