### ISSUE TITLE
Move KUBE_CONFIG_PATH variable to KUBECONFIG variable

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-cni-k8s#3014]
In tests we use Move KUBE_CONFIG_PATH variable,and it causes confusion. We should move the usage of KUBECONFIG variable, so that we don't confuse un-conventinal variable name  KUBE_CONFIG_PATH

**Comment by 852hamza** [comment]
@orsenthil  can you assign me , i can resolved  it

**Comment by 852hamza** [comment]
@orsenthil kindly check this pull request 
[](https://github.com/aws/amazon-vpc-cni-k8s/pull/3015)
