### ISSUE TITLE
Update to v.1.18.3 fails with crd conflict

### ISSUE THREAD

**Issue by nan008** [aws/amazon-vpc-cni-k8s#3028]
**What happened**:

We have a problem with one of the clusters to update the vpc-cni addon on AWS EKS. Running out of the aws box install without any customization. 

The upgrade from v1.18.2-eksbuild.1 to v1.18.3-eksbuild.1 or v1.18.3-eksbuild.2 is failing with 

```
Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. Conflicts: CustomResourceDefinition.apiextensions.k8s.io eniconfigs.crd.k8s.amazonaws.com - .spec.versions
```

Our policy for resolving conflicts in None

2 other clusters updated this addon without issue (no customization, none for conflicts resolution on those as well)

The addons are updated by lambda

Any ideas why this might have happened?

**Environment**:
- Kubernetes version 1.30
- CNI Version v1.18.2-eksbuild.1

**Comment by orsenthil** [comment]
> Conflicts found when trying to apply. Will not continue due to resolve conflicts mode. Conflicts: CustomResourceDefinition.apiextensions.k8s.io eniconfigs.crd.k8s.amazonaws.com - .spec.versions

You could verify what is version set in the previous chart. These are easy to force apply.

You could see the versions and difference here
https://github.com/aws/eks-charts/compare/v0.0.176...v0.0.177

> 2 other clusters updated this addon without issue (no customization, none for conflicts resolution on those as well)

This is strange. The behavior of the helm update from all base versions should be same, unless the one of the clusters was modified.

**Comment by orsenthil** [comment]
Closing this as we don't have additional information.
