### ISSUE TITLE
Pod IP inaccessible from other nodes without calico.yaml applied

### ISSUE THREAD

**Issue by svanlund** [aws/amazon-vpc-cni-k8s#303]
**Background**

I'm currently experimenting with setting up clusters using kubeadm. Started with Flannel networking which worked fine but then decided to give the AWS networking plugin a go since I'm running in that environment.

**Problem**

After applying aws-k8s-cni.yaml as instructed in the README and bringing up the nodes, a pod deployed to one of the nodes will only be accessible from the particular node where it has been scheduled. As in that "curl -v 172.xx.xx.xx" (that's the "podIP") will stall when executed from any other node (including master). 

After troubleshooting for some time, I started to wonder whether applying calico.yaml, the other file in https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config/v1.3, would change anything. This file is not mentioned in the README instructions, but turned out to resolve the issue I was facing. After applying calico.yaml, the "podIP" became accessible from any node, including master.

**Suggested resolution**

The change in behavior after applying calico.yaml indicates that it is an important step which should be included in the README. I would love to contribute a PR, but I understand that it may not be as simple as saying "always apply calico.yaml". Perhaps there is something special about my particular setup that contributes to the problem. So I'm opening this issue to get your thoughts first.

**My setup / Steps to reproduce**

CNI plugin 1.3.0
eu-north-1 region
Ubuntu 18.04 LTS (ami-34c14f4a)
Kubernetes v1.13.2
IAM role with policy like in the README example, plus AmazonEC2ContainerRegistryReadOnly.
Same security group, all communication between instances allowed (source: SG or VPC CIDR).

This is the basic, semi-automated approach I'm using at the moment (user data):

```
#!/bin/bash
apt-get update
apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install -y docker-ce
usermod -aG docker ubuntu
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y python-pip
pip install awscli
eval $(aws ecr get-login --no-include-email --region eu-north-1)
sed -i 's/XXXXXXXXXXXX/602401143452/g' /root/.docker/config.json
docker pull 602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon-k8s-cni:1.3.0
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
```

For the master, SSH to the instance. Run kubeadm init (no args) manually. Apply https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config/v1.3/aws-k8s-cni.yaml with modified region in "image", and "imagePullPolicy: Never" as a workaround for auth issues.

For the nodes, append to user data script before launching instance:
```
kubeadm join 172.XX.XX.XX:6443 --token xxxxxxxxxxxxx --discovery-token-ca-cert-hash sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Start small demo app from https://github.com/kubernetes-up-and-running/kuard:
```
$ kubectl run --restart=Never --image=gcr.io/kuar-demo/kuard-amd64:1 --port=8080 kuard
```
```
$ kubectl get pod kuard -o yaml | grep "podIP"
  podIP: 172.31.23.12
``` 

From master/node where the pod *is not* scheduled:
```
$ curl -v 172.31.23.12:8080
* Rebuilt URL to: 172.31.23.12:8080/
*   Trying 172.31.23.12...
* TCP_NODELAY set
```
From node where the pod *is* scheduled:
```
$ curl -v 172.31.23.12:8080
* Rebuilt URL to: 172.31.23.12:8080/
*   Trying 172.31.23.12...
* TCP_NODELAY set
* Connected to 172.31.23.12 (172.31.23.12) port 8080 (#0)
> GET / HTTP/1.1
> Host: 172.31.23.12:8080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
...
```

This is where I got stuck initially. As mentioned above, I later applied calico.yaml, like this:

```
$ kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/calico.yaml
```

After a few seconds, the pod is accessible from any node, including master, using the exact curl command above that failed previously.

**Comment by nak3** [comment]
The output looks no problem. I have tried to produce the same error, but could not happen on my env, which is deployed by kops and other region but used ubuntu (ami-0c5199d385b432989) and `ens5` for its primary interface. (Actually I suspected the name of primary interface `ens5` was the issue and found one bug at https://github.com/aws/amazon-vpc-cni-k8s/pull/305, but `ens5` was not related to your issue :cry:)

**Comment by edgan** [comment]
I am having the same problem. I am also using AWS CNI 1.3.0, Ubuntu 18.04, AWS, and Kubernetes 1.13.3. I do have an IAM policy for giving the AWS CNI access to the AWS API, as mentioned in the documentation.

I did add `--network-plugin=cni`, `--cni-bin-dir` and `--node-ip`, but nothing changed.

It seems like the `--node-ip` should be auto-detected. It is also not 100% clear what ip should be given to `--node-ip`. At the moment I am giving it the only ip address of eth0.

Both when I had tried using flannel before the AWS CNI, or AWS CNI with Calico, it seems to at least further initialize. But AWS CNI on it's own doesn't seem to do anything.

If the procedure it is going through was documented it would be a huge help to debugging this. Currently it just seems like auto-magic.

**Comment by edgan** [comment]
I see multiple ip addresses assigned to the ENI in the console, but Ubuntu is not detecting them. Seems like I need some configuration to tell it to dhcp all the ip addresses.

**Comment by mogren** [comment]
@edgan @svanlund Is this still an issue?

**Comment by svanlund** [comment]
Thanks for checking in! My experimentation with this setup ended a while back without the issue being resolved. Since my exact problem couldn't be reproduced, I'm fine with the issue being closed.
