### ISSUE TITLE
Support adding custom labels to CNI Helm chart

### ISSUE THREAD

**Issue by kwohlfahrt** [aws/amazon-vpc-cni-k8s#3030]
**What would you like to be added**:

Support adding custom labels to all objects of the CNI Helm chart.

**Why is this needed**:

We would like to add labels to all core infrastructure components of our deployment, to make them easier to identify. This is often supported by Helm charts, e.g. the cluster autoscaler has [`additionalLabels`](https://github.com/kubernetes/autoscaler/blob/cecb34cb863fb015264098b5379bdba40a9113cf/charts/cluster-autoscaler/values.yaml#L6).

I'm happy to open a PR for this change.

**Comment by orsenthil** [comment]
> I'm happy to open a PR for this change.

@kwohlfahrt ; sure, please share your change.
