### ISSUE TITLE
Is ENABLE_SUBNET_DISCOVERY fully compatible with CustomNetworking/ENIConfigs?

### ISSUE THREAD

**Issue by sidewinder12s** [aws/amazon-vpc-cni-k8s#3058]
**What happened**:

Is the new `ENABLE_SUBNET_DISCOVERY` setting compatible with folks using CustomNetworking with custom ENIConfigs to specify pod secondary subnets? I couldn't find much in the issues about this other than some folks mentioning that you cannot use `ENABLE_SUBNET_DISCOVERY` with custom IP addressing settings for IP conservation/split subnet (host primary/pod secondary subnets)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.29
- CNI Version: Latest
- OS (e.g: `cat /etc/os-release`): EKS AMI
- Kernel (e.g. `uname -a`): 5.10

**Comment by orsenthil** [comment]
Custom Networking is a separate feature over the _solution_ for IP-exhausion with `ENABLE_SUBNET_DISCOVERY`

As we mention in our blog post - https://aws.amazon.com/blogs/containers/amazon-vpc-cni-introduces-enhanced-subnet-discovery/

Custom networking takes precedence when both features are enabled on the VPC CNI.
