### ISSUE TITLE
CHANGELOG.md unmainteainted since 1.18.5 release

### ISSUE THREAD

**Issue by arthurzenika** [aws/amazon-vpc-cni-k8s#3127]
**What happened**:

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md only mentions versions up to v1.18.5, but https://github.com/aws/amazon-vpc-cni-k8s/releases shows 1.18.6 and 1.19.0 

**Attach logs**

n/a

**What you expected to happen**:

For the CHANGELOG to be updated for each release

**How to reproduce it (as minimally and precisely as possible)**:

n/a

**Anything else we need to know?**:

n/a

**Environment**:
- Kubernetes version (use `kubectl version`): n/a
- CNI Version : n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a

**Comment by orsenthil** [comment]
Thanks for raising. The current changelog title should say 1.18.6. The title is wrong.
1.19 got just released. https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.19.0
We will merge the changelog from 1.19 branch to master. Sync was in progress - https://github.com/aws/amazon-vpc-cni-k8s/pull/3118

**Comment by orsenthil** [comment]
Resolved by this PR https://github.com/aws/amazon-vpc-cni-k8s/pull/3136
