### ISSUE TITLE
L-IPAMD IP allocation and usage configuration possibility

### ISSUE THREAD

**Issue by daugustus** [aws/amazon-vpc-cni-k8s#314]
I have been experiencing some challenges with IP starvation where an EKS cluster uses all, or almost all available IP addresses within each subnet. I understand the reasoning about pre-assigning ENIs and IPs due to latency that can occur. However, we have some use cases where this behavior is unwanted. Is there a configuration setting that can control/limit the number of IPs assigned? For example, some workloads require higher resources so that larger instances are created for worker nodes. In these cases, alot of the IPs are not going to be used as there will be few pods assigned. Thoughts? Ideas?

**Comment by nak3** [comment]
Do you want to control less than the num of max IPs per ENI? For example, `m4.4xlarge` consumes 30 IP addresses per 1 ENI. You want to limit the num of IPs less than 30.

If No (you don't need to control less than 30 for `m4.4xlarge`), you can set `WARM_ENI_TARGET` or `WARM_IP_TARGET`. Or you can use `MAX_ENI` https://github.com/aws/amazon-vpc-cni-k8s/pull/251 in the future release. I believe `MAX_ENI` is not implemented in current image, though.

If Yes (you want to control less than 30 for `m4.4xlarge`), I am pretty sure that it is not possible for now. ipamD always allocates IPs at least `maxAddrsPerENI` (=`30` IPs for `m4.4xlarge`) as:

https://github.com/aws/amazon-vpc-cni-k8s/blob/4a51ed41abf61b7445f8226e5a086a8ec9b0581b/ipamd/ipamd.go#L723

**Comment by daugustus** [comment]
Yes- I would want to limit the max number of IPs per instance.

**Comment by mogren** [comment]
@daugustus If your pod churn is low, and you only have a few pods per node, setting `WARM_IP_TARGET` should solve this issue for you. Setting `MAX_ENI` would also cap your upper limit.
