### ISSUE TITLE
How to use VPC CIDR

### ISSUE THREAD

**Issue by benishak** [aws/amazon-vpc-cni-k8s#315]
Hi

We created an EKS cluster with latest AMI EKS optimized and kubenertes 1.11.5
my VPC subnet CIDR is 172.29.16.0/24 and i'm using public subnet for my worker nodes
I started my worker nodes and added additional args
```
--network-plugin=cni --pod-cidr 172.29.16.0/20
```

When I run `ifconfig` inside the pod/container I can see that pods are using the IPs from my VPC Subnet

My issue is that if I use hostnames like "redis-master" in my application (like guestbook) it get resolved to 10.100.x.x 
the CoreDNS resolver is 10.100.0.10 which is setup on the /etc/resolv of the pod
I can reach other pods with the both 10.100.x.x and 172.29.x.x IPs
so I think it is only issue with CoreDNS resolving dns to 10.100.x.x

```
kubectl get svc
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP                                                                    PORT(S)          AGE
guestbook      LoadBalancer   10.100.3.83     a52cb7843293911e9b86b0aadae1b41c-2014636973.ap-northeast-1.elb.amazonaws.com   3000:30449/TCP   1d
kubernetes     ClusterIP      10.100.0.1      <none>                                                                         443/TCP          2d
redis-master   ClusterIP      10.100.201.93   <none>                                                                         6379/TCP         1d
redis-slave    ClusterIP      10.100.12.11    <none>                                                                         6379/TCP         1d
```

but Endpoints is showing 172.29.x.x

```
Name:                     guestbook
Namespace:                default
Labels:                   app=guestbook
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"guestbook"},"name":"guestbook","namespace":"default"},"spec":{"ports"...
Selector:                 app=guestbook
Type:                     LoadBalancer
IP:                       10.100.3.83
LoadBalancer Ingress:     a52cb7843293911e9b86b0aadae1b41c-2014636973.ap-northeast-1.elb.amazonaws.com
Port:                     <unset>  3000/TCP
TargetPort:               http-server/TCP
NodePort:                 <unset>  30449/TCP
Endpoints:                172.29.23.70:3000,172.29.25.233:3000,172.29.31.212:3000
Session Affinity:         None
External Traffic Policy:  Cluster
```

what am I doing wrong?

**Comment by frimik** [comment]
Adding the `--pod-cidr` flag to the worker nodes doesn't help. It's taken from the master nodes unless you're running in what's called `standalone` mode.

**Comment by benishak** [comment]
i had misunderstanding
kubernetes utilise a 2nd CIDR for VIPs for internal communication but the pods get assigned ip from the vpc cidr fukly routable
