### ISSUE TITLE
upgrading to 1.3.2 but it remains 1.3.0

### ISSUE THREAD

**Issue by pahud** [aws/amazon-vpc-cni-k8s#321]
I was upgrading from 1.2.1 to 1.3.2 according to [this document](https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html), however, it seems to be the cni version is `1.3.0`.

https://github.com/aws/amazon-vpc-cni-k8s/blob/4a51ed41abf61b7445f8226e5a086a8ec9b0581b/config/v1.3/aws-k8s-cni.yaml#L71

```
pahud:~/environment $ kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni:1.2.1
pahud:~/environment $ kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/aws-k8s-cni.yaml
clusterrole.rbac.authorization.k8s.io "aws-node" configured
serviceaccount "aws-node" unchanged
clusterrolebinding.rbac.authorization.k8s.io "aws-node" configured
daemonset.extensions "aws-node" configured
customresourcedefinition.apiextensions.k8s.io "eniconfigs.crd.k8s.amazonaws.com" configured
pahud:~/environment $ kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni:1.3.0
```

How can I make sure it's already `1.3.2`?

**Comment by pahud** [comment]
checking the log and it seems to remain `v1.3.0`

`tail -f /var/log/aws-routed-eni/*`

![image](https://user-images.githubusercontent.com/278432/52786281-7607e500-3095-11e9-936e-53f302a477be.png)

**Comment by bootc** [comment]
Indeed, https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.3.2/config/v1.3/aws-k8s-cni.yaml is stuck on v1.3.0. If you change the tag to v1.3.2 then the image pull fails.

**Comment by sdavids13** [comment]
The latest config file on master has the 1.3.2 version set (permalink): https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/0121d79566efa768275d3ec3d95fb7a599f84614/config/v1.3/aws-k8s-cni.yaml

The annoying part is that the version changed slightly to have a `v` prefixed so the image version is `v1.3.2` instead of the old version of just `1.3.0`.

Commit used to update the yaml file: https://github.com/aws/amazon-vpc-cni-k8s/commit/0121d79566efa768275d3ec3d95fb7a599f84614#diff-c5b46112cd953925bd7125f8ce8296e5

**Comment by Deshke** [comment]
```
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.3.2: no basic auth credentials
``` 

strangely enough both `1.3.0` and `v1.3.2` now require some auth....

**Comment by mogren** [comment]
This was definitely a mistake in the 1.3 release branch. Put up a CR.

**Comment by tabern** [comment]
It looks like this was a previous commit on the 1.3 branch. This is updated in the latest master and 1.3 branch. https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.3/config/v1.3/aws-k8s-cni.yaml

**Comment by Jportofolio** [comment]
Here is my solution:
1. login to aws ecr:
  aws ecr get-login --region us-west-2 --no-include-email

2. the above cmd returns somthing like this:
   sudo docker login -u AWS -p eyJwYXlsb2FkIjoiak5aRDNKdFVvZ3BtMjluaWJTMnlMdm1LREVXNndlc2dHK0kvL3ZnY1haS2NsS1ptUmJGYnRtNlNGL2tZMUhiTU1NdEZpN3NZM= https://602401143452.dkr.ecr.us-west-2.amazonaws.com

3. pull the image on my Local workstation:
  sudo docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2

4. Tag to my public repo:
    sudo docker tag 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.3.2 Myusername/602401143452.dkr.ecr:v1.3.2

5.  Push it 
   sudo docker push Myusername/602401143452.dkr.ecr:v1.3.2
6. update the image on aws-k8s-cni.yaml
7. sudo kubectl -f apply
