### ISSUE TITLE
EKS and fixed IP for pods

### ISSUE THREAD

**Issue by mikehalof** [aws/amazon-vpc-cni-k8s#326]
Hi,
I'm using EKS and I'd like to assign a static IP to a pod. 
Is that something possible using this plug-in?

Mike

**Comment by mogren** [comment]
Like Kenjiro said, it's not part of the CNI.

**Comment by tn-ascera** [comment]
> No, it is not possible by using this plugin's specific feature. 

Is this still true as of 2026?

**Comment by yash97** [comment]
No, we do not support static IPs as of now. However, if you have a use case, I would encourage you to create a GitHub issue in this repository: https://github.com/aws/containers-roadmap/issues
