### ISSUE TITLE
IPs are not released when WARM_IP_TARGET=1

### ISSUE THREAD

**Issue by xrl** [aws/amazon-vpc-cni-k8s#329]
I am running my cluster (kops managed) inside of a small VPC (corporate policy on IP space was not generous). I have set `WARM_IP_TARGET=1` but what I find after auditing IPs:

```
$ python ~/aws-vpc-cni/audit.py
found 353 unused IPs
{   u'ip-10-43-168-101.ec2.internal (us-east-1c) elasticsearch eni-0d1d1b70964c06bf1': 3,
    u'ip-10-43-168-112.ec2.internal (us-east-1c) elasticsearch eni-0f457fb5ecc4b6b0c': 2,
    u'ip-10-43-168-116.ec2.internal (us-east-1c) elasticsearch eni-05f7e15dcb81d57b4': 3,
    u'ip-10-43-168-117.ec2.internal (us-east-1c) elasticsearch eni-098d5b63d3911317e': 3,
    u'ip-10-43-168-12.ec2.internal (us-east-1c) elasticsearch eni-0267e39e9192862c5': 3,
[[[ SNIP ]]]
```

it sounds like IP pressure over the life of the pod can cause IPs to accumulate but there's no process for returning unused IPs?

You can see my audit script here: https://gist.github.com/xrl/b135198336a142e86f0d2d862b0448e3

**Comment by tabern** [comment]
Part of https://github.com/aws/amazon-vpc-cni-k8s/issues/294
