### ISSUE TITLE
Create a Helm Chart for this CNI and its resources

### ISSUE THREAD

**Issue by max-rocket-internet** [aws/amazon-vpc-cni-k8s#336]
It would be great to have a Helm Chart for this CNI.

This would make a few things easier for cluster administrators:
- Upgrades (or downgrades)
- Setting config options
- Over riding settings
- Enabling the new prometheus metrics
- Nice versioning across clusters
- Easy installation into non-EKS cluster. e.g. kops.

The chart could be in this repo or in [stable](https://github.com/helm/charts/tree/master/stable)

**Comment by forsberg** [comment]
The beginnings of this are available here: https://github.com/mrzobot/calico-helm-chart

**Comment by max-rocket-internet** [comment]
Done. Feedback welcome: https://github.com/aws/eks-charts/pull/27

**Comment by max-rocket-internet** [comment]
DONE
