### ISSUE TITLE
Rename Prometheus metrics to be more conventional

### ISSUE THREAD

**Issue by max-rocket-internet** [aws/amazon-vpc-cni-k8s#337]
Currently the metrics exposed are named:

- ipamd_error_count
- ipamd_action_inprogress
- eni_allocated
- total_ip_addresses
- assigned_ip_addresses

I would say these names are not very informative or consistent with [metric and label conventions](https://prometheus.io/docs/practices/naming/). Specifically:

> A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to

I propose we prefix all the metrics names with `aws_cni_`.

Should I make a PR for this?

**Comment by mogren** [comment]
Hi @max-rocket-internet,

Yes, please do. I agree that we should follow the standard prometheus conventions.

**Comment by max-rocket-internet** [comment]
Here: https://github.com/aws/amazon-vpc-cni-k8s/pull/348
