### ISSUE TITLE
Migrate ENIConfig groupName to k8s.aws

### ISSUE THREAD

**Issue by christopherhein** [aws/amazon-vpc-cni-k8s#339]
Before we move the `ENIConfig` CRDs to `beta` or `stable` we should move the `groupName` under `[project].k8s.aws` to follow the same pattern we're using for other tools.

**Comment by TBBle** [comment]
This hasn't happened yet per https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/apis/crd/v1alpha1/groupversion_info.go.

**Comment by TBBle** [comment]
This hasn't happened yet per https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/apis/crd/v1alpha1/groupversion_info.go.
