### ISSUE TITLE
Failed to CreateNetworkInterface InvalidSecurityGroupID.NotFound

### ISSUE THREAD

**Issue by Pryz** [aws/amazon-vpc-cni-k8s#343]
Hello,

Current version : 1.3.2.
Configuration : default from the AWS EKS AMI.

I'm hitting an issue where ipamd is trying to use a Security Group which doesn't exist anymore to create an ENI. The error message is the following : 
```
2019-03-12T13:59:53Z [ERROR] Failed to increase pool size due to not able to allocate ENI allocate eni: failed to create eni: failed to create network interface: InvalidSecurityGroupID.NotFound: The securityGroup ID 'sg-003456d92039559fb' does not exist
```
From the logs, I see that this SG was found at the start of L-IPAMD : 
```
2019-03-12T01:27:58Z [DEBUG] Found security-group id: sg-003456d92039559fb
```

From https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/awsutils/awsutils.go#L283-L294, it seems that the security groups are coming from the metadata. However if I query the metatada I don't see it.

My guess is that the SG was there at the bootstrap of the instance but it is not anymore and ipamd doesn't refresh its cache.

Am I missing something here ? Is it possible to make ipamd refreshes its cache ?

Thanks

**Comment by Pryz** [comment]
To force refreshing the metadata cache I recycled the `aws-node` PODs which is not necessarily something you would want to do in a production environment. :)

**Comment by mogren** [comment]
I don't think there is any cache refresh functionality right now, but it sounds like a very useful feature.

**Comment by jaypipes** [comment]
Hi @Pryz, sorry for the delay in following up on this. We recognize this may be an issue, and may add some retry behaviour to the `AllocENI()` call to handle this cache sync issue, however at this point, doing that is a low priority for us. If you disagree that this is a low-priority request, please do let us know.

**Comment by mogren** [comment]
Related to https://github.com/aws/amazon-vpc-cni-k8s/issues/277

**Comment by mogren** [comment]
Tracking as a feature in #737
