### ISSUE TITLE
Incorrect SNAT setup when multiple CIDRs on VPC

### ISSUE THREAD

**Issue by tmjd** [aws/amazon-vpc-cni-k8s#35]
## Description 

I was using a VPC that had two IPv4 CIDRs and a subnet with only one of the CIDRs, this resulted in all traffic being dropped with any policy even when trying to match with a pod label.  Using tcpdump I observed on the host with the source pod that all traffic from the pod would be SNAT'ed before being sent to the destination host.

## Observed behavior

IP addresses being assigned to pods were in the subnet 172.32.0.0/16 while the SNAT iptables rule was setup for 172.31.0.0/16.  This resulted in all traffic between hosts being SNAT'ed which caused Calico network policy to block all traffic between hosts.

Here is the iptables SNAT rule:
```
-A POSTROUTING ! -d 172.31.0.0/16 -m comment --comment "AWS, SNAT" -m addrtype ! --dst-type LOCAL -j SNAT --to-source 172.32.0.27
```

## Expected behavior

SNAT will be setup correctly when there are more than one CIDR in a VPC.

**Comment by SaranBalaji90** [comment]
@tmjd I'm curious to know, how did you set up multiple IPv4 CIDRs on a single VPC? Can you add the commands here?

**Comment by tmjd** [comment]
@SaranBalaji90 I did not set it up myself but was using a VPC someone else had setup.

**Comment by ewbankkit** [comment]
@SaranBalaji90 You can associate secondary IPv4 CIDR blocks to a VPC via the EC2 API [`AssociateVpcCidrBlock`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateVpcCidrBlock.html) method or associated [CLI command](https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-vpc-cidr-block.html).

**Comment by xdrus** [comment]
Hi there,

VPC can have multiple CIDRS assigned [1], [2] (default limit is up to 5). Currently plugin fetches only main CIDR [3] from metadata:
```go
	// retrieve vpc-ipv4-cidr-block
	cache.vpcIPv4CIDR, err = cache.ec2Metadata.GetMetadata(metadataMACPath + mac + metadataVPCcidr)
	if err != nil {
		log.Errorf("Failed to retrieve vpc-ipv4-cidr-block from instance metadata service")
		return errors.Wrap(err, "get instance metadata: failed to retrieve vpc-ipv4-cidr-block data")
	}
	log.Debugf("Found vpc-ipv4-cidr-block: %s ", cache.vpcIPv4CIDR)
```

And then use only this primary block to set up SNAT rule [4].

The additional blocks can be fetched using the "network/interfaces/Macs/<mac>/vpc-ipv4-cidr-blocks" metadata path [5], but then VPC CIDR parameters should be either list or additional parameter is needed to pass through additional VPC CIDRs and then used to correct SNAT rules.

Best,
Ruslan.

[1] https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html#VPC_Sizing
[2] https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-vpcs-subnets
[3] https://github.com/aws/amazon-vpc-cni-k8s/blob/3168630f86c0af63724a1a018341c819ca935a9c/pkg/awsutils/awsutils.go#L226
[4] https://github.com/aws/amazon-vpc-cni-k8s/blob/b7c92b99b3643ca6f67391464f8548e0d6135734/pkg/networkutils/network.go#L72-L117
[5] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

**Comment by sdavids13** [comment]
Could we define what the expected behavior is for this NAT rule? i.e. should it include *just* the CIDR block that contains the POD networking layer such as:
`-A POSTROUTING ! -d 172.32.0.0/16 -m comment --comment "AWS, SNAT" -m addrtype ! --dst-type LOCAL -j SNAT --to-source 172.32.0.27`

Or.. should it include all VPC CIDR blocks such as (not sure if this is the correct syntax):
`-A POSTROUTING ! -d 172.31.0.0/16,172.32.0.0/16 -m comment --comment "AWS, SNAT" -m addrtype ! --dst-type LOCAL -j SNAT --to-source 172.32.0.27`

I believe it would be the former, but have minimal iptables expertise.

**Comment by tabern** [comment]
Part of version 1.3
