### ISSUE TITLE
EKS worker node not able to communicate with RDS in a different VPC

### ISSUE THREAD

**Issue by krish7919** [aws/amazon-vpc-cni-k8s#352]
I have installed an EKS cluster in a branch new VPC and am unable to access an RDS instance located in another VPC. I have peered the VPCs to achieve as per https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.Scenarios.html#USER_VPC.Scenario3.

The EKS worker instance has a security group attached to it, which has been allowed in RDS.

The peculiar case starts now:

1. In this scenario, the pod on the specific node cannot access RDS at all and times out; DNS lookup works though. In this case, I have specifically allowed the TCP port from the worker security group in the security group attached to the RDS instance.

2. In this scenario, the pod can telnet into the RDS instance; DNS works fine too. In this case, I have allowed `All traffic` from all IP addresses in the security group attached to the RDS instance.

My question is: why does specifying a security group ingress rule using the source security group ID not working, whereas a blanked allow works every time?

Is the pod IP/secondary IP not considered to be attached to the security group?

What would be a solution for such cross VPCs communication between various AWS services/instances in EKS?

EDIT: If it matters, I did the VPC peering and the RDS security group change after the EKS worker was up. FYI as I don't think it should matter as it works in the second case above.

**Comment by krish7919** [comment]
Disabling SNAT using `AWS_VPC_K8S_CNI_EXTERNALSNAT` does't help either.

**Comment by frimik** [comment]
@krish7919 Are you peering between two different AWS regions or the same region? Same AWS Account or different AWS accounts?

Read the three important points here: https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-security-groups.html

**Comment by krish7919** [comment]
Ok. I could resolve my issue a few days ago. I had not provided the right permissions to the K8S/EKS worker IAM role to create and attach additional network interfaces. Logging into the machine and looking at the IPAM logs showed that clearly and I could then fix it easily.

**Comment by krish7919** [comment]
I had an issue with the peering configuration and deleted and correctly recreated it to resolve the issue.

**Comment by MarkPare** [comment]
@krish7919 what was your issue? I'm in a similar situation but haven't been able to figure it out.

**Comment by krish7919** [comment]
@MarkPare I did put it [here](https://github.com/aws/amazon-vpc-cni-k8s/issues/352#issuecomment-480113083)

**Comment by MarkPare** [comment]
@krish7919 yeah I was wondering about what the issue was specifically (e.g. misconfigured subnets in routing table, etc.). I actually did it a second time and was able to get it working.  For posterity, in this SO post, if you follow the OP's steps 1-6 and then make sure you enable DNS propagation/resolution as suggested by the top answer, things should work: https://stackoverflow.com/questions/53571908/kubernetes-have-no-access-from-eks-pod-to-rds-postgres

**Comment by Tanya-movmint** [comment]
https://stackoverflow.com/questions/76899023/rds-while-connection-error-no-pg-hba-conf-entry-for-host

Really helpful^^
