### ISSUE TITLE
Could we split the ipam CNI from the rest?

### ISSUE THREAD

**Issue by jacksontj** [aws/amazon-vpc-cni-k8s#353]
CNI supports chaining of plugins-- in the example plugins (https://github.com/containernetworking/plugins/) this is generally used to split the routing configuration from ipam. Other CNI plugins (such as lyft's -- https://github.com/lyft/cni-ipvlan-vpc-k8s/pull/47) do the same thing and make their CNIs chainable.

We've been using a fork of this plugin for a while (and are working to use upstream) but there are a lot of features I don't want. For my setup I'd prefer to have an IPAM + the example ptp plugin (no special iptables, etc.). If this CNI plugin was split into 2 it would open up a lot of options for reducing complexity and allow for more re-usable plugin chaining.

The proposal would be specifically to pull the IPAM section out (managing ENIs etc.) and change the current CNI plugin to chain off of that.

**Comment by jacksontj** [comment]
This would more easily enable things such as https://github.com/cilium/cilium/issues/6430 (as they wouldn't need to re-implement, but rather just use the native CNI layering).

**Comment by mogren** [comment]
The problem here is that using real VPC IPs requires some extra configuration on the node to get the routes right. This results in some coupling between ipamd and the CNI plugin that is hard to address.

**Comment by mogren** [comment]
I don't think we can split ipamd out completely, but we could make CNI chaining easier. Our efforts to add the Bandwidth plugin in #463 is currently blocked on containerd/cri#1544.

**Comment by jayanthvn** [comment]
#1580 fixes the issue with chaining. Also if you don't want IPAMD to manage ENIs/IPs, you can configure this https://github.com/aws/amazon-vpc-cni-k8s#disable_network_resource_provisioning-v191 starting CNI 1.9.1 onwards. There is no plans to split IPAMD out as mentioned by @mogren .
