### ISSUE TITLE
setup NS network: failed to add host route: file exists / UpdateRuleListBySrc: failed to add pod rule: file exists

### ISSUE THREAD

**Issue by erolosty** [aws/amazon-vpc-cni-k8s#357]
Similar issue to: https://github.com/aws/amazon-vpc-cni-k8s/issues/344

Breaking the issue out as it seems the author of that one said he is 'rolling back'

Kubernetes: 1.13.3
CNI: 1.3.2

We are seeing Pods get stuck starting with:

```
failed to setup network: setup NS network: failed to add host route: file exists
failed to setup network: UpdateRuleListBySrc: failed to add pod rule: file exists
```

Our current best guess is that the unix.NLM_F_EXCL flag in

https://github.com/vishvananda/netlink/blob/master/route_linux.go#L455

Called from:

https://github.com/aws/amazon-vpc-cni-k8s/blob/c322c8d8c4aa5ca7abd85be7896c385fe89dc7d1/pkg/netlinkwrapper/netlink.go#L131

is inappropriate in some cases, and that if the route exists it would be preferable to simply replace it with the newer one by instead calling:

https://github.com/vishvananda/netlink/blob/master/route_linux.go#L468

We haven't grokked the code base - far from it, it might be that there is very good reason why the exclusive flag is required, and that seeing this bug is actually just a symptom of something wider reaching (The opinion of a developer closer to the code base would be helpful)

We're currently investigating this, and will update this ticket with any progress we make

We're operating currently under the assumption that somehow routes are being left around, when they should have been cleaned out. 

To reduce pages in our team we are also looking into options for detecting/working around this issue, if they are more readily available than a true bug fix

For our workloads it would even be possible to turn machines off, and let the ASG create a fresh one, if we could detect that we were approaching the conditions in which the bug would happen

**Comment by jaypipes** [comment]
@erolosty we believe this is fixed with #367 which is in the CNI 1.4 release, which was cut in April and covers k8s 1.13. Closing this out.
