### ISSUE TITLE
Does this CNI support containerd?

### ISSUE THREAD

**Issue by rudoi** [aws/amazon-vpc-cni-k8s#365]
Is there any part of this CNI that would not function well with containerd (aka not docker)? If so, why?

**Comment by mogren** [comment]
Currently [ipamd](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/ipamd/ipamd.go#L323) uses the go docker client to call `GetRunningContainers()` to find the local pods on the node, but that is the only place. I have not tested another runtime myself, so I'm not sure what would be needed to support that.

**Comment by rudoi** [comment]
Thanks @mogren. I'm curious... what is the reason for retrieving the container ID from Docker, as opposed to checking a container status via Kube API? I have a PR ready to go that completely skips checking Docker, but I'm wondering if I'm missing something critical about the CNI's functionality that requires the container ID from Docker specifically.

If this is required, I will have to implement a client for interfacing with containerd instead, but that is a much larger piece of work. 😄

**Comment by mogren** [comment]
I really don't know why Liwen wrote it that way. The last related change was in #86, way before my time.

**Comment by rudoi** [comment]
I opened #371 proposing getting the container ID from the Kubernetes API instead. Happy to discuss alternative paths, but I can't think of one that doesn't involve writing a bespoke containerd package.

**Comment by mogren** [comment]
Merged in v1.6, release candidate published.

**Comment by mogren** [comment]
It does now! CRI-O as well. That said, we will require containerd to use the CRI plugin in order to get the Sandbox ID.
