### ISSUE TITLE
Why's IP assigned to ClusterIP service is not accessible from outside?

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#369]
I created two k8s clusters within the same AWS VPC.
I can access the nginx pod in another k8s cluster but can't access that same nginx pod using a clusterip svc.

**Comment by bjethwan** [comment]
I created two k8s clusters within the same AWS VPC.
I can access the nginx pod in another k8s cluster but can't access that same nginx pod using a clusterip svc.

**Comment by sethp-nr** [comment]
Cluster IPs don't go through the CNI. AFAICT amazon-vpc-cni-k8s makes no attempt at taking ClusterIPs away from the default `kube-proxy` implementation.

**Comment by bjethwan** [comment]
Hi @sethp-nr 
Thanks for your reply. BTW, I have started liking it and I would probably going live in production with this plugin. 

Would you know any nice way/trick to replicate the dns entries from one k8s cluter to another?

-Thanks

**Comment by sethp-nr** [comment]
I'm glad you like it, though I can't take credit for any of it :)

As for DNS, we've haven't gotten too deep into it, but we've had some luck so far with: https://github.com/kubernetes-incubator/external-dns

**Comment by nickdgriffin** [comment]
You could use a service of type "LoadBalancer", which will create an ELB.

**Comment by thpham** [comment]
Hello,

just to follow up on this question, I read the following blog post: [kubernetes-service-ip-route-advertisement](https://www.projectcalico.org/kubernetes-service-ip-route-advertisement). I didn't try.

But I would love to have a feedback from an AWS network expert, if we could upgrade the calico [DeamonSet version](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/calico.yaml#L40) to enable this feature without having to use an "Internal ELB".

Or is there network restriction with AWS VPC network that block BGP advertisement ?

thank you

**Comment by bjethwan** [comment]
> I'm glad you like it, though I can't take credit for any of it :)
> 
> As for DNS, we've haven't gotten too deep into it, but we've had some luck so far with: https://github.com/kubernetes-incubator/external-dns

I used CoreDNS Kubernetai plugin instead. It's working good. Specially for my use case of running statefulsets.
