### ISSUE TITLE
Update error handling for CNI Delete request

### ISSUE THREAD

**Issue by SaranBalaji90** [aws/amazon-vpc-cni-k8s#37]
As per this document https://github.com/containernetworking/cni/blob/master/SPEC.md "Plugins should generally complete a DEL action without error even if some resources are missing.". CNI plugin should avoid throwing errors like https://github.com/aws/amazon-vpc-cni-k8s/blob/master/plugins/routed-eni/cni.go#L234 and continue with deletion

**Comment by mogren** [comment]
Fix done long ago.
