### ISSUE TITLE
aws-cni-support.sh doesn't finish if errors, and can include tarball in itself

### ISSUE THREAD

**Issue by rdonkin** [aws/amazon-vpc-cni-k8s#375]
At least on 1.2.1, there is a curl error, and due to `set -e` the script exits at that point, so no tar.gz file is generated.  The error is from a curl line that has been removed in recent versions:
```
curl: (7) Failed to connect to localhost port 10255: Connection refused
```
While `set -e` is generally a good idea,  it might be good to relax this so that most logs are included even if there's another unexpected error.

It would also be good to make the last line exclude the tarball from being included inside itself - if this is not the first run of the script, that can happen.  Adding `--exclude` as follows fixes this issue - last line reading like this worked OK:

```
tar --exclude '*.tar.gz' -cvzf $LOG_DIR/aws-cni-support.tar.gz ${LOG_DIR}/
```

**Comment by mogren** [comment]
The script was updated in #320 and #384. Thanks for filing the issue!
