### ISSUE TITLE
Documentation correction for AWS_VPC_K8S_CNI_RANDOMIZESNAT

### ISSUE THREAD

**Issue by hgokavarapuz** [aws/amazon-vpc-cni-k8s#380]
Documentation seems to be wrong for AWS_VPC_K8S_CNI_RANDOMIZESNAT which states use it when AWS_VPC_K8S_CNI_EXTERNALSNAT=true is set. But setting the value to true means `The SNAT iptables rule and off-VPC IP rule are not applied, and these rules are removed if they have already been applied.` AWS_VPC_K8S_CNI_RANDOMIZESNAT should be used only when the AWS_VPC_K8S_CNI_EXTERNALSNAT=false. Here is the code link

https://github.com/taylorb-syd/amazon-vpc-cni-k8s/blob/e59edf200179e82d6cd141d8e394f4d4b7978bb4/pkg/networkutils/network.go#L338

**Comment by InAnimaTe** [comment]
Agreed, definitely contradicts itself as if SNAT isn't enabled, there's no reason to tune the options passed to it.
