### ISSUE TITLE
Do you have a logo icon for this AWS CNI plugin?

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#381]
Do you have a logo icon for this AWS CNI plugin?

I can see some diagrams showing black color circle with work CNI.
Would you mind putting the relevant one on the README?

**Comment by jaypipes** [comment]
@tabern We think this would be cool to have, but obviously AWS has guidelines and constraints on logos. Can you find someone that would be appropriate to whip up something for the AWS VPC CNI plugin? Thanks!

**Comment by tabern** [comment]
I know a few people.... Will look into this.

**Comment by mogren** [comment]
Heh, I made an SVG based on the VPC logo from https://aws.amazon.com/architecture/icons/, does that work?

<img width="150" alt="aws-vpc-cni-logo" src="https://user-images.githubusercontent.com/50456/83688420-3a52a080-a5a2-11ea-8ebd-da3813717d37.png">
