### ISSUE TITLE
Am I correct to assume that if we fall short of IPs in a VPC we can add more CIDRs to it?

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#386]
Am I correct to assume that if we fall short of IPs in a VPC we can add more CIRDs to it?

**Comment by jaypipes** [comment]
@bjethwan sorry for the long delay in responding on this. Basically, while it is of course possible to add additional subnets (and corresponding CIDRs) to a VPC that is used for k8s worker nodes (in EKS or EC2), there is not any functionality that automatically lets the CNI plugin know that those additional subnets are available to use for pod IPs.
