### ISSUE TITLE
Replacing flannel with this amazon-vpc-cni-k8s doesnt work in run time

### ISSUE THREAD

**Issue by ibnsinha** [aws/amazon-vpc-cni-k8s#388]
Replacing flannel with this amazon-vpc-cni-k8s doesnt work in run time. Below are the logs/errors:

Bipin Jethwani <jethwani.bipin@gmail.com> | Bipin Jethwani <jethwani.bipin@gmail.com> | 8:34 PM (18 minutes ago) |   |  
-- | -- | -- | -- | --
Bipin Jethwani <jethwani.bipin@gmail.com>
to me | to me
to me

$ kubectl -n kube-system logs aws-node-vdtzt
=====Starting installing AWS-CNI =========
=====Starting amazon-k8s-agent ===========

**Comment by mogren** [comment]
Hi @ibnsinha, are you sure these are the right logs?

**Comment by ibnsinha** [comment]
Hi @mogren yes that's the right logs. I don't see any more logs other than that

**Comment by bjethwan** [comment]
It's working.
I might have made some mistake in IAM policy edits.

@mogren 
It's true that logs are blank when IAM policy is not set correctly.
And docs talk about --node-ip but in my k8s cluster created using kops, it was missing.
Would it have some bad impacts later on???
We are sure going to have VPC peering in production.

Here are some of my logs as I was trying it again today, it proves that logs are blank when IAM policy is not set correctly, I had missed to set it right for he role applied to master node(s). It worked perfectly fine when I fixed the IAM policy on the masters.

$ ps -ef | grep kubelet
/opt/kubernetes/bin/kubelet 
--network-plugin=cni 
--cni-bin-dir=/opt/cni/bin/ 
--cni-conf-dir=/etc/cni/net.d/
Note: --node-ip was not there in cofig params for kubelet

[ec2-user@ip-10-0-1-147 ~]$ ks get pods
NAME                                                                READY   STATUS    RESTARTS   AGE
aws-node-kkqc4                                                      1/1     Running   0          28s
aws-node-xgvl2                                                      0/1     Error     0          28s
coredns-6d999b89cd-2gs6j                                            1/1     Running   1          51m
coredns-6d999b89cd-t46kk                                            1/1     Running   1          51m
dns-controller-9555bc67d-2sbv5                                      1/1     Running   1          51m
etcd-server-events-ip-10-0-1-197.ap-south-1.compute.internal        1/1     Running   1          51m
etcd-server-ip-10-0-1-197.ap-south-1.compute.internal               1/1     Running   1          50m
kube-apiserver-ip-10-0-1-197.ap-south-1.compute.internal            1/1     Running   2          51m
kube-controller-manager-ip-10-0-1-197.ap-south-1.compute.internal   1/1     Running   1          51m
kube-flannel-ds-bldx2                                               1/1     Running   1          50m
kube-flannel-ds-mm7vf                                               1/1     Running   1          51m
kube-proxy-ip-10-0-1-197.ap-south-1.compute.internal                1/1     Running   1          50m
kube-proxy-ip-10-0-1-233.ap-south-1.compute.internal                1/1     Running   1          49m
kube-scheduler-ip-10-0-1-197.ap-south-1.compute.internal            1/1     Running   1          51m
[ec2-user@ip-10-0-1-147 ~]$

$ ks logs aws-node-xgvl2
=====Starting installing AWS-CNI =========
=====Starting amazon-k8s-agent ===========

**Comment by bjethwan** [comment]
@mogren @ibnsinha 

Hi Claes,

I have an issue:
As you can see in my previous post, the kube-flannel pods continue to run when I deployed amazon-vpc-cni-k8s plugin in that k8s cluster. And we realized that it's costly mistake when we ran into an issue using CoreDNS/Kubernetai plugin https://github.com/coredns/kubernetai/issues/25

Is this expected that we need to manually remove the kube-flannel and then restart all the system pods so that they can get the VPC IP addresses? This seems non-trivial as we will have to delete and re-create other daemonsets and scale the deployments down to 0 and back to normal.
Is there a better way to handle this (I mean until kubespray release a formal support for amazon-vpc-cni-k8s plugin https://github.com/kubernetes-sigs/kubespray/issues/4482)?

-Thanks
