### ISSUE TITLE
IPAMD can lose track of enis during upgrades

### ISSUE THREAD

**Issue by nckturner** [aws/amazon-vpc-cni-k8s#401]
When IPAMD is restarted, it can leak ENIs when the ENI is detached (shown as available in the console) and not yet deleted.  

What it looks like in the console: 
![Screen Shot 2019-04-17 at 2 54 41 PM](https://user-images.githubusercontent.com/1205393/56323468-d3192900-6120-11e9-9ae4-72e5b9bfd397.png)

**Comment by mogren** [comment]
Fixed for updates via #645
