### ISSUE TITLE
Env vars, configuration should be initialized once

### ISSUE THREAD

**Issue by nckturner** [aws/amazon-vpc-cni-k8s#419]
There is logic in ipamd that looks up environment variables in various places.  (E.g. https://github.com/aws/amazon-vpc-cni-k8s/blob/master/ipamd/ipamd.go#L640) This should all be done during initialization, and stored in `IPAMContext` for referencing later.

**Comment by Zyqsempai** [comment]
Looks interesting to me, i can take care of it.

**Comment by mogren** [comment]
Fixed by @Zyqsempai
