### ISSUE TITLE
Allow ENIs to be allocated at a faster rate than 1 per 15 seconds

### ISSUE THREAD

**Issue by nckturner** [aws/amazon-vpc-cni-k8s#420]
Currently, the fastest IPAMD is willing to allocate ENIs is 1/15 seconds (5 seconds per loop + 10 seconds per ENI sleep time), but this can increase up to a max of 55 seconds if the ENI takes longer to attach.  This could be improved.

**Comment by jaypipes** [comment]
As mentioned on #405, the 2.0 CNI plugin design will alleviate this issue. See https://github.com/aws/containers-roadmap/issues/398 for more details. Closing this issue for the 1.x CNI series.
