### ISSUE TITLE
Missing amazon-k8s-cni:v1.3.3 image for AWS region eu-central-1

### ISSUE THREAD

**Issue by sandritter** [aws/amazon-vpc-cni-k8s#423]
Hello, 

I am trying to update the CNI version in my EKS cluster to v1.3.3 due to Kubernetes version update to 1.12.6. Because of a permission boundary of my iam role I am only allowed to access the image when it's located in eu-central-1 or eu-west-1. 
Will the image be available in those regions too soon?

This is the error message I get when the aws-node pod is trying to be created:
`Warning  Failed     17s (x2 over 30s)  kubelet, xxx.eu-central-1.compute.internal  Failed to pull image "602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.3.3": rpc error: code = Unknown desc = Error response from daemon: manifest for 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.3.3 not found`

Would be nice to get feedback, thanks :)

**Comment by mogren** [comment]
Hi,

The only difference between v1.3.2 and v1.3.3 is the addition of the a1 and c5n instance families, so unless you need those, you can stay on v1.3.2, or go with v1.4.0. It was a miss in the release process that the v1.3.3 image was never copied to all regions. I'm working on improving that process.

That said, I'll probably do a v1.4.1 soon with a few minor fixes for Calico, fixing the metrics helper (Still in PR #409) and some more tweaks.

**Comment by mogren** [comment]
@sandritter I did a v1.3.4 today, and it should be available in all regions. Aiming to do a v1.4.1 before the end of the week.
