### ISSUE TITLE
Use -w in support script

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#426]
In the support script, we should wait for the xlock to be released.

**Comment by Zyqsempai** [comment]
Sorry, i am new here, and I am looking for first issue;)
Can you provide little bit more info, do you mean this [script](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/aws-cni-support.sh) ?

**Comment by mogren** [comment]
@Zyqsempai Yes, exactly. The lines with `iptables` should have the `-w` option enabled.
