### ISSUE TITLE
don't pass iam role to pod

### ISSUE THREAD

**Issue by itajaja** [aws/amazon-vpc-cni-k8s#430]
right now, the IAM role of the node is passed to every pod. Iam currently trying to sandbox pods to run without AWS permissions, what is a safe approach for preventing specific pods to access AWS resources using the node's IAM?

**Comment by BrianChristie** [comment]
There is a great IAM roles for pods design outlined by AWS at: https://github.com/aws/containers-roadmap/issues/23

Until that is ready (probably a long time), you can consider using something like https://github.com/uswitch/kiam which runs a proxy intercepting IAM requests.

**Comment by itajaja** [comment]
thanks for the resources. actually the link to kiam helped me really understand how the IAM is provisioned to the container. And since I am using calico as network overlay, I simply disallowed access to any link local IPs, and that did the trick. Thanks!
