### ISSUE TITLE
Add documentation and readme for cni-metrics-helper

### ISSUE THREAD

**Issue by tiffanyfay** [aws/amazon-vpc-cni-k8s#448]
- [x] AWS docs
- [x] readme

**Comment by bjethwan** [comment]
cni-metrics-helper doesn't seem to be working. 
I tried this again on stock k8s version 1.11.9.
I didn't see any of the said metrics in either the pod logs or the CloudWatch (maxIPAddress, totalIPAddresses, assignIPAddresses)
Do I need some additional permissions in IAM policy for getting the metrics populated in CloudWatch?

**Comment by tiffanyfay** [comment]
@bjethwan Yes, it needs the two listed here in the release notes: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.4.1

**Comment by rverma-nikiai** [comment]
Is it possible to use prometheus/grafana for cni metrics collection/dashboard? Do we have any instructions for this?

**Comment by mogren** [comment]
@rverma-nikiai Yes, the prometheus metrics endpoint is on by default for the CNI plugin, listening on port `:61678/metrics`. It can be disabled by setting `DISABLE_METRICS` to `true`.

I agree that we need better documentation around this..

**Comment by bjethwan** [comment]
@mogren 
Can you suggest a prometheus scrape config for collecting these metrics?
I can see that cni-metrics-helper is not exposing those as a service within k8s cluster, so it should be via the worker node? How do we make prometheus pick those (expanding) k8s worker nodes?

**Comment by bjethwan** [comment]
@mogren 
What's the difference between maxIPAddresses and totalIPAddresses?

**Comment by bjethwan** [comment]
Is awsAPILatency in milliseconds?

**Comment by mogren** [comment]
@bjethwan The prometheus output should show the help text, but from the code:
```
Name: "awscni_ip_max",
Help: "The maximum number of IP addresses that can be allocated to the instance",

Name: "awscni_total_ip_addresses",
Help: "The total number of IP addresses",

Name: "awscni_assigned_ip_addresses",
Help: "The number of IP addresses assigned to pods",

Name: "awscni_aws_api_latency_ms",
Help: "AWS API call latency in ms",
```

Max is the how many IPs can be attached to that instance type, total is how many it has attached right now, and assigned are the number of attached IPs that are assigned to pods right now.

All latencies are in ms.

**Comment by mogren** [comment]
Eric fixed this.
