### ISSUE TITLE
CNI plugin chaining supported ???

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#462]
Is it possible to chain amazon-vpc-cni-k8s with other plugins like calico, flannel, Cilium?

With plugin chaining would it be possible to have VPC/Subnet IPs only to specific user workload?? Or is there some other way to skip master pods and other monitoring and control pods not assigned the VPC/Subnet IPs?

**Comment by sethp-nr** [comment]
There's already been a little bit of discussion on this question over at #353. It sounds like a good idea, but I don't think it's been scoped out yet.

I'm not sure that plugin chaining solves your second problem. The closest work I'm aware of for having multiple/distinct CNI providers for different pods is [Multus](https://github.com/intel/multus-cni), but I don't think that's designed for switching out CNIs on a per-workload basis.

**Comment by bjethwan** [comment]
@sethp-nr sethp-nr
Thanks for the info !
I will sure explore Multus.

**Comment by mogren** [comment]
Yes, you can run Calico with the CNI, but like @sethp-nr said, we haven't split out the ipamd part yet.
