### ISSUE TITLE
Capability to create constraints on bandwidth for each pod 

### ISSUE THREAD

**Issue by charan-amzn** [aws/amazon-vpc-cni-k8s#463]
Hi,

In use-case such as blockchain workloads where there are multiple pods in 100s of nodes, it will be good to have capability to create constraints on the bandwidth for each pod, that is, say this pod's maximum bandwidth is 1mbit/s, that one is 100mbit/s etc. 

As I understand we can do this within CNI [Alpha feature] - https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ 

In EKS, when we get to 1.14 version, can we have this capability implemented for our CNI ?

**Comment by ksemaev** [comment]
Guys, we need that implementation also, as large traffic spikes for one pod cause outage for the whole cluster, which is really not prod-ready solution

**Comment by jweite** [comment]
+1.  Creating a platform for running end-user submitted code on EKS and need to minimize the impact a badly behaved submission can have on its peers.  Ability to incorporate the [Bandwidth plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping) would be key.

**Comment by cs50student2** [comment]
We use K8s as PaaS to provide CS students with a cloud-based IDE where each student's IDE is backed by a single-container pod and it would be really useful to be able to limit each IDE's bandwidth per https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping.

**Comment by kzidane** [comment]
We use K8s as PaaS to provide CS students with a cloud-based IDE where each student's IDE is backed by a single-container pod and it would be really useful to be able to limit each IDE's bandwidth per https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping.

**Comment by jansony1** [comment]
+1

**Comment by mogren** [comment]
I opened #1029 that adds some foundations for this. Still some usability issues before we can close this issue though, even after that PR gets merged.

**Comment by willejs** [comment]
It would be useful to be able to customize the content of 10-aws.conflist in general to specify other plugins such as the tuning plugin. I think this issue could/should cover that too?

**Comment by mogren** [comment]
Completing this is currently blocked on containerd/cri#1544

**Comment by jayanthvn** [comment]
Bandwidth plugin support is merged to master. Regarding customizing the content of 10-aws.conflist we will look into.
