### ISSUE TITLE
vendor directory is out of date

### ISSUE THREAD

**Issue by bboreham** [aws/amazon-vpc-cni-k8s#466]
For instance the code has a dependency on `github.com/deckarep/golang-set`, but this is not in the `vendor` directory.

Maybe the intention is that everyone should download dependencies via `go mod` and the `vendor` directory should be deleted from the repo?

**Comment by mogren** [comment]
That dependency will be added by #461 once it has been merged, but I think you are right, we should probably rely on `go mod` for this.

**Comment by mogren** [comment]
Updated the vendor folder. That said, building in docker uses `go mod`, I'll update the Readme for #465.
