### ISSUE TITLE
Support Internet to Pod access directly

### ISSUE THREAD

**Issue by thinalai** [aws/amazon-vpc-cni-k8s#468]
Use case:
Pod accessed by external IP(Pod exposed to Internet).

AFAIK:
[ENI can have a public IP](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html), if we have one pod per ENI, should Internet access the pod directly?

**Comment by mogren** [comment]
Hi @thinalai, if the VPC CIDR range is publicly routable, I guess it would be possible. It's common to set up an NLB in front of the pods though.

Also, some interesting discussion here https://github.com/weaveworks/eksctl/issues/440

**Comment by jaypipes** [comment]
The appropriate way to route Internet traffic to Kubernetes pods is to use a Kubernetes Service of type LoadBalancer, which will create an NLB or ALB with backend endpoints in the Pod's private IP addresses.
