### ISSUE TITLE
Update CNI and CNI Plugin to v0.4.0 spec

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#479]
The CNI plugins [v0.8.5](https://github.com/containernetworking/plugins/releases/tag/v0.8.5) and CNI [v0.7.1](https://github.com/containernetworking/cni/releases/tag/v0.7.1) has been released, using the [v0.4.0 spec](https://github.com/containernetworking/cni/blob/spec-v0.4.0/SPEC.md). We should update our dependencies.

**Comment by mogren** [comment]
Started to [implement this](https://github.com/mogren/amazon-vpc-cni-k8s/tree/spec-0.4.0), but the change is a bit too big for v1.6. Pushing to next in order to not delay the v1.6 release.

**Comment by cgchinmay** [comment]
We will be releasing with cni spec 0.4.0 in v1.10.2 which is scheduled for 7th feb

**Comment by jayanthvn** [comment]
Update of spec is done. We will look into adding check command if needed later. Closing the issue for now.
