### ISSUE TITLE
config/v1.4/calico.yaml not compatible with Kubernetes 1.10

### ISSUE THREAD

**Issue by edmorley** [aws/amazon-vpc-cni-k8s#494]
Hi

Applying [config/v1.4/calico.yaml](https://github.com/aws/amazon-vpc-cni-k8s/blob/4a78643f13c4454771a403781140293ff1fd6a07/config/v1.4/calico.yaml) against a Kubernetes 1.10 cluster currently results in several errors of form:

```
$ kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/4a78643f13c4454771a403781140293ff1fd6a07/config/v1.4/calico.yaml
...
Error from server (Invalid): error when applying patch:
...
CustomResourceDefinition.apiextensions.k8s.io "hostendpoints.crd.projectcalico.org" is invalid: [spec.version: Required value, spec.version: Invalid value: "": field is immutable]
```

This appears to be due to the switch from `version` to `versions` that was made here:
https://github.com/aws/amazon-vpc-cni-k8s/commit/ee13f3ef2b157e60bc01ab4692b76a22048022e7#diff-a3503151a8bea5d2c2b4c1940cc15d6fL180

Adjusting the manifest to use `version` again resolved the errors.

Would it be possible to add a Kubernetes 1.10 compatible manifest (eg `calico-1.10.yaml`) for parity with the 1.10-compatible CNI plugin manifest (`aws-k8s-cni-1.10.yaml`), or alternatively document in the README what the recommended older versions are for Kubernetes 1.10? (Whilst 1.10 is very old, it's helpful to be able to know what interim version combinations work, otherwise it ends up being a chicken and egg situation of what to upgrade first, when trying to modernise a legacy cluster.)

Many thanks :-)

**Comment by mogren** [comment]
Hi @edmorley,

Yes, that would probably be a good idea. That said, [1.10 EKS clusters will be deprecated July 22](https://aws.amazon.com/blogs/compute/updates-to-amazon-eks-version-lifecycle/).
