### ISSUE TITLE
Compare to p2p CNI plugin?

### ISSUE THREAD

**Issue by thockin** [aws/amazon-vpc-cni-k8s#5]
This seems pretty much identical to the point-to-point CNI driver.   https://github.com/containernetworking/plugins/tree/master/plugins/main/ptp

Can someone explain how it is different?

**Comment by liwenwu-amazon** [comment]
Here are few differences:
- on host side, it uses policy routing to route pod's outgoing traffic. For example, if pod-1 gets an IP address from Elastic Network Interface 2,  pod-1 outgoing traffic will get routed out through Elastic  Network Interface 2.
- on NS side, the plugin plumbs an static ARP entry to avoid unnecessary ARPing
- the repo also includes L-IPAM, which is a long running node-Local IP Address Management (IPAM) daemon. L-IPAM manages a warm-pool of VPC IP addresses and Pod IP address assignment. The details can be found in https://github.com/aws/amazon-vpc-cni-k8s/blob/master/proposals/cni-proposal.md
- lastly, this cni plugin communicates with L-IPAM through gRPC for Pod IP address assignment

**Comment by thockin** [comment]
Thanks!

Is the ENI assignment because that is how things like Security Groups are
managed (via ENIs) ?  Or is there some other reason to have multiple ENIs?

I'm surprised there's an ARP involved with sufficient static routes.  Will
have to check that.

Why is L-IPAM not a normal CNI IPAM driver?

**Comment by liwenwu-amazon** [comment]
Yes, user can associate security groups and subnet to an ENI  and use them to enforce security polices and routing polices. The main purpose of  current release is to increase number of VPC IP addresses which can be assigned to Pods running on the instance. Please see [IP Address Per Network Interface Per Instance Type](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI).

L-IPAM, which is a long-running daemon, is responsible for allocating ENIs and ENI's secondary IPv4 addresses and maintaining a warm-pool of these IPv4 addresses.

**Comment by liwenwu-amazon** [comment]
Closing it for now. If you think this is still an issue, please re-open it.
