### ISSUE TITLE
Missing amazon-k8s-cni:v1.5.0 image for AWS region eu-west-1

### ISSUE THREAD

**Issue by astrikos** [aws/amazon-vpc-cni-k8s#505]
We are trying to update our CNI plugin from `1.3.0` to `1.5.0` in our kubernetes cluster (not EKS). Unfortunately we get errors for missing images like:
```
pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.5.0"
Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:1.5.0": rpc error: code = Unknown desc = Error: image amazon-k8s-cni:1.5.0 not found
```

We also tried `1.4.1` but we get the same error, the latest available for `eu-west-1` seems to be `1.4.0`.
Is it something you need to enable? Is there any plan/schedule that you make each verison available to all regions?

**Comment by mogren** [comment]
Hi @astrikos,

I think you are missing a `v` for the version. we did accidently push the `1.3.0` version without the correct semantic versioning name, but did not continue to do that. Could you please try with this instead:
```
602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.5.0
```

**Comment by astrikos** [comment]
🤦‍♂ you are right! It works like a charm if I use `v` a prefix. I should have pay more attention to example configs (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/aws-k8s-cni.yaml#L84)

Thanks for the fast response. No further action required, closing this one!
