### ISSUE TITLE
Support increased ENI limits when awsvpcTrunking is enabled for the account

### ISSUE THREAD

**Issue by cpoole** [aws/amazon-vpc-cni-k8s#506]
like the title says:
This exists for ECS and can be used to have higher density while maintaining SG per pod and IAM role per pod.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

This would be great to have in eks as well.

**Comment by mogren** [comment]
Hi @cpoole,

I totally agree, and we are currently working on this. The task is tracked in https://github.com/aws/containers-roadmap/issues/138
