### ISSUE TITLE
Use a structured logging library

### ISSUE THREAD

**Issue by chiefy** [aws/amazon-vpc-cni-k8s#511]
Feature request: use json logging, or something standard (syslog) because trying to get a logging shipper to parse multiline is a pita. Thanks!

For anyone using fluent-bit, I had to use `tail` input and this as a Multiline_Parser

```
    [PARSER]
        Name        aws-cni
        Format      regex
        Regex       ^(?<time>[^\[]+)\s*\[(?<level>[A-Z]*)\]\s(?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%SZ
```

**Comment by max-rocket-internet** [comment]
> because trying to get a logging shipper to parse multiline is a pita

Or just don't log multi-line messages?

**Comment by jaypipes** [comment]
We should standardize on either klog or logrus.

**Comment by mogren** [comment]
Change merged, following upstream precedence:

https://godoc.org/sigs.k8s.io/controller-runtime/pkg/log/zap
