### ISSUE TITLE
Unable to get AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG working as per the docs

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#514]
k8s version: 1.12.8 (using kops)

amazon-vpc-cni-k8s upgraded to 1.15.0
![image](https://user-images.githubusercontent.com/5045325/60085193-7a848e80-9756-11e9-8feb-4a60c236bde1.png)

VPC
primary cidr: 10.0.0.0/16
secondary cidrs: 10.1.0.0/16

k8s running in secondary cidr.

Below subnets are used for k8s worker nodes
subnet1: 10.1.1.0/24 (ap-south-1a)
subnet2: 10.1.2.0/24 (ap-south-1b)

Below subnets are for k8s pods
subnet3: 10.1.3.0/24 (ap-south-1a)
subnet4: 10.1.4.0/24 (ap-south-1b)

I used the subnet3 and subnet4 to create eniconfig-1a and eniconfig-1b respectively.

k get eniconfigs
NAME           AGE
eniconfig-1a   7m
eniconfig-1b   7m

 k get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
ip-10-1-1-168.ap-south-1.compute.internal   Ready    master   4h2m   v1.12.8
ip-10-1-1-34.ap-south-1.compute.internal    Ready    node     4h1m   v1.12.8
ip-10-1-2-14.ap-south-1.compute.internal    Ready    node     4h1m   v1.12.8

k label node ip-10-1-1-34.ap-south-1.compute.internal k8s.amazonaws.com/eniConfig=eniconfig-1a
k label node ip-10-1-2-14.ap-south-1.compute.internal k8s.amazonaws.com/eniConfig=eniconfig-1b

k create ns nginx
k -n nginx create deploy nginxd --image=nginx
k -n nginx scale deploy nginxd --replicas=30

ISSUE : All the pods came in subnet1 and subnet2 and not in subnet3 and subnet4.
The pod IPs are from 10.1.1.x and 10.1.2.x and not in  10.1.3.x and 10.1.4.x

k -n nginx get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP           NODE                                       NOMINATED NODE
nginxd-7cf9bdd64b-5kxhz   1/1     Running   0          12m   10.1.2.229   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-74x4k   1/1     Running   0          12m   10.1.2.250   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-7vgvk   1/1     Running   0          12m   10.1.1.71    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-852lc   1/1     Running   0          12m   10.1.2.118   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-8d97g   1/1     Running   0          12m   10.1.1.136   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-8ls8h   1/1     Running   0          12m   10.1.1.197   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-9477b   1/1     Running   0          12m   10.1.2.49    ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-9xzrk   1/1     Running   0          12m   10.1.2.151   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-bcwcz   1/1     Running   0          12m   10.1.2.171   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-brcq7   1/1     Running   0          12m   10.1.2.93    ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-dvrbw   1/1     Running   0          12m   10.1.1.114   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-fbslm   1/1     Running   0          12m   10.1.2.24    ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-fpzr2   1/1     Running   0          12m   10.1.2.149   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-fs4dw   1/1     Running   0          12m   10.1.1.181   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-g6bsx   1/1     Running   0          12m   10.1.2.72    ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-g8jxr   1/1     Running   0          12m   10.1.2.103   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-gmqp4   1/1     Running   0          12m   10.1.1.68    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-j5d7r   1/1     Running   0          12m   10.1.1.151   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-jmrn9   1/1     Running   0          12m   10.1.1.44    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-nlkjr   1/1     Running   0          12m   10.1.2.35    ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-pnkrb   1/1     Running   0          12m   10.1.1.214   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-q8t4f   1/1     Running   0          12m   10.1.2.109   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-qf25r   1/1     Running   0          12m   10.1.1.224   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-sb2hz   1/1     Running   0          12m   10.1.1.99    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-v7pwt   1/1     Running   0          12m   10.1.1.79    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-w95zp   1/1     Running   0          12m   10.1.1.235   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-xc2p4   1/1     Running   0          12m   10.1.1.104   ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-z2dl2   1/1     Running   0          12m   10.1.2.243   ip-10-1-2-14.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-zpnx7   1/1     Running   0          12m   10.1.1.27    ip-10-1-1-34.ap-south-1.compute.internal   <none>
nginxd-7cf9bdd64b-zx76s   1/1     Running   0          12m   10.1.2.47    ip-10-1-2-14.ap-south-1.compute.internal   <none>

**Comment by mogren** [comment]
The worker nodes should all use the primary CIDR since the first IP on eth0 is the cross account ENI the masters use to talk to the kubelet, `10.0.0.0/16` in your case. The pods will get IPs from `10.1.0.0/16`. For a detailed overview, take a look at the slides from [last year's re:Invent](https://github.com/liwenwu-amazon/reinvent2018-NET410/tree/master/eks-cni-demo#aws-vpc-routed-cni-and-amazon-eks-cluster-networking).

**Comment by adammw** [comment]
Can you show the ENI Config in use? Also were the pods created before or after they were labeled?

We have been using a custom ENI Config in production for some time, however it is good to note that while the plugin will use the new configuration for new ENIs, existing attached ENIs continue to use the previous configuration. Therefore if pods are already attached to the primary interface because the host was not labelled with a specific netconfig, then they won't magically change their IP when the label changes, and only new pods will be affected (and potentially only after the ENI is full - i haven't tested the exact behaviour here).

**Comment by bjethwan** [comment]
@mogren Hi Claes, Thank you!

@adammw thanks for the help, you can see the eniconfigs below
one carrying subnet in ap-south-1a and another carrying subnet in ap-south-1b
These subnets are not used anywhere else.
 
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eniconfig-1a
spec:
  securityGroups:
    - sg-0XYZ
  subnet: subnet-0ABC


apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eniconfig-1b
spec:
  securityGroups:
    - sg-0XYZ
  subnet: subnet-0DEF

**Comment by bjethwan** [comment]
@mogren @adammw 
It worked !!!

The only change I did was to label the nodes before applying the eniconfigs

![image](https://user-images.githubusercontent.com/5045325/60250095-a1240000-98e3-11e9-8756-d47512d02dd7.png)

**Comment by mogren** [comment]
Glad to hear that @bjethwan, nice work! 🙂
