### ISSUE TITLE
can't set AWS_VPC_K8S_CNI_EXTERNALSNAT to true

### ISSUE THREAD

**Issue by Claywd** [aws/amazon-vpc-cni-k8s#534]
My nodes are in a private subnet, nat in public, multiple CIDRS on the vpc..... all that. Pretty sure all I should need to do is set AWS_VPC_K8S_CNI_EXTERNALSNAT to true as outlined here https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html

So I follow the commands... EXACTLY. 

```kubectl edit daemonset -n kube-system aws-node```

edit and change (using vim by default)

```...
    spec:
      containers:
      - env:
        **- name: AWS_VPC_K8S_CNI_EXTERNALSNAT
          value: "true"**
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: MY_NODE_NAME
...
```

but I get this garbage in response. 

```error: daemonsets.extensions "aws-node" is invalid
A copy of your changes has been stored to "/var/folders/gc/4ys51vtx0vb0vln8k0vs4bg9xhlv4m/T/kubectl-edit-gau99.json"
error: Edit cancelled, no valid changes were saved.
```

I tried editing it in json format, removing the '"' around "true". nothing worked. So I checked for the exact error and found the following

```# daemonsets.extensions "aws-node" was not valid:
# * : Invalid value: "The edited file failed validation": [yaml: line 46: found character that cannot start any token, invalid character 'a' looking for beginning of value]
```

don't see any random 'a's floating in the document so ultimately I just copied the damn thing to a yaml file, edited it and deployed the ds again. Now its working but this isn't expected behavior I'm sure.

**Comment by mogren** [comment]
Hi @Claywd,
I have accidently indented the lines wrong sometimes when using vim because of settings I have, but adding that environment variable should work. You could try just setting the variable using kubectl. First check the current ones:
```
kubectl set env ds aws-node -n kube-system --list
```
To set `AWS_VPC_K8S_CNI_EXTERNALSNAT`:
```
kubectl set env ds aws-node -n kube-system AWS_VPC_K8S_CNI_EXTERNALSNAT=true
```
Then verify that the variable was correctly set:
```
kubectl set env ds aws-node -n kube-system --list
```

**Comment by Claywd** [comment]
@mogren That's a solid option and should be in the docs if it isn't already.
