### ISSUE TITLE
 Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container network for pod : NetworkPlugin cni failed to set up pod network: add cmd: failed to assign an IP address to container Error: context deadline exceeded

### ISSUE THREAD

**Issue by dschaaff** [aws/amazon-vpc-cni-k8s#547]
I'm experiencing frequent issues with the vpc cni failing to assign IPs to pods. In this particular case the instance is an m5a.4xlarge. I have the support files from the instance if needed.

```
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

I see this in the ipamd logs.
```
2019-07-30T15:31:53Z [ERROR]	Failed to increase pool size due to not able to allocate ENI AllocENI: error attaching ENI: attachENI: failed to attach ENI: AttachmentLimitExceeded: Interface count 9 exceeds the limit for m5a.4xlarge
	status code: 400, request id: 0f1dbc3b-cde5-4bd8-832a-72e47c59a362
2019-07-30T15:31:53Z [DEBUG]	Successfully increased IP pool
2019-07-30T15:31:53Z [DEBUG]	IP pool stats: total = 58, used = 58, c.maxIPsPerENI = 29
2019-07-30T15:31:53Z [DEBUG]	IP pool stats: total = 58, used = 58, c.maxIPsPerENI = 29
2019-07-30T15:31:53Z [DEBUG]	Its NOT possible to remove extra ENIs because available (0) <= ENI target (2) * addrsPerENI (29): 
```

ipamd-env.out
```
{"AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG":false,"WARM_ENI_TARGET":2,"WARM_IP_TARGET":0}
```

metrics.out
```
# HELP awscni_add_ip_req_count The number of add IP address request
# TYPE awscni_add_ip_req_count counter
awscni_add_ip_req
# HELP awscni_del_ip_req_count The number of delete IP address request
# TYPE awscni_del_ip_req_count counter
awscni_del_ip_req_count{reason="PodDeleted"} 3.981822e+06
# HELP awscni_eni_allocated The number of ENIs allocated
# TYPE awscni_eni_allocated gauge
awscni_eni_allocated 2
# HELP awscni_eni_max The maximum number of ENIs that can be attached to the instance
# TYPE awscni_eni_max gauge
awscni_eni_max 8
# HELP awscni_ip_max The maximum number of IP addresses that can be allocated to the instance
# TYPE awscni_ip_max gauge
awscni_ip_max 232
# HELP awscni_ipamd_action_inprogress The number of ipamd actions in progress
# TYPE awscni_ipamd_action_inprogress gauge
awscni_ipamd_action_inprogress{fn="increaseIPPool"} 0
awscni_ipamd_action_inprogress{fn="nodeIPPoolReconcile"} 0
awscni_ipamd_action_inprogress{fn="nodeInit"} 0
# HELP awscni_ipamd_error_count The number of errors encountered in ipamd
# TYPE awscni_ipamd_error_count counter
awscni_ipamd_error_count{fn="increaseIPPoolAllocENI"} 139666
awscni_ipamd_error_count{fn="increaseIPPoolwaitENIAttachedFailed"} 6
awscni_ipamd_error_count{fn="waitENIAttachedMaxRetryExceeded"} 6
# HELP awscni_total_ip_addresses The total number of IP addresses
# TYPE awscni_total_ip_addresses gauge
awscni_total_ip_addresses 58_count 1.711633e+06
# HELP awscni_assigned_ip_addresses The number of IP addresses assigned to pods
# TYPE awscni_assigned_ip_addresses gauge
awscni_assigned_ip_addresses 58
# HELP awscni_aws_api_error_count The number of times AWS API returns an error
# TYPE awscni_aws_api_error_count counter
awscni_aws_api_error_count{api="AttachNetworkInterface",error="AttachmentLimitExceeded"} 139666
awscni_aws_api_error_count{api="CreateTags",error="InvalidNetworkInterfaceID.NotFound"} 119
```

It seems that the instance is never going above 58 ips, but still trying to schedule pods. The kubelet max pods is appropriately set to `234`. I can provide additional logs upon request.

Stopping and deleting the aws-node container seems to resolve the issue. After performing that the ipamd logs look as expected.
```
IP pool stats: total = 203, used = 139, c.maxIPsPerENI = 29
```

I appreciate any guidance.

**Comment by oceaneLonneux** [comment]
Currently encountering this problem with an EKS cluster version 1.12, instances are t3.large with 26 pods. I updated the CNI to 1.15, was previously 1.14.

It should be able to go up to 35 but it sent this error: NetworkPlugin cni failed to set up pod.

Will investigate as well, it seems like this issue has been there for some time and I'm not sure about the answer?

**Comment by TechnicalMercenary** [comment]
For me I've only started experiencing this issue when we are trying to move to 1.13.  Exact same Terraform configuration in 1.12 is fine (other than referencing a 1.13 AMI and setting resource EKS to 1.13 ) .  We are scaling r3.2xlarge sized nodes

**Comment by stefansedich** [comment]
Just experienced this on a new node that was autoscaled up and attempting to run a pod, appeared to start up just fine right after. I am assuming something was not initialized on time but will have to dig further.

**Comment by dschaaff** [comment]
I believe #282 may be related. I'm currently building a custom AMI with the kubelet upgraded to 1.13.8 to see if it addresses the issue.

**Comment by i-sam** [comment]
+1 got the same issue with the v1.13.8-eks-a977ba

**Comment by mogren** [comment]
@i-sam Which CNI version?

**Comment by left4taco** [comment]
+1 got the same error. 

Server version: v1.13.8-eks-a977ba

CNI version: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.3

**Comment by pito-svk** [comment]
Same for me. EKS version: v1.14.7-eks-1861c5

**Comment by dschaaff** [comment]
I’m no longer seeing this issue on 1.14.6 and cni version 1.5.3.

**Comment by pito-svk** [comment]
@dschaaff My cni version is: amazon-k8s-cni:v1.5.4

**Comment by karanmagdani1** [comment]
Is there any way to capture `subnet available ips` using cni helper? It would be nice to know if i am running out of ips

**Comment by jaypipes** [comment]
@karanmagdani1 I've put your feature request into a separate issue (#757)

@morganchristiansson @dschaaff it seems like this is no longer occurring on newer CNI plugin releases. Can you confirm? If so, I'm going to close out this issue. Thanks!

**Comment by jaypipes** [comment]
@morganchristiansson @dschaaff can you confirm you are no longer seeing this issue?

**Comment by dschaaff** [comment]
This issue has been completely resolved for me.

**Comment by morganchristiansson** [comment]
@jaypipes My error was from running out of IPs in my private subnets.

A t3.2xlarge instance will use up to 60 IPs. My teams private subnets are /27 per AZ which is quite generous and gives at most 127 IPs per AZ that is also used by other services. So I can only safely run 1 instance per private subnet reliably and am no longer having the problem.

We now have additional private subnets where additional workers can run to work around this.

**Comment by imranismail** [comment]
we're still seeing this issue on 1.5.5

**Comment by imranismail** [comment]
We've resolved this by using a bigger subnet

**Comment by mogren** [comment]
This issue seems to be resolved for the most part. Please open a new issue with details if there are still problems.

**Comment by rjshk013** [comment]
I deleted the cluster and recreated .the problem solved.I have created it using terraform
