### ISSUE TITLE
status: SERVING in logs

### ISSUE THREAD

**Issue by evanshriner** [aws/amazon-vpc-cni-k8s#568]
Hi,

After updating to 1.5 in EKS 1.13 I am continually seeing `status: SERVING` being printed out every 10 seconds from all nodes in the cluster. Everything seems to be healthy, but the log is quite disruptive in regards to monitoring. 

Is there any extra insight into this log / what would be causing it to continuously print? 

Thank you!

**Comment by mogren** [comment]
Hi @evanshriner,

Yes, this comes from the gRPC health check, and I agree that it is way to verbose. The health check was added in 6ba7d76 and the check is in 79fd64a. I'm working on a different way to solve the startup issue that won't pollute the logs.

**Comment by evanshriner** [comment]
@mogren,

Appreciate the quick reply. In the interim a filter will do. Thanks!

**Comment by mogren** [comment]
Just released v1.5.2, it should be a bit less verbose at least.

**Comment by mogren** [comment]
v1.5.3 is out. Should resolve this issue.
