### ISSUE TITLE
Unable upgrade aws cni from 1.3.0 to v1.5.2

### ISSUE THREAD

**Issue by moruikang** [aws/amazon-vpc-cni-k8s#588]
I create kubernetes 1.11.6 cluster in aws with kops, and use aws vpc cni. 
but when  i  upgrading aws vpc cni from 1.3.0 to v1.5.3 or other version
`kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2`
amazon-k8s-cni:1.3.0
`kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml`
After a few seconds it Automatic rollback to 1.3.0
`kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2`
amazon-k8s-cni:1.3.0

how can i upgrade my cni version？

**Comment by mogren** [comment]
Hi @moruikang, I tried starting with a v1.3.4 cluster, and then updating to v1.5.3, and I didn't have any issues. Can you try just updating to v1.3.4?
```
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.3/config/v1.3/aws-k8s-cni.yaml
```
Did you see any errors while updating? If v1.3.4 works, can you try with v1.4? as well?
```
kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.4/config/v1.4/aws-k8s-cni.yaml
```

**Comment by mogren** [comment]
Please reopen if this is still an issue.
