### ISSUE TITLE
Imapct of upgrading CNI from amazon-k8s-cni:v1.3.4 to v1.5.3 on the existing EKS cluster

### ISSUE THREAD

**Issue by rakeysh17** [aws/amazon-vpc-cni-k8s#602]
Hi,

Can someone please put some light on the below concern?

Does upgrading CNI from amazon-k8s-cni: v1.3.4 to v1.5.3 have any impact on existing cluster networking ? 
EKS cluster is running with K8 1.13.

Thanks,
Rakesh

**Comment by mogren** [comment]
Hi @rakeysh17,

Updating the CNI should not have any impact, especially not on any running pods. It might add some increased delays when scheduling pods while the new ipamd starts up and tries to reconcile the existing pods with the ENIs and IPs that are attached to the node, but that's about it.

The biggest change would be if you have `WARM_IP_TARGET` set to something low, with v1.3.4 it won't  do much, but if you update to v1.5.0 or later, we will start freeing unused IPs, so for large clusters or clusters with a lot of pod churn, this setting should not be used.
