### ISSUE TITLE
Simplify upgrades with custom environment

### ISSUE THREAD

**Issue by stevehorsfield** [aws/amazon-vpc-cni-k8s#607]
The aws-node daemonset expects environment variables to configure various options. However, in the current form this makes it difficult to upgrade following the published instructions as the configuration would be lost.

Our approach is to use an external configmap and an envFrom clause but this also requires us to patch the daemonset before upgrading and so we can’t use the instructions as-is. 

As the deployment file combines multiple resources, this makes it needlessly complicated for updating the CNI.

Would it be possible to read in a host-namespace file, or a standard configmap that is only created once and separately. 

Otherwise, every update for most customers runs a risk of error here. I expect most customers, certainly enterprises, will configure at least one option.

Thanks.

**Comment by mogren** [comment]
We would like to standardize best practices for updating the CNI using Helm. The charts are available in the [eks-charts](https://github.com/aws/eks-charts/tree/master/stable/aws-vpc-cni) repository, which includes instructions for upgrading.

**Comment by sagikazarmark** [comment]
As far as I can tell the driver is not installed using Helm at the moment. TBH, I like that it's not. With or without Tiller, installing plain Kubernetes object when minimal or no parameterization is needed sounds a lot better.

I'd like to second this request to add a configmap to the default installation recipe. It can be made optional (ignore if not exist) and has no risk, but the advantage of not having to patch the daemonset.
