### ISSUE TITLE
EKS cannot pull image

### ISSUE THREAD

**Issue by rubroboletus** [aws/amazon-vpc-cni-k8s#613]
We are running EKS and are trying to upgrade from 1.5.1 to 1.5.3. After kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml the aws-node pod is in ImagePullBackOff status.
kubect describe po/aws-node displays this message:
Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.3"
if I try curl, there is message about basic auth credentials.
Our EKS is in VPC, accessing Internet just by HTTP proxy.

**Comment by mogren** [comment]
Hi @rubroboletus, the image is there, so probably there is some permission missing. Does the account you run the worker nodes in have `ecr:GetAuthorizationToken` permissions? More detail here https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth

**Comment by vantagesol** [comment]
Hi there, we also started having issues with EKS being able to pull images from ECR starting from today. Our EKS Nodes have all the correct permissions and policies on their respective roles. Any insights would be great!

**Comment by vipulsabhaya** [comment]
Which region are you seeing this issue?

**Comment by mogren** [comment]
@vantagesol Is this still an issue?

**Comment by max-rocket-internet** [comment]
@mogren 

Wouldn't it make sense to just allow pulling the CNI in every region publicly?

```
$ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.5.3
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.5.3: no basic auth credentials
```

**Comment by max-rocket-internet** [comment]
And the same for AWS `coredns` and `kube-proxy`

**Comment by nckturner** [comment]
@max-rocket-internet what do you mean by pull publicly?  ECR doesn't support uncredentialed access, but the permissions should allow anyone with valid AWS credentials to pull the image in all regions. Is that not the case?

**Comment by max-rocket-internet** [comment]
> ECR doesn't support uncredentialed access, but the permissions should allow anyone with valid AWS credentials to pull the image

Ah sorry, my mistake, I thought this was possible with ECR.

**Comment by rubroboletus** [comment]
currently we are in eu-central-1 region, cannot pull from us-west-2 and when I switch the URL to local zone, I can use regular version image, but cannot use release candidates etc.

**Comment by jaypipes** [comment]
@rubroboletus @vantagesol Hi! Would you mind letting us know if you are still seeing this problem? If not, we'll close the issue out. Thanks!

**Comment by rubroboletus** [comment]
@jaypipes was trying to test amazon-k8s-cni:v1.6.0-rc4 just now, changed the region to eu-central-1 as all our services are in Europe. Logged in to AWS ECR. No change, see attached picture with redacted part of token.
![ecr-image-failure-20191127-1](https://user-images.githubusercontent.com/19551186/69705442-e1d3af80-10f5-11ea-9677-5b8920edfd6a.jpg)

**Comment by jaypipes** [comment]
@mogren are we only publishing RC images to a single region or something like that?

**Comment by mogren** [comment]
Yes, so far we have only published the release candidates in `us-west-2`.

**Comment by jaypipes** [comment]
> Yes, so far we have only published the release candidates in `us-west-2`.

Well, that solves this particular mystery :)

We should document that policy in the README so we can point folks to it.

**Comment by mogren** [comment]
Updated the [v1.6.0-rc5 release notes](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0-rc4) to be more clear that the images are only available in `us-west-2`.

**Comment by tejaswinibussety** [comment]
Hey,
So we ran into similar issue since us-west-2 is disabled using AWS SCP and our nodes were not able to join the cluster. The reason being image pull failed for the code pods which are expected to be running, I see us-west-2 seems to be hardcoded although these images are shared across all regions. Is there a reason as why image from the same region is not used instead of going to us-west-2?

I think this would also mean if us-west-2 is down we will not be able to scale nodes on any other region. 

Any help is appreciated..!

**Comment by noppadol26dw** [comment]
after refer this [document ](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html)
I can solve the issue **ImagePullBackOff** for my coredns issue by adding EC2 instance node role to having the policy "AmazonEC2ContainerRegistryReadOnly"
