### ISSUE TITLE
AWS EBS performance issue

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-vpc-cni-k8s#614]
The aws ebs gp2 based persistent volumes attached to the pods (couchbase in our case) are not performing well. As we were trying to benchmark the performance between "couchbase on k8s/aws" and "couchbase on aws".

And then I ran into this blog:
https://blog.pythian.com/how-to-get-the-most-out-of-your-ebs-performance/
The blog said that I need to have RPS (receive packet steering) enabled for gaining the best ebs network performance while connecting to the underlying k8s node (ec2), I found that it's disabled.

$ uname -r
4.14.96-coreos-r1

$ cat /sys/class/net/eth0/queues/rx-0/rps_cpus
0

$ cat /sys/class/net/eni2c0f977d105/queues/rx-0/rps_cpus
0

**Comment by mogren** [comment]
This is a setting in the AMI, not in the CNI. Are you using the EKS standard image? Then the issue needs to be in https://github.com/awslabs/amazon-eks-ami/
