### ISSUE TITLE
support for traffic mirror sessions

### ISSUE THREAD

**Issue by zenvdeluca** [aws/amazon-vpc-cni-k8s#615]
this is a feature request.   

With AWS Traffic Mirror, the AWS CNI should be capable of creating traffic mirror sessions for it's allocated ENIs.  As ENI dynamically gets attached/detached to a Kubernetes node, mirror sessions should be optionally configured via the plugin

**Comment by jaypipes** [comment]
@zenvdeluca secondary ENIs on Kubernetes worker nodes house IP addresses for Kubernetes Pods. The CNI plugin assigns new Pods an IP address that is associated with one of the ENIs on the worker node, and optionally auto-creates new ENIs on the worker node when there are no more available IP addresses on the ENI. The CNI plugin does not configure ENIs themselves. Rather, it simply keeps track of the IP addresses associated with ENIs. There would be no way that I can tell for the CNI plugin to auto-create traffic mirror targets to the ENIs that it brings up in response to IP address exhaustion events. Instead, to use traffic mirroring with Kubernetes, you'd need to create a new TM target to an already-existing ENI (either primary or secondary) on a worker node.
