### ISSUE TITLE
pod to pod communication issue

### ISSUE THREAD

**Issue by evan-lin** [aws/amazon-vpc-cni-k8s#619]
We are building the K8S with CNI, and we are not using the EKS node AMI, it is build from centOS AMI.
After everything is setup, pod is allocated with the IP associate with the ENI, however, pod is not able to ping another pod.
Take a long time for investigation, and it turns out it is caused by FORWARD policy is DROP by default in iptables, after update it as ACCEPT, everything goes well. In EKS AMI, the policy is update to ACCEPT already.
<img width="742" alt="Screen Shot 2019-09-18 at 12 52 33 PM" src="https://user-images.githubusercontent.com/17717672/65133155-bc129600-da34-11e9-81fb-9abc1719df18.png">

I think everyone try to setup the CNI without EKS AMI may meet the issue, and it is not easy for the trouble shooting, would be helpful if add issues like this to the trouble shooting documents.
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md

**Comment by mogren** [comment]
Related to https://github.com/aws/amazon-vpc-cni-k8s/pull/535 and https://github.com/awslabs/amazon-eks-ami/issues/332

**Comment by jayanthvn** [comment]
Sorry for the delay. Will update the troubleshooting guide.

**Comment by jayanthvn** [comment]
Merged #1565
