### ISSUE TITLE
EC2 instance in the same VPC access K8s Pod

### ISSUE THREAD

**Issue by manlinl** [aws/amazon-vpc-cni-k8s#620]
I have a k8s on AWS (created by kops with --networking amazon-vpc-routed-eni). I have another EC2 instance in the same VPC as the k8s cluster. But my EC2 instance can't access k8s Pod directly. I am under the impression with vpc-cni plugin, traffic from EC2  instance is routable to  Kubernetes Pod. Do I need any special setup?

Many thanks!

**Comment by manlinl** [comment]
It turns out it was the security group setting. But I also learnt for the pod to be accessible from another VPC, one need to disable SNAT https://docs.aws.amazon.com/eks/latest/userguide/external-snat.html

**Comment by mogren** [comment]
Hi @manlinl, thanks for answering your own question! 

For peered VPCs, we added a new environment variable in #520 where you can specify additional CIDRs that should not be SNATed. That feature has not been released yet, but is available to test in the v1.6.0-rc.

**Comment by manlinl** [comment]
@mogren Thx for this inform!
