### ISSUE TITLE
Use MultiStage Docker build

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#638]
We should use a multi stage docker build to reduce size of the final image.

**Comment by Zyqsempai** [comment]
@mogren I Will take this one!

**Comment by Zyqsempai** [comment]
But i already see so made changes related to this topic, what should be done?

**Comment by mogren** [comment]
@Zyqsempai Thanks for volunteering! The Idea here would be to have a build step first, then copy the built CNI binary to a final image in another step since `go mod download` will fetch a lot. It's described pretty well in this blog post: https://levelup.gitconnected.com/multi-stage-docker-builds-with-go-modules-df23b7f91a67

**Comment by mogren** [comment]
@Zyqsempai Heh, you are right, I was looking at the wrong dockerfile last night... Closing it.
