### ISSUE TITLE
AWS CNI should install loopback cni plugin

### ISSUE THREAD

**Issue by nckturner** [aws/amazon-vpc-cni-k8s#64]
This is not required by AWS CNI but kubelet fails without it.

**Comment by worzel666** [comment]
Hey, we're experiencing this issue as well, @nckturner did you find a fix?

**Comment by mogren** [comment]
Not needed.

**Comment by scrothers** [comment]
@mogren, 

  Warning  FailedCreatePodSandBox  110s (x37 over 5m2s)   kubelet, ip-10-1-131-66.us-east-2.compute.internal  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b576e7cf5b25584b510ca25a0a97ef39590b1eb688c2a7075879bc744b97837b" network for pod "default-http-backend-67cf578fc4-l4sv4": networkPlugin cni failed to set up pod "default-http-backend-67cf578fc4-l4sv4_ingress-nginx" network: failed to find plugin "loopback" in path [/opt/cni/bin]

Seems to be needed.
