### ISSUE TITLE
Allow Tagging NIC Created by Plugin

### ISSUE THREAD

**Issue by robottaway** [aws/amazon-vpc-cni-k8s#643]
For the purpose of settings tags used to differentiate billing to one customer versus another we could use the ability to set arbitrary tags on the ENI created. Already we create tags such as 

https://aws.amazon.com/blogs/opensource/vpc-cni-plugin-v1-1-available/

But these are static and more for the purpose of debugging than being used for other business purpose. Having the ability to define tags as needed and have them propagate to ENI will enable many useful business cases.

**Comment by mogren** [comment]
Fixed in #734
