### ISSUE TITLE
control the resource access

### ISSUE THREAD

**Issue by tianyuan848192** [aws/amazon-vpc-cni-k8s#651]
we have just meet the situation as follow:
1. we are using ec2 to build up our k8s environment and using aws-cni as network solutions.
2. our k8s platform is under an account which have other ec2 instance.
3. we need try to attach the IAM policy to the ec2 which is k8s node instance that make them can attach or detach network interface  and other necessary action.

Our concerned is :
In our case, we might want to strict the IAM policy that make k8s instance only can operate the resource that contains the specific tags because we are in a mixed environment. However, we found the IAM action like AttachNetworkInterface or DetachNetworkInterface can not be set specific resource or condition.  we are afraid some unexpected action  will impact other ec2 instance which is not in our k8s platform. 

Just want to make sure is there any way to strict the IAM policy to make sure this will not happened or is there work-round solution?

**Comment by mogren** [comment]
Hi @tianyuan848192,

If you use [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), you should be able to scope a more privileged IAM role for the CNI daemonset service account. That way you can use a less privileged IAM role for your other pods.
