### ISSUE TITLE
Branch release-1.5, the aws-k8s-cni.yaml still pointing to amazon-k8s-cni v1.5.3 instead of v1.5.4

### ISSUE THREAD

**Issue by oceannic** [aws/amazon-vpc-cni-k8s#658]
From AWS official page, it mentioned that by applying the yaml "https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5/config/v1.5/aws-k8s-cni.yaml", CNI will upgrade to latest 1.5.4 version. 
However, I noticed that the aws-k8s-cni.yaml under release-1.5 branch still pointing to CNI v.1.5.3, which is not sync with the information provided in AWS official page - https://docs.aws.amazon.com/eks/latest/userguide/cni-upgrades.html 

Seems like only master and release-1.5.4 branches are pointing to the latest v1.5.4

**Comment by longatrover** [comment]
@oceannic 

Agreed, after reporting to AWS it actually looks like 1.5.3 is the intended version to be on due to a networking issue discussed here: https://github.com/aws/amazon-vpc-cni-k8s/issues/641

They should be making amendments to the upgrade documentation page to account for this.

**Comment by mogren** [comment]
In case there was some issue with v1.5.4 that is not in v1.5.3, we did a temporary rollback. Since the issue seems to be the same in both versions, I reverted it back to v1.5.4.
