### ISSUE TITLE
master node in notready state due to cni setup issue

### ISSUE THREAD

**Issue by xnwsw** [aws/amazon-vpc-cni-k8s#661]
This maybe a basic setup question. I followed the install steps on [k8s site](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/), and after 'kubeadm init', I installed this addon, which seemed to work, a rerun confirms:

`$ kubectl apply -f amazon-vpc-cni-k8s/config/v1.5/aws-k8s-cni.yaml
clusterrole.rbac.authorization.k8s.io/aws-node unchanged
serviceaccount/aws-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/aws-node unchanged
daemonset.apps/aws-node unchanged
customresourcedefinition.apiextensions.k8s.io/eniconfigs.crd.k8s.amazonaws.com unchanged`

After this I expect the master should be in ready state, but 'get nodes' shows it is not.  'describe nodes' shows this message 

> KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

am I look at the right direction?
thanks,

```
$ kubectl get nodes
NAME               STATUS     ROLES    AGE   VERSION
ip-172-xxx   NotReady   master   34m   v1.16.2
ubuntu@ip-172-xxx:~$ kubectl describe nodes ip-172-xxx
Name:               ip-172-xxx
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-172-xxx
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 17 Oct 2019 06:13:51 +0000
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 17 Oct 2019 06:47:57 +0000   Thu, 17 Oct 2019 06:13:48 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 17 Oct 2019 06:47:57 +0000   Thu, 17 Oct 2019 06:13:48 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 17 Oct 2019 06:47:57 +0000   Thu, 17 Oct 2019 06:13:48 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 17 Oct 2019 06:47:57 +0000   Thu, 17 Oct 2019 06:13:48 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by GSCSW** [comment]
@azretkenzhaliev , no I have not. I see this is part of eks setup, but I didn't use EKS, instead simply started an EC2 instance.  and following this instruction:
https://github.com/aws/amazon-vpc-cni-k8s#setup

which boils down to just one command : 
`kubectl apply -f aws-k8s-cni.yaml`

is this not enough? does regular ec2 instance support k8s install? or do I have to rely on eks?

thanks,

**Comment by azretkenzhaliev** [comment]
In my case, I have a Kubernetes cluster (not EKS) that is built over the EC2 instances (spot fleet request), and yes, you have to apply CRD because otherwise when CNI will be querying the kube-api-server for information on in which subnet to put a pod, it will basically fail because there is no "ENIConfig" CRD and no information is being provided on how to configure ENI for the pod under processing.

**Comment by mogren** [comment]
@azretkenzhaliev If you have `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true`, you also have to provide a custom ENI config. Unless you really need it, it's easier not to set this flag. If you do need to keep the pods and nodes separate, there are setup instructions in the [AWS EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html).

**Comment by azretkenzhaliev** [comment]
@mogren Ah, right :) We do use this flag at Yelp — that's probably why I said that to @GSCSW

**Comment by mogren** [comment]
@azretkenzhaliev 🤦‍♂️😀

**Comment by jaypipes** [comment]
@xnwsw apologies for the late response on this. Can you verify that a) this is still an issue you are seeing and b) when you are setting up your kops k8s cluster, are you using an EC2 node as both master and worker node?

We discussed this today and suspect that there might have been issues with incorrect IAM permissions specified for the kubeadm master node IAM role. Looking at the pod logs might help to diagnose this further. There would likely be an error about permissions failure on the `aws-node` daemonset logs.

Please let us know if you're able to provide us a bit more information. Thanks!

**Comment by mogren** [comment]
@xnwsw Is this still an issue? Was it permission related?
