### ISSUE TITLE
AWS_VPC_K8S_CNI_RANDOMIZESNAT prng not working in amazon-k8s-cni:v1.4.1 (and 1.5+)

### ISSUE THREAD

**Issue by jraby** [aws/amazon-vpc-cni-k8s#662]
The iptables version shipped in the amazon-k8s-cni image does not support the `--fully-random` SNAT option. This option was introduced in iptables 1.6.something whereas v1.24.x is used in the  amazon-k8s-cni image. (this seems to be the version from the yum repos from amazonlinux)

When setting `AWS_VPC_K8S_CNI_RANDOMIZESNAT` to  `prng` using this image, it falls back to the hash random method.

Is it expected that fully-random is not working out of the box on the official image? And is there a way to get the `--fully-random` behavior using the official images?

Thanks.

(edit: clarified question)

**Comment by jaypipes** [comment]
Hi @jraby, yes this is the expected behaviour, AFAICT from the code:

https://github.com/aws/amazon-vpc-cni-k8s/blob/3aacadcc5337801b4bf9e027863edbebd68a5bf1/pkg/networkutils/network.go#L349-L357

You should see a warning logged about falling back to "random" instead of "random-fully".

As for when the AL2 iptables package will be updated to a more modern version, I don't know the answer to that. Perhaps @stewartsmith would be able to answer that.

**Comment by jraby** [comment]
For the record, building an image based on `centos:8` instead of `amazonlinux:2` seems to work well.

```
diff --git a/scripts/dockerfiles/Dockerfile.release b/scripts/dockerfiles/Dockerfile.release
index 11bcf42..56da47c 100644
--- a/scripts/dockerfiles/Dockerfile.release
+++ b/scripts/dockerfiles/Dockerfile.release
@@ -17,7 +17,7 @@ RUN go mod download
 COPY . .
 RUN make build-linux && make download-portmap

-FROM amazonlinux:2
+FROM centos:8
 RUN yum update -y && \
     yum install -y iproute && \
     yum install -y iptables && \
```

**Comment by jraby** [comment]
In the end we rolled our own image with the following pseudo diff:
```
 FROM amazonlinux:2
 RUN yum update -y && \
     yum install -y iproute && \
-    yum install -y iptables && \
+    yum install -y tar wget bzip2 gcc gcc-c++ make && \
     yum clean all

+# iptables 1.8.3 without nftable support (aka iptables-legacy to match what kube-proxy uses)
+RUN cd /tmp && wget http://www.netfilter.org/projects/iptables/files/iptables-1.8.3.tar.bz2 && \
+    tar xvf iptables-1.8.3.tar.bz2 && cd iptables-1.8.3 && \
+    ./configure --disable-nftables  --enable-static --disable-shared --prefix=/usr/local && \
+    make && make install
[...]
```

One needs to be aware that iptables >=1.8.0 defaults to nftables (so does iptables shipped with centos:8), which will break if used on a node where `kube-proxy` also injects rules with an older version of iptables.
The above builds iptables without that nftable support to avoid any surprise / conflict.

Fun times.

**Comment by nithu0115** [comment]
#509

**Comment by mogren** [comment]
We need awslabs/amazon-eks-ami#380 done to be able to resolve this issue.

**Comment by mogren** [comment]
Fixed in [v1.5.7](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.7)

**Comment by terrych0u** [comment]
I also got the same issue on the newest eks 1.16 with CNI 1.6.1 and my kube-proxy 1.16.8 keeps show log :
```
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
```

is there any way to fix it?

**Comment by lapidus79** [comment]
@mogren the same issue shows up in eks 1.16 with cni 1.6.2 and kube-proxy v1.16.8

**Comment by infa-ddeore** [comment]
> @mogren the same issue shows up in eks 1.16 with cni 1.6.2 and kube-proxy v1.16.8

`--random-fully` support is added in `1.7.0` [aws-cni](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.0) so using this and above version should solve the problem
