### ISSUE TITLE
ENI not using AWS_VPC_ENI_MTU

### ISSUE THREAD

**Issue by Sushruth-Godugunuari** [aws/amazon-vpc-cni-k8s#665]
We attempted to use environment variable AWS_VPC_ENI_MTU introduced in [v1.6.0-rc3](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0-rc3) but the pods created still use the default value of 9001.

Kubernetes Version:  1.12
Platform Version: eks.5
Worker AMI: amazon-eks-node-1.12-v20190927 (ami-0ee9e136178176e29)

**Comment by jaypipes** [comment]
Hi @Sushruth-Godugunuari, do you see any output related to MTU setting failure in your logs?

**Comment by mogren** [comment]
I've tested this and noticed that the `MTU` gets set on eth1, eth2 and so on, but not on eth0.

**Comment by Sushruth-Godugunuari** [comment]
No, our network team was seeing packets being dropped because of jumbo frames at our firewall. I see the MTU is 9001 when I run `ifconfig` on the pod
