### ISSUE TITLE
FailedCreatePodSandBox

### ISSUE THREAD

**Issue by geraldstanje** [aws/amazon-vpc-cni-k8s#668]
```
$ kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni:v1.3.2
```

im seeing this error, whats the suggested way to fix it, what cni version would fix the problem? the ip address is randomized.
```
Warning  FailedCreatePodSandBox  4m10s (x4 over 4m13s)   kubelet, ip-99-1-23-122.ec2.internal  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9234234234de67e8234cdc5c23423dce7e20842b8334208a6bff3a8" network for pod "custom-test-endpoint-5659dd6f47-92rj7": NetworkPlugin cni failed to set up pod "custom-test-endpoint-523422f47-92rj7_default" network: add cmd: failed to assign an IP address to container
```

**Comment by nckturner** [comment]
`failed to assign an IP address`  The CNI plugin logs are telling you that you don't have any IP addresses available on the instance to assign to the pod.  Did you look at the number of free IP addresses available on the instance?

**Comment by geraldstanje** [comment]
i updated the CNI plugin to a newer version and it worked...

**Comment by geraldstanje** [comment]
i updated the version of the CNI plugin and didnt see that error any more, is that expected?

**Comment by mogren** [comment]
The number of free IPs is per Subnet and you can see it in your AWS console. The issue could have been resolved by running less pods. @geraldstanje Is this still an issue?

**Comment by mogren** [comment]
Please re-open if you see this issue again.
