### ISSUE TITLE
Pod IP Addresses are duplicated

### ISSUE THREAD

**Issue by dmai-apixio** [aws/amazon-vpc-cni-k8s#677]
I found ip addresses could be duplicated in EKS cluster

```
default       consul-mh7dg                   1/1     Running   0          15d     10.0.133.254   ip-10-0-135-147.us-west-2.compute.internal   <none>           <none>
default       reverse-proxy-c546b77bb-4h6jp  1/1     Running   0          15d     10.0.135.159   ip-10-0-135-147.us-west-2.compute.internal   <none>           <none>
kube-system   aws-node-mrdfk                 1/1     Running   0          15d     10.0.135.147   ip-10-0-135-147.us-west-2.compute.internal   <none>           <none>
kube-system   kube-proxy-fvg6t               1/1     Running   0          15d     10.0.135.147   ip-10-0-135-147.us-west-2.compute.internal   <none>           <none>
monitor       datadog-c8p9q                  1/1     Running   0          15d     10.0.135.208   ip-10-0-135-147.us-west-2.compute.internal   <none>           <none>
```

You can see `aws-node-mrdfk` and `kube-proxy-fvg6t` has the same ip address with the worker node `10.0.135.147`

**Comment by nckturner** [comment]
That's because they use host networking, which means they share the same network namespace and IP with the node.

**Comment by dmai-apixio** [comment]
As i know, a aws worker node had a pool of  ip addresses that the worker will assign for a running pod.
Wondering how could be duplicated.
Is it a bug? If pod A and pod B have the same ip, how can i make sure i will talk to pod A, not a pod B.

**Comment by mogren** [comment]
Hi @dmai-apixio,

As @nckturner mentioned, pods using host network bind to different ports on the IP of the host itself. As you can see in that output, the regular pods (in the `default` namespace) all get IPs from the secondary IPs on the ENIs for that worker node. The CNI (`aws-node`) and `kube-proxy` both use host networking.

Some more details about host network in Docker: https://docs.docker.com/network/host/
