### ISSUE TITLE
Document and automate CNI build process

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#687]
There is basic documentation for the build process for the CNI plugin in the README. However, we should add a test of the build process to the new CircleCI runner to automate the process of building and testing those builds.

Basic build process should be put into the CircleCI YAML file (or put into a Bash script and then called from the CircleCI file):

```
#build binary
make 

# run unit test
make unit-test

# on mac
make docker-unit-test

# also do following
make lint

# build docker images
make docker 

# push docker images to $REPO
docker tag amazon/amazon-k8s-cni:latest $AWS_ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:test
```

Of course, the `$AWS_ACCOUNT` needs to be placed into a secret somewhere.

**Comment by mogren** [comment]
This is currently being done in the run-integration-tests.sh script.
