### ISSUE TITLE
Automate e2e tests for leaked ENIs

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#690]
We currently run some manual e2e tests that attempt to emulate the situations where we know (#69, #608) ENIs may be leaked and catch these situations (#624, #645).

We need to automate the running of these e2e tests and gate all merges to prevent regressions.

**Comment by jayanthvn** [comment]
This is added to the new integration framework - 

```
- Manually force detach an ENI
- Let the cni cleanup routine start
- Verify that the ENI is cleaned up.
```
