### ISSUE TITLE
Automate large scale load test

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#693]
Similar to #691, this is for automating of a larger scale test with 100 nodes and 4300 pods:

1. create 100 c4.xlarge node cluster
1. scale replica from 0 to 4300
1. verify kubectl get deployment all to available 
1. scale replica from 4300 to 0
1. verify kubectl get deployment

This should not be done on each PR of course, but set to run automatically before a release commit/tag and periodically

**Comment by mogren** [comment]
Added in #1068
