### ISSUE TITLE
Automate CNI plugin upgrade testing

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#694]
Before releases, we manually perform a test of the upgrade process for the CNI plugin:

1. create 3 c3.xlarge node cluster
1. scale pod replica from 0 to 130
1. verify kubectl get deployment
1. upgrade cni to new version
1. verify kubectl get deployment
1. scale replica from 130 to 0
1. verify kubectl get deployment
1. scale replica from 0 to 130 again and verify

We should automate this and gate all PRs on a successful upgrade test

- [ ] Convert above steps into a Bash script
- [x] Add job to CircleCI pipeline, gating for all PRs

**Comment by mogren** [comment]
The current test script doesn't scale up and down.

**Comment by jayanthvn** [comment]
1. Scale up to 130 pods (Ref performance script)
2. Run traffic test from the new integration scripts.
3. Upon success, scale down to 0
4. Upgrade to latest CNI
5. Repeat 1-3 steps.

**Comment by jayanthvn** [comment]
@cgchinmay - Can we include this issue as part of this PR - https://github.com/aws/amazon-vpc-cni-k8s/pull/1863
