### ISSUE TITLE
awscni_total_ip_addresses vs awscni_ip_max

### ISSUE THREAD

**Issue by karancode** [aws/amazon-vpc-cni-k8s#696]
I wanted to know the difference b/w these metrics that are exposed.
I read the test example [here](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cni-metrics-helper/metrics/cni_test1.data#L4).
What I didn't understand is the exact difference b/w `awscni_assigned_ip_addresses The number of IP addresses assigned to pods` and `awscni_ip_max The maximum number of IP addresses that can be allocated to the instance`.
I mean, why the number of IPs that can be assigned to an instance & to a pod are different ?

**Comment by jaypipes** [comment]
Hi @karancode!

`awscni_assigned_ip_addresses` is the count of IP addresses on the worker node that have been assigned to pods already. It is incremented when any Pod gets an IP address assigned to it on any of the ENIs on the worker node. It is decremented when the Pod is terminated and its assigned IP address is disassociated with the Pod.

`awscni_ip_max` is the maximum number of IP addresses that *may be* assigned to a pod on the worker node. It is calculated by multiplying the number of IP addresses that can fit on each ENI (depends on instance type) times the number of ENIs on the worker node (also depends on the instance type).

Best,
-jay

**Comment by karancode** [comment]
Hi @jaypipes sorry, looks like my question wasn't perfect.
The metrics I am confused about are 
- `awscni_total_ip_addresses`
- `awscni_ip_max`

What's the difference between these ? Also I checked, the value of `awscni_ip_max` is way greater than `awscni_total_ip_addresses`.
