### ISSUE TITLE
Elaborate on roadmap regarding security groups and load balancers

### ISSUE THREAD

**Issue by copumpkin** [aws/amazon-vpc-cni-k8s#7]
Currently the proposal says that a limitation is

> All ENIs on a instance share same subnet and same security groups.

Which is at odds with some of the stated goals. I get that this is a point-in-time view of the CNI but I'm curious what the plan is going forward to support this.

Some specific questions:

1. How does this all relate (if at all) to the `awsvpc` networking mode in ECS, which seems to (as far as I've been able to tell) manage ENIs directly and drop their interface directly into the relevant container's network namespace?
2. What will the user-facing interface look like? For example, if I want to ensure that a particular pod is "in" `sg-123456` (because let's say that's the only SG allowed to speak to my RDS database), how would I tell k8s that?
3. What ENI structure would specifying an explicit SG lead to behind the scenes? Particularly curious when you end up with multiple containers on the same EC2 instance with different security groups.
4. Is there a story for how this will play with native AWS load balancers? Currently ECS seems to have a decent story in this space but it's much less clear to me what it would look like for k8s.

Not sure if it makes more sense to answer these here or just to add more to the proposal, but those are the questions that jumped to mind when I was reading it.

**Comment by mumoshu** [comment]
I'm interested in those questions.

Regarding security groups - perhaps Calico(was mentioned in the announcement as far as I know) will be enhanced to support amazon-vpc-cni-k8s as the backend instead of other providers like flannel, so that ingress/egress rules of K8S network policies are reflected to security groups assigned to the secondary ENIs?

**Comment by lxpollitt** [comment]
@mumoshu Yes, Calico and amazon-vpc-cni-k8s will work together to provide ingress/egress rules of K8s network policies.  You can think of SGs as providing the underlying cluster (VM oriented) security and Kubernetes network policy providing the fine-grained micro-service (container oriented) security.

**Comment by mumoshu** [comment]
@lxpollitt Thank you very much for clarification! Fully understood.

Would there be a dedicated github issue to track the progress and remaining tasks for that?

**Comment by mogren** [comment]
Resolving old issues.
