### ISSUE TITLE
Scenario-based e2e testing

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#703]
Add parameterization for e2e testing to allow permutations/scenarios for:

* MTU
* routing behaviour
* num ENIs, IPs, instance types, etc

**Comment by Shreya027** [comment]
Hi @jaypipes, I am working on this issue and would like more context over the scenarios to consider in routing behavior. Also, for the num ENIs, IPs, instance types scenario, do we need to modify  instance types for different cases as changing the instance type would in turn change num ENIs and IPs ?
