### ISSUE TITLE
awscni_total_ip_addresses vs awscni_ip_max 

### ISSUE THREAD

**Issue by karancode** [aws/amazon-vpc-cni-k8s#704]
Sorry for a new issue but looks like #696 got stale.

The metrics I am confused about are

- `awscni_total_ip_addresses`(The total number of IP addresses)
- `awscni_ip_max` (The maximum number of IP addresses that can be allocated to the instance)

What's the difference between these ? Also I checked, the value of awscni_ip_max is way greater than awscni_total_ip_addresses.
For ex: what would be the max. number of IPs that can be assigned to pods ? 
will it be 
```
sum(awscni_total_ip_addresses) - sum(awscni_assigned_ip_addresses)
```
OR
```
 sum(awscni_ip_max) - sum(awscni_assigned_ip_addresses)
```

/cc @jaypipes

**Comment by jaypipes** [comment]
> Sorry for a new issue but looks like #696 got stale.
> 
> The metrics I am confused about are
> 
>     * `awscni_total_ip_addresses`(The total number of IP addresses)

This is an actual metric/gauge whose value is incremented for *each IP address that can be assigned* to an ENI when an ENI is added to the set of ENIs managed by the ipamD daemon. This happens on start of the CNI plugin's ipamD daemon.

Each time the `addENIaddressesToDatastore` method is called:

https://github.com/aws/amazon-vpc-cni-k8s/blob/5f22fd714ed1713f9345bf2056a0a59b51994d8a/ipamd/ipamd.go#L738

the `AddIPv4AddressToStore` method is called:

https://github.com/aws/amazon-vpc-cni-k8s/blob/5f22fd714ed1713f9345bf2056a0a59b51994d8a/ipamd/ipamd.go#L745

and that method increments the `awscni_total_ip_addresses` gauge:

https://github.com/aws/amazon-vpc-cni-k8s/blob/5f22fd714ed1713f9345bf2056a0a59b51994d8a/ipamd/datastore/data_store.go#L202-L204

>     * `awscni_ip_max` (The maximum number of IP addresses that can be allocated to the instance)

`awscni_ip_max` isn't a metric that changes. It is set on start of the ipamD daemon to the value of `NumENIs * NumIPsPerENI`. The number of IPs per ENI and the number of ENIs is dependent on the instance type.

> What's the difference between these ?

`awscni_total_ip_addresses` is a metric that is incremented each time the CNI plugin's ipamD daemon adds a new managed ENI to its pool of ENIs. `awscni_ip_max` is never incremented. It's a static  value that is *calculated* on startup.

> Also I checked, the value of awscni_ip_max is way greater than awscni_total_ip_addresses.
> For ex: what would be the max. number of IPs that can be assigned to pods ?
> will it be
> 
> ```
> sum(awscni_total_ip_addresses) - sum(awscni_assigned_ip_addresses)
> ```
> 
> OR
> 
> ```
>  sum(awscni_ip_max) - sum(awscni_assigned_ip_addresses)
> ```

Neither :) The maximum number of IPs that can be theoretically assigned to pods on a node is `awscni_ip_max`. The value of `awsvpc_total_ip_addresses` is the total number of IPv4 addresses that the ENIs on a worker node have been allocated. `awsvpc_assigned_ip_addresses` is the total number of IPv4 addresses that have been assigned to a *pod* that is running on the worker node.
