### ISSUE TITLE
Routes missing for some IP:s

### ISSUE THREAD

**Issue by thomas-brx** [aws/amazon-vpc-cni-k8s#705]
* EKS 1.14
* CNI v1.5.4

## Background
After terminating an instance in a cluster of 2, most pods were relocated to the only remaining instance before a new instance were launched. The relocated pods could not resolve DNS queries, or reach other pods.

After some digging around, it turns out that some of the IP:s on the instance are missing from the routing table:

```
# ip rule
0:      from all lookup local
512:    from all to 10.80.36.229 lookup main
512:    from all to 10.80.38.149 lookup main
512:    from all to 10.80.33.161 lookup main
1024:   from all fwmark 0x80/0x80 lookup main
1536:   from 10.80.40.40 to 10.80.0.0/16 lookup 2
1536:   from 10.80.44.94 to 10.80.0.0/16 lookup 2
1536:   from 10.80.36.229 to 10.80.0.0/16 lookup 2
1536:   from 10.80.38.149 to 10.80.0.0/16 lookup 3
1536:   from 10.80.33.161 to 10.80.0.0/16 lookup 3
32766:  from all lookup main
32767:  from all lookup default
```

These are all podIP:s on the same instance:
```
10.80.36.229
10.80.38.149
10.80.33.161
10.80.55.54
10.80.46.124
10.80.53.33
10.80.44.94
10.80.40.40
```
Only the first 3 of those have the `from all to ... lookup main` entry.

As an example, when the pod with podIP 10.80.36.229 tries to connect to a pod on the same instance with podIP 10.80.46.124, it fails due to the missing `from all to 10.80.46.124 lookup main`, the packets are simply routed out of the instance.

```
# nc -zvv 172.20.1.28 8080
nc: 172.20.1.28 (172.20.1.28:8080): Connection timed out
sent 0, rcvd 0
```
(172.20.1.28 is forwarded to 10.80.46.124 by the standard iptables rules, managed by kube-proxy)

I do have an `aws-cni-support.tar.gz` available for the instance. Let me know if it could be useful.

**Comment by nithu0115** [comment]
@thomas-brx, have you looked into #641 ?

**Comment by thomas-brx** [comment]
> @thomas-brx, have you looked into #641 ?

Thanks, completely missed that one! 

Duplicate of: #641
