### ISSUE TITLE
network: failed to Statfs "/proc/24876/ns/net": no such file or directory

### ISSUE THREAD

**Issue by dannyburke1** [aws/amazon-vpc-cni-k8s#707]
Hi,

We're running into a couple of issues running AWS EKS when doing a helm upgrade. 
This platform has been running fine up until recently where a new deployment had originally issued the following error: 

> NetworkPlugin cni failed to set up pod "xxxx" network: add command: failed to setup network: setupNS: failed to add pod rule: file exists

Upon searching the issues here I had seen that there were some fixes for this issue in later versions of CNI, we were running 1.4.1 when this error occurred on Kube 1.12 (EKS).

We are now running:

`git:(danny/vpc-move) ✗ kubectl describe daemonset aws-node -n kube-system | grep Image | cut -d "/" -f 2
amazon-k8s-cni:v1.6.0-rc4`

Which is giving us this error:

> NetworkPlugin cni failed to set up pod "xxx" network: failed to Statfs "/proc/24558/ns/net": no such file or directory

Still on EKS 1.12.

This platform has been fine up this recent deployment. 

Addressable ENI count seems fine and network utilisation seems stable.
Pod count is no higher than normal either. 

Has anybody else experienced this issue and is upgrading to EKS 1.13 the answer?

Additionally, if there are any other actions I can take to get more information I am happy to do so.

Any help on this issue is greatly appreciated.

Thanks,
Danny

**Comment by jaypipes** [comment]
@dannyburke1 are you seeing this error repeatedly in CNI logs? or was this a one-time thing you saw when upgrading?

**Comment by dannyburke1** [comment]
Hi @jaypipes - it appears a few times in the events after a helm upgrade fails.

This only populates once and upgrade is triggered though.

**Comment by jaypipes** [comment]
@dannyburke1 Can you paste all of the CNI logs you have, please? Thanks!

**Comment by dannyburke1** [comment]
Hi @jaypipes - we received this email from AWS directly, are you aware of this?:

> A recent update to the AWS VPC CNI plugin [1] version 1.5.4 caused connection timeouts between pod to pod communication within the same worker node. This can cause operational instability for applications. The issue is more pronounced with low values of WARM_IP_TARGET set on the plugin configuration [2].

You should rollback [3] your cluster's VPC CNI to version 1.5.3 AS SOON AS POSSIBLE.

run: kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.5.3/config/v1.5/aws-k8s-cni.yaml

We're trying a deployment with this version now to see if this resolves the issue.

If it doesn't, i'll send you the logs over. 

Thanks!

**Comment by dannyburke1** [comment]
Hi,

This can be closed using the version 1.5.3 seemed to do the trick :)
