### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by morro-wind** [aws/amazon-vpc-cni-k8s#708]
I use kubernetes(not AWS EKS) on aws ec2 add amazon-vpc-cni  
kubernetes version: v1.15.3
vpc-cni version: v1.5

I run command:

`$(aws ecr get-login --no-include-email --registry-ids 602401143452 --region ap-southeast-1)`

```WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/centos/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```
`kubectl apply -f aws-k8s-cni.yaml`

but aws-k8s-cni is not install 

system log message :
```
15542 kuberuntime_image.go:51] Pull image "602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/amazon-k8s-cni:v1.5.3" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.5.3: no basic auth credentials
```

**Comment by devkid** [comment]
Does your node role have permissions to pull from ECR?

**Comment by mogren** [comment]
@morro-wind Like @devkid mentioned, all worker nodes will do an image pull trying to fetch `602401143452.dkr.ecr.ap-southeast-1.amazonaws.com/amazon-k8s-cni:v1.5.3`, so the node role needs to be allowed to do that.

**Comment by rimaulana** [comment]
@morro-wind not only that your worker node need to have ECR policy on its IAM role to be able to pull docker image from ECR, you will also need to add flag --cloud-provider aws when starting kubelet on worker node. Doing this, kubelet will automatically get ECR token authorization using worker node IAM role.

**Comment by morro-wind** [comment]
I attached IAM role to the ec2 instance and the problem was resolved

**Comment by wttat** [comment]
> I attached IAM role to the ec2 instance and the problem was resolved

which iam  role did you attach ?
I have AmazonEC2ContainerRegistryFullAccess and AmazonSageMakerFullAccess policy's role on my ec2, it runs a Minikube but happen the same issue
