### ISSUE TITLE
podIP duplicate with hostIP

### ISSUE THREAD

**Issue by evan-lin** [aws/amazon-vpc-cni-k8s#709]
The host has 2 ENIs with primary IPs:
<img width="187" alt="Screen Shot 2019-11-09 at 3 07 57 PM" src="https://user-images.githubusercontent.com/17717672/68524523-f98ff300-0302-11ea-989f-58aa272f394c.png">

And here are the secondary IPs:
<img width="318" alt="Screen Shot 2019-11-09 at 3 09 04 PM" src="https://user-images.githubusercontent.com/17717672/68524527-13c9d100-0303-11ea-8312-e0170df9ba03.png">

The CNI suppose to assign pod with secondary IPs, however, one pod (this pod was created by deployment) is assigned with the host primary IP
![WechatIMG188](https://user-images.githubusercontent.com/17717672/68396298-4f05bc00-01ac-11ea-9a0d-8e798943a8d8.png)

![WechatIMG193](https://user-images.githubusercontent.com/17717672/68396370-6e044e00-01ac-11ea-9d5a-1e966d00b5e4.png)

The environment is k8s:v1.10.4 with amazon-k8s-cni:v1.5.4 (have to use the latest version because we are running on the new G4 instance, old version get unknown instance type error)

Also attach with the cni logs.
[aws-routed-eni.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/3827007/aws-routed-eni.zip)

**Comment by devkid** [comment]
This pod is most likely running with `hostNetwork: true` therefor correctly has the host IP.

**Comment by mogren** [comment]
Like @devkid said, this sounds like it is using host network.

@evan-lin You should try [v1.5.5-rc1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.5.5-rc1) instead, it has a fix for a quite serious bug in v1.5.4, and also support g4 (and a few other new instance types).

**Comment by evan-lin** [comment]
> This pod is most likely running with `hostNetwork: true` therefor correctly has the host IP.

@devkid thanks, but I think it has nothing to do with the hostNetwork, the CNI suppose to assign the pod with IP in additional network interface - eth1, instead of assign with the IP for eth0, which is duplicate with the host IP.

**Comment by devkid** [comment]
Does this pod have `hostNetwork: true` set? If yes, then the CNI is **not** supposed to assign an additional IP.

**Comment by evan-lin** [comment]
> Does this pod have `hostNetwork: true` set? If yes, then the CNI is **not** supposed to assign an additional IP.
Hi @devkid , the issue is not about the network access between host and pods, it is about the IP allocation logic by the CNI.
For my scenario, the host has two network interfaces: eth0, eth1
<img width="44" alt="Screen Shot 2019-11-09 at 10 44 10 PM" src="https://user-images.githubusercontent.com/17717672/68530355-860dd600-0342-11ea-8cbc-5d5f7e8030fb.png">
eth0 has 2 IP, 
<img width="187" alt="Screen Shot 2019-11-09 at 3 07 57 PM" src="https://user-images.githubusercontent.com/17717672/68530378-a5a4fe80-0342-11ea-8fdf-ed8ff327b32e.png">
 eth1 has multiples IP,
<img width="318" alt="Screen Shot 2019-11-09 at 3 09 04 PM" src="https://user-images.githubusercontent.com/17717672/68530396-bce3ec00-0342-11ea-99c0-479d11ebf983.png">
as CNI is applied on K8S, when new pod is deployed, CNI will assign IP of **eth1** to pod.
In my case, as you can see in assignedIP list
![WechatIMG193](https://user-images.githubusercontent.com/17717672/68530488-527f7b80-0343-11ea-8a22-1d8d86ee7efd.png)
all pods are assigned with IP of **eth1**, except one - one pod is assigned with IP of **eth0**! this should never happens for my understanding.

**Comment by devkid** [comment]
You seem to confuse something here.

> the issue is not about the network access between host and pods, it is about the IP allocation logic by the CNI.

No, it's not. When the pod (that has this host IP show up in Kubernetes) is running with `hostNetwork: true`, the CNI doesn't do anything about this pod. It doesn't assign any IP to it. The pod runs in the same network namespace as the host and therefore it sees (like the host) all the (virtual) interfaces (that are mapped to all the pods running on that host that do **not** have `hostNetwork: true` set) and only a single IP (the host IP) on the first interface (you can verify this by logging into the instance via SSH and running `ip addr` - running the same command in the pod would yield the same output).

Would you please be so kind to verify if `hostNetwork: true` is set on the pod that has this host IP? (Or provide the output of `kubectl get pod -o yaml <pod name>`?)

>  as CNI is applied on K8S, when new pod is deployed, CNI will assign IP of eth1 to pod.

Not necessarily. IPs can be assigned to any interface (also to eth0, as it's the case in your screenshots - you don't have only one IP on eth0). The primary IP on eth0 is the host IP and will be used by all pods that have `hostNetwork: true` enabled. If new IPs are requrested for new pods, they can be assigned to any interface on the instance.

Also, your screenshots show contradictory contents. Your first screenshot shows that your first interface has 2 IPs, the screenshot from your terminal shows that is has 5. I assume the screenshots were taken at different points in time. Also, the interface with the IPs that are visible in your terminal screenshot are `eth0` (`"DeviceNumber": 0), not `eth1`. If you look closely, `10.29.51.169` is not assigned to `eth1` in the other screenshot (the other IPs are, but I assume they got released in the time between the screenshots and reassigned to `eth1` in the mean time).

**Comment by evan-lin** [comment]
Much thanks for the your patient and details explanation. Sorry that my screenshots caused the confusing. For your questions: yes, the pods have hostNetwork: true enabled. The first screenshot is primaryIPs for both eth0 and eth1, one for each, so there are 2 IPs. The terminal screenshot show the total IP pool (29) for all ENI, and at that time, 5 have been assigned to pods.

Anyway, forget my above explanations about host IP and pod IP, and let me try to explain it in this way:
The node has 2 network interfaces - ENIs, as its instance type is G4dn.8x, the max available IP per ENI is 15. 
According to https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md, 
>A node, based on the instance type limit, can have up to N ENIs and M addresses. The maximum number of IP addresses available to pods on this node is min((N * (M - 1)), free IPs in the subnet). **The -1 is because each ENI uses one of the IPs when it is attached to the instance.**

So the max number of IP addresses available to pods on this node is 2 * (15-1) = 28.
Use the command can show the details:
>curl http://localhost:61679/v1/enis | python -m json.tool

[eni.out.log](https://github.com/aws/amazon-vpc-cni-k8s/files/3828322/eni.out.log)
As you can in the output, there are 29 IPs instead of 28 (5 have been assigned to pods already):
<img width="251" alt="Screen Shot 2019-11-10 at 6 10 42 PM" src="https://user-images.githubusercontent.com/17717672/68542584-20285980-03e9-11ea-981a-2dbca7e2cede.png">
2 ENIs - 15 IPs for each, and each ENI should have one reserved IP. 
While in my case, the reserved IP for one ENI (the primary one) is also added into the pool, which I believe is wrong: the IP 10.29.52.187 supposed to be reserved for ENI is assigned to a pod created by deployment.
Actually, after I rebuild the node, it become normal: there are 28 IPs in the pool. I just concern about the issue may occurs again.

**Comment by devkid** [comment]
I believe the documentation you are referring to:
> A node, based on the instance type limit, can have up to N ENIs and M addresses. The maximum number of IP addresses available to pods on this node is min((N * (M - 1)), free IPs in the subnet). The -1 is because each ENI uses one of the IPs when it is attached to the instance.

is outdated. There was an issue that describes the behavior mentioned in the documentation, but according to @mogren's comment, it was resolved: https://github.com/aws/amazon-vpc-cni-k8s/issues/102. I just couldn't find the commit/PR that did this change right now. But I think now the maximum number of IPs available to pods is `(N*M)-1`, not `N*(M-1)`. Only the primary IP of the first ENI is used for the host; the primary IPs of the secondary ENIs are available to pods now. So the 29 you have been seeing should be valid.

As for why the primary IP of the primary ENI appears in the `/v1/enis` output: I think this output just contains all the ENIs with all the IPs that are assigned to the instance, independent of whether they are assigned to the host or the pods.

**Comment by evan-lin** [comment]
Thanks for the check, the maximum number of IPs available to pods is (N*M)-1 makes sense to me, only one IP of the primary ENI reserved for the host is enough - this reserved IP should never be added into the pod IP pool and available for pod.

From the ipamd debug info:
[ipamd.log](https://github.com/aws/amazon-vpc-cni-k8s/files/3828551/ipamd.log)
This is the primary ENI, it has 15 IPs, the primary IP **10.29.52.187**
```
2019-11-07T10:00:01.200Z [DEBUG]	Found ENI mac address : 06:7a:5e:5e:c7:94
2019-11-07T10:00:01.201Z [DEBUG]	Using device number 0 for primary eni: eni-03b86b879bb0db73e
2019-11-07T10:00:01.201Z [DEBUG]	Found ENI: eni-03b86b879bb0db73e, MAC 06:7a:5e:5e:c7:94, device 0
2019-11-07T10:00:01.202Z [DEBUG]	Found CIDR 10.29.48.0/20 for ENI 06:7a:5e:5e:c7:94
2019-11-07T10:00:01.202Z [DEBUG]	Found IP addresses [**10.29.52.187** 10.29.59.252 10.29.63.30 10.29.60.89 10.29.57.249 10.29.58.123 10.29.52.219 10.29.48.245 10.29.51.144 10.29.58.78 10.29.51.169 10.29.58.139 10.29.61.11 10.29.57.7 10.29.61.2] on ENI 06:7a:5e:5e:c7:94
```
This is the secondary ENI, it has 15 IPs, the primary IP is **10.29.54.91**
```
2019-11-07T10:00:01.202Z [DEBUG]	Found ENI mac address : 06:97:38:54:71:e4
2019-11-07T10:00:01.203Z [DEBUG]	Found ENI: eni-0fe996904ef6e4a7c, MAC 06:97:38:54:71:e4, device 2
2019-11-07T10:00:01.203Z [DEBUG]	Found CIDR 10.29.48.0/20 for ENI 06:97:38:54:71:e4
2019-11-07T10:00:01.204Z [DEBUG]	Found IP addresses [**10.29.54.91** 10.29.51.125 10.29.62.126 10.29.58.89 10.29.60.152 10.29.53.122 10.29.62.151 10.29.54.54 10.29.56.237 10.29.53.175 10.29.52.235 10.29.50.165 10.29.58.192 10.29.57.99 10.29.51.162] on ENI 06:97:38:54:71:e4
2019-11-07T10:00:01.204Z [DEBUG]	Reconcile existing ENI eni-03b86b879bb0db73e IP pool
```
So the primary IP of primary ENI **10.29.52.187** should never be added into the pod IP pool and available for pod.
Not matter what output is in the /v1/enis/, from the pod.out:
[pod.out.log](https://github.com/aws/amazon-vpc-cni-k8s/files/3828586/pod.out.log)
```
{"aws-pre-msg-hw-service-online-58bf98c46-b6nl2_default_2f0ced6fa1f1b93855b704988b800018fa9d664fc5b9b5134aa7ac0294f7284f":{"IP":"10.29.48.245","DeviceNumber":0},"im-admin-hw-66f799b599-cct29_default_1cd546a33312597167bfcd0d375d444c07391a40a5421e401c96cf232cbfbd2b":{"IP":"10.29.58.78","DeviceNumber":0},"php-aws-os-online-aws-clientresource-5df9cf84bb-gzh6z_default_308e2c7a36b0ee4aa7f9d98caf767f4010b62926b64380500696fb22c772e501":{"IP":"10.29.58.123","DeviceNumber":0},"php-aws-overseas-media-web-7ffc4f554b-8dz7v_default_a9b975c1f5545f2b30ed188dba5d096a370fd3c5868f886f332e05d83a5d1a38":{"IP":"10.29.60.89","DeviceNumber":0},"vendor-push-service-hw-online-5b99fb8bc4-nqpsj_default_d833547263052645f1284a06b096c23057411b44c8615c765a7e55316b3b2634":{"IP":"10.29.52.187","DeviceNumber":0}}
```
The IP **10.29.52.187** is assigned to a pod...
<img width="781" alt="Screen Shot 2019-11-10 at 10 59 09 PM" src="https://user-images.githubusercontent.com/17717672/68546035-c71eec80-040d-11ea-9381-ce1a41fad863.png">

**Comment by devkid** [comment]
And `vendor-push-service-hw-online-5b99fb8bc4-nqpsj` is the pod that has `hostNetwork: true` set? If yes, there is no problem and everything is as expected. If no, then this is weird.

**Comment by devkid** [comment]
Also:
> So the primary IP of primary ENI 10.29.52.187 should never be added into the pod IP pool and available for pod.

The log you posted only states the IPs it found on the ENI, it doesn't state that this IP is added to pool of IPs that are available to pods.

**Comment by evan-lin** [comment]
> And `vendor-push-service-hw-online-5b99fb8bc4-nqpsj` is the pod that has `hostNetwork: true` set? If yes, there is no problem and everything is as expected. If no, then this is weird.

The answer is no, it was created by deployment, so it is weird!

**Comment by evan-lin** [comment]
> Also:
> 
> > So the primary IP of primary ENI 10.29.52.187 should never be added into the pod IP pool and available for pod.
> 
> The log you posted only states the IPs it found on the ENI, it doesn't state that this IP is added to pool of IPs that are available to pods.

From the ipamd.log, I can see the primary IP of primary ENI 10.29.52.187 has been added to datastore - not sure about the datastore concept
```
2019-11-07T10:00:01.204Z [DEBUG]	Reconcile existing ENI eni-03b86b879bb0db73e IP pool
2019-11-07T10:00:01.204Z [DEBUG]	Adding ENI(eni-03b86b879bb0db73e)'s IPv4 address 10.29.52.187 to datastore
```
And in the secondary ENI, I can see the primary IP of secondary ENI has **not** been added to datastore.
```
2019-11-07T10:00:01.204Z [DEBUG]	Reconcile existing ENI eni-0fe996904ef6e4a7c IP pool
2019-11-07T10:00:01.204Z [DEBUG]	Reconcile and skip primary IP 10.29.54.91 on ENI eni-0fe996904ef6e4a7c
2019-11-07T10:00:01.204Z [DEBUG]	Adding ENI(eni-0fe996904ef6e4a7c)'s IPv4 address 10.29.51.125 to datastore
```

**Comment by evan-lin** [comment]
So if we can figure out the issue root cause, that would be great.
And temporally, any ideas about how to remove a specific IP (the host IP) from the pool? I can do the manually check and remove it to prevent the issue.

**Comment by mogren** [comment]
@evan-lin the host IP should definitely not be added to the data_store of IPs available to the pods. Could you please run [the log collector script](https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script) and send the dump to mogren@amazon.com? If not, you can check what is currently in the IP cache by running `curl http://localhost:61679/v1/enis` and `curl http://localhost:61679/v1/pods`

**Comment by evan-lin** [comment]
Hi @mogren , the node has been rebuilt, not sure if the new node can reproduce the issue, if so, I will run the script.
Before the old node was destroyed, I ran script as per https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md
> collecting node level tech-support bundle for offline troubleshooting
`[root@ip-192-168-188-7` aws-routed-eni]# /opt/cni/bin/aws-cni-support.sh 

Please check this log [aws-routed-eni.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/3829811/aws-routed-eni.zip)

**Comment by evan-lin** [comment]
Hi @mogren , do we have a way to remove specific IP from the pool?

**Comment by evan-lin** [comment]
> If not, you can check what is currently in the IP cache by running `curl http://localhost:61679/v1/enis` and `curl http://localhost:61679/v1/pods`

The curl enis results is [curl-enis.log](https://github.com/aws/amazon-vpc-cni-k8s/files/3830599/curl-enis.log)
You can see the primary IP of primary ENI is in the pool.
```
"ENIIPPools": {
        "eni-03b86b879bb0db73e": {
            "AssignedIPv4Addresses": 5,
            "DeviceNumber": 0,
            "ID": "eni-03b86b879bb0db73e",
            "IPv4Addresses": {
                ...
                "10.29.52.187": {
                    "Address": "10.29.52.187",
                    "Assigned": false,
                    "UnassignedTime": "2019-11-07T11:47:16.873649718Z"
                },
               ...

```

**Comment by jaypipes** [comment]
@evan-lin this is really weird. From looking at the code here:

https://github.com/aws/amazon-vpc-cni-k8s/blob/3b4fd504fdcd54d7854cb55e083d669be5bfdc97/ipamd/ipamd.go#L741-L744

there should be no way that the primary IP address should be added to the datastore's list of IP addresses for the primary ENI.

**Comment by evan-lin** [comment]
@jaypipes ya, this is really weird, look like the ec2Addr.Primary is false for 10.29.52.187.
Is it possible it is related to the new G4 instance? Let me build a refresh environment and see if I can reproduce it.

**Comment by mogren** [comment]
@evan-lin Please use `v1.5.5-rc1`, v1.5.4 has a quite bad `ip rule` bug.

**Comment by sxauyhz** [comment]
Today I came across the host IP assigned to the pod, and the pod was deployed with deployment. 
cni version v1.5.4
@mogren

**Comment by mogren** [comment]
@sxauyhz Interesting, I would very much like to see the logs for this node. Also, please update to v1.5.5 to avoid the ip rule bug in v1.5.4 (see #641)

**Comment by sxauyhz** [comment]
10.29.34.40,10.29.32.240 is host primary IP.
![image](https://user-images.githubusercontent.com/10152446/71077476-73e54a00-21c2-11ea-8c65-a52e081acefd.png)
![image](https://user-images.githubusercontent.com/10152446/71077512-86f81a00-21c2-11ea-8fa2-f2d0338c0e3f.png)
You can see the primary IP of primary ENI is in the pool.
```
"eni-04cd60e53a82f52c6": {
            "AssignedIPv4Addresses": 5,
            "DeviceNumber": 0,
            "ID": "eni-04cd60e53a82f52c6",
            "IPv4Addresses": {
                ......
                "10.29.34.198": {
                    "Address": "10.29.34.198",
                    "Assigned": false,
                    "UnassignedTime": "2019-12-18T04:36:25.8286636Z"
                },
                "10.29.34.40": {
                    "Address": "10.29.34.40", 
                    "Assigned": false,
                    "UnassignedTime": "2019-12-18T04:22:33.805556229Z"
                },
               ......
```
From the ipamd debug info,I can see the primary IP of primary ENI 10.29.34.40 has been added to datastore.
[ipamd.log.zip](https://github.com/aws/amazon-vpc-cni-k8s/files/3977905/ipamd.log.zip)


```
ipamd.log.2019-12-18-08:2019-12-18T08:28:37.201Z [DEBUG]	Adding ENI(eni-04cd60e53a82f52c6)'s IPv4 address 10.29.34.40 to datastore
ipamd.log.2019-12-18-08:2019-12-18T08:28:37.201Z [DEBUG]	Reconciled IP 10.29.34.40 on ENI eni-04cd60e53a82f52c6
```

**Comment by devkid** [comment]
@sxauyhz most certainly there is a misunderstanding. Your primary private IP of the host is obviously (only) 10.29.32.240 as this one is attached to the `eth0`. 10.29.34.40 looks like the primary private IP of the second ENI, which is intended to be used as a pod IP. The order of the IPs in the EC2 console seems to be confusing.

**Comment by sxauyhz** [comment]
@devkid 10.29.34.40 is host primary IP, After initializing the machine, the name of the network card is ens5 and the IP is 10.29.34.40. The eth0 network card is automatically generated according to the cni plugin and the IP is 10.29.32.240.

**Comment by mogren** [comment]
Hmm, @sxauyhz, I agree that `10.29.34.40` should not be in the available IP pool since it's the primary IP of the second ENI. Has this ever happened with any other IP? Is it still an issue?

**Comment by sxauyhz** [comment]
@mogren This is the second time I have encountered this situation and it is on a different node. I have now upgraded the version to 1.5.5 and haven't encountered it yet.

**Comment by mogren** [comment]
@sxauyhz Great, thanks for confirming. Can we close this issue now?
