### ISSUE TITLE
Document Development of new Integration Tests

### ISSUE THREAD

**Issue by vipulsabhaya** [aws/amazon-vpc-cni-k8s#715]
Document test writing guidelines for testing new Features.

**Comment by jayanthvn** [comment]
Thanks @vipulsabhaya . We are in the process of updating the integration tests and as part of that approach we will provide the documentation for adding new features. Until then will keep this issue open. Thank you!

**Comment by jayanthvn** [comment]
@abhipth - In the new README let us also add guidelines for onboarding new features.

**Comment by Shreya027** [comment]
Closing issue as it has been addressed.
