### ISSUE TITLE
Can't communicate with k8s service on default EKS install

### ISSUE THREAD

**Issue by jwlogemann** [aws/amazon-vpc-cni-k8s#743]
Hi,
I've deployed EKS 1.14 with 3 worker nodes. I can't deploy any workloads on this cluster because the coredns pods won't start. I'm getting this error: 

E1209 10:21:26.352924       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://172.20.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.20.0.1:443: i/o timeout

Any other pod I start on any of the workers ca't reach 172.20.0.1 either, so nothing works. I've customized the security groups in AWS to allow all traffic from any to any, but this doesn't help. Any thoughts on how to debug this?

**Comment by mogren** [comment]
@jwlogemann Hi, did you apply the `aws-auth` [config map](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html) with the right role ARN?

**Comment by jwlogemann** [comment]
Hi,
I've found the problem. I was running the EKS worker on a custom CentOS image, and some system hardening that was applied by our linux engineers turned out to be causing this problem

**Comment by mogren** [comment]
@jwlogemann Glad you found the cause of the problem, and thanks for closing the ticket. 😄
