### ISSUE TITLE
Question: Secondary ENI routing not working with Ubuntu?

### ISSUE THREAD

**Issue by ryan-dyer-sp** [aws/amazon-vpc-cni-k8s#744]
I am experiencing an issue with our k8s cluster (created via kops) running an ubuntu OS where pods landing on the secondary ENI dont appear to be able to route traffic out appropriately.  AWS support has mentioned: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-ubuntu-secondary-network-interface/

I would have thought this is what the VPC CNI is responsible for (as well as attaching the secondary ENI to the instance in the first place).  Is this not the case?

**Comment by mogren** [comment]
@ryan-dyer-sp Yes, the CNI should set up the routes correctly on Ubuntu as well. Could you run the log collector script and send me the logs?

**Comment by ryan-dyer-sp** [comment]
@mogren emailed to your gmail acct.

**Comment by ddynwzh1992** [comment]
I am the support, weird thing is that, we can see all the traffic (ICMP, DNS)out from pod by packet capture over pod, but we can see nothing in the VPC flow log of this ENI

**Comment by mogren** [comment]
Hey @ryan-dyer-sp, did we get this one resolved?

**Comment by ryan-dyer-sp** [comment]
Yes we tracked down that a new AMI we were using was disabled ipv4 forwarding.  Thanks for the help.
