### ISSUE TITLE
Replace use of (ancient) operator-framework/operator-sdk with kubebuilder

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#745]
**Feature request**

We should remove the dependency on the (ancient) 0.7.0 github.com/operator-framework/operator-sdk code. It is only used for the pkg/eniconfig simple controller for handling the `ENIConfig` CRDs but unfortunately comes with the following disadvantages:

* The version of operator-sdk we import is ancient (Nov 2018) and has an entirely different API than modern versions of the operator-sdk, including the client-go clientcmd helpers
* Transitively includes a huge number of packages, including requiring the host building machine to have mercurial installed
* Updating to a new operator-sdk version would bring in *even more* dependencies, including all the operator-lifecycle-manager and all of its deps, which really are useless for a simple controller
* kubebuilder brings in no unnecessary deps (basically just controller-runtime and client-go)

**Comment by jayanthvn** [comment]
Operator-sdk dependency is removed and 1.8 release is out - https://github.com/aws/amazon-vpc-cni-k8s/pull/1419.
