### ISSUE TITLE
Capture subnet available IPs and expose in CNI metrics helper

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#757]
We do not currently expose per-subnet metrics in the CNI metrics helper. Instead, we only have an aggregate total ENIs/IPs and assigned IPs gauge.

It would be useful to have gauges dimensioned per subnet/ENIConfig instance.

Ref: https://github.com/aws/amazon-vpc-cni-k8s/issues/547#issuecomment-565221534

**Comment by karanmagdani1** [comment]
Thanks for creating this issue @jaypipes. Currently we are using 
`error="InsufficientFreeAddressesInSubnet"` but would be awesome to have per-subnet metrics
