### ISSUE TITLE
Move from TagResources to CreateTags for ENI Tagging

### ISSUE THREAD

**Issue by abeer91** [aws/amazon-vpc-cni-k8s#76]
We should not use TagResources for tagging our ENIs, it's a more powerful API and scoping down permissions is harder.
Code where we use this today - https://github.com/aws/amazon-vpc-cni-k8s/blob/5d6757f6feec42c4fcab42b7467f3d1152675904/pkg/awsutils/awsutils.go#L627

We should be using ec2:CreateTag

There's information available here - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources

**Comment by abeer91** [comment]
The permissions for CreateTag on ENI can be scoped to something like:

```
        {
            "Action": [
                "ec2:CreateTags"
                ],
            "Resource": [
                "arn:aws:ec2:::network-interface/*"
                ],
            "Effect" : "Allow"
        }
```

**Comment by nckturner** [comment]
Right now, it looks like we tag the ENI with `k8s-eni-key=<instance-id>`.  I have a few questions about this implementation. 

1. Shouldn't we add the well known tag `kubernetes.io/<clustername>=<owned|shared>`, as this is, as far as I can find, the standard way to track kubernetes-related resources?
2. Who are the known consumers of this tag?

**Comment by nckturner** [comment]
In order to get the cluster name, we could look for the existence of an env var CLUSTER_NAME or similar, and only create `kubernetes.io/$CLUSTER_NAME=owned` if it exists.

**Comment by liwenwu-amazon** [comment]
@nckturner  great idea if we can also tag ENI with cluster name. 

Today, **k8s-eni-key** can be very helpful for debugging.  If there is a ENI leaking, we can use **k8s-eni-key** to figure out which aws-node's ipamD is leaking it.  Then, we can focus on debugging that particular node's ipamD.

**Comment by nckturner** [comment]
Ok, what do you think about renaming it to something more descriptive?  I was thinking something using a format similar to Kubernetes [well known labels](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/), similar to the cluster name label previously mentioned.  `node.amazonaws.com/instance-id=i-0d8928dd968701ba6` or `node.amazonaws.com/i-0d8928dd968701ba6=owned`.

Referencing [this issue](https://github.com/kubernetes/kubernetes/issues/22058#issuecomment-308026369), the tag `kubernetes.io/<clustername>=<owned|shared>` was chosen as formatted (with the cluster name in the key) for querying efficiency, but we can query by tag:key=value, so I'm not sure where the efficiency gains come from.
