### ISSUE TITLE
aws-k8s-tester v0.4.3 cannot be configured via ENV

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#770]
The `scripts/lib/cluster.sh` file sets overrides for cluster configuration via ENV vars:

However, the `UpdateFromEnv` call that exists in master aws-k8s-tester:

https://github.com/aws/aws-k8s-tester/blob/d0f06f7b98914e6e35c2c7dbfeddbd195df2ba19/cmd/aws-k8s-tester/eks/create.go#L89

does *not* exist for the v0.4.3 binary we [use in the integration test script](https://github.com/aws/amazon-vpc-cni-k8s/blob/6e95ffb481484287c1bdef420d503d7187cf59f8/scripts/run-integration-tests.sh#L31):

https://github.com/aws/aws-k8s-tester/blob/v0.4.3/cmd/aws-k8s-tester/eks/create.go#L54-L82

which means none of the env vars supplied in the `up-cluster` function:

https://github.com/aws/amazon-vpc-cni-k8s/blob/6e95ffb481484287c1bdef420d503d7187cf59f8/scripts/lib/cluster.sh#L14-L25

are actually used.

This took me a lot of head-scratching frustration over the weekend to figure out. :(

The solution is to use an updated aws-k8s-tester binary (UpdateFromEnv was added in 0.5.1) but unfortunately v0.5.1 has other failures for me, notably that v0.5.1 attempts to install the `aws` CLI into a protected directory:

```
failed to create EKS deployer error doing chmod on "/usr/local/bin/aws": chmod /usr/local/bin/aws: operation not permitted
```

Note that I have the `aws` binary already installed and is world-executable:

```
jaypipes@thelio:~/go/src/github.com/aws/amazon-vpc-cni-k8s$ ls -l `which aws`
-rwxr-xr-x 1 root root 815 Jun 28 10:25 /usr/local/bin/aws
```

so I'm not sure why `aws-k8s-tester` is trying to chmod anything.

**Comment by leakingtapan** [comment]
Note that 0.5.x is a backward incompatiable change with regard to 0.4.x. Since 0.4.x has been in pre-alpha so far and incompatible changes are acceptable, we didn't bump the major version.

**Comment by gyuho** [comment]
Sorry for the breaking changes!

As @leakingtapan mentioned, please refer to CHANGELOG. I will take a look CNI test script and see if it uses the old env var. Easiest way is just refer to:

- https://godoc.org/github.com/aws/aws-k8s-tester/eksconfig#pkg-constants
- https://godoc.org/github.com/aws/aws-k8s-tester/eksconfig#Config.UpdateFromEnvs

> so I'm not sure why aws-k8s-tester is trying to chmod anything.

It's trying to make sure `aws` CLI is executable.

**Comment by jaypipes** [comment]
No need to apologize for breaking changes, @gyuho! :) We're all good!
