### ISSUE TITLE
cni-metrics-helper: Replace CLUSTER_ID with eks:cluster-name tag

### ISSUE THREAD

**Issue by groodt** [aws/amazon-vpc-cni-k8s#775]
It seems that the "official" EKS tags applied automatically by EKS node-groups is `eks:cluster-name` and not `CLUSTER_ID` or `Name`.

Would you accept a PR to replace either or both of these values with `eks:cluster-name`?

If not, I believe that cni_metrics_helper is unusable with EKS managed nodegroups as they do not allow custom tags such as `CLUSTER_ID` or `Name` to be propagated to the EC2 instances.

**Comment by mogren** [comment]
@groodt Thanks, sounds like an improvement we should do, and all PRs are welcome. 😄

**Comment by manfredlift** [comment]
Any updates on this? We are considering using managed workers (EKS node groups) instead of unmanaged workers, but this makes the transition difficult if we don't want to give up CNI metrics.

**Comment by groodt** [comment]
Hey @manfredlift 

I haven't had any time to look at this, but hope to soon. I'm also happy if somebody else wishes to pick it up. 

The location in the code is here I believe:
https://github.com/aws/amazon-vpc-cni-k8s/blob/50a1b0c279c731bd0323cc02ceef6ba069d8ea51/pkg/publisher/publisher.go#L87

There is also a chance that EKS allows us to propagate tags to instances in managed node groups in future, so it could also get "fixed" on that end. I think it would be cleaner if the cni-metrics-helper used the "standard" tags though, because then all you need to do is install the CNI plugin and cni metrics helper to an EKS cluster and it should "just" work.

**Comment by mogren** [comment]
Fixed in #856
