### ISSUE TITLE
vpc peering secondary eni pod choud not communicate crossing vpc.

### ISSUE THREAD

**Issue by phantooom** [aws/amazon-vpc-cni-k8s#777]
```
                10.0.53.0/22                  172.16.12.0/22
pod1-eni0----node1---vpc1-------peer----------vpc2----node2--eni0 pod2
                                                           \-eni1 pod3
```

pod1 ping pod2 ok
pod1 ping pod3 failed

becasue of 
1536:   from 172.16.13.174 to 172.16.12.0/22 lookup 2
1536:   from 172.16.13.248 to 172.16.12.0/22 lookup 2
1536:   from 172.16.13.197 to 172.16.12.0/22 lookup 2
1536:   from 172.16.13.145 to 172.16.12.0/22 lookup 2
1536:   from 172.16.13.250 to 172.16.12.0/22 lookup 2

policy route define dst, i think dst shoud not set.

1536:   from 172.16.13.174  lookup 2
1536:   from 172.16.13.248  lookup 2
1536:   from 172.16.13.197  lookup 2
1536:   from 172.16.13.145  lookup 2
1536:   from 172.16.13.250  lookup 2

**Comment by jaypipes** [comment]
This is not a bug, AFAICT. You need to use external SNAT option:

```
AWS_VPC_K8S_CNI_EXTERNALSNAT

Type: Boolean

Default: false

Specifies whether an external NAT gateway should be used to provide SNAT of secondary ENI IP addresses. If set to true, the SNAT iptables rule and off-VPC IP rule are not applied, and these rules are removed if they have already been applied. Disable SNAT if you need to allow inbound communication to your pods from external VPNs, direct connections, and external VPCs, and your pods do not need to access the Internet directly via an Internet Gateway. However, your nodes must be running in a private subnet and connected to the internet through an AWS NAT Gateway or another external NAT device.
```

**Comment by jaypipes** [comment]
@phantooom it may be possible you were running into #737. Please check out that issue and perform one of the two workarounds suggested by @0xlen.
