### ISSUE TITLE
Reduce time to create EKS cluster in integration tests

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#786]
Functionally testing the CNI plugin is cumbersome due to the amount of time that it takes to get the `aws-k8s-tester create cluster` to complete (as well as the amount of time it takes to delete that cluster.

I've noticed that the average time for the `aws-k8s-tester create cluster` command to complete seems to be around 30-35 minutes. However, a good chunk (maybe 10-15 minutes) of this time is actually `aws-k8s-tester` running a series of tests to "warm up" the cluster. These tests create 30 `Job`s spread over the 3 worker nodes. Each `Job` does a simple `echo` and there is a poll collecting how many `Job`s completed successfully.

This warm up test is then repeated for 1000 `Job`s of the same type. This takes around 8 minutes or so.

I think for the purposes of the CNI integration tests, we should be able to do a couple things to speed up the iterative cycle of dev-test:

- [ ] Modify `aws-k8s-tester` configuration to run a smaller set of warm-up `Job`s (see [1][1])
- [ ] Modify `aws-k8s-tester` to allow customized expo-backoff polling timeouts and intervals. The intervals for many polling operations is 1 minute, which means `aws-k8s-tester` is basically just sitting there waiting for a minute at a time checking to see if some CloudFormation stack has had its status shifted to an expected status
- [ ] Handle failures in the image building or setup earlier before the `aws-k8s-tester create cluster` command is even run. This means that iterative dev-test is less cumbersome for tracking down failures in the script itself.

[1]: https://github.com/aws/aws-k8s-tester/blob/a10e56f42ec2db3f6ce38baba6a43526ade1fbf4/eks/eks.go#L379-L400

**Comment by jaypipes** [comment]
For the echo Job stuff, looks like we can configure this to run a smaller set of iterations:

https://github.com/aws/aws-k8s-tester/blob/a10e56f42ec2db3f6ce38baba6a43526ade1fbf4/eks/eks.go#L379-L400

**Comment by jayanthvn** [comment]
@sushrk is working on replacing k8stester with eksctl.

**Comment by jayanthvn** [comment]
#1899 related aws-k8s-tester with eksctl. With eksctl there is a reduction from 30-35 mins to 15-18 mins.
