### ISSUE TITLE
Release notes incorrect link

### ISSUE THREAD

**Issue by sagikazarmark** [aws/amazon-vpc-cni-k8s#791]
For the [latest RC](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.0-rc5) the release notes contains an incorrect link for `Additional tags to ENI`:

```
https://github.com/aws/amazon-vpc-cni-k8s/pull/#734
```

instead of

```
https://github.com/aws/amazon-vpc-cni-k8s/pull/734
```

**Comment by mogren** [comment]
@sagikazarmark Thanks, good catch. Fixed the links.
