### ISSUE TITLE
Verify that IMDSv2 works in host networking

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#793]
The new AWS go SDK uses v2 of the IMDS API, which only allows 1 network hop by default. This causes problems for containers trying to access instance metadata, but we should verify that the CNI works as expected since it is running in the host network namespace.

**Comment by mogren** [comment]
Done

**Comment by jaypipes** [comment]
how is this done? do we have a specific test we're now running in CI? :)

**Comment by mogren** [comment]
Was a manual test. If this call to the metadata fails, the logs will show it.
