### ISSUE TITLE
1.6.0-rc5 causes "checking for IPAM connectivity ...  failed." error on startup

### ISSUE THREAD

**Issue by druidsbane** [aws/amazon-vpc-cni-k8s#798]
It appears that the latest release candidate for 1.6.0-rc5 is broken for us with the following error: "checking for IPAM connectivity ...  failed."  We use a proxy (HTTP/HTTPS) as part of our configuration and add that to our `env` variables.  Otherwise all previous versions work fine except for that one.  We are using on an EKS 1.4.x cluster on a private VPC.

**Comment by mogren** [comment]
@druidsbane We added a dependency on the dockershim.sock in rc5. Could that be the cause, in the case that you just bumped the image version from -rc4 to -rc5?

https://github.com/aws/amazon-vpc-cni-k8s/blob/8eac2e4f2552637a1eb5d4dab835553a43465dc3/config/v1.6/aws-k8s-cni.yaml#L123-L140

**Comment by druidsbane** [comment]
@mogren thanks.  I deleted the old `DaemonSet` and created a new deployment.  Unfortunately I only had 3 lines in the output, that one above being the key one before the pod entered its next restart.

**Comment by mogren** [comment]
@druidsbane If that was the cause, I agree that we could have better logging around the issue, and also improve our docks. See #689
