### ISSUE TITLE
Add polling to check that all pods have been updated

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#801]
Poll after DS update to verify that the pod spec has the new image and the pods are in Running state.

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/run-integration-tests.sh#L114

**Comment by jaypipes** [comment]
Furthermore, we talked about running some smoke tests *before* `kubectl apply`ing the CNI DS artifact representing the CNI image we wish to test in order to get a full "upgrade scenario test".

**Comment by mogren** [comment]
Running a smoke test before updating was added in #826, and waiting added in #1076
