### ISSUE TITLE
e2e test for custom ENIConfig

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#804]
Need to add functional tests that validate creating an ENIConfig CRD instance.

- [x] test for specifying ENIConfig for new worker node (with no pods)
- [ ] test for adding ENIConfig to an existing worker node that has pods running on it (and have IPs on the primary ENI)

**Comment by jaypipes** [comment]
related: https://github.com/awsdocs/amazon-eks-user-guide/pull/72

**Comment by jayanthvn** [comment]
First step towards adding these testcases - #1373

**Comment by jayanthvn** [comment]
Testcase for the below scenario is added - 

```
- Follow this guide to start custom networking - https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html
- Verify seconday ENI attached belong to subnet specified in ENI Config
- Verify new pods get IP from the subnet in ENIConfig
--
- Repeat above test but with creating an ENI Config with name other than the subnet
- Set the variable to ENI Config name ame as label annotation

```
