### ISSUE TITLE
e2e test for mixed pods host-network true and false with external SNATing

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#816]
Refer #519 

We believe that pods with `hostNetwork: true` cause the CNI `add` API call to be bypassed, which means that the VPC CNI would not affect the data path at all for those pods. However, we should create and e2e scenario that tests the situation where, for example, an AWS VPC NAT Gateway is being used (and SNAT'ing traffic from pods on a particular subnet) and a worker node houses pods that have hostNetwork: true along with pods that do NOT have hostNetwork: true and ensure outbound communication works for both kinds of pods.

**Comment by jayanthvn** [comment]
We have added the test case for non-host networking pods. Will be extending that for host networking pods to complete the request in this issue.
