### ISSUE TITLE
Configurable reconcile timeout for ipamd

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#817]
Currently the reconcile loop for the CNI runs too often in large clusters. We should make it possible to change these settings, either based on number of nodes in the cluster, or as an environment variable to override the default setting.

**Comment by mogren** [comment]
Checking local metadata should be fine. The calls to EC2 have been reduced in #909

**Comment by jayanthvn** [comment]
Waiting for #1280 PR review.

**Comment by jayanthvn** [comment]
Closing the issue for now, will wait for PR to address the comments.
