### ISSUE TITLE
Incompatible with Hypervisor-based CRIs (hyperd/frakti)

### ISSUE THREAD

**Issue by cjbradfield** [aws/amazon-vpc-cni-k8s#82]
So, played around with running hypervisor-based containers on EKS+i3-metal with the aws-cni. The containers come up fine, but relying on the static-arp / network namespace solution doesn't seem to work when the pod is in a hypervisor.

Perhaps using a vbridge with port-isolating etables rules could work? Then I think arp just works for the gateway without a static entry.

**Comment by dbenhur** [comment]
Thanks for reporting this, Chris.  We have not been testing or targeting metal instances to date; clearly there's some work to do.  This will not be fixed before GA, but we'll put it on our backlog to figure out.  If you find a workable solution please let us know.

**Comment by liwenwu-amazon** [comment]
@cjbradfield  can you provide a yaml file for ***hypervisor-based*** container?  I have launched some simple busybox workloads on i3.x16xlarge, they are able to communicate to each other and externally, thanks

**Comment by cjbradfield** [comment]
@liwenwu-amazon You need to follow the directions on [](https://github.com/kubernetes/frakti). In order to run your own hypervisor containers, you will have to run on i3.metal as EC2 does not support nested virtualization.

**Comment by cjbradfield** [comment]
Link didn't show up: [https://github.com/kubernetes/frakti](url)

**Comment by vsiddharth** [comment]
@cjbradfield Could you please provide additional details on what use-case you are planning to solve? Any details on the observed incompatibilities would help us dig into this further.

**Comment by cjbradfield** [comment]
@vsiddharth This has been a while, but when @liwenwu-amazon and I looked at it a bit, it appeared that some of the static arp/veth routing wasn't working with there was a bridge configured in between you and the container (in this case, a vm-container).

The high-level use case is to use vm-based containers with EKS. EKS customers may have untrusted code that they want to run multi-tenant to a bare metal node. A lot has changed in this space since I wrote this issue and I don't know the state-of-the-art today. I know frakti was moving to kata-containers and kata-containers uses either cri-o or containerd as an alternative CRI to spin up a VM using QEMU or (supposedly now supported) Firecracker.

Regardless, what I was seeing back then was a bridge device was created and the host-side of the virt_io interface from the VM to the bridge as well as the container side of the veth pair were attached to it. This process worked just fine for other open-sourced CNIs such as calico on bare K8s, but would not work on EKS's CNI. I suspect it has something to do with your CNI relying on a static arp entry or something small like that.

**Comment by jaypipes** [comment]
As of CNI v1.6, we support non-Docker runtimes like containerd and cri-o. I think we'd want to revisit/re-open this issue after investigating whether a modern k8s/CNI plugin combo still doesn't satisfy the use cases described here, @cjbradfield. Closing this out.

**Comment by coderplay** [comment]
It's still the case from my side,   the CNI doesn't work with kata container runtime which is hypervisor based.
