### ISSUE TITLE
Using IAM roles for service accounts for CNI daemonset causes issues

### ISSUE THREAD

**Issue by niroowns** [aws/amazon-vpc-cni-k8s#831]
Hi,

Background:
We're facing an issue while upgrading from 1.12 to 1.13.  As part of the upgrade process, the CNI version within our automation is also updated.  1.12 is mapped to v1.5.3 of the CNI and 1.13 is mapped to v1.5.5. of the CNI.  During this particular upgrade, we are also making use of the service account to IAM features that are included in 1.13 via the pod identity webhook by explicitly setting the aws-node daemonset to use a specific role.

Details:
During the upgrade process
1) We upgrade the control plane to 1.13 from 1.12
2) We create a new IAM role specifically for the aws-node daemeonset
3) We then patch the existing aws-node service account with an annotation specifying said role
4)  Subsequently, we end up patching the daemonset to version v1.5.5.  
5) We then join new nodes to the cluster (these new nodes do NOT have the ENI policy attached anymore as the CNI pod directly should have this role only)

For all new nodes and their corresponding CNI (aws-node pod), we are noticing that they do NOT initially have the AWS_ROLE_ARN injection occurring on them by the pod identity webhook.  This causes the CNI pod to be unable to assume the appropriate policies to get ip addresses.  This leaves a ton of pods in a "Container Creating" state.  The fix usually is just to delete the newly created CNI pod and the new one that comes up does properly have the injected role.

Why do we even need to delete/re-start the pod? I would assume that the mutating webhook injection that is occurring should handle this for us as long as we have already upgraded the control plane to 1.13 first (which we did).

**Comment by mogren** [comment]
Hi @niroowns! Thanks for the detailed issue. The steps you list sounds like they should work, and the webhook should update the CNI pods correctly. We will have to try and reproduce this issue.

**Comment by mogren** [comment]
@niroowns Did you see this happening on any newer kubernetes versions? We did have an issue with IRSA when upgrading from 1.12.

**Comment by niroowns** [comment]
@mogren - haven't seen it occur more recently.  Can you speak to the IRSA issue?

**Comment by mogren** [comment]
@niroowns If I recall correctly, there was a specific case where if you had a 1.11 cluster updated to 1.12, then added an IAM roles for service accounts to the cluster, then updating again to 1.13, some component was not enabled correctly. I wasn't involved with that ticket, just remember something like that being mentioned. If you haven't seen this with any other version, can we resolve this issue?

**Comment by niroowns** [comment]
Thanks @mogren - this helps, please proceed to close out the issue.
