### ISSUE TITLE
priorityClassName change missing from some releases/branches

### ISSUE THREAD

**Issue by edmorley** [aws/amazon-vpc-cni-k8s#834]
Hi!

In #498 a change was made from the deprecated `scheduler.alpha.kubernetes.io/critical-pod: ''` annotation to the new `priorityClassName` feature.

This change is present on these branch/file combinations:

https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.1/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.3/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.4/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.5/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.6/config/v1.5/calico.yaml

But missing from these:

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.6/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.6/config/v1.5/calico.yaml
https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.6/config/v1.6/calico.yaml

**Comment by mogren** [comment]
@edmorley Thanks for pointing out the issue! The original PR was wrongly merged into the release branch instead of master, then cherry picked out to the branch.
