### ISSUE TITLE
Example ClusterRole is unnecessarily permissive

### ISSUE THREAD

**Issue by rifelpet** [aws/amazon-vpc-cni-k8s#846]
The example ClusterRole contains wildcards:

https://github.com/aws/amazon-vpc-cni-k8s/blob/61c8d18c0e097c0b7e8477e1afc61d6f2601295d/config/v1.6/aws-k8s-cni.yaml#L7-L13

Following the principle of least privilege, It would be great if those were enumerated to reduce the permissions as much possible.

**Comment by mogren** [comment]
Resolved in #972
