### ISSUE TITLE
Pass role arn for e2e test through env variable

### ISSUE THREAD

**Issue by SaranBalaji90** [aws/amazon-vpc-cni-k8s#858]
As part of https://github.com/aws/amazon-vpc-cni-k8s/pull/844/files we hardcoded roleArn inside our repo. This makes running these tests difficult outside our cni repo. We should pass both ROLE_ARN and ROLE_CREATE parameter through env variable.

**Comment by DrFaust92** [comment]
Hey, willing to give this a shot.

should it be done for both `AWS_K8S_TESTER_EKS_PARAMETERS_*` and `AWS_K8S_TESTER_EKS_ADD_ON_MANAGED_NODE_GROUPS_` parameters?

**Comment by SaranBalaji90** [comment]
Thank you @DrFaust92. You are right, it should be done for both.

**Comment by mogren** [comment]
Resolved and merged!
