### ISSUE TITLE
Splitting overlay network in subnets

### ISSUE THREAD

**Issue by marcusschiesser** [aws/amazon-vpc-cni-k8s#87]
To my knowledge GKE and AKS do both split the K8S overlay network in subnets. Each subnet contains just the pods of one node. In VPC however it looks like pod IPs are overlapping. Is there any way to split the network per node?

We need this to identify whether pod-to-pod traffic is going from one node to another. Querying the k8s API is not an option for performance reasons.

**Comment by dbenhur** [comment]
You could certainly make a bunch of subnets and place your nodes one per subnet but I'm not convinced that's a lovely idea. https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html Note there is a limit of [200 subnets/VPC](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-vpcs-subnets)

You can figure out if traffic is intra- or inter- node by querying EC2 on the IP addrs and seeing if they're associated with the same instance, though that has perf impact too.

The CNI's IPAM daemon [exposes info on node's ENIs and pods](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md#ipamd-debugging-commands) via  localhost:61678.  You could fetch that and see if your source|dest is on the same node from the ip addrs listed.  I would note this info is intended for debugging inspection and not a formal contract, but you can see the interface paths are versioned, so there's some intent not to break em.

**Comment by liwenwu-amazon** [comment]
You could also do following: 
* write your own external ENI Controller/Operator which can allocate ENI with different subnets/security groups according to your business logic and attach them to node. 
* scope down node's IAM policy so that ipamD will NOT allocate ENI and IP addresses
* ipamD will discover the ENIs and IPs allocated by external ENI Controller/Operator and use them to Pods

**Comment by liwenwu-amazon** [comment]
This can be accomplished with #131 .  In another word, each node has its own pod CIDR (subnet).  Please continue discussion on #131
