### ISSUE TITLE
Manifest for Calico is missing environment variable to disable RPF check

### ISSUE THREAD

**Issue by jicowan** [aws/amazon-vpc-cni-k8s#876]
Need to add the following environment variable to the calico-node daemonset if installed onto a [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket) host otherwise it will continually fail/restart. 

See https://github.com/kubernetes-sigs/kind/issues/891. 

`FELIX_IGNORELOOSERPF=true`

**Comment by mogren** [comment]
@jicowan Sorry for the late reply. Is this still an issue on Bottlerocket? If so, we should just add the `FELIX_IGNORELOOSERPF` parameter.

**Comment by jayanthvn** [comment]
Hi @jicowan 

Can you please confirm if this issue still exists with bottlerocket?

**Comment by jayanthvn** [comment]
Hi @jicowan , Closing this issue for now. Kindly reopen if the issue persists.
