### ISSUE TITLE
aws-k8s-tester 0.8.9 fails all test runs

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#880]
https://github.com/aws/amazon-vpc-cni-k8s/commit/28f27855306f8af123301df221e80a1ee24b305b

introduced a new version of aws-k8s-tester (bumped from 0.7.1 to 0.8.9)

We have not had a successful test run since. We need to revert the above commit and re-test.

**Comment by SaranBalaji90** [comment]
But wondering how did the PR tests succeeded though https://app.circleci.com/pipelines/github/aws/amazon-vpc-cni-k8s/219/workflows/4aab6051-94ad-4710-8965-51d9e5b2a70f/jobs/429

**Comment by jaypipes** [comment]
Addressed in #878

**Comment by jaypipes** [comment]
> But wondering how did the PR tests succeeded though https://app.circleci.com/pipelines/github/aws/amazon-vpc-cni-k8s/219/workflows/4aab6051-94ad-4710-8965-51d9e5b2a70f/jobs/429

Because it was functionality that MNG team pushed out in that broke aws-k8s-tester in between the time that 0.8.5 was released and the time 28f2785 landed.
