### ISSUE TITLE
Base image requires iptables version 1.6 or later to support AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng 

### ISSUE THREAD

**Issue by kishorj** [aws/amazon-vpc-cni-k8s#882]
The current base image includes iptables v1.4.21. The iptables package needs to be updated to at least v 1.6 to support the to support AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng  feature.

**Comment by mogren** [comment]
Related to #662 and #509

**Comment by mogren** [comment]
Available in v1.5.7 and later
