### ISSUE TITLE
Excessive DescribeNetworkInterfaces AWS API calls

### ISSUE THREAD

**Issue by jbnjohnathan** [aws/amazon-vpc-cni-k8s#887]
We have a AWS account where we have one EKS cluster. The cluster has about 7 nodes.
We are using amazon-k8s-cni:v1.6.0
The cluster has about 100 pods in total.

Before we had 4 more clusters in the same account and started getting Throttle issues from AWS API.
I imported API calls metrics into CloudWatch and found that something was consistently making around 500 calls DescribeNetworkInterfaces per 5 minutes.
When we deleted 4 clusters this number dropped to about 80-100.
Again, that is only DescribeNetworkInterfaces.
I can see from the CloudTrail that it is coming from our EKS clusters.

A saw that there was an issue open for reducing the amount of calls (https://github.com/aws/amazon-vpc-cni-k8s/issues/873)
I don't have data further back so I cannot say, but I perceive this problem of Throttling to start after we upgraded the CNI plugin from 1.5.5 to 1.6.0

I find the number of API calls excessive since they are at a constant level even when no new deploys to the cluster is ongoing.

With 1.6.0 we have also seen this in the event log
`
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7e3f4bcf7367353f7ec38373c8055a4a3d3ffaf224384351ae0997b06cfc3f87" network for pod "prometheus-stateful-set-v3-0": NetworkPlugin cni failed to set up pod "prometheus-stateful-set-v3-0_scheduled-system-test" network: add cmd: failed to assign an IP address to container
`

Before I finished writing this ticket I downgraded from 1.6.0 to 1.5.5 and saw a dramatic drop of DescribeNetworkInterfaces from 100 per 5min to between 0-1. (zero - one).

So something big changed between 1.5.5 and 1.6.0 in regard to this behavior.

**Comment by jbnjohnathan** [comment]
An update. I just now noticed that there was a note in the 1.6.0 release notes about 
`
Note! If you edit an existing aws-node deployment, make sure to mount /var/run/dockershim.sock correctly!
`

We did not do this. Can this be the cause of this issue?

**Comment by jbnjohnathan** [comment]
We re-deployed with the /var/run/dockershim.sock mounted and using 1.6.0 but we still saw a big increase in DescribeNetworkInterfaces compared with 1.5.5

**Comment by mogren** [comment]
Thanks @jbnjohnathan, we will look into this. Right now the prime suspect is a change done in the PR [Add support for a 'no manage' tag #726](https://github.com/aws/amazon-vpc-cni-k8s/pull/726/files#diff-662503808113183f6eee8c0fbbf5c2f2R449-R452) that will cause one extra call for every call to `getENIMetadata()`

**Comment by mogren** [comment]
Fixed in v1.6.1
