### ISSUE TITLE
How to implement Pods IP Range (Service IP Range) different for different cluster?

### ISSUE THREAD

**Issue by johnzheng1975** [aws/amazon-vpc-cni-k8s#889]
How to implement Pods IP Range (Service IP Range) different for different cluster?

For EKS, seems cannot assign pods ip range/ service ip range, like below:
```
# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18
```

However, if I want to set up multi-clusters on eks: 
http://docs.cilium.io/en/stable/gettingstarted/clustermesh/#prerequisites 
https://istio.io/docs/setup/install/multicluster/shared/#prerequisites 
The pre-condition is: 
PodCIDR ranges in all clusters must be non-conflicting.

So, I have two questions:
1  Do aws vpc cni support different pod/ service ip range?
2  Can aws eks install aws vpc cni?
3  Can I install both aws vpc cni and cilium network plugin?

Thanks a lot.

**Comment by mogren** [comment]
Hi @johnzheng1975, if you use the AWS VPC CNI, which is the default CNI for EKS, the IP range is controlled by the CIDRs in the VPC where the cluster is running. Running multiple clusters in the same VPC should not be an issue. If you want to use Cilium as the CNI, you need to delete the `aws-node` daemonset first, then apply the Cilium one. Note! Don't do this in a cluster with worker nodes and pods, but before worker nodes are added. (Or terminate all worker nodes after doing the change.)

**Comment by johnzheng1975** [comment]
Thanks Mogren.
I find cilium can combine with AWS VPC Ini, FYI
helm3 template cilium   --namespace kube-system   --version 1.6.8    **--set global.cni.chainingMode=aws-cni**   --set global.masquerade=false   --set global.tunnel=disabled   --set global.nodeinit.enabled=true   > cilium.yaml
