### ISSUE TITLE
Missing permissions on AmazonEKS_CNI_Policy

### ISSUE THREAD

**Issue by mogggggg** [aws/amazon-vpc-cni-k8s#891]
Hi guys,
I'm not sure if this is the right place to raise this, but I noticed that the permissions in the IAM policy `AmazonEKS_CNI_Policy` are missing `ec2:DescribeInstanceTypes`.

This looks to have been added here: https://github.com/aws/amazon-vpc-cni-k8s/pull/797

Thanks!

**Comment by mogren** [comment]
Hi @mogggggg, good find! That is correct, and I'm waiting for the update to the managed policy to get approved, it has been pending for months. This permission should not be needed unless a new instance type gets added that we don't yet have the ENI and IP limits for. Hopefully it will get approved before that happens.

**Comment by mogren** [comment]
The managed policy has been updated. Thanks for noticing!
