### ISSUE TITLE
Lack of IPv6 in CNI

### ISSUE THREAD

**Issue by ffrediani** [aws/amazon-vpc-cni-k8s#893]
Why there is still no IPv6 support for CNI Plugin ? How come in 2020 this is still not implemented and left behind this way ?

Actually how is it acceptable a new product/feature come up these day and IPv6 be neglected this way and treated as if it was something "cosmetic" ?

The lack of IPv6 in CNI leaves behind a lot of opportunities to have IPv6 operational on a lot of hosted content and other scenarios. This increases the chicken-and-egg problem of "I will not deploy IPv6 because there is not much stuff available in IPv6 (not true actually)", but gives people more food to keep sweeping it under the carpet.
Example should be given by those who build new products and IPv6 should be implemented as higher priority, even over non urgent bugs.

Please add IPv6 support to it soon so people can carry on work on other layers and thing can evolve as they should.

**Comment by DanielDamito** [comment]
I agree to all the points mentioned by @ffrediani . 

I have a very important service which blames CNI as responsible for IPV6's lack. 
This is not a single or a isolated problem: it affects all the market chain.

**Comment by pontara** [comment]
It is clear why universities do not emphasize the protocol, when it is not present in "last generation" products.
It turns out that this becomes an endless loop. The product does not have the protocol and therefore teachers do not know it, who in turn do not teach it.

**Comment by jrcorazza** [comment]
I agree with the points of the @ffrediani 

IPv6 is very important for the internet, it cannot be left until after. As everything I use needs to support ipv6, I cannot use the plugin.

If you can add this feature, I would be grateful.

**Comment by andrediashexa** [comment]
I agree with the points of the @ffrediani too.

The actual internet protocol is, infact, the version 6, and we must use it.

**Comment by caiot5** [comment]
I agree with the points of the @ffrediani aswell

I guess a project maintained by Amazon, given its relevance to the global internet scenario should always keep in their roadmap a highlight for IPv6 implementation and I cannot think in a reason why this is not the default behavior.

**Comment by mikestef9** [comment]
Hey all, we are actively researching IPv6 across all of EKS, and looking for your feedback. Please leave your feedback on the issue on the containers roadmap https://github.com/aws/containers-roadmap/issues/835

**Comment by ffrediani** [comment]
Hello @mikestef9 thanks for getting back.
Researching seems something still far way to something that should already been there fore day zero. Hopefully it won't take that much longer.

**Comment by astrived** [comment]
@ffrediani It is actively being planned for @mikestef9 is soliciting inputs on the aws/containers-roadmap#835 so that we get more traction and support from individuals such as you.

**Comment by jayanthvn** [comment]
Hi,

IPv6 effort is actively tracked here - https://github.com/aws/containers-roadmap/issues/835. Hence closing this issue for now.

Thank you!
