### ISSUE TITLE
Installation via Kops

### ISSUE THREAD

**Issue by stevenpall** [aws/amazon-vpc-cni-k8s#9]
Given that Kops is currently one of the main Kubernetes installation method on AWS, it would be nice to know how to go about installing this plugin (if it's possible). From what I can tell, only a select list of CNI plugins are currently installable out of the box. I'm wondering if it's possible to manually set the kubelet flags specified in the docs. Deploying the daemonset and adding additional permissions to the role ARN should be trivial. 

Thanks!

**Comment by liwenwu-amazon** [comment]
Here are manual steps I have used to run Kops with this CNI:

* Create a cluster using  **--networking cni**
```
for example:
kops create cluster --networking cni
``` 
* **Modify node's IAM role Policy**
```
for example: modify nodes.<cluster-name>.<dns-name>.com to include following IAM polices
{
     "Effect": "Allow",
     "Action": [
         "ec2:CreateNetworkInterface",
         "ec2:AttachNetworkInterface",
         "ec2:DeleteNetworkInterface",
         "ec2:DetachNetworkInterface",
         "ec2:DescribeNetworkInterfaces",
         “ec2:DescribeInstances”,
         “ec2:ModifyNetworkInterfaceAttribute”,
         "ec2:AssignPrivateIpAddresses"
     ],  
     "Resource": [
         "*" 
     ]   
 },
 {
     "Effect": "Allow",
     "Action": "tag:TagResources",
     "Resource": "*" 
 },
```
* Manually bring master node into **ready** state: 
    * scp **./misc/aws.conf** to directory **/etc/cni/net.d/** on the master node
    * scp CNI binary **aws-cni** to directory **/opt/cni/bin** on the master node
        * you can generate CNI binary **aws-cni** by running **make static** at top level

* Install daemon set
```
kubectl create -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/misc/aws-k8s-cni.yaml
```
Please let me know if this works for you.

**Comment by chrislovecnm** [comment]
We have a PR for this, bit it will be in 1.8.1 or later release. https://github.com/kubernetes/kops/pull/3997 

@arun-gupta is the plugin production ready?

**Comment by chrislovecnm** [comment]
Let me be more clear, can someone at AWS check to see if that plugin is production ready ;)

**Comment by vedit** [comment]
@chrislovecnm In main readme it says it is alpha and shouldn't be used for production

**Comment by stevenpall** [comment]
kubernetes/kops#3997 has been merged in. Thanks!
