### ISSUE TITLE
Timeouts after upgrading EKS from 1.14 to 1.15

### ISSUE THREAD

**Issue by dza89** [aws/amazon-vpc-cni-k8s#906]
After updating my cluster from 1.14 to 1.15 I'm seeing timeouts towards to kube-api for approximately 15 minutes. After 15 minutes, it resolves itself.

`aws-node-z4dp6 aws-node ERROR: logging before flag.Parse: E0407 11:05:38.668447 9 memcache.go:138] couldn't get current server API group list; will keep using cached value. (Get https://172.20.0.1:443/api?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers))`

I'm suspecting an issue with the CNI but I'm not sure. 

I'm following the AWS' upgrading guide, CNI, kubeproxy and coredns are on the recommended versions. 
I've added CNI support script logging from before (114) and after the upgrade.(115)
I've added EKS support logging from before (0937), during timeouts (1005) and after timeouts. (1018)

[aws-route-eni-114.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/4460363/aws-route-eni-114.tar.gz)
[aws-routed-eni-115-1.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/4460364/aws-routed-eni-115-1.tar.gz)
[eks_i-06fef35f47d951797_2020-04-08_0937-UTC_0.6.1.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/4460365/eks_i-06fef35f47d951797_2020-04-08_0937-UTC_0.6.1.tar.gz)
[eks_i-06fef35f47d951797_2020-04-08_1018-UTC_0.6.1.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/4460366/eks_i-06fef35f47d951797_2020-04-08_1018-UTC_0.6.1.tar.gz)
[eks_i-06fef35f47d951797_2020-04-08_1005-UTC_0.6.1.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/4460367/eks_i-06fef35f47d951797_2020-04-08_1005-UTC_0.6.1.tar.gz)

**Comment by mogren** [comment]
Thanks @dza89, I will take a look at the logs. Most likely this is caused by an excessive number of calls to the EC2 API. It is partly caused by the CNI, but mostly because calls made by the authenticator and signer when the worker nodes registers with the new masters. We are working on ways to mitigate these issues.

**Comment by SaranBalaji90** [comment]
@dza89 did you upgrade both your master and worker nodes? or just the master nodes? since you mentioned you noticed this for 15 mins, I'm thinking if DNS caching has anything to play here (because using cached IP will not help as apiserver would not be running on that IP anymore)

**Comment by dza89** [comment]
@SaranBalaji90 I've done multiple upgrades runs, seeing the same issue with new nodes as well. Happy to try anything if you have any ideas.

**Comment by imranismail** [comment]
We're facing this issue as well

**Comment by mogren** [comment]
We have seen some issues with the dockershim.sock, that we are still investigating.

**Comment by mogren** [comment]
@imranismail and @dza89, I looked at the attached logs and could not see any issues with the CNI. The "logging before flags" issue is a known problem with an old dependency, see #976 

Is it always a 15 minutes time-out? This gRPC issue https://github.com/grpc/grpc/pull/15983 is probably too old, but we have seen TCP timeout issues with older clusters, similar to what is described in [this blog post](https://www.hostedgraphite.com/blog/deadlines-lies-and-videotape-the-tale-of-a-grpc-bug). The next guess would be to try and figure out if there is any DNS cache for the API server endpoint that doesn't get updated.

**Comment by mogren** [comment]
@imranismail @dza89 If you still think this was a CNI issue and not caused by issues on the node or the API server, please open a new ticket with some more detailed information.
