### ISSUE TITLE
Need Continuous integration set up

### ISSUE THREAD

**Issue by liwenwu-amazon** [aws/amazon-vpc-cni-k8s#91]
Whenever there is a PR,  **Continuous Integration** should get kick off automatically:

* compile and generate binary and docker image
* run **make unit-test** 
* run **end-to-end** function tests, such as
   * kubernetes e2e network related tests

**Comment by igorvpcleao** [comment]
@liwenwu-amazon, do you still need help on this?
Did https://github.com/aws/amazon-vpc-cni-k8s/pull/116 solve this issue?

**Comment by liwenwu-amazon** [comment]
@igorvpcleao  #116 only solves portion of the problem.  The next step is to figure out how to automatically trigger kubernetes e2e network related test or conformance test upon every PR or code commit.

**Comment by jaypipes** [comment]
We've got the [test-automation project](https://github.com/aws/amazon-vpc-cni-k8s/projects/2) with a bunch of issues tracking testing and CI. Closing this one out.
