### ISSUE TITLE
Include PSP that supports the CNI in the deployment YAML

### ISSUE THREAD

**Issue by avenging** [aws/amazon-vpc-cni-k8s#911]
In EKS 1.13 clusters and above there is a default PSP installed (eks.privileged) which, as the AWS documentation puts it, "has no restriction on what kind of pod can be accepted into the system, which is equivalent to running Kubernetes with the PodSecurityPolicy controller disabled."

Obviously anyone who wants to harden they K8S cluster will probably want to remove this PSP as is described in the AWS documentation: https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy.html

Removing this PSP without replacing it with something that supports the aws-node pods causes failure of the pods to schedule if they re-start or a new node is introduced causing complete cluster failure.

I believe the CNI deployment files should include a PSP specifically supporting the aws-node deployment separate of the eks.privileged PSP so that cluster admins don't have to work out the precise requirements for the CNI. Either that or there should be some additional documentation (warnings) for the CNI discussing what the requirements for the PSP are if you choose to remove the default eks.privileged PSP from an EKS cluster.

**Comment by jayanthvn** [comment]
Hi @avenging 

The request is tracked here - https://github.com/aws/containers-roadmap/issues/1048. Updates will be posted there. So closing this issue.

Thank you!
