### ISSUE TITLE
error pulling image configuration: error parsing HTTP 403 response body

### ISSUE THREAD

**Issue by AVKarelin** [aws/amazon-vpc-cni-k8s#917]
Hi there
I have a new cluster in eu-central-1 region. Cluster and Node group created in AWS Console.
Kubernetes version: 1.15

I try to create Managed Node Groups.
AMI typeInfo: AL2_x86_64
AMI release versionInfo: 1.15.10-20200228
IAM role has AmazonEC2ContainerRegistryReadOnly policy and this role attached to the instance.
After creating I get Health issues: NodeCreationFailure - Instances failed to join the kubernetes cluster.
"kubectl get nodes " shows status "not ready" for this node.
"kubectl -n kube-system describe pods aws-node-cp7ch" shows
`Warning  FailedCreatePodSandBox  12m                  kubelet, ip-10-0-11-197.eu-central-1.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>737684B48CCF79B7</RequestId><HostId>JAx/qlsW5sKuQ6VzR1rcVQODYxIy0ygfNe3omDZLxU6OlKHxWZvzw1Jto+yNscBnbaYnHvaHSu0=</HostId></Error>"
`
In aws node daemonset - image: 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni:v1.5.7

**Comment by abhipth** [comment]
@AVKarelin since you have all the required permissions to ECR repository and the the image link is valid, the node should be able to pull that image. 

I found [similar issue](https://forums.aws.amazon.com/thread.jspa?messageID=914128) due to user attaching VPC endpoint to S3 services, can you confirm that you don't have a VPC Endpoint?

**Comment by AVKarelin** [comment]
My bad. I have VPC Endpoint to S3 services. I fixed the policy. Thank you very much!

**Comment by akanshgupta** [comment]
> My bad. I have VPC Endpoint to S3 services. I fixed the policy. Thank you very much!

@AVKarelin can you please provide what policy you used to resolve the above issue.

**Comment by AVKarelin** [comment]
> > My bad. I have VPC Endpoint to S3 services. I fixed the policy. Thank you very much!
> 
> @AVKarelin can you please provide what policy you used to resolve the above issue.

`            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "*"
`

**Comment by akanshgupta** [comment]
> > > My bad. I have VPC Endpoint to S3 services. I fixed the policy. Thank you very much!
> > 
> > 
> > @AVKarelin can you please provide what policy you used to resolve the above issue.
> 
> ` "Effect": "Allow", "Principal": "*", "Action": "s3:*", "Resource": "*"`

ok got it, thanks.
