### ISSUE TITLE
unable to pull image in eu-west-1

### ISSUE THREAD

**Issue by Deshke** [aws/amazon-vpc-cni-k8s#924]
similar to https://github.com/aws/amazon-vpc-cni-k8s/issues/334 

![image](https://user-images.githubusercontent.com/1473225/80093065-21e37500-8564-11ea-8689-52b250e73f5b.png)

seems like all vpc-cni images are currently not reachable, tested with amzn2-ami-hvm-2.0.20200406.0-x86_64-gp2 , ubuntu 18.04 and coreOS

**Comment by mogren** [comment]
@Deshke Hi,

From the screenshot you are pulling from Oregon, `us-west-2`. Full path:
`602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1`

What is the output of `aws sts get-caller-identity`?

**Comment by Deshke** [comment]
irrelevant, the kubernetes cluster is running with kops without eks

```
aws sts get-caller-identity
{
    "Account": "xxxx",
    "UserId": "xxxx:i-xxxxxx",
    "Arn": "arn:aws:sts::xxxxxx:assumed-role/xxxxxxx/i-xxxxxxx"
}

```

**Comment by Deshke** [comment]
@mogren to replicate, start a ec2 instance in eu-west-1 with or without iam permissions and try to pull any version, all return  `no basic auth credentials`

```
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1
Error response from daemon: Get https://602401143452.dkr.ecr.us-west-2.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.6.1-rc1: no basic auth credentials
```

**Comment by mogren** [comment]
@Deshke Can you try pulling from ECR in the same region?
```
docker pull 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1
```

**Comment by Deshke** [comment]
```
 curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq .region -r
eu-west-1
root@ip-172-31-5-122 ~ # docker pull 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1
Error response from daemon: Get https://602401143452.dkr.ecr.eu-west-1.amazonaws.com/v2/amazon-k8s-cni/manifests/v1.6.1-rc1: no basic auth credentials
```

**Comment by nithu0115** [comment]
Hi @Deshke, 

I ran below steps and did not encounter any issues. I believe you haven't authenticated to ECR to pull the image like I am doing below, can you confirm ? 

```
[ec2-user@ip-10-0-1-130 ~]$ aws ecr get-login --registry-id 602401143452 --region eu-west-1 --no-include-email |bash
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/ec2-user/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
You have new mail in /var/spool/mail/ec2-user
[ec2-user@ip-10-0-1-130 ~]$
[ec2-user@ip-10-0-1-130 ~]$
[ec2-user@ip-10-0-1-130 ~]$ docker pull 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1
v1.6.1-rc1: Pulling from amazon-k8s-cni
Digest: sha256:d3f6a1810d6c3f9c2c3711f1e1c1b420d6b1c3a20bb426a406128968e8448507
Status: Downloaded newer image for 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.6.1-rc1
```

**Comment by Deshke** [comment]
* kube nodeup does not do ecr logins
* instance does not have iam credentials to do any ecr calls
* ecr iam is not documented within the vpc-cni project

if ecr credentials are now required, this has to be documented on the release page and the readme

**Comment by mogren** [comment]
The ECR credentials are not required by the CNI, but is something that Kops should handle for you. I created a Kops cluster yesterday using the `--networking amazon-vpc-routed-eni` flag with no problems. 

That said, the worker nodes do require some permissions in EKS and they are documented over at [Amazon EKS worker node IAM role](https://docs.aws.amazon.com/eks/latest/userguide/worker_node_IAM_role.html). The CNI policy is required since it has to attach and detach ENIs and IPs by calling EC2.

**Comment by Deshke** [comment]
cool, ehm, but why is this happening now? i have instances running for 20+ days on v1.5.7 without a problem, newly created spot instances fail with the basic auth missing

**Comment by mogren** [comment]
@Deshke Do the spot instances have the needed EKS worker node policies as well?

**Comment by Deshke** [comment]
they did not and somehow they are able to pull the image. This whole issue is only happening to my eu-west-1 cluster, the kops managed cluster without ANY ecr IAM permissions in us-east-2 is working without a hitch(cluster running v1.15.11).   

So this whole "you need to add ecr iam permissions" is BS as this is only happening in eu-west-1 with the image location being in us-west-2

**Comment by mogren** [comment]
@Deshke Is this still a problem in eu-west-1? Could you provide instance IDs for a working and a not working instance?

**Comment by Deshke** [comment]
yeah sure, i leave a broken unusable ec2 c5.4xlarge instance running for a week to throw money out of the window.

**Comment by iomarcovalente** [comment]
this has just happened to me as well:
```Failed to pull image "602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.7.8": rpc error: code = Unknown desc = Get https://602401143452.dkr.ecr.eu-west-1.amazonaws.com/v2/amazon-k8s-cni/manifests/sha256:b5f170ae39d950f1d14df495486f9b58a35da07cab5e561bce9aa85c8be0bc71: dial tcp 63.32.243.33:443: i/o timeout```
One node out of 20 just reported that issue for the aws-node pod and the node is left unusable

**Comment by tuapuikia** [comment]
Now the problem is wide spread. We are now required to perform docker login in order to pull the image.
```
docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.9.0
Error response from daemon: pull access denied for 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.
```

**Comment by fishyfishphil** [comment]
FYI. Encountering the same issue today. Running from Terraform that works 100% in `ap-south-1` has an issue pulling in `eu-west-1` verified the image URL and tried to pull from other regions too.

**Comment by fishyfishphil** [comment]
> FYI. Encountering the same issue today. Running from Terraform that works 100% in `ap-south-1` has an issue pulling in `eu-west-1` verified the image URL and tried to pull from other regions too.

Fixed this by setting values in our helm chart config:
```yaml
image:
  account: ${aws_container_account}
  region: ${region}
init:
  image:
    account: ${aws_container_account}
    region: ${region}
```

**Comment by WenboDu1228** [comment]
> > FYI. Encountering the same issue today. Running from Terraform that works 100% in `ap-south-1` has an issue pulling in `eu-west-1` verified the image URL and tried to pull from other regions too.
> 
> Fixed this by setting values in our helm chart config:
> 
> ```yaml
> image:
>   account: "${aws_container_account}"
>   region: ${region}
> init:
>   image:
>     account: "${aws_container_account}"
>     region: ${region}
> ```
Hi mate do you mind sharing your solution for this? what is aws_container_account?

**Comment by fishyfishphil** [comment]
@WenboDu1228 You can deduct the account ID needed for your region from the table on [this AWS documentation page](https://docs.aws.amazon.com/eks/latest/userguide/add-ons-images.html).

```
"af-south-1"     = "877085696533"
"ap-east-1"      = "800184023465"
"ap-northeast-1" = "602401143452"
"ap-northeast-2" = "602401143452"
"ap-northeast-3" = "602401143452"
"ap-south-1"     = "602401143452"
"ap-southeast-1" = "602401143452"
"ap-southeast-2" = "602401143452"
"ca-central-1"   = "602401143452"
"cn-north-1"     = "918309763551"
"cn-northwest-1" = "961992271922"
"eu-central-1"   = "602401143452"
"eu-north-1"     = "602401143452"
"eu-south-1"     = "590381155156"
"eu-west-1"      = "602401143452"
"eu-west-2"      = "602401143452"
"eu-west-3"      = "602401143452"
"me-south-1"     = "558608220178"
"sa-east-1"      = "602401143452"
"us-east-1"      = "602401143452"
"us-east-2"      = "602401143452"
"us-gov-east-1"  = "151742754352"
"us-gov-west-1"  = "013241004608"
"us-west-1"      = "602401143452"
"us-west-2"      = "602401143452"
```

**Comment by nathanleyton** [comment]
If you don't use helm fix for me was to specifically log in to the right place like this
`aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 602401143452.dkr.ecr.us-west-2.amazonaws.com`

**Comment by orsenthil** [comment]
Hello @nathanleyton , please do not comment on the close issue. We have also added this information in our troubleshooting docs - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/troubleshooting.md
