### ISSUE TITLE
CNI Metrics Helper is incompatible with K8S 1.16

### ISSUE THREAD

**Issue by tecnobrat** [aws/amazon-vpc-cni-k8s#942]
Hello,

The CNI metrics helper is hardcoded in the manifest files to use `extensions/v1beta1` `apiVersion` which is removed in k8s 1.16.  EKS now supports 1.16.

The recommended version of CNI from the AWS docs is 1.5.7, which is incompatible:

https://github.com/aws/amazon-vpc-cni-k8s/blob/release-1.5.7/config/v1.5/cni-metrics-helper.yaml#L62-L63

Also 1.6 is also incompatible:

https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.6/cni-metrics-helper.yaml#L62-L63

Here are the AWS docs that state these are the manifest files we should be using:

https://docs.aws.amazon.com/eks/latest/userguide/cni-metrics-helper.html

**Comment by mogren** [comment]
@tecnobrat Thanks a lot for reporting, will cherry pick #943 to the branches as well.

**Comment by mogren** [comment]
@tecnobrat The configs pointed to by the docs should be correct now. Please reopen if you notice any issues!

**Comment by tecnobrat** [comment]
@mogren thank you for your quick action on this one, looks like everything is good from my end!
