### ISSUE TITLE
Updating Security Group of the EC2 instance doesn't update Security Group of Network Interfaces created by EKS controller

### ISSUE THREAD

**Issue by anhdat** [aws/amazon-vpc-cni-k8s#964]
**Steps to reproduce:**

- Create new ASG with SG `sg-1`.
- Create a new SG `sg-2`.
- Attach SG `sg-2` to EC2 instances.
- Detach SG `sg-1` from EC2 instances.

**Results:**

- Primary Network Interface `eni-1`'s SG is updated to `sg-2`.
- Network Interfaces created by EKS controller are still using `sg-1`.

**Expectations:**

- All Network Interfaces attached to the node should be updated Security Group to `sg-2`.

**Comment by mogren** [comment]
@anhdat Yes, you are right that they are currently not being updated. We are working on a fix for that in #903

**Comment by mogren** [comment]
A release candidate including a fix for this is available [v1.7.2-rc1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.7.2-rc1)
