### ISSUE TITLE
Cni-metrics-helper reporting wrong cluster_name

### ISSUE THREAD

**Issue by rverma-jm** [aws/amazon-vpc-cni-k8s#973]
Cni metrics-helper is reporting cluster name as k8s-cluster in place of original cluster name. Is there a way to fix this?

**Comment by mogren** [comment]
Hi @rverma-jm,

This was fixed in #856, but that fix is only available in [CNI v1.6.1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.1) and the matching metrics helper.

**Comment by chiefy** [comment]
I'm actually still seeing this using `1.6.3`
