### ISSUE TITLE
`logging before flag.Parse` on every log line on 1.6.1

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#976]
```
 aws-cni-tnf2f aws-cni aws-cni{"level":"INFO","message":"ERROR: logging before flag.Parse: E0515 15:07:27.958866      36 memcache.go:147] couldn't get resource list for external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request","pattern":"unknown"}
```

saw a [few issues](https://github.com/aws/amazon-vpc-cni-k8s/issues?q=is%3Aissue+is%3Aopen+logging+before+flag.Parse) pasting logs that had the same spam :(

**Comment by mogren** [comment]
Hi,

Yes, this is an unfortunate output from an old dependency that pulls in an old version of `client-go`. The task to update this is tracked in #745.

**Comment by grosser** [comment]
can we just call flag.Parse to shut it up ?
