### ISSUE TITLE
HostPort doesn't work

### ISSUE THREAD

**Issue by Cyansilver** [aws/amazon-vpc-cni-k8s#977]
I'm using EKS and set up a hostport for a node group which is in public subnet but when I try to connect to it, it gets Connection refused error

I'm not sure what is the issue?

Thanks

**Comment by mogren** [comment]
Hi @Cyansilver, are you talking about `nodePort`? Are you trying to talk to the right port number? This is set up by Docker and not the CNI. Some more information about the setup would be helpful in trying to figure out what the issue is.

**Comment by Cyansilver** [comment]
hi @mogren,

I'm talking about the `hostPort` . It works after I updated security group manually.

I will close it now, thank you
