### ISSUE TITLE
more detailed documentation for IPAMD Pod IP address cooling period

### ISSUE THREAD

**Issue by saiteja313** [aws/amazon-vpc-cni-k8s#995]
[CNI proposal document](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md#pod-ip-address-cooling-period) explains Pod IP address cooling period. But it doesn't have details on value for 'cooling period'.

Based on `ipamd.go`, [decreaseIPPoolInterval](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L50) is set to 30 seconds, which is passed as an argument to [decreaseIPPool](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/ipamd/ipamd.go#L533) function.

Its gap in documentation. I don't know if this needs to be handled by [awsdocs/amazon-eks-user-guide](https://github.com/awsdocs/amazon-eks-user-guide/tree/master/doc_source) or here. If this is not correct place, please let me know.

**Comment by jayanthvn** [comment]
Merged #1565
